### ISSUE TITLE
rfxcom is connected to device but not working on node-red

### ISSUE THREAD

**Issue by lpt2007** [hassio-addons/addon-node-red#10]
Now I have another problem:

I see my rfxcom but in node red show disconnected. Port is set to /dev/ttyUSB0.

[ 2.134489] usb 1-1.5: new full-speed USB device number 4 using dwc_otg
[ 2.259199] usb 1-1.5: New USB device found, idVendor=0403, idProduct=6001
[ 2.259210] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2.259216] usb 1-1.5: Product: RFXtrx433
[ 2.259222] usb 1-1.5: Manufacturer: RFXCOM
[ 2.259228] usb 1-1.5: SerialNumber: A1XFL0Y9
[ 4.431352] usbcore: registered new interface driver brcmfmac
[ 5.581569] usbcore: registered new interface driver usbserial
[ 5.581670] usbcore: registered new interface driver usbserial_generic
[ 5.581755] usbserial: USB Serial support registered for generic
[ 5.614937] usbcore: registered new interface driver ftdi_sio
[ 5.615046] usbserial: USB Serial support registered for FTDI USB Serial Device
[ 5.615331] ftdi_sio 1-1.5:1.0: FTDI USB Serial Device converter detected
[ 5.615537] usb 1-1.5: Detected FT232RL
[ 5.616439] usb 1-1.5: FTDI USB Serial Device converter now attached to ttyUSB0

**Comment by frenck** [comment]
Seems like the add-on does not have access to the UART devices.

`auto_uart` needs to be added to the Hass.io add-on configuration for this.

Added this to the board to fix to an upcoming release.

**Comment by frenck** [comment]
@lpt2007 Just released `v0.2.1` which contains the fix.

**Comment by lpt2007** [comment]
Thanks a lot for quick solution of problem. :+1: 

I confirm that now rfxcom device is working :)

**Comment by frenck** [comment]
Thank you for letting me know!

![bitmoji](https://render.bitstrips.com/v2/cpanel/359644fb-c5df-4412-9bc7-ae838696ef14-82100c49-8c0a-4ae4-9b04-3a6d3eac9cc2-v1.png?transparent=1&palette=1&width=246)
