### ISSUE TITLE
server-state-changed not working

### ISSUE THREAD

**Issue by neomvll** [hassio-addons/addon-node-red#100]
# Problem/Motivation

>Events monitoring by server-state-changed its not working anymore.

## Expected behavior

> server-state-changed tell me when some entity is changed

## Actual behavior

> nothing happens

## Steps to reproduce

> Just configure a server-state-changed node to any switch and try change the switch in HA dashboard. Nothing happens in node-red since 1 week ago I think

## Proposed changes

> I dont have sure, but maybe this bug was started at last update

npm, node-red and HA updated

**Comment by neomvll** [comment]
api-current-state not working anymore too. A simple test trying get the sun position can reproduce the bug.

inject -> api-current-stat(entity ID: sun.sun) -> output = need return below_horizon or above_horizon, but is returning nothing.

Can anyone confirm this issue please?

PS: all system updated RPi 3b+ raspbian /// home assistant 0.84.6/// node-red 0.19.5: Maintenance Release/// nodejs 10.15.0-1nodesource1 /// npm 1.4.21+ds-2

thanks

**Comment by tjorim** [comment]
Hm, just tested this and working perfectly.
Are you sure you are using this add-on (which only works on Hass.io)?

Most users of this would probably run HassOS.
Also, this add-on is actually bundled with nodejs and npm 8.14.0-r0.

**Comment by neomvll** [comment]
> Hm, just tested this and working perfectly.
> Are you sure you are using this add-on (which only works on Hass.io)?
> 
> Most users of this would probably run HassOS.
> Also, this add-on is actually bundled with nodejs and npm 8.14.0-r0.

Well, all HA nodes worked until last system update. Raspbian, HA, nodejs and npm was update the day, so something is broked.
And yes, I'm using add-on on Hass.io.

![image](https://user-images.githubusercontent.com/10539556/50515686-4cffa680-0a8d-11e9-970d-92ffdc6d1448.png)

![image](https://user-images.githubusercontent.com/10539556/50515730-833d2600-0a8d-11e9-8125-a69474c3df81.png)

![image](https://user-images.githubusercontent.com/10539556/50515763-bb446900-0a8d-11e9-9b96-a409b51b7117.png)

![image](https://user-images.githubusercontent.com/10539556/50515789-df07af00-0a8d-11e9-8727-53a36ccac017.png)

![image](https://user-images.githubusercontent.com/10539556/50515841-3c9bfb80-0a8e-11e9-8f9e-7fc6de8a31c7.png)

**Comment by frenck** [comment]
Add-ons are not available for Raspbian type installs?
Could you clarify a little on how you've installed it?

**Comment by tjorim** [comment]
Correct, assuming you use that node. Please close this issue if you can.
