### ISSUE TITLE
Error: "missing types"

### ISSUE THREAD

**Issue by FamiliaDomsa** [hassio-addons/addon-node-red#1009]
Hello!

Please help with this:

After import flow example, test and delete flow, an error show:

```
Flows stopped due to missing node types.

    - sonos-config
```

in Node-red log is:

[12:27:18] INFO: Starting NGinx...
6 May 12:29:17 - [info] Stopping flows
6 May 12:29:17 - [info] Stopped flows
6 May 12:29:17 - [info] Waiting for missing types to be registered:

**Comment by FamiliaDomsa** [comment]
I delete empty "config" and is ok now

**Comment by frenck** [comment]
I have no idea what sonos-config type is... That is not something this add-on provides.
