### ISSUE TITLE
SSL = false & credential_secret = "<Auto Generated>"

### ISSUE THREAD

**Issue by Hamsterman** [hassio-addons/addon-node-red#1015]
It seems that you will need to change two settings before nodered will work with Home Assistant

SSL = false
credential_secret = "1234" (or what ever you like)

I propose that SSL is set to false as default.
And that credential_secret comes with a autogenerated text.

**Comment by frenck** [comment]
> I propose that SSL is set to false as default.

I propose not. Secure by default, if you don't want to have best practice, than you should do the effort.

> And that credential_secret comes with a autogenerated text.

Add-on cannot do that, which is an upstream limitation.

Nevertheless, thanks for your feedback 👍
