### ISSUE TITLE
node-red-contrib-cast will not update

### ISSUE THREAD

**Issue by Martin-Dolan** [hassio-addons/addon-node-red#102]
# Problem/Motivation
Can't update node-red-contrib-cast from 0.2.1 to 0.2.2
Google home and chromecast features missing in old version
## Expected behavior
It should update
## Actual behavior
received message
"Failed to update: node-red-contrib-cast
Module not locally installed
Check the log for more information"
## Steps to reproduce
Manage Pallette, select node-red-contrib-cast, click update to 0.2.2
## Proposed changes
I read somewhere that this happens as the module was not installed separately from Node red, but part of the Node red package. The problem needs to be fixed as otherwise it requires a total rebuild version of the node red package every time someone updates an included module.  Or no modules should be included (which defeats having a configuration free works out of the box addon like node red.)
I see your dilemma !

**Comment by frenck** [comment]
Nodes that are shipped with the add-on cannot be updated manually, these will be updated for you when a new release of the add-on ships.
