### ISSUE TITLE
No debugging info whatosever

### ISSUE THREAD

**Issue by dedepene** [hassio-addons/addon-node-red#1029]
# Problem/Motivation

All of a sudden all debug information disappeared! All the nodes seem to be working fine but they are not reporting anything within the node red web UI - neither in the right-hand side debug panel nor via status underneath each node.

## Expected behavior

> (What you expected to happen)

## Actual behavior

No apparent trouble anywhere in the logs (e.g. core, supervisor), only these show up in the addon logs:

```

25 May 19:43:25 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
25 May 19:43:27 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
25 May 19:43:34 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
25 May 19:43:38 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
25 May 19:43:43 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)

```

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
## System Health

version | core-2021.5.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 4.19.0-16-amd64
arch | x86_64
timezone | Europe/Sofia

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.12.3
Stage | running
Available Repositories | 890
Installed Repositories | 17

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 20.10.6
disk_total | 108.1 GB
disk_used | 33.9 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), Duck DNS (1.12.5), NGINX Home Assistant SSL proxy (3.0.1), File editor (5.3.0), ESPHome (1.17.1), Mosquitto broker (5.1.1), Node-RED (9.1.1), Home Assistant Google Drive Backup (0.104.3), UniFi Controller (0.20.3), deCONZ (6.9.0), Network UPS Tools (0.7.0), Glances (0.12.1), Portainer (1.5.0), AdGuard Home (4.1.6), Visual Studio Code (3.3.1), iPerf3 (0.1.0), Frigate NVR (1.13), Terminal & SSH (9.1.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 11
views | 13
mode | yaml

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by gterpstra75** [comment]
I have the same issue.

**Comment by dedepene** [comment]
> I have the same issue. I rolled back 1 week and everything worked fine.

no such luck here as I accidentally deleted my snaphots. Did you restore just node red or the entire snapshot?

Also, in my case I can get it properly showing debugging if I reach the web ui through the configured port in a separate browser tab. Did you try this?

**Comment by gterpstra75** [comment]
> > Did you restore just node red or the entire snapshot?

Actually, I am running HA on a VM under Proxmox with automatic backups.    I just restored one of the earlier VMs.   I initially tried the last one but still had the issue so I picked one where NodeRed was at version 9.0.1.   This is one of the many advantages of running HA on Proxmox.

**Comment by dedepene** [comment]
So when I run node-red in a separate browser tab through the config port, I seem to get superhigh CPU usage on account of the nodered container, processes listed here:

![image](https://user-images.githubusercontent.com/6883390/120307774-0bb5f580-c2dc-11eb-881f-50eb61b8f171.png)

Also, this time around I'm getting the supervisor log spammed with these :

```
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:16:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-01 10:17:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
```

**Comment by JackoAmmerlaan** [comment]
I had a smiliair issue socket error and most of the time no debug info. (yes sometimes briefly debug/status was displayed). I solved it partly by entering a port number in the network part of the add-on (used port 1880). after restarting. After wich I direct connect to node red <http://192,168.x.x:1880) logon with your home assistant password. When starting node-red inside home assistant no debug info...

**Comment by dedepene** [comment]
> I had a smiliair issue socket error and most of the time no debug info. (yes sometimes briefly debug/status was displayed). I solved it partly by entering a port number in the network part of the add-on (used port 1880). after restarting. After wich I direct connect to node red <http://192,168.x.x:1880) logon with your home assistant password. When starting node-red inside home assistant no debug info...

This is precisely what I'm doing for the moment - loading node red in a separate browser via the port I opened in config. Still, this is only a workaround, and also started getting these massive CPU overloads on account of the node-red container.

I wonder if anyone is actually looking into this?

**Comment by kwalkington** [comment]
I am doing the same thing.  Direct connect for now.  I've updated everything and even uninstalled and reinstalled node red.

**Comment by squireblackdens** [comment]
Same issue here

**Comment by matbrewer396** [comment]
same problem, on version 9.1.3

**Comment by mamos76** [comment]
updated to version 9.1.4 the problem remains the same

**Comment by nibblerrick** [comment]
Same here, but as far as I take the changelog there isn't a specific update to this issue, more a general update, as different containers of the communityaddons where updated.

**Comment by dedepene** [comment]
I can also confirm 9.1.4 did not fix the issue.

**Comment by Zkaning** [comment]
Have the same problem. Latest config 9.1.4

**Comment by JackoAmmerlaan** [comment]
Issue still exists in 9.14. Also seeing huge CPU spikes and  during the spikes most flows are slow and lagging. 
Running on a nuc celeron j3455

**Comment by th00mas88** [comment]
Yep same issue as everyone else. 

I removed the add-on and folders, rebuilt and have at least the connection. But it failed to run and run debug. The connection and "visual" only worked in the app. The debug doesn't work at all. 

I had a similar issue a while back also, I'm not sure if that was related to update or not. But that absolutely is. It worked until update.

**Comment by JackoAmmerlaan** [comment]
Since I have several Home Assistannt instances running I decided to Install Node Red on my PI. (Same version's as on the NUC). And to my suprise debug and status worked...

**Comment by dedepene** [comment]
> Since I have several Home Assistannt instances running I decided to Install Node Red on my PI. (Same version's as on the NUC). And to my suprise debug and status worked...

So where does that take us? Something else is breaking node-red?

**Comment by gterpstra75** [comment]
Interesting. Is everyone with issues running on a NUC and could this somehow be causing the problem?     My setup is using a NUC running with HA running on a VM under proxmox.    I now have a Synology NAS where I could easily install HA for testing purposes.

**Comment by dedepene** [comment]
> Interesting. Is everyone with issues running on a NUC and could this somehow be causing the problem? My setup is using a NUC running with HA running on a VM under proxmox. I now have a Synology NAS where I could easily install HA for testing purposes.

I'm on bare-metal x64 thin client, no virtualization whatsoever.

**Comment by th00mas88** [comment]
I spent an AGE dealing with,  I had this issue before or similar so tired again and it worked. 

Make a copy of your flows.
uninstall nodered
Remove ALL nodered files - EVERYTHING 
Reboot 
Install nodered again but NOT using the "i use the homeassistant add on"  using the IP and a token.
reconfigure all the dam nodes (im sure there is a faster way but i dont have many flows to deal with)
It's the only way I could get it working at all 

Also in a bizarre way the nodered portal app I can see debug info , but not on chrome

**Comment by JackoAmmerlaan** [comment]
> Interesting. Is everyone with issues running on a NUC and could this somehow be causing the problem? My setup is using a NUC running with HA running on a VM under proxmox. I now have a Synology NAS where I could easily install HA for testing purposes.

I am running W10 with HA in hyper-V.

**Comment by JackoAmmerlaan** [comment]
> I spent an AGE dealing with, I had this issue before or similar so tired again and it worked.
> 
> Make a copy of your flows.
> uninstall nodered
> Remove ALL nodered files - EVERYTHING
> Reboot
> Install nodered again but NOT using the "i use the homeassistant add on" using the IP and a token.
> reconfigure all the dam nodes (im sure there is a faster way but i dont have many flows to deal with)
> It's the only way I could get it working at all
> 
> Also in a bizarre way the nodered portal app I can see debug info , but not on chrome

Will try this solution and post the outcome.

**Comment by JackoAmmerlaan** [comment]
Indeed removing node red also the directory located under config. Reboot and reinstall did the job .... for 5 minutes and then the debug/status info disappeared again. ..

**Comment by th00mas88** [comment]
> Indeed removing node red also the directory located under config. Reboot and reinstall did the job .... for 5 minutes and then the debug/status info disappeared again. ..
> 
> .. A little but too fast... Updated the Home Assistant flow (as described by Th00mas88) and restarted node red.  (debug/status appeared and stayed .. Yess)..
> Also CPU is back to normal again (5-9%) 

It's now been 12 ? 36 hours since I did it and got all working. 

It still seems I'm missing debug in chrome but on the app it's there

**Comment by R5fan** [comment]
Same issue here. Running HAOS under proxmox on x64

**Comment by gterpstra75** [comment]
OK, I used a modified @th00mas88 method to upgrade my Node-Red to the latest version:

- uninstalled node-red
- remove the node-red directory
- installed the latest version of Node-Red with no flows (since the directory was removed)
- Copied flows back into upgraded version 1 flow sheet at a time updating the Home Assistant nodes and deploying after each flow import.

I used the homeassistant addon.    I did this two days ago.

**Comment by kxqcvl** [comment]
I have the same issue since a couple of weeks, running NR 9.2.0 i noticed some flows responding very slow.
When i open NR and looked what caused it i noticed allot "call service" nodes are stuck at sending
![test with and without server token](https://user-images.githubusercontent.com/73292082/125183590-02437580-e218-11eb-85c8-29483cb59b12.jpg)

All ready tried to completley removed node red and install again but now on server with token, worked for an hour or so but things got worse. Now i'm back on "i use the add_on" and couple times a day the delays are serval minutes.

Allready started over twice this weekend but no luck, flows are still lagging cause status keeps beeing stuck at sending so allot of flows don't work anymore.
Any idea?

**Comment by MagicMountainMan** [comment]
I am also experiencing this same issue. I might migrate out of the HASSIO addon for Node Red and just install it as a Docker anyway, but this is kind of a bummer.

**Comment by MagicMountainMan** [comment]
> I had a smiliair issue socket error and most of the time no debug info. (yes sometimes briefly debug/status was displayed). I solved it partly by entering a port number in the network part of the add-on (used port 1880). after restarting. After wich I direct connect to node red <http://192,168.x.x:1880) logon with your home assistant password. When starting node-red inside home assistant no debug info...

This worked for me so this error must have something to do with the way Home Assistant/Node-Red is handling ingress. 

I usually work on Node-Red remotely though via ingress and Nabu Casa so it is still a problem that needs a solution.

**Comment by frenck** [comment]
Is this happening in a specific browser?

**Comment by MagicMountainMan** [comment]
I'm on Chrome, however everything randomly came back. I don't know how to reproduce it now either.

**Comment by frenck** [comment]
If it happens, is there anything in the browser console?

**Comment by frenck** [comment]
missing source maps is fine and would not be able to cause this.

**Comment by MagicMountainMan** [comment]
I figured. If I'm able to reproduce I will post the console log.

**Comment by MagicMountainMan** [comment]
I am getting this error now that I have been able to reproduce the issue:
```
Uncaught Error: cannot call methods on editableList prior to initialization; attempted to call method 'addItem'
    at Function.error (vendor.js:2)
    at HTMLOListElement.<anonymous> (vendor.js:10)
    at Function.each (vendor.js:2)
    at s.fn.init.each (vendor.js:2)
    at s.fn.init.t.fn.<computed> [as editableList] (vendor.js:10)
    at l (red.min.js:16)
    at red.min.js:16
```
as well as
```
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
```
but I'm not sure the second one is relevant at all.

**Comment by MagicMountainMan** [comment]
This issue is happening pretty consistently for me again. I'm on the latest version of Home Assistant and the latest version of this add-on.

**Comment by kxqcvl** [comment]
Here also

**Comment by mattbruman** [comment]
Add me to the list of effected

**Comment by kxqcvl** [comment]
Here also still problems

**Comment by frenck** [comment]
@MagicMountainMan If this:

```
Uncaught Error: cannot call methods on editableList prior to initialization; attempted to call method 'addItem'
    at Function.error (vendor.js:2)
    at HTMLOListElement.<anonymous> (vendor.js:10)
    at Function.each (vendor.js:2)
    at s.fn.init.each (vendor.js:2)
    at s.fn.init.t.fn.<computed> [as editableList] (vendor.js:10)
    at l (red.min.js:16)
    at red.min.js:16
```

is the source/root cause of the issue, it isn't an add-on problem, but it originates from Node-RED itself (or might be induced by one of the Nodes). From an add-on perspective, there is nothing I can do or fix about that.

Add-ons provide a runtime for an application to run in/on. We don't create/maintain/change the application itself.

**Comment by MagicMountainMan** [comment]
@frenck Fair enough, not a huge deal for me since I found other ways to easily access it, thanks for the help!

**Comment by Jpsy** [comment]
Is anybody else here experiencing extreme lags of the HA events:state nodes in conjunction with this debugging info effect? I see delayed reactions of these nodes of up to several 10 seconds after the event while all other parts of the flows seem to work fast as usual.

**Comment by kxqcvl** [comment]
> Is anybody else here experiencing extreme lags of the HA events:state nodes in conjunction with this debugging info problem? I see delayed reactions of these nodes of up to several 10 seconds after the original event happened. All other parts of the flows seem to work fast as usual.

I see delays in every node, when i use the inject node, the flow starts inmediatly but in my browser there are delays of 20-30 seconds.

**Comment by nibblerrick** [comment]
I had this problem, too. Somehow it went now away.
I detected, that I had multiple "Server configurations" for the add-on. I wasn't specificly trying to get this solved, but wanted to do a bit cleaning in my node-red.
After I deleted the multiple server entries and had only one remaining,configured as "using the HA-add-on" - not with a token, All went suddenly to normal.
I have now debugging events again, the states are shown under the nodes which supports that.
It is running for five days now and just to be sure I restarted HomeAssistant 3 times since then and the node-red add-on I think ten times or so. Used the palette to make upgrades of installed nodes and so on.
Running on a ha-supervised install in a VM.

So I thought I share this here, maybe it helps someone or helps to find the root-cause of this odd behaviour.

**Comment by Jpsy** [comment]
What exactly do you mean by «multiple "Server configurations" for the add-on»? The Node Red add-on config in HA supervisor? Can't find any server settings there.

**Comment by macieksonik** [comment]
Confirmed. Multiple servers for add-on are added when importing flows from others as far as I noticed. 

> I had this problem, too. Somehow it went now away. I detected, that I had multiple "Server configurations" for the add-on.

**Comment by nibblerrick** [comment]
> What exactly do you mean by «multiple "Server configurations" for the add-on»? The Node Red add-on config in HA supervisor? Can't find any server settings there.

Haven't been clear, sorry:
In the home-assistant-websocket-nodes you can define the home-assistant-server(s).
I assumed all of the people in this thread use the ha-websocket-nodes. Thinking over it that doesn't have to be, but still seems very likely.

I think it worked a while with multiple server configurations, which where added at my site, too, when I imported other flows.
If so, the problem could be a connection of this add-on and something which changed in the ha-websocket-nodes.
So if this resolves the problem for more people it could be worth to commuicate this behaviour to the ha-websocket-node-author. But I think then more then one or two people need to verify that this is a thing.

@macieksonik Do you confirm that you have multiple configurations or that the problem is gone after "cleaning" the multiple configuration entries?

**Comment by mattbruman** [comment]
Fixed my issue too by deleting extra servers. Maybe this can be fixed in a future build to ignore servers with 0 nodes.

**Comment by macieksonik** [comment]
Yes. 

> @macieksonik Do you confirm that you have multiple configurations or that the problem is gone after "cleaning" the multiple configuration entries?

**Comment by gaussey** [comment]
> What exactly do you mean by «multiple "Server configurations" for the add-on»? The Node Red add-on config in HA supervisor? Can't find any server settings there.

![2F3CBF92-86C0-47AC-9BE5-E051E311ABCA](https://user-images.githubusercontent.com/1004313/147312797-4917bfa1-2d70-4673-bf29-f8941da71abd.jpeg)

He means the servers in the config section of the node-red ui. The numbers next to them denote how many nodes are using that particular server - no idea how I got two and why one is being used over the other.

If you click/tap on them you can delete one but be aware you’ll need at least one and you’ll need to go into each HA node that now has a red triangle above it and select the server

.

**Comment by dedepene** [comment]
still having this issue. It's kinda random now - sometimes if I keep the addon gui open long enough debugging appears all of a sudden. On other occasions it won't appear at all.
