### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'nodered'

### ISSUE THREAD

**Issue by Papester** [hassio-addons/addon-node-red#1038]
# Problem/Motivation

> Receiving error in Home Assistant regarding version key. NodeRed functionality seems to be affected.

## Expected behavior

> NodeRed to operate fully

## Actual behavior

> Multiple issues with NodeRed. Receiving the following error. 2021-06-02 15:21:47 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'nodered'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'nodered'

## Steps to reproduce

> (Run latest version of Home Assistant and NodeRed

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Papester** [comment]
Seems to be related to #1023, using a NUC.

**Comment by sinclairpaul** [comment]
The addon is not a custom integration, which is what is generating the message.

The custom integration is at https://github.com/zachowj/hass-node-red.
