### ISSUE TITLE
Global pattern {{global.<param>}} does not work when used in "events: state" node

### ISSUE THREAD

**Issue by wiiNinja** [hassio-addons/addon-node-red#1040]
# Problem/Motivation

> (Why the issue was filed)

Globals can be declared in settings.js as in this example:
In functionGlobalContext: {
    my_led_light: 'light.led_light'
}
In a "call service" node, this global can be used in the Entity ID field like this: {{global.my_led_light}}. This works. However when the same convention is used in an "events: state" node, it does not work.

## Expected behavior

> (What you expected to happen)

I would hope that the same pattern {{global.<param>}} can be used in any node, but it seems that this only works in some nodes, but not others. 

## Actual behavior

> (What actually happened)

The pattern {{global.<param>}} only works in "call service" nodes, but not "events: state" node.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not an issue with the add-on itself, but with the anode used. Please report this is upstream, thanks!
