### ISSUE TITLE
GYP download error

### ISSUE THREAD

**Issue by Zolric** [hassio-addons/addon-node-red#1044]
# Problem/Motivation
in the log console I have this message and a lot of gyp error.
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v83-linux-arm-musl.tar.gz 

## Expected behavior

the package should be accessible?

## Actual behavior

a 404 error when the contner is starting.

## Steps to reproduce

just start or restart and have a look on the log.

## Proposed changes

update the package? maybe should be good?

**Comment by frenck** [comment]
The addon itself doesn't install or download stuff... could you share your addon configuration?
