### ISSUE TITLE
Load Example Data No Longer Working in Light Domain

### ISSUE THREAD

**Issue by dmccabe79** [hassio-addons/addon-node-red#1047]
# Problem/Motivation

When working with call service nodes, load example data no longer populates anything if using it within the light domain. This is after moving to core-2021.6.4 and OS 6.0. These could be coincidental, but worth mentioning.
## Expected behavior

Expected examples to populate, as usual.

## Actual behavior

After clicking LOAD EXAMPLE DATA, nothing populates.

## Steps to reproduce

Add a call service node, set it up and click load example data.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I think this feature relies on example data in service calls descriptions, which has been dramatically changed in Home Assistant over the last months. I guess the Home Assistant node for node-red hasn't been adopted to that.

That said, from an add-on perspective, there is not much I can do. Add-on wrap existing applications, in this case, Node-RED with a bunch of nodes. Please report this issue with the Home Assistant WebSocket node for Node-RED. If they adjust, the add-on will update to it.

Thanks! 👍
