### ISSUE TITLE
GYP download error for  npm install node-red-contrib-blindcontroller

### ISSUE THREAD

**Issue by rogu22** [hassio-addons/addon-node-red#1049]
node-pre-gyp ERR! cwd /opt/node_modules/bcrypt
node-pre-gyp ERR! node -v v14.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/node_modules/bcrypt/lib/binding --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
> bcrypt@3.0.8 install /opt/node_modules/node-red-admin/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.8/bcrypt_lib-v3.0.8-node-v83-linux-arm-musl.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.8 and node@14.16.1 (node-v83 ABI, musl) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 5.10.17-v7
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/node_modules/node-red-admin/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/opt/node_modules/node-red-admin/node_modules/bcrypt/lib/binding" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /opt/node_modules/node-red-admin/node_modules/bcrypt
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/node-red-admin/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/node_modules/node-red-admin/node_modules/bcrypt/lib/binding --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/node_modules/node-red-admin/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.10.17-v7
node-pre-gyp ERR! command "/usr/bin/node" "/opt/node_modules/node-red-admin/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/node_modules/node-red-admin/node_modules/bcrypt
node-pre-gyp ERR! node -v v14.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/node-red-admin/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/node_modules/node-red-admin/node_modules/bcrypt/lib/binding --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.6 (node_modules/bcrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.8 (node_modules/node-red-admin/node_modules/bcrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
added 5 packages from 5 contributors in 91.677s
106 packages are looking for funding
  run `npm fund` for details
fixed 0 of 9 vulnerabilities in 1458 scanned packages
  9 vulnerabilities required manual review and could not be updated
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1160 (offset 629 lines).
[08:59:56] WARNING: 
[08:59:56] WARNING: The dark_mode option has been deprecated and will be
[08:59:56] WARNING: removed in a future version. Please use the theme
[08:59:56] WARNING: option instead.
[08:59:56] WARNING: 
up to date in 1.081s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:00:02] INFO: Starting Node-RED...
> addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
17 Jun 09:00:08 - [info] 
Welcome to Node-RED
===================
17 Jun 09:00:08 - [info] Node-RED version: v1.3.5
17 Jun 09:00:08 - [info] Node.js  version: v14.16.1
17 Jun 09:00:08 - [info] Linux 5.10.17-v7 arm LE
17 Jun 09:00:12 - [info] Loading palette nodes
17 Jun 09:00:22 - [info] Dashboard version 2.29.1 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
17 Jun 09:00:24 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
17 Jun 09:00:24 - [info] Settings file  : /etc/node-red/config.js
17 Jun 09:00:24 - [info] Context store  : 'default' [module=memory]
17 Jun 09:00:24 - [info] User directory : /config/node-red/
17 Jun 09:00:24 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Jun 09:00:24 - [info] Flows file     : /config/node-red/flows.json
17 Jun 09:00:25 - [info] Server now running at http://127.0.0.1:46836/
17 Jun 09:00:25 - [info] Starting flows
[09:00:25] INFO: Starting NGinx...
17 Jun 09:00:25 - [info] Started flows
17 Jun 09:00:30 - [info] [server:Home Assistant] Connecting to undefined
17 Jun 09:00:30 - [info] [server:Home Assistant] Connected to undefined

credential_secret: 
theme: default
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: true
system_packages: []
npm_packages:
  - npm install node-red-contrib-blindcontroller
init_commands:
  - npm audit fix
dark_mode: true

**Comment by frenck** [comment]
`gyp ERR! stack Error: not found: make`

This packages has dependencies, that you need to add the `system_packages`. In this case, it is missing `make` and probably needs more build tools.

Please consult the upstream package you are trying to install on what build requirements it has.
