### ISSUE TITLE
missing right dependency for node-red-google-notify

### ISSUE THREAD

**Issue by orcema** [hassio-addons/addon-node-red#1052]
# Problem/Motivation

when i installing this node "node-red-google-notify"  the dependency google-tts-api has the wrong version

## Expected behavior

should install dependency google-tts-api@2.0.2  as "latest"

## Actual behavior

only google-tts-api@0.0.4 available as "latest"

## Steps to reproduce

install "node-red-google-notify" from within node-red's  "Manage-palette"

## Proposed changes

should install google-tts-api@2.0.2  as "latest"

**Comment by sinclairpaul** [comment]
It depends on the pre-installed nodes that you can see at https://github.com/hassio-addons/addon-node-red/blob/main/node-red/package.json

With that said, please don't install via the Manage Palette, but rather the npm packages option, which hopefully will help with dependencies https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-npm_packages

**Comment by orcema** [comment]
i added the dependency in the config file 

```
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: false
system_packages: []
npm_packages:
  - node-red-google-notify
init_commands: []
dark_mode: false
log_level: debug`
```

but still the wrong dependency to "google-tts-api"

**Comment by sinclairpaul** [comment]
As you installed from the palette there is likely an entry in package.json, in the config/node-red folder.

Tested personally and I see 2.0.2 installed in /opt/node_modules

```
root@a0d7b954-nodered:/opt/node_modules/google-tts-api$ cat package.json
{
  "_from": "google-tts-api@>=2.0.0",
  "_id": "google-tts-api@2.0.2",
```

**Comment by orcema** [comment]
thanks, worked after i removed the "node-red-google-notify" from the package.json and supressed the package-lock.json

**Comment by orcema** [comment]
what is the technical issue not beeing able to install correctly the node form the palette ?

**Comment by frenck** [comment]
As above listed already: Conflicts.

**Comment by orcema** [comment]
> As above listed already: Conflicts.

What do you mean by conflicts, shouldn’t  work?

**Comment by denisjoshua** [comment]
Hi there, 
is possible to tell me (a newbie) the steps to install the node-red-google-notify
under HassOS node-red please ? 
Thanks a lot

**Comment by frenck** [comment]
> is possible to tell me (a newbie) the steps to install the node-red-google-notify
under HassOS node-red please ?

That is out of scope for the add-on, as it is not an add-on issue.

**Comment by frenck** [comment]
> What do you mean by conflicts, shouldn’t work?

There is a package conflict, if that is resolved, yes, it could work.
Not all packages can work together, in this case, there is an existing package that conflicts with the one you want to add. This means either upstream needs to solve it, or the one installing it. Conflicts do not magically disappear.

**Comment by orcema** [comment]
Usually when you install a node its dependencies are installed in a sub folder named node_modules in order to avoid such conflicts. Why does the node-red add-on not apply this packages isolation by node?
