### ISSUE TITLE
Load example data no longer working

### ISSUE THREAD

**Issue by Mikefila** [hassio-addons/addon-node-red#1056]
# Problem/Motivation

> The load example data no longer works.

## Expected behavior

> Load an example of available data for defined service call
## Actual behavior

> nothing

## Steps to reproduce

> Drag call service node to flow, define domain, define service, click load example data button located below data entry box.

![Screenshot 2021-07-01 124651](https://user-images.githubusercontent.com/74340408/124160637-7472c800-da6a-11eb-9765-9c4d62fc10ac.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
That is unfortunately not an add-on bug, but a bug with the Home Assistant WebSocket Node-RED Node.

You can find that project here:

<https://github.com/zachowj/node-red-contrib-home-assistant-websocket >
