### ISSUE TITLE
After Fresh Install - Error "502: Bad Gateway" on Open Web UI

### ISSUE THREAD

**Issue by KelvinHelmholtz** [hassio-addons/addon-node-red#1059]
# Problem/Motivation
Unable to connect to Node-Red Node-Red AddOn immediately after Fresh Install
Error "502: Bad Gateway" on Open Web UI as well as side link to  http://127.0.0.1:8123/a0d7b954_nodered/dashboard  

## Expected behavior
Expected to see the Node-Red 

## Actual behavior
Error "502: Bad Gateway" on Open Web UI as well as side link to  http://127.0.0.1:8123/a0d7b954_nodered/dashboard  

Also noted: 
Failed to to call /addons/a0d7b954_nodered/stats - 404 Client Error for http+docker://localhost/v1.41/containers/addon_a0d7b954_nodered/json: Not Found ("No such container: addon_a0d7b954_nodered")

And a supervisor log that shows node-red not starting as follows:

21-07-05 03:23:53 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62084 ssl:default [Connect call failed ('172.30.32.1', 62084)]
21-07-05 03:23:54 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_nodered!
21-07-05 03:23:55 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_a0d7b954_nodered application
21-07-05 03:23:56 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/amd64 with version 9.1.4

And yet indeed node-red container is not started as is clear in portainer's docker container list. 

Judging from the most pointed error info above, it appeared to be an ssl issue so I proceeded to disable it with "ssl:false".  Upon restarting the node-red addon worked.

## Steps to reproduce

I basically did a fresh installation of Debian Buster (vanilla + firmware), jq, docker, portainer, home assistant supervisor + AddOns For: file editor, mosquitto, zwavejs2mqtt and then node-red.  Upon setting "credential_secret:", I started the addon and opened the WebUI.  That resulted in the Error 502: Bad Gateway.   

Version Info (docker containers):

ghcr.io/hassio-addons/node-red/amd64:9.1.4
ghcr.io/hassio-addons/zwavejs2mqtt/amd64:0.22.0
homeassistant/amd64-addon-configurator:5.3.1
homeassistant/amd64-addon-mosquitto:6.0.1
ghcr.io/home-assistant/amd64-hassio-multicast:2021.04.0
ghcr.io/home-assistant/amd64-hassio-cli:2021.05.1
ghcr.io/home-assistant/amd64-hassio-audio:2021.04.0
ghcr.io/home-assistant/amd64-hassio-dns:2021.06.0
ghcr.io/home-assistant/qemux86-64-homeassistant:2021.6.6
portainer/portainer

Home Assistant core-2021.6.6
Supervisor-2021.06.6 

## Proposed changes

Would appreciate a bit more about this in the doc (or a link out) for those of us not clear about this topic.

Thanks.  Please feel free to close upon review.

**Comment by frenck** [comment]
```txt
Failed to to call /addons/a0d7b954_nodered/stats - 404 Client Error for http+docker://localhost/v1.41/containers/addon_a0d7b954_nodered/json: Not Found ("No such container: addon_a0d7b954_nodered")
```

Something went wrong @ the HA side of things. You could try running `ha supervisor repair`.

**Comment by KelvinHelmholtz** [comment]
I did, it apparently fixed something ( the logs zipped by quick with the number of auth requests from the nodered add on when I tried a web connect), but the above issue persisted with use ssl: true (and require_ssl: true).  You had already pointed this out in the prior issue to the other reporter so my issue seems redundant on the use of ssl, please consider my issue as a doc enhancement request only.  Much appreciate your work.

**Comment by frenck** [comment]
> but the above issue persisted with use ssl: true (and require_ssl: true). You had already pointed this out in the prior issue to the other reporter so my issue seems redundant on the use of ssl, please consider my issue as a doc

SSL is documented and the logs will provide instructions in case something goes wrong. I'm confused about your suggestion in this case. Could you clarify?

**Comment by KelvinHelmholtz** [comment]
The installation steps suggest:

1. Installing the addon
2. adding the credential_secret
3. starting the node-red addon

Just those by themselves fail on SSL defaults (true) as the other issue also found.  I was merely suggesting that those who have followed the HA advice on a vanilla Debian install have not been alerted to setting up ssl certificates prior to installing the node-red addon.  Therefore for the node-red addon's default on ssl : true surprises the noob user.  If the docs either made ssl set up a pre-req, or pointed to changing the ssl settings to false in the config before starting up vanilla fresh installs, it may help folks.

Fyi, prior to this I had installed node red with HA core on Debian (guess it defaults to no security), that install had not required SSL (though I do agree SSL is a good idea), thus the default ssl on this addon was a surprise.

Below is the addon log which says what you have already said, so my suggestions is simply one for the docs.

Thanks again.

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 9.1.4
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 2021.6.6
 Home Assistant Supervisor: 2021.06.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[04:41:59] FATAL: 
[04:41:59] FATAL: SSL has been enabled using the 'ssl' option,
[04:41:59] FATAL: this requires a SSL certificate file which is
[04:41:59] FATAL: configured using the 'certfile' option in the
[04:41:59] FATAL: add-on configuration.
[04:41:59] FATAL: 
[04:41:59] FATAL: Unfortunately, the file specified in the
[04:41:59] FATAL: 'certfile' option does not exists.
[04:41:59] FATAL: 
[04:41:59] FATAL: Please ensure the certificate file exists and
[04:41:59] FATAL: is placed in the '/ssl/' directory.
[04:41:59] FATAL: 
[04:41:59] FATAL: In case you don't have SSL yet, consider getting
[04:41:59] FATAL: a SSL certificate or setting the 'ssl' option
[04:41:59] FATAL: to 'false' in case you are not planning on using
[04:41:59] FATAL: SSL with this add-on.
[04:41:59] FATAL: 
[04:41:59] FATAL: Check the add-on manual for more information.
[04:41:59] FATAL: 
[cont-init.d] nginx.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.

-----------------------------------

**Comment by KelvinHelmholtz** [comment]
Thank you for reviewing my request.
