### ISSUE TITLE
require_ssl is being ignored when using nginx

### ISSUE THREAD

**Issue by garv3** [hassio-addons/addon-node-red#1061]
# Problem/Motivation

When ssl is enabled and request are made using http to port 1880, they are rejected and "400 Bad Request The plain HTTP request was sent to HTTPS port" is thrown by nginx.

The require_ssl setting is ignored.

## Expected behavior

The request should be forwarded to Node-RED.

## Actual behavior

Nginx returns the error given above.

## Steps to reproduce

Use a Home Assistant OS installation with nginx and Node-RED, enable ssl in the Node-RED settings and perform an HTTP (not HTTPS) request to the url on port 1880.

**Comment by sinclairpaul** [comment]
It looks to be legacy and we should likely remove the option.

It's a config item when Node-Red itself handles SSL termination, which it doesn't in this case as Nginx is performing it.

**Comment by garv3** [comment]
Ah, good to know!
Any suggestions how to configure nginx to allow http for Node-RED but still allow https?

**Comment by frenck** [comment]
> Ah, good to know!
> Any suggestions how to configure nginx to allow http for Node-RED but still allow https?

The only way to do that, is using a reverse proxy.
