### ISSUE TITLE
Malformed JSON in file

### ISSUE THREAD

**Issue by sharpopotamus** [hassio-addons/addon-node-red#1064]
# Problem/Motivation
My Node Red add on was working well, but I've started getting spammed with "Malformed JSON in file" errors. I get this error repeated in the debug log every time I deploy. It's also all over the logs. 

I genuinely can't tell if its effecting my automations. For the most part it's working, but I am getting some odd behavior (some flows are producing random results or doing things that don't make any sense based on my code). 

As far as I can tell, the errors are always associated with entity nodes, this is what shows up in the debug panel:

```
Malformed JSON in file: /config/node-red//node-red-contrib-home-assistant-websocket.json
Unexpected token  in JSON at position 0
```

Here is what shows up in the add on logs (repeated over and over):

```
Unexpected token  in JSON at position 0
    at FileAsync.parse [as deserialize] (<anonymous>)
    at /opt/node_modules/lowdb/adapters/FileAsync.js:41:35
    at Storage$1.getDb (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:2808:14)
    at Storage$1.saveData (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:2822:20)
(node:538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 643)
(node:538) UnhandledPromiseRejectionWarning: SyntaxError: Malformed JSON in file: /config/node-red//node-red-contrib-home-assistant-websocket.json
Unexpected token  in JSON at position 0
    at FileAsync.parse [as deserialize] (<anonymous>)
    at /opt/node_modules/lowdb/adapters/FileAsync.js:41:35
    at Storage$1.getDb (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:2808:14)
    at Storage$1.saveData (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:2822:20)
(node:538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 644)
```

## Expected behavior

No errors.

## Actual behavior

Error messages every time a flow with entity nodes is deployed, then the flows are unreliable in odd and unexplainable ways.

## Steps to reproduce

Run Node Red add on in the latest version of Hassos supervised on an intel NUC, then create new Home Assistant switch and sensor entities using the entity node. 

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Koterak** [comment]
For me there was a bug in mentioned file. On the end I had some strange symbols. Removing it sometimes help. But otherwise you can just rename this file and let node red create new. And problem should disappear

**Comment by frenck** [comment]
This file is created by the `node-red-contrib-home-assistant-websocket` project, it might be worth it  to report this issue with them.

From an add-on perspective, there is not much I can do about this (sorry!)

../Frenck
