### ISSUE TITLE
NodeRed Panel Not Displaying

### ISSUE THREAD

**Issue by GirzzlyAK** [hassio-addons/addon-node-red#1078]
# Problem/Motivation

> HAOS 2021.7.4, Firefox 90 (and Edge). NodeRed no longer appears when using shortcut in Panel in UI. Blank Screen.

## Expected behavior

> NodeRed screen appears

## Actual behavior

> This used to work fine, but haven't used it in a while. No errors in log. Latest version of NodeRed installed and running. Reset Configuration, restarted. Same blank screen. Was also brought up by another user on Discord yesterday.

## Steps to reproduce

> Click NodeRed icon in Panel on UI

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Please look at #1074  to see if applies to you.

Ingress uses a cookie, it appears the latest Firefox updates block it.

**Comment by GirzzlyAK** [comment]
Yes, it must be related. I just turned off all protection in FF and I can see NodeRed again. Will have to go back now and figure out the correct settings to target just NodeRed. Thanks!!

**Comment by sinclairpaul** [comment]
Glad you got it fixed, will close this out as there really isn't anything to be done at this point from the addon.
