### ISSUE TITLE
Node Red entities home assistant does not generate statistical data 

### ISSUE THREAD

**Issue by geelenbert** [hassio-addons/addon-node-red#1081]
# Problem/Motivation

Node red energy entities do not support the creation of statistical data.

I have modbus meter that I use for measuring the Solar en mains energy from my power grid. 
Nodered is used to read these meters, parse the data and write them to Home assistent entities. 
![image](https://user-images.githubusercontent.com/91923/128503455-5b9179a2-b9e9-4112-a286-b7e412c0a15a.png)

Imported energy:
![image](https://user-images.githubusercontent.com/91923/128503003-604d7746-4178-426a-afdb-bdc733f882ac.png)
![image](https://user-images.githubusercontent.com/91923/128503498-f89695fa-1ae7-43af-b7a3-3efffc63fc19.png)

Exported energy:
![image](https://user-images.githubusercontent.com/91923/128503074-6a569669-a482-44d0-af64-263b10e452bd.png)
![image](https://user-images.githubusercontent.com/91923/128503522-ef4eea49-431a-4a96-ab41-309eaca92dc5.png)

Solar Imported energy
![image](https://user-images.githubusercontent.com/91923/128503139-584bec12-06ad-44b4-b798-3f1eaf63fb34.png)
![image](https://user-images.githubusercontent.com/91923/128503548-664fa981-efb3-4fb5-960c-5729c509ecd7.png)

## Expected behavior

Be able to select these meters for the Energy Dashboard.

## Actual behavior

These meters are not available as meters for the energy dashboard.

## Steps to reproduce

Creating entities in node red with a device class that supports long term statistics. 

## Proposed changes

Probably need some extra paramters to configure the home assistant device class according to this post:
https://www.home-assistant.io/more-info/statistics/

**Comment by Koterak** [comment]
Just set in "attribute key" 

![obraz_2021-08-07_193217](https://user-images.githubusercontent.com/35494920/128608995-ece2da44-223f-4260-a3bb-1806f899d6d4.png)

"last reset" I set to: 1970-01-01T00:00:13.515526+00:00 

And for me it is working.

**Comment by geelenbert** [comment]
I needed to add both state_class and last_reset to make it work. 

state_class:measurement
Last_reset:NULL

That worked!

inwas under the impression i needed the to be in the home assistant config (optional) part. 

All works as expexted!
