### ISSUE TITLE
Enable Projects / Git within Node red 

### ISSUE THREAD

**Issue by mvillarejo** [hassio-addons/addon-node-red#109]
# Problem/Motivation
New feature that might be useful for other people.

## Expected behavior
Use projects and a git repository with Node Red.
 
## Actual behavior
it's not enabled

## Steps to reproduce
How to enable Node Red projects and include a git repository can be found here:
https://nodered.org/docs/user-guide/projects/

## Proposed changes
The idea behind this feature request is that I believe it might be useful to enable project feature within Node Red so the configuration can be saved into a git repository, in case you want to move into different branches / versions or just to identify what was previously changed is something useful.

Great addon!!

<blockquote><div><strong><a href="https://nodered.org/docs/user-guide/projects/">Node-RED : Projects</a></strong></div></blockquote>

**Comment by frenck** [comment]
This feature has been part of this add-on since the first release.
Thanks.
