### ISSUE TITLE
OpenCV support

### ISSUE THREAD

**Issue by dcmartin** [hassio-addons/addon-node-red#11]
# Problem/Motivation

Trying to install NPM package for OpenCV and failing

## Expected behavior

Changed configuration to include: "npm_packages": [ "node-red-contrib-opencv" ], which does initiate additional activity on the backend.

## Actual behavior

Log file:

> opencv@6.0.0 install /opt/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@8.9.3 (node-v57 ABI, musl) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.13.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-x64/opencv.node" "--module_name=opencv" "--module_path=/opt/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-x64"
gyp ERR! cwd /opt/node_modules/opencv
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-x64/opencv.node --module_name=opencv --module_path=/opt/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-x64' (1)

## Steps to reproduce

Add to configuration as above.

## Proposed changes
No idea.

<blockquote></blockquote>

**Comment by frenck** [comment]
`Can't find Python executable "python"`

So, yeah... it is telling you what to do ;)
