### ISSUE TITLE
Node-red dashboards are not loading after the upgrade. Lots of failed socket.io calls.

### ISSUE THREAD

**Issue by niirvana-git** [hassio-addons/addon-node-red#1104]
# Problem/Motivation

After I upgraded Home assistant to the latest version (2021.8.8) and Node-red add-on to 10.0.0 version, my Node-red dashboards are not loading anymore. There's only an empty page. I have several dashboards in Node-red that I have added to Home assistant Lovelace dashboard as tabs (iFrame). On my Lovelace dashboard, I also have one IFrame card that should be showing one of the Node-red dashboards. I'm using this kind of URLs ,"https://my-external-address.duckdns.org/endpoint/ui/#!/1", in IFrames. Everything has been working great for over a year until the upgrade.

When I review developer tools (F12 in Chrome) I can see that there are lot of calls (socket.io) happening all the time. Some of these calls are failing (status 400), but some are also ok (status 200). One example request: "https://my-external-address.duckdns.org/endpoint/ui/socket.io/?EIO=3&transport=polling&t=Nk7y6OT&sid=co_03HXXdWMUGEymAAAc".

If I try to open dashboards in incognito mode in Chrome, everything works. If I clear cache in Chrome, I can also access the dashboard. However, if I try to access dashboards in home assistant , there's only an empty page, and after that page isn't anymore opening in Chrome either (in incognito it's still ok however).

It seems that this issue has been happening in the past as well, but is now back for some reason Please see [this issue](https://github.com/hassio-addons/addon-node-red/issues/194). It seems exactly the same.

I'm also using Nginx Proxy Manager where, in addition, to basic stuff, I have defined custom location for node-red "endpoint/ui". Everything has been working for over a year already, so I assume that Nginx configurations are ok.

## Expected behavior

I'm expecting dashboards to load without errors as before the upgrade.

## Actual behavior

Page is empty and there are lots of socket.io calls happening and failing in the background.

## Steps to reproduce

Upgrade to latest versions. Create Node-red dashboard. Add it to Home assistant dashboard as an IFrame. Try to access.

## Proposed changes

No idea why this is happening.

**Comment by niirvana-git** [comment]
I upgraded to the latest version, but it didn't change anything. I can only access Node-red dashboards in incognito mode in Chrome. Otherwise it's just a blank page and lot's of failed calls happening in the background (network/dev tools).

**Comment by Thomaswaldick** [comment]
> I upgraded to the latest version, but it didn't change anything. I can only access Node-red dashboards in incognito mode in Chrome. Otherwise it's just a blank page and lot's of failed calls happening in the background (network/dev tools).

Appreciate the Chrome recommendation! I'm also running into a similar issue. Node-Red dashboard is not able to load on firefox either locally or over the internet. I was able to get it to load on Google Chrome. The first part of the error message on Firefox was 

"The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range."

**Comment by niirvana-git** [comment]
I'm quite surprised that no one else has commented anything to this issue. I'm wondering if this is the right place for this issue? Any other suggestions?

I believe the issue must be in Node-red/this addon or in home assistant itself. I can still access the dashboards in incognito mode in Chrome and also without incognito when clearing the cache. When I try to do it home assistant, it doesn't work. Something is saved to some persistent state/cache that is causing loading dashboards to fail.

**Comment by niirvana-git** [comment]
Still not working.

**Comment by niirvana-git** [comment]
Upgraded to latest version. Still not working.

**Comment by niirvana-git** [comment]
Not working
