### ISSUE TITLE
SSL enabled by default without certs, breaking new installs

### ISSUE THREAD

**Issue by deviantintegral** [hassio-addons/addon-node-red#1112]
# Problem/Motivation

In the default configuration, SSL is enabled, but since there's no certificate the addon fails to start:

https://github.com/hassio-addons/addon-node-red/blob/main/node-red/config.json#L42-L44

## Expected behavior

The addon should start with a default configuration that only has a `credential_secret` set.

## Actual behavior

I also had to turn the SSL option off.

## Steps to reproduce

1. Install node red addon 10.0.0.
2. Set `credential_secret`
3. Try to start the addon, but it errors out due to the invalid configuration change.

## Proposed changes

Either update the docs with whatever SSL configuration is required, or update the default configuration to not enable SSL by default.

**Comment by sinclairpaul** [comment]
The documentation states what the SSL option does https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-ssl

Also if you start the addon with SSL enabled, and no SSL certificate, the addon logs print a message telling you the issue.

What additions would you propose for this?, I would suggest doing them via a PR.

**Comment by frenck** [comment]
This is the correct behavior.
Could closing the issue

**Comment by deviantintegral** [comment]
Well, it's not secure if the container doesn't start :D

What about provisioning a self-signed cert instead?

**Comment by frenck** [comment]
That is not an add-on responsibility
