### ISSUE TITLE
Just install home assistant and installed Node-red but it will not start 16-09-21

### ISSUE THREAD

**Issue by Bob1946** [hassio-addons/addon-node-red#1115]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Read the documentation (and fill in the issue report).

**Comment by frenck** [comment]
Closing issue, as it has no content
