### ISSUE TITLE
copy state of a variable from node red to sensor virtual home assistant.

### ISSUE THREAD

**Issue by Whastie** [hassio-addons/addon-node-red#1117]
I have the node network communicating with a siemens plc by s7 protocol.

I can read values from a HA entity and through node-red pass it to plc s7.
![envio final](https://user-images.githubusercontent.com/89639919/133862782-99d5cdf5-05ff-400a-9f69-e353e2de9c3e.JPG)
![salida ha](https://user-images.githubusercontent.com/89639919/133862784-4f8012ab-4cc9-47ab-9842-7760e1152027.JPG)
![in_out_plc](https://user-images.githubusercontent.com/89639919/133862785-4a6bca4f-f0e3-41d1-92e6-ec736237cc72.JPG)
![variable plc](https://user-images.githubusercontent.com/89639919/133862786-aa4dbbd1-74c2-4b46-b0b5-71fa4bc04a7f.JPG)

But I don't know how to pass the state of a node-red variable to a virtual sensor or HA register that I can then use in HA automations.
Can you help me?
Thank you

**Comment by sinclairpaul** [comment]
We use GitHub for issue tracking not really configuration advice, I would suggest you ask for help on the Home Assistant Forums or Discord.

Thanks

**Comment by Whastie** [comment]
Hi,

I have put all the data to make the full explanation.

I just want help to know how through node-red to transfer the value of the state of a numerical variable to HA.

with what function of node red and how is it usually done?
