### ISSUE TITLE
Nodered API errors w/ HASS.IO

### ISSUE THREAD

**Issue by inputd** [hassio-addons/addon-node-red#112]
Hass.io running 0.84.6, and node-red 1.2.3 on a pi B.

Node-red appears to connect just fine with the "events:state" node, and reflects the time they last changed. It also seems to have no issue with the "current state" node. However, the "call service" nodes do not work.

In the node-red GUI, the error is 
`"API Error at: (date/time)"`

In the node-red module log, the error is:
```
7 Jan 13:07:42 - [warn] [api-call-service:Turn On Light] Error calling service, home assistant api error
7 Jan 13:07:42 - [error] [api-call-service:Turn On Light] Error calling service, home assistant api error
```

And in the system monitor, the following error:
`19-01-07 21:07:39 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT`

**Comment by lostage** [comment]
@inputd Curious what you did to fix your issue? I'm having the same issue with a different service.

**Comment by inputd** [comment]
Nodered in a recent update changed the call service node so that entity_id has its own field, and you don't need to paste it in the "data" field in YAML format. I went through the call service nodes, cleared the data field, and added entity ID's to the specific field where they belong

**Comment by lostage** [comment]
Thanks! That's exactly what I needed to do.

**Comment by SamJongenelen** [comment]
Hmm, no fix for my flow, using HASSIO + node red on rPI.
The nodes show 'not connected'.  Hassio WebSockets API tells me that the message is not well formatted, still?


![image](https://user-images.githubusercontent.com/3382443/51740290-e4a7e300-2093-11e9-873d-5000dec19672.png)

one of my call service nodes (the most simple; light turn_off)
![image](https://user-images.githubusercontent.com/3382443/51739967-1b312e00-2093-11e9-8ad8-baf384ce9c1d.png)



The nodered log has:
25 Jan 11:19:08 - [info] Starting flows
25 Jan 11:19:08 - [debug] red/nodes/flows.start : starting flow : global
25 Jan 11:19:08 - [debug] red/nodes/flows.start : starting flow : a4cd83c4.9cdf5
25 Jan 11:19:08 - [debug] [server:Home Assistant] instantiated node, name: Home Assistant
25 Jan 11:19:08 - [debug] [api-call-service:5abd8949.ddf5a8] instantiated node, name: undefined
25 Jan 11:19:08 - [debug] [api-call-service:2ee38cc0.8e5cd4] instantiated node, name: undefined
25 Jan 11:19:08 - [info] Started flows
**25 Jan 11:19:08 - [warn] [api-call-service:2ee38cc0.8e5cd4] Call-Service attempted without connection to server.**

Hassio system log shows:
![image](https://user-images.githubusercontent.com/3382443/51740466-68fa6600-2094-11e9-806a-6f2ad23e84fe.png)


Is this the same/similar issue? Other HA node red connections are connected

my simple flow:
`[{"id":"a4cd83c4.9cdf5","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"5abd8949.ddf5a8","type":"api-call-service","z":"a4cd83c4.9cdf5","name":"","server":"181266bf.748f49","service_domain":"","service":"","data":"","render_data":false,"mergecontext":"","output_location":"payload","output_location_type":"msg","x":350,"y":240,"wires":[["14c5e451.effd6c"]]},{"id":"1be21985.112396","type":"inject","z":"a4cd83c4.9cdf5","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":70,"y":380,"wires":[["2ee38cc0.8e5cd4","45396914.814eb8"]]},{"id":"14c5e451.effd6c","type":"debug","z":"a4cd83c4.9cdf5","name":"test","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":630,"y":220,"wires":[]},{"id":"45396914.814eb8","type":"change","z":"a4cd83c4.9cdf5","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"domain\":\"notify\",\"service\":\"android_unnamed_device\",\"data\":{\"message\":\"test\"}}","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":100,"y":240,"wires":[["ae2e9139.11349","5abd8949.ddf5a8"]]},{"id":"ae2e9139.11349","type":"debug","z":"a4cd83c4.9cdf5","name":"payload debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":220,"y":160,"wires":[]},{"id":"2ee38cc0.8e5cd4","type":"api-call-service","z":"a4cd83c4.9cdf5","name":"","server":"181266bf.748f49","service_domain":"light","service":"turn_off","data":"{\"entity_id\":\"light.color_hanglamp_tv\"}","render_data":false,"mergecontext":"","output_location":"payload","output_location_type":"msg","x":370,"y":360,"wires":[[]]},{"id":"181266bf.748f49","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open"}]
`

**Comment by SamJongenelen** [comment]
I found the issue. On publish, the connection to hassio is made.
This takes about five seconds. 
However, the Inject node fires before this! Setting the Inject node to wat five seconds and then fire solves my problem
