### ISSUE TITLE
Theme broken

### ISSUE THREAD

**Issue by poelzi** [hassio-addons/addon-node-red#1123]
# Problem/Motivation

The extension always had a nice dark look. I guess since some update, everything is white now. There seems to be themes in node packages, but they do not show up in the module install window

## Expected behavior

Old theme

## Actual behavior

Some whitish default theme now

## Steps to reproduce

Upgrade from older 2.x version to curren

**Comment by frenck** [comment]
I guess you have missed / didn't read the release notes...

<https://github.com/hassio-addons/addon-node-red/releases/tag/v9.0.0>

Which was removed fully in 10.0.0
