### ISSUE TITLE
NodeRed gets stuck on Loading Plugins

### ISSUE THREAD

**Issue by derekcfoley** [hassio-addons/addon-node-red#1127]
# Problem/Motivation

I can't seem to get NodeRed to load in my browser, the load plugins section freezes. I've tried rebooting the pi, and it doesn't help, same behaviour. Also tried restarting the add-on too.

## Expected behavior

> Node Red loading for use! 

## Actual behavior

> Stops during "loading plugins"

## Steps to reproduce

> I am using the latest versions of HA 
HA core: core-2021.9.7
Supervisor: supervisor-2021.09.4
Host: Home Assistant OS 6.4
NodeRed: Current version: 10.0.1

I am running a raspberry Pi 4
To see this behaviour, I open HA in a browser (local IP) and click "Node-Red" in the side menu.,,

![image](https://user-images.githubusercontent.com/25664126/135256538-195e5f18-5ad4-4774-9a48-80fb01f9a8e5.png)

I tried a system restart (from server menu) in Configuration. Same - freeze on "loading plugins".

I then tried to resolve it via the "Configuration menu" in HA, then the Integration panel, but found the context menu "Reload" there did nothing to help... 

![image](https://user-images.githubusercontent.com/25664126/135257646-66be52ff-35f6-4294-bd44-57c2496e77aa.png)

I found the only way to get it working again - is to go to Supervisor menu in HA, and click the restart button there... 
![image](https://user-images.githubusercontent.com/25664126/135257340-eb31fc18-e4e6-468a-8a45-6f1ead687d8f.png)

**Comment by frenck** [comment]
Anything in the logs?
