### ISSUE TITLE
best way to add new nodes

### ISSUE THREAD

**Issue by fragolinux** [hassio-addons/addon-node-red#113]
which is the best way to add new nodes? Via palette, after addon installs, or via the addon config json page, before starting the addon? What differences are there?

**Comment by frenck** [comment]
Doesn't matter that much, the reason why the add-on provides the configuration option: Allows you to add any NPM package (even when it isn't a Node-RED node). There are multiple use-cases for this.

**Comment by fragolinux** [comment]
> Doesn't matter that much, the reason why the add-on provides the configuration option: Allows you to add any NPM package (even when it isn't a Node-RED node). There are multiple use-cases for this.

i know, my question was really more about the addon startup time, i've read that adding too much nodes to the json config page could make addon startup time longer, i was thinking if adding them via palette can reduce this time... i mean, the addon installed ones are installed on every startup, for example, on the contrary of the palette ones?
thanks
