### ISSUE TITLE
502 BAD GATEWAY after Upload new release

### ISSUE THREAD

**Issue by brutus6506** [hassio-addons/addon-node-red#1130]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by brutus6506** [comment]
hi, I apologize for my English but I'm not really a top, I have a problem with Nodered and I can't solve it, after updating the message 502 BAD GATEWAY appears.
I hope there is a solution because all my automations are linked to its operation
Thank you so much

**Comment by frenck** [comment]
Please provide logs and reproduction scenarios.

Thanks
