### ISSUE TITLE
Fail to connect to devices when loghost is blank

### ISSUE THREAD

**Issue by dsduarte** [hassio-addons/addon-node-red#1137]
# Problem/Motivation

After send the command loghost "" TasmoAdmin can not recognize the device.

## Expected behavior

Recognize devices

## Actual behavior

After send the command loghost "" TasmoAdmin can not recognize the device.

## Steps to reproduce

O command line from TasmoAdmin or from console on Tasmota device, send loghost ""

## Proposed changes

I Don't know what needs to be done to solve.

**Comment by frenck** [comment]
> After send the command loghost "" TasmoAdmin can not recognize the device.

This is the Node-RED add-on issue tracker, seems this issue is misplaced.
