### ISSUE TITLE
10.0.1 fails to work in home assistant

### ISSUE THREAD

**Issue by donnievawter** [hassio-addons/addon-node-red#1138]
# Problem/Motivation

> (Why the issue was filed)
10.0.1 doesn't load in home assistant
## Expected behavior
I expected it to load
> (What you expected to happen)

## Actual behavior
doesn't load
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by MrSnoop** [comment]
which browser do you use? I got the experience that it doesn't work in firefox in ingres. In chrome it loads on my end.

**Comment by donnievawter** [comment]
I use Edge on Mac. I restored to the earlier version so I don't have any logs from the update attempt.  I will be out of pocket the rest of the weekend but will retry the update the first of the week.

**Comment by tinglis1** [comment]
I had the same issue. I rolled back to 10.0.0 and it is working again.
I didn't keep a copy of the log but mine was hundred of lines saying something like "Trying to connect to Home Assistant". Is there a way to activate a debug log?

I run HA as a VM on unRAID. I had tried from many different browers types and OS but it made no difference. NR was executing at all.
