### ISSUE TITLE
Error starting NodeRed

### ISSUE THREAD

**Issue by lamboid** [hassio-addons/addon-node-red#114]
Running Hass.io & HA 8.50
NodeRed 1.2.3

Errors during startup so not able to get to the url.

Updated HASSio to 8.50 and added a reboot. docker image is running but stuck in a startup loop with the following error repeating constantly.

`10 Jan 22:50:45 - [info] Server now running at http://127.0.0.1:1880/
10 Jan 22:50:46 - [info] Starting flows
10 Jan 22:50:46 - [info] Started flows
10 Jan 22:50:46 - [red] Uncaught Exception:
10 Jan 22:50:46 - Error: bind EADDRINUSE 0.0.0.0:1900
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-10T22_50_46_214Z-debug.log

> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

10 Jan 22:50:48 - [info] 

Welcome to Node-RED
===================

10 Jan 22:50:48 - [info] Node-RED version: v0.19.5
10 Jan 22:50:48 - [info] Node.js  version: v8.14.0`

Any ideas on the issue or what to try?

**Comment by frenck** [comment]
The issue: `Error: bind EADDRINUSE 0.0.0.0:1900`

Port 1900 is already in use by something else. Either find out what uses it and disable that (or change the port).
