### ISSUE TITLE
Dashboard doesn't load in Lovelace (but it does from Node-Red if SSL is disabled)

### ISSUE THREAD

**Issue by DrDuk** [hassio-addons/addon-node-red#1150]
# Problem/Motivation
With SSL turned on in configuration I received ERR_SSL_VERSION_OR_CIPHER_MISMATCH from the browser when opening the dashboard from nodered. Turning off SSL and using username/password (ssl: false), I can launch the dashboard from nodered but the same URL in Lovelace results in a blank screen.

No logs are generated by calling the dashboard from nodered or lovelace so I cannot see where the problem is (I've looked in the nodered and supervisor logs but can't find anything).

> (Why the issue was filed)
I was using Lovelace dashboad buttons to control devices but this no longer workds

## Expected behavior

> (What you expected to happen)
To see the dashboard in Lovelace

## Actual behavior

> (What actually happened)
I only see a blank tile

## Steps to reproduce

> (How can someone else make/see it happen)
See above

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

It seems that SSL and the Lovelace integration has broken.

**Comment by alanmasu** [comment]
Hi @DrDuk, I'm reach the same problem as you, but I'm quite new in HA and than I don't understand everything, so can you teach me to install this addon please?

Thanks in advance, 
Alan

**Comment by DrDuk** [comment]
If you are running HA supervised (i.e. you can see "Supervisor" down the left side) then install the addon https://github.com/regevbr/addon-node-red-dashboard from within the supervisor.  You wil need to add the respository from the Add-on store (click the three dots at the top and click on "Repositories", paste the link directly under "Add").  This add-on generates its own URL to view the Nodered dashboard without the failures.  Use this URL in a Lovelace card.  I don't know how to fix this when you are not running Supervisor.
