### ISSUE TITLE
Node red to Hassio connection issue 

### ISSUE THREAD

**Issue by SamJongenelen** [hassio-addons/addon-node-red#117]
# Problem/Motivation
Im trying to call service from node red to hassio, but getting 'no connection to the server', whilst trying to execute a call service ' notify'.
I've test the call service to be working from the HomeAssistant dev tools and this works. 
I'm using HASSio Pi-hole as primary DNS. Therefor I've tried using the IP address of my rPi instead of hostname  ' hassio' . The connection to the Hassio WebSockets seems to be working but still node red node  _call service_ fails

## Expected behavior

Connect to hassio using long lived API token, execute _call service_ on Home assistant / hassio.

## Actual behavior

API-CALL-SERVICE fails.

> 24 Jan 12:28:47 - [info] Started flows
> 24 Jan 12:28:47 - [info] [mqtt-broker:87b4c6e9.bf3768] Connected to broker: NodeRed@mqtt://localhost:1883
> 24 Jan **12:28:47** - [warn] [api-call-service:notify doucheraam open] Call-Service attempted without connection to server.
> 24 Jan **12:28:51 -** [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant

API token works:

> 19-01-24 11:56:46 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
> 19-01-24 11:56:51 INFO (MainThread) [hassio.auth] Auth request from a0d7b954_nodered for root
> 19-01-24 11:56:52 INFO (MainThread) [hassio.auth] Success login from root

## Steps to reproduce

* one rPI 2 
* using duckdns service
* using non ssl at the moment
* using the API token route at the moment
* hassio docker image on rpi
* pihole 
* other HA nodes (state) works fine.

## Proposed changes
What: Allow more time for the WS to connect before giving up the _call service_ node
Why: 
I noticed that the WebSocket succes log occurs 5 seconds after the API-CALL-SERVICE fail
It could be possible that the HASSIO WebSocket _connect_ takes too long for the api-call-service to complete? I'm running on a fairly weak rPi2 model B.

**Comment by SamJongenelen** [comment]
I've started modifying because the OOB settings are not working. :)

**Comment by frenck** [comment]
Multiple things not correct / according to manuals/instructions in here:

> I'm using HASSio Pi-hole as primary DNS

If you use Pi-hole (or AdGuard or DNSMasq) add-on, you must configure your device to have a static IP address (not to be confused with DHCP reservation) AND static external DNS. In no way, your Hass.io device may become a client of itself.

> Allow more time for the WS to connect before giving up the call service node

That is not an add-on issue/feature request. Add-on merely wraps existing software. Please report the issue on the upstream projects. 

> I've started modifying because the OOB settings are not working

See above, nevertheless, @timmo001 is right. Use the ☑️ checkbox "I use Hass.io", working around that, will drop you in a deeper rabithole.

**Comment by SamJongenelen** [comment]
Well, of course my primary DNS server (pi-hole) has a static address. Also, the DNS lookup for the duckdns address is correct. Port forwarding as well, of course. 

In my opinion, even if the ' I use hassio' should work (which it doesn't), the functionality to use the token API should work as well. I disagree with closing the bug. There is no way for me to continue debugging, as I cannot obtain any more info on this :(

**Comment by frenck** [comment]
As I mentioned in my previous reply: Your proposed change is not fixable within this project @SamJongenelen.

Add-ons wrap existing software and does not modify it. Please submit your request to the appropriate upstream project. 

Secondly, I provided 2 pointers on where to look locally (besides pointing you to the upstream projects).

Not sure what more you want from me at this point.

Thanks.

**Comment by SamJongenelen** [comment]
Well, i would be helped greatly if you could point me towards where to look (which projects? do you mean the node-red node _home-assistant_ or something?)

**Comment by frenck** [comment]
@SamJongenelen This is the upstream project for the Home Assistant Websocket node:

https://github.com/zachowj/node-red-contrib-home-assistant-websocket

**Comment by SamJongenelen** [comment]
Thank you, I will ask there
