### ISSUE TITLE
99-message.sh -> Oops! Something went wrong.

### ISSUE THREAD

**Issue by Psike2k11** [hassio-addons/addon-node-red#1170]
Hello I am getting the following error.

I have tried what I could from other forums and other sources to solve the problem, unfortunately without success.

1. credential_secret is set
2. SSL disabled
2. generate more information via log: trace
3. checking general HA log

But nothing has even remotely helped, what else can I do?

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 2da19ba
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (armv7 / tinker)
 Home Assistant Core: 2021.11.1
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
/usr/bin/tempio: line 1: Not: command not found
[cont-init.d] nginx.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/140934060-fa2b6bc8-c8e4-4f23-b086-092f12f7bc88.png)


You are running the development version? Why?

**Comment by Psike2k11** [comment]
Okay my fault, I'm dumb or unaware that the Addon-Store is Split in "Normal" & "Edge", i switched to the latest relase Version. I'm very Sorry, but Thankful ;).
