### ISSUE TITLE
Issue with context storage

### ISSUE THREAD

**Issue by pjgrun** [hassio-addons/addon-node-red#1174]
# Problem/Motivation

I am using the possibility of persistent context data storage on localfilesystem by including following lines in settings.js:
 

```
 contextStorage: {
     default: {
         module: "localfilesystem"
     }
  },

```

After upgrading to nodered addon V:10.1.0, I can see in the logs:

![image](https://user-images.githubusercontent.com/89712102/141460743-af3b27af-c490-4499-bd4f-d5d58118f226.png)

It says that persistent storage method is not specified, but from my testing, it appears that persistent data storage is really working, as expected from configuration settings and despite the log message.

## Expected behavior

If persistent data storage is specified and working as per configuration settings, the log message should reflect this and not say that it is disabled.

## Actual behavior

Log Message says that persistent storage method is not specified, while such method is correctly specified in settings.js and verified to be working ok.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Correct log message for persistent storage method

**Comment by frenck** [comment]
This might be caused by not setting the base directory for storing data. The default is `~/.node-red`, which is not a persistent storage location for the container (meaning that data would be lost each restart).

**Comment by pjgrun** [comment]
The fact is that the data is preserved even after Hard Reset. I have not provided a definition for base directory, so assume it is using the default. On the other side, I can see that files for persistent data storage have been created in folder: /config/node-red/context/global/ and are kept updated as per file date observed.

**Comment by frenck** [comment]
In that case, there is a bug with that, but that is a whole other thing.
I have no clue what could cause this.

**Comment by pjgrun** [comment]
You mean it is a bug that the files are stored in folder  /config/node-red/context/ or the bug is that an incorrect log message is shown?

**Comment by hklages** [comment]
I am also using context storage and just updated to 10.1.0. In my logfile there isnt any "no persistant .." entry as mentioned above. 

My settings.js is slightly different. Maybe you give it a try. 
```contextStorage: {
    default: {
      module:"localfilesystem",
      config: {
      }
    }
  },
```

**Comment by hklages** [comment]
`\config\node-red\context` 
Exactly as in the "Reference" link described. 

 
![dirctories context](https://user-images.githubusercontent.com/17273119/142436636-27ce558d-29c6-4fdc-bdef-f4b0e95e748b.png)

**Comment by pjgrun** [comment]
Yes, "\config\node-red\context" is the same location as in my system. In the "Reference" link it says: "~/.node-red/context". I am unable to match this to "\config\node-red\context"
Ultimately, my concern is if the location in use could be not a persistent storage location for the container (meaning that data would be lost each restart), as advised by @frenck above.

**Comment by hklages** [comment]
Please have a look at your settings.js file. You can see the following comment: 
` * - userDir (is set fixed to `/config/node-red`)`

In general the user directory is set to `Default: the user directory, ~/.node-red`  but due to the modified settings file, for Home Assistant it is `/config/node-red` which as a subdirectory of `/config` very very persistant :-)

**Comment by frenck** [comment]
That means the documentation of Node-RED is wrong or it is a Node-RED bug.

The documentation states: `Default: the user directory, ~/.node-red`
However, that is not true. `~` is the Unix/Linux user folder, which has nothing to do with Node-RED. However, it does not care about the Linux user apparently.

**Comment by sinclairpaul** [comment]
The docs aren't specific, it should say default - whatever you have overridden the User Directory to be (which is persistent in the addons case).

However back to the original issue, I don't see this as being thrown by Node-Red, but but one off the palettes, which do you have installed?

**Comment by guenter-ms** [comment]
I have inserted in /config/nodered/settings.js those lines:

 // configure contextStorage

contextStorage: {
     default: "file",
     memoryOnly: { module: 'memory' },
     file: { module: 'localfilesystem' }
 },

This makes it persistent and selects "file" as default when storing context data:

![Bildschirmfoto 2021-12-05 um 11 01 19](https://user-images.githubusercontent.com/6253315/144742027-015bef1c-95ca-4ff7-b940-94ec34e8e15c.jpg)

Persistent context data is saved in the backup data and therefore can be restored.
