### ISSUE TITLE
401 unauthorized error in Firefox with Enhanced Tracking Protection enabled

### ISSUE THREAD

**Issue by rafkra** [hassio-addons/addon-node-red#1178]
# Problem/Motivation

I clicked the Node-Red link in HA main menu to open Node-Red. Result was an 401 unauthorized error. I could open Node-Red with a handcrafted link I found somewhere but I don't remember it.

## Expected behavior

Node-Red opens within HA.

## Steps to reproduce

Looks like the problem depends on Firefox and Enhanced Tracking Protection enabled. I disabled Enhanced Tracking Protection for my HA installation and Node-Red opens again like in older FF versions. Read this https://www.reddit.com/r/homeassistant/comments/oqr4b3/firefox_90_breaking_hassio/

## Proposed changes

Other addons open without a problem, so there is something special with Node-Red.

**Comment by sinclairpaul** [comment]
Depends if those other addons use Ingress, please see:

https://alerts.home-assistant.io/#firefox.markdown
