### ISSUE TITLE
Setting ENV variable DEBUG - How to

### ISSUE THREAD

**Issue by hklages** [hassio-addons/addon-node-red#1182]
# Problem/Motivation

I need to set the Env variable DEBUG for debugging purposes.

## Expected behavior

I added to the Node-RED Add on configuration node the following lines.
```
init_commands:
  - export DEBUG="sonos:*"
  - printenv DEBUG

```
Expectation is to have DEBUG available in NodeRED flows.

## Actual behavior

The logfile shows the result of the printenv command, but in Node-RED the Env DEBUG is not available. 
I tested it with a simple change node. The TZ env variable is being shown. 

## Steps to reproduce
1. change the Node-RED add on config node and isert the 3 lines
2. restart node-red and verify that the printenv is executed
3. start a simple flow inject change with ENV and debug to see weather it is available

## Proposed changes
Highly appreciate a hint how to make the Env variable available in Node-RED

**Comment by frenck** [comment]
> I need to set the Env variable DEBUG for debugging purposes.

The add-on does not support that.

**Comment by hklages** [comment]
As there are a lot of packages using [debug](https://www.npmjs.com/package/debug) the following work around might be useful:

Adding 
`debug: process.env.DEBUG = "nrcsp:*",`
inside 
`module.exports = {}`
in 
`/config/node-red/settings.js`
