### ISSUE TITLE
Upgrade from 10.1.0 to 10.2.0

### ISSUE THREAD

**Issue by jimdholmes** [hassio-addons/addon-node-red#1198]
# Problem/Motivation

> Upgrade from Node-RED 10.1.0 to 10.2.0 in Home Assistant causes bad gateway error

## Expected behavior

> Node-RED 10.2.0 upgrade to be accessable and run the same as Node-RED 10.1.0

## Actual behavior

> Can't access Node-RED, Home Assistant Displays "502 Bad Gateway - nginx" error with the folloing entry in the Home Assistant Node-RED log.

2 Dec 17:01:03 - [error] Error: Invalid property expression: unexpected ' ' at position 8
    at createError (/opt/node_modules/@node-red/util/lib/util.js:184:13)
    at normalisePropertyExpression (/opt/node_modules/@node-red/util/lib/util.js:328:23)
    at Object.getObjectProperty (/opt/node_modules/@node-red/util/lib/util.js:417:24)
    at Memory._getOne (/opt/node_modules/@node-red/runtime/lib/nodes/context/memory.js:36:26)
    at Memory.get (/opt/node_modules/@node-red/runtime/lib/nodes/context/memory.js:52:26)
    at Object.value (/opt/node_modules/@node-red/runtime/lib/nodes/context/index.js:341:43)
    at Object.evaluateNodeProperty (/opt/node_modules/@node-red/util/lib/util.js:640:39)
    at /config/node-red/node_modules/node-red-contrib-bool-gate/lib/RuleManager.js:109:37
    at new Promise (<anonymous>)
    at RuleManager.updateState (/config/node-red/node_modules/node-red-contrib-bool-gate/lib/RuleManager.js:106:16)

## Steps to reproduce

> Upgraded through Home Assistant Supervisor.

**Comment by as-miner** [comment]
Busted for me too (rpi4 - core-2021.11.5, supervisor-2021.10.8)

3 Dec 08:57:22 - [info] Node-RED version: v2.1.4
3 Dec 08:57:22 - [info] Node.js  version: v16.13.1
3 Dec 08:57:22 - [info] Linux 5.10.17-v8 arm64 LE
3 Dec 08:57:23 - [info] Loading palette nodes
2021/12/03 08:57:29 [error] 565#565: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:46836/", host: "10.10.0.108:8123", referrer: "http://10.10.0.108:8123/a0d7b954_nodered/dashboard"
2021/12/03 08:57:31 [error] 565#565: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:46836/", host: "10.10.0.108:8123", referrer: "http://10.10.0.108:8123/a0d7b954_nodered/dashboard"
2021/12/03 08:57:32 [error] 565#565: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:46836/", host: "10.10.0.108:8123", referrer: "http://10.10.0.108:8123/a0d7b954_nodered/dashboard"

Stuck in a restart loop

**Comment by as-miner** [comment]
Disabling node-red-contrib-miio-roborock has solved the startup issue for me

**Comment by MvQuast** [comment]
switched back to NodeRed 10.1 from backup, but have no node-red-contrib-miio-roborock installed. I'm not sure which other component might be causing this restart issue

**Comment by jimdholmes** [comment]
Sorry guys, I'm a bit new to this so possibly paniced when Node-RED stopped working....

Fixed my issuse which was cuased by node-red-contrib-bool-gate module. I'm guessing that something in that particular module has been depricated cuasing Node-Red to fail on startup.

My issue was fixed by removing the offending module from **_package.json_** file. For newbies like me I have VS Code installed in my Home Assistant deployment, the file can be found under the node-red directory on the left hand fiile explorer in VS Code.

I identified the offending module using the log trace  

2 Dec 17:01:03 - [error] Error: Invalid property expression: unexpected ' ' at position 8
at createError (/opt/node_modules/@node-red/util/lib/util.js:184:13)
at normalisePropertyExpression (/opt/node_modules/@node-red/util/lib/util.js:328:23)
at Object.getObjectProperty (/opt/node_modules/@node-red/util/lib/util.js:417:24)
at Memory._getOne (/opt/node_modules/@node-red/runtime/lib/nodes/context/memory.js:36:26)
at Memory.get (/opt/node_modules/@node-red/runtime/lib/nodes/context/memory.js:52:26)
at Object.value (/opt/node_modules/@node-red/runtime/lib/nodes/context/index.js:341:43)
at Object.evaluateNodeProperty (/opt/node_modules/@node-red/util/lib/util.js:640:39)
at /config/node-red/node_modules/node-red-contrib-bool-gate/lib/RuleManager.js:109:37
at new Promise ()
at RuleManager.updateState (**_/config/node-red/node_modules/node-red-contrib-bool-gate_**/lib/RuleManager.js:106:16)

"/config/node-red/node_modules/**_node-red-contrib-bool-gate_**/lib/RuleManager.js:106:16)" being the givaway.

Once removed Node-RED started OK, just need to find a replacment for the module giving me my issue.

Hope this helps and sorry for jumping on the ... "it must be the upgrade to Node-RED" causing the problem,

I'm guessing it is a compatability issue ... would be good if Node-RED coule provide a compatability tool to scan for these issues prior to upgrading :-)

**Comment by MvQuast** [comment]
(node:513) UnhandledPromiseRejectionWarning: SyntaxError: Malformed JSON in file: /config/node-red//node-red-contrib-home-assistant-websocket.json
Unexpected token  in JSON at position 0
    at FileAsync.parse [as deserialize] (<anonymous>)
    at /opt/node_modules/lowdb/adapters/FileAsync.js:41:35
    at Storage.getDb (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/helpers/Storage.js:25:14)
    at Storage.saveData (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/helpers/Storage.js:37:20)
(node:513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 60587)

**Comment by hugo1721** [comment]
> (node:513) UnhandledPromiseRejectionWarning: SyntaxError: Malformed JSON in file: /config/node-red//node-red-contrib-home-assistant-websocket.json
> Unexpected token in JSON at position 0
> at FileAsync.parse [as deserialize] ()
> at /opt/node_modules/lowdb/adapters/FileAsync.js:41:35
> at Storage.getDb (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/helpers/Storage.js:25:14)
> at Storage.saveData (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/helpers/Storage.js:37:20)
> (node:513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 60587)

Sorry for my English, try delete (node-red-contrib-home-assistant-websocket.json) and update, the file will be recreated when booted

**Comment by bberg115** [comment]
> Disabling node-red-contrib-miio-roborock has solved the startup issue for me

Same issue here.

**Comment by erratique** [comment]
> Sorry for my English, try delete (node-red-contrib-home-assistant-websocket.json) and update, the file will be recreated when booted

Updated Node-red, stopped it, deleted node-red-contrib-home-assistant-websocket.json and restarted node-red. seems to work now

**Comment by jip67** [comment]
Same issue here. Nginx bad gateway error.

**Comment by MvQuast** [comment]
But removing node-red-contrib-home-assistant-websocket.json would mean that I need to export all flows as this component is used from 19 nodes ATM?

**Comment by erratique** [comment]
> But removing node-red-contrib-home-assistant-websocket.json would mean that I need to export all flows as this component is used from 19 nodes ATM?

the file was created again on startup. and everything worked as before. i did not export/import anything

**Comment by pjgrun** [comment]
> Same issue here. Nginx bad gateway error. Restore old version solved it,

Same with me. More details in https://github.com/hassio-addons/addon-node-red/issues/1201#issuecomment-989767974

**Comment by frenck** [comment]
Please... avoid posting "I have the same issue" anywhere on GitHub... instead, just add a 👍  on the opening post of the issue.
