### ISSUE TITLE
Delay node not always triggering after update to 10.2.0

### ISSUE THREAD

**Issue by Greg-or-y** [hassio-addons/addon-node-red#1199]
# Problem/Motivation

> DELAY node don't trigger every time. Sometime triggers only once then restart of NodeRED addon is required.

## Expected behavior

> DELAY node should work every time and should have predictable behavior like in previous version 
## Actual behavior

> DELAY node triggers once and sometime two times in row and then stop working , restart of NODE RED addon is required,
after restoring previous version of ADDON all is good again.

## Steps to reproduce

> I have this problem with long 55 seconds DELAY node when i click INJECT node connected and wait 55 sec it changes from (1) after triggering to (0) after 55 sec and triggers debag node. Next try after that do not work always it's inpredictable.

## Proposed changes

>  I would like someone inspect this behavior in version 10.1.1 of nodered addon restored from backup all works good every time (hundred times in row tested)

**Comment by Greg-or-y** [comment]
Plase help with this problem.

**Comment by aaamoeder** [comment]
Check your logs of the node red addon, 
I'm suspecting the addon is in a reboot loop causing unexpected behaviour.
see --> https://github.com/hassio-addons/addon-node-red/issues/1201
