### ISSUE TITLE
"Join" Node blank

### ISSUE THREAD

**Issue by inputd** [hassio-addons/addon-node-red#12]
HASSIO HA version: 0.73.1
Supervisor: 115
Node-Red module version: 0.2.1

The "Join" node, under "node properties", is totally blank. Drop down lists have selectable items, but they are in turn blank, and lead to more blank options. Not sure if it is related, but the following warnings appear when the node-red module is started up:

11 Jul 16:59:26 - [warn] Cannot find Pi RPi.GPIO python library
11 Jul 16:59:37 - [warn] ------------------------------------------------------
11 Jul 16:59:37 - [warn] [node-red/rpi-gpio] Warning : Cannot find Pi RPi.GPIO python library
11 Jul 16:59:37 - [warn] [node-red-contrib-join/join] 'join' already registered by module node-red
11 Jul 16:59:37 - [warn] ------------------------------------------------------

Photo of what it looks like in Node-red:
![joinnode](https://user-images.githubusercontent.com/38230664/42605550-67f343a6-852d-11e8-8421-9b6844379ee9.png)

**Comment by frenck** [comment]
The issue has been fixed on the `master` branch and will be fixed in the upcoming release.
Thank you for reporting in! 👍
