### ISSUE TITLE
HA addon Security Rating

### ISSUE THREAD

**Issue by tort32** [hassio-addons/addon-node-red#1206]
HA Supervisor rates addon's security in 3 of 6:
![image](https://user-images.githubusercontent.com/2276611/144814044-42a71080-8b7f-4592-99e6-5615687239af.png)

Security Rating criteria and configuration requirements are described here
https://developers.home-assistant.io/docs/add-ons/presentation/

But as far I understand security role and privileges is used for the number of things (like a web-server for a dashbord, controlling of HASS container, GPIO direct access). Related changes: https://github.com/hassio-addons/addon-node-red/commit/8f046cb40535b5c89fd02f3bddcd4f4857d90f0f https://github.com/hassio-addons/addon-node-red/commit/3265fe40c4ea6e7ba20336ae4e3a53d369a766e3
So rating can't be increased easily by enabling protection options in a config.

Unfortunately I found no discussion, explanation or describing of used permissions and possible risks connected with using of this addon. So this issue is created to cover this topic.

Probably the documentation should have some wording about hassio permissions usage and security. At least the mention in the known issues.

**Comment by frenck** [comment]
Security citeria for the rating is based on the amount of access the add-on requires; it doesn't say it is "less secure".

I'm lost on your suggestion in this matter. I have no interest in documenting the security rating from the add-on perspective.

**Comment by tort32** [comment]
Your point is totally valid cause the source code has no malicious intensions.

From the user's point of view there is a notice at the add-on's store page saying:
> Home Assistant provides a security rating to each of the add-ons, which indicates the risks involved when using this add-on. The more access an add-on requires on your system, the lower the score, thus raising the possible security risks.

This actually means "more risky" = "less secure". Is it correct?

HA documentation also says that:
> If your add-on has a lower security rating, then users will be less likely to trust it.

So user either have to trust, accept the risks and install it as-is or don't use it at all.
I see it as an distribution issue considering lack of available information why Node-RED add-on has such a score.

This guys also wonder why
https://community.home-assistant.io/t/hass-io-node-red-add-on-security-rating/135139

**Comment by frenck** [comment]
> This actually means "more risky" = "less secure". Is it correct?

No, it means the it requests more access/resources.

> So user either have to trust, accept the risks and install it as-is or don't use it at all.

Correct.

> I see it as an distribution issue considering lack of available information why Node-RED add-on has such a score.

This is displayed in Home Assistant. You can click on each of the badges provided to get more information on the access requested.


> This guys also wonder why

🤷 Ok

**Comment by frenck** [comment]
Closing as per above.
