### ISSUE TITLE
Failed after update do Node Red Companion

### ISSUE THREAD

**Issue by mdanilohome** [hassio-addons/addon-node-red#1207]
After upgrading the Node Red Companion version from version 5.2 to 5.4, I had difficulty opening Node Red in Home Assistant. After several attempts, when Node Red opened, it kept blocking automations. I noticed that with Node RED in this condition, initialization attempts were consuming around 100% of CPU processing. I tried to restore the previous version of Node Red Companion and the problem remained. It only normalized after backing up Home Assistant to a previous version.

**Comment by frenck** [comment]
What is `Node Red Companion` ?

**Comment by frenck** [comment]
Oh, I see, that is the integration, this is not an integration, but an add-on. So it seems you are in the wrong place.

**Comment by mdanilohome** [comment]
Sorry but for the information that is in Node Red Companion it is rather an integration, a repository. If this is not where I should address this issue, please let me know what the correct topic would be. Thanks.
[Inbformation Node Red Companion.pdf](https://github.com/hassio-addons/addon-node-red/files/7675717/Inbformation.Node.Red.Companion.pdf)

**Comment by frenck** [comment]
>  If this is not where I should address this issue, please let me know what the correct topic would be

I don't know, you are commenting/creating issues in an unrelated repository. 🤷 
Please check with the author of that integration where report issues for that thing.
