### ISSUE TITLE
cant install node red on hass.io

### ISSUE THREAD

**Issue by gibman** [hassio-addons/addon-node-red#121]
Trying to install node red on hass.io 0.86.1 (raspberry pi) but Im stuck with this log:

19-01-27 18:45:01 INFO (SyncWorker_0) [hassio.docker.interface] Pull image hassioaddons/node-red-armhf tag 1.2.5.
19-01-27 18:45:16 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install hassioaddons/node-red-armhf:1.2.5 -> 404 Client Error: Not Found ("no such image: hassioaddons/node-red-armhf:1.2.5: No such image: hassioaddons/node-red-armhf:1.2.5").

any idea whats going on ?

**Comment by frenck** [comment]
404 can be 2 things:
- The image does not exist
- You do not have enough disk space available to complete the action.

Little hint, it is not the first one ;)

**Comment by cnc79** [comment]
@frenck sorry i am a little bit of a noob :( I am getting the following error.

9-02-16 14:36:25 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-02-16 14:46:18 INFO (SyncWorker_17) [hassio.docker.interface] Pull image hassioaddons/node-red-armhf tag 1.3.2.
19-02-16 14:46:22 ERROR (SyncWorker_17) [hassio.docker.interface] Can't install hassioaddons/node-red-armhf:1.3.2 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument"

Currently running hassio version 87.1 and HASSos 2.8

disk space command shows the following.

core-ssh:~# df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  13.6G      2.3G     10.6G  18% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                   463.1M         0    463.1M   0% /sys/fs/cgroup
/dev/root                89.9M     89.9M         0 100% /dev/init
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /config
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /ssl
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /addons
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /backup
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /share
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /data
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /etc/resolv.conf
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /etc/hostname
/dev/mmcblk0p8           13.6G      2.3G     10.6G  18% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                   463.1M         0    463.1M   0% /sys/firmware

note that the first attempt to install nodered froze the system.

**Comment by cnc79** [comment]
Backed up, reflashed sdcard, all working again 😁

**Comment by frenck** [comment]
👍
