### ISSUE TITLE
High CPU and mem usage of node-red add-on suddenly after hours

### ISSUE THREAD

**Issue by guenter-ms** [hassio-addons/addon-node-red#1210]
# Problem/Motivation

After hours of perfect working, suddenly CPU and memory usage are exploding, see screenshots.

![Bildschirmfoto 2021-12-12 um 11 02 50](https://user-images.githubusercontent.com/6253315/145712053-bb26306e-29b0-435f-8006-fac70eac3583.jpg)

![Bildschirmfoto 2021-12-12 um 13 24 06](https://user-images.githubusercontent.com/6253315/145712027-60662d48-56cb-4bde-ac20-dfa95ede8cda.jpg)

## Expected behavior

Expect not such a behavior.

## Actual behavior

I have setup a small dedicated HA installation on a raspy 4. Nodered was only configured with 2 nodes from node-red-contrib-ccu add-on to receive messages from an external homematic CCU and some debug statements. And that works fine four hours. Then suddenly the mentioned behavior comes up, which can be eliminated only with a nodered add-on restart.

![Bildschirmfoto 2021-12-12 um 13 30 05](https://user-images.githubusercontent.com/6253315/145712274-922cce2a-4537-4c9f-a682-f31a9a2c7468.jpg)

## Steps to reproduce

Just wait for hours and it will come up again.

## Proposed changes

Assuming that the [ node-red-contrib-ccu](https://flows.nodered.org/node/node-red-contrib-ccu) node is the cause, I have no Idea how to investigate what has happened at the point when the CPU raises up. Log messages from that node are not found anywhere in the system. The nodered log only shows the last few minutes and no log entries from the add-on which will be seen when installing nodered outside HA (where that problem does not occur). 

What can I do to get closer to the problem? 

![Bildschirmfoto 2021-12-12 um 13 38 41](https://user-images.githubusercontent.com/6253315/145712611-53137c35-cf16-4814-ac55-39ef7f801102.jpg)

**Comment by guenter-ms** [comment]
I could catch the log when CPU is high, see below. Found no errors. How can I get deeper inside to find out the root cause for high CPU consumption?

17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:6 INFO Philips-Hue change=false
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:6 IP 192.168.178.57 change=false
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:6 UNREACH_CTR 0 change=false
17 Dec 09:01:34 - [debug] [ccu-connection:ccu-prod]     > CUxD system.multicall ["","",""]
17 Dec 09:01:34 - [debug] [ccu-connection:ccu-prod] rpc < binrpc system.multicall [[{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803001:12","INFO","Diskstation2"]},{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803001:12","IP","192.168.178.68"]},{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803001:12","UNREACH_CTR",0]}]]
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:12 INFO Diskstation2 change=false
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:12 IP 192.168.178.68 change=false
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:12 UNREACH_CTR 0 change=false
17 Dec 09:01:34 - [debug] [ccu-connection:ccu-prod]     > CUxD system.multicall ["","",""]
17 Dec 09:01:34 - [debug] [ccu-connection:ccu-prod] rpc < binrpc system.multicall [[{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803001:14","INFO","SonosZP-KU"]},{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803001:14","IP","192.168.178.35"]},{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803001:14","UNREACH_CTR",0]}]]
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:14 INFO SonosZP-KU change=false
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:14 IP 192.168.178.35 change=false
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803001:14 UNREACH_CTR 0 change=false
17 Dec 09:01:34 - [debug] [ccu-connection:ccu-prod]     > CUxD system.multicall ["","",""]
17 Dec 09:01:34 - [debug] [ccu-connection:ccu-prod] rpc < binrpc system.multicall [[{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803002:2","INFO","aio-Gateway-Extender-sz"]},{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803002:2","IP","192.168.178.46"]},{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803002:2","UNREACH_CTR",0]}
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803002:2 INFO aio-Gateway-Extender-sz change=false
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803002:2 IP 192.168.178.46 change=false
17 Dec 09:01:34 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803002:2 UNREACH_CTR 0 change=false
17 Dec 09:01:34 - [debug] [ccu-connection:ccu-prod]     > CUxD system.multicall ["","",""]
17 Dec 09:01:36 - [debug] [ccu-connection:ccu-prod] rpc < http system.multicall [[{"methodName":"event","params":["nr_816DDD_BidCos-Wired","LEQ0251965:15","STATE",false]}]]
17 Dec 09:01:36 - [trace] [ccu-connection:ccu-prod] createMessage LEQ0251965:15 STATE false change=true
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"8453bbf628b05522","event":"node.ccu-rpc-event.send","msgid":"2bee8bacbb04ba9e","timestamp":1639728096535}
17 Dec 09:01:36 - [debug] [ccu-connection:ccu-prod]     > BidCos-Wired system.multicall [""]
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"ee05f54819b81981","event":"node.debug.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096538}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"ee05f54819b81981","event":"node.debug.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096540}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"5d7897b0b6280185","event":"node.debug.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096540}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"5d7897b0b6280185","event":"node.debug.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096541}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"9b194a80e4a83dca","event":"node.debug.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096542}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"9b194a80e4a83dca","event":"node.debug.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096543}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"16a61c10832a6abb","event":"node.debug.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096544}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"16a61c10832a6abb","event":"node.debug.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096545}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"01e4ead7bf753e11","event":"node.debug.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096546}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"01e4ead7bf753e11","event":"node.debug.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096547}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"007d35da56b5ada0","event":"node.debug.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096548}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"007d35da56b5ada0","event":"node.debug.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096549}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"38f49a003c1974f8","event":"node.debug.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096549}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"38f49a003c1974f8","event":"node.debug.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096551}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096551}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.send","msgid":"2bee8bacbb04ba9e","timestamp":1639728096553}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096553}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"ab64a7af327e90ea","event":"node.Message Counter.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096554}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"a516ff1828dd99a9","event":"node.debug.receive","msgid":"2bee8bacbb04ba9e","timestamp":1639728096556}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"a516ff1828dd99a9","event":"node.debug.done","msgid":"2bee8bacbb04ba9e","timestamp":1639728096557}
17 Dec 09:01:36 - [debug] [ccu-connection:ccu-prod] rpc < http system.multicall [[{"methodName":"event","params":["nr_816DDD_BidCos-Wired","LEQ0251965:15","STATE",true]}]]
17 Dec 09:01:36 - [trace] [ccu-connection:ccu-prod] createMessage LEQ0251965:15 STATE true change=true
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"8453bbf628b05522","event":"node.ccu-rpc-event.send","msgid":"0060b4cff1bd1bf0","timestamp":1639728096625}
17 Dec 09:01:36 - [debug] [ccu-connection:ccu-prod]     > BidCos-Wired system.multicall [""]
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"ee05f54819b81981","event":"node.debug.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096628}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"ee05f54819b81981","event":"node.debug.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096629}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"5d7897b0b6280185","event":"node.debug.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096629}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"5d7897b0b6280185","event":"node.debug.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096629}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"9b194a80e4a83dca","event":"node.debug.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096630}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"9b194a80e4a83dca","event":"node.debug.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096630}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"16a61c10832a6abb","event":"node.debug.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096630}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"16a61c10832a6abb","event":"node.debug.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096630}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"01e4ead7bf753e11","event":"node.debug.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096630}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"01e4ead7bf753e11","event":"node.debug.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096631}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"007d35da56b5ada0","event":"node.debug.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096631}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"007d35da56b5ada0","event":"node.debug.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096632}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"38f49a003c1974f8","event":"node.debug.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096632}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"38f49a003c1974f8","event":"node.debug.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096632}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096632}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.send","msgid":"0060b4cff1bd1bf0","timestamp":1639728096632}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096633}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"ab64a7af327e90ea","event":"node.Message Counter.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096633}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"a516ff1828dd99a9","event":"node.debug.receive","msgid":"0060b4cff1bd1bf0","timestamp":1639728096633}
17 Dec 09:01:36 - [metric] {"level":99,"nodeid":"a516ff1828dd99a9","event":"node.debug.done","msgid":"0060b4cff1bd1bf0","timestamp":1639728096634}
17 Dec 09:01:37 - [debug] [ccu-connection:ccu-prod] rpc < binrpc system.multicall [[{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX9000001:1","STATE",1.9]}]]
17 Dec 09:01:37 - [trace] [ccu-connection:ccu-prod] createMessage CUX9000001:1 STATE 1.9 change=true
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"8453bbf628b05522","event":"node.ccu-rpc-event.send","msgid":"97aa786c96322a9b","timestamp":1639728097059}
17 Dec 09:01:37 - [debug] [ccu-connection:ccu-prod]     > CUxD system.multicall [""]
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"ee05f54819b81981","event":"node.debug.receive","msgid":"97aa786c96322a9b","timestamp":1639728097075}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"ee05f54819b81981","event":"node.debug.done","msgid":"97aa786c96322a9b","timestamp":1639728097076}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"5d7897b0b6280185","event":"node.debug.receive","msgid":"97aa786c96322a9b","timestamp":1639728097077}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"5d7897b0b6280185","event":"node.debug.done","msgid":"97aa786c96322a9b","timestamp":1639728097077}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"9b194a80e4a83dca","event":"node.debug.receive","msgid":"97aa786c96322a9b","timestamp":1639728097079}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"9b194a80e4a83dca","event":"node.debug.done","msgid":"97aa786c96322a9b","timestamp":1639728097079}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"16a61c10832a6abb","event":"node.debug.receive","msgid":"97aa786c96322a9b","timestamp":1639728097080}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"16a61c10832a6abb","event":"node.debug.done","msgid":"97aa786c96322a9b","timestamp":1639728097081}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"01e4ead7bf753e11","event":"node.debug.receive","msgid":"97aa786c96322a9b","timestamp":1639728097081}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"01e4ead7bf753e11","event":"node.debug.done","msgid":"97aa786c96322a9b","timestamp":1639728097082}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"007d35da56b5ada0","event":"node.debug.receive","msgid":"97aa786c96322a9b","timestamp":1639728097085}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"007d35da56b5ada0","event":"node.debug.done","msgid":"97aa786c96322a9b","timestamp":1639728097086}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"38f49a003c1974f8","event":"node.debug.receive","msgid":"97aa786c96322a9b","timestamp":1639728097086}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"38f49a003c1974f8","event":"node.debug.done","msgid":"97aa786c96322a9b","timestamp":1639728097087}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.receive","msgid":"97aa786c96322a9b","timestamp":1639728097087}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.send","msgid":"97aa786c96322a9b","timestamp":1639728097088}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"93453f1aedbac5df","event":"node.moment.done","msgid":"97aa786c96322a9b","timestamp":1639728097088}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"ab64a7af327e90ea","event":"node.Message Counter.receive","msgid":"97aa786c96322a9b","timestamp":1639728097088}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"a516ff1828dd99a9","event":"node.debug.receive","msgid":"97aa786c96322a9b","timestamp":1639728097091}
17 Dec 09:01:37 - [metric] {"level":99,"nodeid":"a516ff1828dd99a9","event":"node.debug.done","msgid":"97aa786c96322a9b","timestamp":1639728097092}
17 Dec 09:01:37 - [debug] [ccu-connection:ccu-prod] rpcCheckInit HmIP-RF 120 600
17 Dec 09:01:39 - [debug] [ccu-connection:ccu-prod] rpc < binrpc system.multicall [[{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803002:3","INFO","CCU-LAN-Gateway-Keller-OEQ0328488"]},{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803002:3","IP","192.168.178.71"]},{"methodName":"event","params":["nr_GX8gGS_CUxD","CUX2803002:3","UNREAC
17 Dec 09:01:39 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803002:3 INFO CCU-LAN-Gateway-Keller-OEQ0328488 change=false
17 Dec 09:01:39 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803002:3 IP 192.168.178.71 change=false
17 Dec 09:01:39 - [trace] [ccu-connection:ccu-prod] createMessage CUX2803002:3 UNREACH_CTR 0 change=false
17 Dec 09:01:39 - [debug] [ccu-connection:ccu-prod]     > CUxD system.multicall ["","",""]
17 Dec 09:01:40 - [metric] {"level":99,"event":"runtime.memory.rss","value":491884544,"timestamp":1639728100702}
17 Dec 09:01:40 - [metric] {"level":99,"event":"runtime.memory.heapTotal","value":400113664,"timestamp":1639728100702}
17 Dec 09:01:40 - [metric] {"level":99,"event":"runtime.memory.heapUsed","value":364636816,"timestamp":1639728100703}

**Comment by guenter-ms** [comment]
Hi,
you may look at https://community.home-assistant.io/t/solved-update-add-on-nodered-high-cpu-and-log-file-path-not-found/363238/7
Its a DNS problem.

**Comment by nickaggie** [comment]
I looked at that, but im not sure if its the same issue.  I have selected that im using the Home Assistant Add-on so not sure where i can set the IP

**Comment by guenter-ms** [comment]
it seems like HA DNS Server has a prob with DNS name resolution at high traffic. my (in the link described) use case was with the node-red-contrib-ccu add-on. using any nodes from that needs a configuration of a cpu. at that point you can put in a dns name (and get the prob) or take the nativ ip address, the no prob.

**Comment by frenck** [comment]
`node-red-contrib-ccu` is not an node that is delivered by this add-on. One can install additional nodes and do all kinds of nice things with Node-RED, but it are third-party extensions that are pulled in... which well can all do their own things and cause their own problems.

For me, it is impossible to provide support for those. Anyways, as listed above, it seems you have found a solution/way around it (which is great!), so I will go ahead and close/clean it up on this end.

👍

**Comment by guenter-ms** [comment]
I agree, its not a node red prob. its a HA DNS Server prob. Thank you.
The only thing I am missing is an easy way to route the log file (console out) into a separate dataset. that would make life much easier.
