### ISSUE TITLE
Node Status time

### ISSUE THREAD

**Issue by Smerk80** [hassio-addons/addon-node-red#1215]
# Problem/Motivation

Node status time show's 24:40 instead of 0:40

![Screenshot 2021-12-15 004106](https://user-images.githubusercontent.com/58696262/146097185-d0b80748-a563-4287-b557-5bb8c45cf0dd.png)

**Comment by sinclairpaul** [comment]
https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#time-zone-configuration

**Comment by sinclairpaul** [comment]
Oops, wrong button, however have you validated the timezone?

**Comment by sinclairpaul** [comment]
https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/524

Will need an update in the addon.
