### ISSUE TITLE
Ingress Error 502

### ISSUE THREAD

**Issue by rossking** [hassio-addons/addon-node-red#1218]
# Problem/Motivation
21-12-17 06:52:25 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64568/comms')

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by rossking** [comment]
Seems to be in a crash loop, not sure whats crahing

[07:33:50] INFO: Starting Node-RED...
2021/12/17 07:33:52 [error] 557#557: *852 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.onebx.us:8123"
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
2021/12/17 07:33:53 [error] 557#557: *852 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.onebx.us:8123"
17 Dec 07:33:54 - [info] 
Welcome to Node-RED
===================
17 Dec 07:33:54 - [info] Node-RED version: v2.1.4
17 Dec 07:33:54 - [info] Node.js  version: v16.13.1
17 Dec 07:33:54 - [info] Linux 5.10.63-v8 arm64 LE
2021/12/17 07:33:54 [error] 557#557: *852 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.onebx.us:8123"
2021/12/17 07:33:56 [error] 557#557: *852 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.onebx.us:8123"
17 Dec 07:33:56 - [info] Loading palette nodes
2021/12/17 07:33:57 [error] 557#557: *852 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.onebx.us:8123"
17 Dec 07:34:02 - [info] Dashboard version 3.1.2 started at /endpoint/ui
17 Dec 07:34:03 - [info] Settings file  : /etc/node-red/config.js
17 Dec 07:34:03 - [info] Context store  : 'default' [module=memory]
17 Dec 07:34:03 - [info] User directory : /config/node-red/
17 Dec 07:34:03 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Dec 07:34:03 - [info] Flows file     : /config/node-red/flows.json
17 Dec 07:34:03 - [info] Server now running at http://127.0.0.1:46836/
17 Dec 07:34:03 - [info] Starting flows
17 Dec 07:34:04 - [info] Started flows
17 Dec 07:34:05 - [warn] [function:Process Dallas 1 Wire Data] 2.3,39.2,76.9,73.6,67.0,36.5,49.1,57.2
17 Dec 07:34:05 - [error] [ha-entity:Frezer] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Refrigerator] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Water Heater Hot Water] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Water Heater Cold Water] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Water Heater Flume] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Outdoor - Rain Sensor] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Outdoor - MPOE] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Garrage Temp] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Bar Trend] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Barometer] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Inside Temperature] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Inside Humidity] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Outside Temperature] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Outside Humidity] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Speed] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Speed 2M Avg] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Speed 10M Avg] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Direction] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Direction TEXT] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Direction and Speed TEXT] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Speed 10M Gust] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Direction 10M Gust] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Direction 10M Gust TEXT] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Direction and Speed 10M Gust TEXT] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Dew Point] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Heat Index] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Wind Chill] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Rain Rate] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Rain Daily Rate] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Rain Last 15M] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Rain Last 1H] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Rain Last 24H] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Rain Storm] Sensor update attempted without connection to server.
17 Dec 07:34:05 - [error] [ha-entity:Rain Storm Start Date] Sensor update attempted without connection to server.
17 Dec 07:34:08 - [info] [server:Home Assistant] Connecting to undefined
17 Dec 07:34:08 - [info] [server:Home Assistant] Connected to undefined
17 Dec 07:34:09 - [red] Uncaught Exception:
17 Dec 07:34:09 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[07:34:09] INFO: Starting Node-RED..

**Comment by frenck** [comment]
> 2021/12/17 07:33:52 [error] 557#557: *852 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.onebx.us:8123"

Looks like it is using a custom server configuration to connect to an Home Assistant instance externally, that it cannot reach. (Please note, that is not how the add-on was designed to work, by default it comes pre-configured using an internal connection).

**Comment by rossking** [comment]
My home assistant is not external to my netowrk
"homeassistant.onebx.us:8123" is internally configured to DNS

And I did not do any custom configs for Node Red that i know of, I have spent days trying to find any of the connection info.

I uninstalled and re-instaled and set confic back to deault still no working

where do i chnage the Node-red to use default server connections, where are those configs?

**Comment by rossking** [comment]
So, I found article that mentioned Pallets. I looked in their and the Websocket pallet needed to be updated that seems to have solved. 

Still seems to be a bug arround this issue

17 Dec 07:34:08 - [info] [server:Home Assistant] Connecting to undefined
17 Dec 07:34:08 - [info] [server:Home Assistant] Connected to undefined
17 Dec 07:34:09 - [red] Uncaught Exception:
17 Dec 07:34:09 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#".

Should just fail to update not crash and re-start, was hard to get into becasue it was always re0starting

Since I found that hidden update option it seems to be working now

**Comment by tuxamat** [comment]
the same
`22-02-07 18:20:00 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:20:01 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:20:08 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-02-07 18:20:08 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-02-07 18:20:08 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-02-07 18:23:45 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-02-07 18:23:46 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:47 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:48 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:49 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:51 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:52 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:53 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:54 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:55 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:56 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:57 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:58 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:23:59 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:00 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:01 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:02 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:03 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:04 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:05 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:06 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:08 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:09 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:10 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:12 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:13 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:14 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:15 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:16 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.32.1:64782/comms')
22-02-07 18:24:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-02-07 18:24:23 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-02-07 18:24:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running`
