### ISSUE TITLE
http_node not working

### ISSUE THREAD

**Issue by ajitam** [hassio-addons/addon-node-red#1219]
# Problem/Motivation

`http_node` not working (in combination with exposing to `1881` port and going to `http://homeassistant.local:1881`)
(I hope I using this correctly)

## Expected behavior

by setting up 

```
http_node:
  password: strong_password
  username: user
```

above `username`/`password` should work for logging in into Node-RED

## Actual behavior

* basic auth pop-up is presented
* `username`/`password` does NOT work

## Steps to reproduce

* under Options:

```
http_node:
  password: user
  username: strong_password
```

* under Network:

```
 80/tcp > 1881
```

* visit `http://homeassistant.local:1881`

## Proposed changes

/

**Comment by ajitam** [comment]
1. can you please provide link to the new location of this issue? I can't find it here - https://github.com/hassio-addons/repository/issues
2. should I close this issue?

**Comment by frenck** [comment]
It is already moved... :) 
See URL in your browser bar :)

**Comment by ajitam** [comment]
my bad - I read that issue was moved TO hassio-addons/repository - sorry about that

**Comment by sinclairpaul** [comment]
The HTTP nodes are presented under the path ```/endpoint``` for example ```http://homeassistant.local:1881/endpoint/nameofnode```

https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-http_node

The authentication prompt you are receiving is for the application which is your HA credentials

**Comment by ajitam** [comment]
oh - didn't make that connection.
Thx for explanation.
