### ISSUE TITLE
(input_)select.select_option doesn't accept data input

### ISSUE THREAD

**Issue by TheGroundZero** [hassio-addons/addon-node-red#1220]
# Problem/Motivation

> (Why the issue was filed)

I'm trying to change the selected option of a `select` object through Node-RED.

## Expected behavior

> (What you expected to happen)

Calling `select.select_option` with `{ "option": "wanted option" }` in the data field allows me to change the selected option of the `select` entity.

## Actual behavior

> (What actually happened)

An API Error is thrown:
`"Call-service error. extra keys not allowed @ data['option']"`

![image](https://user-images.githubusercontent.com/2406013/146802118-86a94b16-34fb-4084-b9b7-789e2ca180ef.png)

## Steps to reproduce

> (How can someone else make/see it happen)

1. Have a Home Assistant `select` or `input_select` entity
2. Setup a Node-RED flow with a Call Service node
3. Set the call_svc node up as follows:
  - Domain: select
  - Service: select_option
  - Entity id: <your select entity>
  - Data: `{ "option": "your wanted selection" }`

![image](https://user-images.githubusercontent.com/2406013/146802085-ebd96c60-fffe-41a3-9cf8-ac09a7e20658.png)

Note: I also tried and failed using `Lava` and `"Lava"` as Data input.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Seems valid, but not an issue the add-on can do anything about.
Might be an Home Assistant bug, or a bug with the palette used for the Home Assistant nodes.

**Comment by TheGroundZero** [comment]
> Seems valid, but not an issue the add-on can do anything about. Might be an Home Assistant bug, or a bug with the palette used for the Home Assistant nodes.

Thanks for the quick reply (and validation).

Where should I file this bug report then?
`home-assistant / core` ?

**Comment by frenck** [comment]
> Where should I file this bug report then?

I really don't know.

**Comment by TheGroundZero** [comment]
Guess I'll start of here: https://github.com/zachowj/node-red-contrib-home-assistant-websocket
