### ISSUE TITLE
node-red-contrib-rfxcom stoped working after nr update to 10.2.2

### ISSUE THREAD

**Issue by lpt2007** [hassio-addons/addon-node-red#1225]
# Problem/Motivation
node-red-contrib-rfxcom stoped working after nr update to 10.2.2
> (Why the issue was filed)

## Expected behavior
23 Dec 18:50:27 - [warn] ------------------------------------------------------
23 Dec 18:50:27 - [warn] [node-red-contrib-rfxcom/rfxcom] Error: The module '/config/node-red/node_modules/rfxcom/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> node-red-contrib-rfxcom stoped working after nr update to 10.2.2

Seems like you have manually installed it via the command palette instead of using the add-on configuration options.
