### ISSUE TITLE
Big Timer - no payload

### ISSUE THREAD

**Issue by blackcult** [hassio-addons/addon-node-red#1235]
# Problem/Motivation
Big Timer no longer outputs payload message

## Expected behavior

1 for on / 0 for off

## Actual behavior

empty string

## Steps to reproduce

Create big timer addon, selected repeating output in options for faster observation, output to debug

## Proposed changes

The bug was introduced in 2.8.0 and fixed in 2.8.1

**Comment by frenck** [comment]
fixed in #1234
