### ISSUE TITLE
Copy path/value from debug inspector not working

### ISSUE THREAD

**Issue by thomasfals** [hassio-addons/addon-node-red#1241]
# Problem/Motivation

Unable to copy path/value from debug using version 10.3.3

## Expected behavior

Value to be copied to clipboard

## Actual behavior

Pressing copy value or path does nothing

## Steps to reproduce

Try pressing copy value or path in debug inspector

## Proposed changes

Make copy work

**Comment by rlust** [comment]
I just saw NR 2.16 fixes this problem. Hoping we get this upgrade soon.

**Comment by thomasfals** [comment]
> I just saw NR 2.16 fixes this problem. Hoping we get this upgrade soon.

You are right. Closed here https://github.com/node-red/node-red/pull/3363

Will close here as well
