### ISSUE TITLE
No Information regarding GPIO nodes not working in addon Documentation

### ISSUE THREAD

**Issue by thezeroth** [hassio-addons/addon-node-red#1244]
# Problem/Motivation

Well GPIO Nodes on Raspberry Pi (4) don't work out of the box, gives out this error:

"nrgpio python command not running"

after researching it, it seems that they are not suppose to work! and NodeRed even doesn't know its running on a raspberry pi. i read that we are somehow suppose to control them via home assistance. really???

## Expected behavior
It shouldn't be this confusing for the end user.

## Proposed changes

Information about this problem and a possible solution should be added to the addon documentation as we have the GPIO nodes available after addon installation but they don't work and this is very confusing for the end user.

**Comment by thezeroth** [comment]
@frenck using your "my car doesn't start" metaphor, i am not asking to fix the car, i am asking to put a notice on the car saying a certain part of the car does not work so people don't get confused.
 
to reproduce the problem, when running the home assistant with NodeRed addon installed on any Raspberry Pi, try to use a NodeRed's "rpi gpio in" or "rpi gpio out" Node under Raspberry Pi section, "rpi gpio in" or "rpi gpio out" nodes don't function, they produce this error:

"nrgpio python command not running"

I propose doing at least one of the followings:

1) Add Information about this problem and a possible solution to the addon documentation.
2) Remove the "rpi gpio in" or "rpi gpio out" nodes from NodeRed addon until there is a fix
3) Make changes so "rpi gpio in" or "rpi gpio out" work out of the box when people install NodeRed addon.

more information about this problem can be found here:
https://community.home-assistant.io/t/setting-gpio-output-from-nodered-is-broken/131969/7

**Comment by frenck** [comment]
> using your "my car doesn't start" metaphor, i am not asking to fix the car, i am asking to put a notice on the car saying a certain part of the car does not work so people don't get confused.

Are you serious now? You are asking to document something is broken, instead of asking and providing information to help fix things instead?! 

Wtf really.

The linked community topic post, is not related to anything uh eloung this issu

**Comment by thezeroth** [comment]
@frenck are you on something? or you just don't know what GPIO is? the link I provided is not only related but is exactly describing the issue:

https://community.home-assistant.io/t/setting-gpio-output-from-nodered-is-broken/131969

**Comment by frenck** [comment]
> @frenck are you on something? 

👋 see ya

**Comment by thezeroth** [comment]
sad to see a troll is managing the issues for this addon, he should be taken off the team.

**Comment by frenck** [comment]
> sad to see a troll is managing the issues for this addon, he should be taken off the team.

And that got you a ban. 

I'm happy to help, but I would need some good data in issue reports.

I don't owe anyone anything, and most certainly don't have to accept this behavior.
