### ISSUE TITLE
Node Red High Ram / High CPU usage - API calls fail / Web UI becomes unresponsive 

### ISSUE THREAD

**Issue by nickaggie** [hassio-addons/addon-node-red#1245]
# Problem/Motivation

After a few hours the Node-Red becomes unresponsive and all calls to HA fail.  

## Expected behavior

NodeRed to continue to run successfully

## Actual behavior

Addon slowly consumes more and more ram / CPU until API calls fail and web ui cannot open

## Steps to reproduce

Just run the add on
![image](https://user-images.githubusercontent.com/37276807/150210035-b6cb1476-f425-4ef6-bdde-4f85137d4620.png)

19 Jan 08:14:19 - [debug] [api-call-service:Turn Under Cabinet Lights On] Calling Service: switch:turn_on -- {}
19 Jan 08:14:19 - [debug] [api-call-service:Turn On Downstairs Lamps] Calling Service: switch:turn_on -- {}
19 Jan 08:14:19 - [debug] [api-call-service:Turn Christams Switches On] Calling Service: switch:turn_on -- {}
19 Jan 08:14:19 - [debug] [api-call-service:Turn Office Lamp On] Calling Service: light:turn_on -- {"brightness_pct":100}
19 Jan 09:01:22 - [debug] [time-inject:3d245e91.15b8f2] --------- time-inject - input msg={ type: 'start', timeData: {} }
19 Jan 10:32:45 - [debug] [time-inject:473bac34.f37194] --------- time-inject - input msg={ type: 'start', timeData: {} }
19 Jan 10:32:45 - [debug] [time-inject:7bc67bb8a2a1b96a] --------- time-inject - input msg={ type: 'start', timeData: {} }
19 Jan 10:32:45 - [debug] [time-inject:Inject - Kick off Awake] --------- time-inject - input msg={ type: 'start', timeData: {} }
19 Jan 11:26:16 - [debug] [api-call-service:Set Awake] Calling Service: input_boolean:turn_off -- {}
19 Jan 11:26:16 - [error] [api-call-service:Set Awake] Call-service error. 
19 Jan 11:26:16 - [debug] [api-call-service:Set Awake] Calling Service: input_boolean:turn_off -- {}
19 Jan 11:26:16 - [error] [api-call-service:Set Awake] Call-service error. 

I have disabled all downloaded pallets in NR so just operating on the base add on.  Using the most recent version on a fully updated HA instance running on Raspi4 with 4gb ram.

**Comment by nickaggie** [comment]
I have been chasing this issue for weeks running trace in the NR logs.  I cant find any smoking gun that identify where it fails.  If i check in the ram and cpu usage keeps creeping up until it eventually fails and stop responding.  If i restart NR, it will work again for a number of hours until eventually it happens again.

**Comment by Lethal83** [comment]
@nickaggie Im seeing the exact same issue. Even with watchdog on, you have to go and restart NR.  
Im running on HyperV Home Assistant OS 7.1 core-2021.12.10 Node Red  Version 10.3.4

**Comment by nickaggie** [comment]
yeah I have been slowly disabling different types of items in NR to see if I can find a trend.  Next on my list is to disable the listeners that rely on updates from my HA Android app.  @Lethal83 sorry to hear you are having the same issue, but glad to hear its not unique to me.

**Comment by Lethal83** [comment]
@nickaggie I havent got much in NR, Im using it for mapping the remotes and sensors I have using deCONZ and also MQTT from Blue Iris. Not sure if that matches any of yours.

**Comment by nickaggie** [comment]
Still happening with updated   <html>
<body>


core-2021.12.10
--



</body>
</html>

**Comment by nickaggie** [comment]
@Lethal83 I primarily use it for controlling my zwave stuff, but read values for my phone off the HA companion app, look at alarm status and weather. Most is using the default components and everything is updated so not sure where the problem is.  I notice if i restart the whole host, both ram and cpu usage start out at 0, but if i restart just the add on, CPU usage stays pegged high at 25%

**Comment by nickaggie** [comment]
Still happening on latest version of addon, HA and supervisor.   Nothing in log to indicate what is causing the issue, even with log set to debug.  Any other suggestions on what i can do to resolve this?

**Comment by Lethal83** [comment]
Sorry to hear its still happening. Mine has now cleared up. I havent updated to 10.4 of NR, Im currently on 10.3.4 and so far is stable again

**Comment by nickaggie** [comment]
@Lethal83 did you change anything or just upgrade to 10.4?

**Comment by nickaggie** [comment]
I think i solved this, it seems i had a recursive loop that was over consuming the resources.  While this isn't actually a bug for the add-on, it would be nice if over consumption of resources could be written out to the log when a verbose log_level is selected.

**Comment by Lethal83** [comment]
Nope didnt change a thing.   Glad you got yours all sorted.
