### ISSUE TITLE
Featuer Request : Map backup volume to allow nodered rclone backups

### ISSUE THREAD

**Issue by rchukka** [hassio-addons/addon-node-red#1246]
# Problem/Motivation

> To automate remote backup by using rclone installed as system package in nodedred addon config.

## Expected behavior

> Map /mnt/data/supervisor/backup to /backup as read-only

## Actual behavior

> not mapped

## Steps to reproduce

> /backup is not currently mapped, so can be reproduce by using any version.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by rchukka** [comment]
@frenck Can you please take a look at this? Thanks.

**Comment by frenck** [comment]
This has been requested and declined multiple times. See issue tracker history for more information.
