### ISSUE TITLE
Feature request : option to map a user directory

### ISSUE THREAD

**Issue by sabamimi** [hassio-addons/addon-node-red#1251]
# Problem/Motivation

> Would like to create files from node red

## Expected behavior

> be able to use "write file node" and "see" the file created somewhere in Home Assistant

## Actual behavior

> file was created (probably inside the docker) but not visible in home assistant directory structure

## Steps to reproduce

![image](https://user-images.githubusercontent.com/15199141/151366026-29d7e284-5ceb-4c21-9cc8-619d60fc5341.png)

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please clarify "user" directory?

**Comment by sabamimi** [comment]
Thanks for this quick reply....
a mapping of a directory that would allow to see the created file in the home assistant directory structure . 
(no user access rights implied)

**Comment by bonanitech** [comment]
I think you can use `/share` for that.

**Comment by sabamimi** [comment]
OK I will test and post (thanks!)

**Comment by sabamimi** [comment]
.... no joy.
![image](https://user-images.githubusercontent.com/15199141/151367551-12908e0a-58ef-4460-bd3c-d3cb40a04b64.png)

I used the full path "/share/mytest.txt" but I could not find  the file anywhere

**Comment by bonanitech** [comment]
Just tested here and it worked.

Pushed the inject button a few times.

<img width="393" alt="Screen Shot 2022-01-27 at 8 30 17 AM" src="https://user-images.githubusercontent.com/29807944/151368869-8bd8d00a-9bd7-43e5-aba7-a6e7ecbc1b88.png">

And here is the result.

<img width="560" alt="Screen Shot 2022-01-27 at 8 30 30 AM" src="https://user-images.githubusercontent.com/29807944/151368881-bf1695a5-c13f-46bf-8619-573d4ac85ffb.png">

**Comment by sabamimi** [comment]
Correct !!! 
I had to push it twice....
Thanks a lot !
