### ISSUE TITLE
Modbus does not support Node-JS 16

### ISSUE THREAD

**Issue by kurim** [hassio-addons/addon-node-red#1255]
# Problem/Motivation
node-red-contrib-modbus make problems in current version cause it does not support NodeJS 16
```log
[08:39:31] INFO: Starting installation of custom NPM/Node-RED packages...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'node-red-contrib-modbus@5.16.0',
npm WARN EBADENGINE   required: { node: '>=10 <15' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.1.3' }
npm WARN EBADENGINE }
```
## Expected behavior
Update to node-red-contrib-modbus 6.x (as soon as it is released)

## Actual behavior
node-red-contrib-modbus 5.x is included (does not support nodejs 16)

## Steps to reproduce

Install huemagic for example

## Proposed changes
disable/remove modbus 5.x for now since it will cause crashes if you use other node-red addons like huemagic,
even it is not used.

> Node-RED v2.x versions:
> 
> Node.JS 16.x will be supported with v6.+
> Node.JS 14.x is supported with v5.14.+
> Node.JS 12.x is supported with v5.x
> 
> Source:
> https://flows.nodered.org/node/node-red-contrib-modbus

**Comment by frenck** [comment]
There is not much I can do about it, Alpine Linux ships with `nodejs` 16 & 17:

<https://pkgs.alpinelinux.org/packages?name=*nodejs*&branch=v3.15>

As that is the current stable LTS version.

> Update to node-red-contrib-modbus 6.x (as soon as it is released)

Sure, we always keep up with updates. This is automated at a certain level.

> disable/remove modbus 5.x for now since it will cause crashes if you use other node-red addons like huemagic, even it is not used.

That sounds like something that should not be possible to happen. Is that a huemagic bug?

**Comment by kurim** [comment]
Not really, after disable modbus everything works fine, so it might be a unfortunate circumstances

Another thing which has nothing to do with this is another issue with 2.2.0:
https://discourse.nodered.org/t/problem-with-node-red-contrib-actionflows-since-upgrade-to-2-2-0/57368

**Comment by frenck** [comment]
Thanks, but please report issues with those nodes with the node authors. They won't be doing anything is reported here.

**Comment by kurim** [comment]
Your right
Than we close it here, thank you for your help.
