### ISSUE TITLE
Since upgrading to 10.4.0 Home Assistant Websocket API connections just shuts down.

### ISSUE THREAD

**Issue by labob246** [hassio-addons/addon-node-red#1261]
# Problem/Motivation

>Since upgrading to 10.4.0, I will get random Home Assistant Websocket API connection is closed errors.

## Expected behavior

>  Expect it to act like 10.3.6 with regard to the API connection
## Actual behavior

> Randomly the API will just shut down which of course starts a large amount of errors regarding entity could not be found in cache, Call- Service attempted without connection to server, etc.

## Steps to reproduce

>It just randomly happens. I can't force it to happen.
Running core-2022.2.0 but the problem occurred before this upgrade.  
supervisor-2022.01.1
I do run the Node-RED Companion 
Downgrading to 10.3.6 does solve the problem.  

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
[Supervisor Log.txt](https://github.com/hassio-addons/addon-node-red/files/7999930/Supervisor.Log.txt)
[Node Red log.txt](https://github.com/hassio-addons/addon-node-red/files/7999931/Node.Red.log.txt)

**Comment by martinsheldon** [comment]
I have the same issue. It seems to happen everytime I deploy changes. I'll try to downgrade to v10.3.2 as soon as my backup is finished to see if this resolves the issue. If this is not working, I'll try v10.0.1 that I also have a backup of.

**Comment by martinsheldon** [comment]
I can confirm that downgrading to v10.3.2 resolved the issue for me at least. 
I'm also running HA Core v2022.2.1

**Comment by Steve-Mcl** [comment]
I suspect the 502 error you see is due to node-red crash due to actionsflows

There is an issue on action flows (and a PR to fix it) here: https://github.com/Steveorevo/node-red-contrib-actionflows/issues/19
