### ISSUE TITLE
Crash when trying to restart or deploy the flows

### ISSUE THREAD

**Issue by StiviiK** [hassio-addons/addon-node-red#1262]
# Problem/Motivation

When I try to deploy changes or restart the flows node-red crashes.

## Steps to reproduce

Version: 10.4.0
Press restart current flows.

Error in log:

```
4 Feb 16:26:52 - [info] Stopping flows
4 Feb 16:26:52 - [info] [server:Home Assistant] Closing connection to http://supervisor/core
4 Feb 16:26:52 - [info] Stopped flows
4 Feb 16:26:52 - [info] Starting flows
4 Feb 16:26:52 - [red] Uncaught Exception:
4 Feb 16:26:52 - [error] TypeError: RED.settings.functionGlobalContext.get is not a function
    at map (/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:270:51)
    at EventEmitter.runtimeMap (/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:593:5)
    at EventEmitter.emit (node:events:390:28)
    at start (/opt/node_modules/@node-red/runtime/lib/flows/index.js:383:12)
[16:26:53] INFO: Starting Node-RED...
```

**Comment by Steve-Mcl** [comment]
There is an issue on action flows (and a PR to fix it) here: https://github.com/Steveorevo/node-red-contrib-actionflows/issues/19

**Comment by Steve-Mcl** [comment]
@Steveorevo has now published a fix for `node-red-contrib-actionflows`
V2.1.2 is now available [in the flows library](https://flows.nodered.org/node/node-red-contrib-actionflows) :+1:

**Comment by StiviiK** [comment]
Thanks for the info, will try that!

**Comment by StiviiK** [comment]
Upgrading `node-red-contrib-actionflows` to `V2.1.2` did fix the issue.
