### ISSUE TITLE
accessing dashboard via ingress is supported by a diffrent addon

### ISSUE THREAD

**Issue by regevbr** [hassio-addons/addon-node-red#1263]
# Problem/Motivation

I want to access the dashboard within HA and without exposing my node red port to the outside world.

## Expected behavior

Have a sidebar menu to access the dashboard

## Actual behavior

No way to do that currently

## Proposed changes

I created a new addon - [addon-node-red-dashboard](https://github.com/regevbr/addon-node-red-dashboard) that supports this use case. It can be beneficial to other users to document it instead of saying that it is [not possible](https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md?plain=1#L203-L206
) to access the dashboard using ingress.

@frenck thoughts?

**Comment by frenck** [comment]
It not being available is documented behavior and out of scope for this add-on, as an add-on cannot provide multiple interfaces.
