### ISSUE TITLE
V11.0.0 removed actionflow

### ISSUE THREAD

**Issue by henriklund** [hassio-addons/addon-node-red#1276]
# Problem/Motivation
V11.0.0 removed actionflow ref. #1260 due to '...due to non-maintained and errors'. 
v10.4.0 actionflow was v2.0.4, however, actionsflows was updated 4 days ago (to [v2.1.2](https://flows.nodered.org/node/node-red-contrib-actionflows))

## Expected behavior
It should be reevaluated if the package should be retained.

**Comment by sinclairpaul** [comment]
You have the option to install it with the config options <https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-npm_packages>

**Comment by henriklund** [comment]
True,  or have the updated version of actionflows installed (as I did), resulting in the upgrade to v11.0.0 not touching the actionflows package - this could also just be a result of Node-RED refusing to uninstall packages in use...

What I want to poke at is the evaluation criteria for 'unmaintained'. In the specific case #1260 was raised after an [issue](https://github.com/Steveorevo/node-red-contrib-actionflows/issues/19) was raised and approved before a updated (actionflow) version was released a few days later. The obvious question is if this is sufficient for something to be considered 'maintained'? I will not be the judge of that. From a personal PoV the actionflow package has proven very useful so far (I looked for a replacement when 10.4.0 was published, but did not find one fit for purpose). Not being part of the bundle makes the actual 'loss' less obvious for others.

I am all for housekeeping with regards to unmaintained bundled packages. My point here is just to ensure that objective criterias are applied when evaluating whether packages are maintained, or not (not insinuating that this was not the case here). Just my two cents worth :)

**Comment by sinclairpaul** [comment]
We use Github for tracking issues, it appears you don't have an issue and you are already aware of the workaround to the functionality that was removed to reduce the cost of maintenance.

> My point here is just to ensure that objective criterias are applied when evaluating whether packages are maintained, or not (not insinuating that this was not the case here). 

Again, this isn't a discussion forum, if you really wish to contribute you are welcome to discuss it on Discord, or provide a relevant Pull Request.

> Just my two cents worth :)

Which is more than anyone gets for giving their time to maintain and support this project, please do consider that before sharing your opinions.

**Comment by henriklund** [comment]
You are right. Workaround exists and as such this is not an issue. Sorry this was the wrong form for sharing an insight into an update. This was not to start a discussion nor an attempt to offense.
