### ISSUE TITLE
Time Node - Cannot read properties of undefined (reading 'hour')

### ISSUE THREAD

**Issue by JulianRichter** [hassio-addons/addon-node-red#1278]
# Problem/Motivation

After upgrading to version 11.0.0 the time node cannot trigger at a given timedate entity state anymore, but throws an error.
I rolled back to version 10.4.0 and it is working without any changes. Unless I missed a breaking change I think there is an issue with version 11.0.0.

This is how i use the time node (version 10.4.0):
![Time node setup](https://user-images.githubusercontent.com/43118476/153688925-6109b6f7-cff8-4839-8015-fa9f7bafaaa9.png)

## Expected behavior

Node should trigger at a given datetime entity state.

## Actual behavior

Error is thrown: 
cannot read properties of undefined (reading 'hour')

## Steps to reproduce

Upgrade to version 11.0.0 
Add time node to trigger at given datetime entity

**Comment by AlainBRUNEL** [comment]
Same problem for me

**Comment by sinclairpaul** [comment]
Please log this with the upstream project <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>
