### ISSUE TITLE
rbe node obsoled

### ISSUE THREAD

**Issue by hklages** [hassio-addons/addon-node-red#1279]
The node-red logs shows: 
`[node-red-node-rbe/rbe] 'rbe' already registered by module node-red`

---> Please remove package node-red-node-rbe as it is not anymore necessary.

Reason is that rbe is included in Node-RED as node filter

See post from "knolleary": 
[rbe](https://discourse.nodered.org/t/rbe-node-replaced-by-the-filter-node/55742/2)

Henning

**Comment by frenck** [comment]
`node-red-node-rbe` isn't part of this add-on, see:

<https://github.com/hassio-addons/addon-node-red/blob/main/node-red/package.json#L12>

That means it is a manually installed node.

**Comment by hklages** [comment]
right! Sorry. 
Did not recognize that. Could delete it.
