### ISSUE TITLE
Home Assistant Service Call nodes all report "API Error"

### ISSUE THREAD

**Issue by navirom** [hassio-addons/addon-node-red#1280]
# Problem/Motivation

Starting in about the last day, all service call nodes return an API error when called:
![image](https://user-images.githubusercontent.com/16004771/153721358-62a539b1-84ab-4244-84bd-04cc88dc5596.png)

Debug log for affected nodes reads "Call-service error. extra keys not allowed @ data['target']. Got {'entity_id': ['light.bedroom_a']}" for the appropriate service call

![image](https://user-images.githubusercontent.com/16004771/153721391-8beac18b-c894-4cab-92e3-8c7087be7f94.png)

## Expected behavior

Service Call nodes will operate without error

## Actual behavior

Node-Red cannot make Home Assistant service calls

## Steps to reproduce

Add a new node calling any Home Assistant service and a node injecting "1" into it. Inject into the service node.

![image](https://user-images.githubusercontent.com/16004771/153721502-9abc372d-5bf2-4f81-8a09-fa657c28f9f6.png)

I have restarted the Home Assistant instance to no avail. The issue affects nodes that I had created before yesterday as well as new nodes I create today.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Looks to be fixed upstream in the latest node-red-contrib-home-assistant-websocket releases (0.42.2)

Need to wait for a new release of the addon.

**Comment by navirom** [comment]
Thanks, it does look like some updates have taken care of the issue.

I appreciate your time and help.
