### ISSUE TITLE
Modbus node stopped working after 11.0.1

### ISSUE THREAD

**Issue by Mpgod80** [hassio-addons/addon-node-red#1285]
Modbus stopped working after the latest update of Node Red.
got this from the logg :

14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Flex-Getter] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-getter.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Write] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-write.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Flex-Write] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-write.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Server] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-server.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Flex-Server] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-server.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Queue-Info] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-queue-info.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Flex-Connector] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-connector.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-IO-Config] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-io-config.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Response-Filter] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-response-filter.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Feb 14:51:04 - [warn] [node-red-contrib-modbus/Modbus-Flex-Sequencer] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-sequencer.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js

**Comment by MaxRei-dev** [comment]
same here

**Comment by regardts-hub** [comment]
Same here, had to revert to previous version.

**Comment by KlausHans** [comment]
> Same here, had to revert to previous version.

How did you do this?

**Comment by regardts-hub** [comment]
> > Same here, had to revert to previous version.
> 
> How did you do this?
> 
> Working workaround: [BiancoRoyal/node-red-contrib-modbus#291 (comment)](https://github.com/BiancoRoyal/node-red-contrib-modbus/issues/291#issuecomment-1039663771)

Partial restore from scheduled backup

**Comment by Galapalos** [comment]
Adding lines down below to nodered addon config helped me. ( i added those lines before update)

npm_packages:
  - source-map-support
  - line-by-line

Info got from here:  https://github.com/BiancoRoyal/node-red-contrib-modbus/issues/291

**Comment by Markus667** [comment]
Hey, same here.
I'am running NodeRed on Home Assistant.
I'm not sure where to add these lines ?
Can anybody help me to fix ?
Thx

**Comment by cjj25** [comment]
> Hey, same here. I'am running NodeRed on Home Assistant. The update is already done, so i can't find the Package node-red-contrib-modbus in the node-modules Folder. I'm not sure where to add these lines ? Is it possible to reinstall the package ? In the GUI there is no option to reinstall or uninstall. Can anybody help me to fix ? Thx

Configuration -> Addons, Backup and Supervisor -> Node-RED -> Configuration 

Find: `npm_packages: []` 

Replace with:
```
npm_packages: ["source-map-support", "line-by-line"]
```

**Comment by Markus667** [comment]
Works perfect, many Thanks.
I didn't see the forest for the trees

**Comment by cjj25** [comment]
> Works perfect, many Thanks. I didn't see the forest for the trees

My pleasure, it took me a few minutes to find it too :-) 

Thanks @Galapalos for posting a fix!

**Comment by Mpgod80** [comment]
Thx, that worked even for me 🙂👍
