### ISSUE TITLE
Templating into Call Service Node

### ISSUE THREAD

**Issue by stellavision** [hassio-addons/addon-node-red#1286]
# Problem/Motivation

> Something changed and my call to a service node (climate in this case) with a template defining a value for the "temperature" has stopped working producing an API Error 

## Expected behavior

> Work as it did before.

## Actual behavior

> Generates an API Error

## Steps to reproduce

> [{"id":"e2f25f1b60c92db8","type":"inject","z":"901c0a47.917fe8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":80,"y":560,"wires":[["9cb700040f049d6e","3e55081.13731f8"]]},{"id":"3e55081.13731f8","type":"template","z":"901c0a47.917fe8","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"{\n    \"data\" : {\n    \"entity_id\" : \"climate.comfort\",\n    \"temperature\" : 20\n    }\n}","output":"str","x":280,"y":440,"wires":[["a85fb44e.1f89c8"]]},{"id":"a85fb44e.1f89c8","type":"api-call-service","z":"901c0a47.917fe8","name":"Comfort @20","server":"e59339b1.3dff98","version":4,"debugenabled":false,"domain":"climate","service":"set_temperature","target":{"areaId":[],"deviceId":[],"entityId":["climate.comfort"]},"data":"","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"data"}],"queue":"none","x":590,"y":320,"wires":[[]]},{"id":"e59339b1.3dff98","type":"server","name":"Home Assistant","version":2,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30,"credentials":{}}]

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
anything in the logs?
any information about your system and add-on?

Would be helpful 👍

**Comment by stellavision** [comment]
The API Error in the log is
"Call-service error. must contain at least one of temperature, target_temp_high, target_temp_low."
Home Assistant 2022.2.6
Node-RED Current version: 11.0.0

**Comment by bonanitech** [comment]
@stellavision set your template node to Output as Parsed JSON

<img width="335" alt="Screen Shot 2022-02-14 at 12 22 44 PM" src="https://user-images.githubusercontent.com/29807944/153914614-a55c3af4-dcb8-47e4-8efc-6a185b26c237.png">

**Comment by stellavision** [comment]
Thanks @bonanitech that did the trick. Something must have changed though as plain text worked previously.
