### ISSUE TITLE
Call service failed in node-red after update

### ISSUE THREAD

**Issue by tlalos** [hassio-addons/addon-node-red#1289]
Same error here

**Comment by rickjmatthews** [comment]
Similar issue here.

The call service node is no longer correctly retrieving the domain parameters from the payload.

This is my message going into the node:

{"_msgid":"e057ff4f89af2268","payload":"{ \"domain\": \"notify\",\n  \"service\": \"echo_devices\",\n  \"data\": {\n    \"message\": \"<voice name='Brian'>I&#39;m hungry. Give me some food.</voice>\",\n    \"data\": {\n        \"type\": \"announce\",\n        \"method\": \"all\"\n    }\n   }\n}","topic":"","voice":"Brian"}

... and this is the error message in the debug window "call service node is missing api "domain" property, not found in config or payload"

**Comment by sinclairpaul** [comment]
Likely #1287 ?
