### ISSUE TITLE
Events: State and Trigger: State nodes bugged

### ISSUE THREAD

**Issue by blackcult** [hassio-addons/addon-node-red#1291]
# Problem/Motivation

> Events: State and Trigger: State nodes don't show entity, after switch to dropdown menu.  I am not sure when exactly this happened, as it works fine after update and you notice it when changing workflows

## Expected behavior

> The entity_id should stay visible and permanent in the node view

## Actual behavior

> Entity_id resets when any change is done to Events: State and Trigger: State nodes. Plus when opened, you can't see which entity id is set

## Steps to reproduce

> Create any Events: State and Trigger: State node, select entity and deploy. When you open the node again, it won't show the entity. Also if you change anything in the node, it will actually switch to the first alphabetical entity in HA. 

## Proposed changes

> I think maybe switching back from the dropdown menu would be beneficial.

**Comment by sinclairpaul** [comment]
Issues with the Home Assistant nodes should be logged at https://github.com/zachowj/node-red-contrib-home-assistant-websocket
