### ISSUE TITLE
Wait until node don't work with list

### ISSUE THREAD

**Issue by landaisbenj** [hassio-addons/addon-node-red#1292]
# Problem/Motivation

I think wait until node work with exact entity, but don't work with list of entites. I try to make a flow, who wait my couple of windows was closed, if they was open. So "until my windows was off, wait...", with check against current state.

## Expected behavior

I have 2 windows. So i try wait until node with list of 2 binary_sensor. I would like the flow pass the node if that 2 binary_sensor was off, or wait until all them was off.

## Actual behavior

Flow never pass the node if it was in list, even one or more entities was listed. But, work fine with just 1 of this binary_sensor in one exact entity...
And by the way, « check against current state » box disappear in list mode

## Steps to reproduce

Try with this node with 1 exact sensor, and try with 1 sensor or more but in list. Like this:
![image](https://user-images.githubusercontent.com/32144431/154138943-f1951508-b2b7-4e6b-8500-aad99a5b11cd.png)

## Proposed changes

I don't know if it's a bug, but if all of the entities in list was in the state, the flow can pass the node whitout waiting...

### This work :
![image](https://user-images.githubusercontent.com/32144431/154137650-a924f2b7-4579-4113-8649-c2a5f06c46ab.png)
---

### This don’t :
![image](https://user-images.githubusercontent.com/32144431/154137681-c02335e2-3f00-4192-b87e-3ba2b37e6023.png)
---

### And so this don’t too :
![image](https://user-images.githubusercontent.com/32144431/154137703-56da791d-2033-45cc-82ff-74cdb1183f5a.png)

*Note "check against current box" disappear in the 2 last pict.*

**Comment by sinclairpaul** [comment]
Issues with the Home Assistant nodes should be logged at https://github.com/zachowj/node-red-contrib-home-assistant-websocket
