### ISSUE TITLE
Grouped media players and flows using template nodes to construct output fail beginning with 11.0.0

### ISSUE THREAD

**Issue by grantalewis** [hassio-addons/addon-node-red#1293]
# Problem/Motivation

MP3 and TTS calls sent to grouped media players and flows that construct calls using template nodes fail beginning with Node-RED 11.0.0

## Expected behavior

Same behavior as in Node-RED 10.4.0.

## Actual behavior

See above.

## Steps to reproduce

Sample flows provided here: https://community.home-assistant.io/t/home-assistant-community-add-on-node-red/55023/1036

## Proposed changes

Can verify that rolling back to Node-RED 10.4.0 fixes the issue.

**Comment by sinclairpaul** [comment]
Issues with the Home Assistant nodes should be logged at <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>
