### ISSUE TITLE
Call service node doesn’t work with mustache for entity 

### ISSUE THREAD

**Issue by kwithus** [hassio-addons/addon-node-red#1300]
# Problem/Motivation

> (Why the issue was filed) after updating to 11.03 I can no longer use mustache templates for the entity-I’d in call services, like {"entity":topic} or {"entity-id":topic} in the data field or just {topic} in the entity field

## Expected behavior

> (What you expected to happen)I like to populate the entity by a payload, using mustaches 

## Actual behavior

> (What actually happened) entering a mustache template in the entity field is not accepted (‚no resulst‘, entering the mustache template in the data field results in an API-Error

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there 👋 
It sounds to me you have an issue with the Node-RED node for Home Assistant (which is shipped with the add-on). You can find their issue tracker here: https://github.com/zachowj/node-red-contrib-home-assistant-websocket
