### ISSUE TITLE
Weird ui-behavoiur?

### ISSUE THREAD

**Issue by strelniece** [hassio-addons/addon-node-red#1306]
just upgraded to 11.0.3 and love the new alternatives for selecting what entities to select.

But...

When I try the list-option, they will align horisontally, wich makes it rater hard to manage. I hope you get an idea from the picture, it stretches so much it hardly fit on the screen, and that is just two entities.

Tried with the three browsers I have, Vivaldi , chromium and Firefox, all with the same result.

And a question/request, in "call service" there is now a possibility so select area, are there plans to adapt that to other nodes as well, like get status?

![image](https://user-images.githubusercontent.com/11967825/155189619-6821c124-05fa-43fc-b98e-d52a06f9c406.png)

**Comment by stasjminister** [comment]
I have the same issue after updating. But I have only seen it in the "call service"-node:

![image](https://user-images.githubusercontent.com/11752970/158768800-0355a811-49f4-4ff5-b557-2225f219c5ab.png)

**Comment by stasjminister** [comment]
@strelniece did you resolve this somehow?
