### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by jakadia** [hassio-addons/addon-node-red#1307]
Ever since the last update (11.0.3), node-red constantly cycles through the startup loop.  I can not make out from the logs what is telling it to restart

Logs - 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 11.0.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.2.9
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1162 (offset 631 lines).
23 Feb 15:53:57 - [warn] Projects disabled : editorTheme.projects.enabled=false
23 Feb 15:53:57 - [info] Flows file     : /config/node-red/flows.json
23 Feb 15:53:57 - [info] Server now running at http://127.0.0.1:46836/
23 Feb 15:53:57 - [info] Starting flows
23 Feb 15:53:58 - [info] Started flows
(node:581) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
23 Feb 15:53:59 - [info] [mqtt-broker:HA Addon MQTT] Connected to broker: mqtt://192.168.5.50:1883
23 Feb 15:53:59 - [info] [mqtt-broker:fde6627f.aafb4] Connected to broker: mqtt://nam1.cloud.thethings.network:1883
23 Feb 15:53:59 - [red] Uncaught Exception:
23 Feb 15:53:59 - [error] Error: HTTP error 400 from https://api.particle.io/oauth/token - The grant type is unauthorised for this client_id
    at fn (/config/node-red/node_modules/particle-api-js/src/Agent.js:130:20)
    at Request.callback (/config/node-red/node_modules/superagent/src/node/index.js:902:3)
    at fn (/config/node-red/node_modules/superagent/src/node/index.js:1129:18)
    at IncomingMessage.<anonymous> (/config/node-red/node_modules/superagent/src/node/parsers/json.js:19:7)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[15:53:59] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
23 Feb 15:54:00 - [info] 
Welcome to Node-RED
===================
23 Feb 15:54:00 - [info] Node-RED version: v2.2.1
23 Feb 15:54:00 - [info] Node.js  version: v16.14.0
23 Feb 15:54:00 - [info] Linux 5.10.98 x64 LE
23 Feb 15:54:00 - [info] Loading palette nodes
Missing ENV var CONFIG_PATH
23 Feb 15:54:03 - [info] Dashboard version 3.1.5 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
23 Feb 15:54:04 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
23 Feb 15:54:04 - [warn] ------------------------------------------------------
23 Feb 15:54:04 - [warn] [node-red-contrib-ttn/ttn-app] Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v93-linux-x64-musl
Found: [node-v83-linux-x64-musl]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/config/node-red/node_modules/grpc/src/node/extension_binary/node-v93-linux-x64-musl/grpc_node.node'
Require stack:
- /config/node-red/node_modules/grpc/src/grpc_extension.js
- /config/node-red/node_modules/grpc/src/client_interceptors.js
- /config/node-red/node_modules/grpc/src/client.js
- /config/node-red/node_modules/grpc/index.js
- /config/node-red/node_modules/ttn/dist/discovery/discovery.js
- /config/node-red/node_modules/ttn/dist/discovery/index.js
- /config/node-red/node_modules/ttn/dist/handler/handler.js
- /config/node-red/node_modules/ttn/dist/handler/index.js
- /config/node-red/node_modules/ttn/dist/index.js
- /config/node-red/node_modules/node-red-contrib-ttn/ttn-app/ttn-app.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
23 Feb 15:54:04 - [warn] ------------------------------------------------------
23 Feb 15:54:04 - [info] Settings file  : /etc/node-red/config.js
23 Feb 15:54:04 - [info] Context store  : 'default' [module=memory]
23 Feb 15:54:04 - [info] User directory : /config/node-red/
23 Feb 15:54:04 - [warn] Projects disabled : editorTheme.projects.enabled=false
23 Feb 15:54:04 - [info] Flows file     : /config/node-red/flows.json
23 Feb 15:54:04 - [info] Server now running at http://127.0.0.1:46836/
23 Feb 15:54:04 - [info] Starting flows
23 Feb 15:54:05 - [info] Started flows
(node:636) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
23 Feb 15:54:05 - [info] [mqtt-broker:HA Addon MQTT] Connected to broker: mqtt://192.168.5.50:1883
23 Feb 15:54:06 - [info] [mqtt-broker:fde6627f.aafb4] Connected to broker: mqtt://nam1.cloud.thethings.network:1883
23 Feb 15:54:06 - [red] Uncaught Exception:
23 Feb 15:54:06 - [error] Error: HTTP error 400 from https://api.particle.io/oauth/token - The grant type is unauthorised for this client_id
    at fn (/config/node-red/node_modules/particle-api-js/src/Agent.js:130:20)
    at Request.callback (/config/node-red/node_modules/superagent/src/node/index.js:902:3)
    at fn (/config/node-red/node_modules/superagent/src/node/index.js:1129:18)
    at IncomingMessage.<anonymous> (/config/node-red/node_modules/superagent/src/node/parsers/json.js:19:7)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[15:54:06] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
23 Feb 15:54:07 - [info] 
Welcome to Node-RED
===================
23 Feb 15:54:07 - [info] Node-RED version: v2.2.1
23 Feb 15:54:07 - [info] Node.js  version: v16.14.0
23 Feb 15:54:07 - [info] Linux 5.10.98 x64 LE
23 Feb 15:54:07 - [info] Loading palette nodes

Config - 
certfile: fullchain.pem
credential_secret: ???????????????????
http_node:
  password: ''
  username: ''
http_static:
  password: ''
  username: ''
init_commands: []
keyfile: privkey.pem
npm_packages: []
ssl: false
system_packages: []
theme: default

**Comment by sinclairpaul** [comment]
Looks to be the Particle Palette you have installed, you should be able to set safe mode https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-safe_mode

Then restart the addon, and remove the selected flow.  Also would recommend using the npm_packages option for installing custom palettes.

**Comment by jakadia** [comment]
Thanks for the response. I will give it a try.  When you say custom palette, do you mean anything in the manage palette part of node red where i use the install feature? This is my first time asking for help in the 3 years I’ve used home assistant so I appreciate the help!  I will let you know how it goes.

**Comment by sinclairpaul** [comment]
For example:

```
npm_packages:
  - '@particle/node-red-contrib-particle-official'
```

This would mean it's updated on every restart, though you could always pin versions.  It isn't so much of an issue now as we added the safe mode.

**Comment by jakadia** [comment]
I was able to delete the Particle palette after starting in safe mode and restart with no problems.  I downloaded the palette again and everything seems to be working. Weird, but good to know.  Thanks for the help!
