### ISSUE TITLE
 NodeRed boot-loops if a device not present

### ISSUE THREAD

**Issue by lockheed** [hassio-addons/addon-node-red#1313]
# Problem/Motivation

Brought down my entire home automation.

## Expected behavior

Automation to continue working

## Actual behavior

All automation stopped working due to NodeRed bootlooping.

## Steps to reproduce

Offline or change IP of a Xiaomi Miio device (in my case - humidifier). 
This causes NodeRed to throw out an error upon boot and restart the boot process

## Proposed changes

Obviously, this is a grave bug. If a device is absent, NodeRed should just ignore it and start normally so that it can provide automation for the reminder of devices.

### Details:
I discovered yesterday, that NodeRed (in HA installation) will not start if xiaomi.miio module cannot connect to an IP of one of the devices (humidifier in my case), either because it was unplugged or its IP has changed. NodeRed will bootloop perpetually. I wasted a day of restoring backups and snapshots of the Home Assistant VM to finally identify why my whole home automation didn't work.

I think this is a pretty grave bug if absence of one device renders the entire home automation dead.

NodeRed: 11.0.3 & 11.0.4

**Comment by frenck** [comment]
This is an issue with the xiaomi.miio module not handling errors correctly and taking down node-red.

From an add-on perspective, there is nothing I can do about this. Please report this with the module/node project that provides the nodes for this.

../Frenck

**Comment by lockheed** [comment]
Sorry, but if a faulty add-on can take down entire NodeRed, there is a problem with NodeRed not having a protection against it.

**Comment by frenck** [comment]
In that case, it would be an issue/feature request for Node-RED.
As above, the add-on cannot do anything about it. All we can do, is restart Node-RED when it dies (which we do when the watchdog feature is enabled).
