### ISSUE TITLE
Cant uninstall/re-install

### ISSUE THREAD

**Issue by geidorei** [hassio-addons/addon-node-red#1321]
Need to uninstall and reinstall at getting a 404 error. When I try to uninstall I get the following error:

Can’t remove image joshgetter/armhf-home-assistant-nodered: 400 Client Error for http+docker://localhost/v1.41/images/joshgetter/armhf-home-assistant-nodered:?force=True&noprune=False: Bad Request (“invalid reference format”)

I have also tried to delete manually but it still says it is installed and now showing an update is available, which won’t go away!

Any ideas folks?

**Comment by frenck** [comment]
I have no idea, this is out of scope for the add-on (as in, the add-on itself isn't involved there / I cannot do anything on that part from an add-on perspective).

Please report the issue with Home Assistant Supervisor project instead.
