### ISSUE TITLE
Error when update from 11.0.3 to 11.1.0

### ISSUE THREAD

**Issue by Napster589** [hassio-addons/addon-node-red#1323]
Hi 
I get this error and can't acces nodered:

`[error] 621#621: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.1, server: a0d7b954-nodered, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:46836/", host: `

What can i do ?
Kind regards

**Comment by cinghialino** [comment]
I have updated to a newer version a few ays after this happened and now it's working again. thanks
