### ISSUE TITLE
NodeRed keeps becoming unresponsive, requiring STOP and START manually

### ISSUE THREAD

**Issue by derekcfoley** [hassio-addons/addon-node-red#1331]
# Problem/Motivation
I've noticed since the last couple of versions of NodeRed, that the add-on becomes unresponsive, with lots of "deploy" actions failing with Error 502, and many nodes just not running at all, and entire flows being unresponsive until the add-on control is manually stopped and started. 

The "watchdog" option isn't working to resolve this either.

Don't know if this is HA (current version being run on my Pi) or NodeRed causing it.

Also seeing "bad gateway" a lot too when going to my node-red option on the HA sidebar.

## Expected behavior
Normal behaviour during deploy, and proper running of flows.

## Steps to reproduce
Deploy changes to more complex/multiple flows.

Watch the "connecting" states on trigger nodes as you deploy... if they take a long time to show "connected" then you'll probably find your entire set of flows aren't running, requiring a restart of the add-on. This is also usually when the deploy option fails after edits, usually taking 2-3 attempts to work, or following a manual stop and start of the add-on.

**Comment by frenck** [comment]
It isn't normal, but there is zero information provided that allows to debug the situation.

**Comment by frenck** [comment]
@Cl3tus The Node-RED add-on is not part of the Home Assistant Core and should thus not be reported @ that issue tracker...

**Comment by Cl3tus** [comment]
@frenck i know that, but i had troubles in my mind in which section in belongs due to the nature that it happens after the 2022.4.0 upgrade, reverting to 2022.3.8 helps in getting Node-RED working again. Because of the fact it was due to updating to the newest core i choose that path. But all madness on a stick. :) Where can i report this issue, do you want me to report it here? Do you want me to close it there and reopen here? I would like to solve the issue and get to 2022.4.1 :)

**Comment by frenck** [comment]
> i'm having the same issue, reported after the 2022.3.8 upgrade to 2022.4.0 and 2022.4.1.

The core issue is going to be closed, as it's not a problem for the core.

**Comment by frenck** [comment]
> do you want me to lift on this thread

I'm not sure what this issue is about, as there are zero details provided by the issue author.

**Comment by derekcfoley** [comment]
Ok, I've checked the logs on the add-on. Basically when this issue happens, the node-red plugin is continually rebooting and restarting. I keep seeing the "starting node-red" message in the logs when I hit refresh, and pages and pages of stuff. None of which I want to post here because of hacking risks.

**Comment by derekcfoley** [comment]
I think its something to do with the watchdog playing up and uneccesarily rebooting the add-on. I've turned it off and got it working in terms of deployment and debugging flows.

**Comment by derekcfoley** [comment]
Its not that. I've turned off the auto-update feature now. From what I can see its taking several minutes for nodeRed to startup now after restarting several times.

**Comment by derekcfoley** [comment]
2022/04/12 19:02:38 [error] 587#587: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "#########.duckdns.org:8123"

**Comment by derekcfoley** [comment]
12 Apr 19:02:34 - [red] Uncaught Exception:
12 Apr 19:02:34 - [error] TypeError: Cannot read properties of null (reading '1')
    at /config/node-red/node_modules/alexa-cookie2/alexa-cookie.js:326:97
    at IncomingMessage.<anonymous> (/config/node-red/node_modules/alexa-cookie2/alexa-cookie.js:111:33)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[19:02:34] INFO: Starting Node-RED...
2022/04/12 19:02:36 [error] 587#587: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "#########.duckdns.org:8123"
> start

**Comment by derekcfoley** [comment]
Nodered version: 11.1.1 
Version | core-2022.4.2
Installation Type | Home Assistant OS

**Comment by Cl3tus** [comment]
Just out of curiosity, my Node-RED issues are gone when reverting back to 2022.3.8 what happens on your install if you do that?

**Comment by mash2k3** [comment]
if you replace all the ha-device (pink)nodes just the action type (trigger type is fine), it resolves the restart issue. I have been now using version 2022.4.2 for over 24 hours

**Comment by Cl3tus** [comment]
Not really an option i would say more of a workaround till its fixed. But i'm not really eager to change all my nodes in my flows...

**Comment by dezral** [comment]
From what i can see it's the home assistant nodes, not node-red (node-red addon for integrering with home assistant).

https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket

**Comment by dezral** [comment]
The issue is still there and either ha addons should be removed from ha-node-red or be fixet..
