### ISSUE TITLE
Custom home assistant attributes are no longer exposed to home assistant

### ISSUE THREAD

**Issue by DominicWindisch** [hassio-addons/addon-node-red#1336]
# Problem/Motivation

HomeAssistant atrributes of entities created in node-red are no longer visible in Home Assistant. This worked find in the past (ha 2022.3.8 with node-red 11.1.1).

## Expected behavior

Attributes should be visible in Home Assistant.

## Actual behavior

Attributes added to entities in node-red are not visible in Home Assistant (give "undefined")

## Steps to reproduce
- running home assistant 2022.4.5, node-red 11.1.1
- add entity in node-red
- edit entity, add custom "home assistant attribute"
- save
- go to home assistant, view the created entity
- => entity and state are there, the attributes are not
- update entity from node red flow (e.g. energy meter count)
- go to home assistant, view created entity
- => state changed fine, attributes still not defined

**Comment by frenck** [comment]
The add-on does not expose attributes to Home Assistant. It is also against the design guides lines of Home Assistant.

I guess you are confusing the add-on with the Home Assistant Node-RED custom integration.
