### ISSUE TITLE
After update to 11.1.1 random connection errors.

### ISSUE THREAD

**Issue by BohdanGut** [hassio-addons/addon-node-red#1341]
when i deploy it shows "502 bad gateway" but when i click several times it will finaly deploy. it not depends how long i wait. it is per try. you deploy or no. i can fast click several times and it will filany deploy.

thesame goes for my flows.  simple flow with inject node and call service (light switch) node works thesame. 
when i click inject I have two options it will work or it will get me error 
"Call-Service attempted without connection to server."

and after that i can click and it will turn of/on severat times and than again it it will throw me an error.
it looks like connection/responsiveness  problem but i have my HA on mashine with lots of computing power.
can any one help? what logs you need?

**Comment by BohdanGut** [comment]
it looks like nodered is restarting every fiew seconds. this is from logs

Welcome to Node-RED
===================
8 May 04:56:57 - [info] Node-RED version: v2.2.2
8 May 04:56:57 - [info] Node.js  version: v16.14.2
8 May 04:56:57 - [info] Linux 5.10.108 x64 LE
8 May 04:56:58 - [info] Loading palette nodes
8 May 04:56:59 - [info] Dashboard version 3.1.6 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
8 May 04:56:59 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
8 May 04:56:59 - [info] Settings file  : /etc/node-red/config.js
8 May 04:56:59 - [info] Context store  : 'memoryOnly' [module=memory]
8 May 04:56:59 - [info] Context store  : 'default' [module=localfilesystem]
8 May 04:56:59 - [info] User directory : /config/node-red/
8 May 04:56:59 - [warn] Projects disabled : editorTheme.projects.enabled=false
8 May 04:56:59 - [info] Flows file     : /config/node-red/flows.json
8 May 04:56:59 - [info] Server now running at http://127.0.0.1:46836/
8 May 04:56:59 - [info] Starting flows
8 May 04:56:59 - [info] Started flows
8 May 04:56:59 - [info] [server:Home Assistant] Connecting to http://supervisor/core
8 May 04:56:59 - [info] [server:Home Assistant] Connected to http://supervisor/core
8 May 04:57:09 - [red] Uncaught Exception:
8 May 04:57:09 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "No device".
[04:57:09] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
8 May 04:57:10 - [info] 
Welcome to Node-RED
===================
8 May 04:57:10 - [info] Node-RED version: v2.2.2
8 May 04:57:10 - [info] Node.js  version: v16.14.2
8 May 04:57:10 - [info] Linux 5.10.108 x64 LE
8 May 04:57:10 - [info] Loading palette nodes
8 May 04:57:11 - [info] Dashboard version 3.1.6 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
8 May 04:57:11 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
8 May 04:57:11 - [info] Settings file  : /etc/node-red/config.js
8 May 04:57:11 - [info] Context store  : 'memoryOnly' [module=memory]
8 May 04:57:11 - [info] Context store  : 'default' [module=localfilesystem]
8 May 04:57:11 - [info] User directory : /config/node-red/
8 May 04:57:11 - [warn] Projects disabled : editorTheme.projects.enabled=false
8 May 04:57:11 - [info] Flows file     : /config/node-red/flows.json
8 May 04:57:11 - [info] Server now running at http://127.0.0.1:46836/
8 May 04:57:11 - [info] Starting flows
8 May 04:57:11 - [info] Started flows
8 May 04:57:11 - [info] [server:Home Assistant] Connecting to http://supervisor/core
8 May 04:57:11 - [info] [server:Home Assistant] Connected to http://supervisor/core
8 May 04:57:21 - [red] Uncaught Exception:
8 May 04:57:21 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "No device".
[04:57:21] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
8 May 04:57:22 - [info] 
Welcome to Node-RED
===================
8 May 04:57:22 - [info] Node-RED version: v2.2.2
8 May 04:57:22 - [info] Node.js  version: v16.14.2
8 May 04:57:22 - [info] Linux 5.10.108 x64 LE
8 May 04:57:22 - [info] Loading palette nodes
8 May 04:57:23 - [info] Dashboard version 3.1.6 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
8 May 04:57:23 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
8 May 04:57:24 - [info] Settings file  : /etc/node-red/config.js
8 May 04:57:24 - [info] Context store  : 'memoryOnly' [module=memory]
8 May 04:57:24 - [info] Context store  : 'default' [module=localfilesystem]
8 May 04:57:24 - [info] User directory : /config/node-red/
8 May 04:57:24 - [warn] Projects disabled : editorTheme.projects.enabled=false
8 May 04:57:24 - [info] Flows file     : /config/node-red/flows.json
8 May 04:57:24 - [info] Server now running at http://127.0.0.1:46836/
8 May 04:57:24 - [info] Starting flows
8 May 04:57:24 - [info] Started flows
8 May 04:57:24 - [info] [server:Home Assistant] Connecting to http://supervisor/core
8 May 04:57:24 - [info] [server:Home Assistant] Connected to http://supervisor/core

**Comment by martinwheeler** [comment]
> it looks like nodered is restarting every fiew seconds. this is from logs

I am also having this problem and it is restarting every few seconds, I am getting the same `UnhandledPromiseRejection` as is seen in your log output.

```
[22:03:30] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
8 May 22:03:34 - [info] 
Welcome to Node-RED
===================
8 May 22:03:34 - [info] Node-RED version: v2.2.2
8 May 22:03:34 - [info] Node.js  version: v16.14.2
8 May 22:03:34 - [info] Linux 5.15.32-v8 arm64 LE
8 May 22:03:35 - [info] Loading palette nodes
8 May 22:03:40 - [info] Dashboard version 3.1.6 started at /endpoint/ui
8 May 22:03:42 - [info] Settings file  : /etc/node-red/config.js
8 May 22:03:42 - [info] Context store  : 'default' [module=memory]
8 May 22:03:42 - [info] User directory : /config/node-red/
8 May 22:03:42 - [warn] Projects disabled : editorTheme.projects.enabled=false
8 May 22:03:42 - [info] Flows file     : /config/node-red/flows.json
8 May 22:03:42 - [info] Server now running at http://127.0.0.1:46836/
8 May 22:03:42 - [info] Starting flows
8 May 22:03:43 - [info] Started flows
8 May 22:03:43 - [info] [mqtt-broker:71453b40eec58090] Connected to broker: mqtt://127.0.0.1:1883
8 May 22:03:47 - [info] [server:Home Assistant] Connecting to http://supervisor/core
8 May 22:03:47 - [info] [server:Home Assistant] Connected to http://supervisor/core
8 May 22:03:48 - [red] Uncaught Exception:
8 May 22:03:48 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[22:03:48] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
8 May 22:03:52 - [info] 
Welcome to Node-RED
===================```

**Comment by martinwheeler** [comment]
Hey @BohdanGut, after doing some research into the error I found someone having the same problem https://community.home-assistant.io/t/node-red-crashes-when-i-activate-a-home-assistant-node/363760

I followed their steps of disabling all nodes and I am no longer getting the `UnhandledPromiseRejection` error and Node Red isn't restarting non-stop anymore. I am just slowly re-enabling a hand full of nodes at a time to see which one is giving me this problem.

Hope this helps you fix your error too.

**Comment by BohdanGut** [comment]
@martinwheeler
i have one more thing to add in your search. i setuo eparate container in my unraid server with nodered. i used this image nodered/node-red

after install i used node-red-contrib-home-assistant-websocket to connect to my homeassistant API. and it seems connected becouse i can read all enteties and so on. BUT 

when a use node injest and node call service to switch light on and of it returns 

"Call-Service attempted without connection to server."
and it tries to reconect to my HomeAssistant again. 

for me it seems like API problem. something was hanged in new version and was broken. we should look not in nodered but in HA api.

**Comment by martinwheeler** [comment]
> @martinwheeler i have one more thing to add in your search. i setup separate container in my unraid server with nodered. i used this image nodered/node-red
> 
> after install i used node-red-contrib-home-assistant-websocket to connect to my homeassistant API. and it seems connected becouse i can read all enteties and so on. BUT
> 
> when a use node inject and node call service to switch light on and of it returns
> 
> "Call-Service attempted without connection to server." and it tries to reconect to my HomeAssistant again.
> 
> for me it seems like API problem. something was changed in new version and was broken. we should look not in nodered but in HA api.
> 
> if you want i can post screan recording from what i do. so you could see where problem is

Its probably best if you post this issue into the repository for `node-red-contrib-home-assistant-websocket` as the people over there will be much more help and have probably seen this issue before.

All the best with getting it working 🤞

**Comment by BohdanGut** [comment]
i have found the issue. in my case it was bad (outdated) connection to my roborock vacum cleaner. polling was set to 10 sec. co .... nodered restarted every 10 sec. too 

this section in logs was indicating my error
8 May 22:03:48 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".

to everyone who have this problem try at first disable all connections to external server/devices in nodred. for all who dont know how to do this look at attached movie how to debug nodered.
[https://youtu.be/ScJrYLeoI3s](url)
