### ISSUE TITLE
Sensor Attributes

### ISSUE THREAD

**Issue by fencer** [hassio-addons/addon-node-red#1342]
Running Node-RED version 11.1.1 the sensor attributes are not being updated. Used to work in the past but not sure when it stopped working.

**Comment by frenck** [comment]
I'm not sure what you mean by this? Which sensor attributes?

**Comment by frenck** [comment]
As far as I am aware, Home Assistant doesn't send all attribute on each state update anymore (by default).

That said, this is not an add-on issue, but an issue for the Node providing the Home Assistant connection with Node-RED.

You can find that project (and its issue tracker), here:

<https://zachowj.github.io/node-red-contrib-home-assistant-websocket/>

../Frenck
