### ISSUE TITLE
NODE Red Error "Bad Gateway"

### ISSUE THREAD

**Issue by cisco351** [hassio-addons/addon-node-red#1352]
I am unable to access NODE RED in Home assistant. I receive 502 Bad Gateway error. 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 11.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.1  (aarch64 / odroid-n2)
 Home Assistant Core: 2022.5.5
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
npm ERR! Cannot convert undefined or null to object
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-27T23_23_17_824Z-debug.log
[16:23:17] FATAL: Failed un-installing conflicting packages
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Version of HA
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1

**Comment by frenck** [comment]
`[16:23:17] FATAL: Failed un-installing conflicting packages`

It found manually installed conflicting packages, which it can't fix automatically. The add-on cannot start with that. You need to clean up your Node-RED configuration folder/environment.

Did you migrate from an another installation?

**Comment by cisco351** [comment]
I finally got it working. I tried logging in, in safe mode that didn’t work. I tried removing and reinstalling node red that didn’t work. I reverted back to an older back up version of HA, that didn’t work. Finally, I was able to get it working but I am not sure if this is the correct way to fix it. Here is what I ended up doing. I stopped the program from running. I backed up my flows file so I would not lose my automations. (flows.json) I then uninstalled the program in home assistant. This does not remove all files. I then accessed the node-red folder and deleted the package.json and package-lock.json files by backing them up to another folder just in case. I then restarted home assistant and reinstalled node-red. After this everything appears to be working normal. I hope this is helpful.

**Comment by ternzer** [comment]
thank you. your instructions finally fixed my problem with states not updating after a period of time.

**Comment by tiagomaricate** [comment]
I just installed HA and Node-RED. Everything is a fresh installation.
When I try to execute Node-RED, _502: Bad Gateway_.
I saw several workarounds and possible fixes.
Nothing worked for me.
Uninstalled and reinstalled.
Same problem: _502: Bad Gateway_

**Comment by tiagomaricate** [comment]
@frenck
