### ISSUE TITLE
Stange ERROR in Supervisor Logs

### ISSUE THREAD

**Issue by SP410** [hassio-addons/addon-node-red#136]
# Problem/Motivation

> Un-expected error in Supervisor Logs: 
19-02-20 01:48:24 ERROR (SyncWorker_4) [hassio.docker] Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyUSB1": no such file or directory")

## Expected behavior

> Just want to report as I am not sure if nodered is intended to connect to local usb devices.  

Here is my System Health data: 

arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.6.6
timezone | America/Chicago
version | 0.87.1
virtualenv | false

**Comment by frenck** [comment]
Not something I can do anything about, please report this to Hass.io. Thanks.
