### ISSUE TITLE
v12.0.0 return 502: Bad Gateway (FATAL: Failed installing system package python2)

### ISSUE THREAD

**Issue by sergeygalkin** [hassio-addons/addon-node-red#1363]
# Problem/Motivation

v12.0.0 return 502 502: Bad Gateway

## Steps to reproduce

update core to 2022.6.4 and  node red to v12.0.0 

## Logs

cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
v3.16.0-99-g5b6c75ce95 [https://dl-cdn.alpinelinux.org/alpine/v3.16/main]
v3.16.0-108-ge392af4f2e [https://dl-cdn.alpinelinux.org/alpine/v3.16/community]
OK: 16877 distinct packages available
(1/65) Installing sdl2 (2.0.22-r0)
(2/65) Installing libxau (1.0.9-r0)
(3/65) Installing libxdmcp (1.1.3-r0)
(4/65) Installing libxcb (1.15-r0)
(5/65) Installing libx11 (1.8-r0)
(6/65) Installing aom-libs (3.3.0-r0)
(7/65) Installing alsa-lib (1.2.6.1-r0)
(8/65) Installing libbz2 (1.0.8-r1)
(9/65) Installing libpng (1.6.37-r1)
(10/65) Installing freetype (2.12.1-r0)
(11/65) Installing fontconfig (2.14.0-r0)
(12/65) Installing fribidi (1.0.12-r0)
(13/65) Installing libffi (3.4.2-r1)
(14/65) Installing libintl (0.21-r2)
(15/65) Installing libblkid (2.38-r1)
(16/65) Installing libmount (2.38-r1)
(17/65) Installing glib (2.72.1-r0)
(18/65) Installing graphite2 (1.3.14-r1)
(19/65) Installing harfbuzz (4.3.0-r0)
(20/65) Installing libass (0.16.0-r0)
(21/65) Installing libdav1d (1.0.0-r0)
(22/65) Installing libdrm (2.4.110-r0)
(23/65) Installing gmp (6.2.1-r2)
(24/65) Installing nettle (3.7.3-r0)
(25/65) Installing p11-kit (0.24.1-r0)
(26/65) Installing libtasn1 (4.18.0-r0)
(27/65) Installing libunistring (1.0-r0)
(28/65) Installing gnutls (3.7.6-r0)
(29/65) Installing lame (3.100-r0)
(30/65) Installing opus (1.3.1-r1)
(31/65) Installing libasyncns (0.8-r1)
(32/65) Installing dbus-libs (1.14.0-r1)
(33/65) Installing libltdl (2.4.7-r0)
(34/65) Installing orc (0.4.32-r0)
(35/65) Installing libogg (1.3.5-r1)
(36/65) Installing flac (1.3.4-r0)
(37/65) Installing libvorbis (1.3.7-r0)
(38/65) Installing libsndfile (1.1.0-r0)
(39/65) Installing libgomp (11.2.1_git20220219-r2)
(40/65) Installing soxr (0.1.3-r2)
(41/65) Installing speexdsp (1.2.0-r0)
(42/65) Installing tdb-libs (1.4.6-r0)
(43/65) Installing libpulse (15.0-r2)
(44/65) Installing cjson (1.7.15-r3)
(45/65) Installing mbedtls (2.28.0-r0)
(46/65) Installing librist (0.2.6-r1)
(47/65) Installing libsrt (1.4.4-r0)
(48/65) Installing libssh (0.9.6-r1)
(49/65) Installing libtheora (1.1.1-r16)
(50/65) Installing libjpeg-turbo (2.1.3-r1)
(51/65) Installing v4l-utils-libs (1.22.1-r1)
(52/65) Installing libxext (1.3.4-r0)
(53/65) Installing libxfixes (6.0.0-r0)
(54/65) Installing wayland-libs-client (1.20.0-r0)
(55/65) Installing libva (2.14.0-r0)
(56/65) Installing libvdpau (1.5-r0)
(57/65) Installing vidstab (1.1.0-r1)
(58/65) Installing libvpx (1.11.0-r1)
(59/65) Installing libwebp (1.2.2-r0)
(60/65) Installing x264-libs (0.163_git20210613-r0)
(61/65) Installing numactl (2.0.14-r0)
(62/65) Installing x265-libs (3.5-r3)
(63/65) Installing xvidcore (1.3.7-r1)
(64/65) Installing ffmpeg-libs (5.0.1-r1)
(65/65) Installing ffmpeg (5.0.1-r1)
Executing busybox-1.35.0-r13.trigger
OK: 176 MiB in 108 packages
(1/1) Installing make (4.3-r0)
Executing busybox-1.35.0-r13.trigger
OK: 176 MiB in 109 packages
(1/9) Installing binutils (2.38-r2)
(2/9) Installing libatomic (11.2.1_git20220219-r2)
(3/9) Installing isl22 (0.22-r0)
(4/9) Installing mpfr4 (4.1.0-r0)
(5/9) Installing mpc1 (1.2.1-r0)
(6/9) Installing gcc (11.2.1_git20220219-r2)
(7/9) Installing musl-dev (1.2.3-r0)
(8/9) Installing libc-dev (0.7.2-r3)
(9/9) Installing g++ (11.2.1_git20220219-r2)
Executing busybox-1.35.0-r13.trigger
OK: 357 MiB in 118 packages
OK: 357 MiB in 118 packages
  python2 (no such package):
ERROR: unable to select packages:
    required by: world[python2]
[15:00:00] FATAL: Failed installing system package python2
cont-init: info: /etc/cont-init.d/customizations.sh exited 1
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).

**Comment by frenck** [comment]
The `python2` package no longer exists in Alpine Linux 3.16, Python 2 is really old:

<https://pkgs.alpinelinux.org/packages?name=python2&branch=v3.16>

What is your add-on configuration? What do you need Python 2 for?

**Comment by sergeygalkin** [comment]
Hi @frenck 
I can't find any specific configuration for python2
As I remember I have created configuration in UI and forgot about it :)
where I can find dependencies list  ?

**Comment by frenck** [comment]
The add-on itself doesn't use `python2`, the logs say its triggered by:

`cont-init: info: running /etc/cont-init.d/customizations.sh`

which means it is in your add-on configuration (go to the add-on, configuration tab).

**Comment by sergeygalkin** [comment]
Thanks a lot @frenck 
I have found this dependency
