### ISSUE TITLE
Image ghcr.io/hassio-addons/node-red/armv7:12.0.1 does not exist

### ISSUE THREAD

**Issue by tomroeleveld** [hassio-addons/addon-node-red#1364]
After the update of NodeRed 12.0.1 the addon is unable to start on my Raspberry Pi. When trying to start, the following message is presented: "Image ghcr.io/hassio-addons/node-red/armv7:12.0.1 does not exist for addon_a0d7b954_nodered". Seems like the image for ARM based CPU's is missing.

**Comment by frenck** [comment]
The beauty of those messages is that they contain URLs:

<https://ghcr.io/hassio-addons/node-red/armv7:12.0.1>

Showing it does exist and has been downloaded 180 times since the release just a moment ago:

![CleanShot 2022-06-08 at 16 09 21](https://user-images.githubusercontent.com/195327/172638105-f1c246ae-f8df-4add-b168-0a9c4939f521.png)

**Comment by jdavis7765** [comment]
Same issue here after update. What would be the best way to fix this?
![image](https://user-images.githubusercontent.com/56777131/172641663-75aa6d18-298b-4d96-ad23-b912534f3440.png)

**Comment by frenck** [comment]
> downloading the correct Docker image manually

You should **never** do that on a supervisor enabled system.

**Comment by frenck** [comment]
Simple test on my desktop:

![image](https://user-images.githubusercontent.com/195327/172642608-f44737b4-e446-4c68-a878-bd78bdc5bccf.png)

🤷

**Comment by jdavis7765** [comment]
So, what can I do to fix this? I have had no issues with nodered ever and now I cannot start. Nothing in the logs, only this message when I go to start the addon. I have not changed any configurations on my end either. Should I uninstall and reinstall and try to restore my config for it?

**Comment by frenck** [comment]
You can try running `ha supervisor repair` from the terminal

**Comment by jdavis7765** [comment]
`ha supervisor repair` fixed it all up, thanks!

**Comment by frenck** [comment]
Alright, great! 👍
