### ISSUE TITLE
Node Red not working at  all after update to 12.0.1

### ISSUE THREAD

**Issue by bkr1969** [hassio-addons/addon-node-red#1366]
# Problem/Motivation

Unable to add or deploy nodes

## Expected behavior

> (What you expected to happen)

## Actual behavior

Dropdown menus for domain and service are blank. Unable to add entities.  Existing flows do not run

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by bkr1969** [comment]
[10:51:21] FATAL: 
[10:51:21] FATAL: SSL has been enabled using the 'ssl' option,
[10:51:21] FATAL: this requires a SSL certificate file which is
[10:51:21] FATAL: configured using the 'certfile' option in the
[10:51:21] FATAL: add-on configuration.
[10:51:21] FATAL: 
[10:51:21] FATAL: Unfortunately, the file specified in the
[10:51:21] FATAL: 'certfile' option does not exists.
[10:51:21] FATAL: 
[10:51:21] FATAL: Please ensure the certificate file exists and
[10:51:21] FATAL: is placed in the '/ssl/' directory.
[10:51:21] FATAL: 
[10:51:21] FATAL: In case you don't have SSL yet, consider getting
[10:51:21] FATAL: a SSL certificate or setting the 'ssl' option
[10:51:21] FATAL: to 'false' in case you are not planning on using
[10:51:21] FATAL: SSL with this add-on.
[10:51:21] FATAL: 
[10:51:21] FATAL: Check the add-on manual for more information.

**Comment by frenck** [comment]
The error message you pasted contains the error, the reason why and possible solutions to resolve that error... what else do you need? 😄

**Comment by bkr1969** [comment]
I need to know what that error message means and what to do to fix it

**Comment by bkr1969** [comment]
I haven't changed anything other than uninstalling and re-installing Node Red

**Comment by frenck** [comment]
Did you read it? As in, I can respond, but I would copy paste that message as a response here :S

**Comment by bkr1969** [comment]
I apparently need some sort of SSL certificate somewhere.  Where?  How do I get it?  Why was Node Red working yetserday and not today.  I am really desperate for help.

**Comment by frenck** [comment]
> I apparently need some sort of SSL certificate somewhere. 

Depends if you are using SSL or not...

>  Where? 

Add-on configuration, where you configure add-on options.

**Comment by bkr1969** [comment]
OK...let me try to be clearer.  Node Red was working yesterday. I have no SSL that I'm aware of.  I uninstalled Node Red this morning do to a missing conf node that no one can seem to tell me how to remove.  When I re-installed, I got this error.  I restored a backup of HA from 2 days ago and when I try to go to Node Red, I get the same.  None of this makes sense to me.  If you want to just tell me over and over again that I'm stupid, fine, but all I'm looking for is help to make this work again. 

Also, I mentioned it before even though it seems unrelated, but I can't use my file editor for some reason today either, so I can't view or edit any of my files or folders.

**Comment by frenck** [comment]
>  uninstalled Node Red this morning do to a missing conf node that no one can seem to tell me how to remove. When I re-installed, I got this error.

If you did that, it means you've lost your configuration. The default configuration has SSL enabled. If you don't have it, you need to disable that in the add-on configuration.

Go to the add-on page in Home Assistant -> Configuration tab -> Disable SSL. Done.

**Comment by bkr1969** [comment]
That was helpful.  Thank you.

Can you please point me in the right direction  to learn how to remove nodes from the palette?  That is what started all of this problem and why my flows still will not run.  Thank you.

**Comment by frenck** [comment]
![CleanShot 2022-06-08 at 19 37 30](https://user-images.githubusercontent.com/195327/172681603-c52f5ea3-e549-4e47-b1fe-f0a6a9798ce0.png)

**Comment by bkr1969** [comment]
Nope.  Doesn't work.  The conf node is greyed out yet still shows as in use so I am unable to remove in that way.

**Comment by frenck** [comment]
> "The conf node is greyed out yet"

Doesn't ring a bell for me? Got a screenshot?

**Comment by bkr1969** [comment]
Well, the whole thing is somehow out of my palette now, but I still get this:

![image](https://user-images.githubusercontent.com/42385989/172683721-ff99ae4f-848a-4ad2-b1c7-5a707e513f56.png)

None of my flows will run and that conf node is nowhere in any of them.  I am completely locked out.

**Comment by frenck** [comment]
It complains about missing `node-red-contrib-alexa-home-skill` (somewhere in your flows, it uses it... 🤷 Maybe somewhere hidden, underneath something...)

`node-red-contrib-alexa-home-skill` was removed this release (no longer built-in). If you install `node-red-contrib-alexa-home-skill` via the palette manager, it should at least get you up and running again.

**Comment by bkr1969** [comment]
I am trying that now, but that was where the conf node was greyed out previously.  Maybe now that it has gone a re-install will fix.  Standby...

**Comment by bkr1969** [comment]
Working now.  That was a weird mess. Sorry if I was testy...I was freaking out over losing everything I've worked for.  Thanks for your help.
