### ISSUE TITLE
Functions missing: looptimer and stoptimer

### ISSUE THREAD

**Issue by bitmerchandise** [hassio-addons/addon-node-red#1369]
# Problem/Motivation

Stoptimer/looptimer functions unavailable

## Expected behavior

Functions should be available as in past. I haven't found any mention of their removal.

## Actual behavior

Function available and flows work by stopping or the timer for x time and then flow continues

## Steps to reproduce

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

Update from Node Red 11.1.2 to 12.0.1

Steps reproduced on secondary home assistant and result is the same.  2 functions disappear and are no longer available. Looptimer and stoptimer

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> I haven't found any mention of their removal.

Read the release notes...

**Comment by bitmerchandise** [comment]
Uggh sorry
