### ISSUE TITLE
No npm audit fix

### ISSUE THREAD

**Issue by PierreScerri** [hassio-addons/addon-node-red#137]
# Problem/Motivation

> Found 2 vulnerabilities during add-on start up. npm audit fix not working

## Expected behavior

> npm audit fix 

## Actual behavior

> During add-on start up some vulnerabilities are found and it is suggested to run 'npm audit fix'

## Logs
This is the add-on startup log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED v1.3.2
 Flow-based programming for the Internet of Things
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 2.8 / HA 0.87.1 / SU 143 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-config.sh: executing... 
[cont-init.d] 20-config.sh: exited 0.
[cont-init.d] 50-remove-conflicts.sh: executing... 
audited 2 packages in 3.022s
found 0 vulnerabilities
[cont-init.d] 50-remove-conflicts.sh: exited 0.
[cont-init.d] 80-system-packages.sh: executing... 
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-npm-packages.sh: executing... 
+ node-red-contrib-modbus@4.1.1
added 22 packages from 14 contributors, updated 4 packages and audited 3210 packages in 51.963s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-dashboard@2.13.2
added 37 packages from 34 contributors and audited 3312 packages in 46.068s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
[cont-init.d] 81-npm-packages.sh: exited 0.
[cont-init.d] 82-user-scripts.sh: executing... 
[cont-init.d] 82-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
20 Feb 12:43:47 - [info] 
Welcome to Node-RED
===================
20 Feb 12:43:47 - [info] Node-RED version: v0.19.5
20 Feb 12:43:47 - [info] Node.js  version: v8.14.0
20 Feb 12:43:47 - [info] Linux 4.14.81-v7 arm LE
20 Feb 12:43:53 - [info] Loading palette nodes
20 Feb 12:44:20 - [info] Dashboard version 2.13.2 started at /ui
20 Feb 12:44:23 - [info] Settings file  : /etc/node-red/config.js
20 Feb 12:44:23 - [info] Context store  : 'default' [module=memory]
20 Feb 12:44:23 - [info] User directory : /config/node-red/
20 Feb 12:44:23 - [warn] Projects disabled : editorTheme.projects.enabled=false
20 Feb 12:44:23 - [info] Flows file     : /config/node-red/flows.json
20 Feb 12:44:23 - [info] Server now running at https://127.0.0.1:1880/
20 Feb 12:44:23 - [info] Starting flows
```
This is the terminal output when npm audit fix is executed:

>   _    _                 _
>  | |  | |               (_)
>  | |__| | __ _ ___ ___   _  ___
>  |  __  |/ _` / __/ __| | |/ _ \
>  | |  | | (_| \__ \__ \_| | (_) |
>  |_|  |_|\__,_|___/___(_)_|\___/
> 
> 
> Our Cli:
> $ hassio help
> 
> ➜  /workspace npm audit fix
> npm ERR! code EAUDITNOPJSON
> npm ERR! audit No package.json found: Cannot audit a project without a package.json
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-02-20T11_44_57_295Z-debug.log
> ➜  /workspace 
> 
> 

This is the debug log produced:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'audit', 'fix' ]
> 2 info using npm@6.7.0
> 3 info using node@v9.11.1
> 4 verbose npm-session 6115252c94ef0fb2
> 5 verbose stack Error: No package.json found: Cannot audit a project without a package.json
> 5 verbose stack     at Bluebird.all.spread (/usr/local/share/.config/yarn/global/node_modules/npm/lib/audit.js:164:19)
> 5 verbose stack     at tryCatcher (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> 5 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:509:35)
> 5 verbose stack     at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
> 5 verbose stack     at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
> 5 verbose stack     at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
> 5 verbose stack     at Promise._fulfill (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
> 5 verbose stack     at PromiseArray._resolve (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
> 5 verbose stack     at PromiseArray._promiseFulfilled (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:144:14)
> 5 verbose stack     at PromiseArray._iterate (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:114:31)
> 5 verbose stack     at PromiseArray.init [as _init] (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:78:10)
> 5 verbose stack     at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
> 5 verbose stack     at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
> 5 verbose stack     at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
> 5 verbose stack     at Promise._fulfill (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
> 5 verbose stack     at PromiseArray._resolve (/usr/local/share/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
> 6 verbose cwd /workspace
> 7 verbose Linux 4.14.81-v7
> 8 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "audit" "fix"
> 9 verbose node v9.11.1
> 10 verbose npm  v6.7.0
> 11 error code EAUDITNOPJSON
> 12 error audit No package.json found: Cannot audit a project without a package.json
> 13 verbose exit [ 1, true ]
>

**Comment by frenck** [comment]
We don't use NPM audit, we use Snyk.io to monitor CVE's closely (not only on NPM). As soon as a remedy is available, we are notified and will apply it.

Closing issue.
