### ISSUE TITLE
node-red does not start missing image

### ISSUE THREAD

**Issue by gerlipfs** [hassio-addons/addon-node-red#1373]
# Problem/Motivation
node red will not start
> (Why the issue was filed)

## Expected behavior
auto start

> (What you expected to happen)

## Actual behavior
node red does not start
> (What actually happened)

Image ghcr.io/hassio-addons/node-red/aarch64:12.0.2 does not exist for addon_a0d7b954_nodered

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The nice thing about the error message, is that it contains an URL:

<http://ghcr.io/hassio-addons/node-red/aarch64:12.0.2>

Which shows that it exists and has been installed over 13K times already:

![CleanShot 2022-06-09 at 14 52 21](https://user-images.githubusercontent.com/195327/172851310-ed11a36c-577a-4a82-bdf2-36f4fa0ba865.png)

It might be something wrong in the underlying Docker references that the Supervisor holds.
You could try running this command in one of the terminals to fix that:

`ha supervisor repair`

../Frenck

**Comment by thedavidhanks** [comment]
Worked perfectly.  Thanks.
