### ISSUE TITLE
Unable to add missing node types after upgrade to v12.0.2

### ISSUE THREAD

**Issue by pbavinck** [hassio-addons/addon-node-red#1375]
# Problem/Motivation

Unable to add missing node types after upgrade to v12.0.2 with breaking change requiring me to add the nodes manually.

## Expected behavior

Should be able to add the nodes (npm_packages).

## Actual behavior

The npm_packages are added in the UI after entering them (e.g. `node-red-contrib-statistics`). However, the Save button remains greyed out and clicking it removes the added nodes from the list.

## Steps to reproduce

Add a node e.g. `node-red-contrib-statistics` and Save.

**Comment by frenck** [comment]
<img src="https://media1.giphy.com/media/elsol3P5Jt2ASsxLva/giphy-downsized-medium.gif"/>

**Comment by pbavinck** [comment]
Excellent UI design :-/
