### ISSUE TITLE
Disconnecting/undefined

### ISSUE THREAD

**Issue by jar87** [hassio-addons/addon-node-red#1378]
# Problem/Motivation

After updating Node-RED to newest version, I`m having issues with nodes. Sometimes it shows as disconnected (for example all sensors) and because of that automations aren`t work properly. I`ve also saw in logs something like this: 

15 Jun 12:52:23 - [info] [server:Home Assistant] Connected to undefined
15 Jun 12:52:55 - [info] [server:Home Assistant] Connection closed to undefined
15 Jun 12:53:00 - [info] [server:Home Assistant] Connecting to undefined
15 Jun 12:53:00 - [info] [server:Home Assistant] Connecting to undefined
15 Jun 12:53:00 - [info] [server:Home Assistant] Connecting to undefined
15 Jun 12:53:00 - [info] [server:Home Assistant] Connecting to undefined
15 Jun 12:53:02 - [info] [server:Home Assistant] Connected to undefined
15 Jun 12:53:02 - [info] [server:Home Assistant] Connected to undefined
15 Jun 12:53:02 - [info] [server:Home Assistant] Connected to undefined
15 Jun 12:53:02 - [info] [server:Home Assistant] Connected to undefined
15 Jun 12:53:53 - [info] [server:Home Assistant] Connection closed to undefined
15 Jun 12:53:59 - [info] [server:Home Assistant] Connecting to undefined
15 Jun 12:53:59 - [info] [server:Home Assistant] Connected to undefined
15 Jun 12:54:19 - [info] [server:Home Assistant] Connection closed to undefined
15 Jun 12:54:24 - [info] [server:Home Assistant] Connecting to undefined
15 Jun 12:54:25 - [info] [server:Home Assistant] Connected to undefined

i`m attaching screens. 

## Expected behavior

help me to fix that

## Actual behavior

not working

## Steps to reproduce

just help with that issue

## Proposed changes

No i don`t have

![1](https://user-images.githubusercontent.com/90478911/173812071-33000d9b-b6fe-4b3f-a697-c82cd67f1bee.jpg)
![39f26dffcd4692fb1a7d9dc822b7f8f980fa5530](https://user-images.githubusercontent.com/90478911/173812111-3e6ff591-9e6f-4010-b557-5817769fbdbd.png)

**Comment by crow1093** [comment]
Same here since last update 2 weeks ago. Update to v13 didn't solve this problem. Disabled all flows but node red loses the connection to home assistant after a few hours.

**Comment by kjake** [comment]
I have seen this recently as well.  Restarting the add-on resolves it for some time.  I'll respond again when I have some logs to provide.

**Comment by gledsonrabelo** [comment]
Same problem here. Always disconnect after a few hours. This problem starts recently for me.

**Comment by crow1093** [comment]
Solved it now. Look at your integrations. There's one that node red can't handle because of the need to transfer too much information at once. In my case it was a template sensor that crashed the add-on.
