### ISSUE TITLE
Unable to ping from Node-Red

### ISSUE THREAD

**Issue by morrisb74** [hassio-addons/addon-node-red#138]
# Problem/Motivation

> Unable to ping from Node-Red

## Expected behavior

> Getting a response back instead of undefined

## Actual behavior

> getting a undifined back

## Steps to reproduce

> add a PING component

## Proposed changes

> .

**Comment by morrisb74** [comment]
Hi Frenck. The thing is it doesn't give an error in the log ... when sending it to the debug component it just gives undefined I'll paste the simple node config to https://paste.ubuntu.com/p/KRgmwDHT6J/

**Comment by Pihkal82** [comment]
Hi,

I'm having the exact same issue and exact same message.
According to [https://www.npmjs.com/package/node-red-node-ping](url) it can be permission related.

**Comment by frenck** [comment]
I'm unable to reproduce the issue :(

![image](https://user-images.githubusercontent.com/195327/53521630-f5a3a400-3ad8-11e9-9586-696722571e66.png)

**Comment by morrisb74** [comment]
Did you also see the node-red flow I pasted ?

**Comment by niksy111** [comment]
I see what you did wrong! You have entered msg.debug in debug node but it has to be msg.payload
Here is correct flow https://paste.ubuntu.com/p/6r3n758WPb/

**Comment by Pihkal82** [comment]
Hi Frenck,

I've also spotted my error, you're right, it's all working as expected.
Sorry to have wasted your time and many thanks for all the work you put into Hassio.
Regards!

**Comment by frenck** [comment]
Happy there is a solution! 👍
