### ISSUE TITLE
Call Service Node TTS Example Data is Invalid

### ISSUE THREAD

**Issue by pearson** [hassio-addons/addon-node-red#1380]
# Problem/Motivation

The example data loaded by the call service node's TTS "Load example data" button appears to be invalid.

## Expected behavior

I would expect the example data to work correctly.

## Actual behavior

The example data generates the following error: `"Call-service error. expected dict for dictionary value @ data['options']"`. The example data currently loaded is: `{"message":"My name is hanna","language":"ru","options":"platform specific"}`.

## Steps to reproduce

1. Create a "call service" node
2. Connect an "inject" node to the "call service" node
3. Edit the "call service" node
4. Set "Domain" to "tts"
5. Set "Service" to "google_say"
6. Set "Entity" to a valid Google Home speaker
7. Click "Load example data" to load the example into the "Data" property
8. Click "Done"
9. Click "Deploy"
10. Click the button on the "inject" node
11. Open the "debug" tab and notice the error

## Proposed changes

Change the example data to contain a valid dictionary value for "options", such as the following:
`{"message":"My name is hanna","language":"ru","options":{}}`

**Comment by pearson** [comment]
@sinclairpaul , isn't this simply a case that the string `"platform specific"` ends up in `"options"`, rather than a dictionary? Or does the HA Palette add-on change the expected type for `options` from a string to a dictionary?

**Comment by sinclairpaul** [comment]
The functionality of the custom nodes is provided by that project, the addon purely pre-installs and configures them.  There isn't anything that can be done in this project.  The same would apply if it was an issue with Node-Red itself.

**Comment by pearson** [comment]
Ah, my bad. I understand. Thanks, I'll look into it through that repository.
