### ISSUE TITLE
Deleted nodes with V12

### ISSUE THREAD

**Issue by Senbei123** [hassio-addons/addon-node-red#1382]
Hi @frenck,

I think it is a good idea, to limit the needed nodes during the installation to make the addon as smooth as possible.

BUT when I do an update from an existing setup where I use one or multiple of the deleted notes, THEN the update process should NOT deinstall thoses nodes. It should be checked, if the nodes are used, when no = delete, when yes = leave them.

Just my 2 cent.

But next to this, I like your work for NodeRED and Home Assistant. ;)

BR,
Tristan

**Comment by sinclairpaul** [comment]
This isn't possible, the Container that is built either has the nodes or it doesn't.  As the build happens prior to you installing it, there is no way to check.
