### ISSUE TITLE
Gui only shows blank/black page after installation

### ISSUE THREAD

**Issue by Kilill** [hassio-addons/addon-node-red#1383]
# Problem/Motivation

> The addon does not show anny gui when pressing the "Open Web Ui" link

## Expected behavior

> The web ui should be loaded

## Actual behavior

> Black/Blank screen is shown
## Steps to reproduce

> install Node Red addon directly from Settings->Addons->'+Ad-on Store page in HA
in "Configurarion" only add key to "credential_secret"
(doe actually not matter if the password/user fields are left blank or not)

Press the "Start" link on the "Info" page to start the addon
 
Log file indicates that Node red in installed, started and running
`Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 12.0.2
 You are running the latest version of this add-on.
 System: Ubuntu 21.10  (amd64 / qemux86-64)
 Home Assistant Core: 2022.6.4
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
cont-init: info: /etc/cont-init.d/customizations.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
up to date, audited 1 package in 1s
found 0 vulnerabilities
cont-init: info: /etc/cont-init.d/node-red.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun nodered (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:24:14] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
25 Jun 22:24:21 - [info] 
Welcome to Node-RED
===================
25 Jun 22:24:21 - [info] Node-RED version: v2.2.2
25 Jun 22:24:21 - [info] Node.js  version: v16.15.0
25 Jun 22:24:21 - [info] Linux 5.13.0-51-generic x64 LE
25 Jun 22:24:24 - [info] Loading palette nodes
25 Jun 22:24:34 - [info] Dashboard version 3.1.7 started at /endpoint/ui
25 Jun 22:24:36 - [info] Settings file  : /etc/node-red/config.js
25 Jun 22:24:36 - [info] Context store  : 'default' [module=memory]
25 Jun 22:24:36 - [info] User directory : /config/node-red/
25 Jun 22:24:36 - [warn] Projects disabled : editorTheme.projects.enabled=false
25 Jun 22:24:36 - [info] Flows file     : /config/node-red/flows.json
25 Jun 22:24:36 - [info] Server now running at http://127.0.0.1:46836/
25 Jun 22:24:36 - [info] Starting flows
25 Jun 22:24:36 - [info] Started flows
[22:24:37] INFO: Starting NGinx...
25 Jun 22:24:41 - [info] [server:Home Assistant] Connecting to http://supervisor/core
25 Jun 22:24:42 - [info] [server:Home Assistant] Connected to http://supervisor/core`

HA core version: 2022.6.4
Node red version: 2.2.2

**Comment by sinclairpaul** [comment]
There are no errors in the log you posted, which suggests the addon started correctly.

I would suggest looking at browser logs as to why the addon cannot be loaded, in addition you may want to look at the HA supervisor logs.

**Comment by Kilill** [comment]
well.. after fiddling around with this for a day, and after a couple reinstalls, and probably more importantly, restarts of HA it suddenly started working. 
So it works but no clue why it didn't or why it now does... HA works in mysterious ways
