### ISSUE TITLE
Render Template Node not working after upgrade

### ISSUE THREAD

**Issue by Drewskieza** [hassio-addons/addon-node-red#1394]
# Problem/Motivation
Render Template node is giving an error
Without this node my flows fail
18 Jul 20:29:45 - [error] [api-render-template:LS 15 minute] Error get-template: Request failed with status code 400

## Expected behavior
Able to see and create render template nodes

## Actual behavior
Template block does not give you the option to enter anything and in nodes that where created in the past it shows no information
![image](https://user-images.githubusercontent.com/34630805/179579950-ca578cac-d895-472a-ac5d-a69b88f8b623.png)

## Steps to reproduce
Add a Render Template  node and try fill in information

## Proposed changes
None

**Comment by Drewskieza** [comment]
Down graded to 12.0.2 and all is working again.

**Comment by ecard0** [comment]
I was hesitant... Since it did some upgrade steps... Thanks

**Comment by frenck** [comment]
> 18 Jul 20:29:45 - [error] [api-render-template:LS 15 minute] Error get-template: Request failed with status code 400

Status 400 would probably result from Home Assistant. Anything in the logs of Home Assistant when this happens?

**Comment by Drewskieza** [comment]
I see the 400 was due to one of my other integrations not working correctly (was not available), so this can be ignored.
But the Render Template node is an issue.

**Comment by sinclairpaul** [comment]
I would suggest it is https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/647

**Comment by esdcmc** [comment]
same for me: render template editor gone in NodeRed 13.
The nodes in existing flows work but there is no way to change them or introduce new one.
Everything ok when restoring v12

**Comment by slyticoon** [comment]
I am also encountering the same issue.

**Comment by Drewskieza** [comment]
Issue seems to be resolved with 13.1.0

**Comment by esdcmc** [comment]
it works for me too
