### ISSUE TITLE
node-red 13.0.0 hostname resolve not working?

### ISSUE THREAD

**Issue by baylanger** [hassio-addons/addon-node-red#1396]
# Problem/Motivation
hass.io installation inside VM.
DNS service is running on same NAS.
DNS name resolve in hass.io "Terminal" works fine.  Hass.io is able to connect to the MQTT server using fqdn .. why can't node-red?

node-red using fqdn.

```
20 Jul 22:28:47 - [info] [mqtt-broker:mqtt.domain.com] Connection failed to broker: nodered@mqtt://mqtt.domain.com:1883
20 Jul 22:28:51 - [info] [server:Home Assistant] Connecting to http://supervisor/core
20 Jul 22:28:51 - [info] [server:Home Assistant] Connected to http://supervisor/core
20 Jul 22:28:51 - [debug] [server:Home Assistant] States Loaded
20 Jul 22:28:51 - [debug] [server:Home Assistant] Services Loaded
20 Jul 22:28:51 - [debug] [server:Home Assistant] HA State: running
20 Jul 22:29:02 - [info] [mqtt-broker:mqtt.domain.com] Connection failed to broker: nodered@mqtt://mqtt.domain.com:1883
20 Jul 22:29:17 - [info] [mqtt-broker:mqtt.domain.com] Connection failed to broker: nodered@mqtt://mqtt.domain.com:1883
20 Jul 22:29:32 - [info] [mqtt-broker:mqtt.domain.com] Connection failed to broker: nodered@mqtt://mqtt.domain.com:1883
...
...
...
and it goes on and on.
```

Replacing the fqdn in the config with the IP address works.  I heavily rely on mqtt, this service isn't running inside "hass.io".

> (Why the issue was filed)

## Expected behavior
Should be able to resolve fqdn , should be able to resolve to the IP address and connect to the service.

> (What you expected to happen)
1. More debug logging hoping it can help find root cause.
2. Fix bug/logic if anything is required.

## Actual behavior

> (What actually happened)
See logs above.

## Steps to reproduce

> (How can someone else make/see it happen)
Install node-red and try to connect to external mqtt server using fqdn.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
Currently don't - I'm a bit new here...

**Comment by frenck** [comment]
> DNS name resolve in hass.io "Terminal" works fine.

That is not an equal test, unfortunately. Depending on the terminal you are using, the Node-RED add-on runs on the host network, while the core SSH & Terminal add-on does not.

> DNS name resolve in hass.io "Terminal" works fine. Hass.io is able to connect to the MQTT server using fqdn .. why can't node-red?

Works fine here? 🤷 

I have no idea what else to give you.

**Comment by baylanger** [comment]
I also learned out there's a dns instance... wish the mqtt connect would have more insight.  I'll try to figure it out, thanx!
