### ISSUE TITLE
Missing node cards

### ISSUE THREAD

**Issue by jaimmor** [hassio-addons/addon-node-red#1397]
# Problem/Motivation

NodeRed is not showing all of the node cards - they seem to be corrupt.

Noticed that they're all there in the Flows view on the right, but they just wont show up on my dashboard...

![Capture4](https://user-images.githubusercontent.com/108494561/180120624-c76a611c-8b19-4c09-92e3-3f4b43b34518.PNG)

## Expected behavior

Node cards to be present

## Actual behavior

Node missing from dashboard

![Capture](https://user-images.githubusercontent.com/108494561/180119972-38a09ff4-76f1-495b-9e22-10b16d5a9849.PNG)

## Steps to reproduce

N/A

## Proposed changes

N/A

**Comment by frenck** [comment]
Anything in your console?

**Comment by jaimmor** [comment]
Nothing that stands out
But I posted this in the NodeRed Forum and they suggested a browser update since it was apparently a known issue
Updating Chrome fixed this for me.

**Comment by jaimmor** [comment]
https://discourse.nodered.org/t/missing-nodes-in-node-red-editor/65398/2?u=jaimmor
