### ISSUE TITLE
can't configure new Node-RED install 

### ISSUE THREAD

**Issue by donburch888** [hassio-addons/addon-node-red#1413]
# Problem/Motivation

Installing a fresh new Home Assistant OS today on RasPi 4, and installing all my packages... 

Node-RED installation includes 
`3. Set a credential_secret, which is used to encrypt sensitive data. `

When i first installed node-RED, this used to be available in the "Configuration" tab ... but the tab now says "This add-on does not expose configuration for you to mess with…" and consequently trying to START produces a FATAL error message in the "Log" tab. 

1. On the "Info" tab (where the [START] button is) there is no error message - except that it doesn't start.
2. The error mesage in the "Log" tab is a good description - but doesn't give simple instructions for a noob to get node-RED running. 
3. the error message implies that SSL is required. 

## Proposed changes

1. reinstate the Configuration tab, or pop-up a dialog box asking for credential_secret. 
2. change the default to "require_ssl = false".  Why ? Because the error message implies that SSL is required, and so sends noobs on another learning curve ... whereas the quick answer is to remove "require_ssl =true".

**Comment by frenck** [comment]
This is an current issue with the Supervisor: 

> "This add-on does not expose configuration for you to mess with…"

From an add-on perspective, there is nothing I can do. Please report your issue here:

<https://github.com/home-assistant/supervisor/issues>

Thanks! 👍 

../Frenck
