### ISSUE TITLE
cannot write into functions, comments or notes

### ISSUE THREAD

**Issue by SlashGIP** [hassio-addons/addon-node-red#1418]
# Problem/Motivation

- I tried to change my functions or write comments

## Expected behavior

> I can write into my nodes ?

## Actual behavior

> (What actually happened)

## Steps to reproduce

> Dont know whats the problem. Maybe the new editor somehow?  Do I need to install something manually?

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
![1](https://user-images.githubusercontent.com/37490012/183223060-228b8f47-8981-4349-98d1-9981b680643a.jpg)

**Comment by SlashGIP** [comment]
![2](https://user-images.githubusercontent.com/37490012/183223685-7e6782b9-5e77-4b85-82a3-10885f2f5bc4.jpg)

**Comment by Fahrenholz** [comment]
Same issue here. There's an error message in the developer console: `Uncaught Error: Symbol.asyncIterator is not defined.`

**Comment by per2jensen** [comment]
Same issue here:
HA Nodered version installed: 13.3.1
I can't type anything into a function node's code editor on the taps: "On start", "On message" and "On stop".
I can modify the function node's name and deploy it.

I am using Ubuntu 22.04 Firefox 103.0.2 (the snap edition)
