### ISSUE TITLE
node-red-contrib-ccu needs additional port forwardings

### ISSUE THREAD

**Issue by AnDann** [hassio-addons/addon-node-red#1421]
# Problem/Motivation

>For the ccu-connection node in node-red-contrib-ccu you need to open two ports for the ccu to connect. Its not possible in the ha-addon configuration to open additional ports.

## Proposed changes

- Add option to forward ports for ccu-connection node
In config.yaml I added:
```
ports:
  80/tcp: 1880
  2052/tcp: 2052
  2053/tcp: 2053
ports_description:
  80/tcp: Web interface
  2052/tcp: BINRPC interface
  2053/tcp: XMLRPC interface
```
![image](https://user-images.githubusercontent.com/5374645/183599230-6505b578-1b2d-4944-9e96-88322b9a525a.png)
- Make forwarding additional ports configurable

**Comment by frenck** [comment]
There is no need to make those forward, as the add-on runs on the host network already:

<https://github.com/hassio-addons/addon-node-red/blob/main/node-red/config.yaml#L27>

Any port opened will be available already.

**Comment by AnDann** [comment]
Ok thank you I tried again without the forwardings and it worked now 🤦‍♂️. Dont know what I made wrong in config before.
