### ISSUE TITLE
Cannot edit/write/type inside the function node

### ISSUE THREAD

**Issue by prvashisht** [hassio-addons/addon-node-red#1423]
# Problem/Motivation

> I was away from my home for a couple of months and after coming back, I updated Node-Red to version 3.0. However, ever since the upgrade, I have been unable to edit or write anything into any of the function nodes. It's the same for existing and new function nodes I create. Also, all other nodes I tested work fine. I can fill in their custom fields.

## Expected behavior

> I be able to write in the function nodes

## Actual behavior

> I can move the cursor around by clicking at specific places. However, nothing happens when I use my keyboard. I can't move the cursor, write, delete, or paste any text. I can, however, select text with my mouse and copy it.

## Steps to reproduce

> I don't know if others can reproduce this. Just writing into a function node doesn't work.

**Comment by prvashisht** [comment]
Update, further details:

I'm using Firefox, I also tried it on the iOS app and Google Chrome. On Chrome I was able to see that something is being typed somewhere as I was receiving word suggestions on the touchbar above the keyboard. I could also delete the words (by guessing from the hints in the touchbar), but I have not idea where is the typed content going.

Developer's Console is showing this error whenever I do a keypress (it's most likely happening on keydown event)

```
Uncaught Error: e[Symbol.iterator] is not a function

TypeError: e[Symbol.iterator] is not a function
    at e.first (editor.js:2:415180)
    at Object.getCommand (editor.js:2:3261143)
    at Na.executeCommand (editor.js:2:3023864)
    at Object.type (editor.js:2:1360978)
    at ht.type (editor.js:2:1099830)
    at editor.js:2:1090606
    at d.invoke (editor.js:2:396935)
    at u.fire (editor.js:2:398687)
    at editor.js:2:975756
    at d.invoke (editor.js:2:396935)
    at editor.js:2:392210
(anonymous) @ editor.js:2
setTimeout (async)
unexpectedErrorHandler @ editor.js:2
onUnexpectedError @ editor.js:2
o @ editor.js:2
fire @ editor.js:2
(anonymous) @ editor.js:2
invoke @ editor.js:2
fire @ editor.js:2
o @ editor.js:2
```

**Comment by Nusse469** [comment]
I am getting the same issue on version 13.3.2

The exact problem from previous issue -- Render Template Node not working after upgrade #1394

**Comment by ginebib** [comment]
I have the same problem in version 13.3.2. I tried to update since version 12.x and always had this issue. Tried in different browsers and devices. So I am back on 11.1.2 now which works fine.

**Comment by prvashisht** [comment]
@ginebib how did you downgrade to `11.1.2`? I don't have a backup, can I do that too?

**Comment by ginebib** [comment]
> @ginebib how did you downgrade to `11.1.2`? I don't have a backup, can I do that too?

Yes, I had a backup. Sorry, I don't know how to downgrade without.

**Comment by beyond86** [comment]
Have the same problem. What I can do in this situation? 
Don't have backups of previous version.

**Comment by beyond86** [comment]
I found temporary solution.
Added in settings.js: 
_editorTheme: {
  codeEditor: {
    lib: "ace",_

**Comment by bonanitech** [comment]
Possibly related to this https://github.com/node-red/node-red/issues/3078

**Comment by ginebib** [comment]
> Possibly related to this [node-red/node-red#3078](https://github.com/node-red/node-red/issues/3078)

Great, thanks for this. In fact I had nodes installed, which where not on the latest version (node-red-contrib-miio-roborock). Updating this has solved my issue.

**Comment by prvashisht** [comment]
> I found temporary solution. Added in settings.js: _editorTheme: { codeEditor: { lib: "ace",_

Doesn't work for me sadly. I tried in both Chrome and Firefox. Also, the latest `13.4.0` doesn't fix it.

**Comment by prvashisht** [comment]
> Possibly related to this [node-red/node-red#3078](https://github.com/node-red/node-red/issues/3078)

Thank you! This worked. I just had to update the nodes in the palette. However, is there no notification of pending updates? or no way to update them all at once without going through the whole list to see which ones have an update?
