### ISSUE TITLE
NodeRed crashing every morning at exactly 3AM

### ISSUE THREAD

**Issue by knissdesign** [hassio-addons/addon-node-red#1425]
# Problem/Motivation

NodeRed Addon crashes every morning at 3am. No flows seem to be executing at the time. I believe this routine crash started with updating to 13.3.1.

## Expected behavior

NodeRed NOT crashing and continuing on it's merry way.

## Actual behavior

NodeRed crashes at exactly 3am every morning. I have turned watchdog off in an effort to preserve logs until I can access them when I wake up, but even with watchdog on the add-on will NOT successfully restart; I have to manually start the add-on when I wake up regardless of whether watchdog is on or not. Everything else handled by node-red seems to be functioning just fine.

## Steps to reproduce

Home Assistant on RasPi4, Hass
Home Assistant Core 2022.8.5
Home Assistant Supervisor 2022.08.3
Home Assistant Operating System 8.4
NodeRed Add-On V13.3.1

## Log

```
17 Aug 03:00:00 - [red| Uncaught Exception:
17 Aug 03:00:00 - [error] TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (1660730400000)
     at new NodeError (node:internal/errors:372:5)
     at Function.byteLength (node: buffer:735:11)
     at SSH2Stream.exec (/config/node-red/node modules/ssh2-streams/lib/ssh.js:1369:60)
     at reqExec (/config/node-red/node_modules/ssh2/lib/client.js:1402:34)
     at /config/node-red/node_modules/ssh2/lib/client.js:770:28
     at /config/node-red/node_modules/ssh2/lib/client.js:771:17
     at SSH2Stream.onSuccess (/config/node-red/node_modules/ssh2/lib/client.js:1190:5)
     at Object.onceWrapper (node :events:642:26)
     at SSH2Stream.emit (node:events:527:28)
     at parsePacket (/config/node-red/node modules/ssh2-streams/lib/ssh.js:3425:10)
[03:00:00] WARNING: Node-RED crashed, halting add-on
[03:00:00] INFO: Node-RED stoped
```

**Comment by quito96** [comment]
Same problem... have tried several restarts of Node Red and HA, without positive effect. 
NodeRed runs unstable

Add-on version: 13.3.1
 System: Home Assistant OS 8.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.8.6
 Home Assistant Supervisor: 2022.08.3

**Comment by tjorim** [comment]
@knissdesign Can you post your configuration and extra packages? ssh2-streams is not included in the default installation.

**Comment by tjorim** [comment]
@quito96 Might be an issue with your flows? What error do you get and post your config as well please.

**Comment by quito96** [comment]
@tjorim  I don't think so. 
The flows run without change for more than a year. 
Sporadic crashes of Node Red came with Addon Vers 13.3.1 and Core: 2022.8.6 
Sometimes it ran 30 minutes times 4 hrs at a stretch. Then it crashed without rebooting.
System restarts did not help. 

Now with HA 2022.8.7 NodeRed runs stable again. 
Actual:
Home Assistant 2022.8.7
Supervisor 2022.08.3
