### ISSUE TITLE
install error~~~~12.0.2 do u know why?

### ISSUE THREAD

**Issue by yuhuanfan** [hassio-addons/addon-node-red#1430]
The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies g++=11.2.1_git20220219-r2 gcc=11.2.1_git20220219-r2 libc-dev=0.7.2-r3 linux-headers=5.16.7-r1 make=4.3-r0 py3-pip=22.1.1-r0 python3-dev=3.10.4-r0 python3=3.10.4-r0 && apk add --no-cache git=2.36.1-r0 icu-data-full=71.1-r2 nginx=1.22.0-r0 nodejs=16.15.0-r1 npm=8.10.0-r0 openssh-client=9.0_p1-r1 patch=2.7.6-r7 && npm config set unsafe-perm true && npm install --no-audit --no-optional --no-update-notifier --only=production --unsafe-perm && npm rebuild --build-from-source @serialport/bindings-cpp && npm cache clear --force && echo -e "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && apk del --no-cache --purge .build-dependencies && rm -fr /etc/nginx /root/.cache /root/.npm /root/.nrpmrc /tmp/*' returned a non-zero code: 15

> (Why the issue was filed)

Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.4
前端版本： 20220802.0 - latest

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Are you trying to build the add-on yourself? Normally this add-on comes with a pre-built docker image. What system are you using? Architecture?

**Comment by frenck** [comment]
Closing issue as stale (since there hasn't been a response in 25 days).
