### ISSUE TITLE
Can´t start Node-Red

### ISSUE THREAD

**Issue by PitbullSwe** [hassio-addons/addon-node-red#1433]
# Problem/Motivation

> (Why the issue was filed) I installed it and follow the documentation with the password and saved it. pressed start and nothing happends. I get a red dot in the upper right corner
I get this information from the log:

2 Sep 23:02:28 - [info] Node-RED version: v3.0.2
2 Sep 23:02:28 - [info] Node.js  version: v16.16.0
2 Sep 23:02:28 - [info] Linux 5.15.32-v8 arm64 LE
2 Sep 23:02:30 - [info] Loading palette nodes
2 Sep 23:02:35 - [info] Dashboard version 3.1.7 started at /endpoint/ui
2 Sep 23:02:36 - [info] Settings file  : /etc/node-red/config.js
2 Sep 23:02:36 - [info] Context store  : 'default' [module=memory]
2 Sep 23:02:36 - [info] User directory : /config/node-red/
2 Sep 23:02:36 - [warn] Projects disabled : editorTheme.projects.enabled=false
2 Sep 23:02:36 - [info] Flows file     : /config/node-red/flows.json
2 Sep 23:02:36 - [warn] Encrypted credentials not found
2 Sep 23:02:36 - [info] Server now running at http://127.0.0.1:46836/
2 Sep 23:02:36 - [info] Starting flows
2 Sep 23:02:36 - [info] Started flows
[23:02:36] INFO: Starting NGinx...
2 Sep 23:02:41 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:02:41 - [info] [server:Home Assistant] Connected to http://supervisor/core
2 Sep 23:04:45 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
2 Sep 23:04:50 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:04:55 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:00 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:05 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:10 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:15 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:21 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:26 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:31 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:36 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:41 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:05:46 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Sep 23:06:04 - [info] [server:Home Assistant] Connected to http://supervisor/core

and this in the superviser log:

22-09-02 22:50:42 ERROR (MainThread) [supervisor.store] https://github.com/ottopaulsen/node-red-contrib-power-saver.git is not a valid add-on repository

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
There is not much I can do or say based on the logs provided. 
The Supervisor logs should tell you more about why this happens, however, the provided supervisor logs are not related.

**Comment by mgraeuler** [comment]
I just had the same issue, but now it's working. 

Some observations that may help you:
- After installing the addon, the configuration page didn't load. I rebooted the host (config->system->hardware->... (top right)--> reboot host) and that seems to have fixed it.
- The protocol of the startup showed an issue when loading the SSL stuff. I'm still running a plain vanilla HAOS, so there's no SSL (yet!). If that's the case for you as well, deactivate ssl.

**Comment by patricktd** [comment]
Hi, I have the same problem.
I cleaned everything, uninstalled and even empty, node-red does not start.

##### Log Node-Red: log level debug
Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 13.4.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.9.6
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to DEBUG
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
cont-init: info: /etc/cont-init.d/customizations.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
up to date, audited 1 package in 224ms
found 0 vulnerabilities
cont-init: info: /etc/cont-init.d/node-red.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun nodered (no readiness notification)
s6-rc: info: service legacy-services successfully started
[18:05:34] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
22 Sep 18:05:36 - [info] 
Welcome to Node-RED
===================
22 Sep 18:05:36 - [info] Node-RED version: v3.0.2
22 Sep 18:05:36 - [info] Node.js  version: v16.16.0
22 Sep 18:05:36 - [info] Linux 5.15.67 x64 LE
22 Sep 18:05:36 - [info] Loading palette nodes
22 Sep 18:05:37 - [debug] Module: @node-red-contrib-themes/theme-collection 3.0.5 /opt/node_modules/@node-red-contrib-themes/theme-collection
22 Sep 18:05:37 - [debug] Module: node-red-contrib-bigtimer 2.8.3 /opt/node_modules/node-red-contrib-bigtimer
22 Sep 18:05:37 - [debug] Module: node-red-contrib-cast 0.2.17 /opt/node_modules/node-red-contrib-cast
22 Sep 18:05:37 - [debug] Module: node-red-contrib-counter 0.1.6 /opt/node_modules/node-red-contrib-counter
22 Sep 18:05:37 - [debug] Module: node-red-contrib-home-assistant-websocket 0.44.0 /opt/node_modules/node-red-contrib-home-assistant-websocket
22 Sep 18:05:37 - [debug] Module: node-red-contrib-influxdb 0.6.1 /opt/node_modules/node-red-contrib-influxdb
22 Sep 18:05:37 - [debug] Module: node-red-contrib-interval-length 0.0.6 /opt/node_modules/node-red-contrib-interval-length
22 Sep 18:05:37 - [debug] Module: node-red-contrib-modbus 5.23.1 /opt/node_modules/node-red-contrib-modbus
22 Sep 18:05:37 - [debug] Module: node-red-contrib-moment 4.0.0 /opt/node_modules/node-red-contrib-moment
22 Sep 18:05:37 - [debug] Module: node-red-contrib-persistent-fsm 1.2.0 /opt/node_modules/node-red-contrib-persistent-fsm
22 Sep 18:05:37 - [debug] Module: node-red-contrib-sunevents 3.0.3 /opt/node_modules/node-red-contrib-sunevents
22 Sep 18:05:37 - [debug] Module: node-red-contrib-time-range-switch 1.1.3 /opt/node_modules/node-red-contrib-time-range-switch
22 Sep 18:05:37 - [debug] Module: node-red-dashboard 3.2.0 /opt/node_modules/node-red-dashboard
22 Sep 18:05:37 - [debug] Module: node-red-node-base64 0.3.0 /opt/node_modules/node-red-node-base64
22 Sep 18:05:37 - [debug] Module: node-red-node-email 1.17.0 /opt/node_modules/node-red-node-email
22 Sep 18:05:37 - [debug] Module: node-red-node-feedparser 0.3.0 /opt/node_modules/node-red-node-feedparser
22 Sep 18:05:37 - [debug] Module: node-red-node-ping 0.3.1 /opt/node_modules/node-red-node-ping
22 Sep 18:05:37 - [debug] Module: node-red-node-random 0.4.0 /opt/node_modules/node-red-node-random
22 Sep 18:05:37 - [debug] Module: node-red-node-serialport 1.0.1 /opt/node_modules/node-red-node-serialport
22 Sep 18:05:37 - [debug] Module: node-red-node-smooth 0.1.2 /opt/node_modules/node-red-node-smooth
22 Sep 18:05:37 - [debug] Module: node-red-node-suncalc 1.0.1 /opt/node_modules/node-red-node-suncalc
22 Sep 18:05:37 - [debug] Module: node-red-node-twitter 1.2.0 /opt/node_modules/node-red-node-twitter
22 Sep 18:05:38 - [info] Dashboard version 3.2.0 started at /endpoint/ui
22 Sep 18:05:38 - [info] Settings file  : /etc/node-red/config.js
22 Sep 18:05:38 - [info] Context store  : 'default' [module=memory]
22 Sep 18:05:38 - [info] User directory : /config/node-red/
22 Sep 18:05:38 - [warn] Projects disabled : editorTheme.projects.enabled=false
22 Sep 18:05:38 - [info] Flows file     : /config/node-red/flows.json
22 Sep 18:05:38 - [debug] loaded flow revision: baddcab185bfe94ff868bd33355d8076
22 Sep 18:05:38 - [debug] red/runtime/nodes/credentials.load : user provided key
22 Sep 18:05:38 - [debug] red/runtime/nodes/credentials.load : keyType=user
22 Sep 18:05:38 - [warn] Encrypted credentials not found
22 Sep 18:05:38 - [info] Server now running at http://127.0.0.1:46836/
22 Sep 18:05:38 - [info] Starting flows
22 Sep 18:05:38 - [debug] red/nodes/flows.start : starting flow : global
22 Sep 18:05:38 - [info] Started flows
[18:05:39] INFO: Starting NGinx...
22 Sep 18:05:43 - [info] [server:Home Assistant] Connecting to http://supervisor/core
22 Sep 18:05:43 - [info] [server:Home Assistant] Connected to http://supervisor/core
22 Sep 18:05:44 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
22 Sep 18:05:44 - [debug] [server:Home Assistant] HA State: running
22 Sep 18:05:49 - [info] [server:Home Assistant] Connecting to http://supervisor/core
22 Sep 18:05:49 - [info] [server:Home Assistant] Connected to http://supervisor/core
22 Sep 18:05:49 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
22 Sep 18:05:54 - [info] [server:Home Assistant] Connecting to http://supervisor/core
22 Sep 18:05:54 - [info] [server:Home Assistant] Connected to http://supervisor/core
22 Sep 18:05:54 - [info] [server:Home Assistant] Connection closed to http://supervisor/core


##### Log Supervisor
258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5505187 exceeds limit 4194304') is not str
22-09-22 18:06:20 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-09-22 18:06:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-09-22 18:06:25 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-09-22 18:06:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-09-22 18:06:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5505187 exceeds limit 4194304') is not str
22-09-22 18:06:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-09-22 18:06:30 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-09-22 18:06:30 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-09-22 18:06:30 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-09-22 18:06:30 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5505126 exceeds limit 4194304') is not str
22-09-22 18:06:30 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-09-22 18:06:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-09-22 18:06:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-09-22 18:06:35 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-09-22 18:06:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-09-22 18:06:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5505082 exceeds limit 4194304') is not str
22-09-22 18:06:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
