### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by cmsjin** [hassio-addons/addon-node-red#1434]
webui prompt 502: Bad Gateway

**Comment by frenck** [comment]
anything in the logs?

**Comment by cmsjin** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting s6-rc: info: service s6rc-oneshot-runner successfully started s6-rc: info: service fix-attrs: starting s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting cont-init: info: running /etc/cont-init.d/00-banner.sh -----------------------------------------------------------  Add-on: Node-RED  Flow-based programming for the Internet of Things -----------------------------------------------------------  Add-on version: 13.3.2  You are running the latest version of this add-on.  System: Armbian 22.08.0-trunk Bullseye  (aarch64 / qemuarm-64)  Home Assistant Core: 2022.9.2  Home Assistant Supervisor: 2022.08.6 -----------------------------------------------------------  Please, share the above information when looking for help  or support in, e.g., GitHub, forums or the Discord chat. ----------------------------------------------------------- cont-init: info: /etc/cont-init.d/00-banner.sh exited 0 cont-init: info: running /etc/cont-init.d/01-log-level.sh cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0 cont-init: info: running /etc/cont-init.d/customizations.sh cont-init: info: /etc/cont-init.d/customizations.sh exited 0 cont-init: info: running /etc/cont-init.d/nginx.sh [10:54:03] FATAL:  [10:54:03] FATAL: SSL has been enabled using the 'ssl' option, [10:54:03] FATAL: this requires a SSL certificate file which is [10:54:03] FATAL: configured using the 'certfile' option in the [10:54:03] FATAL: add-on configuration. [10:54:03] FATAL:  [10:54:03] FATAL: Unfortunately, the file specified in the [10:54:03] FATAL: 'certfile' option does not exists. [10:54:03] FATAL:  [10:54:03] FATAL: Please ensure the certificate file exists and [10:54:03] FATAL: is placed in the '/ssl/' directory. [10:54:03] FATAL:  [10:54:03] FATAL: In case you don't have SSL yet, consider getting [10:54:03] FATAL: a SSL certificate or setting the 'ssl' option [10:54:03] FATAL: to 'false' in case you are not planning on using [10:54:03] FATAL: SSL with this add-on. [10:54:03] FATAL:  [10:54:03] FATAL: Check the add-on manual for more information. [10:54:03] FATAL:  cont-init: info: /etc/cont-init.d/nginx.sh exited 1 cont-init: info: running /etc/cont-init.d/node-red.sh [10:54:04] FATAL:  [10:54:04] FATAL: Configuration of this add-on is incomplete. [10:54:04] FATAL:  [10:54:04] FATAL: Please be sure to set the "credential_secret" option. [10:54:04] FATAL:  [10:54:04] FATAL: The credential secret is an encryption token, much like [10:54:04] FATAL: a password, that is used by Node-RED for encrypting [10:54:04] FATAL: credentials you put into Node-RED. [10:54:04] FATAL:  [10:54:04] FATAL: Just like a password, a credential secret can be [10:54:04] FATAL: anything you like. Just be sure to store it somewhere [10:54:04] FATAL: safe for later, e.g., in case of a recovery. [10:54:04] FATAL:  cont-init: info: /etc/cont-init.d/node-red.sh exited 1 cont-init: warning: some scripts exited nonzero s6-rc: warning: unable to start service legacy-cont-init: command exited 1 /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information. prog: fatal: stopping the container. s6-rc: info: service fix-attrs: stopping s6-rc: info: service fix-attrs successfully stopped s6-rc: info: service s6rc-oneshot-runner: stopping s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by cmsjin** [comment]
has been resolved.
