### ISSUE TITLE
Node-red does not run

### ISSUE THREAD

**Issue by PierreScerri** [hassio-addons/addon-node-red#144]
# Problem/Motivation

> Node-red add-on stopping with errors

## Expected behavior

>Normal function
## Actual behavior

>Several errors during Hassio restart and when started manually

This log is produced:

> [cont-init.d] 81-npm-packages.sh: executing... 
> > serialport@6.2.2 install /opt/node_modules/modbus-serial/node_modules/serialport
> > prebuild-install || node-gyp rebuild
> prebuild-install WARN install No prebuilt binaries found (target=8.14.0 runtime=node arch=arm platform=linux)
> gyp ERR! build error 
> gyp ERR! stack Error: not found: make
> gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
> gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
> gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
> gyp ERR! System Linux 4.14.98-v7
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /opt/node_modules/modbus-serial/node_modules/serialport
> gyp ERR! node -v v8.14.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the serialport@6.2.2 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-02-26T12_00_48_198Z-debug.log
> FATAL: Failed installing npm package node-red-contrib-modbus
> [cont-init.d] 81-npm-packages.sh: exited 1.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] 99-message.sh: executing... 
> -----------------------------------------------------------
>                 Oops! Something went wrong.
>  
>  We are so sorry, but something went terribly wrong when
>  starting or running this add-on.
>  
>  Be sure to check the log above, line by line, for hints.
> -----------------------------------------------------------
> [cont-finish.d] 99-message.sh: exited 0.
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment]
Could you please provide me the add-on configuration? Thanks!

**Comment by PierreScerri** [comment]
{
  "log_level": "info",
  "credential_secret": "xxxxxxxx",
  "dark_mode": false,
  "http_node": {
    "username": "",
    "password": ""
  },
  "http_static": {
    "username": "",
    "password": ""
  },
  "port": 1880,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [
    "node-red-contrib-modbus",
    "node-red-dashboard"
  ],
  "init_commands": []
}

>

**Comment by PierreScerri** [comment]
I think it happened when I updated to version 1.3.3 a few hours ago.
Tried uninstalling & reinstalling to no avail.
Thanks.

**Comment by frenck** [comment]
Try removing the custom `npm_packages` and see if it starts.

**Comment by PierreScerri** [comment]
Getting this now:

> > hassio-addon-node-red@ start /opt
> > node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
> Error loading settings file: /etc/node-red/config.js
> Error: Cannot find module '/config/node-red/settings.js'

**Comment by frenck** [comment]
If you have applied customizations to `/config/node-red/setting.js` please comment them out (or remove them) as well.

**Comment by PierreScerri** [comment]
Running now.  Let me try to re-add the nom_packages.
No customisation made in settings.js
Gimme a minute.

**Comment by PierreScerri** [comment]
Runs OK without the nom packages but obviously It is now missing those components and my flows will not work.

Trying to install packages manually but it's not doing it.

**Comment by frenck** [comment]
Ok, here is the case, you are trying to install custom npm packages, which (apparently) needs to build some things. The build fails, and contains messages about missing tools, e.g., `Error: not found: make`.

You have to install the required `system_packages` needed for your `npm_packages`.
The add-on does not ship with build tools.

**Comment by PierreScerri** [comment]
Don't know what I did but I restarted it again and all is well now.  go figure

**Comment by PierreScerri** [comment]
Restored 1.3.2 and all is well

**Comment by frenck** [comment]
That is quite possible, 1.3.3 upgrades the serial node, one of you npm packages relies on an older version of that node, hence it tries to build the specific version for it.

You should specify the required `system_packages` to be able to build your dependencies.

**Comment by PierreScerri** [comment]
Don't know exactly what needs to be done.

Added "node-red-node-serialport" in system_packages but that did not work.

**Comment by esnil** [comment]
I had the same problem. As a workaround until the "node-red-contrib-modbus" package is updated (which I assume is what needs to be done..) I manually installed the older 1.3.2 version of this add on.

For others to follow:
Using https://developers.home-assistant.io/docs/en/hassio_addon_tutorial.html 

Steps:
- download sourcecode for 1.3.2 and copy node-red folder to /addons folder
- update gui i hassio/addon store
- install node red

@frenck , keep up the good job. Its highly appreciated!

**Comment by frenck** [comment]
Make the system packages of your add-on configuration like so:

```
"system_packages": [
"make",
"g++",
"linux-headers"
],
```

That should do the trick!

**Comment by esnil** [comment]
> Make the system packages of your add-on configuration like so:
> 
> ```
> "system_packages": [
> "make",
> "g++",
> "linux-headers"
> ],
> ```
> That should do the trick!

I tried this, except for the "linux-headers", I'll try again tonight with also linux-headers. However, from what I tried to read from the source code, isn't make and g++ already included when the container is built?

**Comment by frenck** [comment]
They are only used / available during the container build and removed before finishing.

**Comment by louis000008** [comment]
1.3.4  can not run:
node-red-contrib-modbus

**Comment by esnil** [comment]
> Make the system packages of your add-on configuration like so:
> 
> ```
> "system_packages": [
> "make",
> "g++",
> "linux-headers"
> ],
> ```
> That should do the trick!

Excelent! Tried that earlier but I didn't have enough understanding to also add linux-headers. It was a notably longer startup time during wich there was no log output (using log level info) so if you are running on e.g. Raspberry be patient. Again, thank you @frenck !

@louis000008 , try the sollution above.

**Comment by frenck** [comment]
@esnil The longer startup times are expected, since well, it needs to compile the code.

The main problem is with `node-red-contrib-modbus`, they are behind on their dependency updates.

Thanks for letting me know it worked out @esnil 👍
