### ISSUE TITLE
email MTA not reachable

### ISSUE THREAD

**Issue by chaelli** [hassio-addons/addon-node-red#1443]
# Problem/Motivation

I try to send _local_ mails to the email MTA node to react to it (have an ip camera that cannot send events any other way, but can use a local smtp server)

## Expected behavior

I expected to be able to specify any port (e.g. 2525) and then "send mail" into this (or connect via telnet)

## Actual behavior

With telnet I just get a connection error and the camera also gives me an error when trying to send the mail

## Steps to reproduce

Create an "email MTA" node and specify any port for incoming (disable start tls and auth) and try to send an email to this smtp server

## Proposed changes

while I know this should run on the host network.. I wonder why it doesn't work. I run home assistant on their own OS on a raspi.

**Comment by sinclairpaul** [comment]
Unfortunately I cannot duplicate as it seems to work ok here:

![image](https://user-images.githubusercontent.com/24625998/190277630-fc3b8641-c38c-4066-b972-b1d9c44a1be1.png)

![image](https://user-images.githubusercontent.com/24625998/190277693-0e0422f8-338c-42e2-bd3f-8df3cfc6e5b9.png)

**Comment by chaelli** [comment]
Hi @sinclairpaul 

sorry - feel bad now :( just had to remove the old nodered folder (had used it before) and completely reinstall it. Now it works! Sorry, should have tried this before.

Thanks again
