### ISSUE TITLE
nbrowser crashes nodered

### ISSUE THREAD

**Issue by magiva** [hassio-addons/addon-node-red#1448]
# Problem/Motivation

I added and injection node and an nbrowser node. 
i added a website to the payload of the injection node - https://www.fjordkraft.no/strom/strompriser/dagens/
the webpage is dynamic as it loads data into it on load, so i cant just scrape it the normal way.
i added a debug to initially see results
deployed
when i click inject, the log says it crashed

22 Sep 15:41:46 - [info] [debug:HA msg] 76.4100
22 Sep 15:50:25 - [info] Stopping modified nodes
22 Sep 15:50:25 - [info] Stopped modified nodes
22 Sep 15:50:25 - [info] Updated flows
22 Sep 15:50:26 - [info] Starting modified nodes
22 Sep 15:50:26 - [info] Started modified nodes
22 Sep 15:50:37 - [red] Uncaught Exception:
22 Sep 15:50:37 - [error] Error: spawn /config/node-red/node_modules/electron/dist/electron ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[15:50:37] WARNING: **Node-RED crashed, halting add-on**
[15:50:37] INFO: Node-RED stopped, restarting...
s6-rc: info: service legacy-services: stopping
[15:50:38] INFO: Node-RED stopped, restarting...
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

> (Why the issue was filed)
using nbrowser crashed nodered

## Expected behavior
i expected to see output in some form so that i could start to collect other data from the dynamic webpage

> (What you expected to happen)

## Actual behavior
crashes nodered

> (What actually happened)

## Steps to reproduce
as above
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by magiva** [comment]
i dont know how to get this some attention

**Comment by frenck** [comment]
The `nbrowser` node is not provided or managed by this add-on. If you have problems using that node, please contact the author of that node.

From an add-on perspective, there is nothing I can do.

../Frenck
