### ISSUE TITLE
Installation aborts with a failure message

### ISSUE THREAD

**Issue by DerElch87** [hassio-addons/addon-node-red#147]
# Problem/Motivation

> The installation of the Hass.io Node-Red addon is not possible

## Expected behavior

> Installation working

## Actual behavior

> Installation aborts with the following failure message:
19-02-28 06:43:25 INFO (SyncWorker_17) [hassio.docker.interface] Pull image hassioaddons/node-red-armhf tag 1.3.4.
19-02-28 06:43:27 ERROR (SyncWorker_17) [hassio.docker.interface] Can't install hassioaddons/node-red-armhf:1.3.4 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").

## Steps to reproduce

> It happens always, after reboot, update of Host system etc.

## Proposed changes

> Running on 
Hass.io supervisor Version | 145
System | HassOS 2.10
Deployment | production
Raspberry 3B+

Installation of other add-ons is working perfectly.
Also right now there is nothing which behaves unusual - so everything is running perfect - except this addon installation.

**Comment by frenck** [comment]
This is an issue outside of the control of the add-on.
Installation and update of an add-on are done by Hassio.

Please report this issue with Home Assistant / Hassio / HassOS.
Thanks!
