### ISSUE TITLE
"Error: Invalid server config" when upgrading to 13.5.0

### ISSUE THREAD

**Issue by Nealtron** [hassio-addons/addon-node-red#1476]
# Problem/Motivation

Left my house this morning with my all of my automations working. Came home to none of my automations working. Each node in Node-RED having the state "error" and log is full of the following:

```
27 Oct 21:10:00 - [error] [api-current-state:8d5d7add97166c02] Error: Invalid server config
27 Oct 21:10:00 - [error] [api-current-state:ba7c6dc22430e3ef] Error: Invalid server config
27 Oct 21:10:00 - [error] [server-state-changed:3e1a436a4aa3bc4c] Error: Server config node not found
27 Oct 21:10:00 - [error] [api-call-service:60af4994936ecc08] Error: Server config node not found
27 Oct 21:10:00 - [error] [api-call-service:7feeba8fdb016e27] Error: Server config node not found
```

![image](https://user-images.githubusercontent.com/6655394/198439379-74fec01f-26df-485f-b20d-39400169feab.png)

According to my logs, the Node-Red plugin auto-updated from 13.4.0 to 13.5.0. Restored the add-on from a backup taken before the upgrade and the errors are gone and automations are working. Upgrade to 13.5.0 and it the it fails the same way. I've repeated the process of restoring and upgrading 3 times, and the problem comes back every time. 

## Expected behavior

Automations run. 

## Actual behavior

No automations run. 

## Steps to reproduce

Update to 13.5.0

## Proposed changes
No idea.

**Comment by Nealtron** [comment]
I had a feeling it had something to do with the fact that I had an apostrophe and/or parenthesis in my server node name. So I restored to a working state again, renamed my server node to something simpler, and verified that everything was working still. Manually upgraded to 13.5.0, and everything seems to work fine.

**Comment by meisaku** [comment]
I ran into this same issue when upgrading from 13.4.0 to 13.5.0 - and downgraded to get our automations running. After seeing the above post from @Nealtron I decided to look into the Node-Red settings to see if I also had something strange in the server node name field.

I had never touched the server node settings inside Node-Red so the values and structure most likely originated from some very old version of this addon. My server name is also very default "Home Assistant" so I did not change that, but I noticed that there was an unchecked checkbox "Using the Home Assistant Add-on" (it was working just fine without it - and might been doing so for who knows how long as I had never even looked at these).

![SCR-20221028-f6a](https://user-images.githubusercontent.com/4282263/198572178-f6ecff70-e2d1-430b-98d4-3beac2983a5e.png)

I checked the box and everything continued to work in 13.4.0. I then upgraded to 13.5.0 and now it also works fine.

Maybe the settings needed just some change to get them saved in a more compatible format? Or maybe this "Using the Home Assistant Add-on" was previously not needed but is now mandatory.

**Comment by cloudwalker87** [comment]
> ![SCR-20221028-jjf](https://user-images.githubusercontent.com/4282263/198572693-8a15744f-34a2-4bc7-9d38-f4d25010c9a8.png)
> 
> I checked the box and everything continued to work in 13.4.0. I then upgraded to 13.5.0 and now it also works fine.

I have had exactly the same issue today - I upgraded and everything broke - ticking the "Using the home assistant add-on" solved it for me too

**Comment by hammie00** [comment]
Same problem.
Running on Rpi4.
Always worked fine.
After update  addon_a0d7b954_nodered_13.4.0 NR stopped working.
Strange even more, if I go back to a previous backup of HA, it still crashes.
I've tried in the config to add user and password addition, as suggested elsewere.

Any help appreciated!!

30 Oct 15:59:18 - [error] [api-current-state:aedfb872f8fa8a75] Error: Invalid server config
30 Oct 15:59:18 - [error] [api-current-state:5349d47fe5ce817a] Error: Invalid server config
30 Oct 15:59:18 - [error] [server-state-changed:19552a10d0c77235] Error: Server config node not found
30 Oct 15:59:18 - [error] [api-current-state:2b4d8a5ec484b2e8] Error: Invalid server config
30 Oct 15:59:18 - [error] [api-current-state:0edaa64487b9cd4d] Error: Invalid server config
30 Oct 15:59:18 - [error] [api-call-service:9945e7746a2fa7c9] Error: Server config node not found
30 Oct 15:59:18 - [error] [api-current-state:e259b4c34f5a64f1] Error: Invalid server config
30 Oct 15:59:18 - [error] [server-state-changed:8e5b837e5221730f] Error: Server config node not found
30 Oct 15:59:18 - [error] [api-current-state:626818ce96b5c894] Error: Invalid server config
30 Oct 15:59:18 - [error] [api-call-service:8c2ad434677e70d1] Error: Server config node not found
30 Oct 15:59:18 - [error] [server-state-changed:e95d10e53545dcb6] Error: Server config node not found
30 Oct 15:59:18 - [error] [api-current-state:4adf4e6ac9e9209c] Error: Invalid server config
30 Oct 15:59:18 - [error] [server-state-changed:a840fc56d168b41d] Error: Server config node not found
30 Oct 15:59:18 - [error] [server-state-changed:b15cbb1455814d4e] Error: Server config node not found

**Comment by jjlink** [comment]
Same Problem. Where do I find the settings for edit server node?

Node-RED
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 13.5.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / odroid-n2)
 Home Assistant Core: 2022.10.5
 Home Assistant Supervisor: 2022.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to INFO
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
cont-init: info: /etc/cont-init.d/customizations.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
up to date, audited 149 packages in 2s
10 vulnerabilities (7 high, 3 critical)
To address issues that do not require attention, run:
  npm audit fix
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
cont-init: info: /etc/cont-init.d/node-red.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun nodered (no readiness notification)
s6-rc: info: service legacy-services successfully started
[10:42:04] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
30 Oct 10:42:07 - [info] 
Welcome to Node-RED
===================
30 Oct 10:42:07 - [info] Node-RED version: v3.0.2
30 Oct 10:42:07 - [info] Node.js  version: v16.17.1
30 Oct 10:42:07 - [info] Linux 5.15.74 arm64 LE
30 Oct 10:42:08 - [info] Loading palette nodes
[10:42:08] INFO: Starting NGinx...
30 Oct 10:42:11 - [info] Dashboard version 3.2.0 started at /endpoint/ui
30 Oct 10:42:11 - [info] Settings file  : /etc/node-red/config.js
30 Oct 10:42:11 - [info] Context store  : 'memoryOnly' [module=memory]
30 Oct 10:42:11 - [info] Context store  : 'file' [module=localfilesystem]
30 Oct 10:42:11 - [info] User directory : /config/node-red/
30 Oct 10:42:11 - [info] Projects directory: /config/node-red/projects
30 Oct 10:42:12 - [info] Server now running at http://127.0.0.1:46836/
30 Oct 10:42:12 - [info] Active project : MyProject
30 Oct 10:42:12 - [info] Flows file     : /config/node-red/projects/MyProject/flows.json
30 Oct 10:42:12 - [info] Starting flows
30 Oct 10:42:12 - [error] [server:c5cb4f9d.c447e] Error: No credentials provided
30 Oct 10:42:12 - [error] [api-current-state:f999be0a.29055] Error: Invalid server config
30 Oct 10:42:12 - [error] [api-call-service:5cf4f7fa.15ea98] Error: Server config node not found
30 Oct 10:42:12 - [info] Started flows
30 Oct 10:42:12 - [info] [mqtt-broker:192.168.1.72] Connected to broker: mqtt://192.168.1.72:1883
30 Oct 10:42:17 - [info] [server:Home Assistant] Connecting to http://supervisor/core
30 Oct 10:42:17 - [info] [server:Home Assistant] Connecting to http://supervisor/core
30 Oct 10:42:17 - [info] [server:Home Assistant] Connecting to http://supervisor/core
30 Oct 10:42:17 - [info] [server:Home Assistant] Connected to http://supervisor/core
30 Oct 10:42:17 - [info] [server:Home Assistant] Connected to http://supervisor/core
30 Oct 10:42:17 - [info] [server:Home Assistant] Connected to http://supervisor/core

**Comment by Nealtron** [comment]
@jjlink Open the Node-RED webui. Click on the menu button the top right, and click on "configuration nodes".  Make sure you are looking uunder "On all flows" and look for "server" nodes. More than likely, you'll only have one. Double click it to modify.


![image](https://user-images.githubusercontent.com/6655394/198906135-3e4a02d5-6ed6-4e3f-ac5e-a8e6b9161197.png)

**Comment by hammie00** [comment]
My problem is different (initial the same error), but I cant access my NR.
When I press the link or look in settings, it says NR not started. Please start.
Pressing start doesnt work.
BUT, I see my flows are working when I test them! How weird is that?
When I acces a backup from before the error, I get the same error, still cant access NR.

Is there a way in config to change the node configuration?
Is there a way to downgrade NR to previous versions in the hope I get it working again?

Any help appreciated!
TIA

**Comment by jjlink** [comment]
> Same Problem. Where do I find the settings for edit server node?
> 
> ## Node-RED
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> cont-init: info: running /etc/cont-init.d/00-banner.sh
> ## Add-on: Node-RED
> Flow-based programming for the Internet of Things
> ## Add-on version: 13.5.0
> You are running the latest version of this add-on.
> System: Home Assistant OS 9.3 (aarch64 / odroid-n2)
> Home Assistant Core: 2022.10.5
> Home Assistant Supervisor: 2022.10.0
> ## Please, share the above information when looking for help
> or support in, e.g., GitHub, forums or the Discord chat.
> cont-init: info: /etc/cont-init.d/00-banner.sh exited 0 cont-init: info: running /etc/cont-init.d/01-log-level.sh Log level is set to INFO cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0 cont-init: info: running /etc/cont-init.d/customizations.sh cont-init: info: /etc/cont-init.d/customizations.sh exited 0 cont-init: info: running /etc/cont-init.d/nginx.sh cont-init: info: /etc/cont-init.d/nginx.sh exited 0 cont-init: info: running /etc/cont-init.d/node-red.sh patching file nodes/ui_base.html Hunk #1 succeeded at 1164 (offset 633 lines). up to date, audited 149 packages in 2s 10 vulnerabilities (7 high, 3 critical) To address issues that do not require attention, run: npm audit fix Some issues need review, and may require choosing a different dependency. Run `npm audit` for details. cont-init: info: /etc/cont-init.d/node-red.sh exited 0 s6-rc: info: service legacy-cont-init successfully started s6-rc: info: service legacy-services: starting services-up: info: copying legacy longrun nginx (no readiness notification) services-up: info: copying legacy longrun nodered (no readiness notification) s6-rc: info: service legacy-services successfully started [10:42:04] INFO: Starting Node-RED...
> 
> > start
> > node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
> > 30 Oct 10:42:07 - [info]
> > Welcome to Node-RED
> > ===================
> > 30 Oct 10:42:07 - [info] Node-RED version: v3.0.2
> > 30 Oct 10:42:07 - [info] Node.js  version: v16.17.1
> > 30 Oct 10:42:07 - [info] Linux 5.15.74 arm64 LE
> > 30 Oct 10:42:08 - [info] Loading palette nodes
> > [10:42:08] INFO: Starting NGinx...
> > 30 Oct 10:42:11 - [info] Dashboard version 3.2.0 started at /endpoint/ui
> > 30 Oct 10:42:11 - [info] Settings file  : /etc/node-red/config.js
> > 30 Oct 10:42:11 - [info] Context store  : 'memoryOnly' [module=memory]
> > 30 Oct 10:42:11 - [info] Context store  : 'file' [module=localfilesystem]
> > 30 Oct 10:42:11 - [info] User directory : /config/node-red/
> > 30 Oct 10:42:11 - [info] Projects directory: /config/node-red/projects
> > 30 Oct 10:42:12 - [info] Server now running at http://127.0.0.1:46836/
> > 30 Oct 10:42:12 - [info] Active project : MyProject
> > 30 Oct 10:42:12 - [info] Flows file     : /config/node-red/projects/MyProject/flows.json
> > 30 Oct 10:42:12 - [info] Starting flows
> > 30 Oct 10:42:12 - [error] [server:c5cb4f9d.c447e] Error: No credentials provided
> > 30 Oct 10:42:12 - [error] [api-current-state:f999be0a.29055] Error: Invalid server config
> > 30 Oct 10:42:12 - [error] [api-call-service:5cf4f7fa.15ea98] Error: Server config node not found
> > 30 Oct 10:42:12 - [info] Started flows
> > 30 Oct 10:42:12 - [info] [mqtt-broker:192.168.1.72] Connected to broker: mqtt://192.168.1.72:1883
> > 30 Oct 10:42:17 - [info] [server:Home Assistant] Connecting to http://supervisor/core
> > 30 Oct 10:42:17 - [info] [server:Home Assistant] Connecting to http://supervisor/core
> > 30 Oct 10:42:17 - [info] [server:Home Assistant] Connecting to http://supervisor/core
> > 30 Oct 10:42:17 - [info] [server:Home Assistant] Connected to http://supervisor/core
> > 30 Oct 10:42:17 - [info] [server:Home Assistant] Connected to http://supervisor/core
> > 30 Oct 10:42:17 - [info] [server:Home Assistant] Connected to http://supervisor/core

2022-11-01 Update: I restored NR from my backup to version 13.4.0 and the issues went away.

**Comment by joggs** [comment]
Same problem. Does not matter what values I modify or even create a new server node. Has been stable för years before this

**Comment by colinodell** [comment]
> More than likely, you'll only have one. Double click it to modify.

For some unknown reason, I have three, and one of them had "Using the Home Assistant addon" unchecked.  Checking that and re-deploying fixed everything for me.

**Comment by dangel666** [comment]
I am also having what is likely the same problem - I'm running HA with Node Red and some time ago I noticed that HA upgrades work fine but I'm unable to go beyond the NR addon release of 13.4.0 without the same thing happening to my HA nodes - deconz nodes carry on working. Rolling back NR doesn't fix this - instead I have to restore a complete HA backup before things start working again. It's quite odd!

I've not had time to look at this till today so stuck with 13.4.0 till now. I tried opening a broken node and checked the server selected - i have four "Home Assistant" servers(!). The one selected didn't work so I'd tried the second one in the list. Deploy. Node appears to work... In this case a fridge open/close sensor. However, the next node in the same flow - a notify node which calls alexa_media didn't respond to me changing it the same way and still shows error..

If I look at my config on all flows I can see I indeed have four "Home Assistant" 'servers' - with 111 nodes using the first - which is solid boxed. The following three have no nodes using them and are dashed.

![image](https://user-images.githubusercontent.com/44338896/210591025-de2afa5e-2798-48a2-b193-19bf41d97215.png)

**Comment by dangel666** [comment]
If I disable these 'home assistant' servers that are unused then everything works still.  As long as I don't upgrade..

**Comment by dangel666** [comment]
So (rambling on) I noticed that the first "Home Assistant" server name property is actually empty - I typed in "Home Assistant" and this wasn't much liked - without the space it suddenly was.. (something about an invalid URL flashed up).  So now I've decided to delete these 'extra' servers and with the rename see what happens if I update..

**Comment by dangel666** [comment]
...annnnd now:

4 Jan 15:52:12 - [info] Started flows
4 Jan 15:52:12 - [info] [deconz-server:Deconz Server] WebSocket opened
4 Jan 15:52:16 - [info] [server:HomeAssistant] Connecting to http://supervisor/core
4 Jan 15:52:17 - [info] [server:HomeAssistant] Connected to http://supervisor/core

Mein God!  It so far looks happy and no red errors on my nodes...

**Comment by stcbus** [comment]
> So (rambling on) I noticed that the first "Home Assistant" server name property is actually empty - I typed in "Home Assistant" and this wasn't much liked - without the space it suddenly was.. (something about an invalid URL flashed up). So now I've decided to delete these 'extra' servers and with the rename see what happens if I update..

this worked for me too. Many thanks!!

**Comment by dangel666** [comment]
FWIW this line triggered me looking at the properties:

4 Jan 15:09:01 - [error] [server:fabd9cf1.19d2e] Error: Invalid property expression: unterminated expression

...whether there is a bug here is interesting but since it worked before it's worth thinking about.  Certainly it wasn't coping with the property being empty, nor with it having a space in it.
