### ISSUE TITLE
Node Red not working correctly after update

### ISSUE THREAD

**Issue by rodhall** [hassio-addons/addon-node-red#1479]
# Problem/Motivation
I am unable to access the Node Red frontend on HA after the update. The add-on shows a red dot indicating it has some sort of problem yet the logs show that Node Red is running.

## Expected behavior
Given the logs seem fine I would expect to be able to access Node Red from the menu bar. However, I get a "Addon is not started" error when I try to access it.

## Steps to reproduce
Simply install Node Red. This is a persistent recurring problem for me. It will not work after multiple rebuilds, reinstalls, etc.

Logs below

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 13.5.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.10.5
 Home Assistant Supervisor: 2022.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
cont-init: info: /etc/cont-init.d/customizations.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
up to date, audited 6 packages in 454ms
found 0 vulnerabilities
cont-init: info: /etc/cont-init.d/node-red.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun nodered (no readiness notification)
s6-rc: info: service legacy-services successfully started
[09:20:50] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
2 Nov 09:20:52 - [info] 
Welcome to Node-RED
===================
2 Nov 09:20:52 - [info] Node-RED version: v3.0.2
2 Nov 09:20:52 - [info] Node.js  version: v16.17.1
2 Nov 09:20:52 - [info] Linux 5.15.74 x64 LE
2 Nov 09:20:53 - [info] Loading palette nodes
2 Nov 09:20:55 - [info] Dashboard version 3.2.0 started at /endpoint/ui
2 Nov 09:20:55 - [info] Settings file  : /etc/node-red/config.js
2 Nov 09:20:55 - [info] Context store  : 'default' [module=memory]
2 Nov 09:20:55 - [info] User directory : /config/node-red/
2 Nov 09:20:55 - [warn] Projects disabled : editorTheme.projects.enabled=false
2 Nov 09:20:55 - [info] Flows file     : /config/node-red/flows.json
2 Nov 09:20:55 - [info] Server now running at http://127.0.0.1:46836/
[09:20:55] INFO: Starting NGinx...
2 Nov 09:20:55 - [info] Starting flows
2 Nov 09:20:55 - [info] Started flows
2 Nov 09:20:57 - [error] [api-call-service:Turn off path lights] Call-Service attempted without connection to server.
2 Nov 09:21:00 - [info] [server:Home Assistant] Connecting to http://supervisor/core
2 Nov 09:21:00 - [info] [server:Home Assistant] Connected to http://supervisor/core

Screenshot of front end message concurrent with this log.

<img width="514" alt="Screenshot 2022-11-02 at 10 41 51 AM" src="https://user-images.githubusercontent.com/2503968/199562747-6da6f608-d53f-420e-84d8-51fdc88f696e.png">

And a shot of the Node Red configuration page

<img width="1054" alt="Screenshot 2022-11-02 at 10 43 36 AM" src="https://user-images.githubusercontent.com/2503968/199563079-cdb0ebb0-9b15-4972-9394-a554ec75d10e.png">

**Comment by FoUStep** [comment]
Same issue here, rollback to 13.5.0 solved my issue.

**Comment by gszigethy** [comment]
Same here. Logs below. Roll back to 13.5.0 resolves the issues. If I remove the addon and install 13.5.1 from the addon repository, I still et the below problems.

```
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
[09:24:57] INFO: Starting installation of custom NPM/Node-RED packages...
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
npm ERR! code 1
npm ERR! path /opt/node_modules/@serialport/bindings
npm ERR! command failed
npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=16.17.1 runtime=node arch=x64 libc=musl platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.1 | linux | x64
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:408:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Linux 5.10.0-13-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /opt/node_modules/@serialport/bindings
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-03T08_24_57_790Z-debug-0.log
[09:25:02] FATAL: Failed to install a specified npm package
cont-init: info: /etc/cont-init.d/customizations.sh exited 1
cont-init: info: running /etc/cont-init.d/nginx.sh
```

**Comment by steefzz** [comment]
I also had issues with it and was able to start it again by adding these packages:
```
npm_packages:
  - nan
  - serialport
  - node-red-contrib-rfxcom
system_packages:
  - make
  - python3
  - g++
  - gcc
  - linux-headers
```

Hope this helps. Seems like some packages are missing?
Also posted [here](https://community.home-assistant.io/t/node-red-contrib-rfxcom-stopped-working/212598/11?u=steefzz).

**Comment by rodhall** [comment]
I realized this was a wider issue with other add-ons. The add ons were running but the frontend was showing them not running for some reason. For example, in Node Red my automations were still working but I was unable to edit in the frontend as it kept telling me to start the add-on. The same was true for File Editor. Now spontaneously the issue seems to have resolved itself. I am closing this though it was a weird one.
