### ISSUE TITLE
package fails to install

### ISSUE THREAD

**Issue by tarbax** [hassio-addons/addon-node-red#148]
i try to install i2c and bme280 package and i get:

config:
```
"npm_packages": [
    "node-red-contrib-sensor-ds18b20",
    "node-red-contrib-ui",
    "node-red-contrib-i2c",
    "node-red-contrib-bme280-rpi"   
],
```
error:
```
> i2c-bus@1.2.5 install /opt/node_modules/i2c-bus
> node-gyp rebuild
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.14.98-v7
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/i2c-bus
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i2c-bus@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the i2c-bus@1.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-02T09_53_01_403Z-debug.log
FATAL: Failed installing npm package node-red-contrib-i2c
```
system: rpi 3b with HassOS 2.10

**Comment by frenck** [comment]
Please read the error log, since the hints are in there:

`Error: not found: make`

Please install make using the `system_packages` option.

**Comment by tarbax** [comment]
> Please read the error log, since the hints are in there:
> 
> `Error: not found: make`
> 
> Please install make using the `system_packages` option.
thanks that helped

i now get this error:

> i2c-bus@1.2.5 install /opt/node_modules/i2c-bus
> node-gyp rebuild
make: Entering directory '/opt/node_modules/i2c-bus/build'
  CXX(target) Release/obj.target/i2c/src/i2c.o
In file included from ../src/i2c.cc:16:0:
../src/./i2c-dev.h:26:25: fatal error: linux/types.h: No such file or directory
 #include <linux/types.h>
                         ^
compilation terminated.
make: Leaving directory '/opt/node_modules/i2c-bus/build'
make: *** [i2c.target.mk:101: Release/obj.target/i2c/src/i2c.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.98-v7
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/i2c-bus
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i2c-bus@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the i2c-bus@1.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-03T19_56_15_223Z-debug.log
FATAL: Failed installing npm package node-red-contrib-i2c

**Comment by frenck** [comment]
`../src/./i2c-dev.h:26:25: fatal error: linux/types.h: No such file or directory`

You are missing the `linux-headers` package, please add it to the `system_packages` add-on config option.

See:
<https://pkgs.alpinelinux.org/contents?file=types.h&path=&name=*headers*&branch=v3.8>
