### ISSUE TITLE
Node-RED failed to keep running on HomeAssistant

### ISSUE THREAD

**Issue by ArnoS57** [hassio-addons/addon-node-red#1487]
# Problem/Motivation

> Installed Node-RED in my HA, checkboxes on for start at systemstart and view in sidebar.
  I have setup a secret credential at config.

## Expected behavior

> Run Node-RED and see the flowchart to make a flow

## Actual behavior

>Node-RED will startup but crashes directly

## Steps to reproduce

> Good question

## Proposed changes

> -

**Comment by elearningdienst** [comment]
Same here.

**Comment by vagabondan** [comment]
+1
