### ISSUE TITLE
Node Red Addon Crashing on Start

### ISSUE THREAD

**Issue by seanemclean** [hassio-addons/addon-node-red#1488]
# Problem/Motivation

> Starting yesterday, Node Red crashed and will not relaunch. No changes to system, running HA 11.1 on rPi4/SSD. After issue started, upgraded Node Red to latest version, no change. Updated to 11.2, no change

## Expected behavior

>Node Red Starts, and stays running

## Actual behavior

> Crashes on start

## Steps to reproduce

> Start it

## Proposed changes

> None, error log included

cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
v3.16.3-1-g9bb1c89d8e [https://dl-cdn.alpinelinux.org/alpine/v3.16/main]
v3.16.2-452-g9dd6a31b52 [https://dl-cdn.alpinelinux.org/alpine/v3.16/community]
OK: 16896 distinct packages available
(1/1) Installing make (4.3-r0)
Executing busybox-1.35.0-r17.trigger
OK: 110 MiB in 44 packages
(1/7) Installing libbz2 (1.0.8-r1)
(2/7) Installing libffi (3.4.2-r1)
(3/7) Installing gdbm (1.23-r0)
(4/7) Installing xz-libs (5.2.5-r1)
(5/7) Installing mpdecimal (2.5.1-r1)
(6/7) Installing sqlite-libs (3.38.5-r0)
(7/7) Installing python3 (3.10.8-r0)
Executing busybox-1.35.0-r17.trigger
OK: 159 MiB in 51 packages
  musl-1.2.3-r1:
ERROR: unable to select packages:
    breaks: musl-dev-1.2.3-r2[musl=1.2.3-r2]
    satisfies: world[musl=1.2.3-r1]
               apk-tools-2.12.9-r3[musl>=1.2]
               apk-tools-2.12.9-r3[so:libc.musl-aarch64.so.1]
               nginx-1.22.1-r0[so:libc.musl-aarch64.so.1]
               gcc-11.2.1_git20220219-r2[so:libc.musl-aarch64.so.1]
               g++-11.2.1_git20220219-r2[so:libc.musl-aarch64.so.1]
               libffi-3.4.2-r1[so:libc.musl-aarch64.so.1]
               tzdata-2022f-r1[so:libc.musl-aarch64.so.1]
               patch-2.7.6-r7[so:libc.musl-aarch64.so.1]
               bash-5.1.16-r2[so:libc.musl-aarch64.so.1]
               ca-certificates-20220614-r0[so:libc.musl-aarch64.so.1]
               python3-3.10.8-r0[so:libc.musl-aarch64.so.1]
               binutils-2.38-r3[so:libc.musl-aarch64.so.1]
               busybox-1.35.0-r17[so:libc.musl-aarch64.so.1]
               openssh-client-common-9.0_p1-r2[so:libc.musl-aarch64.so.1]
               sqlite-libs-3.38.5-r0[so:libc.musl-aarch64.so.1]
               curl-7.83.1-r4[so:libc.musl-aarch64.so.1]
               ncurses-libs-6.3_p20220521-r0[so:libc.musl-aarch64.so.1]
               expat-2.5.0-r0[so:libc.musl-aarch64.so.1]
               git-2.36.3-r0[so:libc.musl-aarch64.so.1]
               musl-utils-1.2.3-r1[so:libc.musl-aarch64.so.1]
               nghttp2-libs-1.47.0-r0[so:libc.musl-aarch64.so.1]
               nodejs-16.17.1-r0[so:libc.musl-aarch64.so.1]
               libstdc++-11.2.1_git20220219-r2[so:libc.musl-aarch64.so.1]
               mpdecimal-2.5.1-r1[so:libc.musl-aarch64.so.1]
               libbz2-1.0.8-r1[so:libc.musl-aarch64.so.1]
               brotli-libs-1.0.9-r6[so:libc.musl-aarch64.so.1]
               libcurl-7.83.1-r4[so:libc.musl-aarch64.so.1]
               mpc1-1.2.1-r0[so:libc.musl-aarch64.so.1]
               gdbm-1.23-r0[so:libc.musl-aarch64.so.1]
               icu-libs-71.1-r2[so:libc.musl-aarch64.so.1]
               pcre-8.45-r2[so:libc.musl-aarch64.so.1]
               oniguruma-6.9.8-r0[so:libc.musl-aarch64.so.1]
               mpfr4-4.1.0-r0[so:libc.musl-aarch64.so.1]
               zlib-1.2.12-r3[so:libc.musl-aarch64.so.1]
               libgomp-11.2.1_git20220219-r2[so:libc.musl-aarch64.so.1]
               readline-8.1.2-r0[so:libc.musl-aarch64.so.1]
               make-4.3-r0[so:libc.musl-aarch64.so.1]
               libedit-20210910.3.1-r0[so:libc.musl-aarch64.so.1]
               libgcc-11.2.1_git20220219-r2[so:libc.musl-aarch64.so.1]
               libssl1.1-1.1.1s-r0[so:libc.musl-aarch64.so.1]
               alpine-baselayout-3.2.0-r22[so:libc.musl-aarch64.so.1]
               libcrypto1.1-1.1.1s-r0[so:libc.musl-aarch64.so.1]
               libatomic-11.2.1_git20220219-r2[so:libc.musl-aarch64.so.1]
               openssh-client-default-9.0_p1-r2[so:libc.musl-aarch64.so.1]
               xz-libs-5.2.5-r1[so:libc.musl-aarch64.so.1]
               openssh-keygen-9.0_p1-r2[so:libc.musl-aarch64.so.1]
               pcre2-10.40-r0[so:libc.musl-aarch64.so.1]
               c-ares-1.18.1-r0[so:libc.musl-aarch64.so.1]
               scanelf-1.3.4-r0[so:libc.musl-aarch64.so.1]
               gmp-6.2.1-r2[so:libc.musl-aarch64.so.1]
               jq-1.6-r1[so:libc.musl-aarch64.so.1]
               isl22-0.22-r0[so:libc.musl-aarch64.so.1]
               ssl_client-1.35.0-r17[so:libc.musl-aarch64.so.1]
[08:19:27] FATAL: Failed installing system package g++
cont-init: info: /etc/cont-init.d/customizations.sh exited 1
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
up to date, audited 13 packages in 1s
1 package is looking for funding
  run `npm fund` for details
found 0 vulnerabilities
cont-init: info: /etc/cont-init.d/node-red.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by armanplex** [comment]
Same problem

**Comment by flinthamm** [comment]
Similar problem, running latest 13.5.2 and will no longer start. Using a number of system packages and started to try and isolate issue by adding 1 at a time but none of the system packages will install, see example log from 1 run:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 13.5.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to WARNING
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
v3.16.3-3-g26b0cc4686 [https://dl-cdn.alpinelinux.org/alpine/v3.16/main]
v3.16.2-452-g9dd6a31b52 [https://dl-cdn.alpinelinux.org/alpine/v3.16/community]
OK: 17039 distinct packages available
ERROR: unable to select packages:
  node-red-contrib-rfxcom (no such package):
    required by: world[node-red-contrib-rfxcom]
[09:18:43] FATAL: Failed installing system package node-red-contrib-rfxcom
cont-init: info: /etc/cont-init.d/customizations.sh exited 1
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
up to date, audited 2 packages in 557ms
found 0 vulnerabilities
cont-init: info: /etc/cont-init.d/node-red.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by frenck** [comment]
As per add-on log, the muscle dev version doesn't match. Make sure they match when installing custom packages.

**Comment by seanemclean** [comment]
Not sure why this issue was closed  apologies, but could you be more specific? Add on broke all by itself; with no system changes or updates - and others have confirmed the same.

**Comment by frenck** [comment]
>  Add on broke all by itself; with no system changes or updates - and others have confirmed the same.

Alpine Linux updated their musl packages. The installed `musl` packages in the add-on doesn't match the `musl-dev` package you are installing. You need to ensure you install the matching `musl` package too.

**Comment by donburch888** [comment]
Hi Sean, maybe I understand enough to translate Frenck's reply...

> Alpine Linux updated their musl packages. The installed `musl` packages in the add-on doesn't match the `musl-dev` package you are installing. You need to ensure you install the matching `musl` package too.

- From the **log you provided** it looks like you are running Home Assistant / nodeRED on a machine running Alpine linux. 
- Frenck advised that Alpine linux have updated the version of 'musl' they use, so I guess that your Alpine linux did an update (manually or automatically) 
- now the 'musl' package which node-RED expects does not match the version currently installed by Alpine linux (musl-1.2.3 release 1 vs release 2).  

> musl-1.2.3-r1:
> ERROR: unable to select packages:
> breaks: musl-dev-1.2.3-r2[musl=1.2.3-r2]

- you need to ensure you install the matching version of musl package too.

I don't know whether your problem started because you were trying to compile your own customization as Frenck assumed; or if that log was from was your attempt the troubleshoot to resolve the problem. 

From your statement "No changes to system" I will assume that you were not trying to compile your own customization - in which case you should either (a) use Alpine's package manager (apk) to install the version of musl that works with node-RED, or (b) revert to the previous version of Alpine until node-RED is updated.  Given that the Alpine linux home page states that musl is a core component I personally would be more likely to revert Alpine to the previous version.
