### ISSUE TITLE
installation error message

### ISSUE THREAD

**Issue by onteclab** [hassio-addons/addon-node-red#1492]
# Problem/Motivation

> i can't install the new version of node-red addon

## Expected behavior

> Install the node-red add-on

## Actual behavior

>  error on install: 
Unable to install add-on:
Can't install ghcr.io/hassio-addons/node-red/aarch64:13.5.3: 500 Server Error for http+docker://localhost/v1.41/images/ghcr.io/hassio-addons/node-red/aarch64:13.5.3/json: Internal Server Error ("readlink /var/lib/docker/overlay2/l: invalid argument")## Steps to reproduce

## Proposed changes

??

**Comment by frenck** [comment]
This is not an add-on issue (and cannot be fixed or resolved by the add-on).
You can try running `ha supervisor repair` from an terminal/SSH/command line.

If that doesn't help, please report your issue with the Home Assistant Supervisor project.

Thanks 👍 

../Frenck
