### ISSUE TITLE
Can't Remove Items from Palette

### ISSUE THREAD

**Issue by dfwwingnut** [hassio-addons/addon-node-red#1497]
# Problem/Motivation

> I need to uninstall some unused modules from the Palette.  I am needing to replace some modules with forked versions.

## Expected behavior

I believe I should be able to click "remote" from the palette manager.

> (What you expected to happen)

## Actual behavior

No option exists to remove from palette.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This only works for modules you manage yourself, not the built-in modules.

../Frenck
