### ISSUE TITLE
Connection closed to http://supervisor/core

### ISSUE THREAD

**Issue by MRobi1** [hassio-addons/addon-node-red#1498]
# Problem/Motivation
Since latest update, continuously running into connection issues. Unsure if this is related to HA 2022.11.X or Node Red 13.5.X although based on other issues with this release I am leaning towards the issue being on NR's side.

After initially updating Node Red, the add-on would not start. Same issue as [here](https://github.com/hassio-addons/addon-node-red/issues/1479 ) although in my case it was getting hung up on g++ so removing that from system_packages allowed it to boot.

Then I was not able to update or install any packages using the palette. Same error as seen [here](https://github.com/hassio-addons/addon-node-red/issues/1478). Renaming the node-red-node-email folder then allowed me to update nodes through the palette, one of which was node-red-contrib-home-assistant-websocket to 0.47.0

Now, once per day Node Red is going into an endless connection loop. It can connect/reconnect every few seconds for hours if left without ever getting stable again. To fix I simply have to restart the Node Red addon and it starts right back up and stays connected until some random point the next day. 
```
18 Nov 17:27:58 - [error] [api-call-service:Set Temp 19] Call-Service attempted without connection to server.
18 Nov 17:28:02 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:02 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:05 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:10 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:10 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:13 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:18 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:18 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:20 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:25 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:26 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:26 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
```

I came across a similar issue [here](https://github.com/hassio-addons/addon-node-red/issues/1467) where the issue was being caused by the known_devices.yaml file getting swamped with bluetooth devices and thousands of lines. I checked mine which only had a total of 31 devices and around 200 lines, but I tried the proposed solution of deleting the file and rebooting HA. My known devices file was rebuilt by the system and now has only 12 devices and 84 lines. But my connection loop issue keeps reoccuring.

## Expected behavior

Connection to stay established

## Actual behavior

Connection loop about once per day

## Steps to reproduce

Unknown, happens at complete random and persists until a restart of the Node Red addon.

**Comment by harshawije** [comment]
I have the same issue.

**Comment by sporqist** [comment]
Same/similar issue here. 

This is my supervisor log:
```log
22-12-31 02:49:18 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT
22-12-31 02:49:18 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-12-31 02:49:18 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-12-31 02:49:18 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-12-31 02:49:18 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

and this is node-red's log:
```log
31 Dec 02:49:18 - [info] Stopping flows
31 Dec 02:49:18 - [info] [server:Home Assistant] Closing connection to http://supervisor/core
31 Dec 02:49:18 - [info] Stopped flows
31 Dec 02:49:18 - [info] Updated flows
31 Dec 02:49:18 - [info] Starting flows
31 Dec 02:49:18 - [info] Started flows
31 Dec 02:49:18 - [info] [server:Home Assistant] Connecting to http://supervisor/core
31 Dec 02:49:18 - [info] [server:Home Assistant] Connected to http://supervisor/core
```

This repeats every few minutes.

**Comment by frenck** [comment]
Closing as a duplicate of #1498

**Comment by natedzl** [comment]
Coming to this issue from #1543

Installed Node Red 14.0.2 this morning and things were good for several hours (8+), but this evening I'm back to errors about not being connected:

31 Jan 18:53:26 - [error] [api-call-service:*** Home] Call-Service attempted without connection to server.
31 Jan 18:53:26 - [error] [api-call-service:*** Away] Call-Service attempted without connection to server.
31 Jan 18:53:26 - [error] [api-call-service:*** Away] Call-Service attempted without connection to server.
31 Jan 18:53:26 - [error] [api-call-service:*** Away] Call-Service attempted without connection to server.

**Comment by MRobi1** [comment]
I bit the bullet and moved everything to HA Automations. I couldn't handle my wife complaining anymore when something randomly didn't work as expected. It was a total pain to move years of flows over but I did it. As I was doing it I was disabling flows. I got to the point where every flow in NR was disabled so there is nothing being executed at all right now. And even with no flows enabled, I'm STILL getting this connection error within 24hrs of the addon starting.

**Comment by natedzl** [comment]
@MRobi1 I'm in the process of doing the same now.  WAF has been at an all-time low with severe delays or things just not happening at all.  NR just made some of those far more complex logic flows much easier - such a shame to have to abandon NR but without any attention to the issue(s), I don't see any other options.  

The discord channels also have a number of others mentioning this same issue with no response.

**Comment by chandlben** [comment]
Yup, same here. When I go in to Node-Red and watch some of the nodes which are connected to HA, they toggle back and forth from green to red. This causes a lot of issues with things not happening when they should. I've reverted back to 14.0.1 of the addon to see, and I'll continue to revert to older versions hoping maybe one of them will be working.

I'm willing to provide whatever is needed for debugging. Let's just please get some help on this...

**Comment by roybosch** [comment]
I did the same in the past weeks. It took a lot of time to move only the basic stuff, and I'm still struggling to move the more complex stuff. 

I don't understand why there's still no reaction or whatsoever about this bug. NR is one of the core features of HA for many people. I also don't understand how such a severe bug can get through the tests.

**Comment by rlust** [comment]
Still having issues with NR disconnects. I am running the latest release of NR, web socket and HA NR add-on.

**Comment by chandlben** [comment]
I have gone back to addon 13.5.3 in my backups and it is still having this issue...

**Comment by roybosch** [comment]
> I have gone back to addon 13.5.3 in my backups and it is still having this issue...

I think that's because this is related to one of the latest supervisor versions, not NR. Going back to an older supervisor version isn't very easy.

**Comment by martinsheldon** [comment]
I agree with @roybosch, I think it could be related to the Supervisor as the issue seems to appear on previously stable versions of Core and NR.
I haven't found a way to downgrade the Supervisor either and I'm wondering why its automatically updated when everything else has to be manually updated?

**Comment by roybosch** [comment]
In my case supervisor is presented just like any other HA core and addon update. I can install any update manually.

**Comment by chandlben** [comment]
Does this work better when not using the websocket, so using just an Access token? I switched mine over in the interim to see and until we hear something...if we hear something...

**Comment by natedzl** [comment]
Not sure if this is related but have also noticed Node-Red addon restarting randomly.  I have a series of disconnects/reconnects then it looks like I run out of memory:

10 Feb 02:01:49 - [info] [server:Home Assistant] Connecting to http://supervisor/core
10 Feb 02:01:49 - [info] [server:Home Assistant] Connected to http://supervisor/core
10 Feb 02:01:51 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
10 Feb 02:01:51 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
10 Feb 02:01:58 - [info] [server:Home Assistant] Connecting to http://supervisor/core
10 Feb 02:01:58 - [info] [server:Home Assistant] Connected to http://supervisor/core
<--- Last few GCs --->
[313:0xffffaea5e200] 157283466 ms: Scavenge 1868.3 (1925.3) -> 1862.9 (1925.3) MB, 7.5 / 0.0 ms  (average mu = 0.801, current mu = 0.826) task; 
[313:0xffffaea5e200] 157283515 ms: Scavenge 1870.5 (1926.0) -> 1864.1 (1926.0) MB, 8.0 / 0.0 ms  (average mu = 0.801, current mu = 0.826) allocation failure; 
[313:0xffffaea5e200] 157283564 ms: Scavenge 1871.0 (1926.0) -> 1864.9 (1942.0) MB, 13.3 / 0.0 ms  (average mu = 0.801, current mu = 0.826) allocation failure; 
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
[02:02:01] INFO: Service Node-RED exited with code 256 (by signal 6)
[02:02:02] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js
10 Feb 02:02:06 - [info] 
Welcome to Node-RED
===================
10 Feb 02:02:06 - [info] Node-RED version: v3.0.2
10 Feb 02:02:06 - [info] Node.js  version: v18.12.1
10 Feb 02:02:06 - [info] Linux 5.15.90 arm64 LE
10 Feb 02:02:07 - [info] Loading palette nodes
10 Feb 02:02:11 - [info] Dashboard version 3.3.1 started at /endpoint/ui
10 Feb 02:02:12 - [info] Settings file  : /etc/node-red/config.js
10 Feb 02:02:12 - [info] Context store  : 'default' [module=memory]
10 Feb 02:02:12 - [info] User directory : /config/node-red/
10 Feb 02:02:12 - [warn] Projects disabled : editorTheme.projects.enabled=false
10 Feb 02:02:12 - [info] Flows file     : /config/node-red/flows.json
10 Feb 02:02:12 - [info] Server now running at http://127.0.0.1:46836/
10 Feb 02:02:13 - [info] Starting flows
10 Feb 02:02:14 - [info] Started flows
10 Feb 02:02:18 - [info] [server:Home Assistant] Connecting to http://supervisor/core
10 Feb 02:02:18 - [info] [server:Home Assistant] Connected to http://supervisor/core

Running on Odroid N2+ with 4GB ram, after a clean system reboot and letting it run for an hour or so, I'm consuming 2.2 - 2.4 GB

I don't see anything in the HA logs around this time.

**Comment by chandlben** [comment]
> Does this work better when not using the websocket, so using just an Access token? I switched mine over in the interim to see and until we hear something...if we hear something...

So just to follow up, the answer is no. Using a token actually seemed to exacerbate the issue to a point where in NR any Event State node appeared to be vibrating from losing and gaining the connection back very quickly. It worked initially for a while but once it lost the connection, it was game over.

Knowing this, I'd be curious to try an external NR and token connect to HA from there to see if that does any better.

**Comment by brodkin** [comment]
This seems to be related to the Node-RED HA add-on actually...

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/796

**Comment by martinsheldon** [comment]
Now I'm starting to see the same issue running NR in Docker as well.. Was running without issues for over a month but the past few days it has been a lot of disconnects.
Its starting to get REALLY annoying that no developer has even commented on this issue

**Comment by rlust** [comment]
I only have a few devices in known_devices, but still having issues. Is anyone working on this?

**Comment by chandlben** [comment]
I don't even have a known_devices file (or not sure where to find it) and my NR is completely unusable, including a fresh installed nodered on another host. I have actually, over the last few days, taken to converting my automations to Home Assistant. Things aren't quite the same but at least I'm back to a functioning state whereas before my house was a mess.

It doesn't appear anyone has given the slightest inkling in to working on this.

**Comment by MRobi1** [comment]
I setup HA at my parents as well and they mentioned yesterday their automations hadn't ran in "a while". I hopped on the VPN and sure enough NR was experiencing the same websocket issue there. I don't think it's got to do with the known_devices since all that's in there are 2 ping devices. They also have maybe 20 total devices so this is certainly not a large install. I rebooted NR and it connected but within a few hours back to the websocket issue. Tried a few more times and then spent the rest of the afternoon converting their setup to straight automations in HA as well.

**Comment by MRobi1** [comment]
Those following this issue should also follow [this one](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/796)
The dev of the websocket node has actually responded.

**Comment by roybosch** [comment]
> This seems to be related to the Node-RED HA add-on actually...
> 
> [zachowj/node-red-contrib-home-assistant-websocket#796](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/796)
> 
> In my case the issue was the same as a commenter--that I had too many entries in my known_devices.yaml file and it overwhelmed the API to the point of being unusable.

Wow, this might have been the case with me too. Lately I noticed that some of the automations came back to life, after I deleted more than 30.000 lines of devices from my known_devices file. 

Alsof the "Statusses" tab in my developertools panel became responsive again after that.
