### ISSUE TITLE
API Login Broken

### ISSUE THREAD

**Issue by cmacnichol** [hassio-addons/addon-node-red#15]
# Problem/Motivation

Hassi.io 0.74.0 seems to have broke the API Login from Node-Red

## Expected behavior

Node-Red connecting to Hass.io

## Actual behavior

Node-Red cannot connect to Hass.io

7/23/2018, 11:30:55 PMnode: Home Assistant
msg : string[160]
"Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>"
7/23/2018, 11:30:57 PMnode: Home Assistant
msg : string[160]
"Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password not used>"
7/23/2018, 11:30:57 PMnode: Home Assistant
msg : string[160]

## Steps to reproduce

Upgraded to Hass.io 0.74.0 and Node-red stopped working immediately.  Enabled the new Auth system with legacy api support, did not make a difference.  Attempted to connect with and without the api password.

## Proposed changes

Unknown

**Comment by SergiSuarez** [comment]
I can confirm too.

Running on Ubuntu 18.04 on docker with duckdns
Hass.io supervisor 118
HA 0.74
add on version: 0.4
This started today
Is connected using  http://hassio/homeassistant
It shows long password
Adding syste log part as information
`18-07-24 03:24:35 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/switch/turn_on access from a0d7b954_nodered
18-07-24 03:25:51 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_off access from a0d7b954_nodered
18-07-24 03:25:52 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_on access from a0d7b954_nodered
18-07-24 03:26:17 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_off access from a0d7b954_nodered
18-07-24 03:27:17 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_on access from a0d7b954_nodered
18-07-24 03:27:41 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_off access from a0d7b954_nodered
18-07-24 03:29:06 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_on access from a0d7b954_nodered
18-07-24 03:29:32 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_off access from a0d7b954_nodered
18-07-24 03:31:16 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_on access from a0d7b954_nodered
18-07-24 03:31:42 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_off access from a0d7b954_nodered
18-07-24 03:32:11 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_off access from a0d7b954_nodered
18-07-24 03:35:04 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_on access from a0d7b954_nodered
18-07-24 03:35:37 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/turn_off access from a0d7b954_nodered
18-07-24 04:20:43 INFO (SyncWorker_29) [hassio.docker.interface] Stop hassioaddons/node-red-amd64 docker application
18-07-24 04:20:43 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream close
18-07-24 04:20:44 INFO (SyncWorker_29) [hassio.docker.interface] Clean hassioaddons/node-red-amd64 docker application
18-07-24 04:20:44 INFO (SyncWorker_19) [hassio.docker.addon] Start docker addon hassioaddons/node-red-amd64 with version v0.4.0
18-07-24 04:20:44 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:20:45 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:20:45 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:20:45 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:20:45 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_nodered
18-07-24 04:20:45 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:20:45 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_nodered
18-07-24 04:20:46 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:20:46 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:20:49 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/config access from a0d7b954_nodered
18-07-24 04:20:49 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/stream access from a0d7b954_nodered
18-07-24 04:20:49 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream start
18-07-24 04:20:49 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_nodered
18-07-24 04:20:49 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services access from a0d7b954_nodered
18-07-24 04:20:49 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/events access from a0d7b954_nodered
18-07-24 04:23:16 INFO (SyncWorker_38) [hassio.docker.interface] Stop hassioaddons/node-red-amd64 docker application
18-07-24 04:23:16 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream close
18-07-24 04:23:17 INFO (SyncWorker_38) [hassio.docker.interface] Clean hassioaddons/node-red-amd64 docker application
18-07-24 04:23:17 INFO (SyncWorker_5) [hassio.docker.addon] Start docker addon hassioaddons/node-red-amd64 with version v0.4.0
18-07-24 04:23:17 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:23:17 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:23:18 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:23:18 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:23:18 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_nodered
18-07-24 04:23:18 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:23:18 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_nodered
18-07-24 04:23:19 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:23:19 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 04:23:22 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/config access from a0d7b954_nodered
18-07-24 04:23:22 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/stream access from a0d7b954_nodered
18-07-24 04:23:22 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream start
18-07-24 04:23:22 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_nodered
18-07-24 04:23:22 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services access from a0d7b954_nodered
18-07-24 04:23:22 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/events access from a0d7b954_nodered
18-07-24 09:21:04 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
18-07-24 09:21:04 INFO (MainThread) [hassio.addons.git] Update addon https://github.com/hassio-addons/repository repository
18-07-24 09:21:04 INFO (MainThread) [hassio.addons.git] Update addon https://github.com/home-assistant/hassio-addons repository
18-07-24 09:21:06 INFO (MainThread) [hassio.addons] Load addons: 41 all - 0 new - 0 remove
18-07-24 15:21:04 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
18-07-24 15:21:04 INFO (MainThread) [hassio.addons.git] Update addon https://github.com/home-assistant/hassio-addons repository
18-07-24 15:21:04 INFO (MainThread) [hassio.addons.git] Update addon https://github.com/hassio-addons/repository repository
18-07-24 15:21:06 INFO (MainThread) [hassio.addons] Load addons: 41 all - 0 new - 0 remove
18-07-24 16:46:04 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/config access from a0d7b954_nodered
18-07-24 16:46:04 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/stream access from a0d7b954_nodered
18-07-24 16:46:04 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream start
18-07-24 16:46:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_nodered
18-07-24 16:46:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services access from a0d7b954_nodered
18-07-24 16:46:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/events access from a0d7b954_nodered
18-07-24 16:53:09 INFO (SyncWorker_26) [hassio.docker.interface] Stop hassioaddons/node-red-amd64 docker application
18-07-24 16:53:09 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream close
18-07-24 16:53:09 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream close
18-07-24 16:53:10 INFO (SyncWorker_26) [hassio.docker.interface] Clean hassioaddons/node-red-amd64 docker application
18-07-24 16:53:10 INFO (SyncWorker_18) [hassio.docker.addon] Start docker addon hassioaddons/node-red-amd64 with version v0.4.0
18-07-24 16:53:10 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 16:53:10 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 16:53:11 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 16:53:11 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 16:53:11 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_nodered
18-07-24 16:53:11 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 16:53:11 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_nodered
18-07-24 16:53:12 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 16:53:12 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered
18-07-24 16:53:15 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/config access from a0d7b954_nodered
18-07-24 16:53:15 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/stream access from a0d7b954_nodered
18-07-24 16:53:15 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream start
18-07-24 16:53:15 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_nodered
18-07-24 16:53:15 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services access from a0d7b954_nodered
18-07-24 16:53:15 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/events access from a0d7b954_nodered
18-07-24 16:54:11 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/light/toggle access from a0d7b954_nodered`
Node Red log
`24 Jul 16:53:15 - [info] Started flows
24 Jul 16:54:11 - [warn] [api-call-service:Toggle Balco] Error calling service, home assistant api error
24 Jul 16:54:11 - [error] [api-call-service:Toggle Balco] Error calling service, home assistant api error`

Thanks

**Comment by inputd** [comment]
Same issue.

Running two machines, 

Machine #1 
Hass.io, 32-bit. Supervisor 118 on a Pi B. No beta channel.
HA version is 0.74.0
Node-RED is 0.4.0
URL being used is http:/hassio/homeassistant.
On this machine, the password in node-red shows up as a long token.
The node-red GUI shows HA nodes as "connected", but its not working.

Machine #2 
Hass.io, 32-bit. Supervisor 119 on a Pi B+. No beta channel. This is also HassOS 1.7
HA version is 0.74.0
Node-RED is 0.4.0
URL being used is http:/hassio/homeassistant.
On this machine, the password in node-red shows up as my password in plain text.
The node-red GUI shows HA nodes as "disconnected", and is not working

Logs from Machine 1 
**(In "System")**
18-07-24 15:26:36 WARNING (MainThread) [hassio.api.proxy] Unknown HomeAssistant API access!
**(In "About")**
Login attempt or request with invalid authentication from 172.30.32.2
NO errors showing in the Node-RED logs. The login error shows up every hour or so.

Logs from Machine 2 
**(In "System")**
18-07-24 17:38:54 WARNING (MainThread) [hassio.api.proxy] Unknown HomeAssistant API access!
**(In "Node-RED")**
24 Jul 10:39:24 - [error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>
**(In "About")**
None at all.

**Comment by frenck** [comment]
Working on a fix (well fix... mitigation/fix of your configs).

**Comment by apateluk** [comment]
I am also seeing a similar issue with Hassio 0.74 and Node-RED 0.40.

```
Welcome to Node-RED
===================
24 Jul 20:16:44 - [info] Node-RED version: v0.18.7
24 Jul 20:16:44 - [info] Node.js  version: v8.11.3
24 Jul 20:16:44 - [info] Linux 4.14.41-v8 arm64 LE
24 Jul 20:16:49 - [info] Loading palette nodes
24 Jul 20:17:17 - [warn] ------------------------------------------------------
24 Jul 20:17:17 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
24 Jul 20:17:17 - [warn] ------------------------------------------------------
24 Jul 20:17:17 - [info] Settings file  : /etc/node-red/config.js
24 Jul 20:17:17 - [info] User directory : /config/node-red/
24 Jul 20:17:17 - [info] Server now running at http://127.0.0.1:1880/
24 Jul 20:17:18 - [info] Active project : Hassio-Node-Red
24 Jul 20:17:18 - [info] Flows file     : /config/node-red/projects/Hassio-Node-Red/flows.json
24 Jul 20:17:18 - [info] Starting flows
24 Jul 20:17:19 - [info] Started flows
24 Jul 20:17:21 - [error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>
```

**Comment by inputd** [comment]
Release v0.5.0 fixed the issue on both of my machines - thank you very much!

**Comment by frenck** [comment]
Update to add-on version 0.5.0.
Also, update to Supervisor 120 for the final part of this fix.

👍

**Comment by inputd** [comment]
I'm so sorry but updating to supervisor 120 has re-broken things. 

Now in the "Info" log I get:
Client error on /homeassistant/check request Cannot connect to host 172.30.32.2:80 ssl:None [Connection refused]

and I can no longer click the Hass.io tab in HA; it leads to an error pop-up that says:

"An embedded page on this page says Unable to load the panel source: /api/hassio/app/entrypoint.js"

**Comment by SergiSuarez** [comment]
Hi.

First check. it seems to be working again, thanks for your work and time.

El dt, 24 jul 2018 a les 22:46 inputd <notifications@github.com> va
escriure:

**Comment by cmacnichol** [comment]
Still getting the same error.  Updated Node-Red and the Supervisor.  The new auth system with legacy support is enabled.  Reinstalling the add-on does not help either.

msg : string[160]
"Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>"

Any ideas?

**Comment by apateluk** [comment]
I'm also seeing the same issue. Upgraded to Home-assistant v0.74.1 and v0.5 of this add-on:

```
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-npm-packages.sh: executing... 
[cont-init.d] 81-npm-packages.sh: exited 0.
[cont-init.d] 82-user-scripts.sh: executing... 
[cont-init.d] 82-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
> hassio-addon-node-red@1.0.0 start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
25 Jul 07:59:53 - [info] 
Welcome to Node-RED
===================
25 Jul 07:59:53 - [info] Node-RED version: v0.18.7
25 Jul 07:59:53 - [info] Node.js  version: v8.11.3
25 Jul 07:59:53 - [info] Linux 4.14.54-v8 arm64 LE
25 Jul 07:59:59 - [info] Loading palette nodes
25 Jul 08:00:27 - [warn] ------------------------------------------------------
25 Jul 08:00:27 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
25 Jul 08:00:27 - [warn] ------------------------------------------------------
25 Jul 08:00:27 - [info] Settings file  : /etc/node-red/config.js
25 Jul 08:00:27 - [info] User directory : /config/node-red/
25 Jul 08:00:28 - [info] Server now running at http://127.0.0.1:1880/
25 Jul 08:00:28 - [info] Active project : Hassio-Node-Red
25 Jul 08:00:28 - [info] Flows file     : /config/node-red/projects/Hassio-Node-Red/flows.json
25 Jul 08:00:28 - [info] Starting flows
25 Jul 08:00:29 - [info] Started flows
25 Jul 08:00:31 - [error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>
```

**Comment by SergiSuarez** [comment]
Agreed. Today fails again. I’m out of home so I can’t add logs.

El dc, 25 jul 2018 a les 9:08 apatel <notifications@github.com> va escriure:

**Comment by cmacnichol** [comment]
Update on Mine.  Appears that the Supervisor update to 121 corrected the issue.  Not sure why,
