### ISSUE TITLE
allow reorder of paletteCategories

### ISSUE THREAD

**Issue by chrisdrackett** [hassio-addons/addon-node-red#1504]
# Problem/Motivation

Currently I don't see a way to access `paletteCategories` from the node red config

## Expected behavior

I should be able to organize my custom categories higher up in the palette

## Proposed changes

Provide a setting that overrides the default value that HASS sets for `paletteCategories`

**Comment by frenck** [comment]
Just set it in your config. You can find it in the `/config/node-red` folder.

It works just like any other node-red installation.

../Frenck
