### ISSUE TITLE
NodeRed (often) randomly restart

### ISSUE THREAD

**Issue by teji24** [hassio-addons/addon-node-red#1519]
# Problem/Motivation

On a working HA (os) with marvelous NodeRed for all my automation, i meet sometime this problem.
normally, all is ok, no prob, it run normally from many weeks.
I restart properly VM, and then i got NodeRed restarts randomly every 1...3 jours.
if a make some clean VM restart, sometime, it come in stable state, and no more NodeRed restart.
It's not very visible, cause it work. but some automation sometimes stop. Than i add a telegram message at NodeRed Start. and discover all those intempestive restarts... Maybe lot of people with same problem, without see it ! 
i'm actually in this case. all was good. i shutdown the VM to backup hdd image, i restart, and BIM, NR random restart 10 times a day. i don't found any traces or logs to try to debug. 

## Expected behavior

I hope some advice to find a solution, or a way to have details, NR logs or other...

## Actual behavior

actually in the "instable state". This time not yet play to re-re-restart VM until stable state

## Steps to reproduce

restart VM. sometime restart un stable state, sometime in unstable state.

## Proposed changes

i hope to find something to propose !!!!

on attached screenshots, you can see before december 13 it work perfectly (some other "log message" via telegram)
13dec morning, i clean shutodown vm, restart it (NOTHING CHANGED). And then many autorestart from NR. (can see next days)
home assistant do not restart (also a message via SMS). all work fine (including NR between restarts)
I tried the "restart HA" button (not all VM) 2 times, it does not solve
I tried the "stop NodeRed" (wait 2 minutes) then "Start NordeRed", it does not solve.

I really love this plugin, it make HA so marvelous, insane, fantastic ! 
Thanks for your advices, help....

before restart

![Screenshot from 2022-12-17 09-19-28](https://user-images.githubusercontent.com/13621772/208233061-dc689f7e-cb37-4eec-9386-b1d1dcc41701.png)

after restart....
![Screenshot from 2022-12-17 09-19-50](https://user-images.githubusercontent.com/13621772/208233074-86c25f63-bf3d-4a50-98b5-8c9f048dbfb2.png)
![Screenshot from 2022-12-17 09-20-01](https://user-images.githubusercontent.com/13621772/208233077-48ff6419-8606-409c-b958-c4a0fa19c28e.png)

**Comment by Seba200086** [comment]
"Than i add a telegram message at NodeRed Start"

**How do you know that NodeRed does restart?** 

What is the flow trigger that tells you that NodeRed has been restarted? 
Maybe you have some false-positives...(?)
Do you see those restarts in NodeRed logs as well?

**Comment by teji24** [comment]
Just this, to inject a telegram message 5 seconds after startup :

[{"id":"e60b12c1.93bb3","type":"inject","z":"70ada22ad57be2c5","name":"NodeRed Start !","props":[{"p":"msg","v":"NodeRed Started!","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"5","topic":"","x":150,"y":2360,"wires":[["8aa2a880a9bceb4c"]]}]

![Screenshot from 2022-12-19 20-31-34](https://user-images.githubusercontent.com/13621772/208505235-95b2c25f-bd04-44ef-8b65-2b5b0c8d93d1.png)
![Screenshot from 2022-12-19 20-31-28](https://user-images.githubusercontent.com/13621772/208505239-25582a6f-f96e-459f-960a-5a0dabfe08d8.png)

it give messages you see in telegram screenshot posted before.

another fact telling me NodeRed restart : loop stop ! example : a loop decreasing second to stop a warmer. sometime i receive a "restart" telegram message, and if i verify, the loop is stopped. (now i added a trigger to restart the loop if needed when NodeRed restart). There is no doubt, it restart ! 

about log, are you talking about the "log" button in the node-red addon page ? i will look next restart...
but yesterday, i found another common issue (with HA this time) : bad ascii characters in "repositories.json" (making a json decoding python script crash), then i correct it, restart HA... And no more NodeRed restart... probably not linked to bad repositories.json, but (as explained), probably linked to the restart i make after repair repositories.json...

**Comment by teji24** [comment]
and MANY thanks first for your excellent job, i really love NodeRed in HomeAssistant, it change my live ! And then thank you to take time to read me and answer me ! THANKS.

**Comment by Seba200086** [comment]
As I wrote, I think that you have a false-positive information... (flow is triggered each time when NodeRed is deployed)

My way to get the HA restart information is to create an automation that sends an mqtt message and read it in NodeRed.

Create a new automation:
![obraz](https://user-images.githubusercontent.com/60579173/208626549-bf433142-689a-4b6e-87a0-3610813b6b89.png)

![obraz](https://user-images.githubusercontent.com/60579173/208626640-1fe9de7e-ebe5-45fa-979f-001cc1480fbc.png)

Select edit in YAML:
![obraz](https://user-images.githubusercontent.com/60579173/208626758-2a0fa1e3-c14f-43c7-889a-3b1341421b59.png)

and paste the following:
```
alias: Power state on HA start-up
trigger:
  - platform: homeassistant
    event: start
action:
  - service: mqtt.publish
    data:
      topic: start/ha
      payload: nodered
```

Then in NodeRed add flow:
![obraz](https://user-images.githubusercontent.com/60579173/208627460-f887a256-6f80-4c50-bc42-84488622064d.png)

`[{"id":"164971eb05629748","type":"switch","z":"e0c4e51d81217f07","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"nodered","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":290,"y":120,"wires":[["a27c41375bcf5842"]]},{"id":"42f9a8a6bc0cbd17","type":"mqtt in","z":"e0c4e51d81217f07","name":"","topic":"start/ha","qos":"2","datatype":"auto-detect","broker":"4c8122ca.b479ec","nl":false,"rap":true,"rh":0,"inputs":0,"x":150,"y":120,"wires":[["164971eb05629748"]]},{"id":"a27c41375bcf5842","type":"link out","z":"e0c4e51d81217f07","name":"link out 1","mode":"link","links":[],"x":415,"y":120,"wires":[]},{"id":"4c8122ca.b479ec","type":"mqtt-broker","name":"","broker":"localhost","port":"1883","clientid":"node-red","autoConnect":true,"usetls":false,"compatmode":false,"protocolVersion":"3","keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","birthMsg":{},"closeTopic":"","closeQos":"0","closePayload":"","closeMsg":{},"willTopic":"","willQos":"0","willPayload":"","willMsg":{},"userProps":"","sessionExpiry":""}]`

You need to configure the mqtt-broker in your own way.

Here you can find NodeRed logs:
![obraz](https://user-images.githubusercontent.com/60579173/208628493-0aa53327-e9bf-4f7d-b425-3de2c8f8db2f.png)

BTW, I am a regular user, not a developer. 
However, I also think that NodeRed is a great and indispensable tool :)

**Comment by danieletognetti01** [comment]
Same problem

**Comment by canedje** [comment]
same problem
