### ISSUE TITLE
Error installing node-red

### ISSUE THREAD

**Issue by Sojborg** [hassio-addons/addon-node-red#152]
# Problem/Motivation

> I can't install node-red on my hassio installation.

## Expected behavior

> Node-Red addon was installed

## Actual behavior

> Got an error: 19-03-05 22:00:03 ERROR (SyncWorker_8) [hassio.docker.interface] Can't install hassioaddons/node-red-armhf:1.3.4 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").

## Steps to reproduce

> Go to the hassio addon page and try to install the node-red addon

**Comment by frenck** [comment]
I'm sorry to say, this is an issue with Hassio/HassOS.
As an add-on creator, I can control what happens inside the add-on, outside the add-on is out of my control.

Please report the issue with Home Assistant/Hassio/HassOS.

👍
