### ISSUE TITLE
Error: EPERM: operation not permitted, open '/dev/i2c-1'

### ISSUE THREAD

**Issue by V4l3n10** [hassio-addons/addon-node-red#1538]
# Problem/Motivation

Node-Red addon unable to communicate with EZO devices hardwired to the RPI4 on i2c.  

## Expected behaviour

Pull address, send command, read status 

## Actual behaviour

 [error] [i2c out:CO2 EZO ] Error: EPERM: operation not permitted, open '/dev/i2c-1'

## Steps to reproduce

> Install node-red-contrib-i2c v0.9.0 with 3 nodes: i2c scan; i2c in & i2c out

**Comment by V4l3n10** [comment]
Hi @frenck, 

Any idea on a fix for this? 

Thanks

**Comment by frenck** [comment]
This add-on doesn't support that. If you need direct accept to things like i2c busses or GPIO, this add-on isn't suitable for you.

../Frenck

**Comment by V4l3n10** [comment]
Frenck, 

Thanks for your reply.
I managed previously to communicate with sensors and other devices via i2c buss in the Node red add-on on a rpi4 installation of a unsupported Supervised HA in Docker Installed by a friend a couple of years ago, but this got very slow and not working properly. 

I was hoping there is a way to grant permission within the HAOS as this looks stable. 

Any thoughts? 

Best
Vali

**Comment by frenck** [comment]
Support for these things has been explicitly removed from the add-on a while back.

If you want these features, the add-on won't be of help.

../Frenck
