### ISSUE TITLE
Node Red Add-On will not start aufter Installation (  502: Bad Gateway ) 

### ISSUE THREAD

**Issue by AndynordSee** [hassio-addons/addon-node-red#1539]
# Problem/Motivation

> (Why the issue was filed)

Node Red Add-On will not start aufter Installation (  502: Bad Gateway ) 

## Expected behavior

> (What you expected to happen)
Install , configuration , start

## Actual behavior
Install , configuration , didnt start

> (What actually happened)

Node-RED
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

 Add-on: Node-RED
 Flow-based programming for the Internet of Things

 Add-on version: 14.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.1.1
 Home Assistant Supervisor: 2022.12.1

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
[20:04:13] FATAL: 
[20:04:13] FATAL: SSL has been enabled using the 'ssl' option,
[20:04:13] FATAL: this requires a SSL certificate file which is
[20:04:13] FATAL: configured using the 'certfile' option in the
[20:04:13] FATAL: add-on configuration.
[20:04:13] FATAL: 
[20:04:13] FATAL: Unfortunately, the file specified in the
[20:04:13] FATAL: 'certfile' option does not exists.
[20:04:13] FATAL: 
[20:04:13] FATAL: Please ensure the certificate file exists and
[20:04:13] FATAL: is placed in the '/ssl/' directory.
[20:04:13] FATAL: 
[20:04:13] FATAL: In case you don't have SSL yet, consider getting
[20:04:13] FATAL: a SSL certificate or setting the 'ssl' option
[20:04:13] FATAL: to 'false' in case you are not planning on using
[20:04:13] FATAL: SSL with this add-on.
[20:04:13] FATAL: 
[20:04:13] FATAL: Check the add-on manual for more information.
[20:04:13] FATAL: 
s6-rc: warning: unable to start service init-nginx: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
[20:04:13] INFO: Starting Node-RED...
s6-rc: info: service nodered: stopping
[20:04:13] INFO: Service Node-RED exited with code 256 (by signal 15)
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
I start today with Node-RED on HA but i cant start it after the installation. 

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

If i deaktiat "SSL" it Startet

**Comment by tjorim** [comment]
Read the documentation for configuration documentation, the log clearly States your mistake.
