### ISSUE TITLE
Connection to Home Assistant (with addon or direct with token) does not have all entities and loses others

### ISSUE THREAD

**Issue by magiva** [hassio-addons/addon-node-red#1544]
# Problem/Motivation

Connection to Home Assistant (with addon or direct with token) does not have all entities and loses others
If i use any home assistant node to select an entity, not all are shown / found.
On occasion when an entity is found eg. input_number.stromkostnadrefresh.  i then notice on other days that the node is now showing another entity....because the originally found entity is no longer found.  
If i create a direct web link with token to home assistant (untick use home assistant addon) - i get the same result.

## Expected behavior

i expect to see all entities and they all be found each time

## Actual behavior

not all entities are found in the drop down selection list

## Steps to reproduce

drag a home assistant node onto the canvas, select entity from drop down, not all are shown

## Proposed changes

ive had to expose entities via mqtt via an addon so that i can subscribe to the topic

**Comment by magiva** [comment]
@frenck is anyone looking at these issues ?

**Comment by frenck** [comment]
That is always the question. I do not have an answer or solution.
