### ISSUE TITLE
Weird UI behaviour

### ISSUE THREAD

**Issue by bozman2021** [hassio-addons/addon-node-red#1546]
# Problem/Motivation
UI entity multi selection on entities places the selected entity horizontal rather than vertical position.
> (Why the issue was filed)

## Expected behavior
Vertical dropdown.
> (What you expected to happen)

## Actual behavior
Places the entity in horizontal position.
> (What actually happened)

## Steps to reproduce
Not known how to reproduce.
Tried in Safari,Firefox,Brave,Chrome same phenomenon.
<img width="1053" alt="Error_Vertical_Service_node" src="https://user-images.githubusercontent.com/5424288/213862049-c5d20d43-7c6d-44cb-aa1b-26cc4a65eb19.png">

> (How can someone else make/see it happen)
Similar post:
https://github.com/hassio-addons/addon-node-red/issues/1306

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by bozman2021** [comment]
Hi,
Forgot to mention, I have cleaned out all weird characters in friendly name for a lot of entities by simply use a customisation.yaml file that I call via configuration.yaml file.
So I cleaned out '/\()öäå" characters.

If I look trough the developer tools I can't find any entity with weird characters anymore.
It looks fine but in the call service node it won't place the entity's on correct way.

**Comment by bozman2021** [comment]
anyone?

**Comment by bozman2021** [comment]
Ok, 
I tried to change the css code directly in the browser:
.select2-container .select2-selection–multiple .select2-selection__rendered {
display: contents;
list-style: none;
padding: 0;
}

to:

.select2-container .select2-selection–multiple .select2-selection__rendered {
display: grid;
list-style: none;
padding: 0;
}

Then it worked better, but how can I change this permanently?

**Comment by bozman2021** [comment]
Same problem in version 14.0.3.

**Comment by bozman2021** [comment]
@frenck do you have good solution on how to solve this bug?

**Comment by bozman2021** [comment]
Updated to 14.1.0 and in HACS Node-Red Companion to 1.2.0 but the problem is still there, really annoying bug.

**Comment by bozman2021** [comment]
Updated to 14.1.3 and in HACS Node-Red Companion to 1.2.0 but the problem is still there, really annoying bug.

**Comment by frenck** [comment]
This you issue is not provided by the add-on, add-ons wrap existing applications.
We can't fix the application, as we don't develop it.

Your issue is therefore in the wrong place and, will here, not be ever solved.

Going to close it on this end.

../Frenck

**Comment by bozman2021** [comment]
Ok, tried to escalate this in the node-red forum before I created this ticket and they told me that this isn't in their scope when it is inside HA.
Node-red:
https://discourse.nodered.org/t/entities-area-dropdown-selection-not-working-properly/69799
Home-Assistant:
https://community.home-assistant.io/t/entities-device-area-dropdown-selection-not-working-properly/482361/26

So now it's a dead end and no one can help me at all.

Ok thanks for letting me know anyway.

Regards Boz
