### ISSUE TITLE
Make -flowFile editable in configuration => use YAML instead of JSON

### ISSUE THREAD

**Issue by Senbei123** [hassio-addons/addon-node-red#1548]
# Problem/Motivation

I would like to use the node-red-contrib-yaml-storage node to convert the flows.json to a flows.yaml file.
The reason is, that I can then use the watchman integration to check the integrety of my entities and services.

## Expected behavior

I would like to change the filename in the configuration instead of hardcode it in the files (which will be overwritten by the next update).

## Actual behavior

Hardcoded in the files.

## Steps to reproduce

-

## Proposed changes

See above.

Any comment welcome.

**Comment by frenck** [comment]
Feel free to submit a PR to enable such feature! 👍 

../Frenck
