### ISSUE TITLE
Update 'node-red-contrib-home-assistant-websocket ' palette 

### ISSUE THREAD

**Issue by Swiftnesses** [hassio-addons/addon-node-red#155]
Desperately need the new api node :)

**Comment by Swiftnesses** [comment]
You already did it... whoops.

**Comment by frenck** [comment]
hehe 👍 
We get automatically notified on upgrades 😉

**Comment by Swiftnesses** [comment]
Please push an update, I'm killing myself making manual API state update nodes using my token :(

**Comment by frenck** [comment]
@Swiftnesses Already pushed a couple of hours ago.
If your Hass.io didn't pick it up yet, go into the add-on store, and hit the refresh button in the top right corner. 😉

**Comment by Swiftnesses** [comment]
Thank you, amazing... :)
