### ISSUE TITLE
Addon Nodered can not start

### ISSUE THREAD

**Issue by froggyfly** [hassio-addons/addon-node-red#1556]
# Problem/Motivation

> (Why the issue was filed)

Addon Node-red can not start. It can be used two hours ago, and I did not do anything even not at home.

  _closeCallbacks: [],
  _inputCallback: null,
  _inputCallbacks: null,
  wires: [],
  _wireCount: 0,
  send: [Function: NOOP_SEND],
  credentials: { username: 'jimon@sina.com', password:  '******'},
  name: '',
  _users: [
    '67399ca4.ca7ed4', 'ca3c93af.94008',
    'cb3391e0.3287d',  'c5ae8d65.a24ce',
    'cde1215c.97e87',  '7f175a29.975814',
    '94fa9e4c.847e1',  '7c1f6c86.c7a494',
    '4483f0ef.ff47',   'ae8aefdc.c239b',
    'df4de865.a8ab08', '2821a797.d47718',
    '9822ebba.83a8f8', '780d12c2.7437bc',
    '70556202.77b96c'
  ],
  username: 'jimon@sina.com'
}
Node {
  id: '81f50451.655638',
  type: 'xiaoai-tts-configurator',
  z: undefined,
  g: undefined,
  _closeCallbacks: [],
  _inputCallback: null,
  _inputCallbacks: null,
  wires: [],
  _wireCount: 0,
  send: [Function: NOOP_SEND],
  credentials: { username: 'jimon@sina.com', password:  '******'},
  name: '',
  _users: [
    '67399ca4.ca7ed4', 'ca3c93af.94008',
    'cb3391e0.3287d',  'c5ae8d65.a24ce',
    'cde1215c.97e87',  '7f175a29.975814',
    '94fa9e4c.847e1',  '7c1f6c86.c7a494',
    '4483f0ef.ff47',   'ae8aefdc.c239b',
    'df4de865.a8ab08', '2821a797.d47718',
    '9822ebba.83a8f8', '780d12c2.7437bc',
    '70556202.77b96c'
  ],
  username: 'jimon@sina.com'
}
Node {
  id: '81f50451.655638',
  type: 'xiaoai-tts-configurator',
  z: undefined,
  g: undefined,
  _closeCallbacks: [],
  _inputCallback: null,
  _inputCallbacks: null,
  wires: [],
  _wireCount: 0,
  send: [Function: NOOP_SEND],
  credentials: { username: 'jimon@sina.com', password:  '******'},
  name: '',
  _users: [
    '67399ca4.ca7ed4', 'ca3c93af.94008',
    'cb3391e0.3287d',  'c5ae8d65.a24ce',
    'cde1215c.97e87',  '7f175a29.975814',
    '94fa9e4c.847e1',  '7c1f6c86.c7a494',
    '4483f0ef.ff47',   'ae8aefdc.c239b',
    'df4de865.a8ab08', '2821a797.d47718',
    '9822ebba.83a8f8', '780d12c2.7437bc',
    '70556202.77b96c'
  ],
  username: 'jimon@sina.com'
}
6 Feb 03:38:11 - [info] Started flows
6 Feb 03:38:11 - [info] [bizwechat-input:1a5854b4.6d9d2b] listening on port 3001
6 Feb 03:38:11 - [info] [mqtt-broker:8b35b3ca.cef73] Connected to broker: mqtt://192.168.50.41:1883
6 Feb 03:38:11 - [info] [mqtt-broker:ketingdengdai] Connected to broker: 369e156ca1234d93a410d9fdc8a743b8@mqtt://bemfa.com:9501
6 Feb 03:38:11 - [red] Uncaught Exception:
6 Feb 03:38:11 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[03:38:11] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[03:38:11] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by kohai-ut** [comment]
Ditto.  I just updated to 14.0.2 and HA to 2023.2.3 (from a Nov 2022 version).

**Comment by Villaberg** [comment]
Same issue for me.. HA tells me the app can not start, however.. i am able to access Node-Red via port 1880, but Node Red seem to be blocked from accessing internet..

**Comment by kohai-ut** [comment]
I found my problem.  I updated home assistant and node red and HA grabbed an IPv6 address from my dhcp server (I did not know this was enabled).  So, HA had both an ipv4 address and an ipv6 address BUT the IPv6 address was blocked at the firewall.  Nodered (or HA?) was not failing over to use ipv4.  Everything else with HA was working but not able to get into Nodered from the HA gui.

**Comment by thatso** [comment]
There is an ongoing npm network problem, check other reports like #1525.

**Comment by antonioste** [comment]
I've simply resolved by adding credential-secret in config
