### ISSUE TITLE
Node red Settings.js

### ISSUE THREAD

**Issue by Stianker1** [hassio-addons/addon-node-red#1557]
Hello,
New to home assistant, and i am scrathing my head on this one.
I am running HA supervised on virtuel machine, and have installed Node red as an addon.
I am trying to configure the node red settings.js file, but i dont know how i can reach it.
What command am i suppose to use in terminal to reach it?
Or can i do this whitin home assistant?

regards,
Stian

**Comment by sinclairpaul** [comment]
Please refer to the documentation <https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#configuration-folder>
