### ISSUE TITLE
After Update to 14.1.0 NR not start

### ISSUE THREAD

**Issue by xtronets** [hassio-addons/addon-node-red#1571]
# Problem/Motivation

> Node Red not starting websocket error

14 Mar 15:27:53 - [info] Node-RED version: v3.0.2
14 Mar 15:27:53 - [info] Node.js  version: v18.14.2
14 Mar 15:27:53 - [info] Linux 5.15.90 x64 LE
14 Mar 15:27:53 - [info] Loading palette nodes
14 Mar 15:27:55 - [info] Dashboard version 3.4.0 started at /endpoint/ui
14 Mar 15:27:55 - [info] Settings file  : /etc/node-red/config.js
14 Mar 15:27:55 - [info] Context store  : 'default' [module=memory]
14 Mar 15:27:55 - [info] User directory : /config/node-red/
14 Mar 15:27:55 - [warn] Projects disabled : editorTheme.projects.enabled=false
14 Mar 15:27:55 - [info] Flows file     : /config/node-red/flows.json
14 Mar 15:27:55 - [info] Server now running at http://127.0.0.1:46836/
14 Mar 15:27:55 - [info] Starting flows
14 Mar 15:27:55 - [info] Started flows
14 Mar 15:27:55 - [info] [server:Home Assistant] Connecting to http://supervisor/core
[15:27:55] INFO: Service Node-RED exited with code 256 (by signal 4)

23-03-14 15:28:28 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-03-14 15:28:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-03-14 15:28:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not WSMsgType.TEXT
23-03-14 15:28:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed

**Comment by phellarv** [comment]
There are others experiencing similar problems with 14.1.0. I rely heavily on Node Red for my house, and cannot upgrade if there is a know problems like this, so please look into this.

**Comment by frenck** [comment]
@xtronets This is not something in the add-on I'm afraid. Have you tried restarting the system when this happens?

**Comment by xtronets** [comment]
i do fresh install problem not solved and still exist

**Comment by Pawel128** [comment]
I have the same problem
Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5
20230309.1 - latest
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 14.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.3.5
 Home Assistant Supervisor: 2023.03.1

**Comment by UncleDrew12226** [comment]
same problem, can not connect to my server on homeassistant
Need to revert to 14.0.1 to make it work

**Comment by ndoggac** [comment]
Same problem, get 502 bad gateway.  Nothing in logs for either HA or NR.

**Comment by sarnassj** [comment]
I have the same problem. Any solution yet?

**Comment by himlotia** [comment]
Same issue since update 14.1.0 (same in 14.1.5) if reverted back to 14.0.3 no issue. All works. Got something change from 14.1.0 onwards

**Comment by himlotia** [comment]
I have uninstalled node-red & remove node-red directory as well but (using rm -r node-red) & reinstall node-red, restart HA completely , still same error.

**Comment by himlotia** [comment]
Even complete new instance of HA (new install  & no previous node red install) with node-red 14.1.* gives same error.

**Comment by SilverFire** [comment]
Same problem for me.
A downgrade to 14.0.3 did not fix the problem.
Version 14.0.1 works fine.

**Comment by SinnGit** [comment]
> I found that I had to set a `credential_secret` and turn off SSL in order to make NR run on my Yellow.

This resolved the issue for me, Settings>AddOns>Node-RED>Configuration.  From there set a credential_secret and disable SSL

**Comment by mkosmo** [comment]
I've uninstalled and reinstalled (and reconfigured) this add-on several times to try to pinpoint what causes it to fail to start... and one thing that without fail causes it is the inclusion of python3 as a system package.  Is anybody else installing python3 in the add-on?

**Comment by SinnGit** [comment]
I do not have the python add on installed and experienced a “502 bad gateway” error when browsing the Node-RED sidebar. Not sure if there are two separate issues being reported here but it was clear when reviewing the Node-RED logs that my issue was with the credential_secret and SSL configuration on a fresh install of HA on rpi4.

**Comment by mkosmo** [comment]
Unfortunately the python package no longer seems to be a reliable culprit.  I kept playing, did the same things, and it worked once (and has been working since).  The only other issue I ran in to was that with ipv6 enabled on my yellow, I couldn't download any new palettes - as seen in some other issues and forum posts.

**Comment by SilverFire** [comment]
The problem still reproduces.

**Comment by sarnassj** [comment]
In my case, the message "exited with code 256 (by signal 4)" occurred for Node-Red and Z-Wave add-ons. After diagnostics, it turned out to be a problem of the VM CPU. It  not handling ATX instructions (I know how crazy that sounds :D). I couldn't believe it, but setting the compatibility mode for the CPU in the settings of the virtual machine helped. Now everything works just fine :) in both addons.
