### ISSUE TITLE
Failed to start add-on

### ISSUE THREAD

**Issue by jasonmadigan** [hassio-addons/addon-node-red#1581]
# Problem/Motivation

Failed to start add-on after latest update with message:

```
Image ghcr.io/hassio-addons/node-red/aarch64:14.1.3 does not exist for addon_a0d7b954_nodered
```

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
It does exists, and has over 8K downloads already at the time of writing.

In case of doubt, try adding `https://` in front of the image to check:

<https://ghcr.io/hassio-addons/node-red/aarch64:14.1.3>

![image](https://user-images.githubusercontent.com/195327/228344910-05046311-0d14-4c96-8941-cd2f987f614e.png)

Your local Docker file system is most likely corrupted. Try running 

`ha supervisor repair` and see if it resolves.


../Frenck

**Comment by jasonmadigan** [comment]
Thank you @frenck - it wasn't clear from HA what was up (it genuinely looked like the image wasn't pullable). A supervisor repair has sorted it (also - apologies for the comment on the commit).
