### ISSUE TITLE
ContextStorage

### ISSUE THREAD

**Issue by nos86** [hassio-addons/addon-node-red#159]
# Problem/Motivation

> Is it possible to change the StorageContext to filesystem?

## Expected behavior

> (What you expected to happen)

## Proposed changes

> Add an option in the Config

**Comment by bonanitech** [comment]
You can do this currently without having to change the add-on 😉 

1. Follow the instructions available [here](https://nodered.org/docs/api/context/store/localfilesystem)
1. Place the settings according to your needs in `/config/node-red/settings.js`
1. Restart the add-on

**Comment by frenck** [comment]
Correct @bonanitech!

@nos86 You can still configure node-red to your likings 😉 

Closing this issue, since well, it is just available and there is nothing left to do for me.
(Unless, I'm mistaken, in that case, please let me know)
