### ISSUE TITLE
[Feature Request] Integrate a way to update npm packages provided on settings

### ISSUE THREAD

**Issue by distante** [hassio-addons/addon-node-red#1597]
# Problem

After defining an npm package into the `npm_packages` settings property, there is no way to update it.

## Expected behavior
If the given npm package has a new version that is not installed on the addon, an option to update it should exist.

## Actual behavior

No option exists

## Steps to reproduce
1. Define a node package in de addon settings.
![image](https://user-images.githubusercontent.com/5490201/232246965-e09c6481-9561-48e1-bf78-1e2eaceae00f.png)
2. Start Node-red
3. Update the node package.
4. There is no way to update the package even when [a new version exists](https://www.npmjs.com/package/@saninn/node-red-nodes).
<img width="461" alt="image" src="https://user-images.githubusercontent.com/5490201/232247155-2be520fe-38c3-4677-a421-1285bb60d9cd.png">

## Proposed changes

In the addon page, an "update to latest/downgrade to" option should exist

## Current workaround
Add an `init_command` for each installed npm package that runs every time the addon is rebooted... and reboot the addon when you want an update...
<img width="427" alt="image" src="https://user-images.githubusercontent.com/5490201/232247864-f44cff3b-6cfb-433c-895c-32b9b05d42a1.png">

**Comment by sinclairpaul** [comment]
Why can't you just tag latest in the npm_packages?

The command being run is at <https://github.com/hassio-addons/addon-node-red/blob/072e99868fdfaf4d26c0bc1d62fa60e3edcc1bdb/node-red/rootfs/etc/s6-overlay/s6-rc.d/init-customizations/run#L30>

**Comment by distante** [comment]
You are right @sinclairpaul adding it to the list of packages with `@latest` will install the latest version on each restart.

For me, it is ok, although, if the package was not made by me, I would probably did not want this to be an automatic behavior.

**Comment by sinclairpaul** [comment]
Then you would tag the version you want to install.  I'm going to close this out as it isn't really an addon issue, but is more related to how npm functions.

**Comment by distante** [comment]
It isn't really an issue but a feature request, so we know when a package update exist.
