### ISSUE TITLE
Node-RED increased CPU and memory utilization due to repeated connection/disconnections to HA (websocket)

### ISSUE THREAD

**Issue by Anto79-ops** [hassio-addons/addon-node-red#1598]
# Problem/Motivation

> 

Elevated CPU usage (by ~20%) on HAOS and sensors repeatedly showing green-connected, then red-disconnected on:

Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 10.0.rc3
Frontend 20230411.1 - latest
NodeRED addon -14.1.4

NR-Logs at the end are flooded with these messages:

```

17 Apr 09:06:02 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
17 Apr 09:06:02 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
17 Apr 09:06:07 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Apr 09:06:07 - [info] [server:Home Assistant] Connected to http://supervisor/core
17 Apr 09:06:07 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
17 Apr 09:06:07 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
```

## Expected behavior

> no increased CPU utilization, sensors staying connected.

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Anto79-ops** [comment]
0.49.1 node-red-contrib-home-assistant-websocket

**Comment by Anto79-ops** [comment]
I also wanted to share how wild the memory and CPU utilization is when NR is enabled vs disable (red lines)

![image](https://user-images.githubusercontent.com/79593761/232661595-7b9a9fe0-2e30-42c4-a81b-797cbbe6683d.png)

![image](https://user-images.githubusercontent.com/79593761/232661665-52dad2d2-6560-4e8c-9d36-1466f33e931e.png)

**Comment by Anto79-ops** [comment]
some pictographs
![image](https://user-images.githubusercontent.com/79593761/232837049-f15f4c69-b752-4cfd-bda8-37d873c5b581.png)

and CPU during that time

![image](https://user-images.githubusercontent.com/79593761/232837130-04014396-32d9-4e56-912e-d767ce8c3e29.png)

**Comment by pfefferle** [comment]
I experienced the same issue. I've up to 30% CPU usage of NodeRed!
