### ISSUE TITLE
Node Red unable to start after update 2023.4.5- "Out of memory"

### ISSUE THREAD

**Issue by blackshoals** [hassio-addons/addon-node-red#1599]
The addon won't start and exits trying to execute node-red.sh with an "out of memory" error. Full reboot tried, no issues with memory that I can see on a RPi 4 with an SSD. No previous problems. Reverting does not seem to fix the issue.

Node-RED
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 10.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.4.5
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patch: **** out of memory
[cont-init.d] node-red.sh: exited 2.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by tjorim** [comment]
You are running a version from last year, upgrade to the latest one. (Was fixed in https://github.com/hassio-addons/addon-node-red/releases/tag/v14.1.3)

**Comment by blackshoals** [comment]
Thank you. No add-on update was indicated. I assume I must have missed a release note about a version being deprecated and a reinstall required.
