### ISSUE TITLE
Python 3 Function Node crashes Node Red

### ISSUE THREAD

**Issue by Mobyn** [hassio-addons/addon-node-red#16]
I installed the python 3 function node. As soon as I launched it NodeRed Crashed. Problem is, I can relaunch node red with out that node continuing to prevent it from running.

I've tried uninstalling NodeRed and reinstalling it. But it seems to reinstall with the python node still intact. 

>29 Jul 17:56:50 - [info] Node-RED version: v0.18.7
>29 Jul 17:56:50 - [info] Node.js  version: v8.11.3
>29 Jul 17:56:50 - [info] Linux 4.14.54-v8 arm64 LE
>29 Jul 17:56:53 - [info] Loading palette nodes
>29 Jul 17:57:04 - [warn] ------------------------------------------------------
>29 Jul 17:57:04 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
>29 Jul 17:57:04 - [warn] ------------------------------------------------------
>29 Jul 17:57:04 - [info] Settings file  : /etc/node-red/config.js
>29 Jul 17:57:04 - [info] User directory : /config/node-red/
>29 Jul 17:57:04 - [warn] Projects disabled : editorTheme.projects.enabled=false
>29 Jul 17:57:04 - [info] Flows file     : /config/node-red/flows.json
>29 Jul 17:57:04 - [info] Server now running at http://127.0.0.1:1880/
>29 Jul 17:57:04 - [info] Starting flows
>29 Jul 17:57:05 - [info] [python3-function:9f2da506.47d9d8] Python function '' running on PID undefined
>29 Jul 17:57:05 - [info] Started flows
>29 Jul 17:57:05 - [red] Uncaught Exception:
>29 Jul 17:57:05 - Error: spawn python ENOENT
>    at _errnoException (util.js:992:11)
>    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
>    at onErrorNT (internal/child_process.js:372:16)
>    at _combinedTickCallback (internal/process/next_tick.js:138:11)
>    at process._tickCallback (internal/process/next_tick.js:180:9)
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! hassio-addon-node-red@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js >"--settings" "/etc/node-red/config.js"`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the hassio-addon-node-red@1.0.0 start script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
>npm ERR!     /root/.npm/_logs/2018-07-29T21_57_05_270Z-debug.log
> hassio-addon-node-red@1.0.0 start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

**Comment by frenck** [comment]
I'm not sure how to reproduce this.
Can you guide me?

**Comment by Mobyn** [comment]
For sure, 

Once Node red add-on is installed, install the node-red-contrib-python3-function from manage palette. Pull the python function node into any flow, write any code in the function, working or not as soon as you deploy you will get the error above. 

Thanks for all your amazing work!

**Comment by frenck** [comment]
Thanks @Mobyn,
Have you installed Python?

**Comment by Mobyn** [comment]
I’m’ on Hass.io. I assumed it was installed by default

Sent from Mail for Windows 10

**Comment by frenck** [comment]
Add-ons are Docker containers under the hood and are therefore isolated from e.g., the Home Assistant Docker container.

The add-on provides a way to install additional OS packages, see docs:

https://github.com/hassio-addons/addon-node-red#option-system_packages

**Comment by Mobyn** [comment]
Beauty! So I guess this one will do it. 
https://pkgs.alpinelinux.org/package/edge/main/x86/python3


Sent from Mail for Windows 10

**Comment by Mobyn** [comment]
Do you recommend adding package via npm_package option or using palette manager? 


Sent from Mail for Windows 10

**Comment by frenck** [comment]
👍 

I'll close up this ticket for now. If you run into troubles, feel free to re-open the ticket, create a new one, or simply join us on Discord: https://discord.me/hassioaddons
