### ISSUE TITLE
Node like switch to homeassistant 

### ISSUE THREAD

**Issue by ozmatox** [hassio-addons/addon-node-red#1603]
Hi, Is it possible to add node connection to home assistant as a switch in this version? I don't see check box to connect.
![Screenshot_20230507-192813_Home Assistant](https://user-images.githubusercontent.com/18137379/236693069-9dfeadfc-e209-4f35-ae76-7dcbade15fe9.png)

**Comment by frenck** [comment]
Hi there @ozmatox 👋 

This is the add-on repository. Add-on package-up software to be pluggable/installable within Home Assistant. The software found in add-ons is not developed in the add-on itself.

Therefore, I can't add features as you suggested. Please feel free to submit feature requests like that to the upstream projects. Once they add and release it, the add-on will update to include these changes.

Thanks for understanding.

../Frenck
