### ISSUE TITLE
Feature Request: Add Assist meta information to getentities node

### ISSUE THREAD

**Issue by peteh** [hassio-addons/addon-node-red#1608]
# Problem/Motivation

I'd like to filter by entities that are assist enabled but skip those that are not assist enabled. 

## Expected behavior

Add a filter to skip entities that are not assist enabled. However in the payload of the entities there is nothing to filter about

## Actual behavior

I can only get all entities and there are no meta information about assist settings

## Steps to reproduce
enable or disable assist for an entity and get it through the getentities node -> there are no meta information about assist enabled or not. 

## Proposed changes
Somehow add assist information that allows to check if its enabled or maybe even if it has aliases

**Comment by frenck** [comment]
Add-on wrap existing software and package it up so it can be installed in Home Assistant and automatically hook up with your system correctly.

Add-ons do not build the features inside the software package itself. Please consult the upstream project of the software providing that functionality on how you can submit your feature request to them.

Closing the issue on this end, as it is not an issue, but a feature request and above all in an incorrect place.

../Frenck
