### ISSUE TITLE
sensors created using "API node" HTTP POST "/api/states/" are not correctly updated in global variable "homeassistant.states" after HA restart

### ISSUE THREAD

**Issue by paulius2k** [hassio-addons/addon-node-red#1615]
# Problem/Motivation

After restart of HA core, sensors in NR global variable "homeassistant.states" are not correctly updated.

## Expected behavior

Sensors which were created in NR flow with an "API node" using path "/api/states/" should not remain in the "homeassistant.states" list after HA restart.

## Actual behavior
1. Sensors which were created in NR flow with an "API node" using path "/api/states/" remain in the "homeassistant.states" list after HA restart, holding their last state value available before HA restart.
2. These sensors are _correctly_ not listed in Developer tools --> States.
3. These sensors are _correctly_ removed from global variable "homeassistant.states" after NR restart.

## Steps to reproduce
1. Create a flow with at least two nodes: 
a) "Function" node which outputs payload:
```
msg.payload = {};
msg.payload.data = {};
msg.payload.path = "/api/states/counter.test_sensor";
msg.payload.data.entity_id = "counter.test_sensor";
msg.payload.data.state = 99;
```
b) "API node" which does an HTTP POST with the `data` of previous Function node.

2. `counter.test_sensor` should be created with value `99`.
3. Restart HA.
4. Go to NR "Context data", refresh Global variables, check `homeassistant.states`, your `counter.test_sensor` will be there, although it is not available in Developer Tools --> States anymore.

## Proposed changes
--

**Comment by tjorim** [comment]
This is not something this add-on handles. It simply wraps the Node-RED application.
If it's an issue with node-red-contrib-home-assistant-websocket node, you should report it here: https://github.com/zachowj/node-red-contrib-home-assistant-websocket
