### ISSUE TITLE
Add-on can't start specifically on the OVA (virtual disk image) version of HAOS

### ISSUE THREAD

**Issue by JZ-SmartThings** [hassio-addons/addon-node-red#1617]
# Problem/Motivation

> I run HAOS as a VM on my XPEnology. So I obtained the OVA file from here: https://www.home-assistant.io/installation/alternative/
Everything works very well other than Node Red. After extensive research I know the answer --- the problem is specifically with running HAOS from that OVA file. I proved this by installing brand new HAOS on a spare RPi3 --- installing and running Node Red add-on right after install of the OS worked like a charm from the very first try. So now I know the Node Red add-on work fine on the RPi3. I then set up another OVA based VM on my NAS, blank slate from scratch obviously. My very first step at installing was to try Node Red and I got me the same exact problem as my production HAOS. Basically the node package is failing with an illegal instruction and a core is dumped. Providing logs below and very certain of my findings and diagnosis :) would truly appreciate any advice.

## Expected behavior

> Node Red add-on to start successfully.

## Actual behavior

> **Log for Node Red add-on below:**
```
[13:13:08] INFO: Starting Node-RED...
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[13:13:08] INFO: Service Node-RED exited with code 256 (by signal 4)
[13:13:09] INFO: Starting Node-RED...
[13:13:10] INFO: Service Node-RED exited with code 256 (by signal 4) ---------------- **KEEPS GOING NEVER STOPS**
```

> **DMESG on the nodered container**
```
[314827.440547] traps: node[3893925] trap invalid opcode ip:5572cb3a71c1 sp:7ffc5487c1e0 error:0 in node[5572ca548000+1164000]
[314827.440585] audit: type=1701 audit(1685823242.061:1556324): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=docker-default pid=3893925 comm="node" exe="/usr/bin/node" sig=4 res=1
```

> **FAILED MANUAL COMMAND on the nodered container**
```
root@a0d7b954-nodered:/opt$ node
Illegal instruction (core dumped)
root@a0d7b954-nodered:/opt$ npm
Illegal instruction (core dumped)
```

## Steps to reproduce

> Install a brand new VM and use the HAOS OVA file as your imported base image. After that, simply try installing and successfully starting the Node Red add-on.

## Proposed changes

> Would love any manual steps to fix this. I tried using older versions of Node Red add-on w/o much success. Long-term fix for this nodejs issue with the OVA version of HAOS would be ideal.

**Comment by kess78** [comment]
Problem is not XPEnology related, it happens with the VMware vSphere also.
Everything new and clean installed from scratch...

**Comment by JZ-SmartThings** [comment]
Thanks to these two posts, I was able to fix the issue. The solution is to enable CPU compatibility in the BIOS of the VM. Providing my solution screenshot for Synology virtualization below.

https://github.com/hassio-addons/addon-node-red/issues/1571#issuecomment-1594458271
https://github.com/home-assistant/addons/issues/3035#issuecomment-1551307606

![image](https://github.com/hassio-addons/addon-node-red/assets/16831042/98e02379-0358-44c4-9846-4968199ed470)
