### ISSUE TITLE
Unable to install openssl on 14.2.2

### ISSUE THREAD

**Issue by initialChris** [hassio-addons/addon-node-red#1618]
# Problem/Motivation

Before upgrading Node-Red to the latest version (14.2.2) I had the openssl package for the correct use of "node-red-contrib-iiot-opcua". Now I can't start Node-Red anymore as it can't install openssl anymore.

## Expected behavior

Openssl is installed

## Actual behavior
When starting Node-Red the following error appears

> fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
> s6-rc: info: service init-nginx successfully started
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
> v3.18.0-552-g91b5b5dfc19 [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
> v3.18.0-550-g7c4a1d8aa7e [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
> OK: 20071 distinct packages available
> ERROR: unable to select packages:
>   libcrypto3-3.1.0-r4:
>     breaks: openssl-3.1.1-r1[libcrypto3=3.1.1-r1]
>     satisfies: world[libcrypto3=3.1.0-r4]
>                openssh-client-common-9.3_p1-r3[libcrypto3>=3.1.0]
>                openssh-client-common-9.3_p1-r3[so:libcrypto.so.3]
>                openssh-keygen-9.3_p1-r3[libcrypto3>=3.1.0]
>                openssh-keygen-9.3_p1-r3[so:libcrypto.so.3]
>                openssl-3.1.1-r1[so:libcrypto.so.3]
>                nginx-1.24.0-r6[so:libcrypto.so.3]
>                ca-certificates-20230506-r0[so:libcrypto.so.3]
>                apk-tools-2.14.0-r0[so:libcrypto.so.3]
>                nodejs-18.16.0-r1[so:libcrypto.so.3]
>                libcurl-8.0.1-r2[so:libcrypto.so.3]
>                libssl3-3.1.0-r4[so:libcrypto.so.3]
>                openssh-client-default-9.3_p1-r3[so:libcrypto.so.3]
>   libssl3-3.1.0-r4:
>     breaks: openssl-3.1.1-r1[libssl3=3.1.1-r1]
>     satisfies: world[libssl3=3.1.0-r4]
>                openssl-3.1.1-r1[so:libssl.so.3]
>                nginx-1.24.0-r6[so:libssl.so.3]
>                apk-tools-2.14.0-r0[so:libssl.so.3]
>                nodejs-18.16.0-r1[so:libssl.so.3]
>                libcurl-8.0.1-r2[so:libssl.so.3]
> [11:55:35] FATAL: Failed installing system package openssl

In case you try to boot without the openssl dependency, opcua can't work

> ########################################### OPENSSL ERROR ###########################################
> CWD = /opt
> Command failed: "openssl" rand  -out "/root/.config/node-opcua-default-nodejs/PKI/random.rnd" -hex 256
> /bin/sh: openssl: not found
> ########################################### OPENSSL ERROR ###########################################
> 

## Steps to reproduce

Add the following line to your configuration
```
system_packages:
  - openssl
```

## Proposed changes

The problem seems to be related to the fact that openssl looks for " libcrypto3-3.1.0-r4" but only "libcrypto3=3.1.1-r1" is present in the repository

**Comment by sinclairpaul** [comment]
As mentioned on Discord, update libcrypto3 and libssl3
