### ISSUE TITLE
Crash with environment variable called `length`

### ISSUE THREAD

**Issue by ThePython10110** [hassio-addons/addon-node-red#1620]
# Problem/Motivation

Running a subflow with an environment variable called `length` seems to crash Node Red completely. My guess is that it has something to do with JavaScript's `length` functions... but I know almost nothing about how Node Red actually works, so that could be entirely wrong.

## Expected behavior

The subflow runs.

## Actual behavior

Node Red crashes.

## Steps to reproduce

1. Create a subflow with an environment variable called `length`.
2. Run it.

**Comment by frenck** [comment]
That is entirely possible (and makes sense in a way). That said, this is the issue tracker of the add-on.

Add-on wrap existing software and package them up for use in Home Assistant. The software running inside of it, is not maintained here in the add-on repository.

Please report the issue with the upstream projects. Once it gets fixed or addressed, the add-on will update the versions.

Thanks 👍 

../Frenck
