### ISSUE TITLE
Node Red disconnects all the time in large environment due to Websocket calls to large.

### ISSUE THREAD

**Issue by johanschelin** [hassio-addons/addon-node-red#1627]
# Problem/Motivation

> Node Red cannot connect to HA anymore since update to 2023.6.x - guessing that it depends on ZWave entities now include a lot more entities (params for example) which is very good, byt makes the websocket call too big.

## Expected behavior

>Connecting to HA successfull

## Actual behavior

> Addon starts fine, but is unable to keep connection to HA

## Steps to reproduce

>Happens every start, that it cannot connect.

## Proposed changes

> Implement suggestion https://community.home-assistant.io/t/increase-websocket-message-size-limit-for-node-red/573463 or something similar.

Nod Red addon-log
18 Jun 11:03:26 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:26 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:31 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Jun 11:03:31 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Jun 11:03:31 - [debug] [server:Home Assistant] States Loaded
18 Jun 11:03:31 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:31 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:36 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Jun 11:03:36 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Jun 11:03:36 - [debug] [server:Home Assistant] States Loaded
18 Jun 11:03:36 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:36 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:41 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Jun 11:03:41 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Jun 11:03:41 - [debug] [server:Home Assistant] States Loaded
18 Jun 11:03:41 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:41 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:46 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Jun 11:03:46 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Jun 11:03:46 - [debug] [server:Home Assistant] States Loaded
18 Jun 11:03:46 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Jun 11:03:46 - [info] [server:Home Assistant] Connection closed to http://supervisor/core

Supervisor log containg the error:
23-06-18 11:04:06 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-06-18 11:04:06 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-06-18 11:04:06 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-06-18 11:04:07 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5266471 exceeds limit 4194304') is not str
23-06-18 11:04:07 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-06-18 11:04:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-06-18 11:04:12 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-06-18 11:04:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-06-18 11:04:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5266471 exceeds limit 4194304') is not str
23-06-18 11:04:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-06-18 11:04:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-06-18 11:04:17 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-06-18 11:04:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-06-18 11:04:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5266471 exceeds limit 4194304') is not str
23-06-18 11:04:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-06-18 11:04:22 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-06-18 11:04:22 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-06-18 11:04:22 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-06-18 11:04:22 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5266471 exceeds limit 4194304') is not str
23-06-18 11:04:22 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-06-18 11:04:27 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-06-18 11:04:27 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-06-18 11:04:27 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-06-18 11:04:27 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5266471 exceeds limit 4194304') is not str
23-06-18 11:04:27 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed

**Comment by m3ki** [comment]
I have the same issue on my end.

` Home Assistant 2023.6.2 
Supervisor 2023.06.2 
Operating System 10.2 
Frontend 20230608.0 - latest `

Last known working version was Homeassistant Core 2023.5.2

**Comment by ponvthc** [comment]
Same issue here.

**Comment by sinclairpaul** [comment]
The Palette you are having challenges with can be found at https://github.com/zachowj/node-red-contrib-home-assistant-websocket

There isn't anything that can be done from the addon perspective, it pre-installs the above Palette.  The issue likely lies with it or HA itself.  Closing from this end.

**Comment by ponvthc** [comment]
@sinclairpaul : this ticket describes a breaking change in homeassistant that has made node-red stop working for a reasonable subset of users. Is it not worth examining whether there's a mitigation for this issue?

**Comment by sinclairpaul** [comment]
> this ticket describes a breaking change in homeassistant

This isn't the Homeassistant repo, I would suggest you log the issue upstream

**Comment by ponvthc** [comment]
Fair enough. Thanks.

**Comment by johanschelin** [comment]
Just want to comment that i solved my issue following the suggestion to stop using the Addon (in the HA Config Node in NR)  and creating a manual long lived token instead following this discussion:

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/796

![image](https://github.com/hassio-addons/addon-node-red/assets/65488934/648b233b-a35d-465d-b9fa-2caeb1cf4248)

**Comment by habitoti** [comment]
This just works a bit longer than the HA addon for me, but after a few hours the issue comes up again.
