### ISSUE TITLE
Hassio 0.89.1 cannot upgrade to or install Node v. 1.4.0 

### ISSUE THREAD

**Issue by TheGreatBorg** [hassio-addons/addon-node-red#163]
After latest Hassio upgrade to 0.89.1 and having install Node-red 1.2.1 already I tried to push Update button but nothing happen or rigther Hassio stalled and I had to power of to get in contact with SSH and the browser page (lucky that I didn't do this operation remote - then my home assistance system would have been temporary bricked) RPI should be featured with a  power off function if restart fail (It happens quite a lot with the latest Hassio version - sadly).

I chose to uninstall Node-red from my Hassio and then I tried to install from app-store but nothing happens. What can I do to get this installed? Can I install modules from SSH ? Or should I drop Node-red automations and go for Automation scripts ?

**Comment by frenck** [comment]
Please provide the logs. (e.g. from the Hass.io system tab)

**Comment by TheGreatBorg** [comment]
I'm not at home at the moment so I don't dare to make any remote operations on my Hassio. I fear I will Brick my Hassio again. and my house will run totally out of control. I will send the log entries when I come home but I checked the log and I could not see anything remarkable

**Comment by frenck** [comment]
Thank you for your answer. I have no lead to what the problem may be. Without any hints or logs, it would be hard to find a reproduction or even fix the issue (if any).

**Comment by frenck** [comment]
Still no long provided. Closing issue.

Feel free to re-open when ready.
