### ISSUE TITLE
Node Red not working - error log "Failed installing system package pango-dev"

### ISSUE THREAD

**Issue by I-am-OK-86** [hassio-addons/addon-node-red#1630]
# Problem/Motivation

> (Why the issue was filed) Shows Bad Gateway 502 when starting Add On in Home Assistant

## Expected behavior

> (What you expected to happen) Should have been started

## Actual behavior

> (What actually happened) Does not start

## Steps to reproduce

> (How can someone else make/see it happen) Start the web interface

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Protocol says "Failed installing system package pango-dev"

**Comment by djelimon** [comment]
I have the same error
From the node-red logs:

Executing busybox-1.36.0-r9.trigger
Executing glib-2.76.3-r0.trigger
No schema files found: doing nothing.
OK: 458 MiB in 148 packages
(1/3) Installing libjpeg-turbo (2.1.5.1-r3)
(2/3) Installing libjpeg-turbo-dev (2.1.5.1-r3)
(3/3) Installing jpeg-dev (9e-r1)
OK: 459 MiB in 151 packages
ERROR: unable to select packages:
  icu-libs-73.1-r1:
    breaks: icu-dev-73.2-r0[icu-libs=73.2-r0]
    satisfies: icu-dev-73.2-r0[so:libicuuc.so.73]
               nodejs-18.16.0-r1[so:libicui18n.so.73]
               nodejs-18.16.0-r1[so:libicuuc.so.73]
               icu-73.2-r0[so:libicui18n.so.73]
               icu-73.2-r0[so:libicuio.so.73]
               icu-73.2-r0[so:libicuuc.so.73]
               harfbuzz-icu-7.3.0-r0[so:libicuuc.so.73]
[08:29:18] FATAL: Failed installing system package pango-dev

**Comment by djelimon** [comment]
looking at my config I had a bunch of system libraries installed to support this TensorFlow.js node, one of which was pango-dev. Since I'm not longer using the TensorFlow.js node (bigger fish to fry at the moment) I removed them from my config file and node red started again okay

**Comment by I-am-OK-86** [comment]
I did the same but and also was able to open OR again. But since I need pango for one configuration this is not a long term solution.

**Comment by enricozocca** [comment]
I've got same issue:
ERROR: unable to select packages:
  icu-libs-73.1-r1:
    breaks: icu-dev-73.2-r0[icu-libs=73.2-r0]
    satisfies: icu-dev-73.2-r0[so:libicuuc.so.73]
               nodejs-18.16.0-r1[so:libicui18n.so.73]
               nodejs-18.16.0-r1[so:libicuuc.so.73]
               icu-73.2-r0[so:libicui18n.so.73]
               icu-73.2-r0[so:libicuio.so.73]
               icu-73.2-r0[so:libicuuc.so.73]
               harfbuzz-icu-7.3.0-r0[so:libicuuc.so.73]
[12:41:16] FATAL: Failed installing system package pango-dev
