### ISSUE TITLE
No Node Status

### ISSUE THREAD

**Issue by goldbe4804** [hassio-addons/addon-node-red#1637]
haven't used node red in a bit- went to update something and saw that the nodes have nothing under them - i dont know how long its been like this- i did try to restore node red also reinstalled it with the same outcome -- the automations do seem to be working- dont know what to try next---- somtimes if i stop and restart NR it will be ok till i go to another page the come back
node red 3.0.2
ha 2003.7.1
thanks

![nr](https://github.com/hassio-addons/addon-node-red/assets/56876314/8b04df01-ef60-4379-bd53-bf909c660fdb)

**Comment by frenck** [comment]
This functionality is provided by the `node-red-contrib-home-assistant-websocket` project, not the add-on. Please consult their documentation on where to go for support.

Their repository: <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>

../Frenck
