### ISSUE TITLE
Node Red failing to start

### ISSUE THREAD

**Issue by stain3565** [hassio-addons/addon-node-red#1641]
# Problem/Motivation

NodeRed will not start

## Expected behavior

Start button should open NodeRed successfully

## Actual behaviour

Log shows unhandled exception

## Steps to reproduce

Not sure. Was failing to start when I had flows in. Decided to completely remove including the folder node-red. Re-installed but not starting.

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 14.3.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.7.2
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[22:37:19] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js
14 Jul 22:37:25 - [info] 
Welcome to Node-RED
===================
14 Jul 22:37:25 - [info] Node-RED version: v3.0.2
14 Jul 22:37:25 - [info] Node.js  version: v18.16.1
14 Jul 22:37:25 - [info] Linux 6.1.21-v8 arm64 LE
14 Jul 22:37:27 - [info] Loading palette nodes
14 Jul 22:37:35 - [info] Dashboard version 3.5.0 started at /endpoint/ui
14 Jul 22:37:38 - [info] Settings file  : /etc/node-red/config.js
14 Jul 22:37:38 - [info] Context store  : 'default' [module=memory]
14 Jul 22:37:38 - [info] User directory : /config/node-red/
14 Jul 22:37:38 - [warn] Projects disabled : editorTheme.projects.enabled=false
14 Jul 22:37:38 - [info] Flows file     : /config/node-red/flows.json
14 Jul 22:37:38 - [warn] Encrypted credentials not found
14 Jul 22:37:39 - [info] Server now running at http://127.0.0.1:46836/
14 Jul 22:37:39 - [info] Starting flows
14 Jul 22:37:39 - [info] Started flows
[22:37:39] INFO: Starting NGinx...
14 Jul 22:37:44 - [info] [server:Home Assistant] Connecting to http://supervisor/core
14 Jul 22:37:44 - [info] [server:Home Assistant] Connected to http://supervisor/core
14 Jul 22:39:02 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
14 Jul 22:39:02 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
14 Jul 22:39:02 - [red] Uncaught Exception:
14 Jul 22:39:02 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[22:39:03] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[22:39:03] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

## Proposed changes

No idea what to do. I realise others have raised similar issues before but I have not seen any real answer as to how to get this working. My Home Assistant versions are:
Home Assistant 2023.7.2

Node-RED
Current version: 14.3.0

**Comment by murraysst** [comment]
I seem to have the same problem, started a day or so ago (maybe coinciding with an automatic update to 14.4.0?). From my log;

```
fileServer listening on ip 192.168.0.200 and port 8098
21 Jul 09:24:59 - [info] [server:Home Assistant] Connected to http://supervisor/core
21 Jul 09:25:00 - [red] Uncaught Exception:
21 Jul 09:25:00 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[09:25:00] INFO: Service Node-RED exited with code 1 (by signal 0)
```

I can successfully start node red in safe mode and view my not running flows, but even if all flows are disabled it won't start outside of safe mode, always throwing the Uncaught Exception above.

**Comment by msmarks** [comment]
```
[16:16:59] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js
21 Jul 16:17:02 - [info] 
Welcome to Node-RED
===================
21 Jul 16:17:02 - [info] Node-RED version: v3.0.2
21 Jul 16:17:02 - [info] Node.js  version: v18.16.1
21 Jul 16:17:02 - [info] Linux 5.10.0-21-amd64 x64 LE
21 Jul 16:17:05 - [info] Loading palette nodes
21 Jul 16:17:09 - [info] Dashboard version 3.5.0 started at /endpoint/ui
21 Jul 16:17:10 - [info] Settings file  : /etc/node-red/config.js
21 Jul 16:17:10 - [info] Context store  : 'default' [module=memory]
21 Jul 16:17:10 - [info] User directory : /config/node-red/
21 Jul 16:17:10 - [warn] Projects disabled : editorTheme.projects.enabled=false
21 Jul 16:17:10 - [info] Flows file     : /config/node-red/flows.json
21 Jul 16:17:10 - [info] Server now running at http://127.0.0.1:46836/
21 Jul 16:17:10 - [info] Starting flows
21 Jul 16:17:10 - [info] Started flows
21 Jul 16:17:10 - [info] [tcp in:a09f518fa3e4b8ff] listening on port 12355
21 Jul 16:17:10 - [info] [server:Home Assistant Remote] Connecting to http://192.168.11.6:8123
[16:17:10] INFO: Starting NGinx...
21 Jul 16:17:11 - [info] [serialconfig:32c80261df3b0af2] serial port /dev/tty_usb3 opened at 9600 baud 8N1
21 Jul 16:17:11 - [info] [server:Home Assistant Remote] Connected to http://192.168.11.6:8123
21 Jul 16:17:11 - [red] Uncaught Exception:
21 Jul 16:17:11 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[16:17:11] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[16:17:11] INFO: Service NGINX exited with code 0 (by signal 0)
```

**Comment by chatoooo** [comment]
I have exactly the same issue. It started with version 14.4.0. I reverted to 14.3.0 and the issue disappeared. Before revert I disabled all flows without any effect on startup.

**Comment by murraysst** [comment]
I updated home assistant core from 2022.6 to 2023.7.3 and the node red starting issue is resolved. Unfortunately the core changes seem to have broken a lot of my setup. I have to now go through and debug just about everything it seems.

**Comment by toollu** [comment]
> I have exactly the same issue. It started with version 14.4.0. I reverted to 14.3.0 and the issue disappeared. Before revert I disabled all flows without any effect on startup.

Yeah I can confirm, 14.4.0 broke the addon so it does not even start. Restored 14.3.0  snapshot and things running again.

**Comment by pjrt** [comment]
It just started to happen to me. However, my error is different. 

```
Welcome to Node-RED
===================
9 Aug 10:54:24 - [info] Node-RED version: v3.0.2
9 Aug 10:54:24 - [info] Node.js  version: v18.17.0
9 Aug 10:54:24 - [info] Linux 6.1.39 x64 LE
9 Aug 10:54:24 - [info] Loading palette nodes
9 Aug 10:54:26 - [info] Dashboard version 3.5.0 started at /endpoint/ui
9 Aug 10:54:26 - [info] Settings file  : /etc/node-red/config.js
9 Aug 10:54:26 - [info] Context store  : 'default' [module=memory]
9 Aug 10:54:26 - [info] User directory : /config/node-red/
9 Aug 10:54:26 - [warn] Projects disabled : editorTheme.projects.enabled=false
9 Aug 10:54:26 - [info] Flows file     : /config/node-red/flows.json
9 Aug 10:54:26 - [info] Server now running at http://127.0.0.1:46836/
9 Aug 10:54:26 - [info] Starting flows
9 Aug 10:54:26 - [error] [server:4e9b651b.5810fc] Error: No credentials provided
9 Aug 10:54:26 - [info] [join-server:3cad5404.1c873c] Starting server on port 1025...
9 Aug 10:54:26 - [info] [join-server:3cad5404.1c873c] Sending Registration NodeRED
9 Aug 10:54:26 - [info] [join-server:3cad5404.1c873c] Saved device Name: NodeRED
9 Aug 10:54:26 - [info] Started flows
[10:54:27] INFO: Starting NGinx...
9 Aug 10:54:31 - [info] [server:Home Assistant] Connecting to http://supervisor/core
9 Aug 10:54:31 - [info] [server:Home Assistant] Connected to http://supervisor/core
9 Aug 10:54:36 - [red] Uncaught Exception:
9 Aug 10:54:36 - [error] TypeError: Cannot read properties of null (reading 'indexOf')
    at /config/node-red/node_modules/node-red-contrib-join-joaoapps/js/ipgetter.js:16:43
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at sendRegistration (/config/node-red/node_modules/node-red-contrib-join-joaoapps/join-server.js:80:13)
[10:54:36] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[10:54:36] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped```

**Comment by Frankynov** [comment]
> It just started to happen to me. However, my error is different.
> 
> ```
> Welcome to Node-RED
> ===================
> 9 Aug 10:54:24 - [info] Node-RED version: v3.0.2
> 9 Aug 10:54:24 - [info] Node.js  version: v18.17.0
> 9 Aug 10:54:24 - [info] Linux 6.1.39 x64 LE
> 9 Aug 10:54:24 - [info] Loading palette nodes
> 9 Aug 10:54:26 - [info] Dashboard version 3.5.0 started at /endpoint/ui
> 9 Aug 10:54:26 - [info] Settings file  : /etc/node-red/config.js
> 9 Aug 10:54:26 - [info] Context store  : 'default' [module=memory]
> 9 Aug 10:54:26 - [info] User directory : /config/node-red/
> 9 Aug 10:54:26 - [warn] Projects disabled : editorTheme.projects.enabled=false
> 9 Aug 10:54:26 - [info] Flows file     : /config/node-red/flows.json
> 9 Aug 10:54:26 - [info] Server now running at http://127.0.0.1:46836/
> 9 Aug 10:54:26 - [info] Starting flows
> 9 Aug 10:54:26 - [error] [server:4e9b651b.5810fc] Error: No credentials provided
> 9 Aug 10:54:26 - [info] [join-server:3cad5404.1c873c] Starting server on port 1025...
> 9 Aug 10:54:26 - [info] [join-server:3cad5404.1c873c] Sending Registration NodeRED
> 9 Aug 10:54:26 - [info] [join-server:3cad5404.1c873c] Saved device Name: NodeRED
> 9 Aug 10:54:26 - [info] Started flows
> [10:54:27] INFO: Starting NGinx...
> 9 Aug 10:54:31 - [info] [server:Home Assistant] Connecting to http://supervisor/core
> 9 Aug 10:54:31 - [info] [server:Home Assistant] Connected to http://supervisor/core
> 9 Aug 10:54:36 - [red] Uncaught Exception:
> 9 Aug 10:54:36 - [error] TypeError: Cannot read properties of null (reading 'indexOf')
>     at /config/node-red/node_modules/node-red-contrib-join-joaoapps/js/ipgetter.js:16:43
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at sendRegistration (/config/node-red/node_modules/node-red-contrib-join-joaoapps/join-server.js:80:13)
> [10:54:36] INFO: Service Node-RED exited with code 1 (by signal 0)
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service nginx: stopping
> [10:54:36] INFO: Service NGINX exited with code 0 (by signal 0)
> s6-rc: info: service nginx successfully stopped
> s6-rc: info: service init-nginx: stopping
> s6-rc: info: service nodered: stopping
> s6-rc: info: service nodered successfully stopped
> s6-rc: info: service init-nodered: stopping
> s6-rc: info: service init-nginx successfully stopped
> s6-rc: info: service init-nodered successfully stopped
> s6-rc: info: service init-customizations: stopping
> s6-rc: info: service init-customizations successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service base-addon-log-level: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service base-addon-log-level successfully stopped
> s6-rc: info: service base-addon-banner: stopping
> s6-rc: info: service base-addon-banner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped```
> ```

As suggested somewhere else in the issues section, have you tried a « ha supervisor repair » command from terminal ?
For me it has solved the issue and I’m running correctly the 14.4.5 version.

**Comment by Tirarex** [comment]
Same problem after fresh install...

**Comment by lukaspustina** [comment]
I ran into the same problem. Neither reboot or even uninstall + fresh install fixed the problem.

**Comment by blokl** [comment]
Same problem after uograde  last core
14 Sep 15:05:08 - [info] Node-RED version: v3.1.0
14 Sep 15:05:08 - [info] Node.js  version: v18.17.1
14 Sep 15:05:08 - [info] Linux 6.1.45 x64 LE
14 Sep 15:05:10 - [info] Loading palette nodes
14 Sep 15:05:15 - [info] Dashboard version 3.6.0 started at /endpoint/ui
Error connecting to dbus: Error: connect ENOENT /var/run/dbus/system_bus_socket
14 Sep 15:05:18 - [info] Settings file  : /etc/node-red/config.js
14 Sep 15:05:18 - [info] Context store  : 'default' [module=memory]
14 Sep 15:05:18 - [info] User directory : /config/node-red/
14 Sep 15:05:18 - [warn] Projects disabled : editorTheme.projects.enabled=false
14 Sep 15:05:18 - [info] Flows file     : /config/node-red/flows.json
14 Sep 15:05:18 - [info] Server now running at http://127.0.0.1:46836/
14 Sep 15:05:18 - [info] Starting flows
14 Sep 15:05:18 - [info] [hue-bridge:Philips hue bridge] Initializing the bridge (192.168.2.70)…
[15:05:18] INFO: Starting NGinx...
14 Sep 15:05:18 - [info] Started flows
14 Sep 15:05:18 - [info] [hue-bridge:Philips hue bridge] Connected to bridge
14 Sep 15:05:19 - [info] [hue-bridge:Philips hue bridge] Processing bridge resources…
14 Sep 15:05:19 - [info] [hue-bridge:Philips hue bridge] Initial emit of resource states…
14 Sep 15:05:20 - [info] [hue-bridge:Philips hue bridge] Keeping nodes up-to-date…
14 Sep 15:05:20 - [info] [hue-bridge:Philips hue bridge] Subscribing to bridge events…
14 Sep 15:05:20 - [error] [api-current-state:Youles ] TypeError: (0 , lodash_1.cloneDeep) is not a function
Error connecting to dbus: Error: connect ENOENT /var/run/dbus/system_bus_socket
14 Sep 15:05:23 - [info] [server:Home Assistant] Connecting to http://supervisor/core
14 Sep 15:05:23 - [info] [server:Home Assistant] Connected to http://supervisor/core
14 Sep 15:05:23 - [error] [poll-state:Solis < 150] (0 , lodash_1.cloneDeep) is not a function
14 Sep 15:05:23 - [error] [poll-state:Kamer temp.] (0 , lodash_1.cloneDeep) is not a function
14 Sep 15:05:25 - [error] [trigger-state:Vocht change > reference] TypeError: (0 , lodash_1.cloneDeep) is not a function
14 Sep 15:05:25 - [error] [api-call-service:5a9045d745239b2b] TypeError: (0 , lodash_1.cloneDeep) is not a function
Error connecting to dbus: Error: connect ENOENT /var/run/dbus/system_bus_socket
14 Sep 15:05:29 - [error] [trigger-state:Vocht change > reference] TypeError: (0 , lodash_1.cloneDeep) is not a function
14 Sep 15:05:30 - [red] Uncaught Exception:
14 Sep 15:05:30 - [error] TypeError: (0 , lodash_1.cloneDeep) is not a function
    at Websocket.getStates (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:385:42)
    at PollState.onTimer (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/poll-state/controller.js:60:46)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[15:05:30] INFO: Service Node-RED exited with code 1 (by signal 0)

**Comment by nagydavid** [comment]
same here 
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 14.5.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.2
 Home Assistant Supervisor: 2023.09.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started
npm WARN deprecated bcrypt@3.0.6: versions < v5.0.0 do not handle NUL in passwords properly
npm WARN deprecated bcrypt@3.0.8: versions < v5.0.0 do not handle NUL in passwords properly
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated node-pre-gyp@0.12.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
up to date, audited 1001 packages in 7s
14 packages are looking for funding
  run `npm fund` for details
67 vulnerabilities (1 low, 24 moderate, 39 high, 3 critical)
To address issues that do not require attention, run:
  npm audit fix
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[17:01:48] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js
Error loading settings file: /etc/node-red/config.js
[17:01:49] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[17:01:49] INFO: Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
´´´
