### ISSUE TITLE
Webhook nodes failed to register

### ISSUE THREAD

**Issue by wiiNinja** [hassio-addons/addon-node-red#1651]
# Problem/Motivation

Previously working Webhook nodes stop working after updating Addon to 14.4.2

## Expected behavior

Webhook nodes should register and work the same way as before

## Actual behavior

All my webhook nodes display these messages: "error registering at: Jul 28, 04:50" and when opening up the node "Attention: This node requires Node-RED custom integration version 1.6.0+ to be installed in Home Assistant for it to function."

## Steps to reproduce

Add a webhook node to canvas and deploy.

## Proposed changes

I do not know what the issue is and would like to get some hints as to how to resolve this.

**Comment by fjepsen** [comment]
Have a look at HACS page. Perhaps you overlooked an update for Node-RED custom integration there.

**Comment by wiiNinja** [comment]
Oh! I didn't realize I had to install a HACS companion plugin as well. I never had that installed. Anyway, I installed that and issue resolved. Thanks.
