### ISSUE TITLE
Node "events: all" massively spams event bus in HA

### ISSUE THREAD

**Issue by ShadowRep** [hassio-addons/addon-node-red#1653]
I am trying to detect if a HA-timer is canceled at any time.

Using the "events: all" node everything seems to work fine, but after a reboot the event bus in HA
is being spammed massively with messages.
(I can see it in Mosquitto and under: "_HA - Developer Tools - Events - Listen to events_" when I subscribe to "timer.cancelled".)

I can not explain this, since I understand the node should **only** listen and **not generate** messages itself.

Am I doing something completely stupid here or is this a bug? 

## Expected behavior

I expected the node to **fire once**, only **after the timer is canceled**.
Also I expected the node **only to listen** to HA, not send anything itself. (Outside of the Node-Red flow, of course.)

## Actual behavior

It works as expected, when I deploy the flow. After a reboot, the node immediately starts spamming these messages:

```
event_type: timer.cancelled
data:
  entity_id: timer.gastebadfenstertimer
origin: LOCAL
time_fired: "2023-07-29T16:55:30.285594+00:00"
context:
  id: 01H6H9777DMYAFNCC8XJNVBJSP
  parent_id: null
  user_id: null
```

Deactivating the node and deploying stops the spamming.
When I start and cancel the timer again, the spamming also starts again.

## Steps to reproduce

I am using this node:

```
[
    {
        "id": "843a3bb9f85b82b6",
        "type": "server-events",
        "z": "7bfc619dc41e3622",
        "g": "e3d3041bf2d990bd",
        "name": "Timer is canceled",
        "server": "b46bded.64eb82",
        "version": 2,
        "eventType": "timer.cancelled",
        "exposeToHomeAssistant": false,
        "eventData": "{\"entity_id\":\"timer.gastebadfenstertimer\"}",
        "haConfig": [
            {
                "property": "name",
                "value": ""
            },
            {
                "property": "icon",
                "value": ""
            }
        ],
        "waitForRunning": true,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "eventData"
            },
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "$outputData(\"eventData\").event_type",
                "valueType": "jsonata"
            }
        ],
        "event_type": "",
        "x": 220,
        "y": 320,
        "wires": [
            [
                "cef8b05c0a81e333",
                "e611c84628c98f9a",
                "af07a9e5eb032778",
                "bd006a328cea24d9"
            ]
        ]
    }
]
```

Import it and deploy the flow. Everything seems fine.
Restart HA. It starts spamming immediately.
Deactivate the node and redeploy and the spamming stops.
After reactivation and redeployment of the node it seems fine,
but after starting and cancelling the timer it starts spamming again.

**Comment by frenck** [comment]
Hi there @ShadowRep 👋 

It seems like you are in the wrong place to raise this issue. The add-on wraps existing software, there is nothing I can do from an add-on perspective to address your reported issue.

Please report the issue upstream.

../Frenck

**Comment by sinclairpaul** [comment]
The Home Assistant nodes are provided by <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>

**Comment by ShadowRep** [comment]
@sinclairpaul thanks!
