### ISSUE TITLE
update failed to update.. and now nodered wont start.. and no way to reinstall without uninstall

### ISSUE THREAD

**Issue by comet424** [hassio-addons/addon-node-red#1661]
# Problem/Motivation
node red had an update this morning  it was updating but failed...  and  now it wont run..   i cant uninstall i dont wannt loose my settings...  there is no reinstall over top of it.. it says its missing files

Image ghcr.io/hassio-addons/node-red/amd64:14.4.4 does not exist for addon_a0d7b954_nodered

so not sure how to fix it

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
It exists, see for yourself as it is an URL: <https://ghcr.io/hassio-addons/node-red/amd64:14.4.4>

Generally, this indicates an issue with Home Assistant. You can try running `ha supervisor repair` from an terminal screen.

If that doesn't resolve the issue, please file an issue with the Home Assistant Supervisor project instead (as this isn't an problem the add-on can solve or do anything about).

../Frenck

**Comment by comet424** [comment]
@frenck  thank you didnt know about this  ha supervisor repair...   that fixed the issue... as i didnt know where to ask for help figured it was node red addon i needed to do...

thank you very much
