### ISSUE TITLE
Node-Red HTTP requests failing with DEPTH_ZERO_SELF_SIGNED_CERT since upgrading AddOn (14.5.0) to NR 3.1

### ISSUE THREAD

**Issue by davidcoulson** [hassio-addons/addon-node-red#1690]
# Problem/Motivation

Node-Red HTTP requests failing with DEPTH_ZERO_SELF_SIGNED_CERT since upgrading AddOn (14.5.0) to NR 3.1

## Expected behavior

Should connect via HTTPS and provide response msg - This is what happened with prior version of addon/NR.

## Actual behavior

request fails with DEPTH_ZERO_SELF_SIGNED_CERT error

## Steps to reproduce

Use 'http request' node and connect to any HTTPS/TLS site (e.g. https://www.google.com/

**Comment by mikejac** [comment]
This also happens on my installation :-(

**Comment by mikejac** [comment]
@davidcoulson Have you found a workaround?

**Comment by kalda123** [comment]
Hi, when it happens to me, I disabled unused nodes and it magically starts to work (after addon restart).

**Comment by davidcoulson** [comment]
> @davidcoulson Have you found a workaround?

No, but I expect if you define a SSL/TLS profile for each service and manually load the CA to trust it, then it will work.

**Comment by davidcoulson** [comment]
> Hi, when it happens to me, I disabled unused nodes and it magically starts to work (after addon restart).

Weird I did the same thing and it fixed it. Wonder if there was a broken node somewhere that blew it up.
