### ISSUE TITLE
Node Red won't start after Update to 2.0.0

### ISSUE THREAD

**Issue by t0bse** [hassio-addons/addon-node-red#170]
Running HASSIO 0.89.2 on a Raspberry Pi Zero W

after updating, i got these in my Log every time i try to start node-red:
are there new timeout settings in 2.0 ?? it is running smooth on a RPI Zero W but it took its time to start.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
s6-maximumtime: warning: child process crashed
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment]
Issue is found, will be deploying a release asap.

This is due to a bug in Docker.

**Comment by frenck** [comment]
Fixed in v2.0.1
