### ISSUE TITLE
Cannot search for entity in list.  Cannot add events:state node for specific entity due to this

### ISSUE THREAD

**Issue by slbailey** [hassio-addons/addon-node-red#1704]
# Problem/Motivation

> I am no longer able to add an events:state node for most entities because the entity drop down list isn't collecting all the entries and isn't filtering based on what I type

## Expected behavior

> I should be able to type binary_sensor.steve_in_bed or some part of that to make the search locate my entity and it would find it.

## Actual behavior

> When I enter the value, it selects a completely different entity and I'm unable to override.

![image](https://github.com/hassio-addons/addon-node-red/assets/141894/05b0a850-25b9-4f2c-9cc0-5159eae1bfdb)

## Steps to reproduce

> Add an "Events:State" node and try to select an entity based on name.

## Proposed changes

> I'm assuming this may be because I have a lot of entities and maybe it's not pulling the entire list?

**Comment by frenck** [comment]
Hi there 👋 

You are reporting an issue against the add-on, however, add-ons wrap existing software. In this case: Node-RED with a bunch of nodes pre-installed and configured (like the one for Home Assistant).

I'm happy to help out with issues caused in the add-on itself, but this is upstream software you are reporting an issue with. Please report this issue upstream, once it is fixed and released there, the add-on will receive an update.

../Frenck
