### ISSUE TITLE
Wrong date time of nodes within flows

### ISSUE THREAD

**Issue by DerLoco** [hassio-addons/addon-node-red#1707]
Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 14.6.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.10.1
 Home Assistant Supervisor: 2023.10.0

# Problem

When running automations, the picked time is wrong within nodes. Debug message instead showing the right time.

<img width="1087" alt="Bildschirmfoto 2023-10-10 um 09 14 22" src="https://github.com/hassio-addons/addon-node-red/assets/92661887/563c2cd0-0e5a-4f2d-90c4-66ab293f1915">

## Expected behavior

Picked date time is equal browser date time.

## Actual behavior

Picked date time is -2h from actual time 

## Steps to reproduce

Inject node -> call-service -> debug

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Did you follow the documentation on setting the Timezone <https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#time-zone-configuration>

**Comment by DerLoco** [comment]
Thank you, this helped.
