### ISSUE TITLE
Node-Red is not starting

### ISSUE THREAD

**Issue by maximklein** [hassio-addons/addon-node-red#1716]
Hey together, 

I have a problem with Node-Red not starting anymore since a few days. I updated HomeAssistant Core and it stopped working.

Im running the following versions:
Add-on version: 14.6.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.9.3
 Home Assistant Supervisor: 2023.10.0

Everything seems normal till starting the AddOn. The log comes up and freezes at the last line: 

```
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

```

I reinstalled NodeRed allready but it changed nothing. I hope someone can help me! Thanks a lot

**Comment by jmlk52** [comment]
Same issue here. Fresh install, but Node-Red doesn't start. (similar issue with Studio Code Server, log successful but doesn't start).
Re NodeRed:
Add-on version: 14.6.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.10.3
 Home Assistant Supervisor: 2023.10.0
----
[22:11:29] INFO: Starting Node-RED...
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

**Comment by snickers2k** [comment]
same here.. i think problem is HA OS 11.0+

**Comment by agmuz** [comment]
problemy od kilku dni, node-red 14.6.3 not working good,

**Comment by Arthks** [comment]
Had the same issue, it came from not having set the credential secret field in the Configuration tab even when I filled it. The solution that worked for me was to click on the 3 dots on the top right of the configuration tab, select edit yaml and key the credential secret in the appropriate line.

**Comment by LindsayReid** [comment]
Just update HomeAssistant to 11.1 and Node Red does not start correctly.

Core  2023.11.0b0
Supervisor  2023.10.1
Operating System  11.1
Frontend  20231025.1

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 14.6.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.11.0b0
 Home Assistant Supervisor: 2023.10.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to WARNING
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

up to date, audited 1116 packages in 40s

78 packages are looking for funding
  run `npm fund` for details

76 vulnerabilities (34 moderate, 33 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

Error loading settings file: /etc/node-red/config.js
/config/node-red/settings.js:47
   default: "memoryOnly",
   ^^^^^^^

SyntaxError: Unexpected token 'default'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/etc/node-red/config.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
