### ISSUE TITLE
Node red wont start

### ISSUE THREAD

**Issue by RDickens** [hassio-addons/addon-node-red#1719]
Just updated node red and home assistant to the latest versions and now node red won't start

Home assistant 2023.10.5
Supervisor 2023.10.0
Operating system 11.0
Fronted 20231005.0 - latest
Node red 14.6.3

Error log:
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 04:55:22 (11 occurrences)
Last logged: 08:07:43

Failed to to call /addons/a0d7b954_nodered/start - 500 Server Error for http+docker://localhost/v1.43/containers/addon_a0d7b954_nodered/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l/XN5EVDDMKE77XUWQASAPMALPLF: no such file or directory")

I tried to start it in safe mode and it still throws the same error and doesn't start

**Comment by frenck** [comment]
>  500 Server Error for http+docker://localhost/v1.43/containers/addon_a0d7b954_nodered/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l/XN5EVDDMKE77XUWQASAPMALPLF: no such file or directory

This is an issue with your system, not the add-on. This might be a sign of data corruption (if you are using an SD card that might be a bad sign). You can try to fix your overlay by running `ha supervisor repair` from an terminal.

../Frenck

**Comment by RDickens** [comment]
Thanks that worked a treat :relieved:
