### ISSUE TITLE
Node-Red flows are not loading on version 16.0.0

### ISSUE THREAD

**Issue by 10Thirty** [hassio-addons/addon-node-red#1737]
# Problem/Motivation
Node-Red flows are not loading on version 16.0.0

## Actual behavior

When I open node red I get the following message

![image](https://github.com/hassio-addons/addon-node-red/assets/58256824/34677270-f3f4-4a42-afb4-d462b88a44dd)

Any automations in node red are no longer running and the logfile has the following in it

Node-RED
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 16.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

up to date, audited 2 packages in 1s

found 0 vulnerabilities
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[11:02:38] INFO: Starting Node-RED...

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

15 Nov 11:02:39 - [info] 

Welcome to Node-RED
===================

15 Nov 11:02:39 - [info] Node-RED version: v3.1.0
15 Nov 11:02:39 - [info] Node.js  version: v18.18.2
15 Nov 11:02:39 - [info] Linux 6.1.59 x64 LE
15 Nov 11:02:40 - [info] Loading palette nodes
15 Nov 11:02:41 - [info] Dashboard version 3.6.1 started at /endpoint/ui
15 Nov 11:02:41 - [info] Settings file  : /etc/node-red/config.js
15 Nov 11:02:41 - [info] Context store  : 'default' [module=memory]
15 Nov 11:02:41 - [info] User directory : /config/
15 Nov 11:02:41 - [warn] Projects disabled : editorTheme.projects.enabled=false
15 Nov 11:02:41 - [info] Flows file     : /config/flows.json
15 Nov 11:02:41 - [info] Server now running at http://127.0.0.1:46836/
15 Nov 11:02:41 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

15 Nov 11:02:41 - [warn] Error loading credentials: SyntaxError: Unexpected token  in JSON at position 0
15 Nov 11:02:41 - [warn] Error loading flows: Error: Failed to decrypt credentials
15 Nov 11:02:41 - [info] Starting flows
15 Nov 11:02:41 - [info] Started flows
[11:02:42] INFO: Starting NGinx...
15 Nov 11:02:46 - [info] [server:Home Assistant] Connecting to http://supervisor/core
15 Nov 11:02:46 - [info] [server:Home Assistant] Connected to http://supervisor/core

**Comment by frenck** [comment]
Duplicate of #1733 fixed in #1734 released in v16.0.1
