### ISSUE TITLE
Git pull and Node-RED config

### ISSUE THREAD

**Issue by klatka** [hassio-addons/addon-node-red#1739]
# Problem/Motivation

I have my node-red config in a git repo synced via git pull add on. I assume that upgrading to version 16.x will kill my setup because the config folder is no longer in `config/` where the git repo lives. How can I sync the node-red config in version 16.x?

## Expected behavior

Sync node-red config in git like in version 15.x

**Comment by frenck** [comment]
Use `/homeassistant` instead.

**Comment by klatka** [comment]
I did the upgrade. Now my node-red config is stored at `/addon_configs/a0d7b954_nodered`. I don't understand your comment. How can I use `/homeassistant`?
