### ISSUE TITLE
Hass.io 0.90.1 cannot update NodeRed to 2.0.1

### ISSUE THREAD

**Issue by comment23** [hassio-addons/addon-node-red#174]
# Problem/Motivation

> NodeRed will not update to 2.0.1 from Hass.io 0.90.1

## Expected behavior

> NodeRed to successfully install.

## Actual behavior

> 
19-03-22 02:25:26 INFO (SyncWorker_17) [hassio.docker.interface] Update Docker hassioaddons/node-red-armhf:v1.4.0 to hassioaddons/node-red-armv7:2.0.1
19-03-22 02:25:26 INFO (SyncWorker_17) [hassio.docker.interface] Pull image hassioaddons/node-red-armv7 tag 2.0.1.
19-03-22 02:25:27 ERROR (SyncWorker_17) [hassio.docker.interface] Can't install hassioaddons/node-red-armv7:2.0.1 -> 500 Server Error: Internal Server Error ("readlink /var/lib/docker/overlay2/l: invalid argument").

## Steps to reproduce

> Clicked update within NodeRed

## Proposed changes

>

**Comment by frenck** [comment]
I'm sorry to say, but this is an HassOS issue.
The add-on doesn't start or update, which is out of my control scope.
Please report the issue with Home Assistant/Hassio/HassOS.

👍
