### ISSUE TITLE
Can't access Node-Reds own folder in /addon_configs/

### ISSUE THREAD

**Issue by dflvunoooooo** [hassio-addons/addon-node-red#1740]
# Problem/Motivation

I have a flow to generate a text file out of the `flows.json` file mit a read file node. This txt file is to be checked by watchman. But I can no longer access this file since it moved from /config/node-red. I get the error `Error: ENOENT: no such file or directory, open '/addon_configs/a0dc2854_nodered/flows.json'`.

## Expected behavior

Have access to this file from Node-Red.

## Actual behavior

No access.

## Steps to reproduce

Create read file node and try to read it.

## Proposed changes

Make it accessible, please.

**Comment by frenck** [comment]
Correct, Home Assistant can no longer access the Node-RED configuration.

../Frenck

**Comment by HaraldGithub** [comment]
@frenck 
I want to push and support the possibility to check also all node-red-flows by Watchman!
An alternativ solution would be, that your baby "Spook" will also check node-red-flows!!
