### ISSUE TITLE
Link to dashboard port 8123

### ISSUE THREAD

**Issue by kokoardruino** [hassio-addons/addon-node-red#1741]
When I want to go to the Node-red dashboard. I always click on the icon shown in the image in the circle.

<img width="346" alt="Screenshot 2023-11-15 at 20 59 18" src="https://github.com/hassio-addons/addon-node-red/assets/22130812/e451208a-61aa-478c-acd6-db950e99d6cd">

Which always worked fine. But now it doesn't work anymore.
When I click on it, it links to http://xxx.xxx.xxx.xxx:8123/endpoint/ui
And I get a 404: Not Found error.

(xxx.xxx.xxx.xxx = local ip addres)

When I change the port 8123 to 1880, the dashboard works normally.

I have had this problem since the update to nodered version 14. Before that it has always worked fine.
I was previously able to solve this problem by completely reinstalling nodered in hassio.
It was then necessary to also delete the nodered folder in the config folder.
After the new installation the link worked properly again. until the next update from nodered.

**Comment by sinclairpaul** [comment]
If you access the Node-Red UI over http://xxx.xxx.xxx.xxx:1880 does the same behaviour occur?

You may be prompted for Credentials, which would be your HA creds

**Comment by kokoardruino** [comment]
No, I can simply access node-red via http://xxx.xxx.xxx.xxx:1880.

**Comment by sinclairpaul** [comment]
That's not what I meant, access node-red via the port, then click the dashboard link, and does the same behaviour occur?

I can't duplicate it.

**Comment by kokoardruino** [comment]
Sorry for the late response!!

Ahh yes, now I understand your question.
No, if I open nodered directly. so via :1880. Then the dashboard link will work normally.
