### ISSUE TITLE
On 16.0.2, Webhook blocked. Not working, Alexa not working

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [hassio-addons/addon-node-red#1743]
# Problem/Motivation

> Update 16.0.2 makes problem as the cause origin.

## Expected behavior

> Webhook components and Alexa/Echo components must be works as before.

## Actual behavior

> Webhook not working/not triggered. Alexa/Echo components cookie keep mis-recognized(keep asking open Alexa login browser to get cookie after every time restart node-red or Alexa/Echo component).

## Steps to reproduce

> Just update 16.0.2 from 15.1.1

## Proposed changes

> Just needed to be fixed.

**Comment by driagi** [comment]
Same problem with cookies. The contents of the Node-red folder are gone and the file for Alexa cookies cannot be written

**Comment by driagi** [comment]
I went back to the previous version 15.1.1. Node-red wouldn't reboot. Back to 16.0.2 I completely lost the Flow.json. Once the Flow.json Backup has been restored, Alexa seems to be working again. However, I don't understand where to find the Node-red files (I use HA OS)

**Comment by Mitchell-kw-Lee** [comment]
ping. Why don't you stop/rollback the version has multiple problems?

**Comment by Mitchell-kw-Lee** [comment]
On 17.0.1 the new version on 9th Jun 2024, 
Websocket problem seems solved.
BUT, 
'Alexa Event node' not recognize Alexa cookie. Event open web browser to save cookie new.

The cookie path is '/config/node-red/cookie.txt'.
What is the problem of 16.x and 17.x? Why it happen?

**Comment by Mitchell-kw-Lee** [comment]
Errr...
just checked that 
NO Files exist in /root/config/node-red. empty.
Which folder is right folder for the alexa cookie?

**Comment by frenck** [comment]
@Mitchell-kw-Lee Seems like you didn't read the release notes on a major version change, see: <https://github.com/hassio-addons/addon-node-red/releases/tag/v16.0.0>

**Comment by Mitchell-kw-Lee** [comment]
@frenck Got that information.
BUT, Alexa STILL NOT working with the path niether '/root/share/AlexaCookie.txt' nor '/root/addon_configs/a0d7b954_nodered/AlexaCookie.txt'.
Keep asking open browser to login Amazone to save cokkies and, after seeing succesfully saved page, no response.
What is your suggestion now on?

**Comment by Mitchell-kw-Lee** [comment]
After change the path to just '/share/AlexaCookie.txt' 
and
Restart node-red.
Works.
Problem solved.
