### ISSUE TITLE
Write file node can no longer access home assistant www folder

### ISSUE THREAD

**Issue by smeegoan** [hassio-addons/addon-node-red#1745]
# Problem/Motivation

> With the recent change of node red directory save file nodes no longer work properly

## Expected behavior

> Before upgrading to version 16 I had a write file node saving a file in /config/www/frigate.jpg

## Actual behavior

> No file is saved. The only way I got the file to be created was to only specify frigate.jpg as the filename and that saved the file in addon_configs\a0d7b954_nodered\www. Even trying to use relative paths to the proper home assistant www folder did not work

## Steps to reproduce

> Create a simple http request node linked to a write file node with the path /config/www/frigate.jpg

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by krammie** [comment]
In addition to the above, the issue **also occurs when reading files** using the "Read file" node to read a file in the /config/ path.
When reading the file, the following message is logged in the debug log: Error: ENOENT: no such file or directory, open '/config/file.csv'

The problem occurred after upgrading to Node-RED version 16.0.2.

**Comment by bowlingbeeg** [comment]
Change your paths to use /homeassistant/... insteand of /config/...  That seemed to work for me using the image node to save an image to the /homeassistant/www/ directory

**Comment by krammie** [comment]
> Change your paths to use /homeassistant/... instead of /config/... That seemed to work for me using the image node to save an image to the /homeassistant/www/ directory

Thank you! This did solve the issue for me as well.
Nevertheless, it would be helpful if the initial situation is fixed as this is also documented and used by people.

**Comment by DrDuk** [comment]
I have a similar problem with my back up flow.  I can't find a path to the flows.json file.  I'm running supervised.  How do I now read /addon_configs/a0d7b954_nodered/flows.json ?   Will "a0d7b954" change ever time the addon gets updated? Thanks

**Comment by DrDuk** [comment]
For anyone else having difficulty, I found the answer in Discord.  There is a symlink from /addon_configs/a0d7b954_nodered/ which can be found by the read and write nodes using /config/ in the Filename path.

**Comment by Jpsy** [comment]
> Change your paths to use /homeassistant/... instead of /config/... That seemed to work for me using the image node to save an image to the /homeassistant/www/ directory

I found this too and indeed it works for read file nodes, but not for write file nodes. Writing seems to be blocked by insufficient permissions. I get the following error in the debug pane:

    Call-service error. 
    Cannot write `/homeassistant/www/tmp/mytest.jpg`, 
    no access to path; 
    `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`

I tried adding /homeassistant/www/tmp/ and also /config/www/tmp/ to my `allowlist_external_dirs` block,  but this does not help.

**Comment by joaopedros2** [comment]
I'm having the same problem:

```
Error: ENOENT: no such file or directory, open '/config/.storage/local_todo.compras_no_lidl.ics'
```

**Comment by earto** [comment]
Same problem here. After the last update many of my automations stopped working and the debug log is full of errors. These have all been working fine for a long time. A few error examples:

Flogger nodes:
`Can't write file: Error: ENOENT: no such file or directory, open '/config/www/flogger/arm-disarm_events.log'`

FS-Ops nodes:
`Error: ENOENT: no such file or directory, scandir '/config/www/snapshots/'`

Pushover nodes:
`Error: form-data: ENOENT: no such file or directory, open '/config/www/snapshots/1700384599905_vto.jpg'`

Is this a "breaking change" by design and if so, for what purpose? Comments above indicate that the mapping "/config/www/" has changed to "/homeassistant/www/" so I will try that. I've got a lot of variables and nodes in flows/subflows to work through.

Interestingly, the "call service" node still requires "/config/www/" path (I guess because its HA accessing). Either way if this is change is by design, there's now 2x different root paths within Node Red to the same directory. I was using a variable to store the path/filename and use it across both HA and non-HA nodes. This isn't possible now.

Screenshot below of working "call service" node using /config/www/ path (in green). Note that errors are failures from other nodes using the same path.
![image](https://github.com/hassio-addons/addon-node-red/assets/1768017/b791042e-3995-4cf6-a798-c10fdcc154b7)

**Comment by earto** [comment]
> > Change your paths to use /homeassistant/... instead of /config/... That seemed to work for me using the image node to save an image to the /homeassistant/www/ directory
> 
> Yes, I found this option too and indeed it works, but only for read file nodes. Writing seems to be blocked by insufficient permissions. I get the following error in the debug pane:
> 
> ```
> Call-service error. 
> Cannot write `/homeassistant/www/tmp/mytest.jpg`, 
> no access to path; 
> `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`
> ```
> 
> I tried adding /homeassistant/www/tmp/ and also /config/www/tmp/ to my `allowlist_external_dirs` section, but this does not help. (I also think, the hint in the error message is outdated and should be changed too.)

I suspect its because the "call service" node still uses the original /config/www/ path. At least it did for me (see above). It becomes awkward when you have other nodes in the same flow which need to use /homeassistant/www/ for the same location.

Yes, its a mess. I'm still working through my flows, sub-flows to fix this.

**Comment by Jpsy** [comment]
> I suspect its because the "call service" node still uses the original /config/www/ path. At least it did for me (see above). It becomes awkward when you have other nodes in the same flow which need to use /homeassistant/www/ for the same location.
> 
> Yes, its a mess. I'm still working through my flows, sub-flows to fix this.

You are SO VERY right! 
After reverting the changes back to /config/ for all "call services" nodes, my flows work as expected.
Thanks you!
And you are right about the mess too. My flows are terribly confusing now.

**Comment by dmutpuul** [comment]
@earto , @Jpsy   I have same situation... writing file to folder /config/www but reading from /homeassistant/www

**Comment by Jpsy** [comment]
It's actually not about reading or writing.
It's about nodes that execute in Nodes Red context (/homeassistant) and call service nodes that send data over to HA, so it is processed in HA context (/config).

**Comment by dmutpuul** [comment]
> It's actually not about reading or writing. It's about nodes that execute in Nodes Red context (/homeassistant) and call service nodes that send data over to HA, so it is processed in HA context (/config).
yep... i am also using (or try to use) snapshot directly from go2rtc. In that case only /homeassistant path works.
[There is](https://github.com/AlexxIT/go2rtc/wiki/Snapshot-to-Telegram) some info howto

**Comment by sanderlv** [comment]
Left or right... it's frikking confusing now writing and reading in the same location with different folder names. This worked for years!

(There was shortly an equal issue with the samba addon which changed to homeassistant foldername as wel for a very short time untill it was changed back).

This is typically a case of "back to the drawingboard" or " document well before launch".

It was not even mentioned as a breaking change although it clearly was/is.

**Comment by Ottmar0815** [comment]
I have the same problem. Is there any bugfix in progress? Thank you!

**Comment by domhauton** [comment]
Thank you for this thread. The change also invalidated most help threads online on how to set up flow that require reading to or writing from files. I spent the last two hours banging my head against this.

Is it possible to find the volume mount configuration anywhere?

**Comment by sinclairpaul** [comment]
> Is it possible to find the volume mount configuration anywhere?

/addon_configs/a0d7b954_nodered is mounted to /config (a0d7b954 is the slug of the release addon, if you install edge it would be different)

the old /config is mounted to /homeassistant

This isn't the addon doing this, it is the supervisor, your can look at the code in that repo.

There are multiple discussions in this thread around palettes that run within the Node-Red container (which if you would want to write to the homeassistant config folder would use /homeassistant), and those that use the service calls to Home Assistant which runs in the context of the HA container (in which case uses it's /config directory).

**Comment by domhauton** [comment]
> that use the service calls to Home Assistant which runs in the context of the HA container (in which case uses it's /config directory).

Thank you for the very informative response. So home-assistant is also running on a container, and there is some magic (made from soft-links and/or volume mounts) on the underlying host that allows addon containers to see the same files in different directories. My assumption was initially that home-assistant was running without containerisation.

It a shame that they're now inconsistently mapped but it makes sense. 👍

**Comment by sinclairpaul** [comment]
>  and there is some magic (made from soft-links and/or volume mounts)

It's not so much magic, but just bind mounts within Docker, yep it was easier when everything was mounted the same however the main goal here was to ensure that backups contain the addon data where they didn't before.

**Comment by dierochade** [comment]
Does this mean the different path for write and read in the nodes settings is as intended and wont be addressed for a more consistent user experience? 

@frenck Could you take a look and give feedback?

**Comment by ingo916** [comment]
> Change your paths to use /homeassistant/... instead of /config/... That seemed to work for me using the image node to save an image to the /homeassistant/www/ directory

Where do I change the paths?

**Comment by Ottmar0815** [comment]
> Where do I change the paths?

Directly in every node.

**Comment by ingo916** [comment]
Thanks for the info I got it



Ingo Azarvand
209-207-2243
Licensed FFL Dealer

**Comment by frenck** [comment]
As pointed out above, the right location is `/homeassistant/www/`

../Frenck
