### ISSUE TITLE
Can't start node-red after update 16.0.2

### ISSUE THREAD

**Issue by jansendejong** [hassio-addons/addon-node-red#1746]
I can't start node-red after updating to 16.0.2 
tried multiple times to backup and update again but nothing. 

Anyone who can help me? 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 16.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

up to date, audited 356 packages in 8s

15 packages are looking for funding
  run `npm fund` for details

26 vulnerabilities (2 low, 10 moderate, 12 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[21:09:57] INFO: Starting Node-RED...

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

Error loading settings file: /etc/node-red/config.js
[21:09:58] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[21:09:58] INFO: Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by emotionallogos0f1** [comment]
+1
seems to run my automations, but still red dot at the node-red config page and no access to the gui.
When clicking on node-red in the hassio sidebar, it asks to start up, cause it thinks node-red not running. But it is.

**Comment by jansendejong** [comment]
It really doesn't start for me. I have now restored a full backup and exported all flows. then uninstalled node-red and did a fresh install. even then it doesn't want to start and I get messages in my log as you see above.

**Comment by emotionallogos0f1** [comment]
Did exactly the same. Saw red dot -> full restore -> still red dot -> update to 16.0.2 -> still red dot, but seems running in background as my automations came alive in my visualisation. But no access to the gui, nor access to gui via Port (1880 in my case).

**Comment by MartinMajewski** [comment]
I'm a noob with Node-Red in combination with HA (so a HA noob, I am), so no fancy log from me (I haven't figured out where to find it, as the UI-way shows an empty log). However, I cannot start the add-on either.

The first time, I got an error that some configuration could not be read. However, this was a one-time occurrence. I haven't received any messages since. The start procedure stops. Restarting the server or rebooting my Raspberry Pi 4 does not help, either. Configuration seems okay, from what HA is telling me. However, I still need a good look into the (ssh) cli.

Can anyone point me to where to look for a solution, please?

Cheers,
Martin

**Comment by MartinMajewski** [comment]
So, as this was a clean installation of Node-Red on a reasonably fresh HA install, the SSL option was set to `on` by default.
I have disabled it now, and Node-Red started as expected.

Therefore, why is this option enabled if there is neither a valid certificate available nor information given that SSL is a default-on option now?

**Comment by sinclairpaul** [comment]
> Therefore, why is this option enabled if there is neither a valid certificate available nor information given that SSL is a default-on option now?

This hasn't changed, it's always been default on a fresh install and the log message is quite descriptive.

To the original poster (as we seem to be adding multiple issues here), does the addon start with the safe mode option?

**Comment by frenck** [comment]
> why is this option enabled if there is neither a valid certificate available nor information given that SSL is a default-on option now?

We can't know or check if you have that or not. It assumes secure by default out of the box. If you want to lower it, that is up to you 👍 

../Frenck
