### ISSUE TITLE
Node red not recessived UDP packets to device

### ISSUE THREAD

**Issue by userosos** [hassio-addons/addon-node-red#1747]
# Problem/Motivation

I installed HA with supervised in Debian and node-red addon. Make the scheme like on the pic. I check the host and the port in the router used network traffic analyzer - it have 0 packets.
![изображение](https://github.com/hassio-addons/addon-node-red/assets/22872748/af4aa101-ce36-4895-9cef-0d25cc811532)
## Expected behavior

I want that all packets will go to the devices and see it in network traffic analyzer

## Actual behavior

All packets was blocked and i can't seeit on the router.

## Steps to reproduce
1. Install debian
2. Install HA uses the manual: https://github.com/home-assistant/supervised-installer
3. Install node-red addoninto HA
4. Make the scheme like the pic and start it,
5. Go to network traffic analyzer and check the port.

**Comment by henriklund** [comment]
Stupid question: Have you checked all firewalls (including iptables)?

**Comment by userosos** [comment]
> Stupid question: Have you checked all firewalls (including iptables)?

No. But i have official debian. It has disabled firewall, i think. How i can check it, can you help me?

**Comment by henriklund** [comment]
sudo iptables -L -v -n
