### ISSUE TITLE
Han desaparecido mis flows.

### ISSUE THREAD

**Issue by Jadelcas** [hassio-addons/addon-node-red#1748]
All my scripts were disappeared!!! Help

Edited: sorry, not my scritpts, I wanted to say: my flows

_Originally posted by @rubendediegomartinez in https://github.com/hassio-addons/addon-node-red/issues/1738#issuecomment-1812517583_

**Comment by Jadelcas** [comment]
Me ha ocurrido lo mismo con la última actualización.

**Comment by tjorim** [comment]
Duplicate of #1736.
