### ISSUE TITLE
[16.0.2] Failing to populate HA information in NR, No Node Status, No Debug Node Output

### ISSUE THREAD

**Issue by XxInvictus** [hassio-addons/addon-node-red#1749]
# Problem/Motivation

- Addon not correctly retrieving data from HA, this includes but is not limited to Services, Node Status and complete lack of Debug node operation. I am sure there is more but I at this point I haven't gone through everything. It would honestly take so long to find all functionality because it is shambles.

NR Addon: 16.0.2
node-red-contrib-home-assistant-websocket: 0.59.0
HA Core: 2023.11.2
HA Supervisor: 2023.11.3
HA OS: Operating System 11.1

Loosely related to: https://github.com/hassio-addons/addon-node-red/issues/1669

## Expected behavior

- Able to select Services and use the Call Service node. Node Status' update appropriately, without current Status' Node Red is essentially useless.

## Actual behavior

- Placing a Call Service node, none of the auto-populated fields are filled with anything, because you cannot manually type in these fields it renders the Node unusable.
- All HA Nodes appropriately update their status to be parsed and used in flows/downstream nodes
- HA nodes appropriately send output for troubleshooting into a debug node

## Steps to reproduce

- I wish I knew, surely others would be screaming if this was a wider issue.
- Setup is via HA Addon on Home Assistant OS system
- I have completely nuked the addon, started from scratch multiple times and still the issue persists
 - This includes removing the addon
 - Confirming the docker container was removed not just inactive
 - Confirming the image was removed
 - Confirming all NR configs are deleted
 - Using shell to do a find for any remaining node-red files

Below are screenshots of the Service behaviour and configs:
![image](https://github.com/hassio-addons/addon-node-red/assets/3955293/23c5cbe7-4129-49b5-bc4b-370445899489)
![image](https://github.com/hassio-addons/addon-node-red/assets/3955293/f5db8eae-f681-4077-9f6b-8a2ff4fa0056)
![image](https://github.com/hassio-addons/addon-node-red/assets/3955293/8b47c35f-0660-48dd-8020-32becf1e515e)

Also attached a Trace log of opening the Domain dropdown in the Call Service node. I can get a larger log if required I just need to get it direct from the shell/docker logs because of the way HA is truncating it.
[a0d7b954_nodered_2023-11-21T13-13-38.739Z.log](https://github.com/hassio-addons/addon-node-red/files/13426774/a0d7b954_nodered_2023-11-21T13-13-38.739Z.log)

## Proposed changes

Unknown

**Comment by XxInvictus** [comment]
Further information discovered, it looks like if you access Node-Red UI directly on port 1880 (not in-frame of HA) everything works as intended:
https://community.home-assistant.io/t/no-autocompletion-connection-to-homeassistant/638079/14

**Comment by XxInvictus** [comment]
This is still an active issue.

**Comment by Tommyboy51300** [comment]
Seconded.

**Comment by frenck** [comment]
Try with v17.0.0 just shipped.
