### ISSUE TITLE
toLocaleString not working in Node-RED 2.0

### ISSUE THREAD

**Issue by NoWebH** [hassio-addons/addon-node-red#176]
# Problem/Motivation

Since Node-RED 2.0 the JavaScript function toLocaleString for a DateObject is not working any more.

## Expected behavior

toLocaleString('en-GB') should provide a date formatted as 3/22/2019, 20:55:30

## Actual behavior

but it returns 3/22/2019, 8:55:30 PM. Regardless what format is provided 'en-GB' or 'de-DE' it's always 'en-US' returned.

## Steps to reproduce

create a JavaScript node and add
var myDateString = new Date().toLocaleString('en-GB');
and output this string

Running Hassio on Raspberry Pi 3 B+, browser is Safari on a Mac, browser language German

**Comment by frenck** [comment]
The add-on has been updated to run NodeJS 10.x, could that be related?

**Comment by NoWebH** [comment]
The add-on is 2.0.2, but where can I find the NodeJS version?
At least first time I realised this issue has been after the upgrade to Node-Red add-on 2.x

**Comment by frenck** [comment]
Changes are always listed in the release notes:

<https://github.com/hassio-addons/addon-node-red/releases>

Furthermore, you can always check the Dockerfile for what is installed:

<https://github.com/hassio-addons/addon-node-red/blob/master/node-red/Dockerfile#L27>

**Comment by frenck** [comment]
Issue running stale and is about custom code, closing issue.
