### ISSUE TITLE
Can't open file anymore

### ISSUE THREAD

**Issue by Hellis81** [hassio-addons/addon-node-red#1763]
# Problem/Motivation

> By some reason Node red is no longer able to open and read the core.config_entries file.

```
Error: ENOENT: no such file or directory, open '/config/.storage/core.config_entries'
```

## Expected behavior

> Read file node has previously been able to open and read it. I would expect it to be possible still

## Actual behavior

> I get the error above. Not sure what update this happened since I probably lagged behind two or three updates. 

## Steps to reproduce

> Try and read the file: 

```
[{"id":"edaef6d3.315478","type":"file in","z":"48ef5c6b.b38b24","name":"","filename":"/config/.storage/core.config_entries","filenameType":"str","format":"utf8","chunk":false,"sendError":false,"encoding":"none","allProps":false,"x":500,"y":580,"wires":[["a53436a2.399bc8"]]}]
```

## Proposed changes

> I don't see a reason why we shouldn't be able to read these files, writing is a different thing. But reading them should not be blocked in my opinion.

**Comment by sinclairpaul** [comment]
`/config` has been changed to `/homeassistant`

There are a few other issues discussing this.
