### ISSUE TITLE
Connection closed to http://supervisor/core

### ISSUE THREAD

**Issue by LucasJanin** [hassio-addons/addon-node-red#1764]
# Problem

NodeRed addon gets disconnected from HA.
The only solution is to restart the addon.

## Expected behavior

Nodered would stay connected to Home Assistant

## Actual behavior

7 Dec 07:57:16 - [info] [server:Home Assistant] Connecting to http://supervisor/core
7 Dec 07:57:16 - [info] [server:Home Assistant] Connected to http://supervisor/core
7 Dec 07:57:16 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
7 Dec 07:57:21 - [info] [server:Home Assistant] Connecting to http://supervisor/core
7 Dec 07:57:21 - [info] [server:Home Assistant] Connected to http://supervisor/core
7 Dec 07:57:21 - [info] [server:Home Assistant] Connection closed to http://supervisor/core

## Steps to reproduce

I was able to figure out why this happened. 
It mostly occurs at night without any updates or restarts of any add-on or HA. 
How can I access the full log of the add-on? 
This will help me understand what is causing this issue.

## Proposed changes

TBD

**Comment by LucasJanin** [comment]
This is related to https://github.com/zachowj/hass-node-red but addon-node-red isn't using the last version of Node-RED v3.1.3 and the last version of node-red-contrib-home-assistant-websocket v0.62.2

**Comment by tjorim** [comment]
Not an issue as we didn't ship a release with that version yet. We can't control which nodes the user updates.
https://github.com/hassio-addons/addon-node-red/blob/v16.0.2/node-red/package.json#L19
