### ISSUE TITLE
Watchdog in overdrive, node red constantly resetting

### ISSUE THREAD

**Issue by home-rj** [hassio-addons/addon-node-red#1765]
Hi,

Ive checked my logs and i cant seem to find anything to tell node red to stop, but there is something causing it to constantly crash. Ive checked both the internal log and node red log and nothing is saying an error. 

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 16.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.11.1
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

up to date, audited 1 package in 429ms

found 0 vulnerabilities
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[08:37:02] INFO: Starting Node-RED...

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

10 Dec 08:37:03 - [info] 

Welcome to Node-RED
===================

10 Dec 08:37:03 - [info] Node-RED version: v3.1.0
10 Dec 08:37:03 - [info] Node.js  version: v18.18.2
10 Dec 08:37:03 - [info] Linux 6.1.59 x64 LE
10 Dec 08:37:04 - [info] Loading palette nodes
10 Dec 08:37:06 - [info] Dashboard version 3.6.1 started at /endpoint/ui
10 Dec 08:37:06 - [info] Settings file  : /etc/node-red/config.js
10 Dec 08:37:06 - [info] Context store  : 'default' [module=memory]
10 Dec 08:37:06 - [info] User directory : /config/
10 Dec 08:37:06 - [warn] Projects disabled : editorTheme.projects.enabled=false
10 Dec 08:37:06 - [info] Flows file     : /config/flows.json
10 Dec 08:37:06 - [info] Server now running at http://127.0.0.1:46836/
10 Dec 08:37:06 - [info] Starting flows
10 Dec 08:37:06 - [info] Started flows
10 Dec 08:37:06 - [error] [ha-sensor:Sonnen2 Operation Mode2] NoConnectionError
10 Dec 08:37:07 - [error] [ha-sensor:Sonnen Operation Mode] NoConnectionError
[08:37:07] INFO: Starting NGinx...
10 Dec 08:37:11 - [info] [server:Home Assistant jez] Connecting to http://supervisor/core
10 Dec 08:37:11 - [info] [server:Home Assistant] Connecting to http://supervisor/core
10 Dec 08:37:11 - [info] [server:Home Assistant jez] Connected to http://supervisor/core
10 Dec 08:37:11 - [info] [server:Home Assistant] Connected to http://supervisor/core`

What can cause the system to crash and watchdog to re fire it up constantly?

**Comment by Supermanenvysme** [comment]
Same issue experienced for the past 14 hours.

Restarted several times, when disabling watchdog, node red starts but the logs indicate the following:

Service Node-RED exited with code 256 (by signal 4)

**Comment by creoden** [comment]
I think what I'm seeing is similar and it started in the last week or so, I'm seeing high CPU Usage, and Node-Red constantly locking up, and watchdog not doing anything, I either have to load the web interface of node-red to get it to respond again or restart node-red. not running any addon tied to node-red (like node-red companion) and haven't updated anything outside of whats come through official HA Updates.

constantly seeing this in the node-red logs as well as API call failures

16 Dec 12:35:48 - [info] [server:Home Assistant] Connecting to http://supervisor/core
16 Dec 12:35:48 - [info] [server:Home Assistant] Connected to http://supervisor/core
16 Dec 12:42:42 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
16 Dec 12:42:47 - [info] [server:Home Assistant] Connecting to http://supervisor/core
16 Dec 12:42:47 - [info] [server:Home Assistant] Connected to http://supervisor/core
16 Dec 12:49:42 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
16 Dec 12:49:47 - [info] [server:Home Assistant] Connecting to http://supervisor/core
16 Dec 12:49:47 - [info] [server:Home Assistant] Connected to http://supervisor/core
16 Dec 12:56:42 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
16 Dec 12:56:47 - [info] [server:Home Assistant] Connecting to http://supervisor/core
16 Dec 12:56:47 - [info] [server:Home Assistant] Connected to http://supervisor/core
16 Dec 13:03:41 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
16 Dec 13:03:46 - [info] [server:Home Assistant] Connecting to http://supervisor/core
16 Dec 13:03:46 - [info] [server:Home Assistant] Connected to http://supervisor/core
16 Dec 13:10:42 - [info] [server:Home Assistant] Connection closed to http://supervisor/core

[error] [api-call-service:Display On] Call-service error.

**Comment by frenck** [comment]
Please try with the latest release v17.0.0

**Comment by Kurisutian** [comment]
I also experience this for weeks now. Every now and then NodeRed completely locks up even with the most recent v17.0.4 version:

4 Feb 08:14:06 - [info] [server:Home Assistant] Connected to http://supervisor/core
4 Feb 08:14:06 - [info] [server:Home Assistant] Connection closed to http://supervisor/core

**Comment by digitalMedic** [comment]
This issue is still occurring.  It happens due to node red version 17.0.7 being installed and running.

**Comment by digitalMedic** [comment]
The new version, 17.0.10 seems to have fixed the freezing and crashing. There are no errors in the HA supervisor log either.
