### ISSUE TITLE
Vulnerability in NR 16.0.2

### ISSUE THREAD

**Issue by jm-cook** [hassio-addons/addon-node-red#1768]
# Problem/Motivation

During startup, the node red add-on reports a vulnerability in the logs.

## Expected behavior

No warning in the logs

## Actual behavior

Got a warning about 2 vulnerabilties:

    s6-rc: info: service s6rc-oneshot-runner: starting
    s6-rc: info: service s6rc-oneshot-runner successfully started
    s6-rc: info: service base-addon-banner: starting
    
    -----------------------------------------------------------
     Add-on: Node-RED
     Flow-based programming for the Internet of Things
    -----------------------------------------------------------
     Add-on version: 16.0.2
     You are running the latest version of this add-on.
     System: Home Assistant OS 11.2  (armv7 / raspberrypi3)
     Home Assistant Core: 2023.12.1
     Home Assistant Supervisor: 2023.11.6
    -----------------------------------------------------------
     Please, share the above information when looking for help
     or support in, e.g., GitHub, forums or the Discord chat.
    -----------------------------------------------------------
    s6-rc: info: service base-addon-banner successfully started
    s6-rc: info: service fix-attrs: starting
    s6-rc: info: service base-addon-log-level: starting
    s6-rc: info: service fix-attrs successfully started
    s6-rc: info: service base-addon-log-level successfully started
    s6-rc: info: service legacy-cont-init: starting
    s6-rc: info: service legacy-cont-init successfully started
    s6-rc: info: service init-nginx: starting
    s6-rc: info: service init-customizations: starting
    s6-rc: info: service init-customizations successfully started
    s6-rc: info: service init-nodered: starting
    s6-rc: info: service init-nginx successfully started
    
    up to date, audited 37 packages in 5s
    
    1 package is looking for funding
      run `npm fund` for details
    
    2 vulnerabilities (1 moderate, 1 high)
    
    To address all issues, run:
      npm audit fix
    
    Run `npm audit` for details.
    s6-rc: info: service init-nodered successfully started
    s6-rc: info: service nodered: starting
    s6-rc: info: service nodered successfully started
    s6-rc: info: service nginx: starting
    s6-rc: info: service nginx successfully started
    s6-rc: info: service legacy-services: starting
    s6-rc: info: service legacy-services successfully started
    [08:29:32] INFO: Starting Node-RED...

## Steps to reproduce

Start the node red add-on 16.0.2 and inspect the log file

## Proposed changes

Follow the proposed advice in the log file when building the next release.:

    2 vulnerabilities (1 moderate, 1 high)
    
    To address all issues, run:
      npm audit fix

**Comment by frenck** [comment]
Fixed in the v17.0.0 release
