### ISSUE TITLE
since upgrading to 2.0.2 current state nodes don't work.

### ISSUE THREAD

**Issue by niemyjski** [hassio-addons/addon-node-red#177]
# Problem/Motivation

The nodes just don't work. I get tons of messages like this in the logs.
```
30 Mar 08:05:47 - [info] Started flows
(node:516) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 nodes-started listeners added. Use emitter.setMaxListeners() to increase limit
30 Mar 08:05:47 - [warn] [api-current-state:Automations Enabled?] entity could not be found in cache for entity_id: input_boolean.automation_enable, sending empty payload
```

## Steps to reproduce

Have state nodes.

**Comment by frenck** [comment]
This sounds like an issue with the Home Assistant Node, please report the issue upstream, since from an add-on perspective, there is not much I can do.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/
