### ISSUE TITLE
Home Assistant Nodes suddenly gone, Node Red not working with HA

### ISSUE THREAD

**Issue by Nutti85** [hassio-addons/addon-node-red#1773]
# Problem/Motivation

All Home Assistant nodes are suddenly missing

![image](https://github.com/hassio-addons/addon-node-red/assets/17089762/14039fbf-e6db-4119-b644-5134db84b463)

Version is 16.0.2
HA info:
Core 2023.12.1
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

## Expected behavior

Nodes to be there

## Actual behavior

Nodes gone

## Steps to reproduce

Not sure

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by glijie** [comment]
same here, it happends when you update "node-red-contrib-home-assistant-websocket" to ver. 0.62.1
After restoring Node red the nodes will be back and everything looks normal.

**Comment by MEKadan** [comment]
It seems to be missing `node-red-contrib-home-assistant-websocket.` From "Manage pallette" it offers an update to 0.62.1. When trying that, it looses the nodes. 

When looking for this same `node-red-contrib-home-assistant-websocket.` from "Install" tab, it offers the same version 0.62.1, but actually downgrades to version 0.59. At least that it tells me:

![image](https://github.com/hassio-addons/addon-node-red/assets/66167932/631bcd06-ef8a-457a-83d9-ef3c321f431b)


My system seems to be working with that also, so waiting for further info.

**Comment by MartinMajewski** [comment]
Same here. When I try to reinstall the palette, I get the old 0.59.0 version. Updating to 0.62.1 requires a restart of Node-Red, but then the log says:

```
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 16.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.12.2
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

up to date, audited 74 packages in 2s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[01:10:53] INFO: Starting Node-RED...

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

14 Dec 01:10:57 - [info] 

Welcome to Node-RED
===================

14 Dec 01:10:57 - [info] Node-RED version: v3.1.0
14 Dec 01:10:57 - [info] Node.js  version: v18.18.2
14 Dec 01:10:57 - [info] Linux 6.1.58-haos-raspi arm64 LE
14 Dec 01:10:58 - [info] Loading palette nodes
14 Dec 01:10:59 - [warn] [node-red-contrib-home-assistant-websocket] Node module cannot be loaded on this version. Requires: >=3.1.1 
14 Dec 01:11:02 - [info] Dashboard version 3.6.1 started at /endpoint/ui
14 Dec 01:11:04 - [warn] Missing node modules:
14 Dec 01:11:04 - [warn]  - node-red-contrib-home-assistant-web socket (0.59.0): ha_entity_filter, ha-api, ha-binary-sensor, ha-button, api-call-service, server, api-current-state, ha-device, ha-device-config, ha-entity, ha-entity-config, server-events, server-state-changed, ha-fire-event, ha-get-entities, api-get-history, ha-number, poll-state, api-render-template, ha-select, ha-sensor, ha-sentence, ha-switch, ha-tag, ha-text, ha-time, ha-time-entity, trigger-state, ha-update-config, ha-wait-until, ha-webhook, ha-zone
14 Dec 01:11:04 - [info] Removing modules from config
14 Dec 01:11:04 - [info] Settings file  : /etc/node-red/config.js
14 Dec 01:11:04 - [info] Context store  : 'default' [module=memory]
14 Dec 01:11:04 - [info] User directory : /config/
14 Dec 01:11:04 - [warn] Projects disabled : editorTheme.projects.enabled=false
14 Dec 01:11:04 - [info] Flows file     : /config/flows.json
```

So `[info] Node-RED version: v3.1.0` is running, which is incompatible with the palette version.

**Comment by osulivanDE** [comment]
Same for me. Is there a way to force Node-Red to update to v3.1.1 to meet the requirements of the plugin?

**Comment by MartinMajewski** [comment]
> Same for me. Is there a way to force Node-Red to update to v3.1.1 to meet the requirements of the plugin?

Or at least to stop the auto update of the pallet, as it breaks functionality on each restart.

**Comment by tjorim** [comment]
We can't control the updates and it does not happen automatically.
The user needs to click update in the palette manager for that to happen.
The add-on will get updated in due time. Version 16.0.2 ships with the correct combo:
https://github.com/hassio-addons/addon-node-red/blob/v16.0.2/node-red/package.json#L19

**Comment by MartinMajewski** [comment]
It tries to update the pallet on every machine reboot (RPI4), then all HA nodes are gone and the pallet is no longer installed. I have to search for and install it. It installs 0.59 and provides an option to update to 0.62.x what I **do not** click. Still, on the next reboot: gone!

**Comment by MEKadan** [comment]
> It tries to update the pallet on every machine reboot (RPI4), then all HA nodes are gone and the pallet is no longer installed. I have to search for and install it. It installs 0.59 and provides an option to update to 0.62.x what I **do not** click. Still, on the next reboot: gone!

Mine does not. When You have that 0.59.0 installed, nodes stay there

**Comment by MartinMajewski** [comment]
> > It tries to update the pallet on every machine reboot (RPI4), then all HA nodes are gone and the pallet is no longer installed. I have to search for and install it. It installs 0.59 and provides an option to update to 0.62.x what I **do not** click. Still, on the next reboot: gone!
> 
> Mine does not. When You have that 0.59.0 installed, nodes stay there

Nope, not for me! The pallet gets thrown out!

**Comment by MEKadan** [comment]
> > > It tries to update the pallet on every machine reboot (RPI4), then all HA nodes are gone and the pallet is no longer installed. I have to search for and install it. It installs 0.59 and provides an option to update to 0.62.x what I **do not** click. Still, on the next reboot: gone!
> > 
> > 
> > Mine does not. When You have that 0.59.0 installed, nodes stay there
> 
> Nope, not for me! The pallet gets thrown out!

Hmmm... Came into my mind... You are talking about machine reboots in a way that gives me a feeling those happen often/ regularly... By any chance, do You have automatic reboots scheduled? I do have in attempt to try to maintain system stability.

However, I use service call for Core Integration restart. Node-red survives that.

**Comment by Rohrleitner** [comment]
Are there any news? Who must fix this?

**Comment by ingo916** [comment]
I was able to download and install  and this worked for me. However if I update to 0.62.2 I lose the node-red-contrib-home-assistant-websocket palette 
[node-red-contrib-home-assistant-websocket-0.60.1.tgz](https://github.com/hassio-addons/addon-node-red/files/13847593/node-red-contrib-home-assistant-websocket-0.60.1.tgz)

**Comment by MEKadan** [comment]
In case you haven't seen it, there is a good explanation of the situation: https://community.home-assistant.io/t/warning-do-not-update-websocket-to-0-61-1-with-add-on-version-16-0-2/653887/25

**Comment by ingo916** [comment]
Tha k you.



Ingo Azarvand
209-207-2243
Licensed FFL Dealer

**Comment by MEKadan** [comment]
Frenck just updated the node-red addon, in which thereis also whole chain of websocket updates from 59.0 to the latest.

I installed the addon, and updated websocket from the pallet -> OK with 62.2
