### ISSUE TITLE
Node Red no longer runs after the update

### ISSUE THREAD

**Issue by DL4DP** [hassio-addons/addon-node-red#1774]
Hello everyone,

I do a lot of work in Node Red and have primarily used it to connect my Logo PLCs with Home Assistant.

Node Red no longer runs after the update. It doesn't start anymore. I can no longer access my node red.

Protokoll Node Red:

13 Dec 16:40:19 - [error] [ha-binary-sensor:40EA001 Ausgang Q8] NoConnectionError
13 Dec 16:40:19 - [info] [server:Home Assistant] Connecting to http://supervisor/core
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Ausschaltverzögerung Licht Eingangsbereich Aktualwert] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Ausschaltverzögerung Licht Eingangsbereich Ausschaltverzögerung] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Ausschaltverzögerung Licht Eingangsbereich Restzeit] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Nachlaufzeit nach der AstroUhr Beleuchtung Garten E71.1 Aktualwert] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Nachlaufzeit nach der AstroUhr Beleuchtung Garten E71.1 Ausschaltverzögerung] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Nachlaufzeit nach der AstroUhr Beleuchtung Garten E71.1 Abgelaufende Ausschaltverzögerung] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Nachlaufzeit nach der AstroUhr Beleuchtung Bereich der Werkstatt E41.2+E41.3 Aktualwert] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Nachlaufzeit nach der AstroUhr Beleuchtung Bereich der Werkstatt E41.2+E41.3 Ausschaltverzögerung] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Nachlaufzeit nach der AstroUhr Beleuchtung Bereich der Werkstatt E41.2+E41.3 Restzeit] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor: 40EA001 Astro Uhr E71.1 Verschiebung Sonnenaufgang] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor: 40EA001 Astro Uhr E71.1 Sonnenaufgang] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor: 40EA001 Astro Uhr E71.1 Verschiebung Sonnenuntergang] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor: 40EA001 Astro Uhr E71.1 Sonnenuntergang] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor: 40EA001 Astro Uhr E41.2+3 Verschiebung Sonnenaufgang] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor: 40EA001 Astro Uhr E41.2+3 Sonnenaufgang] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor: 40EA001 Astro Uhr E41.2+3 Verschiebung Sonnenuntergang] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor: 40EA001 Astro Uhr E41.2+3 Sonnenuntergang] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Taster Ausschaltverzögerung E-Bike Ladestation Aktualwert] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Taster Ausschaltverzögerung E-Bike Ladestation Ausschaltverzögerung] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 Taster Ausschaltverzögerung E-Bike Ladestation Restzeit] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 APP HA Ausschaltverzögerung E-Bike Ladestation Aktualwert] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 APP HA Ausschaltverzögerung E-Bike Ladestation Ausschaltzeit] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 APP HA Ausschaltverzögerung E-Bike Ladestation Verbleibende Ausschaltzeit] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 - Taster Schutzschaltung 80AP001 über HA Aktualwert] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 - Taster Schutzschaltung 80AP001 über HA Ausschaltzeit] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 - Taster Schutzschaltung 80AP001 über HA Verbleibende Ausschaltzeit] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 APP HA Schutzschaltung 80AP001 über HA Aktualwert] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 APP HA Schutzschaltung 80AP001 über HA Ausschaltzeit] NoConnectionError
13 Dec 16:40:19 - [error] [ha-sensor:40EA001 APP HA Schutzschaltung 80AP001 über HA Ausschaltzeit] NoConnectionError
13 Dec 16:40:19 - [info] [server:Home Assistant] Connected to http://supervisor/core
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Logo Merker M25] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Logo Merker M26] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Logo Merker M27] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Logo Merker M28] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Logo Merker M29] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Logo Merker M30] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Logo Merker M31] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q1] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q2] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q3] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q4] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q5] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q6] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q7] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q8] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 01] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 02] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 03] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 05] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 06] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 07] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 09] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 10] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 11] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 12] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 04] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Schaltzeituhr Monat 08] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 01] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 02] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 03] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 04] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 05] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 07] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 08] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 09] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 10] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 11] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 12] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Aktiver Monat 06] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q9 Rollladen Auf] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q10 Rollladen Ab] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q11 Rollladen Auf] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q12 Rollladen Ab] InputError: Integration not loaded
13 Dec 16:40:19 - [error] [ha-binary-sensor:30EA001 Ausgang Q13 Rollladen Auf] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Ausgang Q14 Rollladen Ab] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Ausgang Q15 Rollladen Auf] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Ausgang Q16 Rollladen Ab] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Ausgang Q17 Rollladen Auf] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Ausgang Q18 Rollladen Ab] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Ausgang Q19 Rollladen Auf] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Ausgang Q20 Rollladen Ab] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 01] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 02] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 03] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 04] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 05] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 06] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 07] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 08] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 09] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 10] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 11] InputError: Integration not loaded
13 Dec 16:40:20 - [error] [ha-binary-sensor:30EA001 Urlaubssteuerung Monat 12] InputError: Integration not loaded
13 Dec 16:40:21 - [error] [s7 endpoint:00EA001 Logo in 00EF001 EG und Keller] Error: Timeout connecting to the transport
13 Dec 16:50:02 - [error] [s7 endpoint:30EA001 Logo in 30EF001 OG und Dachstudio] Error: Request timeout
13 Dec 16:50:04 - [error] [s7 endpoint:00EA001 Logo in 00EF001 EG und Keller] Error: Request timeout
13 Dec 16:59:07 - [error] [s7 endpoint:00EA001 Logo in 00EF001 EG und Keller] Error: Request timeout
13 Dec 16:59:22 - [error] [s7 endpoint:00EA001 Logo in 00EF001 EG und Keller] Error: Timeout connecting to the transport

I would be happy about a solution as there are many hours of work in my node red.

It is an important part of our company's automation.

Dirk

**Comment by gretel** [comment]
it's because 

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.61.0

which requires `Node-RED version: v3.1.1` but the addon is not that version.

**Comment by DL4DP** [comment]
Thanks for the feedback.

Unfortunately I could no longer access Node Red.

I set up a new computer with Home Assistant and created a backup of the old system.

Then I imported the old backup and Node Red runs without any problems.

Of course I carried out your update.

But Node Red ran correctly on the new system straight away.

I have no idea, it's working again now, thanks!

I think the problem can be considered closed. Although I can't give a correct solution.


Thank you, says Dirk
