### ISSUE TITLE
16.0.2 Node-Red will not start with fresh install

### ISSUE THREAD

**Issue by SurgeHawk** [hassio-addons/addon-node-red#1776]
# Problem/Motivation

> Fresh install oh HA on rPi4b. downloaded Node-Red 16.0.2 from Home Assistant Community Add-ons. Will not start. Logs state missing ssl cert.

## Expected behavior

> Node-Red to start

## Actual behavior

> None-Red fails to start due to missing ssl cert.

## Steps to reproduce

> Fresh install Node-Red and try to start.

## Temp fix

> disabling ssl allows Node-Red to start.

Home Assistant info:
Core 2023.12.3
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

**Comment by sinclairpaul** [comment]
This is a documented feature, with a concise error show in the log when misconfigured, this is not an issue.
