### ISSUE TITLE
Current Behavior Flows stopped due to missing node types

### ISSUE THREAD

**Issue by DL4DP** [hassio-addons/addon-node-red#1779]
Hello everyone,

Now my automation ran for a few days, but now after the next update some things no longer work.

Sometimes the functions are there for a short time and then they are gone again.

Is there a solution?

Flows stopped due to missing node types

server
ha-entity-config
ha-device-config
ha binary sensor
ha sensor
ha-update-config
ha button
api call service
server-state-changed
api-current-state

![Node Red](https://github.com/hassio-addons/addon-node-red/assets/101423128/b2f415b6-4f19-4f76-996c-aa597ba3f57d)

![Node Red Bild 2](https://github.com/hassio-addons/addon-node-red/assets/101423128/9954b5f4-066d-4555-b3b8-9dfdff340f16)

The two images show the state of Node Red after the update

I reset my system to the state before the "Home Assistant Core 2023.12.3" update and everything is working again.

I then updated again to “Home Assistant Core 2023.12.3” and the functions from above are immediately missing in Node Red.

![Node Red Bild 3](https://github.com/hassio-addons/addon-node-red/assets/101423128/f333315b-5615-49df-9ba6-eaf841306421)

I install the web base and then it disappears again, very strange behavior!

In some cases it cannot be installed either.

I now run 2 servers for Home Assistant, one without an update and one with an update.

![Node Red Bild 4](https://github.com/hassio-addons/addon-node-red/assets/101423128/e6a6b129-05fd-461e-ad86-80f97b22304e)

Server without update

![Node Red Bild 5](https://github.com/hassio-addons/addon-node-red/assets/101423128/93c272ac-3981-4bc1-a5f4-c65d4dd463c1)

Everything runs as usual in Node Red

![Node Red Bild 8](https://github.com/hassio-addons/addon-node-red/assets/101423128/6b9b4369-51bf-4919-83d0-28c4acf95d73)

Start websockel 0.62.2 

![Node Red Bild 6](https://github.com/hassio-addons/addon-node-red/assets/101423128/cbd19480-4f7c-4896-8df1-0680462d8914)

After updating to 0.62.2 I am reset to 0.59.0, the update doesn't work.

![Node Red Bild 7](https://github.com/hassio-addons/addon-node-red/assets/101423128/51f7f031-23dd-420a-b560-7caf63307dab)

After restarting Node Red, the web socket will be completely uninstalled.

Then I can reinstall 0.62.2 and Node Red works again.

Somehow you find yourself in an endless loop, sometimes it works and then again it doesn't.

As soon as you close node Red or do something, you grant the functions.

[10:04:55] INFO: Starting NGinx...
16 Dec 10:04:55 - [info] Waiting for missing types to be registered:
16 Dec 10:04:55 - [info]  - server
16 Dec 10:04:55 - [info]  - ha-entity-config
16 Dec 10:04:55 - [info]  - ha-device-config
16 Dec 10:04:55 - [info]  - ha-binary-sensor
16 Dec 10:04:55 - [info]  - ha-sensor
16 Dec 10:04:55 - [info]  - ha-update-config
16 Dec 10:04:55 - [info]  - ha-button
16 Dec 10:04:55 - [info]  - api-call-service
16 Dec 10:04:55 - [info]  - server-state-changed
16 Dec 10:04:55 - [info]  - api-current-state

Dirk wishes you a good start to the weekend

**Comment by ZEi20T** [comment]
im having the exact same issue. also happened when upgrading to 0.62.1

**Comment by tjorim** [comment]
Simple: don't update the node manually. The add-on manages that for you, bundling the correct node-red with the correct node-red-contrib-home-assistant-websocket node. See also previous (closed) issues.

**Comment by DL4DP** [comment]
@ [tjorim](https://github.com/tjorim) 


Thanks for the feedback, but I don't fully understand the answer.

Can you explain it in more detail, thank you!

Thank you Dirk

**Comment by tjorim** [comment]
Add-on comes with node-red-contrib-home-assistant-websocket v0.59.0, don't update it in the palette manager.

**Comment by DL4DP** [comment]
Thanks for the feedback, how do I reinstall the old websocket?

I don't have one anymore and when I search for installation, I'm only offered the new one.

How do I get to the old one to reinstall it?
