### ISSUE TITLE
Hello, since the last update NodeRed it has changed the add-on directory. How is the absolute paht for the write-file-node? i used "verz = "/config/MeineLogs/Meldungen/" but this doesnt seem the absolute, because the relative. I will end up to safe the file in config where the configuration.yaml is. Can anyone help me to get the absolute-path?? thanks

### ISSUE THREAD

**Issue by gotsila** [hassio-addons/addon-node-red#1780]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Use `/homeassistant` instead of `/config` in case you want to write to your Home Assistant configuration folders.
