### ISSUE TITLE
No connection to home assistant anymore / cant update websocket

### ISSUE THREAD

**Issue by realfire23** [hassio-addons/addon-node-red#1781]
# Problem/Motivation

Since the last HA update, I dont have anymore connection to home assistant entities

If I update the palette for the websocket the conection is again established, but due to dependencies Iam unable to run 0.62 of websocket until after the next restart of the nodered addon. As soon as I restart there is a dependency error as the websocket requires node red 3.1.1 but 3.1 is the installed

https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket

[Node.js](https://nodejs.org/) v14.0.0+
[Node-RED](https://nodered.org/) v3.1.1+
[Home Assistant](https://home-assistant.io/) v2023.12+

**Comment by veno77** [comment]
Same issue here!

**Comment by jaytea33** [comment]
We'll have to either wait until the Node-Red add-on is updated or someone needs to fork it as there's already several closed issues on it - see these:

https://github.com/hassio-addons/addon-node-red/issues/1767

https://github.com/hassio-addons/addon-node-red/issues/1773

And follow this to fix it in the interim (worked for me)

https://github.com/hassio-addons/addon-node-red/issues/1774#issuecomment-1854478442

Then when you fix it just make sure NOT to click "Update HA Nodes" even though it's a tempting button, both that and the ha web socket in the Pallet's Nodes section will break it, so just update everything else except the ha web socket and wait for the next update. That's all you can do for now unless you wanna fork it yourself

**Comment by realfire23** [comment]
> We'll have to either wait until the Node-Red add-on is updated or someone needs to fork it as there's already several closed issues on it - see these:
> 
> #1767
> 
> #1773
> 
> And follow this to fix it in the interim (worked for me)
> 
> [#1774 (comment)](https://github.com/hassio-addons/addon-node-red/issues/1774#issuecomment-1854478442)
> 
> Then when you fix it just make sure NOT to click "Update HA Nodes" even though it's a tempting button, both that and the ha web socket in the Pallet's Nodes section will break it, so just update everything else except the ha web socket and wait for the next update. That's all you can do for now unless you wanna fork it yourself

well that fix doesnt really work for me. I didnt update anything except for Home Assistant and node red fails to connect.

**Comment by jaytea33** [comment]
For me the only thing that broke was the HA nodes - the rest of node-red still functioned fine other than that for the non-HA nodes, but I still got the 3.1.1 version error on boot like you did. 

If you can get the service to start and get to the web UI, the fix should work - it's 0.62.2 ha web socket that breaks it, so you just downgrade it to 0.61.1 and as long as you don't update it again, everything should work just as it did.

The other option is to uninstall and then restore from a backup of the node-red addon from before you did the upgrade and if it's functional again, update everything except for the HA web socket. If that doesn't work then idk

**Comment by henriklund** [comment]
What I noticed was that upon entering NodeRed I was informed that the HA nodes had gone. Palette manager offered ability to upgrade (which I did) and everything was OK. Restart NodeRed reverted to same erratic situation (ie. sounds a lot like [issue 1773](https://github.com/hassio-addons/addon-node-red/issues/1773).

As far as I could see there is no downgrade button for packages in the palette manager. I thus had to try to obtain the old version. I am not certain if following is advisable (ie. be warned....**no* warranties and remember to create a backup before). However, it worked for me and I am back on 0.60.1 with a NodeRed that can survive a restart:
- get overview of version by running `curl https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/ > ver.txt`
- find the tarball for v0.60.1 in ver.txt file (hint: it is https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/-/node-red-contrib-home-assistant-websocket-0.60.1.tgz)
- in the NodeRed palette manager (under Install) upload the tgz from URL above.
- check if all is OK (a restart of NodeRed would also be recommended)
Again...while it worked for me, please use at your own risk.

**Comment by adsavia** [comment]
@henriklund thank you - it worked for me. What I did was restart Node-RED so the HA nodes went missing then uploaded the file you pointed to and everything restored as expected and was then able to restart without the nodes disappearing!

**Comment by realfire23** [comment]
> What I noticed was that upon entering NodeRed I was informed that the HA nodes had gone. Palette manager offered ability to upgrade (which I did) and everything was OK. Restart NodeRed reverted to same erratic situation (ie. sounds a lot like [issue 1773](https://github.com/hassio-addons/addon-node-red/issues/1773).
> 
> As far as I could see there is no downgrade button for packages in the palette manager. I thus had to try to obtain the old version. I am not certain if following is advisable (ie. be warned....*_no_ warranties and remember to create a backup before). However, it worked for me and I am back on 0.60.1 with a NodeRed that can survive a restart:
> 
> * get overview of version by running `curl https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/ > ver.txt`
> * find the tarball for v0.60.1 in ver.txt file (hint: it is https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/-/node-red-contrib-home-assistant-websocket-0.60.1.tgz)
> * in the NodeRed palette manager (under Install) upload the tgz from URL above.
> * check if all is OK (a restart of NodeRed would also be recommended)
>   Again...while it worked for me, please use at your own risk.

I did it suggested but now iam having great errors like 

![image](https://github.com/hassio-addons/addon-node-red/assets/26832574/196dec0c-a0bf-49b7-a72d-543167a6e800)

Anyone any suggestions ? :D

**Comment by henriklund** [comment]
Are you **certain** that you used 0.60.1 before you updated the websocket to 0.62.2?

If you have a backup prior to the update to 0.62.2 then either consider restoring that or you can tinker a bit more around:
- _copy_ the backup to a temporary folder
- run a `tar -xvf BACKUPFILE` (where BACKUPFILE is the name of the backup). This will extract the content of the backup. For NodeRed that would be a file like a0d7b954_nodered.tar.gz
- since this is a temp folder; in the same folder run a `tar -xvf a0d7b954_nodered.tar.gz`. The folder content will start to look a bit messy, but we only want to look at the config directory being created
- perform a `cd config` and then a `grep websocket package.json`. The line printed will contain the websocket version. My take would be that you would need to get that version when downgrading.

**Comment by adsavia** [comment]
No - I upgraded from .59 to .62.2 after a recent Home Assistant update. 

What happened was that HA update made my routines with HA nodes stop working (the nodes became blank wireframe placeholders) but I discovered that installing the HA Websocket nodes from the palette manager brought them back. Unfortunately they would not persist over a Node-RED restart. Same symptom - HA nodes appeared as blank wireframe boxes.

After finding your post I restarted again and this time imported the .60.1 package you referenced via the palette manager file module upload feature and it worked. Did not have to use the CLI or anything.  All my routines appear to be working fine even across restarts.. so .60.01 is definitely working. In the palette manager it shows that I can update to .62.2 but am holding off of course.

I hope this makes sense?

**Comment by henriklund** [comment]
@adsavia good to know. My comment was directed at @realfire23. 
After my latest comment I tried running a testbed with 0.59.0 and then upgrading to 0.62.2. It gave all the same symptoms as I saw previously. However, while an install of 0.60.1 also worked in this case, I also noticed that a large amount of nodes started to show an error (the red triangle); jsonata data was (despite being correct) considered erratic. Oddly enough everything was working as expected. I did not redeploy (despite NodeRed strongly suggesting so). After some attempts to figure out what went on (including just restarting NodeRed to see if there were any telltale errors during start), I simply installed a downloaded v0.59.0 and everything was back to normal (ie. no errors). Although the errors seen were different than the ones seen by @realfire23, I still have the suspicion that the incorrect version could play a role.

**Comment by adsavia** [comment]
> @adsavia good to know. My comment was directed at @realfire23. After my latest comment I tried running a testbed with 0.59.0 and then upgrading to 0.62.2. It gave all the same symptoms as I saw previously. However, while an install of 0.60.1 also worked in this case, I also noticed that a large amount of nodes started to show an error (the red triangle); jsonata data was (despite being correct) considered erratic. Oddly enough everything was working as expected. I did not redeploy (despite NodeRed strongly suggesting so). After some attempts to figure out what went on (including just restarting NodeRed to see if there were any telltale errors during start), I simply installed a downloaded v0.59.0 and everything was back to normal (ie. no errors). Although the errors seen were different than the ones seen by @realfire23, I still have the suspicion that the incorrect version could play a role.

Interesting - this morning I just looked at my NR and am getting the same red triangles.. will downgrade to .59 as well.

**Comment by adsavia** [comment]
So upgraded to 0.62.2 via palette manager, restarted NR, nodes were missing as expected, uploaded 0.59.0 via palette manager upload module feature, nodes returned, restarted NR to check and everything was working - no red triangles etc.

Used this file: [https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/-/node-red-contrib-home-assistant-websocket-0.59.0.tgz](url)

Thank you for your assistance, it is much appreciated.

**Comment by frenck** [comment]
# ℹ️ The WebSocket node should not be manually managed, it is bundled in the add-on.

Making manual changes to that, will cause issues in the long run. The add-on will therefore revert those manual changes each start.

I've shipped v17.0.0 just now with everything latest.

../Frenck

**Comment by frenck** [comment]
@cannondale0815 It means you have override it yourself in the pallet (instead of using the built-in shipped version).

Either remove that manual version, or update it yourself in that case 🤷 

../Frenck

**Comment by cannondale0815** [comment]
Frenck, correct, I fell into the same trap as others in this thread where in the past I manually updated it, not knowing this should not be done. Then afterwards I [downgraded manually to 0.59](https://github.com/hassio-addons/addon-node-red/issues/1781#issuecomment-1872087757), hoping this would get me back on track. 

I am looking for ways to properly undo the damage I have done. The palette manager doesn't allow me to uninstall the websocket component, only manually update to 0.62.3, which I don't want to do, because that's what got me into this mess to begin with. Any suggestions how to get back on track for those of us who were too trigger happy in the past? :)

**Comment by revoltadodan** [comment]
I updated my Node Red and I'm also having problems, my HA nodes are broken, I checked in the palette manager and I'm running version 0.62.3 of websocket. I already uninstalled the HA addon and reinstalled it, but it didn't solve the problem.

**Comment by henriklund** [comment]
> I updated my Node Red and I'm also having problems, my HA nodes are broken, I checked in the palette manager and I'm running version 0.62.3 of websocket. I already uninstalled the HA addon and reinstalled it, but it didn't solve the problem.

So you upgraded to v17.0.0 and now nodes are broken? If that is the case, I think you need to create a separate issue on this subject as this one is related to websockets failing due to manual upgrade of WebSocket in the palette managerr. Secondly, did you create a backup before the update and have you considered restore?

**Comment by revoltadodan** [comment]
> 
> So you upgraded to v17.0.0 and now nodes are broken? If that is the case, I think you need to create a separate issue on this subject as this one is related to websockets failing due to manual upgrade of WebSocket in the palette managerr. Secondly, did you create a backup before the update and have you considered restore?

It was updated to v17.0.1 and websocket 0.62.3, both were updated automatically, I already restored the backup, uninstalled and reinstalled NodeRed and nothing resolved

![Node 0](https://github.com/hassio-addons/addon-node-red/assets/95450097/ffb4d956-f9a9-4202-8698-c5a003b362db)
![node 1](https://github.com/hassio-addons/addon-node-red/assets/95450097/8149a046-36e7-4fa7-b6d4-d72e3b2c02bd)
![Node](https://github.com/hassio-addons/addon-node-red/assets/95450097/59957d91-0e5a-4014-bc05-7ff7342cd8ea)

**Comment by henriklund** [comment]
Since this issue is already closed, I suggest you open a new issue on this matter. Please include the log as this may provide additional insights.
