### ISSUE TITLE
I cannot install a contrib because it requires a newer version of NodeJS. Can I update it?

### ISSUE THREAD

**Issue by pstaszko** [hassio-addons/addon-node-red#1784]
# Is it possible to update the NodeJS version that Node-Red uses on Home Assistant?
I'm trying to install @gregoriusrippenstein/node-red-contrib-introspection 0.5.5 and it fails with this information:
  Required: {"node":">=20"}
  Actual:   {"npm":"9.6.6","node":"v18.18.2"}

I have ssh access to my home assistant instance which is running on a VM Ware VM. I poked around and couldn't find node or node-red. I'm a Windows guy so I'm a bit unclear where to find things.

**Comment by frenck** [comment]
We can't, as NodeJS 20 cannot be built at this moment in time, due to a bug in QEMU.

../Frenck
