### ISSUE TITLE
Error on Service Call Nodes on 17.0.0

### ISSUE THREAD

**Issue by darthrater78** [hassio-addons/addon-node-red#1789]
I replaced a node this morning with a new plug, and now I get this when deploying. Everything seems to work fine, but now the node has a warning on the label as well.

![3df4f4d532a8dfcf8ec7ae61eb3421887781cede.png](https://github.com/hassio-addons/addon-node-red/assets/94141126/6cd955e3-2ea4-417b-b318-812aaf4efb6b)

![60bab31ee62922e047d1f799a0dda9f64937eef5.png](https://github.com/hassio-addons/addon-node-red/assets/94141126/93ea8735-88c7-43b5-a9d3-c1858a93e78b)

![6043d41c9bfc242362074c51105a00dcb5265446.png](https://github.com/hassio-addons/addon-node-red/assets/94141126/2d0ab96f-5489-4c8e-a2b8-a1b58567e475)

Using NR via Add-on with HAOS, on latest 2014 version.

**Comment by tempus2016** [comment]
Me also.  On the latest version too.

**Comment by frenck** [comment]
Hi there!

This issue seems to be specific to the Home Assistant node for Node-RED, not the add-on.
Please report this issue upstream here: <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>

../Frenck

**Comment by darthrater78** [comment]
@frenck I was just about to do this when I noticed the Home Assistant node for Node-RED was ABSURDLY out of date. Like version 2.x something. 

I updated it from the palette manager and the errors went away. I had no idea that updating NR didn't also update the nodes themselves!  

TIL.

**Comment by frenck** [comment]
> I updated it from the palette manager and the errors went away. I had no idea that updating NR didn't also update the nodes themselves!

You should not need it from the pallet manager, it is shipped built-in into the add-on (and also updated with it). By installing it manually, you override the built-in.

**Comment by tempus2016** [comment]
I can confirm that manually updating also fixed it for me.

**Comment by darthrater78** [comment]
> > I updated it from the palette manager and the errors went away. I had no idea that updating NR didn't also update the nodes themselves!
> 
> You should not need it from the pallet manager, it is shipped built-in into the add-on (and also updated with it). By installing it manually, you override the built-in.

Interesting.  I've been using HA for what five years now and never updated the pallet manually for the HA node before. It was on 2.x something. 


Any way I can restore the automatic nature of it?

**Comment by frenck** [comment]
Removing the node from the pallet should be enough, as it is built-in into the add-on, it should just be there again after restart.

(Make a backup of the add-on before doing that, just to be sure).

**Comment by darthrater78** [comment]
> Removing the node from the pallet should be enough, as it is built-in into the add-on, it should just be there again after restart.
> 
> (Make a backup of the add-on before doing that, just to be sure).

I'll try that, thanks for the guidance.
