### ISSUE TITLE
error with json variabile

### ISSUE THREAD

**Issue by guegiurm** [hassio-addons/addon-node-red#1792]
# Problem/Motivation:
Hello, I have noticed that there are considerable problems with the 'call service' node. What happened is that before the update when passing json variables of type {{msg.payload}} it would take its value whereas now it returns an error: InputError: Invalid JSON:  
Why can't the JSON value be supplied?

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by martinsheldon** [comment]
I'm doing the same as you in the Service Call node but I use this without the "msg." at the beginning of the variable.
Maybe you can try that?

![image](https://github.com/hassio-addons/addon-node-red/assets/64303842/79b0a855-418f-4fb5-9d74-0f03bac145b6)

**Comment by guegiurm** [comment]
I only tried with {{payload}} but it gives me the same error.I attach some photosGiuseppeIl giorno 8 gen 2024, alle ore 18:03, martinsheldon ***@***.***> ha scritto:﻿
I'm doing the same as you in the Service Call node but I use this without the "msg." at the beginning of the variable.
Maybe you can try that?
image.png (view on web)

**Comment by tanker11** [comment]
Hello, same here.
{"message":"{{payload}}"}
format helps but is it the correct one? Should I correct everywhere from {{msg.payload.data}}?
I have almost a hundred nodes like this!

**Comment by VOSsec** [comment]
https://github.com/hassio-addons/addon-node-red/assets/129999011/61c851d4-7960-458d-a3aa-b7d8543ad10d

Unfortunately I have the same problem. When I create a call service (no matter which one), it requires a data code (json) every time. If I leave the data code empty, I get an API error when executed. No additional data code is required for the call service update...
