### ISSUE TITLE
After update node-red won't start

### ISSUE THREAD

**Issue by Salsalove** [hassio-addons/addon-node-red#1794]
Hassio on RPi 

![image](https://github.com/hassio-addons/addon-node-red/assets/44812056/4f8ab016-4ef1-40af-9651-26c77302288e)

![image](https://github.com/hassio-addons/addon-node-red/assets/44812056/e212a19c-2e8b-462b-9b4a-3fcaa804b460)

Any solutions?

**Comment by frenck** [comment]
Duplicate of #1791

Please check for existing issue before creating new ones. Thanks! 🙏 

../Frenck
