### ISSUE TITLE
After Node-red update (17.0.0) it won't start

### ISSUE THREAD

**Issue by Salsalove** [hassio-addons/addon-node-red#1795]
After the automatic update i can't start the add-on...

![image](https://github.com/hassio-addons/addon-node-red/assets/44812056/5e7117f8-c612-4328-9e8e-6ce1bb2b764c)

![image](https://github.com/hassio-addons/addon-node-red/assets/44812056/4c400363-b042-4a2b-9d55-8920302f9073)

**Comment by scubabas** [comment]
downgrade to 16.0.2 worked for me as a workaround

**Comment by Salsalove** [comment]
> downgrade to 16.0.2 worked for me as a workaround

Thank u...but I solved with 17.0.2 (last update)
