### ISSUE TITLE
On 17.0.1, Alexa Event Node not working

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [hassio-addons/addon-node-red#1797]
# Problem/Motivation

> Alexa Event node not working

## Expected behavior

> Alexa must accept voice command for HA

## Actual behavior

> No event arriaves in HA

## Steps to reproduce

> Update 17.0.1

## Proposed changes

> Fix.
> What I found is every single files disaappears in /config/node-red/. That empty.
 > So that seems system cannot find AlexaCookie.txt

**Comment by Mitchell-kw-Lee** [comment]
The version everything working fine is 15.1.1. Nothing others.
With the node-red 15.1.1, any of OS or Core or Node-red Companion updates combination are works.

**Comment by frenck** [comment]
This is the same issue as #1743
