### ISSUE TITLE
[Feature request] Node Update Notification

### ISSUE THREAD

**Issue by jf-64** [hassio-addons/addon-node-red#1798]
# Problem/Motivation
Node Red's UI  shall give out some visual notification, if for some of the installed (custom) nodes an update is available.
> (Why the issue was filed)
User shall be able to timely apply updates to (custom) nodes without manually polling the Palette Manager.
## Expected behavior
User of Node Red get a notification about the availability of an update. Then the user can manually do the update in the Palatte Manager.
> (What you expected to happen)
Node Red (or some internal unit of it) shall check out the availability of update for each installed node in the Palette Manager - at least once every day. If an update is available, then e.g. a button (e.g. "Node update available") shall appear, if the user clicks on it, then a short description will describe,  what (s)he has to/can do (which includes not to do the update). 
## Actual behavior
Currently the user have to check out (poll) by hand all installed nodes in Palette Manager wther or not an update is available.
> (What actually happened)
n/a
## Steps to reproduce
n/a
> (How can someone else make/see it happen)
n/a
## Proposed changes
The best place for the visual notification would be black area left of the Deploy button.
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
n/a

**Comment by frenck** [comment]
Thanks for your suggestion, but that is not within the scope of the add-on.

../Frenck
