### ISSUE TITLE
Memory issue after upgrading to v17.0.x

### ISSUE THREAD

**Issue by ofladby** [hassio-addons/addon-node-red#1806]
# Problem/Motivation

After upgrading from v16.0.2 to 17.0.x the addon won't start, just keeps retrying.
I manually pulled and ran 16.0.2 again just to see if it would run at all, and it does. The system has plenty of free memory and I've tried increasing the 'max_old_size_space' value as well without any improvement. Tried both in safe_mode and not in safe mode. Tried uninstalling and installing the addon and removing the config folder manually.

## Actual behavior

[12:21:37] INFO: Setting safe mode startup
[12:21:37] INFO: Starting Node-RED...

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --safe --settings /etc/node-red/config.js

16 Jan 12:21:41 - [info] 

Welcome to Node-RED
===================

16 Jan 12:21:41 - [info] Node-RED version: v3.1.3
16 Jan 12:21:41 - [info] Node.js  version: v18.19.0
16 Jan 12:21:41 - [info] Linux 6.1.63-haos-raspi arm64 LE
16 Jan 12:21:43 - [info] Loading palette nodes
16 Jan 12:21:43 - [debug] Module: @node-red-contrib-themes/theme-collection 3.1.8 /opt/node_modules/@node-red-contrib-themes/theme-collection
16 Jan 12:21:43 - [debug] Module: node-red-contrib-bigtimer 2.8.5 /opt/node_modules/node-red-contrib-bigtimer
16 Jan 12:21:43 - [debug] Module: node-red-contrib-cast 0.2.17 /opt/node_modules/node-red-contrib-cast
16 Jan 12:21:43 - [debug] Module: node-red-contrib-counter 0.1.6 /opt/node_modules/node-red-contrib-counter
16 Jan 12:21:43 - [debug] Module: node-red-contrib-home-assistant-websocket 0.62.3 /opt/node_modules/node-red-contrib-home-assistant-websocket
16 Jan 12:21:43 - [debug] Module: node-red-contrib-influxdb 0.7.0 /opt/node_modules/node-red-contrib-influxdb
16 Jan 12:21:43 - [debug] Module: node-red-contrib-interval-length 0.0.6 /opt/node_modules/node-red-contrib-interval-length
16 Jan 12:21:43 - [debug] Module: node-red-contrib-modbus 5.27.2 /opt/node_modules/node-red-contrib-modbus
16 Jan 12:21:43 - [debug] Module: node-red-contrib-moment 5.0.0 /opt/node_modules/node-red-contrib-moment
16 Jan 12:21:43 - [debug] Module: node-red-contrib-persistent-fsm 1.2.1 /opt/node_modules/node-red-contrib-persistent-fsm
16 Jan 12:21:43 - [debug] Module: node-red-contrib-sunevents 3.1.1 /opt/node_modules/node-red-contrib-sunevents
16 Jan 12:21:43 - [debug] Module: node-red-contrib-time-range-switch 1.2.0 /opt/node_modules/node-red-contrib-time-range-switch
16 Jan 12:21:43 - [debug] Module: node-red-dashboard 3.6.2 /opt/node_modules/node-red-dashboard
16 Jan 12:21:43 - [debug] Module: node-red-node-base64 0.3.0 /opt/node_modules/node-red-node-base64
16 Jan 12:21:43 - [debug] Module: node-red-node-email 2.1.0 /opt/node_modules/node-red-node-email
16 Jan 12:21:43 - [debug] Module: node-red-node-feedparser 0.3.0 /opt/node_modules/node-red-node-feedparser
16 Jan 12:21:43 - [debug] Module: node-red-node-ping 0.3.3 /opt/node_modules/node-red-node-ping
16 Jan 12:21:43 - [debug] Module: node-red-node-random 0.4.1 /opt/node_modules/node-red-node-random
16 Jan 12:21:43 - [debug] Module: node-red-node-serialport 2.0.2 /opt/node_modules/node-red-node-serialport
16 Jan 12:21:43 - [debug] Module: node-red-node-smooth 0.1.2 /opt/node_modules/node-red-node-smooth
16 Jan 12:21:43 - [debug] Module: node-red-node-suncalc 1.1.0 /opt/node_modules/node-red-node-suncalc
16 Jan 12:21:43 - [debug] Module: node-red-node-twitter 1.2.0 /opt/node_modules/node-red-node-twitter
16 Jan 12:21:44 - [info] Node-RED Contrib Theme Collection version: v3.1.8

<--- Last few GCs --->
0.5 ms, walltime since start of marking 57 ms) (average mu = 0.978, current mu = 0.785) finalize incrementa[1594:0x7fbee54030]     4719 ms: Mark-sweep 22.8 (55.5) -> 21.1 (56.7) MB, 13.5 / 0.1 ms  (+ 7.1 ms in 35 steps since start of marking, biggest step 0.5 ms, walltime since start of marking 102 ms) (average mu = 0.959, current mu = 0.813) finalize incremen[1594:0x7fbee54030]     6193 ms: Scavenge 42.7 (61.6) -> 32.1 (61.2) MB, 13.1 / 0.0 ms  (average mu = 0.959, current mu = 0.813) allocation failure; 

<--- JS stacktrace --->

FATAL ERROR: DateTimePatternGeneratorCache::CreateGenerator Allocation failed - process out of memory
[12:21:47] INFO: Service Node-RED exited with code 256 (by signal 6)

**Comment by ofladby** [comment]
With 17.0.5 this issue is gone

**Comment by Stefano201** [comment]
I have some issues with newest versions. How did u pulled a previous version? Unfortunately I don't have a backup. 

Thanks
