### ISSUE TITLE
RequestError: connect ECONNREFUSED on HTTPs Endpoint

### ISSUE THREAD

**Issue by Barrow1990** [hassio-addons/addon-node-red#1808]
# Problem/Motivation
Trying to complete a HTTPs API endpoint (https://api.octopus.energy/v1/products/)

## Expected behavior

To pull in a json object hosted at https://api.octopus.energy/v1/products/

## Actual behavior

Error From Node:
`RequestError: connect ECONNREFUSED 127.0.0.1:443`

Error Outputted from node:
`{"_msgid":"753da48dc9aac9c4","payload":"RequestError: connect ECONNREFUSED 127.0.0.1:443 : https://api.octopus.energy/v1/products/","topic":"","statusCode":"ECONNREFUSED"}`

## Steps to reproduce

On Home Assistant Supervisor
Install Node Red Add On
Add the Following Nodes:
`[{"id":"eb279dade5872de3","type":"inject","z":"6621fa84f1eddc16","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":420,"wires":[["3ef69765e5707a40"]]},{"id":"bc3bb33cbf35ea0d","type":"debug","z":"6621fa84f1eddc16","name":"debug 15","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":480,"y":420,"wires":[]},{"id":"3ef69765e5707a40","type":"http request","z":"6621fa84f1eddc16","name":"","method":"GET","ret":"obj","paytoqs":"ignore","url":"https://api.octopus.energy/v1/products/","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":310,"y":420,"wires":[["bc3bb33cbf35ea0d"]]}]`

### **Note:**
Installed via Node Red Docker-compose and works fine with the above workflow

## Proposed changes
Unknown

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Barrow1990** [comment]
Also to add both the Home Assistant and Node Red docker-compose are on x86_64

**Comment by borpin** [comment]
Me too trying to access https://crt.sh/

Moved the flow off this NR instance and it worked fine. 

Standard HAOS install on a Blue with the addon.
