### ISSUE TITLE
Sudden change of entity name

### ISSUE THREAD

**Issue by driagi** [hassio-addons/addon-node-red#1828]
# Problem/Motivation
Some entities created in node red have changed their name to HA. For example sensor.nr_stufetta_totale has become sensor.stufetta_totale. The variables that have changed names are those Class State -> Total

> (What you expected to happen)
Keep the same name

## Steps to reproduce
I can't reproduce this by creating a new entity. The problem occurred when switching from Core 2024.1.3 to 2024.2.0
Node-Red 17.0.6

![Cattura](https://github.com/hassio-addons/addon-node-red/assets/74871092/299a71f3-a0d4-4283-95bd-4c099c5f9c51)
![Cattura2](https://github.com/hassio-addons/addon-node-red/assets/74871092/6c8fdef1-5fde-4f3b-a122-532e29d815c7)

**Comment by driagi** [comment]
Could it be a Node-red companion problem?

**Comment by driagi** [comment]
Once the entities were recreated, they changed names again. Being an entity on the Energy board, I cannot change my name.

**Comment by frenck** [comment]
The add-on doesn't create entities. The companion node-red integration could, but that isn't managed by this add-on/project.

Please create an issue upstream with them.
