### ISSUE TITLE
Node-RED Companion Integration Button Not Displayed After Home Assistant Reboot

### ISSUE THREAD

**Issue by BMWfan** [hassio-addons/addon-node-red#1829]
# Problem/Motivation
After installing the Node-RED Companion via HACS and subsequently integrating it into Home Assistant, I expected to see the Node-RED button on the left side of the panel after rebooting Home Assistant.

## Expected behavior

Upon rebooting Home Assistant, I anticipated seeing the Node-RED button on the left side of the panel.

## Actual behavior

However, no button is displayed.

**Comment by frenck** [comment]
I think you are mixing up things. This is not the companion integration. This is the repository for the add-on. Add-ons and integrations are not the same thing.

If you want to show the add-on in the sidebar, enable the "Show in sidebar" toggle in the add-on configuration panel.

../Frenck
