### ISSUE TITLE
Suggestion : Add option to integrate an existing external Node-red instance into HASS, instead of a new Node-Red container

### ISSUE THREAD

**Issue by glecoz** [hassio-addons/addon-node-red#1838]
# Problem/Motivation

I have an existing Node-Red instance on another RPi.
It would be nice if we could just point this addon to an existing Node-red URL (optionnaly with credentials) instead of getting a new instance.

I know I could re-import all my existing Node-red flows and plugins, but I only use HASS as a front-end on purpose, all my HA backend code (Node.js / PHP microservices) is through MQTT calls <-> Node-Red <-> HASS,  to remain loosely coupled to one or more front-ends, and I don't want to lose critical Node-red access (temp / motion sensors, wall switches,etc...) if my HASS instance gets broken for some reason. 

But having all monitoring interfaces accessible **also** from HASS is relevant (Loki / Grafana for log management, Node-Red...).

## Expected behavior

Addon Install Option A : as is (new Node-Red instance)
Addon Install Option B : only set existing Node-red url + username + password on this addon config files.

**Comment by frenck** [comment]
This is not in scope of this add-on.

This add-on contains Node-RED itself.

../Frenck
