### ISSUE TITLE
Web Interface is not reachable with DuckDNS & Trusted Networks and NGINX

### ISSUE THREAD

**Issue by CMDR-Sloma** [hassio-addons/addon-node-red#184]
I’m running in circles trying to get my Hassio inside Proxmox running. I have pretty much basic setup with DuckDNS, NGINX Proxy, Mosquitto and Node RED addons. I tried without DuckDNS and NGINX earlier and it was working. As soon as I setup DuckDNS addon it breaks NodeRED after restart. Something must have changed since 0.89 (last version I was running OK) that breaks it. Since I can’t restore my backup from RPI3 I need to set it up from scratch with the latest version of HA but I'm stuck with it.

I can reach my Hassio from the following locations:

    locally from 192.168.1.7:8123
    externally from my duckdns address

No matter what I do I just can’t open Node RED Web Interface

My Hassio config looks like this:

    ###################################################
    #                                                 #
    #     Home Assistant Main Configuration File      #
    #                                                 #
    ###################################################

    homeassistant:
      name: !secret name
      temperature_unit: C
      time_zone: !secret timezone
      latitude: !secret latitude
      longitude: !secret longitude
      elevation: 38
      unit_system: metric
      auth_providers:
        - type: legacy_api_password
          api_password: !secret api_password
        - type: trusted_networks
          trusted_networks:
             - 192.168.1.0/24
             - 172.30.0.0/16
      customize: !include customize.yaml
      whitelist_external_dirs:
      - /share
    
    # Configure a default setup of Home Assistant (frontend, api, etc)
    default_config:
    
    # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
    http:
      base_url: !secret hassio_address

    # Discover some devices automatically
    discovery:
    
    # Sensors
    sensor:
      # Weather prediction
      - platform: yr
    
    # Text to speech
    tts:
      - platform: google
    
    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    
Here is my Node Red Addon config and the Log:

    {
      "credential_secret": "!secret node_red_credential",
      "dark_mode": false,
      "http_node": {
        "username": "",
        "password": ""
      },
      "http_static": {
        "username": "",
        "password": ""
      },
      "port": 1880,
      "ssl": true,
      "certfile": "fullchain.pem",
      "keyfile": "privkey.pem",
      "require_ssl": true,
      "system_packages": [],
      "npm_packages": [],
      "init_commands": []
    }

My Hassio System Log:

    19-04-08 13:17:27 INFO (MainThread) [hassio.core] Hass.io is up and running
    19-04-08 13:17:34 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
    19-04-08 13:17:34 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
    19-04-08 13:17:34 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
    19-04-08 13:17:34 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
    19-04-08 13:17:52 INFO (MainThread) [hassio.auth] Auth request from a0d7b954_nodered for redacted
    19-04-08 13:17:52 WARNING (MainThread) [hassio.auth] Wrong login from redacted
    19-04-08 13:18:09 INFO (MainThread) [hassio.auth] Auth request from a0d7b954_nodered for redacted
    19-04-08 13:18:09 WARNING (MainThread) [hassio.auth] Wrong login from redacted
    19-04-08 13:18:18 INFO (MainThread) [hassio.auth] Auth request from a0d7b954_nodered for redacted
    19-04-08 13:18:18 WARNING (MainThread) [hassio.auth] Wrong login from redacted

And Home Assistant log:

    2019-04-08 13:17:15 WARNING (MainThread) [homeassistant.components.http.auth] legacy_api_password support has been enabled.
    2019-04-08 13:17:16 ERROR (MainThread) [homeassistant.components.device_tracker] Unable to load /config/known_devices.yaml: Config file not found: /config/known_devices.yaml
    2019-04-08 13:17:52 ERROR (MainThread) [homeassistant.components.hassio.auth] Can't find Home Assistant auth.
    2019-04-08 13:18:09 ERROR (MainThread) [homeassistant.components.hassio.auth] Can't find Home Assistant auth.
    2019-04-08 13:18:18 ERROR (MainThread) [homeassistant.components.hassio.auth] Can't find Home Assistant auth.
    2019-04-08 13:18:49 WARNING (MainThread) [homeassistant.components.http.view] Access from trusted networks without auth token is going to be removed in Home Assistant 0.96. Configure the trusted networks auth provider or use long-lived access tokens to access /api/services/script/turn_on from 172.30.33.2

I don’t know how to resolve this, I have wasted three days trying to find solution online without success. When I check config it’s OK.

Any help?

**Comment by CMDR-Sloma** [comment]
Sorry forgot to include this line from my System log:
    19-04-08 14:07:31 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].

**Comment by SurfingSpider** [comment]
I also have a similar problem after updating to v3. I use duckdns in a rpi running hassio. everything was working as it should before upgrade to v3. 

I understand that the panel_iframe will stop working because you are now using ingress. but if I click on the "open web UI" button in the hassio addons it doesn't load the page properly  you just get a black banner at the top with node-red logo and the rest of the screen is black. 

However I managed to find the iframe_src path (using chrome inspect panel). https://192.168.0.40:8123/api/hassio_ingress/2OMvmiepvsgOZ24cA6l-svXw8YPfEcB5Tt8LY3DQToM/#flow/99f658fc.380f08

If I change that to my local ip address instead of my duckdns host name it works (after accepting browser security warnings).

Any Ideas?

**Comment by frenck** [comment]
@CMDR-Sloma 

Add `homeassistant` to the auth methods:

```yaml
auth_providers:
    - type: homeassistant
```

**Comment by CMDR-Sloma** [comment]
Thx Frenck, that did it.

**Comment by frenck** [comment]
Glad we got that resolved @CMDR-Sloma! Thanks for letting me know 👍
