### ISSUE TITLE
What's happening with this addon?

### ISSUE THREAD

**Issue by Salsalove** [hassio-addons/addon-node-red#1857]
Despite the latest updates, node-red is causing serious instability issues.
Sometimes it won't start, causing reebots...or, if it's working, it causes websocket api errors, timeout on call errors with system freeze 3-4 times in an hour or reebots.
I'm frustraited, and I don't understand why this still happens after 2 months and various updates and why nobody can give an explanation or a solution.

Can someone investigate? Node-red is unusable

**Comment by frenck** [comment]
I think you are experiencing issues with the node module for Home Assistant by your description? If so, please report the issue with that node. The add-on (this repository) wraps and packages existing software, it doesn't create it.

../Frenck
