### ISSUE TITLE
node status disappeared with 3.0 upgrade

### ISSUE THREAD

**Issue by papperone** [hassio-addons/addon-node-red#186]
# Problem/Motivation

> I upgraded add-on to 3.0 and despite NodeRed seems to work all node status disappeared

## Expected behavior

> Node status is crucial and important to check flows and debug them eventually

## Actual behavior

> all nodes have no more the status line, I tried to disable and enable it again in the settings but no changes

## Steps to reproduce

> upgrade the addon to 3.0

## Proposed changes

> Please revert all broken features at wokring state...
> as well NodeRed is not loading properly using the old ULR (myip:1880)

**Comment by Swiftnesses** [comment]
Also seeing this. It also broke my reverse proxy, which I'm looking into :(

**Comment by MTrab** [comment]
+1 on this issue.
Node status is enabled under settings, but not showing.

**Comment by Swiftnesses** [comment]
I actually have my reverse proxy working again (restarted web server and enabled the port option in the node red add-on config screen), statuses seem to update fine.

The issue I have is that like reported, the statuses don't work on the ingress screen and the login screen no longer works when accessing node red via IP:port like it did before (now I just get a basic http auth login box).

**Comment by Swiftnesses** [comment]
BTW, the reason statuses don't work via reverse proxy and the ingress page is because the wss port tries to connect via the reverse proxy address.

Error in console:

WebSocket connection to 'wss://xxx/api/hassio_ingress/7aJ5wfr0bWUz3Hp0hGWqZy8gHEgDAOZ0o3KMprhE_3Q/comms' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1

Not sure why the UI login page is broken via IP:port though....

**Comment by Swiftnesses** [comment]
You guys can get statuses for now via your local HA IP if it's accessible, i.e:

http://xxx:8123

I think you'll find status works there!?

**Comment by MTrab** [comment]
Can't get the reverse proxy up and running.
But I can confirm the status part is working by directly accessing the local IP.

**Comment by Swiftnesses** [comment]
@MTrab make sure you've enabled port 1880 under the config setting on the node red config page... It's off by default after the update (or was for me). You'll need to stop and start after...

**Comment by MTrab** [comment]
I have always had a **"port": 1880,** line in my config - and still have - still no access to port 1880.

**Comment by Swiftnesses** [comment]
I did too, but for some reason I had to remove it, save, and then add it via the config options below the main options box. I then restarted and reverse proxy was up again (also restarted my web server, serving the reverse proxy).

**Comment by MTrab** [comment]
Just noticed the Network config had the port disabled - when entering 1880 in there that - partly - fixed the problem.
Now I'm only not able to log in - it just hangs at the auth prompt even when entering correct credentials.

Accessing IP:1880 directly works like intended.

**Comment by papperone** [comment]
confirmed for me as well, accessing IP:1880 after enable port access status are restored...

**Comment by helto4real** [comment]
I can confirm that it works with IP address. Alsoe the debug output works now with IP, its gone using full qualified name.

**Comment by MTrab** [comment]
Node status not working when using Node-RED in ingress mode.

**Comment by daniel-matthews** [comment]
I have the same. Also there are no longer debug messages from Debug Nodes. It seems the two are related as both of these occur in Ingress, but they are working just fine in the old interface.

**Comment by frenck** [comment]
Just released add-on v3.0.1, which requires Home Assistant 0.91.4, which addresses this issue with this add-on.

Don't get me wrong, there are still issues with Ingress, but the WebSocket connect that makes these statuses work, have been fixed.
