### ISSUE TITLE
Node-Red Install on HomeAssistant Green

### ISSUE THREAD

**Issue by AlanEisen** [hassio-addons/addon-node-red#1860]
# Problem/Motivation

> I installed Node-Red on HomeAssistant Green (HAG). It seemed to install correctly, but after starting the log showed an SSL error and the SSL certfile wasn't recognized. I turned off SSL and was able to start without a problem (but haven't done anything with it yet. 
Running: 
Core - 2024.3.2
Supervisor - 2024.03.0
Operating System - 12.1
Frontend - 20240307.0

## Expected behavior

> Expected to run without error

## Actual behavior

> The SSL certfile wasn't recognized and the add-on closed.

## Steps to reproduce

> Install on HAG and run.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> The SSL certfile wasn't recognized and the add-on closed.

Where did you store your SSL certificate? And how did you create one?

**Comment by AlanEisen** [comment]
I didn't have one; the default install assumed that I did, and prefilled the options field. That was the "problem."

**Comment by frenck** [comment]
That is not a problem. The default settings are "secure by default" out of the box.

If you wish to lower that, go ahead 👍 

../Frenck
