### ISSUE TITLE
Still trying to connect to the duckdns address even though I no longer have it

### ISSUE THREAD

**Issue by juanpa669** [hassio-addons/addon-node-red#1861]
# Problem/Motivation

I deleted duckdns and all instances of my https://xxxxx.duckdns.org addresses. I uninstalled duckdns and use zerotier instead. I have uninstalled and reinstalled node-red several times but when I start it, it always tries to connect to the duckdns address and marks that it fails to connect to mqtt://192.168.1.254:1883

## Expected behavior

I would like it to be able to connect to the mqtt server

## Actual behavior

The mqtt nodes do not connect to broker

In the logs:
 [info] [mqtt-broker:138aac1868d658bf] Connection failed to broker: mqtt://192.168.1.254:1883
 [info] [server:Home Assistant] Connecting to https://xxxxxx.duckdns.org

## Steps to reproduce

No idea

## Proposed changes

No

**Comment by sinclairpaul** [comment]
The error for the duckdns address isn't related to the mqtt error.

I would guess you may have configured a separate server configuration for the Home Assistant nodes referencing the address.

As for the MQTT error, ensure it is running correctly and check the logs from your MQTT instance.

**Comment by juanpa669** [comment]
Thank you for your response which was able to direct me to the configuration errors I had made.

**Comment by juanpa669** [comment]
Thank you

**Comment by juanpa669** [comment]
Thank you for your response which was able to direct me to the configuration errors I had made.
