### ISSUE TITLE
remove user and password for http node

### ISSUE THREAD

**Issue by jwende** [hassio-addons/addon-node-red#1862]
# Problem/Motivation

I need a callback via HTTP_IN but can't provide user/password

## Expected behavior

callback without authentication 

## Actual behavior

callback fails 

## Steps to reproduce

deploy a HTTP_IN node with any /path and point your browser to this URL ((http://homeassistant:1880/path)

## Proposed changes

allow anonymous connections to node red

**Comment by sinclairpaul** [comment]
Please see the note in the documentation <https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-http_node>

You need to use `http://homeassistant:1880/endpoint/path`

**Comment by jwende** [comment]
That means I can't use http nodes in the add-on configuration only with authentication?
So I need switch back to plain node-red.
