### ISSUE TITLE
Can't access node-red via reverse proxy

### ISSUE THREAD

**Issue by foux** [hassio-addons/addon-node-red#1863]
# Problem/Motivation

I'm trying to access my Node-Red addon via a reverse proxy. FOr that I point my reverse proxy to http://my.ha.ip:1880. But when accessing this URL (via or without my reverse proxy), I'm greated by a password/login popup, when I defined none in my configuration.

What are those default passwords?

Thanks
## Expected behavior

Access to my Node-Red page

## Actual behavior

Access to a login popup
## Steps to reproduce

Go to http://ha.ip:1880

**Comment by frenck** [comment]
> What are those default passwords?

There are no defaults. Log in with your HA account.

../Frenck
