### ISSUE TITLE
Where to store attributes.csv for victron-modbus

### ISSUE THREAD

**Issue by 1984ozone1984** [hassio-addons/addon-node-red#1865]
# Problem/Motivation

Attributes field of Victron-modbus node remains empty.

<img width="482" alt="Bildschirmfoto 2024-03-30 um 11 57 08" src="https://github.com/hassio-addons/addon-node-red/assets/114089236/389c02f0-f65b-4639-9eea-efe54b95c67e">

[https://flows.nodered.org/node/node-red-contrib-victron-modbus]

Event thought attributes.csv is int addon_config folder

<img width="739" alt="Bildschirmfoto 2024-03-30 um 11 58 51" src="https://github.com/hassio-addons/addon-node-red/assets/114089236/6f9d21a4-6c42-4ea2-9fff-6fccac60ce26">

## Expected behavior

Attributes filled:

![](https://raw.githubusercontent.com/dirkjanfaber/node-red-contrib-victron-modbus/master/doc/img/editpanel.png)

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Sorry, that node isn't developed or used here. You'd probably should ask the creator of that node instead.

../Frenck
