### ISSUE TITLE
No access to IP:1880 in version 3.0

### ISSUE THREAD

**Issue by MTrab** [hassio-addons/addon-node-red#187]
# Problem/Motivation

I have Node-Red implemented in iFrame, this is no longer working after upgrade to version 3.0.
Node-Red can't be accessed thru port 1880 any longer.

## Expected behavior

Node-Red answering proberly to requests on port 1880 (or any other port for that matter) so it can be integrated in iFrame

## Actual behavior

No access to port 1880.

## Steps to reproduce

Upgrade to version 3.0

## Proposed changes

Fix access to port 1880

**Comment by thecode** [comment]
Same problem here, not only iFrame, port 1880 is closed

**Comment by frenck** [comment]
That is the solution. More details are released soon on the Home Assistant website.

**Comment by MTrab** [comment]
Only login doesn't work when in panel_iframe.

Also mentioned here: https://github.com/hassio-addons/addon-node-red/issues/186
