### ISSUE TITLE
Call Service node error with Input Boolean Domain

### ISSUE THREAD

**Issue by daviss57** [hassio-addons/addon-node-red#1874]
Entity Fields disapear in Call Service node when Domain "Input_Boolean" and a service of Toggle, Turn_on or Turn_off is chosen.

When I went to edit an existing Call Service node I noted that I could not change the Area, Device or Entity as they are not shown.

See snips below of blank Service Node and after I select Input Boolean.

Has anyone seen this behaviour before?

![2024-04-15_08h45_39](https://github.com/hassio-addons/addon-node-red/assets/65281157/6d361b30-523c-4de7-9418-b5f29c9d2343)
![2024-04-15_08h46_04](https://github.com/hassio-addons/addon-node-red/assets/65281157/2d669195-183d-48c6-b651-e6a68c4f2100)

**Comment by tjorim** [comment]
The add-on does not influence the nodes provided. For support with this one specifically, please go to https://github.com/zachowj/node-red-contrib-home-assistant-websocket.
