### ISSUE TITLE
Service, Area and device desapear for switch

### ISSUE THREAD

**Issue by Tanjohnson99** [hassio-addons/addon-node-red#1875]
Hello,

Why Service, Area and device desapear for switch ?
![Captura de ecrã 2024-04-18 104253](https://github.com/hassio-addons/addon-node-red/assets/97446509/37f7b86c-0f2e-416c-99f0-d5d0caffa11f)

Thanks

**Comment by tjorim** [comment]
No idea but this is out of scope for the add-on, we just pre install the node for convenience. For support with it, please go to https://github.com/zachowj/node-red-contrib-home-assistant-websocket.
