### ISSUE TITLE
After update, Node-Red cant start.

### ISSUE THREAD

**Issue by IkaSGC** [hassio-addons/addon-node-red#1876]
# Problem/Motivation

> Impossible start Node-Red

## Expected behavior

> Start Node-Red

## Actual behavior

> Wont start due to error

## Steps to reproduce

> None

## Proposed changes

> None

Error: 

`Welcome to Node-RED
===================

21 Apr 12:18:43 - [info] Node-RED version: v3.1.9
21 Apr 12:18:43 - [info] Node.js  version: v18.20.2
21 Apr 12:18:43 - [info] Linux 6.6.25-haos x64 LE
21 Apr 12:18:44 - [info] Loading palette nodes
21 Apr 12:18:45 - [info] Dashboard version 3.6.5 started at /endpoint/ui
21 Apr 12:18:45 - [warn] ------------------------------------------------------
21 Apr 12:18:45 - [warn] [node-red-hxtx-ftp/ftp] 'ftp in' already registered by module node-red-contrib-ftp-beta
21 Apr 12:18:45 - [warn] ------------------------------------------------------
21 Apr 12:18:45 - [info] Settings file  : /etc/node-red/config.js
21 Apr 12:18:45 - [info] Context store  : 'default' [module=memory]
21 Apr 12:18:45 - [info] User directory : /config/
21 Apr 12:18:45 - [warn] Projects disabled : editorTheme.projects.enabled=false
21 Apr 12:18:45 - [info] Flows file     : /config/flows.json
21 Apr 12:18:45 - [info] Server now running at http://127.0.0.1:46836/
21 Apr 12:18:45 - [info] Starting flows
21 Apr 12:18:45 - [info] Started flows
[12:18:45] INFO: Starting NGinx...
21 Apr 12:18:50 - [info] [server:Home Assistant] Connecting to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connecting to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connecting to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connecting to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connecting to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connected to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connected to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connected to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connected to http://supervisor/core
21 Apr 12:18:50 - [info] [server:Home Assistant] Connected to http://supervisor/core
21 Apr 12:19:05 - [red] Uncaught Exception:
21 Apr 12:19:05 - [error] Error: Timeout while connecting to server
    at Timeout._onTimeout (/config/node_modules/ftp/lib/connection.js:304:24)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[12:19:05] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[12:19:05] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by tjorim** [comment]
Seems out of scope for the add-on. Rather an issue with the FTP node you set up. Enable `safe_mode` and fix the flow.

**Comment by IkaSGC** [comment]
The error was somewhere in HA, but I have no idea where. The whole HA started behaving unstable. Some add-ons could not be started. Node-Red started and was available, but when I clicked on the add-on in settings, it said it was not running and could not be started, but all NR tasks were still running. Other add-ons could not be started at all.
The same thing happened after restoring from a backup. Only restoring from a backup to a new clean installation helped.
