### ISSUE TITLE
Web UI login screen broken on 3.0.0

### ISSUE THREAD

**Issue by Swiftnesses** [hassio-addons/addon-node-red#188]
After updating, the builtin web ui login is broken. It now just shows a basic auth popup box instead.

Further, no user menu is shown once logged in via the box.

See:

<img width="279" alt="Screenshot 2019-04-15 at 09 18 13" src="https://user-images.githubusercontent.com/1001877/56117175-71f62780-5f5f-11e9-928d-188f7c3a9cb3.png">

This works fine on a standalone install, so unlikely a Node red issue:

<img width="266" alt="Screenshot 2019-04-15 at 09 18 21" src="https://user-images.githubusercontent.com/1001877/56117202-7de1e980-5f5f-11e9-9ab2-d71b0d33c6e2.png">

**Comment by frenck** [comment]
This is expected. Node-RED login has been replaced with HA Authentication, which allows automatic authentication when using Ingress.

**Comment by Swiftnesses** [comment]
What about those that use Ingress and other deployments at the same time?

**Comment by MTrab** [comment]
But when integrating non-ingress in panel_iframe login is broken and not working.

**Comment by Swiftnesses** [comment]
This seems a little close minded, but I love this addon, so will find a way to restore the original functionality (I used the login to capture info!).
