### ISSUE TITLE
Help please my node red has crashed

### ISSUE THREAD

**Issue by sfdiaz1** [hassio-addons/addon-node-red#1881]
Hi,

I need to see if someone can give me a hand.
After installing several things in node red, it looped and closed, as a result I have not been able to reopen it. 

I have tried uninstalling and reinstalling it several times but to no avail. It's like when I reinstall it, all the flows and nodes that caused the error are still there.

Does anyone know how to uninstall and redo a clean install starting from scratch.

Attached is a screenshot in case it could be helpful.

Thanks

![Node Red](https://github.com/hassio-addons/addon-node-red/assets/42835995/010ba772-bccc-4014-b9c8-6978e25b3254)

**Comment by frenck** [comment]
This is an issue with the Tuya Cloud SDK node. Please report the issue with them (as the exception isn't caught).

You can start Node-RED in safe mode, as documented here:

<https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-safe_mode>

In which you can disable/remove/clean up the error and next restart with the option turned off again to resume normal operations.

../Frenck

**Comment by sfdiaz1** [comment]
Thank you very much Frenck, but when I put it in safe mode and hit save I get an error.

![Node Red](https://github.com/hassio-addons/addon-node-red/assets/42835995/2f07761a-c19e-403a-9b6c-cf2a837c0645)

**Comment by sfdiaz1** [comment]
Good afternoon Frenck,
I have put it in safe mode, but I can't get it to start.
![Node RED](https://github.com/hassio-addons/addon-node-red/assets/42835995/2f362e63-ffd1-4734-84e2-843277f98e88)
![Node Red1](https://github.com/hassio-addons/addon-node-red/assets/42835995/916fe357-1403-4d9a-ac9b-75ac6e2e31cd)
