### ISSUE TITLE
[info] [server:Home Assistant] Connecting to http://supervisor/core

### ISSUE THREAD

**Issue by hoebanx** [hassio-addons/addon-node-red#1886]
# Problem/Motivation

> I dont have any entry in node-red in my home assistant 

## Expected behavior

> get my entities available

## Actual behavior

> logs shows only '[server:Home Assistant] Connecting to http://supervisor/core' again and again

## Steps to reproduce

> no idea, I tried with a friend, it is working well on his HA

## Proposed changes

![2024-05-31 17_03_20-Home Assistant](https://github.com/hassio-addons/addon-node-red/assets/77239440/7937d368-b163-4995-b0a9-da2bb7f5b4f7)
![2024-05-31 17_04_26-10CS-0021683 Structure  - PDF-XChange Editor](https://github.com/hassio-addons/addon-node-red/assets/77239440/a9075f3f-fe7a-4594-b746-4730f5c72f04)
![2024-05-31 17_04_38-Home Assistant](https://github.com/hassio-addons/addon-node-red/assets/77239440/0fb2b89b-fa0b-4976-b75a-dfaca15dc313)
![2024-05-31 17_05_42-Home Assistant](https://github.com/hassio-addons/addon-node-red/assets/77239440/f300c3fe-1c5e-4952-9d45-8594f8517d61)

**Comment by hoebanx** [comment]
for info:

Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1
Node-RED Companion v4.0.0
Node-RED Current version: 17.0.12

**Comment by olibos** [comment]
I've tried to help @hoebanx  without success. 
Do you need more information to diagnose this issue?

**Comment by corpsell** [comment]
> I've tried to help @hoebanx without success. Do you need more information to diagnose this issue?

I am having the same issue. Can provide more info as requested as this is critical for serveral automations for me. What can I provide to help solve this?

**Comment by corpsell** [comment]
@olibos to add more information:
- Existing automations still trigger
- node red log reports `3 Jul 23:44:21 - [info] [server:Home Assistant] Connecting to http://supervisor/core` repeatedly
- 'Inject' node broken (cant click)
- new entities are not pulling into node edit UI, nor are 'actions' or 'domains' under 'call service' node as an example.

**Comment by hoebanx** [comment]
Hello,
I though I solved the problem creating a new HA server
![image](https://github.com/hassio-addons/addon-node-red/assets/77239440/81948168-a6fa-4769-834a-ea30835d36e2)
It work better now, I have all my entities for state events
![image](https://github.com/hassio-addons/addon-node-red/assets/77239440/53f2e120-dca2-4011-a11e-b2023e31ab92)
Unfortunately I still have nothing for 'call service'
![image](https://github.com/hassio-addons/addon-node-red/assets/77239440/ac79d117-c276-48aa-95b9-2d50ff04fffc)
Best regards,
L.

**Comment by corpsell** [comment]
> Hello, I though I solved the problem creating a new HA server ![image](https://private-user-images.githubusercontent.com/77239440/345934962-81948168-a6fa-4769-834a-ea30835d36e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMTYzNzMsIm5iZiI6MTcyMDIxNjA3MywicGF0aCI6Ii83NzIzOTQ0MC8zNDU5MzQ5NjItODE5NDgxNjgtYTZmYS00NzY5LTgzNGEtZWEzMDgzNWQzNmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIxNDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNWZhYWJkYzdlZWIxNzI2MmU3OGM1MTE3OTMxYzNlZTFhN2Q0ODNkZjc2MDBjMmU5MTZjYzNjZDI1ODdlZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BeKGrn_B16M8C1orwjeBb_x3009oI3OpgQ9q2HcUgrI) It work better now, I have all my entities for state events ![image](https://private-user-images.githubusercontent.com/77239440/345935181-53f2e120-dca2-4011-a11e-b2023e31ab92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMTYzNzMsIm5iZiI6MTcyMDIxNjA3MywicGF0aCI6Ii83NzIzOTQ0MC8zNDU5MzUxODEtNTNmMmUxMjAtZGNhMi00MDExLWExMWUtYjIwMjNlMzFhYjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIxNDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNWM3ZmQ3YjRkNWRlY2U5NDEyNDZjYTkxYWEyNmIyYTVmZTc1MjcwZmJkNzlkNTBhOTRkMzllNjRmODgyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sbxc1z7wfg6nnVpa8Bdm6WrZI8ftOvBfJ7fylpIYmtk) Unfortunately I still have nothing for 'call service' ![image](https://private-user-images.githubusercontent.com/77239440/345935371-ac79d117-c276-48aa-95b9-2d50ff04fffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMTYzNzMsIm5iZiI6MTcyMDIxNjA3MywicGF0aCI6Ii83NzIzOTQ0MC8zNDU5MzUzNzEtYWM3OWQxMTctYzI3Ni00OGFhLTk1YjktMmQ1MGZmMDRmZmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIxNDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OTBiMWQ2YzA3Y2Q5NjQ5YWZkZmU4MDhhNmJjZDFmOTY0OTMyZDI5ZmQ0ZTY2YWQ1MTEzNmY2NzA2OTYzYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qKZGJ5cJ8JXzRPRFFGxGtMvKQD6u6FrZdsaOi0gNvRE) Best regards, L.

Same here, and there is no listed 'last ran' information under the nodes anymore. I was tinkering today and somehow managed to get everything pulling properly for a moment, but on the next reboot it is back to broken.
1. Only entities pull, not actions, domains, etc.
2. Only have one server for homeassistant within node red
3. When I was able to get everything working including the 'last ran' status under each node (for the brief moment mentioned above), I only removed a link to a specific link to stop my lights from turning on at sunrise. I've since relinked and removed the link but it has not re-fixed anything.

Any thoughts?

**Comment by corpsell** [comment]
@hoebanx See what is going on over here: https://github.com/hassio-addons/addon-node-red/issues/1898

Disabling SSL fixed it for me.
- Go to settings/add-ons/nodered/configuration/ 
- click the three dots and edit yaml
- change both SSL entries to false
- Save and restart node red

**Comment by hoebanx** [comment]
Hello corpsell,
Thanks a lot, it works!
