### ISSUE TITLE
3.0 horror: keeps asking for password

### ISSUE THREAD

**Issue by Slayerrulez** [hassio-addons/addon-node-red#189]
# Problem/Motivation

> Can't login on the web interface

## Expected behavior

> fill out user/pass --> success

## Actual behavior

> Keeps asking for password, no error

## Steps to reproduce

> I do not know, just installing the new version?

## Proposed changes

> Please make it work again, 2.0.1 was fine.

**Comment by frenck** [comment]
Try again with a better subject.
Please provide logs.

**Comment by Slayerrulez** [comment]
My config;

{
  "credential_secret": "<justmysecret>",
  "dark_mode": false,
  "http_node": {
    "username": "<username>",
    "password": "<password>"
  },
  "http_static": {
    "username": "<username>",
    "password": "<password>"
  },
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": false,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": [],
  "log_level": "info"
}

**Comment by MTrab** [comment]
+1
