### ISSUE TITLE
Create sensors, switches and other nodes for HA in NR.

### ISSUE THREAD

**Issue by sdavides** [hassio-addons/addon-node-red#1902]
### Describe the bug

I can no longer add new entities, I don’t see it in the sensor “Entity congif” menu.
I had never seen “none”.

I also tried with the "+" button but the screen doesn't change.

### Screenshots

![342080387-79e4fda2-a8ea-4655-90bc-840a8a32c551](https://github.com/hassio-addons/addon-node-red/assets/31100253/12ea8e5d-68cf-4e0e-a758-d517ce6cf7cb)

### Environment Information

NodeRed version: 18.0.0

HA
Core 2024.6.4
Supervisor 2024.06.0

**Comment by sdavides** [comment]
I reverted to the old version 17.0.13 (nodered 3).
With version 18 (nodered 4) I didn't understand how to do it.

**Comment by frenck** [comment]
> I can no longer add new entities, I don’t see it in the sensor “Entity congif” menu.
> I had never seen “none”.

That is not an add-on issue, but an issue with either the Home Assistant node or the Home Assistant companion integration for Node-RED.

Both are not created or maintained in this repository. Please report this issue with the upstream projects instead.

../Frenck
