### ISSUE TITLE
can't find a way to disable ingress

### ISSUE THREAD

**Issue by GrandadEvans** [hassio-addons/addon-node-red#192]
# Problem/Motivation

Hey, Frenck. Loving the work and thank you. After updates to a few of your add-ons, I've not been able to use my proxies (which are through the NGINX addon) due to the ingress feature. I'm only partially sure of what this is by looking at the commits etc just now.
The point is that in the code that I've looked at I can see several checks to see if HA authentication is disabled, but I can't see any way to disable ingress and/or go back to the old port numbers.

## Expected behavior

I might have expected a config entry to bypass the ingress feature and go to the old port number (although I realize that this would then not be passed in the port binding box below and so I don't know what the result of that is)

## Actual behavior

The port binding box (or whatever you call it) only shows port 80 and says that the binding is not needed in ingress mode

## Steps to reproduce

Open up an affected addon, such as Node-RED, and try and find a way to enable the old port forwarding

## Proposed changes

Is there a way to add a check to see if a config option has been entered indicating that it then should revert to the old way of mirroring the port numbers by default? Again, I'm not sure, and that's why I'm posing it as a question.
I must be one of the 1st to upgrade, as I cannot imagine that I am the only person that this effects.
Thanks again.

John/Grandad/HASSCASTS

**Comment by frenck** [comment]
I gave an answer on the Portainer add-on which applies to here as well:

<https://community.home-assistant.io/t/community-hass-io-add-on-portainer/68836/53?u=frenck>

**Comment by GrandadEvans** [comment]
That solved it. I love that you can also access the addons from the sidebar in remote as well now. Thanks again for your work :-)
