### ISSUE TITLE
Fields disappear (Call Service node)

### ISSUE THREAD

**Issue by hassos246** [hassio-addons/addon-node-red#1922]
# Problem/Motivation

> When using Call Service node with domain switch the fields area, device and entity disappears when using services toggle or turn_off

## Expected behavior

> I expect the fields stated above not to disappear.

## Actual behavior

> The fields disappear.

## Steps to reproduce

> Create a Call service node. Select domain Switch. Select turn_off or toggle

## Proposed changes

> 

## Screenshots 
<img width="508" alt="Service turn_on" src="https://github.com/user-attachments/assets/538dacdb-859a-4024-8f27-19ffd6a66d8a">
<img width="508" alt="Service toggle" src="https://github.com/user-attachments/assets/9efb9bda-1bd7-4e09-b9a3-db7a778da56a">
<img width="508" alt="Service turn_off" src="https://github.com/user-attachments/assets/37b32390-e072-49b2-b8e2-36737b5350e8">

**Comment by lucode** [comment]
Had the same problem, but can't remember what exactly was the cause. Did you check if you more than one Home Assistant Configuration nodes? That might be related. I renamed mine to "Home Assistant ok" to be aware if a node uses a different one. More than 3 will slow down the interface dramatically.
![image](https://github.com/user-attachments/assets/1a9f2400-6af9-4ebf-ab3c-cda7c6f686ff)

**Comment by hassos246** [comment]
I only have one server in node red.

**Comment by daviss57** [comment]
Same issue here, cant update any nodes.

**Comment by ndoggac** [comment]
Oops, filed separate issue before seeing this one.  Seeing the same thing.  Even my old nodes are affected.  Nodes I know referenced items by device name are not showing them.

**Comment by ndoggac** [comment]
Surprised this issue has been allowed to stick around for going on 2 months.  This is a major bug.

**Comment by ndoggac** [comment]
See the discussion linked below.  Apparently this is not the right place for this issue??  Unhelpful responses there....so where is the proper location?  I looked within the core repository with no luck.  

Not all of us have a working knowledge of the code base in order to know the correct location to submit a bug.  Realize devs may get frustrated with us pleebs, but the community is trying to help ID this (in my opinion anyway) significant bug.  Can confirm the HASS core update to 2024.9.3 this morning did not fix this issue.

https://github.com/hassio-addons/addon-node-red/discussions/1678

**Comment by ndoggac** [comment]
ok, tried posting a new issue here.  https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1600

I updated all the palettes in NR as well.  still no fix.  In the new palette the "call service" node is now called "action".  even creating a new action node, adding a device (which is also a new mechanism +), and then selecting the "Action" from the dropdown, the items still disappear.

**Comment by sinclairpaul** [comment]
One thing you might want to validate is if the issue exists using the default theme, and gathering data via the Browser Console.
