### ISSUE TITLE
Deployment of changes slow and not possible

### ISSUE THREAD

**Issue by tobik176** [hassio-addons/addon-node-red#1929]
# Problem/Motivation

I recognized that I am not able to deploy node-red changes sometimes... It never stops loading...
Sometimes it works but takes a loooong time...
Is there probably an issue with any new home assistant update?

## Expected behavior

Usually, it just takes some seconds to deploy changes

## Actual behavior

Now it starts loading but never completes the deployment of the changes or it takes very long

![image](https://github.com/user-attachments/assets/349101d1-0162-4dfa-b173-0e1289e57501)

## Steps to reproduce

It's probably a problem with a new HA or node-red update, so I don't know.

## Home Assistant Version

Core
2024.8.2

Supervisor
2024.08.0

Operating System
13.0

## Node-Red Add-On Version

Current version: 18.0.5 

## Node-Red Companion Version

Current version: 4.0.2

**Comment by LiquidBlackNL** [comment]
I have the same problem since the last NR update. Both in Firefox and Chrome (both latest versions).
In the end the deploy often works but it takes much longer than before.

**Comment by temasnick** [comment]
Did you install any bluetooth proxy devices on your homeassistant instant recently?
I am playing with bermuda integration/esphome ble proxy and i think issue started after that.

And i find something like this... https://www.reddit.com/r/homeassistant/comments/yqwre3/node_red_got_really_slow/

**Comment by tobik176** [comment]
No, I did not install any bluetooth proxy devices. I tried now again and now it worked but it took some minutes to deploy.

**Comment by jstaro** [comment]
So I noticed this too a few days ago. Talked to my brother who could see the same thing on his setup. Spent the day trying different clients (11 different devices in total) and scratching our heads.

We are both running HA on Proxmox.

It seems almost random regarding the client used, but very consistent results with those clients.

On Android it is always instant and works beautifully, but on different Windows clients (wireless, hardwired), we experienced different delays ranging from 30 seconds to up to 5 minutes. I even have a Windows 10 client that consistently fails w/ 502 Gateway Timeout after 95 seconds using Firefox, but using Chromium, it works after waiting about 3 minutes and 20 seconds. I have one laptop that chugged along trying to deploy for over 7 minutes before I gave up waiting.

Another computer (Win 11 this time) connected to the same network switch takes 20 seconds to deploy.

A Linux client worked fine.

It's only deploys that are taking ages to complete; node-red flows works fine. Memory pressure and CPU usage is not excessive either.

No errors in the node-red addon log, not with debug level set either.

I think, but am not entirely sure, that this started happening after the 13.0 HA Operating System update and not the latest node-red.

I have yet to try to downgrade to HAOS 12.4.

It is all very strange.

**Comment by temasnick** [comment]
I think i found the issue. When i connect to node red from external url (cloudflare tunnel) deploy time is normal (like 1-2 seconds). But when i connect fron local ip (192.168.xxx.xxx) deploy process lasts couple of minutes.

I think my android app/ ipad app work normal because it is connecting with cloudflare tunnel.

**Comment by jstaro** [comment]
FWIW, when I've been testing the Android app, it's been on the local Wi-Fi (same VLAN even), so I am not tunneling and it still works great.

I just tried disconnecting my phone from Wi-Fi and tunneling via WireGuard on 4G and that also works fine for me.

**Comment by badanka** [comment]
I have the same issue. Five different clients, all connected on the same network and accessing HA via local IP address directly (no VPN/tunnel or mDNS). No Bluetooth units anywhere in my setup/network. Android phone and one of my PCs still work great, three other PCs with different operating systems started acting up at the same time. Using ethernet or wi-fi does not seem to matter at all, neither does choice of browsers. I have no idea how to test this further to get any useful debugging tips.

I'm also leaning towards the HA OS update to 13.0 being the culprit, though I'm not entirely sure.

**Comment by 335iguy** [comment]
This happened to me on a Windows client.
Went from 2024.6.4 to 2024.7.4 and updated Node-Red from 18.0.3 to 18.0.5. When I went to make some changes this same issue is occurring.

I reverted back to a snapshot I had taken previously (remember kids, snapshot and backup before making big changes, never know when you'll need either..and snapshot is NOT a backup!) and the same issue happened. Core was on 2024.6.4 and NR was 18.0.3.

For the sake of "have you tried turning it off and on again", I rebooted the client and wiped cache, cookies, and data from the primary browser. Private/Incognito is also affected.

**Comment by dfludwig** [comment]
Another data point:   After making a simple change to one node, Deploy-Modified-Nodes took 2 seconds to complete when connected Ethernet-Desktop-Linux Mint-Firefox, and 120 seconds to complete when making the same change connected Ethernet-Desktop-Windows 11-Firefox.  Running NR 18.0.5 addon on HA 2024.8.2.

**Comment by 335iguy** [comment]
The common point here is that it seems to be affecting Windows clients when accessing NR.
My Manjaro instance on my laptop and desktop work without issue.

**Comment by dfludwig** [comment]
Woot - fixed for me as well.  Thanks!

**Comment by jstaro** [comment]
Super! Verified here on my end too. Perhaps it was the virtio kernel update mentioned in this [issue](https://github.com/home-assistant/operating-system/issues/3528) after all.
