### ISSUE TITLE
PANIC: unprotected error in call to Lua API

### ISSUE THREAD

**Issue by fabiangl** [hassio-addons/addon-node-red#193]
# Problem/Motivation
node-red won't start.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

Welcome to Node-RED
===================

15 Apr 20:57:56 - [info] Node-RED version: v0.20.5
15 Apr 20:57:56 - [info] Node.js  version: v10.14.2
15 Apr 20:57:56 - [info] Linux 4.20.2-aml-s905 arm64 LE
15 Apr 20:57:58 - [info] Loading palette nodes
15 Apr 20:58:03 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
15 Apr 20:58:05 - [info] Settings file  : /etc/node-red/config.js
15 Apr 20:58:05 - [info] Context store  : 'default' [module=memory]
15 Apr 20:58:05 - [info] User directory : /config/node-red/
15 Apr 20:58:05 - [warn] Projects disabled : editorTheme.projects.enabled=false
15 Apr 20:58:05 - [info] Flows file     : /config/node-red/flows.json
15 Apr 20:58:05 - [info] Server now running at http://127.0.0.1:46836/
[20:58:05] INFO: Starting NGinx...
15 Apr 20:58:05 - [info] Starting flows
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is, unfortunately, an upstream issue with Alpine Linux (the operating system the add-on runs).
There is not much I can do, except for waiting.

**Comment by fabiangl** [comment]
Ok. The addon version before 3.0 was working.  How can I install that version?
-

**Comment by frenck** [comment]
closing in favor of dupe #199
