### ISSUE TITLE
Issue after updatimg

### ISSUE THREAD

**Issue by guedini** [hassio-addons/addon-node-red#1941]
After the last update I started getting an issue on some entities.

This node requires [Node-RED custom integration version 1.3.0+ ](https://github.com/zachowj/hass-node-red) to be installed in Home Assistant for it to function.

All my automations that use number or text are not working anymore. All of them showing the message above.

Not sure how to solve it. Haven't found anything googling the message.

**Comment by guedini** [comment]
I'm also getting the error NoConnectionError for all entities when I run any flow.

**Comment by sinclairpaul** [comment]
Then you need to update the Custom Component you have installed, that you linked in the issue
