### ISSUE TITLE
Function trigger node please add time last triggered and current delay value display when active

### ISSUE THREAD

**Issue by adey** [hassio-addons/addon-node-red#1944]
# Problem/Motivation

Function trigger node shows the blue box below the node when active but does not provide details on last time triggered and the delay value it was triggered with. Please see picture below. I can see the node delay is active but not when hit was activated or what delay value was set using msg.delay.

## Expected behavior

When active display last time node was triggered and the delay value it was triggered with, next to the active indicator.

## Actual behavior

It only displays the active indicator for the node but nothing else.

## Steps to reproduce

Trigger the node.

## Proposed changes

There is currently no indication of when this node was last triggered or what delay value it was triggered with, making debugging issues less intuitive.

<img width="135" alt="image" src="https://github.com/user-attachments/assets/61d67142-49c8-4e71-9cab-d74a238f3521">

**Comment by tjorim** [comment]
This is a default node red node which does not have that functionality.
