### ISSUE TITLE
Nodered api problem finding entities e.g. sun.sun

### ISSUE THREAD

**Issue by Slayerrulez** [hassio-addons/addon-node-red#195]
# Problem/Motivation

> Nodered does not find all entities within home assistant, this problem arises in my case with "call service" and "curent state" node.

## Expected behavior

> Finding entity without problems

## Actual behavior

> entity could not be found in cache for entity_id: sun.sun

## Steps to reproduce

> Make use of the sun above or below horizon or create a custom group entity. I made one for my outside lights (hue).

## Proposed changes

> It worked in 2.0.1, so one more bug to get rid of

**Comment by Slayerrulez** [comment]
Debug message;

"entity could not be found in cache for entity_id: sun.sun, sending empty payload"

**Comment by frenck** [comment]
Cannot reproduce:

![image](https://user-images.githubusercontent.com/195327/56223484-22eae800-606e-11e9-9ac5-61ce63303b90.png)

Could you send me a basic flow that doesn't work?

**Comment by SurfingSpider** [comment]
I have seen this problem. when you do a full deploy it seams to take 10-15 seconds to connect properly to HA. if I inject before that I see the issue with Check current state nodes. after a short time it sorts itself out. Dont think it happened like that in previous versions.

**Comment by Slayerrulez** [comment]
@frenck I send you an email with an example flow which does not work.
@SurfingSpider Sadly enough, it still does not work.

**Comment by Slayerrulez** [comment]
Strange, now it seems to work without errors. I am going to change the naming of the node just to get a new deployment.

**Comment by Slayerrulez** [comment]
@frenck I am going to close this one, it automagically works again.
