### ISSUE TITLE
Device & Area entries disappear

### ISSUE THREAD

**Issue by ndoggac** [hassio-addons/addon-node-red#1953]
![Image1](https://github.com/user-attachments/assets/86367e74-da05-4451-9f4e-d88e20d03715)
# Problem/Motivation
Device & Area entries disappear when editing node's values.  On NR v18.0.5.

Even my old flows are affected.  Nodes I know have device entries in them, and I cannot see them.

## Expected behavior
Device & Area entries do not disappear when editing.

## Actual behavior
Device & Area entries disappear when editing node's values.

## Steps to reproduce
create a new "call service" node.  Entries for area, device, and entity exist.  

Change Domain to "zwave_js", all three entries still exist.  

Change Service to "multicast_set_value" and the entries for area & device disappear.  Entity remains.

....

Edit old nodes that you know have things referenced by device name, realize the device entry area does not show up.

**Comment by ndoggac** [comment]
Sorry.  Duplicate of #1922.  But that issue thread has been around since Aug 9!!  This is a major bug, surprised it's been allowed to stick around this long.

**Comment by sinclairpaul** [comment]
Duplicate therefore closing.
