### ISSUE TITLE
Cannot pick a select-entity in action node when using select.select_option.

### ISSUE THREAD

**Issue by gust4vsson** [hassio-addons/addon-node-red#1954]
# Problem/Motivation

> I cannot pick/choose a select-entity, in the action node when using action scope: select.select_option.
> Input_select works as intended, where I can select an input_select-entity, but not the select-entities.
> In my situation I have a heat pump integration which has a select-entity, from which I can select to run the heat pump to heat house, heat water, cooling, combined functions etc. It's just a regular select-entity.
> Everything is up to date here in my end.

## Expected behavior

> I expected when choosing the select functions in the action node, to allow me to pick a select-entity that should be affected by the select functions.

## Actual behavior

> Entity-picker doesnt show up / gets removed when action picked is one of the select-functions.

## Steps to reproduce

> Create an action node, in action select "select.select_option".

## Proposed changes

> Make it possible to select a select-entity when using select actions.

**Comment by magne74** [comment]
I have the same issue.

**Comment by jeremeyi** [comment]
same here

**Comment by daviss57** [comment]
Same here

**Comment by JJ00-dk** [comment]
Same problem for me 👎
