### ISSUE TITLE
Z2M button not working with cover in 18.1.1

### ISSUE THREAD

**Issue by dacorde** [hassio-addons/addon-node-red#1959]
# Problem/Motivation

After update, when I click any Z2M button, covers do not work, and depuration says "InputError: Invalid action format: close" or "InputError: Invalid action format: open".
If I am back to 18.0.5, it works again.

This is my flow:
`[{"id":"ece33bf80ac280df","type":"api-call-service","z":"a62ce2271b426433","name":"","server":"48b45fa.b45a2a","version":7,"debugenabled":false,"action":"cover.set_cover_position","floorId":[],"areaId":[],"deviceId":[],"entityId":["cover.cortina_david_z2m"],"labelId":[],"data":"{\"position\":91}","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"cover","service":"set_cover_position","x":1050,"y":60,"wires":[[]]},{"id":"ac9966810cc036e1","type":"api-call-service","z":"a62ce2271b426433","name":"","server":"48b45fa.b45a2a","version":7,"debugenabled":false,"action":"cover.close_cover","floorId":[],"areaId":[],"deviceId":[],"entityId":["cover.cortina_david_z2m"],"labelId":[],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"cover","service":"close_cover","x":630,"y":240,"wires":[[]]},{"id":"323f0c03ff339fed","type":"api-call-service","z":"a62ce2271b426433","name":"","server":"48b45fa.b45a2a","version":7,"debugenabled":false,"action":"cover.stop_cover","floorId":[],"areaId":[],"deviceId":[],"entityId":["cover.cortina_david_z2m"],"labelId":[],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"cover","service":"stop_cover","x":630,"y":300,"wires":[[]]},{"id":"6374b78728577a70","type":"counter","z":"a62ce2271b426433","name":"","init":"0","step":"1","lower":"","upper":"2","mode":"increment","outputs":1,"x":580,"y":100,"wires":[["c994438ab1cad5d9"]]},{"id":"c994438ab1cad5d9","type":"switch","z":"a62ce2271b426433","name":"press count","property":"count","propertyType":"msg","rules":[{"t":"eq","v":"1","vt":"num"},{"t":"eq","v":"2","vt":"num"}],"checkall":"true","repair":false,"outputs":2,"x":730,"y":100,"wires":[["ece33bf80ac280df"],["875d2194832285aa","76b6bbccc467e188"]]},{"id":"ea9332da39770345","type":"change","z":"a62ce2271b426433","name":"Reset","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":710,"y":180,"wires":[["6374b78728577a70"]]},{"id":"f29a924eb4925272","type":"trigger","z":"a62ce2271b426433","name":"","op1":"","op2":"0","op1type":"nul","op2type":"str","duration":"30","extend":true,"overrideDelay":false,"units":"s","reset":"","bytopic":"all","topic":"topic","outputs":1,"x":570,"y":180,"wires":[["ea9332da39770345"]]},{"id":"875d2194832285aa","type":"change","z":"a62ce2271b426433","name":"Reset","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":930,"y":180,"wires":[["6374b78728577a70"]]},{"id":"76b6bbccc467e188","type":"api-call-service","z":"a62ce2271b426433","name":"","server":"48b45fa.b45a2a","version":7,"debugenabled":false,"action":"cover.stop_cover","floorId":[],"areaId":[],"deviceId":[],"entityId":["cover.cortina_david_z2m"],"labelId":[],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"cover","service":"stop_cover","x":1010,"y":120,"wires":[[]]},{"id":"e6a178b8572db0bb","type":"zigbee2mqtt-in","z":"a62ce2271b426433","name":"TRÅDFRI estor David","server":"3bb5b18df6db5014","friendly_name":"TRADFRI estor David (E1766)","device_id":"0x680ae2fffe3b859e","state":"0","outputAtStartup":true,"filterChanges":false,"enableMultiple":false,"x":100,"y":200,"wires":[["2e600aee347ed66c"]]},{"id":"2e600aee347ed66c","type":"switch","z":"a62ce2271b426433","name":"switch click type","property":"payload.action","propertyType":"msg","rules":[{"t":"eq","v":"open","vt":"str"},{"t":"eq","v":"close","vt":"str"},{"t":"eq","v":"stop","vt":"str"}],"checkall":"false","repair":false,"outputs":3,"x":340,"y":200,"wires":[["6374b78728577a70","f29a924eb4925272"],["ac9966810cc036e1"],["323f0c03ff339fed"]]},{"id":"48b45fa.b45a2a","type":"server","name":"HomeAssistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true},{"id":"3bb5b18df6db5014","type":"zigbee2mqtt-server","name":"Z2M-MQTT","host":"192.168.XX.XXX","mqtt_port":"1883","mqtt_username":"yyyyyyy","mqtt_password":"aeiou1234","mqtt_qos":"0","tls":"","usetls":false,"base_topic":"zigbee2mqtt"}]`

**Comment by gregolin** [comment]
The same here.
