### ISSUE TITLE
This addon is not available on your system.

### ISSUE THREAD

**Issue by Wafje** [hassio-addons/addon-node-red#196]
# Problem/Motivation

> Not possible to install add-on using the web gui.

## Expected behavior

> Being able to install the add-on, other add-ons seem to be fine

## Actual behavior

> Presented with "This addon is not available on your system." message.

## Steps to reproduce

> Clean raspbian lite install
> Installed hass.io on top of raspbian using following method: https://gist.github.com/frenck/32b4f74919ca6b95b30c66f85976ec58

**Comment by tjorim** [comment]
Is your Home Assistant up-to-date? It needs to be the latest version (0.91.4).

**Comment by frenck** [comment]
Please update to Home Assistant 0.91.4 as per release notes.
