### ISSUE TITLE
Addon fails to start after update to 18.1.x

### ISSUE THREAD

**Issue by crasu** [hassio-addons/addon-node-red#1962]
# Problem/Motivation

The addon does no longer start inside of hass os (probably after update to 18.1.x)

## Actual behavior

A critical error is logged:
```
2 Oct 23:33:12 - [debug] [server:Home Assistant] States Loaded
2 Oct 23:33:12 - [debug] [server:Home Assistant] Services Loaded
2 Oct 23:33:12 - [debug] [server:Home Assistant] HA State: running
2 Oct 23:33:12 - [debug] [server:Home Assistant] Integration: notloaded
2 Oct 23:33:12 - [red] Uncaught Exception:
2 Oct 23:33:12 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
```
## Steps to reproduce

I am pretty sure my HA components are not at the current version. Which might cause this issue. Is there anyway to check the component version without the node red gui?

**Comment by sinclairpaul** [comment]
The full log would likely be helpful, however you can try starting with the safe mode option set:

https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-safe_mode

**Comment by crasu** [comment]
Just confirmed 18.0.5 still works

**Comment by crasu** [comment]
Still breaks with updated HA components with 18.1.1

**Comment by crasu** [comment]
Full log:

`s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

up to date, audited 2 packages in 2s

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice To update run: npm install -g npm@10.8.3
npm notice
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[01:30:37] INFO: Starting Node-RED...

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

3 Oct 01:30:40 - [info] 

Welcome to Node-RED
===================

3 Oct 01:30:40 - [info] Node-RED version: v4.0.3
3 Oct 01:30:40 - [info] Node.js  version: v18.20.4
3 Oct 01:30:40 - [info] Linux 6.1.58-haos-raspi arm64 LE
3 Oct 01:30:40 - [info] Loading palette nodes
3 Oct 01:30:41 - [info] Node-RED Contrib Theme Collection version: v4.0.10
3 Oct 01:30:44 - [info] Dashboard version 3.6.5 started at /endpoint/ui
3 Oct 01:30:46 - [info] node-red-contrib-home-assistant-websocket v0.73.0 nodes initialized
3 Oct 01:30:46 - [info] Settings file  : /etc/node-red/config.js
3 Oct 01:30:46 - [info] Context store  : 'default' [module=memory]
3 Oct 01:30:46 - [info] User directory : /config/
3 Oct 01:30:46 - [warn] Projects disabled : editorTheme.projects.enabled=false
3 Oct 01:30:46 - [info] Flows file     : /config/flows.json
3 Oct 01:30:46 - [info] Server now running at http://127.0.0.1:46836/
3 Oct 01:30:46 - [info] Starting flows
3 Oct 01:30:46 - [info] Started flows
3 Oct 01:30:46 - [warn] [function:Filter by date] mm=,10
3 Oct 01:30:46 - [error] [api-current-state:.................. present for 1min] InputError: Entity could not be found in cache for ..................
3 Oct 01:30:46 - [error] [api-current-state:.................. away for 60 min] InputError: Entity could not be found in cache for entityId: ..................
3 Oct 01:30:46 - [error] [api-current-state:.................. da für mehr als 5 min] InputError: Entity could not be found in cache for entityId: ..................
[01:30:46] INFO: Starting NGinx...
3 Oct 01:30:51 - [info] [server:Home Assistant] Connecting to http://supervisor/core
3 Oct 01:30:51 - [info] [server:Home Assistant] Connected to http://supervisor/core
3 Oct 01:30:51 - [red] Uncaught Exception:
3 Oct 01:30:51 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[01:30:52] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[01:30:52] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 18.1.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.12.3
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started`

**Comment by sinclairpaul** [comment]
Then looking at the changes, it most likely is with the node-red-contrib-home-assistant-websocket which the addon wraps.

**Comment by 7c** [comment]
Just updated to 18.1.1 - disaster in my home.... it threw error to almost all nodes. But particularly when i copy & paste a "api-call-service". Node throws:

"HomeAssistantError: required key not provided @ data['entity_id']"

After debugging little bit further:

![image](https://github.com/user-attachments/assets/44883939-df7d-4f2a-b76b-5b52c0970c0d)

i found that the entityId is not copied, but on the UI i also do not see the fields to enter the speakers anymore:

![image](https://github.com/user-attachments/assets/a51c1ff0-6358-4e97-8c15-38dd68182257)

**Comment by Yomegaman** [comment]
After updating to 18.1.1 from 18.0.5 - Node-Red won't connect to my MQTT Server.  When I go back to 18.0.5 everything connects and works.  Is the problem on my end?  Can anyone help?

**Comment by Marcos-kp** [comment]
Some have the same problem [#1964 ](url)

**Comment by kernel610** [comment]
This is not stale. It sounds like the 0.74.0 release of the websocket fixed the issue according to [this post](https://github.com/hassio-addons/addon-node-red/issues/1969#issuecomment-2467110419) but that is not included in the current Node Red add-on release.
