### ISSUE TITLE
18.1.1 data lost

### ISSUE THREAD

**Issue by 7c** [hassio-addons/addon-node-red#1963]
Just updated to 18.1.1 - disaster in my home.... it threw error to almost all nodes. But particularly when i copy & paste a "api-call-service". Node throws:

"HomeAssistantError: required key not provided @ data['entity_id']"

After debugging little bit further:

![image](https://github.com/user-attachments/assets/44883939-df7d-4f2a-b76b-5b52c0970c0d)

i found that the entityId is not copied, but on the UI i also do not see the fields to enter the speakers anymore:

![image](https://github.com/user-attachments/assets/a51c1ff0-6358-4e97-8c15-38dd68182257)

-----------------------------------------------------------

 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 18.1.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.8.2
 Home Assistant Supervisor: 2024.09.1

**Comment by qkddn49** [comment]
Click Load sample date
Format has been changed
{"entity_id": "media_player.all_speaker", "message": "test" }

**Comment by 7c** [comment]
go to import and paste:
```
[{"id":"3f354c0ef8226b82","type":"api-call-service","z":"55a572a719914fec","name":"","server":"272f759e.9ee09a","version":7,"debugenabled":true,"action":"tts.cloud_say","floorId":[],"areaId":[],"deviceId":[],"entityId":["media_player.office_speaker","media_player.googlehome8713"],"labelId":[],"data":"{\"message\":\"test\"}","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"tts","service":"cloud_say","x":570,"y":300,"wires":[[]]},{"id":"272f759e.9ee09a","type":"server","name":"Home Assistant","addon":true}]
```

run it, it works, once you change ANY property by editing like the title and deploy. It stops working because entityId is emptied

**Comment by qkddn49** [comment]
Until it is updated, try using it as a temporary method as below
There seems to be an error when the media turns off
![화면 캡처 2024-10-05 075048](https://github.com/user-attachments/assets/51dce573-f056-4d6f-a623-a852773272ec)
I use it like this temporarily.
