### ISSUE TITLE
Zigbee2Mqtt Topic stopped working after 18.1.1 update

### ISSUE THREAD

**Issue by Marcos-kp** [hassio-addons/addon-node-red#1964]
# Problem/Motivation

> All my Zigbee buttons that have a mqtt node stopped working.

## Expected behavior

> When a button is pressed, I expect an action to appear in Node-red trough the mqtt node.

## Actual behavior

> Nothing happens, no output at all. When listening to events in HA, I get: 
`event_type: state_changed
data:
  entity_id: sensor.botao_escritorio_action
  old_state:
    entity_id: sensor.botao_escritorio_action
    state: single
    attributes:
      icon: mdi:gesture-double-tap
      friendly_name: Botão Escritório Action
    last_changed: "2024-10-03T17:11:06.599855+00:00"
    last_reported: "2024-10-03T17:11:06.599855+00:00"
    last_updated: "2024-10-03T17:11:06.599855+00:00"
    context:
      id: 01J99NT9K71DGK3F56MDYJDPFG
      parent_id: null
      user_id: null
  new_state:
    entity_id: sensor.botao_escritorio_action
    state: ""
    attributes:
      icon: mdi:gesture-double-tap
      friendly_name: Botão Escritório Action
    last_changed: "2024-10-03T17:11:06.601384+00:00"
    last_reported: "2024-10-03T17:11:06.601384+00:00"
    last_updated: "2024-10-03T17:11:06.601384+00:00"
    context:
      id: 01J99NT9K978F00V8XEEC4JDG0
      parent_id: null
      user_id: null
origin: LOCAL
time_fired: "2024-10-03T17:11:06.601384+00:00"
context:
  id: 01J99NT9K978F00V8XEEC4JDG0
  parent_id: null
  user_id: null
`
Logs:
`3 Oct 14:33:32 - [error] [api-call-service:Desliga Luz Escritório] InputError: Invalid action format: single
3 Oct 14:33:33 - [error] [api-call-service:Liga Luz Escritório] InputError: Invalid action format: double
3 Oct 14:36:46 - [error] [api-call-service:Desliga Luz Escritório] InputError: Invalid action format: single`
Also looking at the Mqtt integration I see the action when pressing the button.

**Comment by gregolin** [comment]
The same here, with a response from a Yale device (door lock). It returns:

> action: "unlock"
action_source: 2
action_source_name: "manual"
action_user: 0
auto_relock_time: null
battery: 100
battery_low: null
linkquality: 120
lock_state: "locked"
pin_code: null
sound_volume: null
state: "LOCK"

and I receive error message about the "action" node, and I really don't know how could I fix it (should be fixed in the Z2M? In the Node Red add-on?)

> "InputError: Invalid action format: unlock"

**Comment by dacorde** [comment]
Issue I reported looks to be the same.
https://github.com/hassio-addons/addon-node-red/issues/1959#issue-2561004792

**Comment by Marcos-kp** [comment]
Just confirming that rolling back to 18.0.5, things work again. I also had an issue where I wasn't able to interact with inject nodes.

**Comment by gregolin** [comment]
Hi everyone.
Any news here?

**Comment by Marcos-kp** [comment]
> does it look like this? [#1962 (comment)](https://github.com/hassio-addons/addon-node-red/issues/1962#issuecomment-2400876693)
> 
Yes, it does!
Still nothing from the developers, and I have no idea if these issues have been looked at.

**Comment by Marcos-kp** [comment]
Also, I updated all my Node-RED palettes, updated Node-RED again to check, and still the issue with Z2MQTT persists but fixes the inject node issue. Rolling back to 18.0.5 makes things work again.

**Comment by Marcos-kp** [comment]
Figured the issue: and its described [here](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1489)

**Comment by Marcos-kp** [comment]
Figured the issue: and its described [here](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1489)
