### ISSUE TITLE
18.1.1 Unstable connection with Home Assistant server

### ISSUE THREAD

**Issue by qkddn49** [hassio-addons/addon-node-red#1966]
For tts, the home assistant server is frequently disconnected and cannot broadcast
The connection to the home assistant server is unstable.
![화면 캡처 2024-10-04 090325-horz](https://github.com/user-attachments/assets/aebf75d5-ea11-40f5-88ed-49e2d42ee358)

Even when tts are executed, errors often occur
![화면 캡처 2024-10-04 091214](https://github.com/user-attachments/assets/d739c12e-906a-4dce-9878-0b7c4b49e55e)

**Comment by Jens-Wymeersch** [comment]
same here

**Comment by Jens-Wymeersch** [comment]
Any news on this ?

**Comment by qkddn49** [comment]
> 이에 대한 소식이 있나요?
We are using tts temporarily as below
![화면 캡처 2024-10-06 202029](https://github.com/user-attachments/assets/453fe595-3642-4cf9-99b7-05d5140086bd)

**Comment by Z4RR0** [comment]
same situation here old configured nodes work but any new attemp give me a blank list

**Comment by jesperholstjh** [comment]
I have the exact same issue.

**Comment by Duckle29** [comment]
This is still an issue.

Adding an action node, you have the option to set targets:
![image](https://github.com/user-attachments/assets/f387e895-f6ec-40b4-9a75-35187b2aa9fa)

When you pick `light.turn_on` as the action, the target input is gone
![image](https://github.com/user-attachments/assets/fca58abd-d991-4ad9-bff9-7fe4fba72bc1)

I'm unaware of how to update the contrib plugin in HAOS
