### ISSUE TITLE
Template not being evaluated after update to 18.1.1

### ISSUE THREAD

**Issue by 1liminal1** [hassio-addons/addon-node-red#1968]
# Problem/Motivation

After the update, it now just reads out the message and no longer evaluates the template

## Expected behavior

It should evaluate the template and give the correct options 

## Actual behavior

It just reads out the entire string

## Steps to reproduce

input node

Here is a screen shot of the node; 

![image](https://github.com/user-attachments/assets/db5ecf49-b512-44ad-bfe3-91377d14b7ee)

Here is the message json

```
{
   "message":"[{% set door = is_state('binary_sensor.balcony_door_sensor', 'on') %}  {% set bdoor = is_state('binary_sensor.bedroom_balcony_door', 'on') %}  {% set window = is_state('binary_sensor.second_bedroom_window', 'on') %}  {% if door and window and bdoor %}  Please close both balcony doors and the bedroom window? {% elif door and window %}  Please close the balcony door and the bedroom window? {% elif bdoor and window %}  Please close the bedroom balcony door and the bedroom window? {% elif bdoor and door %}  Please close both balcony doors? {% elif window %} Please close the bedroom window?  {% elif door %} Please close the balcony door?  {% elif bdoor %} Please close the bedroom balcony door? {% endif %}]",
   "data":{"type":"announce", "method":"speak"},
   "target":[
       "media_player.bathroom_spot",
       "media_player.bedroom_show",
       "media_player.living_room_show",
       "media_player.kitchen_show"
   ]
}
```

## Proposed changes

Bug?

**Comment by 3ative** [comment]
Seconded. 
For a workaround I've had to grab a "Global Get" and substitute a variable.
Prior to update, this worked fine:
```yaml
msg.payload =
    "The temperature is " + "{{states.sensor.bedroom_temperature.state}}"
return msg
```
Now only this works:
```yaml
var state = global.get('homeassistant').homeAssistant.states["sensor.bedroom_temperature"].state
msg.payload =
    "The temperature is " + state 
return msg
```

**Comment by 3ative** [comment]
I found the **Render Template Node** still works:
![TP-Node-Tester](https://github.com/user-attachments/assets/d2778a84-f48b-4a95-8472-cee9a9f95edd)

So it seems: **_{{states.sensor.bedroom_temperature.state}}_** IS a valid way to get an entity's State/Value/Etc. It's just not getting evaluated elsewhere like it always was.

**Comment by frenck** [comment]
> So it seems: {{states.sensor.bedroom_temperature.state}} IS a valid way to get an entity's State/Value/Etc

It is strongly discouraged. Don't use that.

**Comment by 1liminal1** [comment]
> Seconded. For a workaround I've had to grab a "Global Get" and substitute a variable. Prior to update, this worked fine:

How do you make that work?

**Comment by 1liminal1** [comment]
> It is strongly discouraged. Don't use that.

Um, thanks... 

Is this a you thing, or a node red thing. Why is this now broken?

I understand you're busy, but Im sure a lot of people are using templating in Node Red.

**Comment by 1liminal1** [comment]
I have no idea what frenck was trying to say, but the render template works. And its an issue with HA core, not Node Red anyway.
