### ISSUE TITLE
Targets not showing in action node after upgrading to 18.1.1

### ISSUE THREAD

**Issue by ssillen** [hassio-addons/addon-node-red#1969]
# Problem/Motivation

After updating from 18.0.5 to 18.1.1 NR asked me to update HA nodes. After that I noticed multiple issues for my action (previously "call service") nodes. All of them told me that entity_id should be in "data" and not in "target". I could not find the "targets" property, so no way to find the entity_id. According to screenshots of other people, there should be a "targets" property.
Reverted back to 18.0.5 and everything is ok now. Phew, that was scary.

## Expected behavior

I expect to still be able to use the "targets" property and not having to define the target entity_id in the data property. Also, the target property should be shown.

## Actual behavior

Targets property is missing. Multiple errors, although I did not change anything.

## Steps to reproduce

Update from 18.0.5 to 18.1.1 and then confirm update HA nodes.

**Comment by Sirena44** [comment]
I have exactly the same issue. No targets property showing in the action node making Node Red unusable.  if I go into Node Red directly using :1880 the target property shows but then vanishes.

**Comment by Sirena44** [comment]
Correction mostly working now except Z Wave JS and that is probably me.

**Comment by paulcusick3** [comment]
+1 NO actions at all
![Capture](https://github.com/user-attachments/assets/532cbf95-2002-40eb-9721-8f32920e13e9)

Log looks fine at startup:

`Welcome to Node-RED
===================

8 Oct 07:34:41 - [info] Node-RED version: v4.0.3
8 Oct 07:34:41 - [info] Node.js  version: v18.20.4
8 Oct 07:34:41 - [info] Linux 6.6.46-haos arm64 LE
8 Oct 07:34:42 - [info] Loading palette nodes
8 Oct 07:34:43 - [info] Node-RED Contrib Theme Collection version: v4.0.10
8 Oct 07:34:47 - [info] Dashboard version 3.6.5 started at /endpoint/ui
8 Oct 07:34:49 - [info] node-red-contrib-home-assistant-websocket v0.73.0 nodes initialized
8 Oct 07:34:49 - [info] Settings file  : /etc/node-red/config.js
8 Oct 07:34:49 - [info] Context store  : 'default' [module=memory]
8 Oct 07:34:49 - [info] User directory : /config/
8 Oct 07:34:49 - [warn] Projects disabled : editorTheme.projects.enabled=false
8 Oct 07:34:49 - [info] Flows file     : /config/flows.json
8 Oct 07:34:49 - [info] Server now running at http://127.0.0.1:46836/
8 Oct 07:34:50 - [info] Starting flows
[07:34:50] INFO: Starting NGinx...
8 Oct 07:34:51 - [info] Started flows
8 Oct 07:34:55 - [info] [server:Hingham Home] Connecting to http://supervisor/core
8 Oct 07:34:55 - [info] [server:Home Assistant] Connecting to http://supervisor/core
8 Oct 07:34:55 - [info] [server:Hingham Home] Connected to http://supervisor/core
8 Oct 07:34:55 - [info] [server:Home Assistant] Connected to http://supervisor/core`

**Comment by Marx1** [comment]
+1 same issue. Reverted back to 18.0.5

**Comment by gregolin** [comment]
Certainly the issue is related to this change:

https://www.home-assistant.io/blog/2024/10/02/release-202410/#improved-yaml-syntax-for-automations

I think the addon must be updated by the developers.

**Comment by paulcusick3** [comment]
Bump - Still an issue. Staying on 18.0.5

**Comment by ssillen** [comment]
This could probably be linked to the version of node-red-contrib-home-assistant-websocket
Go to menu->Manage Palette -> Nodes
here search for node-red-contrib-home-assistant-websocket, and look for an update. There should be an update button to 0.74.2
I still have to test this when I have time to debug and know how to revert to the previous version. Does anyone know how to do this?

Also, why is the palette not- automatically updated with the update of the HA add-on?

**Comment by Marx1** [comment]
Still broken for me. Nodes are still missing.

**Comment by DougEdey** [comment]
@Marx1 Did you update the websocket add on then reload the Node Red integration? That's what fixed it for me.

👍 on "Why didn't this pallete node update?"

Mine was at 0.73 before, so I'm guessing the fix was in 0.74.0 based on the [Changelog](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/main/CHANGELOG.md)
