### ISSUE TITLE
node.js not automatically updated?

### ISSUE THREAD

**Issue by Podler** [hassio-addons/addon-node-red#1978]
Hi,

I upgraded the Home Assistant Node-RED addon to version 18.1.1. Now I am having trouble with my Node-RED flows using the knx-utlimate integration.

knx-ultimate requires node.js version 20.x.x. My node.js seems to be 18.20.4. Doesn't node.js get updated automatically when updating the Home Assistant Node-RED addon? How do I update to node.js 20.x manually and is there any risk for the rest of Home Assistant doing so?

Your help is very much appreciated!

Warm regards, Thomas.

**Comment by frenck** [comment]
There is an upstream issue with NodeJS on armv7, preventing upgrading any NodeJS Docker container for this platform.

This is, unfortunately out of our control.

../Frenck

**Comment by Podler** [comment]
Hi Frenck, thank you for your reply. Does that mean, that every installation of Node-RED depending an NodeJS 20.x on Home Assistant is broken right now? Do you already know how it will be handled from your side when the upstream issue is solved? Will a later version of your Node-RED integration retry the upgrade of NodeJS? Please excuse my questions. I am not a linux professional... Regards, Thomas.

**Comment by frenck** [comment]
> Does that mean, that every installation of Node-RED depending an NodeJS 20.x on Home Assistant is broken right now?

It means this add-on uses NodeJS 18.

> Do you already know how it will be handled from your side when the upstream issue is solved?

If the upstream issue is solved, it means we can remove the manual enforcing of the NodeJS version from this add-on and upgrade to the latest greatest.

../Frenck

**Comment by Podler** [comment]
Last question an then I will rest in patience: Is is right, that this issue already exists for months? Do you have any information how long this state might last? Any hint or hope for a resolution in the near future? I ask because nearly 4.500 (!) KNX funktions in my property depend on this... :-(

**Comment by frenck** [comment]
> Is is right, that this issue already exists for months?

Yes.

>  Do you have any information how long this state might last? 

Nope. This is an issue upstream with the NodeJS project.

../Frenck

**Comment by Podler** [comment]
Thank you Frenck. Your help (and) work is highly appreciated. Warm regards, Thomas.
