### ISSUE TITLE
Node-RED Addon doesn't start

### ISSUE THREAD

**Issue by rzucki71** [hassio-addons/addon-node-red#1981]
# Problem/Motivation

Dear folks,
when starting the addon it tries to start up but doesn't, and finally shows "start" again.
Yesterday everything worked fine, and I didn't change anything in between.

Can anyone help?

## Expected behavior

The addon should start properly

## Actual behavior

Instead of starting up, the addon just tries to start up, but then show "start" again in the end.

## Configuration
theme: default
http_node:
  username: ""
  password: ""
http_static:
  username: ""
  password: ""
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
system_packages: []
npm_packages: []
init_commands: []
credential_secret: MyVerySecret

## Logs
46 packages are looking for funding
  run `npm fund` for details

15 vulnerabilities (3 low, 3 moderate, 9 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[22:46:36] INFO: Starting Node-RED...
s6-rc: info: service legacy-services successfully started

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

17 Oct 22:46:37 - [info] 

Welcome to Node-RED

17 Oct 22:46:37 - [info] Node-RED version: v4.0.3
17 Oct 22:46:37 - [info] Node.js  version: v18.20.4
17 Oct 22:46:37 - [info] Linux 6.6.54-haos x64 LE
17 Oct 22:46:37 - [info] Loading palette nodes
17 Oct 22:46:38 - [info] Node-RED Contrib Theme Collection version: v4.0.10
17 Oct 22:46:39 - [info] Dashboard version 3.6.5 started at /endpoint/ui
17 Oct 22:46:39 - [info] Settings file  : /etc/node-red/config.js
17 Oct 22:46:39 - [info] Context store  : 'default' [module=memory]
17 Oct 22:46:39 - [info] User directory : /config/
17 Oct 22:46:39 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Oct 22:46:39 - [info] Flows file     : /config/flows.json
17 Oct 22:46:39 - [info] Server now running at http://127.0.0.1:46836/
[22:46:39] INFO: Starting NGinx...
17 Oct 22:46:39 - [info] Starting flows
17 Oct 22:46:40 - [error] [trigger-state:0de69c401fbae16f] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [error] [trigger-state:bba9632aacc2c1a3] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [error] [trigger-state:fff7822be618a47b] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [error] [trigger-state:6b15eaef6a9d8c77] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [error] [trigger-state:2dae9f993f2ad3f5] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [error] [trigger-state:44b377ea5d8b9124] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [error] [trigger-state:a6280b3c541bbff9] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [error] [trigger-state:0ba9cc59dbc43278] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [error] [trigger-state:23747197aae487af] ConfigError: trigger-state.error.enttity_id_required
17 Oct 22:46:40 - [info] Started flows
17 Oct 22:46:40 - [info] [vsh-connection:heurigl@zucki.net] MQTT: attempting connection: a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883 (clientId: vsht-5d6e2e4f-8328-4f06-b387-86e16b95fa17)
17 Oct 22:46:40 - [info] [vsh-connection:heurigl@zucki.net] MQTT: connected to a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883, connection #1
17 Oct 22:46:40 - [info] [vsh-connection:heurigl@zucki.net] MQTT: subscribe to topics: ["$aws/things/vsht-5d6e2e4f-8328-4f06-b387-86e16b95fa17/shadow/get/accepted","vsh/vsht-5d6e2e4f-8328-4f06-b387-86e16b95fa17/+/directive","vsh/service","vsh/version/4.4.2/+","vsh/vsht-5d6e2e4f-8328-4f06-b387-86e16b95fa17/service"]
17 Oct 22:46:40 - [info] [vsh-connection:heurigl@zucki.net] MQTT: publish to topic $aws/things/vsht-5d6e2e4f-8328-4f06-b387-86e16b95fa17/shadow/update: {"state":{"reported":{"connected":true,"vsh_version":"4.4.2","nr_version":"4.0.3"}}}
17 Oct 22:46:41 - [info] [vsh-connection:heurigl@zucki.net] MQTT: publish to topic vsh/vsht-5d6e2e4f-8328-4f06-b387-86e16b95fa17/requestConfig: {"vshVersion":"4.4.2"}
17 Oct 22:46:42 - [info] [vsh-connection:heurigl@zucki.net] MQTT: message received on topic vsh/vsht-5d6e2e4f-8328-4f06-b387-86e16b95fa17/service: {"operation":"kill","reason":"User not found! VSH Alexa skill enabled?"}
17 Oct 22:46:42 - [red] Uncaught Exception:
17 Oct 22:46:42 - [error] TypeError: this[logLevel] is not a function
    at ConnectionNode.logger (/config/node_modules/node-red-contrib-virtual-smart-home/connection.js:70:27)
    at ConnectionNode.handleKill (/config/node_modules/node-red-contrib-virtual-smart-home/connection.js:610:12)
    at ConnectionNode.handleService (/config/node_modules/node-red-contrib-virtual-smart-home/connection.js:644:16)
    at MqttClient.<anonymous> (/config/node_modules/node-red-contrib-virtual-smart-home/connection.js:823:18)
    at MqttClient.emit (node:events:517:28)
    at MqttClient.<anonymous> (/config/node_modules/node-red-contrib-virtual-smart-home/MqttClient.js:53:12)
    at MqttClient.emit (node:events:517:28)
    at Array.<anonymous> (/config/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/src/lib/handlers/publish.ts:155:14)
    at Object.MqttClient.options.customHandleAcks (/config/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/src/lib/client.ts:524:14)
    at handlePublish (/config/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/src/lib/handlers/publish.ts:136:12)
[22:46:42] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[22:46:42] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by tjorim** [comment]
This is a problem with `node-red-contrib-virtual-smart-home`. You can try setting `safe_mode` to true in the add-on configuration.

**Comment by rzucki71** [comment]
Fixed
