### ISSUE TITLE
Regular crashes after recent updates

### ISSUE THREAD

**Issue by stefanbode** [hassio-addons/addon-node-red#1987]
The last messages before automatic shutdown are following. Currently watchdog mitigate the issue. Anyhow the restart is new to my system

{"type":"result","success":false,"error":{"code":3,"message":"Connection lost"}}
29 Oct 01:01:17 - [red] Uncaught Exception:
29 Oct 01:01:17 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[01:01:18] INFO: Service Node-RED exited with code 1 (by signal 0)

Happy to help debugging

**Comment by zachowj** [comment]
Possibly related to this issue: [home-assistant/home-assistant-js-websocket#533](https://github.com/home-assistant/home-assistant-js-websocket/issues/533)

**Comment by stefanbode** [comment]
some additional logs after activating watchdog and auto restart:
29 Oct 22:33:11 - [error] [api-call-service:Schliessen] HomeAssistantError
29 Oct 23:09:32 - [error] [api-call-service:Schliessen] HomeAssistantError
29 Oct 23:33:07 - [error] [api-call-service:Schliessen] HomeAssistantError
30 Oct 03:17:35 - [error] [api-call-service:Schliessen] HomeAssistantError
30 Oct 07:51:35 - [error] [api-call-service:Schliessen] HomeAssistantError
