### ISSUE TITLE
Nod Red not starting Latest HA.

### ISSUE THREAD

**Issue by nutshellml** [hassio-addons/addon-node-red#1990]
Have Node Red latest update of HA and added on succesfully but when clicking "Start" it doesn't start.  Tried reboot but nothing.

[18:12:04] FATAL: is placed in the '/ssl/' directory.
[18:12:04] FATAL: 
s6-rc: info: service nodered successfully started
[18:12:04] FATAL: In case you don't have SSL yet, consider getting
[18:12:04] FATAL: an SSL certificate or setting the 'ssl' option
[18:12:04] FATAL: to 'false' in case you are not planning on using
[18:12:04] FATAL: SSL with this add-on.
[18:12:04] FATAL: 
[18:12:04] FATAL: Check the add-on manual for more information.
[18:12:04] FATAL: 
s6-rc: warning: unable to start service init-nginx: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service nodered: stopping
[18:12:04] INFO: Service Node-RED exited with code 256 (by signal 15)
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 18.1.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / qemux86-64)
 Home Assistant Core: 2024.10.4
 Home Assistant Supervisor: 2024.10.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
[18:16:55] FATAL: 
[18:16:55] FATAL: SSL has been enabled using the 'ssl' option,
[18:16:55] FATAL: this requires an SSL certificate file which is
[18:16:55] FATAL: configured using the 'certfile' option in the
[18:16:55] FATAL: add-on configuration.
[18:16:55] FATAL: 
[18:16:55] FATAL: Unfortunately, the file specified in the
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
[18:16:55] FATAL: 'certfile' option does not exist.
[18:16:55] FATAL: 
[18:16:55] FATAL: Please ensure the certificate file exists and
[18:16:55] FATAL: is placed in the '/ssl/' directory.
s6-rc: info: service nodered successfully started
[18:16:55] FATAL: 
[18:16:55] FATAL: In case you don't have SSL yet, consider getting
[18:16:55] FATAL: an SSL certificate or setting the 'ssl' option
[18:16:55] FATAL: to 'false' in case you are not planning on using
[18:16:55] FATAL: SSL with this add-on.
[18:16:55] FATAL: 
[18:16:55] FATAL: Check the add-on manual for more information.
[18:16:55] FATAL: 
s6-rc: warning: unable to start service init-nginx: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service nodered: stopping
[18:16:55] INFO: Service Node-RED exited with code 256 (by signal 15)
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by nutshellml** [comment]
Disregard - turned SSL off and worked.

Now next question - how important is it to have SSL for HA/ Node Red?

**Comment by nutshellml** [comment]
I went into configuration and disabled it, works now..

**Comment by BoyuanJiang** [comment]
> configuration and disabled it

I want to know how to configuration and disabled it?
