### ISSUE TITLE
Failed to get a0d7b954_nodered logs, undefined is not a function (near '...e.callApiRaw...')

### ISSUE THREAD

**Issue by timpetersson81** [hassio-addons/addon-node-red#1991]
My nodered log says Failed to get a0d7b954_nodered logs, undefined is not a function (near '...e.callApiRaw...')

Allso I cant deploy my nodes

**Comment by figorr** [comment]
Exactly the same error running ...
- Core: 2024.10.4
- Supervisor: 2024.11.2
- Operating System: 13.2
- Frontend: 20241002.4

`Failed to get a0d7b954_nodered logs, e.callApiRaw is not a function`
