### ISSUE TITLE
Node Red 3.0.1 flows not displaying in web ui 

### ISSUE THREAD

**Issue by dreed47** [hassio-addons/addon-node-red#201]
probably same issue as closed issue https://github.com/hassio-addons/addon-node-red/issues/197

# Problem/Motivation
No Node Red UI when using ingress

## Actual behavior
 Get the banner at the top but no flows load

## Steps to reproduce
Node Red version 3.0.1 and HA 0.91.4

**Comment by pbavinck** [comment]
Experiencing the same thing. (Node Red version 3.0.1 and HA 0.91.4)
Steps to reproduce
- click hassio in left side menu
- select node-red addon
- click open web ui

The node-red window appears with the node-red header bar, but no content is being shown (no flows, no tabs, etc.)

**Comment by Den-W1** [comment]
I concur 

Steps to reproduce

Click hassio in left side menu
Select node-red addon
Click open web ui
The node-red window appears with the node-red header bar, but no content is being shown (no flows, no tabs, etc.).

http://hassio.local:1880 shows flows, tabs, content as expected.

Versions
Node-RED 3.0.1
Home Assistant 0.91.4
Google Chrome Browser
Windows 10

**Comment by FindingJohnny** [comment]
Can confirm. I used the same steps as @Den-W1 and @pbavinck.

Versions
Node-Red 3.0.1
Home Assistant 0.91.4
Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Windows 10

**Comment by smoke007** [comment]
Same issue, buy my Node-RED logo is broken when the site doesn't load.  The only way I'm able to get Node-RED to load ONCE, it to clear the Chrome cache.  Node-RED will then load successfully ONE time, until I clear Chrome cache again.  

I've confirmed the same issue at more than one computer and with a friend who has the same same, same versions, and same issue.  Thanks in advance!

https://%mysite%.duckdns.org:%port%/hassio/ingress/a0d7b954_nodered
Versions
Node-RED 3.0.1
Home Assistant 0.91.4
Google Chrome Browser
Windows 10

**Comment by Den-W1** [comment]
I concur with smoke007

Node-RED will load ONCE after clearing Chrome cache.

Clear Chrome cache
Click hassio in left side menu
Select node-red addon
Click open web ui 
Web ui opens with header bar, tabs, flows, content as expected.

Closing web requires clearing Chrome cache before web ui / ingress will fully populate.  

Versions
Node-RED 3.0.1
Home Assistant 0.91.4
Google Chrome Browser
Windows 10

**Comment by AZDane** [comment]
Exact Same issue as above

**Comment by arretx** [comment]
Yes, same issue, as well as a persistent notification about needing to deploy after setting up a server every time I open a node.

And, if I try to import from examples posted on the forum using the import menu, the nodes import, but immediately after I'm prompted by the browser to login to HA again with a plain text popup.

**Comment by PurelyNicole** [comment]
I'm seeing the same behavior as Den-W1 and smoke007. 

I have found that Node-RED will consistently load with Firefox 66.0.3 (64-bit)

**Comment by wiggitamoo** [comment]
For those using MacOS, I have found Safari to be more reliable than Chrome in loading Node-Red in ingress.

**Comment by frenck** [comment]
I've applied and am testing a more permanent fix right now.

**Comment by frenck** [comment]
This issue has been addressed and resolved in the `v3.0.2` release of the add-on.

Thanks for reporting the issue 👍
