### ISSUE TITLE
Unable to log in from public network

### ISSUE THREAD

**Issue by naamah75** [hassio-addons/addon-node-red#202]
From the last update 3.0.1 I'm unable to login from outside local network (the login windows get back forever even if I put the correct username and password) and in the local area I'm not asking anymore from credentials when accessing the page.

From the log only the following string, no erros at all.
`GET /locales/node-red?lng=en-US HTTP/2.0 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36)`

The configuration is still the same as before the update...

```
{
  "credential_secret": "********",
  "dark_mode": false,
  "http_node": {
    "username": "********",
    "password": "********"
  },
  "http_static": {
    "username": "********",
    "password": "********"
  },
  "ssl": true,
  "certfile": "********.crt",
  "keyfile": "********.key",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": [],
  "log_level": "info"
}
```

**Comment by frenck** [comment]
How are you accessing it from outside your network? Have you tried deleting existing application data as written on the community forums and discussed in #190?

**Comment by naamah75** [comment]
My problem it's the same of #190 and the workaround is working but the login page of the node-red server is still missing.

**Comment by frenck** [comment]
there is no node-red login page since v3.0.0.....

**Comment by naamah75** [comment]
Ooops! thanks...
