### ISSUE TITLE
please stop your updates

### ISSUE THREAD

**Issue by pico563** [hassio-addons/addon-node-red#204]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by pico563** [comment]
node-red
#  refused to connect.

**Comment by frenck** [comment]
Really?

Please make a proper issue.

**Comment by pico563** [comment]
I hope you know what you are doing Franck  at least give us the possibility
to return to previous version.
For me it is second time with Node-Red  and first time with influxDB.
Sorry.

**Comment by frenck** [comment]
> I hope you know what you are doing Franck  at least give us the possibility to return to previous version.

That is not a feature an add-on can provide. That is a Hass.io feature request.

If you are having issues, please file a proper bug report so I can look into it and make sure everything works for everybody.

In case you need support, join or Discord server, so we can help you out.
