### ISSUE TITLE
Deploying a new imported flow fails with Maximum Request Body Size Exceeded error

### ISSUE THREAD

**Issue by lsilva171** [hassio-addons/addon-node-red#211]
# Problem/Motivation

> Failing to importing large size flows.

## Expected behavior

> Same as version 2.0.2 where large size flows where imported successfully

## Actual behavior

>  Importing a large flow fails with Maximum Request Body Size Exceeded error

## Steps to reproduce

> Trying to deploy a flow like Zigbee2MQTT Admin

**Comment by lsilva171** [comment]
Fixed by deleting /usr/share/hassio/homeassistant/node-red from previous installation and restarting everything from scratch

**Comment by frenck** [comment]
The issue has been addressed in the current development version.

**Comment by frenck** [comment]
Fixed in release v3.1.0
