### ISSUE TITLE
Dashboard will not open get 404: Not Found

### ISSUE THREAD

**Issue by kandbcontrols** [hassio-addons/addon-node-red#215]
# Problem/Motivation
When I try to open dashboard a new tab opens in chrome, just like before, except now I get 404: Not Found
> (Why the issue was filed)
I upgraded from 2.02 to 3.03
## Expected behavior
Before a new tab would open with my dashboard
> (What you expected to happen)
the same as before
## Actual behavior
404: Not Found
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Is this using Ingress?

**Comment by kandbcontrols** [comment]
Yes. I can not get Node Red to open in a new tab like before. I tried
adding 9000 to the config, but that does not work. I finally did get Node
Red to open in a new tab by double clicking on the Dashboard tab in Node
Red trying to open the dashboard. However, the dashboard still does not
open.

**Comment by kandbcontrols** [comment]
Sorry, not double click. Node Red will open in a new tab if I right click on the dashboard tab and say open in a new tab. I've included 3 screen shots. BTW, I am using duckDNS.
![404](https://user-images.githubusercontent.com/47787237/57083638-e0104d80-6cc6-11e9-900f-ae474a35f405.png)
![Dashboard open](https://user-images.githubusercontent.com/47787237/57083639-e0104d80-6cc6-11e9-9260-2b2c5afaeaf0.png)
![Node Red Open](https://user-images.githubusercontent.com/47787237/57083640-e0104d80-6cc6-11e9-8a86-35d5376a2fce.png)

**Comment by usenetj23** [comment]
Same here. Clean install hassio and then latest node-red. Same issue. If I add 1880 port to config and go to ip:1880/ui it asks for user pass and none is working.

**Comment by sinclairpaul** [comment]
Not sure these are the same issues, if you access ip:1880/ui the username and password should be your HA credentials, are these failing?, if so would it be possible to see the output from the dev console in your browser to see the HTTP codes returned?  The previous issue seems to be that the Node-Red UI presents the link from root, which will not work under ingress only, in which case it may be possible to copy the link and append /ui to it.

**Comment by usenetj23** [comment]
If I reproduce step by step like described in OP I see 404: Not Found
I can only open node-red going directly from HS sidebar: http://hassio.local:8123/a0d7b954_nodered or http://192.168.1.137:8123/a0d7b954_nodered I cant open ui from node-red webui -> 404.
If I add for example 1880 port to node-red config and go to that page http://hassio.local:1880 it asks user and password. Noone of configured passwords and users is accepted. Added to settings.js:
```
    adminAuth: {
    type: "credentials",
    users: [{
        username: "usenet",
        password: "$2a$08$f5x86qt8Z8QbdgLuL/DUJOowNiLx1URUSRwi1ZXN4Txb7GQPHSG6m",
        permissions: "*"
    }]
    },
    httpNodeAuth: {
        user:"usenet",
        pass:"$2a$08$f5x86qt8Z8QbdgLuL/DUJOowNiLx1URUSRwi1ZXN4Txb7GQPHSG6m"
    }
}
```
nothing helps. Password generated with node-red-admin hash-pw. node-red-admin added to config:
```
  "npm_packages": [
    "node-red-admin"
  ],
```

**Comment by frenck** [comment]
You cannot use the Node-RED dashboard UI from Ingress, you'd have to enable direct access for it and use it that way.

**Comment by sinclairpaul** [comment]
@usenetj23 can you access http://hassio.local:1880  and enter your Home Assistant credentials?  The latest versions of the addon are configured to use HA authentication, previously it was within Node Red itself.

**Comment by usenetj23** [comment]
@sinclairpaul when I go to http://hassio.local:1880  it ask user and pass. Enter my login then opens node-red top bar and asks user and pass (not node-red login page but browser user/pass popup). I enter every combination. Nothing helps. 
Tomorrow I once again install everything from scratch.

**Comment by frenck** [comment]
@usenetj23 
https://community.home-assistant.io/t/community-hass-io-add-on-node-red/55023/629?u=frenck

**Comment by usenetj23** [comment]
@frenck yes, this helps to login to http://hassio.local:1880 Thank You
Now time to investigate why http://hassio.local:1880/ui ask about password and not accept

**Comment by kandbcontrols** [comment]
I have tried to copy the link and add /ui to it and it does not work. I
have tried  I tried the following and get this error.

[image: image.png]

**Comment by kandbcontrols** [comment]
How do i disable Ingress? I added 9000 to the config section and re-started
Node Red and it still opens in Ingress. I changed it to 1880 like I used
before same results. Sorry if I am missing something.

[image: image.png]
