### ISSUE TITLE
Connection refused several times before being accepted

### ISSUE THREAD

**Issue by folrewef** [hassio-addons/addon-node-red#216]
# Problem/Motivation

> Problems connecting slows down restart significantly

## Expected behavior

> Node-RED to connect on first try

## Actual behavior

> I get the following error:

> 19-04-29 10:37:04 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
> 19-04-29 10:37:04 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
> 19-04-29 10:37:04 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
> 

The error is repeated several times over several minutes delaying the restart. Eventually the connection works and the restart is completed:

> 19-04-29 10:46:10 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
> 19-04-29 10:46:10 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
> 19-04-29 10:46:10 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
> 19-04-29 10:46:12 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance

My setup is on hassio 92.1:

```
{
  "credential_secret": "redacted",
  "dark_mode": false,
  "http_node": {
    "username": "",
    "password": ""
  },
  "http_static": {
    "username": "",
    "password": ""
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": [],
  "log_level": "info"
}

```
## Steps to reproduce

> Do not know

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is expected behavior, the connection might not be ready yet, the add-on just keeps trying until it is.
