### ISSUE TITLE
Unable to open the palette sidebar when it's collapsed

### ISSUE THREAD

**Issue by simonk83** [hassio-addons/addon-node-red#223]
# Problem/Motivation

Unable to expand the palette sidebar when it's collapsed

## Expected behavior

When you click on the arrow in the middle of the bar, the sidebar is collapsed.  Hovering over the center of the collapsed bar should show an arrow to expand it.

## Actual behavior

No expand arrow appears.  You need to use Ctrl-P to get the sidebar to appear again.

## Steps to reproduce

Collapse the palette sidebar, hover over the centre of the collapsed bar and try and find the arrow to expand it.

**Comment by sinclairpaul** [comment]
Just as a guess, but I am assuming this only occurs on the ingress link and not when you access via https://mylink:1880 ?

**Comment by frenck** [comment]
Please provide log information.
It is useless without it. Closing issue. Feel free to open a proper one.

**Comment by frenck** [comment]
Found it, but that is unfortunately not fixable (actually a node-red bug).

Beside the shortcut you've listed, you can also enable the view via the top right menu again.

**Comment by simonk83** [comment]
Hmm fair enough.  I've actually just moved from a standalone install of Node-RED to this add-on. I was running standalone for a good month and never ran into this problem, so is it something specific to the HA integration (even if the problem is at their end)?

**Comment by frenck** [comment]
Node-RED runs in an iframe when using ingress.
Seems like the logic behind showing the pull-out label is not working when it is not stuck on the far left end of the screen.

PS: You can use Node-RED without Ingress if you'd like. Ensure there is a port assigned in the "Network" section of the add-on configuration and point your browser directly to it.

**Comment by simonk83** [comment]
Gotcha, thanks frenck :)
