### ISSUE TITLE
Not simple to side the HomeAssistant sidebar to make Node-RED full screen

### ISSUE THREAD

**Issue by simonk83** [hassio-addons/addon-node-red#224]
# Problem/Motivation

With Ingress, there's no option/hamburger button to hide the HA sidebar. With this open, and both Node-RED sidebars open, the actual usable flow real estate is dramatically reduced (unless you have a gigantic monitor I suppose).

![image](https://user-images.githubusercontent.com/518440/57975433-6db0a480-7a0c-11e9-9db1-f68a35aa6374.png)

vs

![image](https://user-images.githubusercontent.com/518440/57975439-8456fb80-7a0c-11e9-9a11-b0c88b8bce40.png)

## Proposed changes

Could we either have an option to hide the HA sidebar when using Ingress tabs, or have an option to open NR full screen/width?

**Comment by frenck** [comment]
That is not something I can do anything about. That is a Home Assistant (more specifically an Hass.io Polymer frontend) feature request.

Feel free to open up an issue on that end.

**Comment by simonk83** [comment]
Just for anyone else who comes across this and also isn't aware, if you assign a port in the node-red addon settings, you can then access NR directly (full screen).
