### ISSUE TITLE
HTTP Node no longer allowing incoming connections...

### ISSUE THREAD

**Issue by Swiftnesses** [hassio-addons/addon-node-red#227]
Using the latest version, my flows with incoming HTTP requests no longer work.

Nothing has changed with my config, but trying to GET or POST etc to Node Red results in a 404 error?

**Comment by Swiftnesses** [comment]
I see the request in the log:

[24/May/2019:23:19:56 +0100] 404 -(192.168.1.100) GET /test HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36)

But the flow no longer runs (no output to debug either).

**Comment by Swiftnesses** [comment]
Just noticed the BREAKING change: https://github.com/hassio-addons/addon-node-red/pull/214

This explains it, I now need to rebuilt 50+ flows...

**Comment by sinclairpaul** [comment]
The change was done to allow non-authenticated access to HTTP nodes, which several people logged issues for, apologies that it broke your use case.  Going to close the issue.
