### ISSUE TITLE
Current state node: override topic doesn´t work after last add-on update

### ISSUE THREAD

**Issue by IsaTTeN** [hassio-addons/addon-node-red#229]
# Problem/Motivation

Current-state node doesn´t  pass the state of the entity being checked, but instead passes the message that triggered the node. The check-box "override topic" doesn´t appear to have any effect

## Expected behavior

I expected the current state node to pass the state of the entity_id being polled, in cases where "override topic" are checked.

## Actual behavior

Message of triggering node is passed

## Steps to reproduce

My current config:

    Hassio / Home Assistant 0.93.2 (Ubuntu 18/Docker)
    Node-red addon 3.1.1

Flow where I have the problem:
Overall flow:
- With a single click of Aqara switch the Bedroom Table toggle. This work ok
- With a double click of Aqara Switch the flow should switch ON the bedroom and Sinfonier lights if Sinfonier light is ON, or switch OFF the bedroom and Sinfonier lights if Sinfonier light is OFF. This is not working

![imagen](https://user-images.githubusercontent.com/20249994/58412650-cae0d180-806e-11e9-9975-21394fd30941.png)

debug1:

```
xiaomi_aqara.click : msg.payload : Object
object
event_type: "xiaomi_aqara.click"
entity_id: "binary_sensor.switch_158d0001b19ae3"
event: object
entity_id: "binary_sensor.switch_158d0001b19ae3"
click_type: "double"
```

debug2:

```
xiaomi_aqara.click : msg.payload : Object
object
event_type: "xiaomi_aqara.click"
entity_id: "binary_sensor.switch_158d0001b19ae3"
event: object
entity_id: "binary_sensor.switch_158d0001b19ae3"
click_type: "double"
```

debug3:

```
xiaomi_aqara.click : msg.payload : Object
object
event_type: "xiaomi_aqara.click"
entity_id: "binary_sensor.switch_158d0001b19ae3"
event: object
entity_id: "binary_sensor.switch_158d0001b19ae3"
click_type: "double"
```

debug4:

```
binary_sensor.switch_158d0001b19ae3 : msg.payload : string[3]
"off"
```

debug5:
Nothing

debug6:

```
binary_sensor.switch_158d0001b19ae3 : msg.payload : string[3]
"off"
```

The initial state was both lights ON, the expected behaviour should be switch OFF both lights, but is not happening because the node 4 doesn´t see the sinfonier light state

This is the internal of the Current State Node (Sinfonier State?):
![imagen](https://user-images.githubusercontent.com/20249994/58412936-77bb4e80-806f-11e9-9dc5-61921a4ae11e.png)

**Comment by frenck** [comment]
This is not an add-on thing. Please report the issue with the Home Assistant Websocket node for HA. Thanks.
