### ISSUE TITLE
Unable to install I2c module

### ISSUE THREAD

**Issue by nos86** [hassio-addons/addon-node-red#230]
# Problem/Motivation
I'm not able to install node-red-contrib-i2c even if the raspberry pi has been configured the I2C interface and the i2c-1 device is present in the dev folder.

I tried to install this module from Nodered UI and from terminal (through Portainer)

## Expected behavior
I'm expecting to install it without problems.

## Actual behavior
I'm receiving the following error 

> > bcrypt@3.0.5 install /opt/node_modules/bcrypt
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.5/bcrypt_lib-v3.0.5-node-v64-linux-arm-musl.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.5 and node@10.14.2 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
> gyp ERR! build error
> gyp ERR! stack Error: not found: make
> gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
> gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
> gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
> gyp ERR! System Linux 4.14.98-v7
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/opt/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
> gyp ERR! cwd /opt/node_modules/bcrypt
> gyp ERR! node -v v10.14.2
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> node-pre-gyp ERR! System Linux 4.14.98-v7
> node-pre-gyp ERR! command "/usr/bin/node" "/opt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /opt/node_modules/bcrypt
> node-pre-gyp ERR! node -v v10.14.2
> node-pre-gyp ERR! node-pre-gyp -v v0.12.0
> node-pre-gyp ERR! not ok
> Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> 
> > i2c-bus@1.2.5 install /opt/node_modules/i2c-bus
> > node-gyp rebuild
> 
> gyp ERR! build error
> gyp ERR! stack Error: not found: make
> gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
> gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
> gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
> gyp ERR! System Linux 4.14.98-v7
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /opt/node_modules/i2c-bus
> gyp ERR! node -v v10.14.2
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> [            ......] - install: info lifecycle i2c-bus@1.2.5~install: Failed to exec install scrip[            ......] - install: info lifecycle i2c-bus@1.2.5~install: Failed to exec install scrip[            ......] - install: info lifecycle i2c-bus@1.2.5~install: Failed to exec install scrip[            ......] - install: info lifecycle i2c-bus@1.2.5~install: Failed to exec install scrip[            ......] - install: info lifecycle i2c-bus@1.2.5~install: Failed to exec install scripnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.5 (node_modules/bcrypt):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.5 install: `node-pre-gyp install --fallback-to-build`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! i2c-bus@1.2.5 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the i2c-bus@1.2.5 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Steps to reproduce
`npm install node-red-contrib-i2c`
> (How can someone else make/see it happen)

## Proposed changes

<blockquote></blockquote>

**Comment by sinclairpaul** [comment]
This may help https://github.com/hassio-addons/addon-node-red/issues/148

**Comment by nos86** [comment]
Hello @sinclairpaul ,
I solved the problem of installing the module; but then I'm not able to see the i2c-1 device in docker container even if I remove the protected mode option.

Could you help me to fix this issue?

Thanks in advance,
Salvo
