### ISSUE TITLE
Timezone for Events State Node is not using my current Time zone

### ISSUE THREAD

**Issue by almostserious** [hassio-addons/addon-node-red#235]
# Problem/Motivation

> When checking the states of the message from any event that comes from Home Assistant the Time it shows to the current time is exactly 2h off. It looks like its not using the Time Zone i set in my config.yaml. 

![image](https://user-images.githubusercontent.com/14896478/58752870-6e3e4600-84b6-11e9-9820-79a93c7551ac.png)

## Expected behavior

> The time shown in the state, should be current time.

## Actual behavior

> The time shown in the state is in a different time zone

## Steps to reproduce

> Check the full message of any Event State change.

## Proposed changes
>  Maybe there can be an option to override the Time zone in the options?

**Comment by Appyx** [comment]
I think I have the same issue...

The time has a 2 hour offset.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/18675385/59966914-0ca45100-9523-11e9-886f-046df05142e3.png">

**Comment by sinclairpaul** [comment]
Can you confirm which O/S you are running?, copying the information from the Startup log will be ok.

**Comment by sinclairpaul** [comment]
I'll assume actually its HassOS (i.e. the image on a Pi), I believe that the underlying OS will use UTC.  Either that or a different base OS that has the UTC timezone set.  In order to set the specific Timezone for the NodeRed addon add the following to your /config/node-red/settings.js file:

```process.env.TZ = "America/Toronto";```

You will need to enter your correct timezone, I would suggest you place it above the line that states "module.exports = {" (44 by default).

**Comment by Appyx** [comment]
@sinclairpaul, you were right concerning my OS. I tried adding the TZ environment variable as suggested and then restarted home assistant. The time is still wrong (I even tried to trigger a node with an inject node).

**Comment by sinclairpaul** [comment]
@Appyx Did you restart the Node Red addon?, the configuration is for Node Red not Home Assistant.

**Comment by Appyx** [comment]
Oh I thought that restarting home assistant restarts all docker containers...
Now it's working. Thank you very much 👍

**Comment by sinclairpaul** [comment]
Closing this out, the original issue logged is the known behaviour, the time stamp isn't incorrect, its logged in UTC (the +00:00 part).  Node Red should interpret this fine if its Timezone is set correctly.
