### ISSUE TITLE
ha-wait-until node is throwing errors after most recent update

### ISSUE THREAD

**Issue by arretx** [hassio-addons/addon-node-red#239]
# Problem/Motivation

After updating to 3.1.3, all of my flows that contain wait nodes are reporting mis-configuration.

## Expected behavior

I've been using wait nodes as a delay between nodes, primarily utilizing the 2nd output upon timeout to pass the message to the next node.

## Actual behavior

Unable to deploy without configuration error notification.

## Steps to reproduce

Not sure what caused it.  Add a wait node to the flow with only a timeout period and try to deploy.

## Proposed changes

I leave this sort of thing up to the geniuses amongst us.

Another thing to note.  Some of the text coloring changed on some of the nodes after the most recent update.  I presume this is related to the state check outputs being swapped...so I'll be careful about editing those.

**Comment by frenck** [comment]
Please report this issue with the nodes affected, from an add-on perspective, there is nothing I can do.
