### ISSUE TITLE
Unable to find i2c device

### ISSUE THREAD

**Issue by nos86** [hassio-addons/addon-node-red#242]
# Problem/Motivation
I have installed i2c module on Raspberry Pi and I can see it in the devices list; however I'm not able to see the i2c-1 device in NodeRed docker container even if I remove the protected mode option.

Could you help me to fix this issue?

## Expected behavior
> See the i2c-1 as device mapped in docker container

## Actual behavior

> device is not available and if I try to use it in nodered, no slaves can be found

## Steps to reproduce

> Install node-red-contrib-i2c and use Scan block to find attached slaves

**Comment by frenck** [comment]
Please provide information on your device and logs so I can get a reproduction if needed.
