### ISSUE TITLE
Expose option to enable NodeRED projects

### ISSUE THREAD

**Issue by danrspencer** [hassio-addons/addon-node-red#245]
# Problem/Motivation

Enabling NodeRED projects would make it much easier to backup flows to GitHub.

See: https://nodered.org/docs/user-guide/projects/

## Expected behavior

Turning on the projects flag would enable the projects feature in NodeRed.

## Actual behavior

N/A

## Steps to reproduce

N/A

## Proposed changes

Add a `projects` boolean flag which maps to 
```
editorTheme: {
       projects: {
           enabled: true
       }
   },
``` 
in the `settings.json`.

<blockquote><div><strong><a href="https://nodered.org/docs/user-guide/projects/">Node-RED : Projects</a></strong></div></blockquote>

**Comment by frenck** [comment]
That is already exposed...

Your node-red dir (and thus `settings.json`) is in `/config/node-red`.
