### ISSUE TITLE
im trying to install node-red-contrib-node-tradfri but i only get error

### ISSUE THREAD

**Issue by Golab** [hassio-addons/addon-node-red#267]
im trying to install node-red-contrib-node-tradfri but when i restart node-red then i get error masseg

my settings is

{
  "credential_secret": "xxxxx",
  "dark_mode": false,
  "http_node": {
    "username": "xxxxx",
    "password": "xxxxx"
  },
  "http_static": {
    "username": "",
    "password": ""
  },
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [
    "node-red-contrib-node-tradfri"
  ],
  "init_commands": []
}

Log
Hunk #1 succeeded at 530 (offset -1 lines).
npm notice created a lockfile as package-lock.json. You should commit this file.
removed 3 packages in 1.371s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[16:32:53] INFO: Starting installation of custom NPM/Node-RED packages...
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
> node-aead-crypto@1.1.6 install /opt/node_modules/node-aead-crypto
> node lib/install.js
running default installation script
> node-aead-crypto@1.1.6 install:default /opt/node_modules/node-aead-crypto
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/AlCalzone/node-aead-crypto/releases/download/v1.1.6/node-v64-linux-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-aead-crypto@1.1.6 and node@10.16.0 (node-v64 ABI, musl) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.19.20
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/node_modules/node-aead-crypto/build/Release/node-v64-linux-arm/node_aead_crypto.node" "--module_name=node_aead_crypto" "--module_path=/opt/node_modules/node-aead-crypto/build/Release/node-v64-linux-arm" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /opt/node_modules/node-aead-crypto
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/node-aead-crypto/build/Release/node-v64-linux-arm/node_aead_crypto.node --module_name=node_aead_crypto --module_path=/opt/node_modules/node-aead-crypto/build/Release/node-v64-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/node_modules/node-aead-crypto/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.19.20
node-pre-gyp ERR! command "/usr/bin/node" "/opt/node_modules/node-aead-crypto/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/node_modules/node-aead-crypto
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/node-aead-crypto/build/Release/node-v64-linux-arm/node_aead_crypto.node --module_name=node_aead_crypto --module_path=/opt/node_modules/node-aead-crypto/build/Release/node-v64-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-aead-crypto@1.1.6 install:default: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-aead-crypto@1.1.6 install:default script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-11T14_33_23_346Z-debug.log
child_process.js:669
    throw err;
    ^
Error: Command failed: npm run install:default
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (/opt/node_modules/node-aead-crypto/lib/install.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-aead-crypto@1.1.6 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-aead-crypto@1.1.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-11T14_33_25_066Z-debug.log
[16:33:25] FATAL: Failed installing npm package node-red-contrib-node-tradfri
[cont-init.d] user.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment]
You are missing `make`:

`gyp ERR! stack Error: not found: make`

See add-on options on how to add system dependencies.
