### ISSUE TITLE
Allow to disable authentication for http node

### ISSUE THREAD

**Issue by giangvo** [hassio-addons/addon-node-red#27]
Hi,

My use case is that I want IFTTT to make requests to node-red but because IFTTT does no support basic authentication or setting headers.

Currently, in the config, we need to set `http_node` with username and password.  It would be great if we can make it optional so we can disable authentication for http node.

Thanks & Regards,
Giang Vo

**Comment by tjorim** [comment]
I don't use the node-red ifttt combination myself, but you should be able to use basic authentication anyway: http://bfy.tw/JjV2

Although it's not recommended, it should also be possible to do what you want. Leave both username and password empty to disable authentication.
You'll also need to set another option to acknowledge it's unsafe, read the documentation for that: https://github.com/hassio-addons/addon-node-red/blob/master/README.md#option-leave_front_door_open
