### ISSUE TITLE
brand new install, can't login to web port

### ISSUE THREAD

**Issue by thayneq** [hassio-addons/addon-node-red#288]
I have been banging my head against this for a few hours.

I installed hass.io fresh. I added the node-red addon fresh.

I have set a credential secret, disabled SSL, and no other changes. Ingress login works, but when I try to login to the service directly, http://192.168.2.4:1880 I am presented with a username and password. I have tried everything under the sun, and nothing works. I even blew away all my .storage and config files and it still doesn't work. I tried 3 different web browsers, including iOS devices, and no dice. What gives? This is a brand new fresh install, and I'm not doing anything fancy.

I simply want to be able to use nodered via an IP address, so I can eventually put it behind a reverse proxy, but accessing it directly simply doesn't allow anyone to authenticate.

**Comment by thayneq** [comment]
I can't seem to find any errors in any logs. I've set logging level to debug.

**Comment by thayneq** [comment]
a few things I've tried:
- changing to port 1881. No luck.
- deleted .storage directory and set up a new user account. No luck.
- deleted nodered directory and uinstalled the addon. Reinstalled. No luck.

It seems the only way I can use nodered is with the ingress option after logging into the HA webUI. This is not ideal at all. Is there really no way to directly access the nodered interface directly? I know it's possible if you use the docker/node-red package, because it provides a web-form login that works great. Can't this addon be updated to do something similar, or am I missing something obvious? Based on my google searches, and looking through the closed issues list on this github, this is a very common issue.

**Comment by thayneq** [comment]
oh, I also tried using a much simpler password with no symbols or digits in HA in case it was getting confused, per a comment I read somewhere. That didn't work either.

**Comment by thayneq** [comment]
I also tried deleted any old auth tokens per another comment. None of my browsers had any existing tokens. I also disabled my firewalls in case something was happening there.

**Comment by sinclairpaul** [comment]
As discussed on Discord there appears to be upstream issues that may cause this, please use Ingress temporarily for now while it is resolved.

**Comment by sinclairpaul** [comment]
Should be resolved with the supervisor that has just been released.

**Comment by thayneq** [comment]
confirmed fixed. Thanks!!
