### ISSUE TITLE
Access to the bluetooth stack

### ISSUE THREAD

**Issue by elmarburke** [hassio-addons/addon-node-red#289]
# Problem/Motivation

I want to access data from a device that sends out data through bluetooth le advertising. Running node-red locally with [node-red-contrib-generic-ble](https://flows.nodered.org/node/node-red-contrib-generic-ble) installed works perfectly, but in hass.io i could not find any device. I guess that the container don't have access to the bluetooth stack, [I found a hint](https://hub.docker.com/r/dsample/node-red-iot/) to use `--net=host` on the `docker create` command. But this would expose the complete network to the container which is also not wished.

## Expected behavior

Container is able to find and communicate with bluetooth LE devices

## Actual behavior

n/a

## Steps to reproduce

1. install/add `node-red-contrib-generic-ble` to the node dependencies
2. add a "Generic BLE" input step
3. Double-click on the node
4. hit the pencil symbol
5. Search results should be populated (after a moment)

## Proposed changes

![no idea](https://media.giphy.com/media/37smQpbdHrBjVsxEhM/giphy.gif)

**Comment by sinclairpaul** [comment]
Could you share the addon startup log?  What hardware are you running?

**Comment by sinclairpaul** [comment]
Closing as no response.
