### ISSUE TITLE
Update pre-installed nodes

### ISSUE THREAD

**Issue by OperatorB** [hassio-addons/addon-node-red#29]
Hi there,

I have opened this issue because I can not find a solution for updating such node-red nodes which came pre-installed with node-red.
Node-Red's "Manage palette" also not functional from this point of view. "Module not locally installed" message popping up.
Also after ssh into my Raspberry Pi I am not able to locate these node modules so it is not possible to remove the old then install newer modules.

Do anyone has a intel on this?

**Comment by frenck** [comment]
Updates are pending for the next release and are automatically pushed and updated into this repository by Greenkeeper (which monitors all releases).

Unfortunately, I'm currently on a holiday which delays releases. Sorry about that.

**Comment by OperatorB** [comment]
Thanks for the quick answer.
Is it possible to delete/uninstall one of such pre-installed node module? (maybe through ssh)

**Comment by frenck** [comment]
No.
