### ISSUE TITLE
Add pull request to add home assistant  /backup directory  to accessible direcories

### ISSUE THREAD

**Issue by chrisn-au** [hassio-addons/addon-node-red#296]
# Problem/Motivation

Cant access the /backup directory from within node red. Am wanting to automate backups uploads to NAS devices

## Expected behavior

Be able to access the direcory

## Actual behaviour

Not able to

## Steps to reproduce

Use any file node within node red to attempt to access the /backup directory

## Proposed changes

Create a pull request to update node-red/config.json file

Update

 "map": [
    "config:rw",
    "share:rw",
    "ssl"
  ],

to

 "map": [
    "config:rw",
    "share:rw",
    “backup:rw”,
     "ssl"
  ],

Is there any reason why this is a bad idea ?

**Comment by frenck** [comment]
There is a security complication with this. Accessing backups will allow node-red to access everything...

**Comment by frenck** [comment]
Closing this, since node-red is able to access the Hassio API that can tell you the states of snapshosts/backups.
