### ISSUE TITLE
Websocket Input and Websocket Out Nodes

### ISSUE THREAD

**Issue by GACHAPO** [hassio-addons/addon-node-red#299]
#Websocket nodes are not connecting as they do in Node Red standalone version

> (Why the issue was filed)

## Connected Nodes issue

> (What you expected to happen)

## Websocket Nodes connect and enable link to simple website as set out in Node Red lecture http://noderedguide.com/node-red-lecture-3-example-3-7-using-websockets-with-node-red/ 

>No connection.  Also, when I edit the template node with the HTML, CSS and Javascript when the syntax highlight is on css it shows errors which are not shown in standalone node red.

## copy flows from standalone node red to Hass.io Node Red
![Node Red Websocket](https://user-images.githubusercontent.com/26501171/64067940-619dcb00-cc28-11e9-8000-0ba247a3791b.JPG)
![Hassio Node Red](https://user-images.githubusercontent.com/26501171/64067941-6b273300-cc28-11e9-8bc0-7f74b9965e05.JPG)

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote><div><strong><a href="http://noderedguide.com/node-red-lecture-3-example-3-7-using-websockets-with-node-red/">Node-RED: Lecture 3 – Example 3.7 Using Websockets with Node-RED – Node RED Programming Guide</a></strong></div></blockquote>

**Comment by sinclairpaul** [comment]
So you want something like this?

![image](https://user-images.githubusercontent.com/24625998/64068228-51bfc000-cc03-11e9-97e6-f21ca9fba80f.png)

**Comment by GACHAPO** [comment]
Yes

**Comment by sinclairpaul** [comment]
So that works, will close the issue, details are in the screenshot.

**Comment by GACHAPO** [comment]
When I sais yes,I meant that's what I want, not what I get.  There's no
connection when I try and feed in your websocket path.

Please advise?

**Comment by sinclairpaul** [comment]
When I recreate it, I no longer see the connected info, however the flow works.
<details> 
[{"id":"ad9d106b.f403d","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"e60f811.747c68","type":"websocket in","z":"ad9d106b.f403d","name":"","server":"815d9e43.7fca","client":"","x":370,"y":120,"wires":[["38fc139a.646a2c"]]},{"id":"4d5ff9dd.f720b8","type":"websocket out","z":"ad9d106b.f403d","name":"","server":"","client":"7bb6c9e3.850368","x":330,"y":260,"wires":[]},{"id":"5499ceba.37423","type":"inject","z":"ad9d106b.f403d","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":180,"wires":[["4d5ff9dd.f720b8"]]},{"id":"38fc139a.646a2c","type":"debug","z":"ad9d106b.f403d","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":600,"y":140,"wires":[]},{"id":"815d9e43.7fca","type":"websocket-listener","z":"","path":"/ws/example","wholemsg":"false"},{"id":"7bb6c9e3.850368","type":"websocket-client","z":"","path":"ws://localhost:1880/endpoint/ws/example","tls":"","wholemsg":"false"}]
</details>

**Comment by sinclairpaul** [comment]
To add, if I delete and recreate the endpoints, the connected flag appears, this is unlikely to be an issue with the addon, but more likely a Node-Red/Docker issue.

**Comment by GACHAPO** [comment]
Interestingly my webpage is called simple and yours is called example.
Example connects, but simple doesn't my end...................not sure why?

**Comment by sinclairpaul** [comment]
Does the flow actually work?, I am thinking this is actually a cosmetic issue.  Also please test using http://yourhaaddress:1880 as well.

**Comment by GACHAPO** [comment]
I'm not running docker.

Node Red is loaded through Hassio.

This is where I am at;

[image: image.png]

[image: image.png]
Has always worked previous;y when not through Hassio and Node Red
standalone.

**Comment by GACHAPO** [comment]
Hi Paul,

Please see below the unexpected tokens and indent errors in the template
node.  This is the same node used successfully in the standalone Node Red.
Could this possibly be where the issue now lies?

[image: image.png]

Glenn

**Comment by GACHAPO** [comment]
Hi Paul,

Am I best to put this issue back through Github?

Kind Regards

Glenn

**Comment by sinclairpaul** [comment]
@GACHAPO You already are.., replying to the emails updates the Github issue.  Unfortunately it does not seem to do well with the images, so can you post those directly on the issue.

**Comment by GACHAPO** [comment]
Thanks Paul,

I have decided to go back and use the Node Red Library version of a website as found here and import the flow to Node Red running in docker and also in Hassio - Node Red to see the difference.

https://flows.nodered.org/flow/8666510f94ad422e4765

Docker - version shows

![image](https://user-images.githubusercontent.com/26501171/64117701-c3c41080-cd8d-11e9-9e3f-e7cf55e23abd.png)

Webpage served at ipaddress:1880/simple

![image](https://user-images.githubusercontent.com/26501171/64117763-ef46fb00-cd8d-11e9-8eba-5f1fd52b859e.png)

Hassio - Node Red

![image](https://user-images.githubusercontent.com/26501171/64117850-24534d80-cd8e-11e9-9975-c8958a8aea0f.png)

No webpage served

Only other difference is i'm using duckdns on Hassio and local on docker.  However I can reach node  red admin duckdns.org:1880 without an issue.

Thanks in advance

**Comment by sinclairpaul** [comment]
I think I see the issue, can you make sure you connect to the site at http://ipaddress:1880/endpoint/simple the **endpoint** part is important

As the addon uses HA auth we break out the Dashboard/Hosting parts to a subfolder.

![image](https://user-images.githubusercontent.com/24625998/64118585-ed694180-cd65-11e9-817d-0a7e98b1ad12.png)

If you look at the nodes, they will have a message on them like the following

![image](https://user-images.githubusercontent.com/24625998/64118720-2dc8bf80-cd66-11e9-8446-367e4d44ce10.png)

**Comment by GACHAPO** [comment]
Nice one Paul,

This is now resolved - thanks so much for your help
