### ISSUE TITLE
Cant connect to hass.io instance

### ISSUE THREAD

**Issue by acordill** [hassio-addons/addon-node-red#30]
# Problem/Motivation

>Problem connecting to hass.io instance

## Expected behavior

>node-red connec to hass.io
## Actual behavior

>[error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>

## Things I tried

Tried uninstalling and reinstalling node-red addon, including clearing node-red folder from config directory

Tried changing server address to 192.168.1.3:8123, localhost:8123, my_addy.duckdns.org:8123

## Steps to reproduce

>Not sure how it happened.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The server address should be: `http://hassio/homeassistant`.
Please change the URL and restart the after after that.

**Comment by frenck** [comment]
Sorry I was to quick... (early morning, need coffee :S)

**Comment by lpt2007** [comment]
Hi I have the same problem. I upgraded hassio form 0.72.1 to hassio 0.77.3. And now I have error: [error] [server:hassio] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://ip:8123 <password redacted>

**Comment by frenck** [comment]
@lpt2007 Your issue is not related, `http://ip:8123` is incorrect. Use `http://hassio/home-assistant` as the server URL, deploy the workflow, restart the add-on.

**Comment by frenck** [comment]
@acordill A supervisor update has been released (130), which contains bug fixes for authentication. Could you check if that solves your problem?

Secondly, make sure the internal IP is not banned (check ip_bans.yaml).

**Comment by acordill** [comment]
Ended up redoing my hassio instance from scratch.  Works now.  Had already changed address to what was posted to no avail.

**Comment by frenck** [comment]
@lpt2007 As before, this is not related. Please stay on topic. For general support (which you need in this case), join on Discord, we can help you quick and easy. (https://discord.me/hassioaddons)

@acordill 👍
