### ISSUE TITLE
node "file in" location

### ISSUE THREAD

**Issue by GACHAPO** [hassio-addons/addon-node-red#304]
# Need to store data from a sensor in a file.

> Current standalone Node Red will store to a directory Door and a file Dataflush and is set in the node as Door/Dataflush as the path

## File with a list of sensor readings.  Both file and directory created.  With Node Red in Hass.io I have created the following directory structure.  /home/pi/Door/Dataflush and I have tried with and without the absolute path to no avail.

I wonder if there is a hidden file structure I should be aware of and if the data is being stored elsewhere?

Thanks in advance

**Comment by frenck** [comment]
It is recommended to use the `/share` folder for sharing data between add-ons or Home Assistant.

**Comment by GACHAPO** [comment]
Thanks for coming back to me so promptly.

I made file in the share directory and I have changed the node to the absolute path /share/Dataflush and share/Dataflush to no avail.  No data ever populates the file.

I there anything else I am missing please?
