### ISSUE TITLE
node-red addon stops working after a few days

### ISSUE THREAD

**Issue by fred-c1** [hassio-addons/addon-node-red#316]
Hello,

At startup node-red works always fine.
After a few days (usually 1 to 5 days) it stops working:
- not answer from the "design" page
- no answer from the dashboard

The log at the bottom of this page shows nothing special:
http://192.168.0.120:8123/hassio/addon/a0d7b954_nodered

Restarted the addon "fixes" the problem.

How I can investigate this problem?

Thanks!

**Comment by sinclairpaul** [comment]
Can you post the log here and confirm the HA version, Addon version and hardware you use.  Also do you have custom nodes, have you tried disabling your flows one by one to try to work out the cause?

**Comment by fred-c1** [comment]
Here is a 1st answer:

hardware => Raspberry Pi 3B+

software versions => everything was up to date about 2 months ago

"custom nodes" => I hope this means this:   (from package.json file)
    "dependencies": {
        "node-red-contrib-mopidy": "~2.0.2",
        "node-red-contrib-os": "~0.1.7",                          but no more used as far as I know
        "node-red-contrib-presence-faker": "~1.4.0",       possibly added just before the problem started
        "node-red-dashboard": "~2.9.8",
        "node-red-node-twilio": "~0.1.0"
    }

"have you tried disabling your flows one by one to try to work out the cause?"
Not yet. This would take a lot of time because it can take up to 5 days before the problem appears.

*******************
I have now upgraded HA and node-red addon to the lastest versions.
I have also changed the log level to     "log_level": "info"    with the hope to see more info in the log
node-red just restarted
just need to wait now ????

Thanks!

**Comment by fred-c1** [comment]
Another occurrence of the problem today.

Last week I have updated "everything" ??? to the lastest version:
This shown after the addon is started:
"
-----------------------------------------------------------
 Add-on version: 4.2.1
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.99.3
 Supervisor version: 189
-----------------------------------------------------------
"

The log shown on 192.168.0.120:8123/hassio/addon/a0d7b954_nodered
is empty
more precisely there is just 1 line:
"
[09/Oct/2019:20:32:23 +0200] 499 -(internet IP address) GET /endpoint/ui/ HTTP/2.0 (Mozilla/5.0 (Android 7.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0)
"
This seems to indicate that a new log was started after the problem appears
and that the new log is only recording the http connection attempts.

Any suggestion on how to investigate this problem would help.
For example can I find the "old/previous log file" somewhere?
Thanks.

**Comment by fred-c1** [comment]
@sinclairpaul do you have any suggestion for me?
Thanks

**Comment by sinclairpaul** [comment]
The logs aren't persistent across container restarts to reduce file writes.  My suggestion is still to remove the custom nodes you are using to see which is causing Node Red to error and restart, there really is not much we can do from an addon perspective.

**Comment by fred-c1** [comment]
@sinclairpaul

OK, I will try the "remove the custom nodes + test/wait" idea if there is no other solution.

About "The logs aren't persistent across container restarts to reduce file writes.":
Apparently a "new log" 
(log shown on 192.168.0.120:8123/hassio/addon/a0d7b954_nodered)
is started before I restart the addon.
Is it possible to find the "old log" before I restart the addon?
If yes, were/how can I find the "old log"?
Thanks

**Comment by frenck** [comment]
@fred-c1 The only log output can be found in the add-on configuration screen, there are not other locations.

**Comment by fred-c1** [comment]
@frenck     thanks for your answer
I will move to "remove the custom nodes + test/wait"
just not easy because it can take up to 10 days before the problem appears.

My "custom nodes" from package.json file are:
"dependencies": {
"node-red-contrib-mopidy": "~2.0.2",
"node-red-contrib-os": "~0.1.7",            but no more used as far as I know
"node-red-contrib-presence-faker": "~1.4.0",              possibly added just before the problem started
"node-red-dashboard": "~2.9.8",
"node-red-node-twilio": "~0.1.0"
}
