### ISSUE TITLE
UI lags with large number of nodes

### ISSUE THREAD

**Issue by iRanduMi** [hassio-addons/addon-node-red#324]
# Problem/Motivation

The UI lags with large numbers of nodes within a single flow.  This behavior is not present in a dedicated docker container of node-red running the same version (0.20.8) and identical flows/npms.

Accessing node-red both locally and via port 1880 (without Hass.io iframe) experiences the same behavior.

## Expected behavior

The UI should be lag free.

## Actual behavior

The UI experiences massive amount of lag.

## Steps to reproduce

1) Proceed into Node-Red hass.io addon
2) Import the flow provided. 
3) Scroll through the flow
4) Observe the delayed performance
5) Double click any node
6) Observe the delayed performance

## Proposed changes

Unfortunately, not. 
[node-red logs.txt](https://github.com/hassio-addons/addon-node-red/files/3684012/node-red.logs.txt)

[flows.txt](https://github.com/hassio-addons/addon-node-red/files/3684021/flows.txt)

**Comment by sinclairpaul** [comment]
I can load your flow and don't see any issues with responsiveness, however obviously I don't have your entities so nothing is being fetched from HA.

Can you restart the addon and post the log, also can you post the supervisor log for when you see the issue.  Did you also check that your server node is as follows:
![image](https://user-images.githubusercontent.com/24625998/66127278-4ae8ec00-e5b9-11e9-9652-e85d726bfbc8.png)

**Comment by iRanduMi** [comment]
I've restarted the addon.  The issue still occurs.  The logs are attached.  Please let me know if this is not what you're looking for.
[node-red logs 2019.10.03.txt](https://github.com/hassio-addons/addon-node-red/files/3686982/node-red.logs.2019.10.03.txt)

**Comment by sinclairpaul** [comment]
I ideally wanted to see the startup information to confirm the versions and hardware and the hassio supervisor log.
These don't look correct to me:
`[03/Oct/2019:08:57:15 -0700] 200 192.168.0.122, 172.30.32.1(172.30.32.2) GET /homeassistant/f9175015.e1766/services HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36)`

Can you please confirm how you have the Homesassistant server configured in Node Red as per the previous image I posted.

**Comment by frenck** [comment]
Since you experience the same issue without Ingress, I believe this issue should be opened at node-red or the ha node-red node module.
