### ISSUE TITLE
Will you update to 0.19.4 anytime soon?

### ISSUE THREAD

**Issue by vandalon** [hassio-addons/addon-node-red#33]
The title says it all :)

**Comment by ludeeus** [comment]
@vandalon There are already an open PR for that https://github.com/hassio-addons/addon-node-red/pull/31 ;)

**Comment by vandalon** [comment]
Oops. Sorry about that. But the hassio addon still installs 0.19.1

**Comment by ludeeus** [comment]
That is correct, it has not been merged, and therefore not been released.
info about PR: <https://help.github.com/articles/about-pull-requests/>
