### ISSUE TITLE
Does not accept !secret for username and passwords

### ISSUE THREAD

**Issue by austwhite** [hassio-addons/addon-node-red#333]
# Problem/Motivation
In the latest version of HA, plugins now can accept !secret for user names and passwords.
This is more of a request to add this feature to NodeRed plugin rather than a fault.
> (Why the issue was filed)
Home Assistant now accepts !secret for Hassio Plugins.  This provides an additional layer of security as it prevents usernames and passwords being visible via the User Interface.
This is a request to add this to NodeRed plugin for additional security.

**Comment by austwhite** [comment]
Ignore above.  I found out it does accept it.  I had a typing error that took me a few days to find

**Comment by bdcarr** [comment]
Hey @austwhite, what was your typing error? The config editor won't let me save with the following:
```{
  "credential_secret": !secret red_secret,
  "dark_mode": false,
  "http_node": {
    "username": "",
    "password": ""
  },
  "http_static": {
    "username": "",
    "password": ""
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": []
}```

**Comment by austwhite** [comment]
Yes.  The quotes are important.
My issue was a typo in the secrets file as it verifies the secrets file before it restarts/saves 🙂
