### ISSUE TITLE
Open ports required to monitor UDP / TCP Packets.

### ISSUE THREAD

**Issue by andylether** [hassio-addons/addon-node-red#34]
# Problem/Motivation

>Unable to see any udp / tcp packets. 

## Expected behavior

>debug windows displays received packets.

## Actual behavior

> nothing received unable to forward the ports  ie 55005/udp : 55005

## Steps to reproduce

> insert a udp packet on a different machine and try to receive it.

## Proposed changes

config to allow the declaration of the required ports. For example as found in the ssh addon.

 "ports": {
     "port number/tcp": port number
     "port number/udp": port number
 }  

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
![image](https://user-images.githubusercontent.com/43098184/45918180-f6297600-be7a-11e8-9015-d311b97a8f35.png)

**Comment by frenck** [comment]
This add-on runs on the host network. So every port is available instantly.
The suggested solution on adding a `port` section in the add-on configuration, won't work at all.
