### ISSUE TITLE
Updagrade from 4.2.1 to 5.0.0

### ISSUE THREAD

**Issue by mdgrab** [hassio-addons/addon-node-red#347]
# Problem/Motivation

Trying to upgrade 4.2.1 to 5.0.0 running hassio 
on system Ubuntu 18.04.2 LTS

## Expected behavior

successful upgrade

## Actual behavior

got error in logs 

ERROR (SyncWorker_4) [hassio.docker.interface] Can't install hassioaddons/node-red-amd64:5.0.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/node-red-amd64:5.0.0: No such image: hassioaddons/node-red-amd64:5.0.0").

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Check your storage, do you have enough space?

**Comment by frenck** [comment]
@mdgrab, @tjorim is right.
The 404 occurs when there is not enough disk space left to perform the upgrade operation.

**Comment by mdgrab** [comment]
Thank you gentlemen.  Swap file grew to consume all available disk space

**Comment by frenck** [comment]
Glad we were able to help out @mdgrab! 👍
