### ISSUE TITLE
googlehome notify node - get key from google failed

### ISSUE THREAD

**Issue by blackshoals** [hassio-addons/addon-node-red#36]
This node is in the Node Red addon has been failed for the last few days. It look like the google-tts-api version needs to be updated in the package.json for the node. I searched the addon code but could not locate it.

[]https://github.com/nabbl/node-red-contrib-google-home-notify/issues/25(url)

**Comment by blackshoals** [comment]
The fault does not appear to leave node red, so it doesn't show anything in the log. I assume it just stops the flow before passing the message to Google Home. There is just a message below the node with "get key from google failed"

**Comment by frenck** [comment]
There is nothing to be updated. The add-on already runs v0.0.6 of the node-red-contrib-google-home-notify.

For the latest release see:
https://www.npmjs.com/package/node-red-contrib-google-home-notify

Here you can see the add-on is running 0.0.6:

https://github.com/hassio-addons/addon-node-red/blob/26546f7302c634e1b352f4cf1da4b04d25b3dd03/node-red/package.json#L20

If you have any issues with the package, I suggest creating an issue at the GitHub of the node.

**Comment by blackshoals** [comment]
The npm package isn't fixed yet and I don't have the same reference to it in my addonpackage.json, so I wasn't sure if you might have forked it. Thanks for clarifying and your work on the addon.

I notice your git package.json shows 

>     "name": "hassio-addon-node-red",
    "version": "1.0.0",
    "description": "A visual tool for wiring the Internet of Things",

My hassio addon shows version 0.6.1 from the addon repository where it was last updated a month ago. Just wanted to check the addonbot is working OK.

**Comment by frenck** [comment]
`"version": "1.0.0",` is just a placeholder (since the add-on itself is not published on NPM, it doesn't matter).

The add-on version is 0.6.1 at this point and I expect an update any moment now.
