### ISSUE TITLE
Feature to uninstall npm packages

### ISSUE THREAD

**Issue by non092** [hassio-addons/addon-node-red#364]
Hi,
I'm trying to use node node-red-contrib-alexa-smart-home but it looks like it conflicts with node-red-contrib-alexa-home-skill
Any way I can remove completly node-red-contrib-alexa-home-skill ?
Maybe a feature should be added where you can remove packages included by default using something like this in the config file :
```
  "npm_packages": [
    -"node-red-contrib-alexa-home-skill"
  ],
```

**Comment by frenck** [comment]
This more advanced usage can be achieved using the `init_commands` options.

**Comment by non092** [comment]
Could you clarify if this the correct way to do it ?

  "init_commands": [
    "npm uninstall node-red-contrib-alexa-home-skill --save"
  ]

I was getting the following error when the command ran : node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@10.16.3 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
I add to add "build-base" to system_packages, then it seems to have removed it correctly

Also the node still appears in palette but cannot be enabled :

![image](https://user-images.githubusercontent.com/729962/68700006-75e53900-0584-11ea-852d-bf70a6671084.png)
