### ISSUE TITLE
v2.02 is the last version that works

### ISSUE THREAD

**Issue by G8YTZ** [hassio-addons/addon-node-red#365]
# Problem/Motivation Upgrade to v 3 and beyond and it is not possible to reliably connect to the dashboard "Connection Lost"

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Can you please share both the addon logs and the Hassio Supervisor log.

More details would be helpful as it is very difficult to help here, there are plenty of users of the latest version, so it would be a case of identifying your unique issue.
