### ISSUE TITLE
NodeRed 5.0.5 won't start after fresh install

### ISSUE THREAD

**Issue by yannoz** [hassio-addons/addon-node-red#389]
# Problem/Motivation

Config: Raspberry Pi 3+ /  Conbee II stick as Zigbee Gateway/ new SD card Class 10
hassos_rpi3-64-2.12.img
Hass.io Version 192

I've decided to change my SD card because i was suspecting it from some freeze and slowdown, and want to start with a fresh configuration, so i decided to reinstall everything from scratch.
after a fresh HASSIO install, I successfully installed some add-on: Configurator, Samba, Deconz, and finished by NodeRed. But No way to start this AddOn. 
I don't see any error either in the addon log and in the system log

please any idea where to look ? 
cheers !!! :)

## Expected behavior

 start the service and give access

## Actual behavior

 freeze and terminate without any error...

## Steps to reproduce
>Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 >Hass.io Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 >Add-on version: 5.0.5
 You are running the latest version of this add-on.
 System: HassOS 2.12  (aarch64 / raspberrypi3-64)
 Home Assistant version: 0.102.3
 Supervisor version: 192
-----------------------------------------------------------
 >Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
>[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
up to date in 2.816s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:01:25] INFO: Starting Node-RED...
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
6 Dec 19:01:35 - [info] 
Welcome to Node-RED
===================
6 Dec 19:01:35 - [info] Node-RED version: v1.0.3
6 Dec 19:01:35 - [info] Node.js  version: v10.16.3
6 Dec 19:01:35 - [info] Linux 4.14.98-v8 arm64 LE
6 Dec 19:02:47 - [info] Loading palette nodes
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
Terminated

----------------------------
System log: 

19-12-06 18:00:54 INFO (SyncWorker_9) [hassio.docker.interface] Clean addon_a0d7b954_nodered application
19-12-06 18:00:59 INFO (SyncWorker_9) [hassio.docker.addon] Start Docker add-on hassioaddons/node-red-aarch64 with version 5.0.5
19-12-06 18:01:04 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nodered
19-12-06 18:01:10 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_nodered

**Comment by frenck** [comment]
Seems like you have a custom node/pallet installed? That might be missing stuff. To be sure, rename your `node-red` config folder and restart the add-on to ensure it able to start from scratch.
