### ISSUE TITLE
Node-red and HA doesnt communicate without wifi connection

### ISSUE THREAD

**Issue by fremut** [hassio-addons/addon-node-red#390]
Hello to all, 

is there some possible settings? My node-red stops to communicate with HA server in case of wifi disconection (LAN connection is broked up).

I am using this settings:
<img width="413" alt="Snímek obrazovky 2019-12-08 v 0 04 51" src="https://user-images.githubusercontent.com/50186344/70381658-63290e80-194e-11ea-85c2-10113ecbcca2.png">

**Comment by sinclairpaul** [comment]
If you are using the addon, why are you changing the settings, it is pre-configured.  Please check the box that says I use Hass.io.

Also please post addon logs for your issue.

**Comment by fremut** [comment]
With checked box is the situation same. I have lights controls in node-red with using entites from zigbee2mqtt. And everything is working. After I shutted wifi connection. Mqtt server is working but node-red flows not. Everything started again after wifi connection is ready back.  Sorry but in node-red logger is everything seems ok. No new lines during this.
<img width="888" alt="Snímek obrazovky 2019-12-08 v 0 26 08" src="https://user-images.githubusercontent.com/50186344/70381808-5954da80-1951-11ea-9190-e272270b9baf.png">

**Comment by frenck** [comment]
Disconnects would show up in the logs...

The add-on uses an internal URL on the Hass.io network. From the add-on perspective, this is the right way to do it, and should be available when there is no connection to the device at all.

**Comment by fremut** [comment]
Sorry, I hadbad ip address of mosquito-mqtt broker (LAN) not internal. Thanks for your help!
