### ISSUE TITLE
Is there a way to solve module dependencies? 

### ISSUE THREAD

**Issue by naoki16n1100026** [hassio-addons/addon-node-red#4]
Is there a way to solve module dependencies?

I would like to add node-red-contrib-amazondash to the palette
It is an error because there is no libcap or something

**Comment by frenck** [comment]
Hi there, @naoki16n1100026! 👋 

It would not resolve these automatically for you, still, you can install them using the `system_packages` add-on setting.

For more information please see this section of the documentation:

https://github.com/hassio-addons/addon-node-red/blob/master/README.md#option-system_packages
