### ISSUE TITLE
Poll state shows false all the time

### ISSUE THREAD

**Issue by Mikro007** [hassio-addons/addon-node-red#403]
If I set a statement that should send true under < 4000 I get a green dot but the boolean always send false even if it should be true.

![logic](https://user-images.githubusercontent.com/22572811/71352078-a356d680-2575-11ea-9afa-96c66060a77d.png)
![settings](https://user-images.githubusercontent.com/22572811/71352090-a81b8a80-2575-11ea-9798-eca7220d2fdf.png)

**Comment by Mikro007** [comment]
RPI 4, latest hass.io

**Comment by sinclairpaul** [comment]
The issues in Github is for logging problems running the addon, as it is running and outputting we really can't help here.

I would suggest that you seek help on Discord or the Forums to help resolve your challenge.

With that said, I doubt your your state type is a Boolean, but an Integer.
