### ISSUE TITLE
AddOn not starting via HassIo Docker

### ISSUE THREAD

**Issue by iosif-bancioiu** [hassio-addons/addon-node-red#405]
# Problem/Motivation

AddOn not starting from HassIo (located inside docker)

## Expected behavior

Plugin should start

## Actual behavior

```
-----------------------------------------------------------
 Hass.io Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 5.0.7
 You are running the latest version of this add-on.
 System: Fedora 31 (Server Edition)  (amd64 / qemux86-64)
 Home Assistant version: 0.103.4
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
mkdir: can't create directory '/config/node-red/': Permission denied
[19:56:56] FATAL: Failed to create node-red configuration directory
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
```

## Steps to reproduce
1) create a linux server machine (i use fedora 31)
2) install docker (as root)
3) install hassio (as a docker container) (as root)
4) install the addon for node-red version 5.0.7 (from hass io add on manager)
5) add secret key and disable SSL
6) press start and you will get in the logs the lines from above

Attempted fixes. I tried to create the /config/node-red from docker my self using the command added in node-red.sh and i created it without any issues. But it can't find or cp the settings and flow files to complete the setup.....

**Comment by sinclairpaul** [comment]
This is unlikely to be related to the addon, but more than likely your configuration (any addon trying to write to /config will have the same issue).  Please consult the installation instructions for Hass.io at https://www.home-assistant.io/hassio/installation/

**Comment by iosif-bancioiu** [comment]
Problem found, looking for a permanent fix.

The problem is caused by SELinux in fedora.
