### ISSUE TITLE
Export file written with node-red (within socker container) to homecassistant directory structure

### ISSUE THREAD

**Issue by makkie2002** [hassio-addons/addon-node-red#408]
# Problem/Motivation

From within a nod-red flow I want to log to text files. I want these text files to be available outside the container.

## Expected behavior

See above

## Actual behavior

Files not available in home assistant directory structure

## Steps to reproduce

node-red import:

`[{"id":"a0e80e5d.d18be","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"a211a3e5.56538","type":"inject","z":"a0e80e5d.d18be","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":220,"y":220,"wires":[["4780688b.ac0858","d9d41248.6482b"]]},{"id":"4780688b.ac0858","type":"file","z":"a0e80e5d.d18be","name":"","filename":"/opt/test.txt","appendNewline":true,"createDir":false,"overwriteFile":"false","encoding":"none","x":450,"y":220,"wires":[[]]},{"id":"d9d41248.6482b","type":"file","z":"a0e80e5d.d18be","name":"","filename":"test.txt","appendNewline":true,"createDir":false,"overwriteFile":"false","encoding":"none","x":430,"y":120,"wires":[[]]}]`

## Proposed changes

It would be nice if a certain directory of the node-red container is mapped to a directory in the home-assistant directory structure (eg. /config/node-red/user)

**Comment by sinclairpaul** [comment]
Like this?
`[{"id":"4b317d0b.e52ec4","type":"file","z":"cf1d33be.3010a","name":"","filename":"/share/test.txt","appendNewline":true,"createDir":false,"overwriteFile":"false","encoding":"none","x":460,"y":220,"wires":[[]]}]`

**Comment by sinclairpaul** [comment]
I will add, you can also write to /config if you want to.

**Comment by makkie2002** [comment]
Thanks ... that was exactly what I was looking for!
