### ISSUE TITLE
TTN (The Things Network) not working anymore

### ISSUE THREAD

**Issue by makkie2002** [hassio-addons/addon-node-red#413]
# Problem/Motivation

TTN (The Things Network) not working anymore.

## Expected behavior

> (What you expected to happen)

## Actual behavior

I get an error "Flows stopped due to missing node types. - ttn app"
In the log I see:

```
5 Jan 01:47:19 - [warn] [node-red-contrib-ttn/ttn-app] Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v72-linux-arm-musl
Found: [node-v64-linux-arm-musl]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node'
Require stack:
- /config/node-red/node_modules/grpc/src/grpc_extension.js
- /config/node-red/node_modules/grpc/src/client_interceptors.js
- /config/node-red/node_modules/grpc/src/client.js
- /config/node-red/node_modules/grpc/index.js
- /config/node-red/node_modules/ttn/dist/discovery/discovery.js
- /config/node-red/node_modules/ttn/dist/discovery/index.js
- /config/node-red/node_modules/ttn/dist/handler/handler.js
- /config/node-red/node_modules/ttn/dist/handler/index.js
- /config/node-red/node_modules/ttn/dist/index.js
- /config/node-red/node_modules/node-red-contrib-ttn/ttn-app/ttn-app.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
```

## Steps to reproduce

1/ install "node-red-contrib-ttn" in the palette section of node-red

2/ node-red import:

`[{"id":"9e04035c.137b8","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"af12243b.484bd8","type":"ttn event","z":"9e04035c.137b8","name":"","app":"","dev_id":"","event":"#","x":240,"y":340,"wires":[["d36f1f49.71756"]]},{"id":"f27c12ce.126e4","type":"ttn uplink","z":"9e04035c.137b8","name":"","app":"","dev_id":"","field":"","x":240,"y":400,"wires":[["c0a0890b.a22cd8","73ff0cc0.ed2794"]]},{"id":"b76ddfd4.50217","type":"ttn downlink","z":"9e04035c.137b8","name":"","app":"","dev_id":"","port":"","confirmed":false,"schedule":"replace","x":590,"y":520,"wires":[]},{"id":"c0a0890b.a22cd8","type":"function","z":"9e04035c.137b8","name":"function","func":"return {\n    dev_id: msg.dev_id,\n    port: msg.port,\n    schedule: \"replace\",\n    confirmed: false,\n    payload: {\n        led: !msg.led,\n    },\n}","outputs":1,"noerr":0,"x":400,"y":460,"wires":[["b5e0742b.2a8f68","b76ddfd4.50217"]]},{"id":"d36f1f49.71756","type":"debug","z":"9e04035c.137b8","name":"event","active":true,"console":"false","complete":"true","x":570,"y":340,"wires":[]},{"id":"73ff0cc0.ed2794","type":"debug","z":"9e04035c.137b8","name":"uplink","active":true,"console":"false","complete":"true","x":570,"y":400,"wires":[]},{"id":"b5e0742b.2a8f68","type":"debug","z":"9e04035c.137b8","name":"function","active":true,"console":"false","complete":"true","x":580,"y":460,"wires":[]}]`

## Proposed changes

In previous version v5.?.? I had this working by including "g++" and "make" in the system_packages section of the configuration file. Now this does not work any more.

**Comment by sinclairpaul** [comment]
I would suggest you log this at the upstream repo for the node itself
