### ISSUE TITLE
Can't start node-red after update

### ISSUE THREAD

**Issue by Dendrowen** [hassio-addons/addon-node-red#417]
# Problem/Motivation

After updating to node-red 6.0.0, the add-on won't start up

## Expected behavior

Node-red running and automations triggering

## Actual behavior

An 'something went wrong' in the logs and node-red exiting with status 0

## Steps to reproduce

- Go to the hassio panel in home assistant
- Selecting the node-red add-on
- click start

## log
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 6.0.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 9 (stretch)  (armv7 / raspberrypi3)
 Home Assistant version: 0.103.5
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
[11:33:21] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[11:33:23] INFO: Password is NOT in the Have I Been Pwned database! Nice!
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
/var/run/s6/etc/cont-init.d/node-red.sh: line 86:   447 Illegal instruction     (core dumped) npm uninstall node-red-contrib-home-assistant node-red-contrib-home-assistant-llat node-red-contrib-home-assistant-ws
[11:33:24] FATAL: Failed un-installing conflicting packages
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
## config
```
{
  "credential_secret": "xxxxxxxx",
  "dark_mode": false,
  "http_node": {
    "username": "xxxx",
    "password": "xxxx"
  },
  "http_static": {
    "username": "xxxx",
    "password": "xxxx"
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": [],
  "log_level": "info"
}
```

**Comment by Dendrowen** [comment]
Is no one else facing this issue?

**Comment by jdavis7765** [comment]
I am getting something similar below. 

Additionally, this shows up in the HA log [hassio.docker] Can't start addon_a0d7b954_nodered: 403 Client Error: Forbidden ("endpoint with name addon_a0d7b954_nodered already exists in network host")

Welcome to Node-RED
===================
21 Jan 16:53:21 - [info] Node-RED version: v1.0.3
21 Jan 16:53:21 - [info] Node.js  version: v12.14.0
21 Jan 16:53:21 - [info] Linux 4.14.98-v7 arm LE
21 Jan 16:53:22 - [info] Loading palette nodes
Terminated
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by jgthornburgh** [comment]
I was unable to restart node-red after update also. uninstalled it and now can't reinstall. 
![image](https://user-images.githubusercontent.com/44178327/73911064-e3dc8c00-4865-11ea-9627-0ea39aa83d46.png)

**Comment by jgthornburgh** [comment]
The error I got after it updated. 
![image](https://user-images.githubusercontent.com/44178327/73911158-22724680-4866-11ea-8d36-b655d453af7e.png)

**Comment by jgthornburgh** [comment]
![image](https://user-images.githubusercontent.com/44178327/73911194-39189d80-4866-11ea-9567-23a14a88acc1.png)

**Comment by jgthornburgh** [comment]
![image](https://user-images.githubusercontent.com/44178327/73911212-4170d880-4866-11ea-96e0-f42bf49c66c0.png)

**Comment by frenck** [comment]
All the above issues are out of my control and have different root causes as well. So there is no way I can ever solve this issue.

Please create a new issue if a fresh installation with the latest version of the add-on still causes problems.

Thanks! 👍
