### ISSUE TITLE
node-red-contrib-home-assistant replaced by node-red-contrib-home-assistant-llat

### ISSUE THREAD

**Issue by rafuz** [hassio-addons/addon-node-red#42]
# Problem/Motivation

> node-red-contrib-home-assistant seems to be no longer mantained and will not support the new home assistant authentication. A new fork called [node-red-contrib-home-assistant-llat ](https://github.com/Spartan-II-117/node-red-contrib-home-assistant-llat)will replace it.

## Expected behavior

> To be able to remove node-red-contrib-home-assistant from the palette and install node-red-contrib-home-assistant-llat

## Actual behavior

> node-red-contrib-home-assistant cannot be removed from the palette

## Proposed changes

Replace node-red-contrib-home-assistant bundled in the addon with node-red-contrib-home-assistant-llat. This is a breaking change because you need to reconfigure hassio connection in the node-red plugin.

**Comment by frenck** [comment]
This is incorrect. It is not being replaced, it is just another fork.
This add-on ran that fork for a while and was reverted for a lot of reasons.

I'm not going to use that fork ever again. We are currently looking into another fork, that uses a better option: websockets.
