### ISSUE TITLE
How to enable projects

### ISSUE THREAD

**Issue by Cludch** [hassio-addons/addon-node-red#430]
# Problem/Motivation

I wanted to use projects within Node-RED and saw another issue that stated that this should work and is enabled. However the `settings.js` in this repo has projects disabled.

## Expected behavior

Use projects within Node-RED

## Actual behavior

Plain old Node-RED without projects.

## Steps to reproduce

Start Node-RED and see projects to be disabled.

## Proposed changes

Set projects within settings to true.

**Comment by bonanitech** [comment]
To activate projects, edit your `settings.js` and restart the add-on. That file is located in `/config/node-red`

**Comment by Cludch** [comment]
Thanks!
I tried to change the file within the container. That worked.
