### ISSUE TITLE
turn all light off

### ISSUE THREAD

**Issue by internet-conception** [hassio-addons/addon-node-red#437]
hello,

It's not really an issue related to node red but since home assistant removed the entity "group.all_lights" I cant use anymore my very simple flow that shutdown all the light at 1am...

Now I should create a "group" in HS and maintain this each time I add a light :(

Is there a way to handle this in nodered has the new expected syntax (entity_id: "all.") dont work in nodered ?

Thanks, bye bye

**Comment by sinclairpaul** [comment]
Thank for logging the issue, however this is really for logging issues related to the addons themselves.  You will get better help (and more people 😄 ) at the community forums.  Here is a link that may help https://community.home-assistant.io/t/psa-turn-on-off-all-lights-in-home-assistant-0-104-group-all-changes/163743
