### ISSUE TITLE
Can't install Node-Red

### ISSUE THREAD

**Issue by jgthornburgh** [hassio-addons/addon-node-red#439]
# Problem/Motivation

I am unable to Install Node-Red. 
Pi3B
HassOS 3.9
Home Assistant 0.105.1
MariaDB
6.5GB free disk space

## Expected behavior

Expect node-red to install

## Actual behavior
Get the following message in the system log:

20-02-06 19:32:55 INFO (SyncWorker_13) [hassio.docker.interface] Pull image hassioaddons/node-red-armv7 tag 6.0.4.
20-02-06 19:32:58 ERROR (SyncWorker_13) [hassio.docker.interface] Can't install hassioaddons/node-red-armv7:6.0.4 -> 404 Client Error: Not Found ("no such image: hassioaddons/node-red-armv7:6.0.4: No such image: hassioaddons/node-red-armv7:6.0.4").

## Steps to reproduce

Node-red auto updated to 6.0.4 while running Home Assistant 0.104.1, I was unable to open Node-red getting a 502 error., and the following messages in the Node-red log:

![image](https://user-images.githubusercontent.com/44178327/73972455-ba5b4900-48d5-11ea-8071-77ee99a273ab.png)
![image](https://user-images.githubusercontent.com/44178327/73972524-d8c14480-48d5-11ea-88a1-71dfb887ed3f.png)

The system log showed:
![image](https://user-images.githubusercontent.com/44178327/73972570-e7a7f700-48d5-11ea-8ec6-92f3aaffa57d.png)

I uninstalled node-red with the intent to reinstall, but now am unable to. 

## Proposed changes

unknown

**Comment by sinclairpaul** [comment]
Looks to be a missing node module required bust some custom Palette.  Only suggestion would be to add  node-gs under npm packages.
