### ISSUE TITLE
Support for Admin HTTP API

### ISSUE THREAD

**Issue by rsuplido** [hassio-addons/addon-node-red#44]
# Problem/Motivation

> Basically, I need to get an Auth Token to be able to reload flows on demand. I tried doing a POST "http request" directly via Node-RED and via SSH using: 

        curl http://localhost:1880/auth/token --data 'client_id=node-red-admin&grant_type=password&scope=*&username=admin&password=password'

and it always comes back as 'Unauthorized'. 

Is Admin HTTP API supported at all?

## Expected behavior

> Comes back with token as detailed here: https://nodered.org/docs/api/admin/oauth

## Actual behavior

> comes back as "Unauthorized"

## Steps to reproduce

> run: curl http://localhost:1880/auth/token --data 'client_id=node-red-admin&grant_type=password&scope=*&username=admin&password=password'

## Proposed changes

> This might as a workaround to force reload flows when HA restarts, via /flows API ( see: https://nodered.org/docs/api/admin/methods/post/flows/ ) by setting "Node-RED-Deployment-Type" to "reload".

**Comment by frenck** [comment]
This should not be a problem with v1.0.0 of the add-on. Could you please upgrade and check?

Be sure to read the upgrade instruction: <https://community.home-assistant.io/t/community-hass-io-add-on-node-red/55023/414?u=frenck>

**Comment by rsuplido** [comment]
Yes, v1.0.0 has worked around on, and is a better solution for this problem and this is no longer needed. Thanks.
