### ISSUE TITLE
Mount .ssh/known_hosts

### ISSUE THREAD

**Issue by Cludch** [hassio-addons/addon-node-red#440]
# Problem/Motivation

Pushing projects to external git instances via SSH fails, because the ssh host is not trusted.
This can be fixed by going into the container's bash and ssh'ing into the target server once and trust the server.

## Expected behavior

Pushing to ssh remote should work without having to trust the key before.

## Actual behavior

Trying to pull or push from / to the remote fails because the ssh command prompts for a yes/no answer in order to trust the host.

## Steps to reproduce

Create Git(ub) repo.
Create Node-RED project and ssh key.
Add the ssh key to the repo as deploy key.
Try to pull.

## Proposed changes

Maybe trust all ssh keys or mount the ssh known_hosts file and persist it.

**Comment by frenck** [comment]
Trust all sounds like the only route we have for this. Mounting isn't an option since, well... mount from where?

**Comment by frenck** [comment]
Fixed in v6.1.3

**Comment by Cludch** [comment]
> Trust all sounds like the only route we have for this. Mounting isn't an option since, well... mount from where?

You are right. Thanks for implementing a fix!
