### ISSUE TITLE
Wait Until node timeout before configured timeout value is reached.

### ISSUE THREAD

**Issue by rdariolemes** [hassio-addons/addon-node-red#442]
# Problem/Motivation

Wait Until node timeout before configured timeout value is reached.
![image](https://user-images.githubusercontent.com/46392038/74080165-f940ea00-4a0e-11ea-80ea-a3c3140ba2d8.png)
![image](https://user-images.githubusercontent.com/46392038/74080178-0d84e700-4a0f-11ea-83e8-02633312bbb2.png)

## Expected behavior

Wait until the configured timeout value is reached

## Actual behavior

Wait Until node timeout before configured timeout value is reached.

## Steps to reproduce

Configure wait until node. Create function node who passes timeout and timeoutunits to wait until node. Wait and see node timing out before configured value and not executing timeout action.

## Proposed changes

I haven't found WA.

**Comment by frenck** [comment]
This is not an add-on issue. Add-ons wrap existing software, your issue is with that software.
Please file an issue with the node you are having an issue with.
Thanks 👍
