### ISSUE TITLE
Credentials in my config.yaml file?

### ISSUE THREAD

**Issue by SteveRMann** [hassio-addons/addon-node-red#445]
# Problem/Motivation
I am lazy
> (Why the issue was filed)

## Expected behavior
Auto logon.
> (What you expected to happen)

## Actual behavior
Always asks for login credentials when starting Node-Red from Home Assistant
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
Allow me to put my login and password in a yaml file?
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
As stated, I am lazy.  My system is not exposed to the WWW and I am the only user.  I would just like to not need to enter my credentials every time I open Node-red from Home Assistant.

**Comment by frenck** [comment]
If you use ingress, it won't be asking for login.
If you use direct access to the add-on, yes, it will ask for login.

There is an option to disable that in the add-on documentation: `leave_front_door_open`.
