### ISSUE TITLE
Included node-red-contrib-home-assistant cannot be removed

### ISSUE THREAD

**Issue by JohnnyPicnic** [hassio-addons/addon-node-red#45]
# Problem/Motivation

I cannot seem to remove node-red-contrib-home-assistant from Node Red.
There is no Remove button 

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Remove the node-red-contrib-home-assistant node from the package.json so that users can install the fork of their choice.

**Comment by danrspencer** [comment]
I came here looking if there was any discussion of something like this. Given the current unmaintained state of the `node-red-contrib-home-assistant` node and the forks that are appearing if feels like the solution may be to stop treating is as a special package and just list it in the `npm_packages` by default. Or if it is fundamentally different in some way to other packages maybe add a configuration option for the HA node package?

**Comment by simo878** [comment]
the only way i have found to remove it currently is this way:

```
"init_commands": [
    "npm uninstall node-red-contrib-home-assistant"
]
```

as described here:
https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/master/README.md

**Comment by frenck** [comment]
As per above answers, closing this issue.
