### ISSUE TITLE
Bug in multi-line editors, visible cursor does not line up with where text is entered

### ISSUE THREAD

**Issue by lightmaster** [hassio-addons/addon-node-red#452]
# Problem/Motivation

> When typing in a multi-line box, the visible cursor and where the cursor actually are do not line up, leading to a very difficult time trying to click something on the line to add or remove letters.

## Expected behavior

> The visible cursor and location where text is modified should be the same.

## Actual behavior

> [Bug recorded in this Youtube Video](https://youtu.be/kASfM62vnwY). It seems that the location where text is being modified is to the right of the visible cursor, and as the cursor progresses further across the text box, the gap between the visible cursor and where the text is modified at grows.

## Steps to reproduce

> I have be able to reproduce this every time I try to type in a multi-line text box, such as the Template box in the above video, and also in the "Edit JSON" Editor. The Visual JSON Editor does not have this problem

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by bonanitech** [comment]
Do you see the same issue if you disable the dark theme?

**Comment by bonanitech** [comment]
@lightmaster thanks for the heads up. The problem was in the dark theme. I just released a new version of it with the fix.

This issue can be closed now.

**Comment by lightmaster** [comment]
Is there a way to add these changes before the next release? I tried removing those lines from the theme, but they keep getting added back when I restart node-red.

**Comment by bonanitech** [comment]
You could add `node-red-contrib-theme-midnight-red@latest` to `npm_packages` in the add-on Config section. I don't like doing this though.
