### ISSUE TITLE
Wasn't NodeRed in the approved HA 

### ISSUE THREAD

**Issue by jimmyz5150** [hassio-addons/addon-node-red#454]
Latest HA 107
From HA logs..
You are using a custom integration for nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant

I could have sworn that nodered add-on was an official add-on not too long ago?
If not then why not?? lol
Since Frenck is on board ..shouldn't it be..lol
Just want to make sure nothing is screwed up thanks
Jim

**Comment by frenck** [comment]
A) The add-on does not provide a custom component/integration.
B) The community add-ons is my personal project.
C) This add-on has never been an official add-on.

**Comment by jimmyz5150** [comment]
Thanks for the response frenck. 
I appreciate the add-on.. thanks for the work!  It's great, meant no disrespect.
I was being light hearted. 
When I saw this warning, I had to scratch my head. I've not seen it in the year I've been using the add-on.  
I had hoped that you would re assure that there was no problem.

**Comment by frenck** [comment]
I know, it is just that I don't distribute any custom integration.
There is a node-red custom component around, but that is not from this add-on.
