### ISSUE TITLE
Node-red stops after reboot start

### ISSUE THREAD

**Issue by tanker11** [hassio-addons/addon-node-red#457]
# Problem/Motivation

I have checked and saw similar (startup) issues but not exactly the same.
My issue is: after restarting Home Assistant (hassio), Node-red starts up, and after several minutes it terminates.
If I manually restart, it will run without problems except it still takes a long time to start.

It all happened after upgrade (upgraded OS, hassio, and Node-red, too, no idea of the previous versions...)

## Steps to reproduce

Restart hassio and check Node-red status.

I am open to check/test, debug things, but no idea what to watch for...

Here is the log from stopping situation, see the time stamps, I guess the startup should not be that long:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 6.0.4
 You are running the latest version of this add-on.
 System: HassOS 3.11  (armv7 / raspberrypi3)
 Home Assistant version: 0.105.5
 Supervisor version: 201
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
[18:21:08] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[18:21:13] INFO: Password is NOT in the Have I Been Pwned database! Nice!
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
audited 444 packages in 18.89s
14 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:22:48] INFO: Starting Node-RED...
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
23 Feb 18:23:58 - [info] 
Welcome to Node-RED
===================
23 Feb 18:23:58 - [info] Node-RED version: v1.0.3
23 Feb 18:23:58 - [info] Node.js  version: v12.14.0
23 Feb 18:23:58 - [info] Linux 4.19.93-v7 arm LE
23 Feb 18:24:00 - [info] Loading palette nodes
[info] "2020-02-23T17:26:50.082Z"  'Loading knx: KNXnet/IP protocol implementation for Node(>=4.x), version: 2.3.6'
Terminated
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

END OF LOG

Before pointing out KNXNet/IP protocol, I tried with de-installed KNXNet, and the result was the same, unfortunately.
Debug log did not tell me too much, but if you suggest posting it, let me know.

Thanks in advance for helping.

**Comment by tanker11** [comment]
Thanks, bot, checked it, and it's different. :)

**Comment by sinclairpaul** [comment]
It looks like it is failing to load one of your palette nodes.  How many do you have installed, have you tried removing them?  The config is stored in the config/node-red folder, which you can access via SSH/SMB.

**Comment by frenck** [comment]
This is a custom pallet, not delivered out of the box by the add-on.
While you can install custom nodes, issues with those are yours, not ours.

We can't support al the thousands of nodes out there.

I hope you find a solution for it.
