### ISSUE TITLE
Current state node: override topic / payload does not seem to work

### ISSUE THREAD

**Issue by ps-nl** [hassio-addons/addon-node-red#46]
# Problem/Motivation

Current-state node does not pass the state of the entity being checked, but instead passes the message that triggered the node. The check-boxes "override topic"  and "override payload" appear not to have any effect

## Expected behavior

I expected the current state node to pass the state of the entity_id being polled, in cases where "override topic"  and "override payload" are checked. 

## Actual behavior

Message of triggering node is passed

## Steps to reproduce
My current config:
- Hassio / Home Assistant 0.79.3 (Raspberry Pi 3)
- Node-red addon 0.7

Flow as per the attached screenshots

Overall flow:
Zwave device Dimmer_1 used as a trigger. If button 2 is pushed, state of other Zwave device (Plug1) should be checked and depending on state of that device lights should be switched on or off.
![screenshot 2018-10-08 at 08 07 04](https://user-images.githubusercontent.com/17012245/46594260-396a2280-cad2-11e8-9e1d-685a6e2497f2.png)

Setting of the Current State node. Override buttons are checked:
![screenshot 2018-10-08 at 08 06 54](https://user-images.githubusercontent.com/17012245/46594263-3c651300-cad2-11e8-9dea-d5eb66f97566.png)

Debug output: state of trigger Zwave device is passed, not the state of the entity_id that is being checked.
![screenshot 2018-10-08 at 08 08 03](https://user-images.githubusercontent.com/17012245/46594266-3ec76d00-cad2-11e8-967d-e0c85ac4f636.png)

**Comment by simo878** [comment]
This is a known bug with the version of home assistant nodes that the add-on is currently using (node-red-contrib-home-assistant), it looks like the original dev is MIA and a few forks have poped up to continue development

Im using https://github.com/zachowj/node-red-contrib-home-assistant-websocket successfully atm.

**Comment by ps-nl** [comment]
@simo878 Many thanks, that solved it. 

That said, the log is not entirely clean. Startup is now 70secs longer because it adds the NPM again after every restart, and there is a make problem with bcrypt. I know this is not a support channel, but do you by any chance have a solution for that as well?

>[cont-init.d] 81-npm-packages.sh: executing... 
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN hassio-addon-node-red@1.0.0 No repository field.
>'+ node-red-contrib-home-assistant-websocket@0.1.0
added 5 packages in 72.899s
[cont-init.d] 81-npm-packages.sh: exited 0.
[cont-init.d] 82-user-scripts.sh: executing... 
npm WARN deprecated bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes
> bcrypt@2.0.1 install /opt/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v2.0.1/bcrypt_lib-v2.0.1-node-v57-linux-arm-musl.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@2.0.1 and node@8.11.4 (node-v57 ABI, musl) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make`

**Comment by frenck** [comment]
This new WebSocket version of the Node-RED connector is now in the add-on. V1.0.0 just got released.
