### ISSUE TITLE
template node does not work correctly with person

### ISSUE THREAD

**Issue by ciB89** [hassio-addons/addon-node-red#466]
# Problem/Motivation

I found a bug in the ‘get template’ node:

`{{ is_state("person.bob", "home") }}` returns `True `in the template editor in Home Assistant, but when I use the ‘get template’ node it returns False. I tested it with other persons too and it’s the same.

## Expected behavior

`{ is_state("person.bob", "home") }}` should return `True `when the person is home.

## Actual behavior

`{ is_state("person.bob", "home") }}` returns `False`

## Steps to reproduce

Create a person with device tracker in HA. Create a 'get template' node in node-red and enter `{ is_state("person.X", "home")` }}

**Comment by frenck** [comment]
Hi!

This is the Node-RED add-on. Add-ons wrap existing applications (and in this case node palettes as well).

Please report this issue with the node that belongs to this.

**Comment by ciB89** [comment]
My bad!
