### ISSUE TITLE
Using hassio add-on checkbox cleared by itself

### ISSUE THREAD

**Issue by omriasta** [hassio-addons/addon-node-red#467]
# Problem/Motivation
Not sure how it happened but the add-on stopped working all of a sudden. After downgrading, restoring from backup and a bunch of other trials, I noticed that the connection to homeassistant has a checkbox for "using hassio add-on" and it was unchecked for me. 
> (Why the issue was filed)
This is just an fyi, if anyone else runs into it. 
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
It's really an issue with the actual nodes for HA, lots of work was put in to try and mitigate this, and a note was added to the documentation.  Not sure what more we can do,
