### ISSUE TITLE
add support for long-lived token (fix issue with node-red losing connection to HA)

### ISSUE THREAD

**Issue by simo878** [hassio-addons/addon-node-red#47]
# Problem/Motivation

currently when the server config uses http://hassio/homeassistant and pulls a token each time home assistant is restarted, i must re-deploy my flows (or restart the add-on) for node-red to regain connection to home assistant

## Proposed changes

using the websockets fork  (https://github.com/zachowj/node-red-contrib-home-assistant-websocket) if i set the server config to my duckdns IP (https://_____.duckdns.org:8123) and use the long-lived token, node red functions perfectly, regarding restarts to home assistant.

**Comment by frenck** [comment]
@simo878 You should not use your external URL in Hassio....
`https://_____.duckdns.org:8123` -> `http://hassio/homeassistant`

I'm considering switching to zachowj's fork. But this will break the setup for the current add-on users.

**Comment by danielsjf** [comment]
What are the pros of moving to zachowj's fork?

**Comment by frenck** [comment]
@danielsjf Well first of all, it is created and maintained by someone with programming experience. Secondly, it uses websockets instead of the (broken by design) event stream.

**Comment by frenck** [comment]
Version 1.0.0 of the add-on just got out. It uses a different method of connecting and does not require long-lived access tokens!

Be sure to read the upgrade instructions: https://community.home-assistant.io/t/community-hass-io-add-on-node-red/55023/414?u=frenck

Closing the issue.
