### ISSUE TITLE
Node Red still broken after HA update (0.106.1)

### ISSUE THREAD

**Issue by wiggitamoo** [hassio-addons/addon-node-red#478]
# Problem/Motivation

Ever since the 0.105.2 upgrade, my Node-Red has been stuck in a connecting state. 
I keep seeing `[info] [server:Home Assistant] WebSocket Connecting http://supervisor/core` in the node-red logs.

Before the upgrade, everything was working. I have seen other users experiencing problems, but I haven't seen a fix that works for me yet.

## Expected behavior

Node-Red should connect to Home Assistant when checking the checkbox that says "I use the Home Assistant Add-On". 

## Actual behavior

Node-Red stays in a 'connecting' state.
![image](https://user-images.githubusercontent.com/1783757/75499752-fcd5ea00-5998-11ea-8edd-647b56af523c.png)

## Steps to reproduce

Upgrade to 
Home Assistant 0.106.0
Node-Red 6.1.1
Supervisor: 201
HassOS 3.11

**Comment by frenck** [comment]
Add-on wraps existing applications. The add-on provides the keys, but does not handle the connection.

Please report your issue with the Home Assistant Node-RED node. Thanks! 👍
