### ISSUE TITLE
trigger:state substring or regex filtering not working properly after upgrade

### ISSUE THREAD

**Issue by phdonnelly** [hassio-addons/addon-node-red#481]
# Problem/Motivation

After updating to 6.1.2 all trigger:state nodes with entity IDs set to either substring or regex are returning ALL entities instead. "Exact" nodes work as expected.

## Expected behavior

trigger-state nodes should filter according to the substring or regex.

## Actual behavior

trigger-state nodes turned into a firehose.

## Proposed changes

events:state nodes work as expected; I've worked around by using those nodes instead for now.

**Comment by frenck** [comment]
Hi there!

This is the node-red add-on repository, your request has to do with the home assistant node-red node, which this add-on uses/wraps.

That said, we don't modify that, we just install it. If you have issues with the node, please report is with the home assistant node, as this add-on has no contro over the working of that.

Thanks! 👍

**Comment by phdonnelly** [comment]
Whoops sorry about that; I see this has now been fixed upstream and you're already pushed out a new add-on package with the change. Thanks much!
