### ISSUE TITLE
Severe issue in node-red-contrib-home-assistant-websocket@0.21.2

### ISSUE THREAD

**Issue by 1300371** [hassio-addons/addon-node-red#482]
# Problem/Motivation

My NodeRED automation got very problematic behaviour. In the _node-red-contrib-home-assistant-websocket_ package at version 0.21.2, there is a issue in the **trigger-state** node.

It will trigger the state of **all entity registered** in HA.

So after a fresh install of my automations, i start to receive a lot of notifications and my lights starts blinking as most of my automations are based on trigger-state.

## Expected behavior

Trigger only the status of the target entityID.

## Actual behavior

Trigger the status of all entities.

## Steps to reproduce

Update the _node-red-contrib-home-assistant-websocket_ to 0.21.2

## Proposed changes

This has been fixed in node-red-contrib-home-assistant-websocket@0.21.3. But the current version in addon-node-red is 0.21.2.
So can you update the version to **0.21.3** to avoid this to other people ?

**Comment by frenck** [comment]
0.21.3 is in the current development branch.

**Comment by 1300371** [comment]
Nevermind, just see the PR to update this. Sorry ...
And thank you for all your work ! ;)
