### ISSUE TITLE
Home Assistant starts before Node Red

### ISSUE THREAD

**Issue by Glazzanz** [hassio-addons/addon-node-red#485]
# Problem/Motivation

I am using Node-Red as middle aware between various devices, including light systems and alarms.  I have previously used a standalone installation of Node-Red; but have opted to move to the addon.

However, within Node-Red I am using MQTT (node-red-contrib-mqtt-broker: mosca in) - when rebooting the host, all the entities provided via MQTT and Node-Red display as Entity not available: entity.name

In the logs of Home Assistant it reports that it is unable to connect to the MQTT broker, and wait to connect.  It does eventually connect - but at this point I'm guessing there is no data to provide to Home Assistant, and hence the Entity is flagged as not available.

## Expected behavior

Node-Red would start before home assistant.

## Actual behavior

Node-Red starts after home assistant

## Proposed changes

The config.json for this add on is set to application (which means it will start after home assistant has started).  If it was set to service it would start before home assistant

**Comment by frenck** [comment]
While I get your use case, we can't do that.
The other way around, most people use Home Assistant as the authoritative endpoint for their entities, hence Home Assistant needs to start first.

This is not a problem I can solve for you, as we should follow the general use case.
