### ISSUE TITLE
Cannot GET /homeassistant/services

### ISSUE THREAD

**Issue by divineliving** [hassio-addons/addon-node-red#49]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by divineliving** [comment]
Just upgraded hass.Io to version 8.. Now I am getting this error in node-red - 
Cannot GET /homeassistant/services

First thing that happened in Node-Red was that I i was prompted to the user/id of Node-Red - when I had already logged in and was working in Node-red. I double clicked on a call service I got this error in node-Red
Cannot GET /homeassistant/services

Hopefully something that can be easily fixed.


Thanks!

**Comment by frenck** [comment]
This is now fixed in the v1.0.0 release of the add-on.
