### ISSUE TITLE
alexapy.websocket errors appear to be caused by node red add on

### ISSUE THREAD

**Issue by seamus65** [hassio-addons/addon-node-red#490]
# Problem/Motivation

> (Why the issue was filed)

I have a problem on HA 0.106.2 and have had it for the last couple of updates.

Node red add on version 6.1.3, but has been ongoing for a few versions now, since I reinstalled and setup Home Assistant over my old hassbian set-up a few weeks ago.

I am running home assistant on a pi3b+ with official power supply, installed and boot from ssd.

This is stopping alexa from being able to control lights etc and causing lag generally in the system.
```
Logger: alexapy.alexawebsocket
First occured: 4:07:31 PM (28 occurences)
Last logged: 6:32:30 PM

WebSocket Error: <class 'concurrent.futures._base.TimeoutError'>
```
I am also getting this error repeatedly as well:
```
Logger: alexapy.alexawebsocket
First occured: 4:44:04 PM (5 occurences)
Last logged: 7:06:34 PM

WebSocket Error: <class 'aiohttp.streams.EofStream'>
```

I stopped the node red add-on and haven’t had any error messages for the last 5 hours or so.

## Expected behavior

> (What you expected to happen)

Everything to run along nicely.

## Actual behavior

> (What actually happened)

alexapy.websocket errors repeating in the logs and the whole system becoming laggy and sometimes crashing.

## Steps to reproduce

> (How can someone else make/see it happen)

Not sure, but the only flow I have in node red is one switch and one script connected to alexa.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Add-ons wrap existing software. Please report this issue with the creator of that node. Thanks 👍

**Comment by seamus65** [comment]
Thank you for the quick response Frenck
