### ISSUE TITLE
Dark mode Function Node background - Urrg ! 

### ISSUE THREAD

**Issue by 3ative** [hassio-addons/addon-node-red#491]
# Problem/Motivation

> (Why the issue was filed)
After latest update, the Function Node background has changed from a nice Black to a lower contrast Grey. It makes it harder to see text
## Expected behavior

> (What you expected to happen)
background returned to Black
## Actual behavior

> (What actually happened)
background changed to Grey
## Steps to reproduce

> (How can someone else make/see it happen)
Update to V6.1.3 and turn on dark_mode
## Proposed changes
Please restore Background Colour.

![Function-node-BG](https://user-images.githubusercontent.com/51385971/75792403-d4b60480-5d65-11ea-816b-0fdc92f09b35.jpg)

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The theme isn't made by the add-on, we just include it.
Please report your issue on the right project.

<https://github.com/node-red-contrib-themes/midnight-red>

Thanks! 👍

**Comment by 3ative** [comment]
Ah, I suspected as much...
Reporting to other page now. Cheers.
