### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by mikesac** [hassio-addons/addon-node-red#492]
# Problem/Motivation

Nodered addon is crashing at boot with error

> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Installation was working fine and error started after some image parsing flow, so I suspect I should increase **max_old_space_size** parameter, but since the addon is running into a docker container on a Raspberry Pi 4 I'd like to konw the proper way to add it in a permanent way.

As a workaround is there a way to dump and then delete my flow to let nodered restart with mint configuration ?

Last question: I'm running HA/Nodered on Raspian, which ships with nodered as well.
Is there a way to use the addon with standalone nodered and avoid additional docker container ?

 Add-on version: 6.1.0
 There is an update available for this add-on!
 Latest add-on version: 6.1.3
 Please consider upgrading as soon as possible.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 0.105.5
 Home Assistant Supervisor: 207

**Comment by mikesac** [comment]
thanks @sinclairpaul , the config/node-red/flows.json folder was exactly what I was looking for.
I renamed flows.json and gain back a working NodeRed process :)

> Not sure what you mean, by this, if the question is can I use Node-Red outside of the Add on with the HA nodes, then yes absolutely. Obviously you would need to configure this all yourself.
Yes, that was exactly my point! Do you know if and guide is available to perform such configuration?

**Comment by sinclairpaul** [comment]
Documentation for those nodes is at https://zachowj.github.io/node-red-contrib-home-assistant-websocket/
