### ISSUE TITLE
G++ : ERROR: unsatisfiable constraints

### ISSUE THREAD

**Issue by lorerave85** [hassio-addons/addon-node-red#496]
# Problem/Motivation
I'm trying to install gg+ module for build custom integration
> (Why the issue was filed)
ERROR: unsatisfiable constraints:
  musl-1.1.24-r0:
    breaks: musl-dev-1.1.24-r1[musl=1.1.24-r1]
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
enter in docker
apk add g++
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Install `musle` as well to guarantee you have the correct set of dependencies.
