### ISSUE TITLE
Installation instructions result in a different addon being installed

### ISSUE THREAD

**Issue by unikitty37** [hassio-addons/addon-node-red#499]
# Problem/Motivation

Following the installation instructions in the README results in a different Node-RED addon being installed to HA, and the remaining instructions cannot be followed, resulting in a non-working installation.

HA version is 0.106.2, running on hassio 3.11. The only custom repo installed in HACS is `rogro82/hass-variables`.

## Expected behaviour

Searching for "Node-RED" in HACS and clicking the install button results in this addon being installed, and the remaining install instructions being valid.

## Actual behaviour

The addon at https://github.com/zachowj is installed. It does not offer a way to set a `credential_secret`, there is no "OPEN WEB UI" button, and it appears to need a server configured.

## Steps to reproduce

1. Search for `Node-RED` in HACS.
1. Check the URL of the `REPOSITORY` link — it should be https://github.com/hassio-addons/addon-node-red but is https://github.com/zachowj/hass-node-red.
1. Attempt to configure the `credential_secret` but fail because no config is exposed.
1. Restart HA.
1. Go to HACS > Installed and click on the Node-RED addon.
1. Attempt to start the addon, but there is no `Start` button; instead, there are instructions to add an integration.
1. Regardless of whether you add the integration or not, there is no button to open the web ui, and the add-on does not work straight out of the box.

## Proposed changes

The addon that was installed is the only one that comes up in a search for Node-RED. I'm not sure that is the correct addon and the install instructions are out of date, or if HACS is returning a different addon and not this one.

If it *is* returning the correct version, could the instructions be changed to reflect the current install process?

(Unfortunately, the README does not contain instructions for a manual install — could these instructions be added, please? They would be useful in cases like this…)

<blockquote><img src="https://avatars2.githubusercontent.com/u/37859597?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/zachowj">zachowj - Overview</a></strong></div><div>zachowj has 4 repositories available. Follow their code on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-node-red">hassio-addons/addon-node-red</a></strong></div><div>Node-RED - Home Assistant Community Add-ons. Contribute to hassio-addons/addon-node-red development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/37859597?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/zachowj/hass-node-red">zachowj/hass-node-red</a></strong></div><div>Companion Component for node-red-contrib-home-assistant-websocket to help integrate Node-RED with Home Assistant Core - zachowj/hass-node-red</div></blockquote>

**Comment by frenck** [comment]
HACS is for installing custom integrations and themes, not add-ons.
Add-ons are in the add-on store.

Thanks.

**Comment by unikitty37** [comment]
Thanks — can't believe I didn't spot that 🤦‍♂
