### ISSUE TITLE
Error starting container

### ISSUE THREAD

**Issue by mikyjazz** [hassio-addons/addon-node-red#500]
# Problem/Motivation

> Cannot start add-on

## Expected behavior

>Start with no errors

## Actual behavior

> -----------------------------------------------------------
 Add-on version: 6.1.3
 You are running the latest version of this add-on.
 System: Ubuntu 16.04.6 LTS  (aarch64 / qemuarm-64)
 Home Assistant Core: 0.106.5
 Home Assistant Supervisor: 209
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
mv: can't rename '/etc/nginx/servers/direct-ssl.disabled': Invalid argument
[cont-init.d] nginx.sh: exited 1.

## Steps to reproduce

> install node-red addon and start

NOTE:
- Log-viewer addon use similar initialization procedure for nginx and work always correctly
- Tasmo-admin addon use similar initialization procedure for nginx and FAIL with similar behaviour

- The addon WORKS on another installation, Ubuntu 18.03 LTS on amd64 (intel) platform, same versions

**Comment by sinclairpaul** [comment]
Can you please add which hardware platform?

**Comment by mikyjazz** [comment]
The System: is Ubuntu 16.04.6 LTS (aarch64 / qemuarm-64)
More precusely
ARMBIAN 5.41 user-built Ubuntu 16.04.6 LTS 3.14.29
Processor is:
 description: AArch64 Processor rev 4 (aarch64)
    product: Amlogic
    width: 64 bits

**Comment by sinclairpaul** [comment]
Thanks will guess this is some kind of Amlogic s905x3 box?

**Comment by mperniola** [comment]
Yes, it is, with 2gb ram...

**Comment by mikyjazz** [comment]
Further experiments:

as it is the mv command that causes the error I thought to change into container file nginx.sh:
mv /etc/nginx/servers/direct-ssl.disabled /etc/nginx/servers/direct.conf
into
cp -f  /etc/nginx/servers/direct-ssl.disabled /etc/nginx/servers/direct.conf

with this modifications the star procedure make other steps and fails:

[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
patch: **** Can't rename file nodes/ui_base.html to nodes/ui_base.html.orig : Invalid argument
[cont-init.d] node-red.sh: exited 2.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 

the command that fails is SED...
cannot rename, probabily it calls mv internally

I tried to execute mv command on the host many times without any error

Why mv fails starting the container ??!?!?!?
Permissions? command execute as root...

**Comment by sinclairpaul** [comment]
Which container image is pulled?

**Comment by mikyjazz** [comment]
I found the mv command into these files so i changed all three
/var/lib/docker/overlay2/b9e4e231a1b5c8cd7575a7d168bb9f0bcadee9dad6a872d3f206ee8db0ef6a28/diff/etc/cont-init.d/nginx.sh
/var/lib/docker/overlay2/ba1cc5170d126a1fbf8043cd0278c199c5fb141f00f6ee751bdcd7f3904871f1/diff/etc/cont-init.d/nginx.sh
/var/lib/docker/overlay2/8066ee48520e6f064e492b3a8118375fc94394fb3a49ae8d17177c034a6aef3d/diff/etc/cont-init.d/nginx.sh

Morover, I inspected the container after startup patch
the SED commands in nginx.sh (after the cp command)  all were successful

**Comment by sinclairpaul** [comment]
I would likely check what the underlying file system is.  As you can appreciate it, from the details you have given, this is unlikely to be an issue with the add on itself.  Although best efforts are given to support all devices, we cannot duplicate/test everything, so unfortunately I doubt there is anything that can be done from an add on perspective.
