### ISSUE TITLE
Can't install NodeRed add-on 

### ISSUE THREAD

**Issue by bwanajag** [hassio-addons/addon-node-red#501]
# Problem/Motivation

> Can't install NodeRed add-on from Community Add-on Store

## Expected behavior

> I expected to click install and NodeRed would install

## Actual behavior

> It failed to install; received the following error in logs
`20-03-12 00:53:07 INFO (SyncWorker_4) [supervisor.docker.interface] Pull image hassioaddons/node-red-amd64 tag 6.1.3.
20-03-12 00:53:22 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install hassioaddons/node-red-amd64:6.1.3 -> 404 Client Error: Not Found ("no such image: hassioaddons/node-red-amd64:6.1.3: No such image: hassioaddons/node-red-amd64:6.1.3").`

## Steps to reproduce

> Download and install the homeassistant vmdk, install in esxi, start it up, try to install NodeRed

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
If Home Assistant throws that error, it generally means you don't have enough disk space to complete the operation.

Make sure you have enough disk space left.
