### ISSUE TITLE
node-red-contrib-dht-sensor not installing

### ISSUE THREAD

**Issue by lecrote** [hassio-addons/addon-node-red#510]
I'm unable to install that node
node-red-contrib-dht-sensor

Setup RPI3B+

It returns me error
 Mar 08:44:39 - [info] Installing module: node-red-contrib-dht-sensor, version: 1.0.4
22 Mar 08:44:48 - [warn] Installation of module node-red-contrib-dht-sensor failed:
22 Mar 08:44:48 - [warn] ------------------------------------------
22 Mar 08:44:48 - [warn] gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.19.106-v7
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /config/node-red/node_modules/node-dht-sensor
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-dht-sensor@0.4.1 postinstall: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-dht-sensor@0.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-22T12_44_48_251Z-debug.log
22 Mar 08:44:48 - [warn] -----------------------------------------

**Comment by sinclairpaul** [comment]
`gyp ERR! stack Error: not found: make`

You are missing the dependencies needed under system packages.  If you search through the closed issues there are many example of this.
