### ISSUE TITLE
Really need help understanding node and system package!

### ISSUE THREAD

**Issue by lecrote** [hassio-addons/addon-node-red#511]
I may be to noobs to this but still need help,

I have 2 nodes that I need to install for my project.
1- node-red-contrib-dht-sensor
see other issue closed
https://github.com/hassio-addons/addon-node-red/issues/510
I did install make with
system_packages:
  - make
but still no luck
Can someone explain me the system packages? which one is needed to make the system equal to an standalone nodered installation?
I read other post talking about gcc or build-base what they are?
I tried this
system_packages:
  - build-base
And build-base fail
_[07:25:45] FATAL: Failed installing system package build-base
[cont-init.d] user.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0._

On my RPI1B (nodered only no homeassistant) I only add to add the node and thats it.
The node documentation only requires this:
_Install the BCM2835 library from here._ 
no clue how to install this!?
_Install the node-dht-sensor dependency_
when I try to do this 
system_packages:
  - make
  - gcc
npm_packages:
  - node-dht-sensor

it fails

2- node-red-contrib-ds18b20
That one I need to run this in the command line.
sudo modprobe w1-gpio
sudo modprobe w1-therm
but it fails
if a do 
su root
modprobe w1-gpio
got
/lib/modules: no such files or directory

Help is really appreciate

Thanks Dan

**Comment by frenck** [comment]
We don't provide support on custom nodes. The documentation of the add-on links to the Alpine package index where you can find all system packages available.
