### ISSUE TITLE
current state node

### ISSUE THREAD

**Issue by matteos1** [hassio-addons/addon-node-red#521]
# Problem/Motivation

since yesterday, the current node does not give numerical values. if I pass a value from a sensor it gives Nan output. can it be solved in some way? I believe i’ve update some palette in Node Red 

## Expected behavior

> (What you expected to happen)

## Actual behavior

current state node not working
![IMG_0357](https://user-images.githubusercontent.com/16237822/78013310-956bdb00-7346-11ea-813b-dcfec26ed0b8.jpg)
![IMG_0358](https://user-images.githubusercontent.com/16237822/78013316-97359e80-7346-11ea-843a-81e9791702aa.jpg)
![IMG_0359](https://user-images.githubusercontent.com/16237822/78013317-9866cb80-7346-11ea-804b-fc825c030194.jpg)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there,

That state node is not created by the add-on. Please report the issue with the node itself. Thanks 👍

**Comment by knobunc** [comment]
This seems to be tracked over at https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/226 now
