### ISSUE TITLE
Entity could not be found in cache

### ISSUE THREAD

**Issue by hrmele** [hassio-addons/addon-node-red#544]
# Problem/Motivation

NodeRed giving error 'Entity could not be found in cache for entity_id: switch.whatever"'.
Error just happens right after deploying. If I wait for around 10 seconds, problem goes away.

It seems to be the same as issue #195 and the same as here, that appears to be solved by a user.
https://github.com/Spartan-II-117/node-red-contrib-home-assistant-llat/issues/34

## Expected behavior

Flow to work

## Actual behavior

Flow stopped

## Steps to reproduce

Just put a injection node, some get state node, a debug message, deploy and inject data right after deploy.

**Comment by sinclairpaul** [comment]
The addon wraps the existing applications, you would likely be better raising your issue at https://github.com/zachowj/node-red-contrib-home-assistant-websocket
