### ISSUE TITLE
Error: Username is required to use password

### ISSUE THREAD

**Issue by Roberto6969** [hassio-addons/addon-node-red#545]
**Problem/Motivation**
NodeRed giving error:
![image](https://user-images.githubusercontent.com/21200507/80074654-c86e4c80-8549-11ea-978c-9854c4e8acc9.png)

**Expected behavior**
Restrict entering password without username

**Actual behavior**
You can enter and deploy security only with password

**Steps to reproduce**
i am not sure but i think the following error, repeating to infinity, came because i have configured mqtt node without an username - i've entered password only in server/properties/security.

Is it possible to remove mqtt node which is configured without an username?

**Comment by sinclairpaul** [comment]
You may be able to delete the problematic flow from config/node-red/flows.json

As this really isn't a problem with the addon, but the node itself will close this out.
