### ISSUE TITLE
Increase Node-Red security role to manage?

### ISSUE THREAD

**Issue by danrspencer** [hassio-addons/addon-node-red#55]
# Problem/Motivation

I want to be able to setup automations in Node Red which do things like start / stop HA, reboot the system, etc... 

## Expected behavior

It can control Hassio

## Actual behavior

403 Permission Denied

## Steps to reproduce

[{"id":"432de28f.85bc8c","type":"function","z":"ce7797ed.a4f218","name":"Set X-HASSIO-KEY","func":"\nmsg.headers = {};\nmsg.headers['X-HASSIO-KEY'] = msg.payload;\n\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":500,"wires":[["f9756f2e.a1eef"]]},{"id":"51cf1b16.32ec54","type":"inject","z":"ce7797ed.a4f218","name":"HASSIO_TOKEN","topic":"","payload":"HASSIO_TOKEN","payloadType":"env","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":500,"wires":[["432de28f.85bc8c"]]},{"id":"f9756f2e.a1eef","type":"http request","z":"ce7797ed.a4f218","name":"Reboot Host","method":"GET","ret":"txt","url":"http://hassio/host/reboot","tls":"","x":550,"y":500,"wires":[["5c4d0604.b8e6a8"]]},{"id":"5c4d0604.b8e6a8","type":"debug","z":"ce7797ed.a4f218","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":710,"y":500,"wires":[]}]

## Proposed changes

Change the security role for the Node Red addon to "manager"

**Comment by frenck** [comment]
Thanks for the suggestion, @danrspencer!

I will consider this for the next release.
