### ISSUE TITLE
Autocomplete of Entity Ids is not happening

### ISSUE THREAD

**Issue by DesertDwellerEv** [hassio-addons/addon-node-red#555]
# Problem/Motivation
Created new entities in HA. NR does not display them when I attempt to create a State Node.
If I insert it manually, the node states connected, however it does not display state change even though HA clearly show state changed
Looked at issue https://github.com/hassio-addons/addon-node-red/issues/407
and it mentions flipping Protection Mode on/off. However my current implementation does not display that option.
> (Why the issue was filed)
Unable to continue developing flows
## Expected behavior
When a new entity is created in HA, it should be available in NR, specially after a restart.
> (What you expected to happen)
Newly added Entity IDs in HA to be available in NR
## Actual behavior
New entities do not appear in NR
> (What actually happened)

## Steps to reproduce
Create new Entity in HA
Create new State node in NR
Select Entity drop down
> (How can someone else make/see it happen)

## Proposed changes
Refresh cache of Entity Ids on demand
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Protection mode is not used by this add-on.

Furthermore, add-ons wrap existing software. In this case the Home Assistant Node-RED node is responsible for this. Please report your issue with them.

Thanks! 👍

**Comment by DesertDwellerEv** [comment]
Oh sorry. Thought I was so NodeRed
