### ISSUE TITLE
502 bad gateway.. still

### ISSUE THREAD

**Issue by dlo747** [hassio-addons/addon-node-red#561]
# Problem/Motivation

Clicking on Open Web UI resulted in 502 Bad Gateway.

## Expected behavior

Node Red add-on welcome page

## Actual behavior

502 Bad Gateway.

## Steps to reproduce

Reinstalled NodeRed. 
Restored a working snapshot of NodeRed

## Proposed changes

Help with getting it to work.. Thank you

`[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1244 (offset 713 lines).
> @serialport/bindings@8.0.8 install /config/node-red/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=12.15.0 runtime=node arch=arm libc=musl platform=linux)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.19.114-v7l
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@8.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-07T21_37_30_258Z-debug.log
[17:37:30] FATAL: Failed un-installing conflicting packages
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

credential_secret: password1234567
dark_mode: false
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: true
system_packages:
  - make
  - g++
  - gcc
  - python
  - linux-headers
npm_packages: []
init_commands: []

**Comment by frenck** [comment]
I feel like you config is incomplete, as there are no custom packages?

**Comment by dlo747** [comment]
Its a brand new install. No packages. I tried to reinstall it and its still giving me same errors

**Comment by sinclairpaul** [comment]
It's a snapshot restore though?

Can you try the following, backup your flows.json from your config/node-red folder.

Uninstall the addon, remove the config/node-red folder.

Reinstall the addon, start and make sure it works.

Stop the addon, copy the flows.json back and restart.

It sounds to me there is a conflict between the addon install and the snapshot version of the nodes.

**Comment by dlo747** [comment]
Thank you Sinclairpaul. That worked!
