### ISSUE TITLE
Fail on initial add

### ISSUE THREAD

**Issue by warb12** [hassio-addons/addon-node-red#574]
# Problem/Motivation
Just trying out this add-on

> (Why the issue was filed)
Failure.

## Expected behavior

> (What you expected to happen)

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 6.2.0
 You are running the latest version of this add-on.
 System: HassOS 3.13  (armv7 / raspberrypi4)
 Home Assistant Core: 0.110.3
 Home Assistant Supervisor: 224
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[22:47:56] FATAL: 
[22:47:56] FATAL: SSL has been enabled using the 'ssl' option,
[22:47:56] FATAL: this requires a SSL certificate file which is
[22:47:56] FATAL: configured using the 'certfile' option in the
[22:47:56] FATAL: add-on configuration.
[22:47:56] FATAL: 
[22:47:56] FATAL: Unfortunately, the file specified in the
[22:47:56] FATAL: 'certfile' option does not exists.
[22:47:56] FATAL: 
[22:47:56] FATAL: Please ensure the certificate file exists and
[22:47:56] FATAL: is placed in the '/ssl/' directory.
[22:47:56] FATAL: 
[22:47:56] FATAL: In case you don't have SSL yet, consider getting
[22:47:56] FATAL: a SSL certificate or setting the 'ssl' option
[22:47:56] FATAL: to 'false' in case you are not planning on using
[22:47:56] FATAL: SSL with this add-on.
[22:47:56] FATAL: 
[22:47:56] FATAL: Check the add-on manual for more information.
[22:47:56] FATAL: 
[cont-init.d] nginx.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The instruction is in the error message?

You have SSL enabled on the add-on configuration but it can't find the specific certificate files. Either make sure the certificates exist or disable SSL.

**Comment by warb12** [comment]
Yea, I saw the error. I was just trying to point out that the add-on failed to install on a fresh install of home automation. I did not change or request SSL. I did add the wemo add on and maybe one more, maybe one of them set the request for SSL, but they did not fail.
