### ISSUE TITLE
Can‘t start clean / from scratch

### ISSUE THREAD

**Issue by neotrace** [hassio-addons/addon-node-red#578]
# Problem/Motivation

> Accicentally installed the wrong palette and wanted to start over. After uninstalling via home assistant supervisor, deleting config folder, reboot and reinstalling node-red the wrong palette is still there! tried for 3 hours with portainer and init_commands to uninstall palette. could not get it to work. 

## Expected behavior

> Reinstall should give you a fresh install like it was the first time you installed the addon

## Actual behavior

> Addon palette still installed in node-red, cant uninstall

## Steps to reproduce

> install palette node-red-contrib-home-assistant-websocket and try uninstall / reinstall of node-red

Please help, I have an unusable node-red now.

**Comment by sinclairpaul** [comment]
Node red configuration is held in the config/node-Red folder (the one accessible via SSH/SMB).  Did you stop the addon and remove that folder?

**Comment by neotrace** [comment]
yes, as i states above I deleted config/node-red multiple times via smb. when node-red comes up again after reinstall the palette from before is still there. seems like the container does not get deleted and is just reused to me. very frustrating for me that you can install a palette so easily but uninstalling has cost me hours without any result.

**Comment by sinclairpaul** [comment]
As you haven't posted your system details, its hard to tell what is happening.

The addon will store information in the relevant /data folder on the host, and for node-red, in the config folder.  On an uninstall both the data folder and image will be removed.  Do you have other software on your host that could be managing the containers?

**Comment by neotrace** [comment]
I am using hassos as a vm in a proxmox virtualization environment. did not alter anything to the system in any way after importing the vmdk.. 
i only installed portainer as an addon from supervisor hoping to find a solution. but did not change anything with it.
When I uninstall, nothing gets deleted as far as I can see. I manually deleted the node-red folder in config. No change. Did not know about /data, will check.

**Comment by neotrace** [comment]
wait - i just realized something: is node-red-contrib-home-assistant-websocket installed by default in a fresh install?

**Comment by sinclairpaul** [comment]
Yes, the add on is pre-configured with the HA node.

https://github.com/hassio-addons/addon-node-red/blob/93425065e2a8052a1f48eef3e3a21c0d8f25e5f3/node-red/package.json#L23

**Comment by neotrace** [comment]
Oh my God, how embarrassing... I think I watched an old tutorial on how to get node-red working inside home assistant and it stated you have to manually install a palette to get it to work. 
That tutorial also stated to use the palette without -websocket at the end. I guess this is all outdated now!?

I thought I had accidentally installed the wrong Version but instead it is pre-configured. That explains why it keeps showing up after uninstall. 

Sorry for the wrong bug report. really hard to get started as a newbie with so much outdated information out there.

Keep up the great work! Regards, Steffen
