### ISSUE TITLE
WebSocket closed - Message size exceeds limit

### ISSUE THREAD

**Issue by poberth** [hassio-addons/addon-node-red#579]
# Problem/Motivation

Hi,
I recently upgraded my node-red install to 6.3.0 on HA 0.110.4 (HassOS 4.8 / Supervisor 225).

On previous version, node-red was connecting to HA without any problem but now there seems to be a problem with the WebSocket API.

Here is the logs from Supervisor
```
20-06-01 18:06:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-06-01 18:06:53 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
20-06-01 18:06:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
20-06-01 18:06:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 258:WebSocketError('Message size 4392952 exceeds limit 4194304') is not str
20-06-01 18:06:57 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
```
Here is the logs from the node-red add-on
```
1 Jun 14:06:36 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
1 Jun 14:06:36 - [info] [server:Home Assistant] WebSocket Connected to http://supervisor/core
1 Jun 14:06:36 - [debug] [server:Home Assistant] config server event listener connected
1 Jun 14:06:40 - [info] [server:Home Assistant] WebSocket Closed http://supervisor/core
```

My node-red Home Assistant palette is configured with the "I use the Home Assistant Add-on" setting.

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
`Home Assistant WebSocket API error: Received message 258:WebSocketError('Message size 4392952 exceeds limit 4194304') is not str`

This is either an issue with the Home Assistant palette/Node in Node-RED itself or Home Assistant Core. 

From an add-on perspective, there is not much I can do.

Upstream project:

<https://github.com/zachowj/node-red-contrib-home-assistant-websocket>
