### ISSUE TITLE
Node-red RFXCOM contrib

### ISSUE THREAD

**Issue by Kouwe-sudo** [hassio-addons/addon-node-red#582]
# Problem/Motivation

After updating Node-red from 6.2.0 to 6.3.0 RFXCOM-contrib gives errors and Node-Red won't start. After deleting RFXCOM-contrib again Node-red works just fine expect I have to disable all my RFXCOM-flows and find yet another solution. This problem is different from the one closed just days ago. where someone tried to add RFXCOM-contrib via the palette (which never worked for me) 

> (Why the issue was filed)

## Expected behavior
That it works just as fine as in 6.2.0

> (What you expected to happen)

## Actual behavior
Log:

Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 6.3.0
 You are running the latest version of this add-on.
 System: HassOS 4.8  (armv7 / raspberrypi3)
 Home Assistant Core: 0.110.4
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
[16:39:54] INFO: Password is NOT in the Have I Been Pwned database! Nice!
patching file nodes/ui_base.html
Hunk #1 succeeded at 1177 (offset 646 lines).
audited 269 packages in 11.558s
15 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[16:40:13] INFO: Starting installation of custom NPM/Node-RED packages...
> @serialport/bindings@8.0.8 install /opt/node_modules/rfxcom/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=12.15.0 runtime=node arch=arm libc=musl platform=linux)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 5.4.42-v7
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/rfxcom/node_modules/@serialport/bindings
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@8.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-04T14_41_08_044Z-debug.log
[16:41:08] FATAL: Failed to install a specified npm package
[cont-init.d] user.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

> (What actually happened)

## Steps to reproduce
Add: 

certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: false
system_packages: []
npm_packages:
  - node-red-contrib-rfxcom
init_commands: []

To the configuration file

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Try to go back to 6.2.0 but snapshot don't allow rollback of only one item all of a sudden. Also since last release

**Comment by sinclairpaul** [comment]
It is missing the dependencies used to build the node.  Try:
```
system_packages:
  - make
  - g++
  - gcc
  - linux-headers
npm_packages:
  - node-red-contrib-rfxcom
```

**Comment by Kouwe-sudo** [comment]
Thank you. That did the trick.
