### ISSUE TITLE
Manage Palette

### ISSUE THREAD

**Issue by glavermicocca** [hassio-addons/addon-node-red#583]
# Problem/Motivation

on Raspberry pi 4 node-red-contrib-generic-ble doesn't work -> from Manage Palette in HassOS 4.10
![Annotazione 2020-06-08 145752] (https://user-images.githubusercontent.com/10889124/84032962-728a2280-a998-11ea-99b3-fcd1348af01e.jpg)

<blockquote></blockquote>

**Comment by frenck** [comment]
The error tells it is missing `make`. Apparently, it needs to build something. Please make sure to install dependencies needed by the node you are trying to install.

**Comment by glavermicocca** [comment]
Thanks for your reply, i read it but how can i install MAKE in Hassio.io through shell?

**Comment by frenck** [comment]
https://github.com/hassio-addons/addon-node-red/blob/master/node-red/DOCS.md#option-system_packages

**Comment by glavermicocca** [comment]
Maybe there is somthing that i don't well understand - i used https://www.home-assistant.io/hassio/installation/ to install in a raspberry pi3 32bit Hassio.io (turn key) than i install NodeRed from Hassio.is addons and i try to install  node-red-contrib-generic-ble for bluetooth scan but nothing seems to work (this first test was related to turn key installation)

I also follow "non turn key" solution with Raspbian pi4 32bit vanilla installation - in this second solution i was able to install with npm without any problem but when i try to "scan" nothing seems to work (just to be clear i follow strictly online instructions -> sudo usermod -G bluetooth -a pi) - nodejs v8 (for bluetooth raspbian compatiblity)

All i would like to do is to install Hassio with raspberry pi3/4 from iso and using bluetooth in nodered - is that possible?

Thanks

**Comment by frenck** [comment]
The add-on comes pre-installed with a lot of commonly used palettes, if you need additional, feel free to add so.
However, some might have an addition build dependencies, which can be added if needed.

Customizations have nothing to do with "turn-key".

**Comment by glavermicocca** [comment]
I know what do you mean about "customization" i have investigate more to understand all your work. I will try "build dependencies". Thanks
