### ISSUE TITLE
nodered.switch: Platform not found

### ISSUE THREAD

**Issue by djansen1987** [hassio-addons/addon-node-red#587]
# Problem/Motivation

> Since the update to Hassio 0.111.2 my nodered switches are not working anymore. Crusial to my config. Hope it can be fixed.
All palets are updated in NodeRed. Addon is up2date. 

## Expected behavior

> When Nodered (addon) started it should create entities within HA, in my case a Switch

## Actual behavior

 >Invalid config
The following integrations and platforms could not be set up:
nodered.switch
Please check your config.
1 minute ago

> errorlog: Unable to prepare setup for platform nodered.switch: Platform not found (cannot import name 'EVENT_AUTOMATION_TRIGGERED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

## Steps to reproduce

> Update HA to latest version (currently 0.111.2), create a flow with a entity (type switch) deploy and restart HA

## Proposed changes

> N/A

**Comment by frenck** [comment]
That is not code or an error message from this add-on. Please report your issue with the custom component that causes this.

**Comment by SHHA24** [comment]
Hi 
This is the exact issue I am having, could you explain what you mean by this is not code or.... from this add on? @frenck 
My understanding is the node red add on and the link into HA is not working anymore. 
Please let me know what info you need? 
Thanks

**Comment by frenck** [comment]
This is not from this add-on, it is a custom component by the same author of the node-red palette for node-red, that this add-on uses.

The custom component can be installed by a user, but isn't installed, recommended or affiliated with this add-on.
