### ISSUE TITLE
Node-Red with Home Assistant 0.111.2

### ISSUE THREAD

**Issue by SHHA24** [hassio-addons/addon-node-red#588]
Updated to 0.111.2, and Node Red add on has stopped reporting on the HA node states, for switches and sensors. 
Have uninstalled Node red add on, removed all files, reinstalled via add on store, followed all the steps to add the config into HA. 

within Node red the nodes report as connected and they are set as "using HA app" for the server.
but the state doesn't feed back to HA, and if i add a new HA node in node red it doesn't appear as an entity as it should. 

anyone else having issues, what logs would be best to share? 

thanks

**Comment by sinclairpaul** [comment]
> but the state doesn't feed back to HA

This is a function of the custom component isn't it? Please see #587 if applicable and ensure you update it.

If not please post relevant logs

**Comment by SHHA24** [comment]
https://github.com/hassio-addons/addon-node-red/issues/587#issuecomment-646104469

Hi this is the same issue. 

Thanks
