### ISSUE TITLE
!secret not supported through HA hassio addon interface

### ISSUE THREAD

**Issue by lukassvec** [hassio-addons/addon-node-red#59]
# Problem/Motivation

> !secrets is stated to be supported but the Hass.io configuration page does not allow the file to be saved when the passwords are not in quotes "". The secret keyword is not entered as string. If implementation.

## Expected behavior

> When entering the passwords as references to the secret file (e.g. !secret key_word), the config file should be savable.

## Actual behavior

> When anything other than a string is entered into the config file, Hassio does not allow the changes to be saved.

## Steps to reproduce

> Go into an installed Node-red addon in Hass.io (Hass.io tab in the HA interface) and try entering text for passwords that are not in quotes. The save button becomes inactive, not allowing !secret to be used..  

## Proposed changes

Update documentation if patch cannot be made.

**Comment by frenck** [comment]
It should be in quotes. The Hass.io configuration is in JSON format, unlike the Home Assistant YAML configuration format.
