### ISSUE TITLE
Stuck on "Websocket Connecting" after HA update

### ISSUE THREAD

**Issue by rogersmj** [hassio-addons/addon-node-red#591]
# Problem/Motivation

> After updating HA from (I believe) 0.108 to 0.111.4, Node Red no longer works. All the nodes are stuck on “connecting”, and the Node Red add-on’s log keeps repeating the following over and over after getting through all the startup stuff:

`19 Jun 22:59:58 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core`

It just keeps repeating that and never stops.

I’ve tried:

1. Updating the supervisor (now on version 227) and Host os (now on HassOS 4.10)
2. Rebooting the server
3. Updating Node-Red add-on to the latest version (now on 6.3.0)
4. Changing the credential_secret to something else, starting the add-on, then changing it back (someone said this might work…it didn’t)
5. Resetting the Node-Red add-on’s config to default (only changing my credential_secret back to what it was)
6. Exporting all my flows, uninstalling the NR add-on, and re-installing.
7. Un-checking "I use the Home Assistant Add-On" option in the Home Assistant configuration node, saving and then re-checking it and saving again.

None of the above had had any effect. Since all my home's automations are done in NR now, my house is totally dumb at the moment.

I haven't observed any other connection issues to Home Assistant. My mobile app works, Alexa works. Only NR seems to be having an issue.

## Expected behavior

> Node Red can connect to HA.

## Actual behavior

> Node Red log shows never-ending "WebSocket Connecting http://supervisor/core" message

## Steps to reproduce

> Unsure; I am on HA 0.111.4 and Node-RED add on 6.3.0. I don't think I have anything particularly weird with my setup, I'm using all official add-ons. NR has worked fine for over a year.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by SHHA24** [comment]
hi @rogersmj 
there seems an issue here, see the issue at #587 
https://github.com/hassio-addons/addon-node-red/issues/587#issue-638431607 
im still trying to resolve this also, let me know if you get it working again.

**Comment by bretttickx** [comment]
I now have the same issue when upgrading hassio to 0.113 im on node red addon 7.0.0 did you find a way of fixing it @rogersmj ?

**Comment by bretttickx** [comment]
i downgraded to 0.112.1 and now its all working again

**Comment by dennisbrouwer91** [comment]
Same problem here now :(

**Comment by wesleysieses** [comment]
After upgrading from 0.107 to 0.115.1 I'm having the same issue. Downgraded to 0.112.1 but that didn't work.. Anyone got a solution?

**Comment by sinclairpaul** [comment]
Assuming this is resolved, however if not, it appears to be an issue with the HA Node-Red package rather than the addon.
