### ISSUE TITLE
Missing GPIO and annoying projects pop-up

### ISSUE THREAD

**Issue by Smandurlo** [hassio-addons/addon-node-red#6]
Hello,
thanks for the great work!

I have this message: Warning : Cannot find Pi RPi.GPIO python library (no gpio node loaded)

And I cannot find the way to remove the "projects" popup opening Node-Red. I don't want to create any project on github nor want to clone any repository...

Thank you!

**Comment by frenck** [comment]
@Smandurlo The GPIO message can be safely ignored. This is documented as well:

<https://github.com/hassio-addons/addon-node-red#known-issues-and-limitations>

The project settings can be disabled in the Node-RED configuration. Please refer to the Node-RED documentation for information about this:

<https://nodered.org/docs/user-guide/projects/>

(Please note, the documentation writes about enabling this, disabling would be the same but the option sets to `false` in that case.)
