### ISSUE TITLE
Node red does not recognise the Home assistant plugin

### ISSUE THREAD

**Issue by tre4b** [hassio-addons/addon-node-red#601]
# Problem/Motivation
I am trying to use Node-Red in HA to manage my devices

## Expected behavior
Installed the pluggin and expected that NodeRed would know about the devices in my Home Assistant setup.  

## Actual behavior
Noted that the Entity block had a red note saying to install a pluggin.  Followed the link installed the plugin, rebooted everything several times, however the Entity block still has that entry and I cannot see HA entities anywhere in Node red

## Steps to reproduce
Not sure,  I cannot seem to get anyone to respond and help on discord or anywhere else.  I don't think anyone else is seeing this however I have been through all the documents and webpages I can and it simply does not work.

## Proposed changes
Either resolve the issue or make clearer the setup steps necessary to ensure the system will work.  I have tried unistalling all parts and reinstalling however I still have not managed to fix it and am loosing heart.  It looks so cool but with no connection to HA it is almost impossible to make any real use of :-(

**Comment by sinclairpaul** [comment]
The Entity node creates entities within HA from Node Red and requires a custom integration installed, this is out of scope for the addon itself and you would need to seek help on it at the repo for the custom integration.

The other Nodes, such as Current State, Call Service etc, should work as installed from the addon, and will give you information from HA.

Please note, Github is used for issue and bug tracking, it is very difficult to provide how-to information here.

**Comment by tre4b** [comment]
Yep, it's installed.  Node red just refuses to acknowledge it.

Apologies for contacting this way it was a last ditch attempt to get someone to talk to me about it.

Trev

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by frenck** [comment]
As said, this is out of scope for the add-on. Please contact the author of the custom component or the maintainer of the HA node.
