### ISSUE TITLE
node-red-contrib-light-scheduler Not displaying scheduler correctly.

### ISSUE THREAD

**Issue by mbedworth** [hassio-addons/addon-node-red#605]
# Problem/Motivation

I use node-red-contrib-light-scheduler for scheduling lights in my HA  setup.  After the upgrade to Node-Red v7 the scheduling area is not displayed correctly.

**Comment by frenck** [comment]
Please report your issue @ the node-red-contrib-light-scheduler project.

Thanks 👍

**Comment by mbedworth** [comment]
Wow ok. Was just trying to help.
