### ISSUE TITLE
Plugin 7.0.0 does not start on Raspberri Pi 4

### ISSUE THREAD

**Issue by formatBCE** [hassio-addons/addon-node-red#608]
# Problem/Motivation
After update to 7.0.0, plugin can't start on Raspberry Pi 4 Model B
Log:
Can't create container from addon_a0d7b954_nodered: 404 Client Error: Not Found ("No such image: hassioaddons/node-red-armv7:7.0.0")
Looks like arm package isn't there.

**Comment by sinclairpaul** [comment]
The image is available.  The 404 is generally caused by one of two things, name resolution so the system cannot pull the image, or disk space where there is not enough space to store the image.
