### ISSUE TITLE
Ping Node not working as described after update.

### ISSUE THREAD

**Issue by PierreScerri** [hassio-addons/addon-node-red#610]
# Problem/Motivation

> (Why the issue was filed)
Behaviour of the ping node changed, possibly after a recent update of the Node-Red addon
## Expected behavior
> (What you expected to happen)
The ping node should output false if the pinged address does not respond

## Actual behavior
> (What actually happened)
Nothing comes out of the ping node when an unresponsive address is pinged.
A responsive address outputs the expected payload.

## Steps to reproduce
> (How can someone else make/see it happen)
Add ping node with a valid IP address that pings every 5s.  Add debug node to see output.

Current Log:
```
11 Jul 15:52:46 - [info] Node-RED version: v1.1.0
11 Jul 15:52:46 - [info] Node.js  version: v12.17.0
11 Jul 15:52:46 - [info] Linux 4.19.127-v7 arm LE
...
11 Jul 16:06:33 - [info] [ping:5d529e6e.9ce42] ping - Host '192.168.1.162' process timeout - sending SIGINT
...

```
The issue was there with NR v1.0.6, Node.js 12.15.0 and ping version 0.2.0

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Addons wrap existing applications (and thus nodes). Please report this issue with the author of the ping node. Thanks 👍
