### ISSUE TITLE
Addon does not start 

### ISSUE THREAD

**Issue by Klagio** [hassio-addons/addon-node-red#62]
Since yesterday the addon does not start, was before. I don't know what happened 

18-10-23 18:55:27 INFO (SyncWorker_9) [hassio.docker.interface] Clean hassioaddons/node-red-amd64 Docker application
18-10-23 18:55:29 ERROR (SyncWorker_9) [hassio.docker] Can’t start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error (“linux runtime spec devices: error gathering device information while adding custom device “/dev/ttyUSB0”: no such file or directory”)

**Comment by Klagio** [comment]
Hassio 0.80.3 on Ubuntu NUC.

Nothing in the addon log

**Comment by rodhall** [comment]
I am also now getting the following log error even after Supervisor restarts and uninstall/reinstall of Node-Red.

26 Oct 07:36:32 - [error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>

I see that this had occurred in the past but my Node-Red was working fine and now isn't

**Comment by frenck** [comment]
This issue in the OP is not related to the add-on, but Hass.io. This is not something I can help with, maybe try the Hassio repository.

@rodhall That issue is not related to this issue, but v1.0.0 got out just now, which should take care of that.
