### ISSUE TITLE
can't start node-red

### ISSUE THREAD

**Issue by GHSTUDIO1** [hassio-addons/addon-node-red#635]
I installed node.red 7.0.0 on Home Assistant. Configured it:

credential_secret: '0123456789'
dark_mode: false
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: false
system_packages: []
npm_packages: []
init_commands: []

saved the port and started the integration.  Waited a minute and tried to open web UI.....got "bad gateway" and found that node-red had stopped itself.

I have tried entering http node username and password with the same results.  I just can't get node-red started.

The only message I see in my logs is:

ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62034 ssl:None [Connection refused]

**Comment by sinclairpaul** [comment]
Please post the Node Red Addon startup log.
