### ISSUE TITLE
Telegram Webhook on port 46836 not reachable

### ISSUE THREAD

**Issue by dongore** [hassio-addons/addon-node-red#637]
# Problem/Motivation

I installed the "node-red-contrib-chatbot" Palette which uses a webhook to connect to Telegram. In this addon it is created on a different port that can't be reached.

## Expected behavior

On the standalone Node Red istallation the webhook is reachable on the standard port:

```
------ WebHooks for TELEGRAM----------------
http://localhost:1880/redbot/telegram/test
http://localhost:1880/redbot/telegram
```

## Actual behavior

On this hassio addon  it is on a different port:

```
------ WebHooks for TELEGRAM----------------
http://localhost:46836/redbot/telegram/test
http://localhost:46836/redbot/telegram
```

and I can't connect to http://noderedip:1880/redbot/telegram ( Cannot GET /redbot/telegram)
or http://noderedip:46836/redbot/telegram (ERR_CONNECTION_REFUSED)

## Steps to reproduce

install "node-red-contrib-chatbot" Palette and check the log for the webhook entries above

## Proposed changes

I'm just guessing that has something to do with the ingress feature?! The different port is specified for the upstream backend and there is probably some access restriction in place.

**Comment by sinclairpaul** [comment]
Node-Red runs on a different port internally on the container.

Nginx listens on 1880 and forwards, however anything outside of the /endpoint/ path has authentication set.

**Comment by dongore** [comment]
I know, I have filled out the basic auth prompt, but still for "noderedip:1880/redbot/telegram" it only says "Cannot GET /redbot/telegram" instead it shoud show a status code of the webhook.

**Comment by frenck** [comment]
you cannot use `/redbot/telegram`, only endpoints starting with `/endpoint/` can use it.
As per add-on documentation.

**Comment by Diddlik** [comment]
@dongore did you solved your problem? At the moment I am working on setup webhook for telegram in node-red

**Comment by dongore** [comment]
@Diddlik yes, as frenck mentioned you have to add `/endpoint/` to the URL:
`yourip:1880/endpoint/redbot/telegram`

**Comment by Diddlik** [comment]
> 
> 
> @Diddlik yes, as frenck mentioned you have to add `/endpoint/` to the URL:
> `yourip:1880/endpoint/redbot/telegram`

I have external access to home assistant like: ha.mydomain.com, node-red has a link like:
https://ha.mydomain.com/ablabde_nodered.

If I put endpoint like this: https://ha.mydomain.com/endpoint/ablabde_nodered
I get this error on weghookinfo: "Wrong response from the webhook: 404 Not Found"

**Comment by dongore** [comment]
> > @Diddlik yes, as frenck mentioned you have to add `/endpoint/` to the URL:
> > `yourip:1880/endpoint/redbot/telegram`
> 
> I have external access to home assistant like: ha.mydomain.com, node-red has a link like:
> https://ha.mydomain.com/ablabde_nodered.
> 
> If I put endpoint like this: https://ha.mydomain.com/endpoint/ablabde_nodered
> I get this error on weghookinfo: "Wrong response from the webhook: 404 Not Found"

Don't forget the listening port.
