### ISSUE TITLE
Unable to add / change schedules in Light Scheduler node

### ISSUE THREAD

**Issue by elrogalo** [hassio-addons/addon-node-red#642]
# Problem/Motivation

I noticed today, that it is impossible to add new or modify existing scheules in Light Scheduler (LS) nodes in my flows. There seem to be display / edit error of the graphs inside the scheduler table.

## Expected behavior

Clicking and dragging inside LS table should add new schedule bar or modify existing one. 
All of my LS nodes contain a schedule for whole week, which should be displayed as bars. Instead of them I can only see the bar for Monday, and a dot in place of the Tuesdays bar.

![grafik](https://user-images.githubusercontent.com/69166053/89216059-11628200-d5ca-11ea-96df-38ac8a7969d2.png)

## Actual behavior

When I click on the Monday bar it "jumps" over to the Tuesdays schedule, the dot also moves also one place. That goes all the way to the end of the schedule table.

![grafik](https://user-images.githubusercontent.com/69166053/89216353-8766e900-d5ca-11ea-8e77-00f8a236b61f.png)

![grafik](https://user-images.githubusercontent.com/69166053/89216386-96e63200-d5ca-11ea-8c09-9ded18f34c3d.png)

That goes for all existing nodes.
Drawing new schedule bars deos not work as well, well it seems to work, but the coloured bar is drawn in opaque color and dissapears after releasing mouse button.
Clicking and drawing in place where a bar is supposedly present (although not visible) is causing the cursor to change to crossed circle (couldn't register than on screen capture).

## Steps to reproduce

Open existing or add new LS node and try to edit schedule table.

## Proposed changes

Seems that the issue is realted to some of the recent updates, I didn't notice when the problem started though. 
Despite the display and editing problems all scheduler nodes that I have in flows are still working properly and react to override commands.
I am using Home Assistant 0.113.3 on HassOS 4.11 with Supervisor version 229 on Raspberry Pi 4B.

**Comment by frenck** [comment]
Thank you for opening an issue @elrogalo, however...

Add-ons wrap existing software, in this case: Node-RED with the scheduler node.
Please report this issue directly with the scheduler node project. If they fix the issue, the add-on will be updated as well.
