### ISSUE TITLE
Wait until node does not work when EntityId is dynamic

### ISSUE THREAD

**Issue by ngelotte** [hassio-addons/addon-node-red#647]
# Problem/Motivation

> I am reusing a subflow with different components in my Home Assistant System. So I need to pass the EntityId into the wait until node. But it never triggers. 

## Expected behavior

> If I set the Entity_Id either with a Mustache template using a flow variable, a Mustache template with a data from msg or  a message set to entity_id it should send a message when the state of the Entity_Id when the Entity changes state. 

## Actual behavior

> The timeout is the only thing that ever fires. If I debug the full message coming out of the timeout it says that the component is in the state expected and that it change xxxx ms ago. So it is kind of connected. 

## Steps to reproduce

> Save the name of the enitity in a flow variable or set the incoming msg to have the name of the enitity. Create a Wait Until node and set the Entity_Id to a mustache template for the passed in value. Create a debug node on the out and on timed out. 
![NodeRed](https://user-images.githubusercontent.com/16006512/89613977-4ecc4700-d838-11ea-8560-2249c1701a27.JPG)

## Proposed changes

If I use the current state node with the same Mustache Template it correctly displays the state. Also, It does pass the correct state information in the data when timing out. So it is kind of connected but not actually triggering.

**Comment by frenck** [comment]
Add-ons wrap existing software. Please report this specific issue upstream with the Home Assistant nodes for Node-Red.

Thanks 👍
