### ISSUE TITLE
Unable to login. 

### ISSUE THREAD

**Issue by vandalon** [hassio-addons/addon-node-red#67]
# Problem/Motivation

After removing the Users list from the plugin settings I can not login. Allthough loging says i'm authenticated successful:

30 Oct 08:46:56 - HA Auth - joris authenticated

## Expected behavior
Get the node-red ui after login

## Actual behavior
Keep getting the login screen

## Steps to reproduce

Not sure.

**Comment by vandalon** [comment]
Seems to be a browsers issue. In chrome I can login, in safari I can't , also not after clearing caches.

**Comment by vandalon** [comment]
Issues seems to be solved itself after a while. Maybe some session cookies where still there.

**Comment by frenck** [comment]
Node-RED is quite hard on caching on the browser... 😉
