### ISSUE TITLE
New theme for dark mode

### ISSUE THREAD

**Issue by noxhirsch** [hassio-addons/addon-node-red#678]
# Problem/Motivation

The dark mode isn't really that dark with the midnight theme.

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

There's a new theme by the same author which is way darker: https://github.com/node-red-contrib-themes/dark
It would be really cool if that could be the new theme for dark mode.

![image](https://user-images.githubusercontent.com/30938717/92312072-b2739c80-efbd-11ea-8cd2-7d299c9acf49.png)

**Comment by frenck** [comment]
Sorry, I'm not going to add tons of themes to the add-on.
Please raise a feature request @ Node-RED so they get proper theme management in the frontend (like they do with palettes).
