### ISSUE TITLE
Output on Connect no longer works

### ISSUE THREAD

**Issue by SentryMax** [hassio-addons/addon-node-red#682]
## Issue

Output on Connect no longer works on any node 

## Expected behavior

Expect Output on Connect to works on any node as always

## Actual behavior

Since the last two or so updates it stopped working 

## Steps to reproduce

Just try Output on Connect on any node

## Proposed changes

Just fix it if possible

**Comment by sinclairpaul** [comment]
I believe this is a function of the Node Red HA palette, so you would need to log the issue at https://github.com/zachowj/node-red-contrib-home-assistant-websocket

Thanks
