### ISSUE TITLE
Disregard

### ISSUE THREAD

**Issue by disstress** [hassio-addons/addon-node-red#684]
Nevermind

**Comment by frenck** [comment]
> When installing NodeRed in HASSIO via HACS the application does not work.

HASSIO does not exist anymore (for a long time already).
HACS does not install/support add-ons, so that is impossible.

**Comment by disstress** [comment]
Is this not HASSIO https://www.home-assistant.io/hassio/? 

When I am in the Home Assistant GUI and I click on HACS on the sidebar, then click Addons on the primary pane I see NodeRed. 

Am I missing something?

**Comment by frenck** [comment]
Yes, please read the link you've clicked in HACS, as it tells you HACS doesn't have add-ons and provides a convenience link to the supervisor.. Please learn the difference between add-ons and integrations.

Nevertheless, see the add-on or supervisor logs, as a 502 means it is not starting, the logs should tell you why (as also written in the installation notes of the add-on).

**Comment by disstress** [comment]
Holy shit you are an asshole. I was submitting the issue to try and be helpful because there are multiple people posting the exact same thing. I will avoid posting clear bugs in the future and just keep shit to myself.

**Comment by frenck** [comment]
I don't think that is called for. However, considering you calling me an asshole bought you a ban, so no need to return.
