### ISSUE TITLE
is it possible to force upgrade node-red-contrib-home-assistant-websocket to 0.25.1?

### ISSUE THREAD

**Issue by asapkota** [hassio-addons/addon-node-red#690]
# Problem/Motivation

Upgraded add-on to latest 7.2.0 which is supposed to have node-red-contrib-home-assistant-websocket 0.25.1 but the palette still shows 0.24.1 and does not upgrade

## Expected behavior

node-red-contrib-home-assistant-websocket automatically upgrades to 0.25.1 when add-on is started

## Actual behavior

node-red-contrib-home-assistant-websocket automatically does not upgrade

Log below:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 7.2.0
 You are running the latest version of this add-on.
 System: HassOS 4.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 244
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1178 (offset 647 lines).
audited 368 packages in 3.908s
13 packages are looking for funding
  run `npm fund` for details
found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[12:16:56] INFO: Starting installation of custom NPM/Node-RED packages...
+ node-red-node-tail@0.1.1
+ node-red-contrib-web-worldmap@2.5.4
+ node-red-contrib-web-worldmap@2.5.4
+ node-red-node-rbe@0.2.9
+ node-red-contrib-simple-message-queue@0.2.6
+ node-red-contrib-power-monitor@0.1.2
+ node-red-contrib-light-scheduler@0.0.16
+ node-red-contrib-timerswitch@1.3.0
+ node-red-contrib-average@0.1.8
added 21 packages from 25 contributors, updated 2 packages and audited 1034 packages in 12.204s
46 packages are looking for funding
  run `npm fund` for details
found 6 vulnerabilities (3 low, 3 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:17:10] INFO: Starting Node-RED...
> addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
17 Sep 12:17:11 - [info] 
Welcome to Node-RED
===================
17 Sep 12:17:11 - [info] Node-RED version: v1.1.3
17 Sep 12:17:11 - [info] Node.js  version: v12.18.3
17 Sep 12:17:11 - [info] Linux 5.4.63 x64 LE
17 Sep 12:17:12 - [info] Loading palette nodes
17 Sep 12:17:14 - [info] Worldmap version 2.5.1
17 Sep 12:17:14 - [info] Dashboard version 2.23.3 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
17 Sep 12:17:15 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
17 Sep 12:17:15 - [info] Settings file  : /etc/node-red/config.js
17 Sep 12:17:15 - [info] Context store  : 'default' [module=localfilesystem]
17 Sep 12:17:15 - [info] User directory : /config/node-red/
17 Sep 12:17:15 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Sep 12:17:15 - [info] Flows file     : /config/node-red/flows.json
17 Sep 12:17:15 - [info] Server now running at http://127.0.0.1:46836/
17 Sep 12:17:15 - [info] Starting flows
[12:17:15] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
17 Sep 12:17:15 - [info] Started flows
17 Sep 12:17:15 - [info] [mqtt-broker:MQTT] Connected to broker: mqtt://192.168.171.241:1883
17 Sep 12:17:20 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Sep 12:17:20 - [info] [server:Home Assistant] Connected to http://supervisor/core

**Comment by sinclairpaul** [comment]
Can you check the contents of config/node-red/package.json?

The updated palette is installed by the addon, but it looks like something else maybe changing the version for you.

**Comment by frenck** [comment]
The add-on ships with that version, unless you have manually changed or forced it. This is out of scope for the add-on and your own doing. Can't help with that.
