### ISSUE TITLE
Power Performance / Hanging after upgrade - Rolledback

### ISSUE THREAD

**Issue by joemadd3n** [hassio-addons/addon-node-red#694]
# Problem/Motivation
Upgraded from 7.1.1 to 7.2.1 and whilst NodeRed continued to work and process flows it resulted in the Supervisor page just hanging and not loading. I rolled back the version to to 7.1.1 and the issue has disappeared. The machine has plenty of resources available to it so not sure why the new version is causing Supervisor to hang.

I am running;
Supervisor 245
Home Assistant 0.114.4

**Comment by frenck** [comment]
Would need logs showing problems, traces or reproductions to be able to address such an issue. Unfortunately, there is not much for me to start working on with the issue description provided.

**Comment by joemadd3n** [comment]
> Would need logs showing problems, traces or reproductions to be able to address such an issue. Unfortunately, there is not much for me to start working on with the issue description provided.

Absolutely, totally appreciate that.
Let me try and upgrade again now I'm back to a healthy position and see if I can replicate the problem and give you more detail.

Thanks for replying
