### ISSUE TITLE
High Swap usage

### ISSUE THREAD

**Issue by marcinbauer85** [hassio-addons/addon-node-red#696]
# Problem/Motivation

> After 10-20hrs Node-RED takes as much swap file as it possibly can (always at 100% /w NR)

## Expected behavior

> Have the swap file usage as it is upon starting it

## Actual behavior

> Uses up all of the swap file

## Steps to reproduce

> Run NR with some basic automations (3-8 nodes long), Hassio, RPI 3B+

## Proposed changes

> Not make it take up 100% of the swap file.

**Comment by frenck** [comment]
The add-on does not care or work with swap files. It is not the job of the add-on to manage that.

Sounds like there is a memory leak in node-red or one of the components. I'm not seeing the same behavior, nevertheless, similar to my other answer: This is unfortunately out of scope for the add-on.

Add-on wraps existing software, the software running inside this add-on is not managed or created by me. Please report your issue upstream. Thanks 👍

**Comment by marcinbauer85** [comment]
I understand, thanks frenck!
