### ISSUE TITLE
Node-Red login suddenly failed

### ISSUE THREAD

**Issue by TKDJesper** [hassio-addons/addon-node-red#70]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by TKDJesper** [comment]
Hi... 
My Node-RED add-on suddenly stopped working last night and when I try to login to the WebUI the login fails. 
I haven't changed anything within the last 24 hours but it seems like something is wrong with the Node-Red account. 
How can I get access back to my account?
Best Regards Jesper

**Comment by TKDJesper** [comment]
The add-on is set to auto update and it is running 1.0.0 now... So I guess it has done it by itself...

**Comment by frenck** [comment]
Well, please read the relese notes and announcements, since this major version upgrade has backwards breaking changes.

**Comment by TKDJesper** [comment]
Thanks...
