### ISSUE TITLE
Error in new version (7.2.3)

### ISSUE THREAD

**Issue by mihail4anov** [hassio-addons/addon-node-red#709]
# Problem/Motivation

After update my function node started to give ma an error in debug window.
**const start = states['input_datetime.alarm1'].attributes;**
Gives me smth which says that states is undefined. As I understand it stopped to get attributes from input_datetime. I checked this entity and it seems ok.

**Comment by frenck** [comment]
Not much I can do about that from an add-on perspective.

Please report your issue with the actual node that provides this data:

<https://github.com/zachowj/node-red-contrib-home-assistant-websocket>
