### ISSUE TITLE
Nodered add on (Hassio) Connection to home assistant could not be established with config: http://hassio/homeassistant

### ISSUE THREAD

**Issue by ceaswaran** [hassio-addons/addon-node-red#71]
My Node red not able to configure home assitant componet (Call service)
I see the following errors

Node Red Add on log:
``
1 Nov 09:24:16 - [error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password not used> <accessToken not used>
``

Home assitant error log as follows
``
18-11-01 04:02:59 WARNING (MainThread) [hassio.api.proxy] Unknown Home Assistant API access!
``

How to resolve this Please help
Using Hassio on Raspberr y pi 2 
Node red hassio addon version 1.0.1
Node Red Pallet manager version say v0.19.5
Hassio Version 0.81

Please Help

**Comment by rmrozinsky** [comment]
Similar circumstance with:

HassOS 1.12 Hassio Supervisor 140
Node-Red 1.1.0
RPi 3 B

I've tried setting up the call service node server base URL with:
http://hassio/homeassistant
http://rpi ip addr:1880
and get the respective node-red log message:
Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant

Node-Red config file 
{
  "log_level": "info",
  "credential_secret": "zzzz",
  "http_node": {
    "username": "xxx",
    "password": "yyy"
  },
  "http_static": {
    "username": "xxx",
    "password": "yyy"
  },
  "port": 1880,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": false,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": []
}

System log recurring message:

WARNING (MainThread) [hassio.api.proxy] Unknown Home Assistant API access!

Installed Home Assistant nodes originally with node-red-contrib-assistant and had problem. Given the comment above, installed the node-red-contrib-home-assistant-llat in pallete manager, still have the problem.

Uninstalled/reinstalled node-red, started/restarted node-red, but unsuccessful. Any insight appreciated. Thanks

**Comment by rmrozinsky** [comment]
After continuing to look into this issue, I've decide to do a fresh install of every thing, hass.io and node red. The difference will be I'll use a different node palette than previous (i.e. I noted on a different webpage you recommended node-red-home-assistant-web socket.

**Comment by frenck** [comment]
I've been seeing this issue way too often, I'll try to add a conflict resolver in the next version.

**Comment by frenck** [comment]
Please upgrade to v1.2.0, which takes care of conflicts.

**Comment by rmrozinsky** [comment]
Thanks for all the assistance. In process of doing this from a fresh install. 

I can see v1.2.0 on the github page, but when I add the repository https://github.com/hassio-addons/repository to hass.io the node red install is v1.1.0. Not sure how to get the new version.

**Comment by frenck** [comment]
@rmrozinsky Go to the Hass.io panel -> Add-on store -> Hit the refresh button in the top right. Wait a minute.... 🎉

**Comment by rmrozinsky** [comment]
Brilliant...almost there. Got it! Appears the Home Assistant nodes were added automatically and there was no need to add via the pallete manager. 

The apparent cause of my problems was using outdated instructions. Thanks much for the help. Coffee on the way!
