### ISSUE TITLE
HowTo downgrade addon?

### ISSUE THREAD

**Issue by artaxx81** [hassio-addons/addon-node-red#713]
Hi there,

do you have a how-to to downgrade the addon-node-red?

Every two month the addon brokes because of an update because of an old node.

I do not want to revert to a backup because of my own dumbness not to update every node before updating the addon.

Thanks
/artaxx

**Comment by frenck** [comment]
Snapshots.

**Comment by artaxx81** [comment]
Not helpful when I forgot to take one.

**Comment by artaxx81** [comment]
OK, snaphot restore restores the version of the add-on but it still broken. I am giving it up.

**Comment by frenck** [comment]
Sorry to hear that. There is not another option I can provide from an add-on perspective. Snapshots is what are available.
