### ISSUE TITLE
Bit confused here breaking change? 

### ISSUE THREAD

**Issue by blair287** [hassio-addons/addon-node-red#717]
# Problem/Motivation

> (Why the issue was filed)

Have I missed a breaking change somewhere?
Noticed some node red flows were not working where i was using switch nodes with properties like "data.old_state.state" which is for manual alarm and noticed that new data is now shown at "data.event.old_state.state".
changed all my flows to now contain the .event after data and are back working again however i also noticed on a flow thats monitoring a lamps brightness the data had moved too from "data.new_state.attributes.brightness" to "data.event.new_state.attributes.brightness" however that flow was still working not sure how.

edit: never mind found out why other were working was using not equal too so it didnt care it was always triggering regardless im a numpty.

still curious if this extra .event and also some attributes are in a completely different place was mentioned anywhere as breaking change? probably was im just blind. sorry

![event node red](https://user-images.githubusercontent.com/44187409/95651876-13265580-0ae5-11eb-9118-5e335e229f23.JPG)

## Expected behavior

> (What you expected to happen)

if the path have now changed to need .event how come things like alarm and device trackers needed to have it added but other things like lamps seem to work without it even though the data doesnt exist there anymore.

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is a question about the palette/node of Home Assistant in Node-RED. The add-on bundles it, but it isn't developed here.

Add-ons bundle existing applications and pack those for easy use. Please file your issue upstream, as this is not related to add-on sources.

Thanks 👍

**Comment by blair287** [comment]
> This is a question about the palette/node of Home Assistant in Node-RED. The add-on bundles it, but it isn't developed here.
> 
> Add-ons bundle existing applications and pack those for easy use. Please file your issue upstream, as this is not related to add-on sources.
> 
> Thanks 👍

it was a bug its now fixed in the latest node red release XD time to change it all back
