### ISSUE TITLE
Unable to Connect to MQTT broker on LAN

### ISSUE THREAD

**Issue by DeviousPenguin** [hassio-addons/addon-node-red#72]
# Problem/Motivation

I'd like to be able to connect to Mosquitto MQTT broker running on my LAN.

## Expected behavior

I have another Raspberry Pi 2 running Raspbian with the latest Node-RED installed, and it connects to my MQTT broker without issue, here's my Node-RED log showing a working MQTT connection:

```
# RASPBIAN LOG #
3 Nov 01:07:20 - [info] Node-RED version: v0.19.5
3 Nov 01:07:20 - [info] Node.js  version: v8.12.0
3 Nov 01:07:20 - [info] Linux 4.9.35-v7+ arm LE
3 Nov 01:07:22 - [info] Loading palette nodes
global Settings { uib_globalSettings: { debug: false },
userDir: '/home/pi/.node-red',
httpNodeRoot: '/' }
3 Nov 01:07:32 - [info] Settings file  : /home/pi/.node-red/settings.js
3 Nov 01:07:32 - [info] Context store  : 'default' [module=memory]
3 Nov 01:07:32 - [info] User directory : /home/pi/.node-red
3 Nov 01:07:32 - [info] Server now running at http://127.0.0.1:1880/
3 Nov 01:07:32 - [info] Active project : ras_pi_node_red_flows
3 Nov 01:07:32 - [info] Flows file     : /home/pi/.node-red/projects/ras_pi_node_red_flows/flows_ras_pi.json
3 Nov 01:07:33 - [info] Starting flows
3 Nov 01:07:34 - [info] Started flows
3 Nov 01:07:35 - [info] [mqtt-broker:DS413 root] Connected to broker: mqtts://ds413.local:8883
```
**[mqtt-broker:DS413 root] Connected to broker: mqtts://ds413.local:8883**

I can send and recieve test messages over MQTT in Node-RED also.

## Actual behavior

The Hass.IO Node-RED addon does not connect to the exact same MQTT server with the exact same settings the MQTT options in Node-RED, I copy/pasted the working flow and used the same credentials. Log:

```
# HASSIO LOG #
3 Nov 01:02:10 - [info] Node-RED version: v0.19.5
3 Nov 01:02:10 - [info] Node.js  version: v8.12.0
3 Nov 01:02:10 - [info] Linux 4.14.78-v7 arm LE
3 Nov 01:02:11 - [info] Loading palette nodes
3 Nov 01:02:17 - [info] Settings file  : /etc/node-red/config.js
3 Nov 01:02:17 - [info] Context store  : 'default' [module=memory]
3 Nov 01:02:17 - [info] User directory : /config/node-red/
3 Nov 01:02:17 - [warn] Projects disabled : editorTheme.projects.enabled=false
3 Nov 01:02:17 - [info] Flows file     : /config/node-red/flows.json
3 Nov 01:02:17 - [info] Server now running at http://127.0.0.1:1880/
3 Nov 01:02:17 - [info] Starting flows
3 Nov 01:02:17 - [info] Started flows
3 Nov 01:02:17 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
3 Nov 01:02:43 - HA Auth - DevTesta authenticated
3 Nov 01:02:47 - [info] [mqtt-broker:DS413 root] Connection failed to broker: mqtts://ds413.local:8883
```

**[mqtt-broker:DS413 root] Connection failed to broker: mqtts://ds413.local:8883**

It looks like it doesn't even try and connect to my broker, I checked the `mosquitto` logfile on `ds413.local` and it doesn't even log a connection attempt from my `hassio.local` IP address.

## Steps to reproduce

Try and connect to a MQTT host over Lan, maybe it's because I'm using TLS? I'll try another MQTT server without encryption or a public test server.

EDIT: I tried using MQTT server `test.mosquitto.org:1883` wired up to a debug node, topic = "+" and it works great, it produces a lot of test messages, so it seems to be a issues with MQTT over LAN only.

## Proposed changes

I'm not sure yet, I don't have a solution yet. I'm guessing it's a network issue, or maybe mDNS? What steps can I do to debug? Thanks

EDIT: My HASS.IO info: 

Hostname | hassio
-- | --
System | HassOS 1.12
Deployment | production

**Comment by frenck** [comment]
Looks like it cannot resolve `ds413.local`, could you please try the IP address instead?

**Comment by DeviousPenguin** [comment]
Hi, I've just tried to connect using the IP address, and I can see in the MQTT broker log that it tries to connect, but the authentication on the MQTT broker fails. It's a self signed cert that only allows connections to hostname `ds413.local`, so really connecting to the IP address won't work in this case.

After a little more tinkering, it does seem to be a mDNS issue, it can't resolve `ds413.local`:

```
# Raspbian on LAN
$ ping ds413.local -c1
PING ds413.local (192.168.1.187) 56(84) bytes of data.
64 bytes from 192.168.1.187: icmp_seq=1 ttl=64 time=0.414 ms
--- ds413.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.414/0.414/0.414/0.000 ms

# Node-Red Docker Image
$ docker exec addon_a0d7b954_nodered ping 192.168.1.187 -c1
PING 192.168.1.187 (192.168.1.187): 56 data bytes
64 bytes from 192.168.1.187: seq=0 ttl=64 time=0.550 ms
--- 192.168.1.187 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.550/0.550/0.550 ms

# Node-Red Docker Image
$ docker exec addon_a0d7b954_nodered ping ds413.local -c1
PING ds413.local (92.242.132.16): 56 data bytes
--- ds413.local ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
```

It looks like it's trying to connect to `ds413.local` over the internet as my lan is only 192.168.x.x addresses. I am able to resolve the hostname in hass.io so it seems my network is working ok:

```
# Hass.IO
/bin/avahi-resolve-host-name ds413.local
ds413.local	192.168.1.187
```

Now while I could disable encryption on my broker in order to connect from Node-RED there other things in my Node-RED flow that require mDNS hostname resolution so I'd rather fix the mDNS name resolution if possible.

**Comment by frenck** [comment]
that is (unfortunately) outside the scope of the add-on.
The network is provided by Hass.io.

**Comment by DeviousPenguin** [comment]
Ok, thanks this does seem to be more of a Hass.IO issue, after more testing even the `homeassistant` container has the same nDNS issue.
Thanks for pointing me in the right direction, hopefully with a little tinkering of Hass.IO I should be able to fix or workaround this issue.
