### ISSUE TITLE
Error installing arduino nodes

### ISSUE THREAD

**Issue by mikimpek** [hassio-addons/addon-node-red#722]
# Problem

[15:48:28] INFO: Starting installation of custom NPM/Node-RED packages...

> @serialport/bindings@8.0.8 install /opt/node_modules/firmata/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.18.4 runtime=node arch=x64 libc=musl platform=linux)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 4.15.0-118-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/firmata/node_modules/@serialport/bindings
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@8.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-14T13_49_07_604Z-debug.log
[15:49:07] FATAL: Failed to install a specified npm package
[cont-init.d] user.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
------------------------------------------------------

**Comment by sinclairpaul** [comment]
> gyp ERR! stack Error: not found: make

Please look at some of the closed issues (you will find several similar ones), you are missing the dependencies required for building the node in the System Packages option.

**Comment by mikimpek** [comment]
> > gyp ERR! stack Error: not found: make
> 
> Please look at some of the closed issues (you will find several similar ones), you are missing the dependencies required for building the node in the System Packages option.

Hi sinclairpaul ,

I added packages like shown below, now worked like a charm. Thanks

system_packages:
  - make
  - g++
  - linux-headers

**Comment by alex88** [comment]
@mikimpek did it work out of the box? I can't seem to find the serial interface (connected via USB)

**Comment by frenck** [comment]
This is an old and closed issue @alex88. Please don't dig up old stuff. Thanks 👍
