### ISSUE TITLE
[error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>

### ISSUE THREAD

**Issue by tomcatGu** [hassio-addons/addon-node-red#73]
Node Red Add on log:
[error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>

Home assitant error log as follows
18-11-01 04:02:59 WARNING (MainThread) [hassio.api.proxy] Unknown Home Assistant API access!

How to resolve this Please help
Using Hassio on Raspberr y pi 3b+
Node red hassio addon version 1.0.1
Node Red Pallet manager version say v0.19.5
Hassio Version 0.81.5

**Comment by frenck** [comment]
Please upgrade to v1.2.0, which should take care of conflicts.
