### ISSUE TITLE
Give NodeRED attribution in the logbook instead of "triggered by Hass.io"

### ISSUE THREAD

**Issue by jschwalbe** [hassio-addons/addon-node-red#732]
# Problem/Motivation

I was tracking down why some lights turned off without my expectation to do so. The logbook said the lights were turned off `by Hass.io`.

## Steps to reproduce

Trigger something via the call service node. Look in the logbook. `by Hass.io`

## Proposed changes

Since the logbook is now doing such a great job of showing why something happened, I propose that the logbook start to say "triggered by NodeRED add-on", or even more detail "triggered by the Patio Rules tab NodeRED add-on".

**Comment by sinclairpaul** [comment]
At a guess there is a generic entry for anything that calls the API.  This would likely need a change in HA itself, and then in the HA Node Palette.

Either way, sorry there isn't anything that can be done at the addon level.
