### ISSUE TITLE
LoadNodeRedFlowsOnStartup option / button

### ISSUE THREAD

**Issue by xvolte** [hassio-addons/addon-node-red#734]
# Problem/Motivation
> (Why the issue was filed)

I ended up myself almost locking me out of my HomeAssistant - i did code a WRONG Nodered flow, that used 100% of the CPU thus the Home Assistant website was unresponsive.
The only solution i found was to reboot the Raspberry, wait for it to boot homeassistant website and then rushed to the supervisor to disable completely the whole "NodeRed" module autostart... which then gave me some time to remove the wrong code on the system, by hand ...

If there would be such LoadNodeRedFlowsOnStartup button, we could still have the time to launch Nodered interface and make modifications within the flows - as the flows could be EDITABLE but would not be in use yet (not loaded).

## Expected behavior
> (What you expected to happen)

To have a button to disable the loading of the flows to be executed by nodered.
Would love to still have the editor loaded, to be able to make modifications

## Actual behavior
> (What actually happened)

Nodered stuck at 100% CPU capacity.
Locked myself out - raspberry was unresponsive
Only solution is to rush on startup before the Nodered service is loaded and then reboot again...

## Steps to reproduce
> (How can someone else make/see it happen)

make a wrong Nodered flow that uses 100% cpu ... get yourself locked out as Raspberry is unresponsive... only solution is to shutdown power...

## Proposed changes
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

If there would be such LoadNodeRedFlowsOnStartup button, we could still have the time to launch Nodered interface and make modifications within the flows - as the flows could be EDITABLE but would not be in use yet (not loaded).

**Comment by frenck** [comment]
Add-ons wrap existing applications, in this case, Node-RED and a couple of pallets.

If you like new features to those applications, you'll need to file feature requests with those apps. From an add-on perspective, we do not modify the application on such a level.
