### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by pragmantic** [hassio-addons/addon-node-red#741]
# Problem/Motivation

fresh install, multiple installs   no luck   502: Bad Gateway  web UI

log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 7.2.7
 You are running the latest version of this add-on.
 System: Ubuntu 20.04.1 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 0.117.1
 Home Assistant Supervisor: 2020.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[06:58:47] FATAL: 
[06:58:47] FATAL: SSL has been enabled using the 'ssl' option,
[06:58:47] FATAL: this requires a SSL certificate file which is
[06:58:47] FATAL: configured using the 'certfile' option in the
[06:58:47] FATAL: add-on configuration.
[06:58:47] FATAL: 
[06:58:47] FATAL: Unfortunately, the file specified in the
[06:58:47] FATAL: 'certfile' option does not exists.
[06:58:47] FATAL: 
[06:58:47] FATAL: Please ensure the certificate file exists and
[06:58:47] FATAL: is placed in the '/ssl/' directory.
[06:58:47] FATAL: 
[06:58:47] FATAL: In case you don't have SSL yet, consider getting
[06:58:47] FATAL: a SSL certificate or setting the 'ssl' option
[06:58:47] FATAL: to 'false' in case you are not planning on using
[06:58:47] FATAL: SSL with this add-on.
[06:58:47] FATAL: 
[06:58:47] FATAL: Check the add-on manual for more information.
[06:58:47] FATAL: 
[cont-init.d] nginx.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by pragmantic** [comment]
config....

credential_secret: password
dark_mode: false
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: true
system_packages: []
npm_packages: []
init_commands: []

**Comment by frenck** [comment]
The problem is describe in the error message.

**Comment by will2568** [comment]
The problem is described in the error message but the solution is not. Duh.

**Comment by frenck** [comment]
The solution is described there as well. 

```
[06:58:47] FATAL: Please ensure the certificate file exists and
[06:58:47] FATAL: is placed in the '/ssl/' directory.
[06:58:47] FATAL:
[06:58:47] FATAL: In case you don't have SSL yet, consider getting
[06:58:47] FATAL: a SSL certificate or setting the 'ssl' option
[06:58:47] FATAL: to 'false' in case you are not planning on using
[06:58:47] FATAL: SSL with this add-on.
```

Reading helps.

**Comment by will2568** [comment]
That's not a solution. A solution would have step by step instructions for
fixing the problem.

**Comment by frenck** [comment]
That is a solution. If that doesn't speak to you, running this system, might not be for you.

**Comment by will2568** [comment]
It's not any solution that would work for me. Step by step instructions,
just like you'd find in a manual for something off the shelf is what I call
a solution. Just because this is an open source project that doesn't mean
you get to be lazy when it comes to writing documentation.

**Comment by frenck** [comment]
It literally says: If you do not have SSL yet, consider setting the `ssl` option to false. How on earth is that not a concrete instruction?

For the record, that message has been added based on feedback in the past.

Calling me straight out lazy I find rather offending. Please, don't come here again. Thanks.

**Comment by will2568** [comment]
Where do I find that option? How do I change it? There's a lot missing from
those instructions.

**Comment by frenck** [comment]
See add-on documentation.

**Comment by will2568** [comment]
What documentation? You don't know how to write. my neighbor's 3-year-old
could do a better job of writing than you.

**Comment by frenck** [comment]
Seriously? You cannot see the documentation link in this repository? The documentation tabs in side Home Assistant that are shipped with each add-on?

You bought yourself a ban because of that last comment.
