### ISSUE TITLE
node-red-contrib-msg-queue

### ISSUE THREAD

**Issue by firestrife23** [hassio-addons/addon-node-red#75]
# Problem/Motivation

How do I set the path to SQLite DB file?

## Expected behavior

N/A

## Actual behavior

N/A

## Steps to reproduce

* Install _node-red-contrib-msg-queue_ pallete

> For more information on this pallete:
> https://flows.nodered.org/node/node-red-contrib-msg-queue

## Proposed changes

I'm not not familiar with hassio addons file system structure, would like to see better support for local files, and update Node-RED addons wiki on how-to set the path to local files for certain Node-RED palettes.

**Comment by frenck** [comment]
Not sure about your question, it is documented in link you gave: 

https://flows.nodered.org/node/node-red-contrib-msg-queue
