### ISSUE TITLE
node-red-contrib-cast - "Not able to get media file via google-tts:get key failed from google"

### ISSUE THREAD

**Issue by firestrife23** [hassio-addons/addon-node-red#751]
# Problem/Motivation

node-red-contrib-cast is not working as intend

## Expected behavior

casting text to speech message to Google Mini

## Actual behavior

error message: `"Not able to get media file via google-tts:get key failed from google"`

## Proposed changes

fixed by adding dependencies to packages.json

`"google-tts-api": "0.0.4"`

**Comment by frenck** [comment]
Please report your issue with `node-red-contrib-cast`. Thanks 👍
