### ISSUE TITLE
Node-Red disappears when resizing the browser window

### ISSUE THREAD

**Issue by fabsenet** [hassio-addons/addon-node-red#754]
![bugreport](https://user-images.githubusercontent.com/2065705/98927419-cca78a80-24d8-11eb-82dc-8f5515d1c21d.gif)

The gif is on `firefox developer edition 83.0b10 (64-Bit)`
I also veriefied the issue on `chrome Version 86.0.4240.198 (Offizieller Build) (64-Bit)` and on `edge Version 86.0.622.63 (Offizielles Build) (64-Bit)`

My expectation would be to not loosing access to the node-red part of the window. it is also very frustrating because you can loose not deployed changes that way!

**Comment by fabsenet** [comment]
vscode has the same issue! my other sidebar tabs work without that issue.

**Comment by fabsenet** [comment]
also all other versions:
HassOS 4.16
Supervisor 2020.11.0
Browsers were running on Windows 10, Version 2004, Build 19041.610

**Comment by sinclairpaul** [comment]
Only appears to happen when using the "Show in Sidebar" option, and only when the Sidebar is collapsed.

However this will be a UI issue, please log it with the Home Assistant frontend repo.
