### ISSUE TITLE
Error when connecting to entities on server via websockets

### ISSUE THREAD

**Issue by squeakus** [hassio-addons/addon-node-red#755]
# Problem/Motivation
Error after installing nodered addon. It is working with all of my existing nodes but if I add a HA node I get the following error:
![error](https://user-images.githubusercontent.com/167925/99193694-82d9d100-2772-11eb-95c2-cea16b03021e.png)

I have definitely deployed the server but the %25%25ID%25%25 probably means I have misconfigured something incorrectly.
I am still trying to get my head around HA but I think it is in the same docker image. I can see the config files if I ssh onto the machine.

I set it up with ssl turned off.

> (Why the issue was filed)
Cannot set up the HA integration
## Expected behavior
Show a list of entities
> (What you expected to happen)

## Actual behavior
Get the error message above
> (What actually happened)

## Steps to reproduce
> (How can someone else make/see it happen)
Clean install of Home Assistant 0.117.6 and install latest node-red addon

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 4.16
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Dublin
version | 0.117.6
virtualenv | false

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The addon installs Node-Red and comes preconfigured with the HA palette.  As it is running unfortunately there is not much else that can be added here.

This looks from a glance to be the node that is dependent on the Custom Component, https://github.com/zachowj/hass-node-red

**Comment by squeakus** [comment]
Thanks for the prompt reply! The problem seems to be the pre-configured HA palette. I tried installing the addon in the ticket listed but it is still having the same issue.

Basically I am running this out of the box and installing the node-red addon but whenever I use anything in the HA palette it throws an error. Looking at the nodered log it is making the following calls:

[16/Nov/2020:18:06:35 +0000] 400 -(192.168.1.197) GET /homeassistant/%%ID%%/entities HTTP/1.1 (-)
[16/Nov/2020:18:06:35 +0000] 400 -(192.168.1.197) GET /homeassistant/%%ID%%/entities HTTP/1.1 (-)
[16/Nov/2020:18:06:35 +0000] 400 -(192.168.1.197) GET /homeassistant/%%ID%%/version?_=1605549995933 HTTP/1.1 (-)
[16/Nov/2020:18:06:35 +0000] 400 -(192.168.1.197) GET /homeassistant/%%ID%%/entities HTTP/1.1 (-)
[16/Nov/2020:18:06:35 +0000] 400 -(192.168.1.197) GET /homeassistant/%%ID%%/version?_=1605549995977 HTTP/1.1 (-)

and these are throwing the error. Shouldn't %%ID%%/ be populated with something? or is this get request correctly formed?
