### ISSUE TITLE
I want to disable pwned in initialization. What I do. 

### ISSUE THREAD

**Issue by educastellini** [hassio-addons/addon-node-red#76]
I want to use the this add-on and others with a same user name and password I use in the all add-ons I have.

What I do to disable pwned check in the initializing off add-ons.

I try use the option in the end of config but dont works, and the add-on initialization stops.

My config:

{
  "log_level": "info",
  "credential_secret": "xxxxxxxxx",
  "http_node": {
    "username": "xxxxxxxx",
    "password": "xxxxxxxx"
  },
  "http_static": {
    "username": "xxxxxxxxx",
    "password": "xxxxxxxxx"
  },
  "port": 1880,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": false,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": [],
  "i_like_to_be_pwned": false,
  "leave_front_door_open": true
}

The initialization PWNED error:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED v1.1.0
 Flow-based programming for the Internet of Things
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 aarch64 / HassOS 2.3 / HA 0.82.1 / SU 140 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
WARNING: Password is in the Have I Been Pwned database!
WARNING: Password appeared 9323 times!
FATAL: Please choose a different http_node password, this one is unsafe!
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

Some clue to help me here...?

**Comment by tmcarr** [comment]
This feature is intended to protect you and it is not advisable to disable it. If that password is in the HaveIBeenPwned database, it is now part of a list of passwords that malicious scripts across the internet will try against your addons. 

The real solution here is to change your password on all of the addons and choose something very complex, ideally with a password manager like 1Password, Lastpass, or KeePassX....

**Comment by tjorim** [comment]
@tmcarr is right. Yet, if you really want to disable it, read the documentation again, like I commented on your issue with the SSH add-on as well: https://github.com/hassio-addons/addon-node-red/blob/master/README.md#option-i_like_to_be_pwned

**Comment by educastellini** [comment]
I know for what this is, bus if don't see I put the two options of pwned to off the check but the check continues and break the initialization on add-on.

in the and of config I put:
"i_like_to_be_pwned": false,
"leave_front_door_open": true

And don't work for disable the pwned check, but the don't work. 

},
"port": 1880,
"ssl": false,
"certfile": "fullchain.pem",
"keyfile": "privkey.pem",
"require_ssl": false,
"system_packages": [],
"npm_packages": [],
"init_commands": [],
```
"i_like_to_be_pwned": false,
"leave_front_door_open": true
```
}

-I have the same problem in SSH & Web Terminal and in Node-Red.
-Any idea what I do realy in config to disable the pwned...?

**Comment by tjorim** [comment]
Again, it's in the documentation, read it once more:
> Adding this option to the add-on configuration allows to you bypass the HaveIBeenPwned password requirement by setting it to true.

Once more but I'll highlight some stuff:
> Adding this option to the add-on configuration **_allows to you bypass_** the HaveIBeenPwned password requirement **_by setting it to true_**.

**Comment by educastellini** [comment]
-Thank you I config the inverse in the option.
-Ok thank you Sr....!!!
