### ISSUE TITLE
Node-red addon not starting after update to 7.2.9

### ISSUE THREAD

**Issue by newlund** [hassio-addons/addon-node-red#764]
Updated Node-red addon from 7.2.8 to 7.2.9
Now the addon refuse to start.

Log:
```
----------------------------------------------------------------------
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 7.2.9
 You are running the latest version of this add-on.
 System: HassOS 4.16  (amd64 / qemux86-64)
 Home Assistant Core: 0.117.6
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 FAILED at 531.
1 out of 1 hunk FAILED -- saving rejects to file nodes/ui_base.html.rej
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by pjmaenh** [comment]
Same issue here! Is there an easy way to downgrade the plugin until this is fixed?

**Comment by newlund** [comment]
> Same issue here! Is there an easy way to downgrade the plugin until this is fixed?

Restore snapshot. That's what I did

**Comment by sanderlv** [comment]
HELP! Me too. Now in progress of restoring from last VMware snaphot (I luckily take every hour).

**Comment by CrallH** [comment]
Same issue here:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 7.2.9
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.5 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 0.117.6
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
[11:00:59] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[11:01:00] INFO: Password is NOT in the Have I Been Pwned database! Nice!
patching file nodes/ui_base.html
Hunk #1 FAILED at 531.
1 out of 1 hunk FAILED -- saving rejects to file nodes/ui_base.html.rej
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
`

**Comment by frenck** [comment]
The issue has been located, fix made. Awaiting development builds now...

**Comment by sanderlv** [comment]
Frenck, how should 7.2.10 appear? I have restored, restarted and restarted supervisor.... but still only show update to 7.2.9

**Comment by newlund** [comment]
Thanks! Working fine now. Thank you for quick fix 👍 :)

**Comment by frenck** [comment]
@sanderlv See my message above, it contains that instruction...

**Comment by newlund** [comment]
@frenck Quick question. Should we update palettes through Node-Red or let the plugin handle that?
Ex. node-red-contrib-home-assistant-websocket ?

**Comment by sanderlv** [comment]
> 
> 
> @sanderlv See my message above, it contains that instruction...

Must be me... but cant find what you mean

**Comment by newlund** [comment]
> > @sanderlv See my message above, it contains that instruction...
> 
> Must be me... but cant find what you mean

"If you don't see the upgrade yet, please reload/refresh the add-on store. Go to the add-on store, click on the 3 dots menu in the top left and reload it. Next, refresh/reload your browser page and the upgrade should show up immediately."

**Comment by sanderlv** [comment]
Yes that works! Anyone did the update to 7.9.10 and succesful?

**Comment by newlund** [comment]
> Yes that works! Anyone did the update to 7.9.10 and succesful?

Yes, it is working fine now
