### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by will2568** [hassio-addons/addon-node-red#773]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is an empty issue. Please fill out the issue template when creating an issue.

**Comment by will2568** [comment]
I'm a newbie. I don't know how to answer those questions.

**Comment by frenck** [comment]
Those are non-technical questions. I'm sorry but I cannot help you without information.

**Comment by will2568** [comment]
How can I give you information if I don't know where to find it? Duh. I
told you I'm a newbie.

**Comment by frenck** [comment]
And I don't have a crystal ball.
