### ISSUE TITLE
Output on Connect do not work after restart of HA

### ISSUE THREAD

**Issue by RestOp** [hassio-addons/addon-node-red#774]
# Problem/Motivation, Expected behavior, Actual behavior, Steps to reproduce

I used Event Node with any input boolean to detect that HA or Node-Red or both were restarted
![image](https://user-images.githubusercontent.com/46259141/99878339-f19cab80-2c04-11eb-9813-953c76c4dd83.png)
![image](https://user-images.githubusercontent.com/46259141/99878369-29a3ee80-2c05-11eb-9188-b5c4aa0647a7.png)
on connect i get message, send me a telegram and make a lot of actions after restart.
I know for sure that it works till 114 HA and this NR (currently i have working raspberry with this version and it works there)
![image](https://user-images.githubusercontent.com/46259141/99878385-49d3ad80-2c05-11eb-8966-00691627b8bb.png)

Now i made new install HA 118 and NR  7.2.10 on new Rapsberry and it do not work. 
It works only if i make FULL Deloy. On restart i get yellow CONNECTING and then RUNNING with no further message
![image](https://user-images.githubusercontent.com/46259141/99878426-87d0d180-2c05-11eb-9dad-627ce1cf995d.png)

Code
`[{"id":"6580c804.984c68","type":"server-state-changed","z":"93133afd.ad6e88","name":"Fake Node","server":"f39df34a.e72b7","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"input_boolean.fake","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":false,"for":"","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":1180,"y":1000,"wires":[[]]},{"id":"f39df34a.e72b7","type":"server","name":"Home Assistant Websocket","legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]`

Thanks a lot!

**Comment by frenck** [comment]
form an add-on perceive, there is nothing I can do about that. Please report these types of issues upstream (e.g., with the nodes used).

**Comment by RestOp** [comment]
> Please report these types of issues upstream (e.g., with the nodes used).

Could you please give me a link where i should report it?

**Comment by RestOp** [comment]
> PS: You might just want to use the homeassistant_started event?

I think it will not help if i restart NR it will not work (because at this time HA will be already started)
