### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by nasked** [hassio-addons/addon-node-red#78]
# Problem/Motivation

> Login Fail

## Expected behavior

> Access program

## Actual behavior

> Password seems rejected

I saved config equal example but login fail.

{
  "log_level": "info",
  "credential_secret": "KJHhfdhiFRENCKfsdfdsDHFHDJS",
  "http_node": {
    "username": "MarryPoppins",
    "password": "Supercalifragilisticexpialidocious"
  },
  "http_static": {
    "username": "MarryPoppins",
    "password": "Supercalifragilisticexpialidocious"
  },
  "port": 1880,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": false,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": []
}

And my log has not errors...

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED v1.1.0
 Flow-based programming for the Internet of Things
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.12 / HA 0.82.0 / SU 140 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
INFO: Password is NOT in the Have I Been Pwned database! Nice!
INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-config.sh: executing... 
[cont-init.d] 20-config.sh: exited 0.
[cont-init.d] 80-system-packages.sh: executing... 
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-npm-packages.sh: executing... 
[cont-init.d] 81-npm-packages.sh: exited 0.
[cont-init.d] 82-user-scripts.sh: executing... 
[cont-init.d] 82-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
25 Nov 19:58:30 - [info] 
Welcome to Node-RED
===================
25 Nov 19:58:30 - [info] Node-RED version: v0.19.5
25 Nov 19:58:30 - [info] Node.js  version: v8.12.0
25 Nov 19:58:30 - [info] Linux 4.14.78-v7 arm LE
25 Nov 19:58:32 - [info] Loading palette nodes
25 Nov 19:58:42 - [info] Settings file  : /etc/node-red/config.js
25 Nov 19:58:42 - [info] Context store  : 'default' [module=memory]
25 Nov 19:58:42 - [info] User directory : /config/node-red/
25 Nov 19:58:42 - [warn] Projects disabled : editorTheme.projects.enabled=false
25 Nov 19:58:42 - [info] Flows file     : /config/node-red/flows.json
25 Nov 19:58:42 - [info] Server now running at http://127.0.0.1:1880/
25 Nov 19:58:42 - [info] Starting flows
25 Nov 19:58:42 - [info] Started flows
25 Nov 19:58:42 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
25 Nov 19:59:03 - HA Auth - Failed to authenticate: MarryPoppins
25 Nov 19:59:17 - HA Auth - Failed to authenticate: MarryPoppins

I know there are friend with the same login problem...thanks in advance...

**Comment by frenck** [comment]
You need to log in with your HA credentials....
