### ISSUE TITLE
Cannot reinstall node-red or delete "config/nod-red" folder

### ISSUE THREAD

**Issue by schivuku** [hassio-addons/addon-node-red#79]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
If you do not take the time to fill in the blanks and provide a proper issue, I'm not going to take the time to look at it.

Closing issue.
