### ISSUE TITLE
Possible error with path copy and use of the change node

### ISSUE THREAD

**Issue by hvddrift** [hassio-addons/addon-node-red#8]
# I am using the debug node and selecting copy path. It does not copy the entire path.

> (Why the issue was filed)
Attempting to use the change node with paths and I noticed the copy does not select the payload section. 

## Expected behavior
Set the value to the new value.

## Actual behavior

Example:

What I expected to copy: payload.data.old_state.attributes.latitude

What actually copies: data.old_state.attributes.latitude

## Steps to reproduce

When I enter in the paths in the change node, I do not get the expected results.

**Comment by frenck** [comment]
Hi @hvddrift, this sounds like a Node-RED issue (as in, the software itself).
This is add-on is just simply wrapping Node-RED. I would strongly advise you to create an issue on the upstream Node-RED project or maybe try to find help in the community forum and/or the Discord chat.

I'm closing this issue, but feel free to re-open in case you disagree.
