### ISSUE TITLE
Login fails for HomeAssistant passwords containing "å" and " "

### ISSUE THREAD

**Issue by johan** [hassio-addons/addon-node-red#80]
# Problem/Motivation

> I expect any legal Home Assistant user / password to work for logging into Node-RED too.

## Expected behavior

> Logging in to Node-RED with my former Home Assistant password `Hå och hej!` should work.

## Actual behavior

> Attempting to log in to Node-RED with my username and above password always fails.

## Steps to reproduce

> 1. Create a Home Assistant user / password combination `frej` / `Hå och hej!`
> 2. Attempt to log in to Node-RED with those credentials.

## Proposed changes

> Based on a quick look at your form encoding and http traffic in Chrome DevTools, you seem to send `Hå och hej!` form-url-encoded as `H%C3%83%C2%A5+och+hej!` (or something like that – I seem to recall URL encoded UTF-8, and spaces turned plus signs, like back in the nineties), and then presumably not repackage that into proper Unicode JSON for the HomeAssistant endpoint, which I think expects plain `application/json` input. Maybe you can have your form use the same encoding setup that Home Assistant uses and then just pass on what you get their way, and save on conversion bugs.

> (I managed to bypass the bug by setting a bug-evading US-ASCII password instead, but it took me many days to figure out how Node-RED password setup works, as it plain didn't, no matter what I put in its configuration.)

**Comment by johan** [comment]
This issue was encountered with Node-RED v0.19.5, Home Assistant v0.82.1, and Hass.io Add-on: Node-RED v1.1.0. Its 00-banner start message cites additional version details `armhf / HassOS 1.12 / HA 0.82.0 / SU 140 / stable`.

**Comment by Gronsak** [comment]
Ran into the same problem but due to the username I use for my Hassio login using an ö, would be nice for the forms to be encoded the same if it's gonna use the same system to login

**Comment by Gronsak** [comment]
On a related note this doesn't seem to trow any errors anywhere so quite hard to pin down what's wrong if you're not guessing

**Comment by frenck** [comment]
I've looked into this, but as far as I can see, this is an issue with Node-RED itself.

**Comment by Jpsy** [comment]
Same problem here.
After digging through all the "node red login failed" hits in Google, I finally found that the problem was caused by the character "€" in my HA password. For the time being I will try to leave some notes in the threads that come up on top of the google search about that topic. So others don't try all the good tips give there without any chance of success.

**Comment by Jpsy** [comment]
Frenck, I think we could spare some human life time if we would leave a short notice about this special character problem in the README.md of the add-on (https://github.com/hassio-addons/addon-node-red/blob/master/README.md). If you want me to do that I would be happy to create a commit and merge request. 
If I got it right the username/passwords in http_node and http_static are now obsolete, so I would mention that too in the readme, if I create a commit.

**Comment by johan** [comment]
I'd second @Jpsy's suggestion of noting in the README what subset of node-red password characters  will work with the home assistant node-red plugin. A fair guess is a-z, A-Z, 0-9, and maybe some basic US-ASCII punctuation characters.
