### ISSUE TITLE
Possibility to use the flowFilePretty option?

### ISSUE THREAD

**Issue by jlo88** [hassio-addons/addon-node-red#804]
# Problem/Motivation
Not really an issue but more a feature request. I'm struggling with version control of my flows everything is on one line and committing with git is possible but not very insightful. I've read about the `flowFilePretty` option but cannot find it in settings.js which tells me it is controlled by the add-on. Is there any way to make this setting available? I tried setting it in the add-on config but this had no effect. 

## Expected behavior
N/A

## Actual behavior
N/A

## Steps to reproduce
N/A

## Proposed changes
Exposing the `flowFilePretty` option in the add-on config to allow for easier commits.

**Comment by frenck** [comment]
its in `/config/node-red/` You can customize it to your liking.

**Comment by jlo88** [comment]
I just wanted to add for other people that are looking for this that using the following in `config/node-red/settings.js` indeed allows for better formatting: 

```
module.exports = {
    // To enabled pretty-printing of the flow within the flow file, set the following
    //  property to true:
    flowFilePretty: true,
```

I was a bit confused because I couldn't find the commented out variable and didn't know where to put it in the settings file. But I found an example settings file which showed this.
