### ISSUE TITLE
Failed to install addon // Unknown error, see supervisor

### ISSUE THREAD

**Issue by alfonsofiore** [hassio-addons/addon-node-red#805]
# Problem/Motivation

I just installed Home Assistant 0.118.5 and I want to install Node-RED from Supervisor but I keep getting this error even after restarting Home Assistant.

## Expected behavior

From Supervisor I can install Node-RED

## Actual behavior

Installation keeps failing with the same message: Failed to install addon // Unknown error, see supervisor

## Steps to reproduce

I am using a fresh docker install following this instructions on an Intel based Linux home Node-REDserver:
https://www.jamestucker.me/post/install-home-assistant-on-ubuntu-server-20-04/

**Comment by tjorim** [comment]
Check the supervisor logs, should tell you more. Furthermore, Home Assistant supervised is not supported on Ubuntu.

**Comment by frenck** [comment]
Ubuntu is not supported by the Home Assistant project.

**Comment by alfonsofiore** [comment]
Thanks for the clarification - for others who might encounter the same issue:

1st: check logs: 
go to Supervisor -> System
and then scroll to the bottom
in my case the log reveals "WARNING (MainThread) [supervisor.jobs] 'AddonManager.install' blocked from execution, system is not healthy"

then go to Supervisor -> System
That should show you 3 widgets at the top: 
Supervisor
Host System
System Metrics

Under Supervisor you will find:

Your installation is running in an unhealthy state. Learn more

There you can find the problem - for me it was "Supervisor is not privileged":
https://www.home-assistant.io/more-info/unsupported/privileged

I'll see if I can fix this problem in Ubuntu

**Comment by alfonsofiore** [comment]
check your /usr/sbin/hassio-supervisor
if you can find "--privileged" then you simply have to reboot your computer and restart Home Assistant to start it in privileged mode - it worked for me!
