### ISSUE TITLE
 npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained

### ISSUE THREAD

**Issue by dragonfly69** [hassio-addons/addon-node-red#823]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by dragonfly69** [comment]
Try to play with node red in Hassio but can't add some nodes due to core-js version /// required is v_3 - current 2.6.12

**Comment by frenck** [comment]
That can happen, not sure what you want me to do about that from an add-on perspective?
