### ISSUE TITLE
PANIC: unprotected error in call to Lua API (bad light userdata pointer)

### ISSUE THREAD

**Issue by DunklerPhoenix** [hassio-addons/addon-node-red#824]
# Problem/Motivation

Heho. I'm sorry for opening such an issue again, but i think that my comment is lost in the other issue.
https://github.com/hassio-addons/addon-node-red/issues/816#issuecomment-748678373

## Expected behavior

> Accessable Webinterface

## Actual behavior

> Webinterface is not accessable

## Steps to reproduce

Get an HA Blue
Install Node Red via Supervisor
See start fail

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 7.2.11
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.8  (aarch64 / odroid-n2)
 Home Assistant Core: 2020.12.1
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1156 (offset 625 lines).
up to date in 1.294s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:16:39] INFO: Starting Node-RED...
> addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
20 Dec 23:16:41 - [info] 
Welcome to Node-RED
===================
20 Dec 23:16:41 - [info] Node-RED version: v1.2.5
20 Dec 23:16:41 - [info] Node.js  version: v12.18.4
20 Dec 23:16:41 - [info] Linux 5.9.14 arm64 LE
20 Dec 23:16:42 - [info] Loading palette nodes
20 Dec 23:16:44 - [warn] [RED.events] Deprecated use of "nodes-started" event from "/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:615:14". Use "flows:started" instead.
20 Dec 23:16:45 - [info] Dashboard version 2.24.0 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
20 Dec 23:16:45 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
20 Dec 23:16:46 - [info] Settings file  : /etc/node-red/config.js
20 Dec 23:16:46 - [info] Context store  : 'default' [module=memory]
20 Dec 23:16:46 - [info] User directory : /config/node-red/
20 Dec 23:16:46 - [warn] Projects disabled : editorTheme.projects.enabled=false
20 Dec 23:16:46 - [info] Flows file     : /config/node-red/flows.json
20 Dec 23:16:46 - [info] Starting flows
20 Dec 23:16:46 - [info] Started flows
20 Dec 23:16:46 - [info] Server now running at http://127.0.0.1:46836/
[23:16:46] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
20 Dec 23:16:51 - [info] [server:Home Assistant] Connecting to http://supervisor/core
20 Dec 23:16:51 - [info] [server:Home Assistant] Connected to http://supervisor/core
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
```

**Comment by ronaldheft** [comment]
I'm seeing the same thing with Home Assistant Blue. Node RED works fine through the ingress, but trying to access Node Red through an exposed port triggers this error message.

**Comment by jorgeassuncao** [comment]
I've just updated Node Red to 8.0.0 and having the same errors (Home Assistant 2021.1.4, Supervisor 2021.01.5). Everything works well via Ingress but get a "500 Internal Server Error" and erros in the log.

```
[20:08:33] INFO: Starting NGinx...
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /etc/nginx/nginx.conf:43
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2021/01/22 20:08:33 [error] 553#553: *1 lua entry thread aborted: runtime error: /usr/share/lua/common/resty/core/request.lua:124: no request found
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/share/lua/common/resty/core/request.lua:124: in function 'get_headers'
	/etc/nginx/lua/ha-auth.lua:7: in function 'authenticate'
	/etc/nginx/lua/ha-auth.lua:73: in function </etc/nginx/lua/ha-auth.lua:1>, client: 10.0.10.131, server: a0d7b954-nodered, request: "GET / HTTP/1.1", host: "10.0.10.10:1880"
[22/Jan/2021:20:08:33 +0000] 500 -(10.0.10.131) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36)
2021/01/22 20:08:34 [error] 553#553: *2 lua entry thread aborted: runtime error: /usr/share/lua/common/resty/core/request.lua:124: no request found
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/share/lua/common/resty/core/request.lua:124: in function 'get_headers'
	/etc/nginx/lua/ha-auth.lua:7: in function 'authenticate'
	/etc/nginx/lua/ha-auth.lua:73: in function </etc/nginx/lua/ha-auth.lua:1>, client: 10.0.10.131, server: a0d7b954-nodered, request: "GET /favicon.ico HTTP/1.1", host: "10.0.10.10:1880", referrer: "http://10.0.10.10:1880/"
[22/Jan/2021:20:08:34 +0000] 500 -(10.0.10.131) GET /favicon.ico HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36)
```

**Comment by ronaldheft** [comment]
Seeing the same on 8.0.0.

**Comment by frenck** [comment]
Hmm... that uh... 

Let me be this free: Sucks.

I can work around it, but it takes a bit of development and time (but would eradicate this issue forever). So please bare with me, as the workload on the repositories are high at this point.

**Comment by jorgeassuncao** [comment]
That your time @frenck and thank you for your good work!

**Comment by btsimonh** [comment]
Just installed on RPI3 std HA SD card install, and get 
23 Jan 08:56:53 - [info] Server now running at http://127.0.0.1:46836/
[08:56:53] INFO: Starting NGinx...
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /etc/nginx/nginx.conf:43
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
23 Jan 08:56:58 - [info] [server:Home Assistant] Connecting to http://supervisor/core
23 Jan 08:56:58 - [info] [server:Home Assistant] Connected to http://supervisor/core
2021/01/23 08:57:26 [error] 534#534: *2 lua entry thread aborted: runtime error: /usr/share/lua/common/resty/core/request.lua:124: no request found
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/share/lua/common/resty/core/request.lua:124: in function 'get_headers'
	/etc/nginx/lua/ha-auth.lua:7: in function 'authenticate'
	/etc/nginx/lua/ha-auth.lua:73: in function </etc/nginx/lua/ha-auth.lua:1>, client: 192.168.1.72, server: a0d7b954-nodered, request: "GET / HTTP/1.1", host: "homeassistant.lan:1880"
[23/Jan/2021:08:57:26 +0000] 500 -(192.168.1.72) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36)
2021/01/23 08:57:26 [error] 534#534: *1 lua entry thread aborted: runtime error: /usr/share/lua/common/resty/core/request.lua:124: no request found
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/share/lua/common/resty/core/request.lua:124: in function 'get_headers'
	/etc/nginx/lua/ha-auth.lua:7: in function 'authenticate'
	/etc/nginx/lua/ha-auth.lua:73: in function </etc/nginx/lua/ha-auth.lua:1>, client: 192.168.1.72, server: a0d7b954-nodered, request: "GET /favicon.ico HTTP/1.1", host: "homeassistant.lan:1880", referrer: "http://homeassistant.lan:1880/"
[23/Jan/2021:08:57:26 +0000] 500 -(192.168.1.72) GET /favicon.ico HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36)

I guess it's the same kind of issue....  and ends with access direct to 1880 giving 500 Internal Server Error.
UI access works.

**Comment by frenck** [comment]
Thanks, @btsimonh 


# ⚠️  I do not need more error logs. The issue is clear.

**Comment by btsimonh** [comment]
:).

**Comment by firestrife23** [comment]
I'm having the same issue as #862, then found this. I'm glad to see someone is working on a workaround.

**Comment by frenck** [comment]
I'm currently testing a solution (for the same issue) on the AdGuard add-on.
So the future is bright and nearby 😉
