### ISSUE TITLE
can't install node-red-contrib-face-recognition

### ISSUE THREAD

**Issue by 1003657663** [hassio-addons/addon-node-red#828]
# Problem/Motivation

I want to install node-red-contrib-face-recognition.
This node is useful for face-recognition;

# I try to run this order

apk add make
apk add g++

npm install node-red-contrib-face-recognition

# and then error

I think this system is lost something, there are something need be install , otherwise the node-red can not run any thing about Neural Networks

**Comment by bonanitech** [comment]
Add the packages you need to [system_packages](https://github.com/hassio-addons/addon-node-red/blob/master/node-red/DOCS.md#option-system_packages) in the add-on config, restart the add-on, and then install `node-red-contrib-face-recognition` using the palette manager.

**Comment by frenck** [comment]
> node-red-contrib-face-recognition using the palette manager.

One should not use the palette manager, use add-on configuration instead.


In general, this is not an add-on issue, but a user configuration error, therefore closing this issue.

**Comment by bonanitech** [comment]
Oh, right. Use the [npm_packages](https://github.com/hassio-addons/addon-node-red/blob/master/node-red/DOCS.md#option-npm_packages) option to install `node-red-contrib-face-recognition`.
