### ISSUE TITLE
Node-RED missing from the HASS add-on 

### ISSUE THREAD

**Issue by andrew-w-roberts** [hassio-addons/addon-node-red#839]
# Problem/Motivation. 
I have recently installed a new pi 4 B with HA version core 2021.1.0 with supervisor 2020.12.7. I cant find Node-RED in the HASS add-ons library.

## Expected behavior

> (What you expected to happen)
Node-RED should be available in the HASS add-ons library.

## Actual behavior

> (What actually happened)

## Steps to reproduce
The Supervisor, Add-ons and search for node-RED does not reveal anything

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by djdemer** [comment]
I am in the same situation, seems you started the journey two days before I.  I see "Use the following URL to add this repository:
https://github.com/hassio-addons/repository".  But that isn't clear to me, those instructions just seem to link me back to the same pages.  I looked into the configuration.yaml hoping for a clue about adding repositories.  So far no luck.

**Comment by djdemer** [comment]
I solved my problem...  1. In HA, go to Supervisor.  2. Go to Add-on Store.  3. Upper top right corner, click on the 3 dots.  4. Click on Repositories.  5. I attempted adding the url https://github.com/hassio-addons/repository but got errors complaining about duplicates. 6. I removed/deleted the default repository and then re-added above url.
I still received duplicate errors messages, but now under Add-on Store, I can search and install Node-RED.

**Comment by frenck** [comment]
This is outside of the scope for the add-on. Feel free to report an issue with Home Assistant. I cannot change this behavior from an add-on perspective.

**Comment by andrew-w-roberts** [comment]
@djdemer , thanks for the effor with your detailed response. Tell me though, did you remove the actual subfolder and content from the custom_repository folder? Also, once you installed the node-RED app were you able to configure it and then add it to the side-bar and open the UI?

**Comment by frenck** [comment]
This is the add-on and in no way related to any custom repository folder (what the hell that even may be).

Locking down the conversation as it is out of scope and out of place.
