### ISSUE TITLE
Output on Connect wont work after HA restart

### ISSUE THREAD

**Issue by SentryMax** [hassio-addons/addon-node-red#845]
# Problem/Motivation
Output on Connect wont work after HA restart
> (Why the issue was filed)

## Expected behavior
Output on Connect works after HA restart
> (What you expected to happen)

## Actual behavior
Output on Connect wont work after HA restart
> (What actually happened)
Output on Connect wont work after HA restart
## Steps to reproduce
Restart HA
> (How can someone else make/see it happen)

## Proposed changes
Fix Output on Connect wont work after HA restart
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
I need Output on Connect to
![2](https://user-images.githubusercontent.com/57269475/104812464-93ee9f00-5802-11eb-8cff-fb7b19ad92ee.PNG)
![1](https://user-images.githubusercontent.com/57269475/104812466-96e98f80-5802-11eb-87a6-5c0e913883c7.PNG)

 That it actually work after HA restart and not just stuck on Running which = Nothing Happens

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the Home Assistant node for Node-RED.

Please report your issue upstream, as from an add-on perspective, there is nothing I can do.

Thanks 👍

**Comment by SentryMax** [comment]
Was reported “upstream ” and nothing happened, they said that it needs the
HACS node red integration to work properly. I don’t want the HACS node red
integration. It used to work before the HACS integration. I guess “free
software ” means no responsibility ? Maybe I should pay for the Nabu Casa
in order to get support. Thanks 👍🏻

**Comment by frenck** [comment]
>  it needs the HACS node red integration to work properly

Ok, well that's clear.

> I don’t want the HACS node red integration

So, uh... yeah 🤷 

> I guess “free software ” means no responsibility ?

Depends how one defines responsibility I guess.

> Maybe I should pay for the Nabu Casa in order to get support. Thanks

None of these projects you are complaining about now are related to Home Assistant Team or Nabu Casa, I don't see how that would work.

All in all, this is an add-on. Add-ons wrap existing software, in this case, Node-RED with the available nodes online.

I don't write and/or maintain the software upstream; I cannot help you with that.
As said, the functionality of this part, comes from the upstream node. That is where your frustration should go.

👍

**Comment by SentryMax** [comment]
Ok, well that's clear.

       It’s clear that I need an integration so the add-on that you “works”
properly?

So, uh... yeah 🤷

      So, uh... yeah 🤷

Depends how one defines responsibility I guess.

a thing which one is required to do as part of a job, role, or legal
obligation.
plural noun: *responsibilities*


*None of these projects you are complaining about now are related to Home
Assistant Team *

*       Node-Red is part of Home Assistant? I understand that you don’t
like Node Red, but it’s there and you maintain it *


*That is where your frustration should go.*

*      I have no frustrations. If you don’t like your paid job maybe you
should get another one and that way you don’t get frustrated when people
ask for help**.*

*Here’s another definition for you *

*People Skills *


*the ability
<https://dictionary.cambridge.org/dictionary/english/ability> to communicate
<https://dictionary.cambridge.org/dictionary/english/communicate> with people
<https://dictionary.cambridge.org/dictionary/english/people> in a friendly
<https://dictionary.cambridge.org/dictionary/english/friendly> way
and therefore
<https://dictionary.cambridge.org/dictionary/english/therefore> deal
<https://dictionary.cambridge.org/dictionary/english/deal> with
them effectively
<https://dictionary.cambridge.org/dictionary/english/effectively>, especially
<https://dictionary.cambridge.org/dictionary/english/especially> in business
<https://dictionary.cambridge.org/dictionary/english/business>.*

👍🏻

**Comment by frenck** [comment]
> *People Skills *

You got yourself a ban. Congratulations.

**Comment by EpicLPer** [comment]
I wish I could upvote status changes.

**Comment by ToxicToast** [comment]
Sorry, just found this issue Ticket on twitter... it was an rollercoaster zu read
btw - keep up the good work and dont let yourself annoy about people like that one <3
