### ISSUE TITLE
Non-admin users can take control of Node-RED on port 1880

### ISSUE THREAD

**Issue by jant90** [hassio-addons/addon-node-red#848]
# Problem/Motivation
Regular, non-admin, HA users can take control of Node-RED by accessing it on port 1880. This is not an issue when accessing Node-RED through ingress.

## Expected behavior
When non-admin HA users access Node-RED on port 1880 and enter their credentials a HTTP 401 or 403 status code should be returned.

## Actual behavior
When non-admin HA users access Node-RED on port 1880 and enter their credentials the Node-RED dashboard loads and users can control Node-RED.

## Steps to reproduce
Enable and start the Node-RED add-on and access it on port 1880 (i.e. http://homeassistant.local:1880).
Log in with non-admin credentials.
(I run Home Assistant OS 5.10 in Hyper-V.)

## Proposed changes
Reject Node-RED access for non-admin users on port 1880 with a HTTP 401 or 403 status code.

**Comment by frenck** [comment]
This is correct and expected behavior.

As for the feature request in this issue; this cannot be done, as Home Assistant does not provide such controls.

**Comment by jant90** [comment]
Thanks for the very quick reply. Is there another way to mitigate this? I.e. block access on port 1880 for all users (so no basic auth prompt at all)? http://homeassistant.local:1880/endpoint is also accessible without basic auth so there must be some controls here (is this done through nginx's reverse proxy settings?).

Or is it possible for me to block all incoming connections on 1880 (meaning I will lose http in node functionality)?

**Comment by frenck** [comment]
you can disable port 1880 in the add-on configuration panel inside the Supervisor panel if you like.

**Comment by jant90** [comment]
Thanks, I'll do that for now :).

In case anyone else is wondering how to do this, because it's not at all clear from the GUI,  **you need to clear the port number (1880) from it's input field** (in the add-on configuration tab under network, as @frenck mentioned already) and then save and restart the add-on. I was looking for a disable checkbox or red cross or something.
![Screenshot_2021-01-19 Supervisor - Home Assistant](https://user-images.githubusercontent.com/16788798/105025450-9ee93f80-5a4d-11eb-8107-58792f85e913.png)
