### ISSUE TITLE
Missing 8.0.0 on Docker Hub

### ISSUE THREAD

**Issue by vitinhosessa** [hassio-addons/addon-node-red#860]
# Problem/Motivation

The addon is showing the notification to update for about 1 or 2 days, but hassioaddons/node-red-amd64 on Docker Hub is missing 8.0.0

## Expected behavior

Have this version on Docker Hub.

## Actual behavior

Not having this version.

## Steps to reproduce

Just open https://hub.docker.com/r/hassioaddons/node-red-amd64/tags?page=1&ordering=last_updated

## Proposed changes

It's all good, i created this just to notify. 😄

**Comment by frenck** [comment]
Maybe read the release notes...

**Comment by vitinhosessa** [comment]
How do i update? When i click `update` nothing happens.

I thought the docker version was missing, so I was unable to update.

**Comment by vitinhosessa** [comment]
I'm running Home Assistant on a Ubuntu Server VM.

**Comment by frenck** [comment]
Update as normal, there is no difference on where the images are hosted for the end-users, the manifest informs the supervisor of the download location.

**Comment by vitinhosessa** [comment]
Mine is probably broken. When i click on `update` the animation dont even appear.

I will look for some log.

**Comment by tjorim** [comment]
Check the supervisor logs, since you run HA (I assume supervised) in a Ubuntu Server VM, it is probably unhealthy.

**Comment by vitinhosessa** [comment]
You are 100% correct.

My supervisor was unhealthy. I already got it fixed.

Sorry to bother you guys. :)
