### ISSUE TITLE
Duplicate entities created and cannot delete them without editing the HTML

### ISSUE THREAD

**Issue by ab3lson** [hassio-addons/addon-node-red#868]
# Problem/Motivation

> The sensor node created a duplicate entity (same name with _2 appended to it). I went to delete both entities to make new ones and the delete button was greyed out.

## Expected behavior

> If I want to delete an entity that Node-RED created through a entity node, I should be able to do it.

## Actual behavior

> The HTML for the Delete button has the "disabled" attribute.

## Steps to reproduce

> Create a sensor in Node-RED with the entity node. Go to Configuration > Integrations > Node-RED entities and select the entity. Try to delete the entity. It should be greyed out. The entity can be deleted by removing the "disabled" attribute in the HTML and then clicking the delete button.

## Proposed changes

> Remove the disabled attribute from the delete button's HTML. I do not know how the entity was duplicated, so I can't offer much help there. This has happened to me a handful of times over the past few months.

**Comment by sinclairpaul** [comment]
Sounds like an issue with the custom integration, as the addon just wraps the software.  I would suggest seeking help at https://github.com/zachowj/hass-node-red
