### ISSUE TITLE
node-red-contrib-state-machine runtime errors (Deprecated Events)

### ISSUE THREAD

**Issue by joelmoses** [hassio-addons/addon-node-red#872]
# Problem/Motivation

The node-red component "node-red-contrib-state-machine" has not been updated in some time and has been apparently abandoned by its maintainer; it has been replaced by "node-red-contrib-persistent-fsm" which appears to be compatible to the behavior of the old component.

The older component was written prior to the availability of "flows:started" and uses an older method of flow setup that is no longer supported in NodeRED.

## Expected behavior

No warnings, no indications on flow initiation.

## Actual behavior

Debug panel display on deployment with the node in the configuration:
`"[RED.events] Deprecated use of "nodes-started" event from "/opt/node_modules/node-red-contrib-state-machine/state-machine.js:98:20". Use "flows:started" instead."`

## Steps to reproduce

1. Add a flow with the node from "node-red-contrib-state-machine" in use (an inject -> node -> debug flow is fine for this purpose.
2. Display the Debug window in the side pane.
3. Deploy.

## Proposed changes

A substitution is proposed in the following issue logged against the "node-red-contrib-state-machine" github repository: [ISSUE](https://github.com/DeanCording/node-red-contrib-state-machine/issues/9)
It suggests a config change to the addon, which does in fact function fine:

```
npm_packages:
- node-red-contrib-persistent-fsm
init_commands:
- npm un node-red-contrib-state-machine --save
```

The new module is based on the old DeanCording module, and is kept here: [node-red-contrib-persistent-fsm](https://github.com/hufftheweevil/node-red-contrib-persistent-fsm)
It does not appear that the old maintainer is improving the module anymore.

**Comment by frenck** [comment]
Nice, seems like this is a drop-in replacement.
Does one need to modify flows in order to change to this?

**Comment by joelmoses** [comment]
It seems to share the same nodename and base configuration; when I loaded it into my flow set it seemed to adopt the existing flow configuration. It certainly seemed to "drop in".

**Comment by joelmoses** [comment]
There is a bug with the "persist state" function that makes this component behave oddly with Home Assistant; when configured to "Persist state on re-deploy" it sends a copy of the state message during node.startup and doesn't wait for flows:started. 

This means that if one uses that option with a HA call-service node the message arrives before the node is ready, leading to an API error. I'm going to address this with the maintainer of the project. It also tends to bypass queue or break nodes because it executes before they register to the flow.

It does NOT, however, keep the node from functioning fine as a state machine... as long as you don't check "Persist state on re-deploy".

**Comment by frenck** [comment]
> as long as you don't check "Persist state on re-deploy".

😓 So that makes this trading a deprecation warning for a known bug 😂 

So, that makes me rather wait for making the swap.

**Comment by joelmoses** [comment]
Yeah, I'm going to work on it with him. Hang tight.

**Comment by joelmoses** [comment]
I was able to provide the maintainer a fix and sent him a pull request. I was able to verify that a simple async delay on the message works fine... I'll let you know when he replies.

**Comment by joelmoses** [comment]
The maintainer has implemented a delay option and an option to not update a persisted state at all, which solves this issue. A user can technically configure something that doesn't work with HA - but it's no longer the default.

I've tested it, and it works fine now. If you add it to an existing config where state-machine was originally, it does not enable "Persist state" but performs the same function as the prior component.

https://github.com/hufftheweevil/node-red-contrib-persistent-fsm/releases/tag/v1.1.0

**Comment by frenck** [comment]
Alright, time to get something going in that case :)

**Comment by joelmoses** [comment]
Sounds good. Just so you know, actionflows also exhibits the same deprecated function; there's a fix proposed:

https://github.com/Steveorevo/node-red-contrib-actionflows/pull/15

But it appears as if the maintainer has moved on to other things (he last responded to a pull request in August promising a new release but nothing ever appeared).

**Comment by joelmoses** [comment]
@frenck 
I was able to get the maintainer of Actionflows to accept a fix PR. I'll open a new issue on that one.
