### ISSUE TITLE
api-call-service using switch SonOff

### ISSUE THREAD

**Issue by hellresistor** [hassio-addons/addon-node-red#874]
# Problem/Motivation

I have some nodes created with a 2x pool state -> 2x template ontime/offtime -> schedex -> switch On/Off -> Many Call-Services
I have SonOff Switches (has hardware Original firmware) need On/Off on same time switching.
Randomly Call-service API error.

## Expected behavior

All Ons/Offs services after switch decision.
SonOff device have a dedicated account.
All SonOff devices response on HA Dashboard toogles correctly. (include the Header Toogle)

## Actual behavior
Getting this on log
```
28 Jan 22:15:00 - [error] [api-call-service:Fan OFF] Call-service API error.  Error Message: Cannot write to closing transport
28 Jan 22:20:00 - [error] [api-call-service:Exaust ON] Call-service API error.  Error Message: Cannot write to closing transport
28 Jan 22:20:00 - [error] [api-call-service:Fan ON] Call-service API error.  Error Message: Cannot write to closing transport
```

## Steps to reproduce

Just type the Ontime and Offtime on HomeAssistant Dashboard, when reach the pretend time will On or Off (mixing on/offs , Not all ON, not all OFF)

## Proposed changes
Starts do this issue after HA Update to last version Or NodeRed Update from 7.x.x to 8.0.0

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the Home Assistant WebSocket Node for Node-RED. Please report your issue upstream.
