### ISSUE TITLE
node-red-contrib-actionflows runtime errors (Deprecated Events)

### ISSUE THREAD

**Issue by joelmoses** [hassio-addons/addon-node-red#875]
# Problem/Motivation

The node-red component "node-red-contrib-actionflows" was written prior to the availability of "flows:started" and uses an older method of flow setup that is no longer supported in NodeRED. This triggers runtime deprecation notices.

## Expected behavior

No warnings, no indications on flow initiation.

## Actual behavior

Debug panel display on deployment AND deprecation notice on Node RED startup with the node in the configuration:
`[warn] [RED.events] Deprecated use of "nodes-started" event`

## Steps to reproduce

1. Add a flow with the node from "node-red-contrib-actionflows" in use (an inject -> node -> debug flow is fine for this purpose.
2. Display the Debug window in the side pane.
3. Deploy.

## Proposed changes

Adopt version 2.0.4 with fix.

PR to fix this deprecated event use has been merged by the maintainer.
PR here: https://github.com/Steveorevo/node-red-contrib-actionflows/pull/15
Main git here: https://github.com/Steveorevo/node-red-contrib-actionflows

**Comment by frenck** [comment]
The upstream author needs to drop a release.
Currently, it's still on 2.0.3. If it's released, our bots will pick it up automatically.

![image](https://user-images.githubusercontent.com/195327/106717813-7d1cba80-6600-11eb-9e69-f1660e919eff.png)

**Comment by joelmoses** [comment]
2.0.4 has dropped. (Although I think you're already aware?)
https://flows.nodered.org/node/node-red-contrib-actionflows

**Comment by joelmoses** [comment]
Pull [885](https://github.com/hassio-addons/addon-node-red/pull/885 ) resolves this issue.
