### ISSUE TITLE
library debug logs not showing up

### ISSUE THREAD

**Issue by Hacksore** [hassio-addons/addon-node-red#879]
# Problem

Getting debug logs from my node-red library seems to not work.

## Expected behavior

Set `log_level: debug` in the `node-red` config, restart, and get my libraries debug output.

## Actual behavior

Nothing from my library debug logs are showing up.

![image](https://user-images.githubusercontent.com/996134/106392966-ea8ada00-63b9-11eb-9254-e9e921692d05.png)

---

I do see debug logs getting enabled from node-red itself but nothing comes back for my library. Typically outside of home assistant, I'll do something like this to debug them.

`LOG_LEVEL=debug node-red`

**Comment by Hacksore** [comment]
So I did some investigation in the code which might help provide more context here.

There is a startup service which calls `npm start`
https://github.com/hassio-addons/addon-node-red/blob/main/node-red/rootfs/etc/services.d/nodered/run#L15

Followed by the start script for the addon which starts the node-red server
https://github.com/hassio-addons/addon-node-red/blob/main/node-red/package.json#L10

I tried setting an env var in the HA `configuration.yaml` but it did not yield any success.
```yaml
environment:
  - LOG_LEVEL=debug
```

I did read on the [docs](https://developers.home-assistant.io/docs/add-ons/configuration/) that there is this config setting for an HA addon, however, I'm not fully sure how it could be used at runtime if you wanted to debug an external node-red flow addon.

Key | Type | Required | Description
-- | -- | -- | --
environment | dict | no | A dictionary of environment variable to run add-on.

**Comment by sinclairpaul** [comment]
You can set env variables in the settings.js file, an example is in the documentation for setting the Timezone.  Would that not solve the issue?

**Comment by Hacksore** [comment]
@sinclairpaul  Thanks a bunch, I am now able to see debug data!

![image](https://user-images.githubusercontent.com/996134/109825209-34582180-7bff-11eb-8189-f18cbab2386b.png)
