### ISSUE TITLE
Oops! Something went wrong.

### ISSUE THREAD

**Issue by vedatorkun** [hassio-addons/addon-node-red#88]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED v1.2.0
 Flow-based programming for the Internet of Things
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.13 / HA 0.83.3 / SU 140 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
FATAL: Setting a credential_secret is REQUIRED!
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

///////////////////////////////////////////////////////////////////////////////////////////////

{
  "log_level": "info",
  "credential_secret": "",
  "http_node": {
    "username": "1234",
    "password": "1234"
  },
  "http_static": {
    "username": "1234",
    "password": "1234"
  },
  "port": 1880,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": []
}

**Comment by tjorim** [comment]
"Be sure to check the log above, line by line, for hints."
So let's do that... 
"FATAL: Setting a credential_secret is REQUIRED!"
There we go... 

Step 3 of the installation instructions is pretty clear! https://github.com/hassio-addons/addon-node-red/blob/master/README.md#installation

**Comment by frenck** [comment]
Closing issue, please read the documentation. Thx! 👍
