### ISSUE TITLE
502 BAD Gateway

### ISSUE THREAD

**Issue by milandzuris** [hassio-addons/addon-node-red#894]
I updated HA and my Node Red stopped working, write it to me: 502 Bad Gateway

WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_nodered!

https://pastebin.com/p4m9UUvm

**Comment by sinclairpaul** [comment]
The error message in the log is quite descriptive, and states how to fix the problem.

Change the password for http_node.password to a more secure one.
