### ISSUE TITLE
Could not create cache folder

### ISSUE THREAD

**Issue by Aryankids** [hassio-addons/addon-node-red#896]
Just upgraded to the latest version of node-red addon and  got this: 

mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:57] FATAL: Could not create cache folder
 Add-on: 
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:57] FATAL: Could not create cache folder
 
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
 Add-on version: 
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
 You are running the latest version of this add-on.
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
 System:   ( / )
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
 Home Assistant Core: 
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
 Home Assistant Supervisor: 

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder
2021/02/10 17:23:58 invalid character '}' looking for beginning of value
[cont-init.d] nginx.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 

                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.

[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

/dev/shm/ does exist and it is fully accessible i.e. (chmod 777) but the problem persists, not only for this adds-on, but also for ssh & web terminal. 

some more info 

Operating System
Ubuntu 20.04 LTS
Docker version
19.03.12

Supervisor
Version
supervisor-2021.02.6
Newest Version
supervisor-2021.02.6

Core
Version
core-2021.2.2
Newest Version
core-2021.2.2

**Comment by frenck** [comment]
Please update the node-red add-on to the latest version

**Comment by Aryankids** [comment]
@frenck  appreciate the speedy reply, really do.  but I am on the latest of node-red (the same happens on ssh & web terminal) both on the latest and both

**Comment by Aryankids** [comment]
Not sure the cause of the error. restored a backup that was 2 days old. then re-upgrade again all my adds-on and this time everything went OK. I have no explanation as what went wrong but whilst I am on the latest on all my adds-on, the issue is gone. Thanks for your help

**Comment by Aryankids** [comment]
It seems that I have the very same issue on SSh & Web terminal, Grafana , InfluxDB  and node-red !! They are all on the latest (including Core and supervisor). Is there anything common amongst these four that causes the VERY same issue on all of them?

**Comment by frenck** [comment]
Please update @Aryankids.

`/usr/lib/bashio/cache.sh: line 62: basshio::exit.nok: command not found`, has been fixed around 6 months ago. (there is an `s` too much in `basshio::exit.nok` -> `bashio::exit.nok`.

**Comment by sinclairpaul** [comment]
Just to clarify the latest versions:

Node-Red -  v8.1.1
Grafana - v6.1.0
Influx - v4.0.3
SSH - v8.0.1

I would look at the supervisor log as to why you are not fetching the latest, I would have a guess its name resolution.

**Comment by Aryankids** [comment]
Thanks both

@frenck, you might have fixed it months back but it appeared in my supervisor during the last two weeks, not sure why  (could it be because I am running HA on ubuntu i.e. unsupported version)? 
 
@sinclairpaul  I can see all of those versions on my supervisor now, but as said they all appeared on my supervisor just during the last two weeks. As described above if I upgrade to the latest, the following issue 

mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder

stops the add on to load. Happy to provide more info

**Comment by sinclairpaul** [comment]
Sorry I'm not following, previously you stated you were on the latest, but the versions aren't.

Can you capture the start of the addon log (appreciate this may be challenging), also can you post the supervisor log?

**Comment by Aryankids** [comment]
@sinclairpaul my core and supervisor on the latest, I received the notification to upgrade these four add-ons through the supervisor, I did  and all of them crashed and stopped working due to this issue 

mkdir: can't create directory '/dev/shm/': No such file or directory
[17:23:58] FATAL: Could not create cache folder

rolled back to my snapshot created two weeks back, put the add-ons on versions mentioned above and realised the very same issue exists on the log file but as "Warning" and not "Fatal"

[23:20:54] WARNING: An error occurred while storing supervisor.info to cache
mkdir: cannot create directory ‘/dev/shm’: File exists

**They are all now functional on the previous versions** if I upgrade EITHER of THEM to the latest I get the following, which breaks the add-on (this is for ssh)


s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:06] FATAL: Could not create cache folder
 Add-on: 
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:06] FATAL: Could not create cache folder
 
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
 Add-on version: 
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
 You are running the latest version of this add-on.
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
 System:   ( / )
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
 Home Assistant Core: 
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
 Home Assistant Supervisor: 


 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.


[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
[cont-init.d] docker.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
mkdir: can't create directory '/dev/shm/': No such file or directory
[09:03:07] FATAL: Could not create cache folder
[cont-init.d] mosquitto.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 


                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.

[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.



and the supervisor log says: 

21-02-11 09:02:19 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-02-11 09:03:03 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image hassioaddons/ssh-amd64:7.8.0 to ghcr.io/hassio-addons/ssh/amd64:8.0.1
21-02-11 09:03:03 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/ssh/amd64 with tag 8.0.1.
21-02-11 09:03:04 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_a0d7b954_ssh application
21-02-11 09:03:04 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_a0d7b954_ssh application
21-02-11 09:03:04 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_ssh' successfully updated
21-02-11 09:03:04 INFO (SyncWorker_4) [supervisor.docker.interface] Cleanup images: ['hassioaddons/ssh-amd64:7.8.0']
21-02-11 09:03:06 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/ssh/amd64 with version 8.0.1

21-02-11 09:06:30 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_ssh application
21-02-11 09:06:30 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/ssh/amd64 with version 8.0.1

It seems the problem is in here, 

if ! bashio::fs.directory_exists "${__BASHIO_CACHE_DIR}"; then
       mkdir -p "${__BASHIO_CACHE_DIR}" \|\|
      bashio::exit.nok "Could not create cache folder"

or to be more precise here:

function bashio::fs.directory_exists() {
    local directory=${1}

    bashio::log.trace "${FUNCNAME[0]}:" "$@"

    if [[ -d "${directory}" ]]; then
        return "${__BASHIO_EXIT_OK}"
    fi

    return "${__BASHIO_EXIT_NOK}"
}

but it is not clear to me why that if return false when the directory exist:


amir@TheHost-wsl:/dev$ ls -la /dev/shm
lrwxrwxrwx 1 root root 8 Feb 10 23:10 /dev/shm -> /run/shm
amir@TheHost-wsl:/dev$

**Comment by frenck** [comment]
> wsl2

that system is not a concern to us.

**Comment by Aryankids** [comment]
@frenck understood but can we have that if amended to check for symlink? or that causes issues?

**Comment by frenck** [comment]
I'm not spending a single second on adding support for WSL2

**Comment by frenck** [comment]
Found the topic on the community around this.
DON'T RUN THIS STUFF IN WSL2. Really. Just don't.

Furthermore, it would be fair if you were straight up on that matter, as you have now wasted my time in looking into something that nobody should do or care about in the first place. Time I could have spent on things that do matter for a wider audience.

I will actively reject any contribution to making this WSL compatible.

**Comment by Aryankids** [comment]
@frenck  well, as one of your biggest supporter, admirer and follower (and someone who buys you coffee on an occasional basis) bit disappointed to see that you believe I wasted your time when there is no documentation out there to know which operating system is supported or unsupported. I was thinking that I am helping you to pinpoint the issue and help you to fix a script as clearly there are crazy people out there (like me) that are using WSL2 to run HA on NUCs. 
Despite the above, I remain as one of your biggest supporter, admirer and follower .....

**Comment by frenck** [comment]
>  I wasted your time when there is no documentation out there to know which operating system is supported or unsupported

There is actually. Double unsupported, as Ubuntu isn't supported and WSL neither.
It has been even formalized here: <https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#decision> and blogged about.

I appreciate people supporting me, but it doesn't buy privileges to build things for specific use cases.

**Comment by Aryankids** [comment]
Thanks for the pointer

**Comment by Aryankids** [comment]
If you are here to find a fix for the issue mentioned in the subject of this issue, in particular for Ubuntu on WLS2, I put together a detailed instruction  [here, https://community.home-assistant.io/t/guide-hass-io-on-windows-10-wsl2-no-more-vms/166298/52](url) which could help.

**Comment by Aryankids** [comment]
If you are here to find a fix for the issue mentioned in the subject of this issue, in particular for Ubuntu on WLS2, I put together a detailed instruction [https://community.home-assistant.io/t/guide-hass-io-on-windows-10-wsl2-no-more-vms/166298/52?u=aryankids](url) which could help.
