### ISSUE TITLE
Hassio addon-node-red

### ISSUE THREAD

**Issue by AlexKR1** [hassio-addons/addon-node-red#90]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by AlexKR1** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 


log file look like this but unable to  open nod-red from hassio

**Comment by tjorim** [comment]
It's simply not started up yet, give it some time (depends on your hardware).

**Comment by frenck** [comment]
Please use the issue template and provide full logs, since this is not all.

Closing issue, feel free to join or Discord in case you are in need for support OR please, create a proper issue with as much information as possible.
