### ISSUE TITLE
Access configuration Web UI from exposed port

### ISSUE THREAD

**Issue by M-Gregoire** [hassio-addons/addon-node-red#903]
Hello,

I have a working node-red instance running in Hassos. Node-red is exposed with port 1880 and has a configured user/password (`http_node` and `http_static`).

I can access https://IP:1880/endpoint/ui after the basic auth using the defined login.

However, I'm trying to access the node red configuration page (as presented in home assistant), but http://IP:1880/ gives me a login loop, I tried node-red, home assistant and default logins without success.

I found a post on the community showing local storage should be deleted for the host (via the Dev tools) but this didn't work.

I'm note sure whether this is a bug or is it expected usage not to be able to access node-red from outside home assistant ?

Thank you for any help you might provide.

**Comment by DaftHonk** [comment]
I can access https://IP:1880/endpoint/ui using the credentials defined in the nodered config under `http-node:`

To access http://IP:1880/ I need to use my HA username and password. I spent quite a bit of time scratching my head over this one, but in the end got it to work without any additional config. You can get the addon to reset the nginx config by adding `leave_front_door_open: true` to the config, restart addon, remove it, and restart again.
