### ISSUE TITLE
node-gyp build error when installing a node package from within the add-on environment

### ISSUE THREAD

**Issue by BrianDee67** [hassio-addons/addon-node-red#904]
# Problem/Motivation

cannot install any additional nodes to use in my flows. specifically I want to access the base I2c bus on Raspberry Pi 3B+ GPIO via 2 additional node palettes

## Expected behavior

Nodes to install correctly

## Actual behavior

install failed with node-gyp rebuild error:  reported in log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 8.1.1
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.9
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1158 (offset 627 lines).
up to date in 1.059s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:35:15] INFO: Starting Node-RED...
> addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
17 Feb 20:35:20 - [info] 
Welcome to Node-RED
===================
17 Feb 20:35:20 - [info] Node-RED version: v1.2.9
17 Feb 20:35:20 - [info] Node.js  version: v14.15.4
17 Feb 20:35:20 - [info] Linux 5.10.11-v7+ arm LE
17 Feb 20:35:21 - [info] Loading palette nodes
17 Feb 20:35:28 - [info] Dashboard version 2.27.0 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
17 Feb 20:35:29 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
17 Feb 20:35:29 - [info] Settings file  : /etc/node-red/config.js
17 Feb 20:35:29 - [info] Context store  : 'default' [module=memory]
17 Feb 20:35:29 - [info] User directory : /config/node-red/
17 Feb 20:35:29 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Feb 20:35:29 - [info] Flows file     : /config/node-red/flows.json
17 Feb 20:35:29 - [info] Starting flows
17 Feb 20:35:30 - [info] Started flows
17 Feb 20:35:30 - [info] Server now running at http://127.0.0.1:46836/
[20:35:30] INFO: Starting NGinx...
17 Feb 20:35:35 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Feb 20:35:35 - [info] [server:Home Assistant] Connected to http://supervisor/core
17 Feb 20:37:11 - [info] Installing module: node-red-contrib-i2c, version: 0.8.0
17 Feb 20:37:22 - [warn] Installation of module node-red-contrib-i2c failed:
17 Feb 20:37:22 - [warn] ------------------------------------------
17 Feb 20:37:22 - [warn] gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 5.10.11-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /config/node-red/node_modules/i2c-bus
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i2c-bus@5.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the i2c-bus@5.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-17T10_07_22_695Z-debug.log
17 Feb 20:37:22 - [warn] ------------------------------------------
17 Feb 20:37:22 - [error] Error: Install failed

## Steps to reproduce

install homeassistant-supervisor on Raspberry Pi 3B+
install and start Node-Red add-on
open Node-Red web-UI and select manage palette from menu
attempt to install node-red-contrib-i2c node

## Proposed changes
fix if it is a bug or provide clear install instructions if I am missing something

**Comment by frenck** [comment]
`gyp ERR! stack Error: not found: make`

Install make and other needed build tools, see the add-on manual.
If you don't know what this means, you probably should not go this path.
