### ISSUE TITLE
Hassio inputs undefined

### ISSUE THREAD

**Issue by danhajduk** [hassio-addons/addon-node-red#91]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please use the issue template, this is an empty issue.
