### ISSUE TITLE
Deploy fails when accessing HA through nginx reverse proxy

### ISSUE THREAD

**Issue by jyourstone** [hassio-addons/addon-node-red#910]
# Problem/Motivation

I'm running HA behind an nginx reverse proxy to be able to access it from anywhere. I'm exposing port 443 in nginx and forwarding it to 8443 locally. I've also installed certbot to manage SSL certificates from Let's Encrypt.

This has always worked, until recently. Now, when I try to deploy changes in Node Red, I get an internal server error.

## Expected behavior

When deploying changes in Node Red, they should be deployed.

## Actual behavior

When deploying changes, I get the following error message:

![image](https://user-images.githubusercontent.com/4037547/108595389-e2520900-737f-11eb-8da9-f0195e310add.png)

## Steps to reproduce

Access HA through a reverse proxy that forwards port 443 from the proxy to port 8443 that HA runs on.

## Additional info

When access Node Red locally directly, on IP:1880, everything works, I can deploy changes.

Since I have Node Red on auto update (I know, my mistake), I'm not sure when it stopped working. But probably not more than 2 weeks ago.

Running the following versions:
Add-on version: 8.1.2
System: Home Assistant OS 5.11  (amd64 / qemux86-64)
Home Assistant Core: 2021.2.3
Home Assistant Supervisor: 2021.02.11

**Comment by sinclairpaul** [comment]
I'm assuming that your reverse proxy is running Ubuntu?, as that is what is generating the 500, I would suggest looking at the nginx logs there.

**Comment by jyourstone** [comment]
Yeah it turns out it was a weird error with my proxy, sorry.
