### ISSUE TITLE
Node Red installation fails on Home Assistant OS

### ISSUE THREAD

**Issue by popescunsergiu** [hassio-addons/addon-node-red#914]
# Problem/Motivation

> Fail to install Node Red on Home Assistant Operating System, intel NUC 
> Node Red: 8.1.2
> HA: core-2021.2.3, supervisor-2021.02.11, Home Assistant OS 5.12

## Expected behavior

> Node Red should install

## Actual behavior

> [supervisor.docker.interface] Can't install ghcr.io/hassio-addons/node-red/amd64:8.1.2 -> 404 Client Error for http+docker://localhost/v1.40/images/ghcr.io/hassio-addons/node-red/amd64:8.1.2/json: Not Found ("no such image: ghcr.io/hassio-addons/node-red/amd64:8.1.2: No such image: ghcr.io/hassio-addons/node-red/amd64:8.1.2").

## Steps to reproduce

> Go to HA Add-on store
> Add Home Assistant Community Add-ons repo
> Install Node Red

**Comment by frenck** [comment]
The image exists 🤷 
And has over 27K downloads... <https://github.com/orgs/hassio-addons/packages/container/node-red%2Famd64/1217912>

Make sure your host can reach ghcr.io or maybe try running a `ha supervisor repair`

**Comment by popescunsergiu** [comment]
Thank you. `ha supervisor repair` worked. Dunno what happened but your suggestion is gold
