### ISSUE TITLE
Node Red Event States disconnected from home assistant

### ISSUE THREAD

**Issue by KonstantinaAndr** [hassio-addons/addon-node-red#915]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Unfortunately there are no details here, so it would be impossible to assist.
