### ISSUE TITLE
Node-RED 8.1.2 won't start after updating

### ISSUE THREAD

**Issue by capstan1** [hassio-addons/addon-node-red#918]
# Problem/Motivation
Node-RED won't start after updating it to 8.1.2. Tried twice with different Home Assistant versions. When rolling back to 8.1.1 everything works as expected.
_EDIT: found out that the exact same thing is happening for SSH & Web Terminal 8.0.3_
These are the errors in log:

```
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/00-banner.sh: Exec format error
[cont-init.d] 00-banner.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
s6-maximumtime: fatal: unable to spawn /var/run/s6/etc/cont-finish.d/99-message.sh: Exec format error
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

```

HA Versions:

- supervisor-2021.03.4
- core-2021.3.2
- Home Assistant OS 5.12

Hardware:

- RaspBerry 3B+ with an SSD attached (used datactl move)

**Comment by frenck** [comment]
>  Exec format error

This can happen if 64 bits mode is activated manually in the boot.txt, is that something you did?

**Comment by capstan1** [comment]
No, didn't do anything like this.

**Comment by frenck** [comment]
> Only changed some things in config.txt to make the conbee work.

What?

**Comment by capstan1** [comment]
I'm sorry, I have a RaspBee and added this to the end of config.txt
enable_uart=1
dtoverlay=pi3-disable-bt

**Comment by capstan1** [comment]
So, it did resolve by itself. Didn't change anything. Just waited these 3 weeks and tried again today without any problems.
