### ISSUE TITLE
HA warning: Insecure secrets in nodered

### ISSUE THREAD

**Issue by rotrials** [hassio-addons/addon-node-red#923]
Hello,

# Problem/Motivation

HA keep informing me that: "Insecure secrets in a0d7b954_nodered
The add-on a0d7b954_nodered uses secrets which are detected as not secure, see https://www.home-assistant.io/more-info/pwned-passwords for more information."
Remark: 
- no password for node-red was saved
- all my passwords are inside the secrets.yaml

## Expected behavior

No warning/notification repoted.

## Actual behavior

After updating the core to version 2021.3.2 (or HA, I don't remember) I keep getting this notification. Even if I disable the Node-red add-on the warning still appear in the "notification" area. 

## Steps to reproduce

Install the latest HA, Core, Supervisor and HACS, and add the node-red.

## Proposed changes

It was anounced that the latest release will make periodically some checked on the saved password. I have no idea why I get this warning.

My Node-Red confication is:

credential_secret: file
dark_mode: false
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: true
certfile: certificate.pem
keyfile: privkey.pem
require_ssl: true
system_packages: []
npm_packages: []
init_commands: []

If this is not an issue of node red and it's a configuration problem. But before the last updated I did not get this warning.

Thanks

**Comment by frenck** [comment]
This is a warning from Home Assistant, not the add-on. Please report your issue with Home Assistant.

Thanks 👍
