### ISSUE TITLE
Heads-Up: Sunevents node change may need manual changes by administrator

### ISSUE THREAD

**Issue by joelmoses** [hassio-addons/addon-node-red#925]
# Problem/Motivation

Sunevents 3.0 changes the behavior of the node to require initialization before it emits events. 

## Expected behavior

Prior to 3.0, the node would automatically emit events provided the lat/long was encoded into the node configuration. If this is present in the node after migration, the events will still emit properly BUT the node must be triggered to begin its event loop with an Inject node. 

## Actual behavior

If an older node configuration is migrated it will stop emitting events and an Inject node must be added to the configuration to begin the event loop. Also, when the event emits, it will emit on msg.payload.sunevent, not on msg.payload as it would previously.

## Steps to reproduce

1. On a pre v3.0 Sunevents node, configure the lat/long information on the node. Check the box to "make hours seem like minutes".
2. Add it to the configuration and attach a debug node to it. Deploy.
3. In the debug window, the Sunevents node will begin emitting events immediately.
4. Update the Sunevents node to v3.0. Deploy.
5. Note that the node now has a red status with an error of "No events scheduled". It has not been initiated with an Inject node. Events will no longer be emitting into the Debug window.
6. Add an inject node with a timestamp payload. Deploy.
7. Click on the Inject handle; the status should change to green with the next sunevent displayed.
8. Monitor the msg.payload object for the new payload location.

## Proposed changes

Document the change in behavior and note that it may affect existing policies that use the Sunevents node.

**Comment by joelmoses** [comment]
As noted in the Sunevents documentation, a node should not run its own internal event loop. The way the new node logic works is more in line with the way the Node Red team specifies a node should do.

**Comment by Elkropac** [comment]
Thanks for report. I was just searching, why are my night lights on all day.

I have set it up, so change in "sun.sun" triggers sunevents node, to recalculate events. I store it in HA helper and use it in flows.

There is also another change - `msg.payload` is now an object, not string with actual value. You have to use `msg.payload.sunevent` to get the text

**Comment by joelmoses** [comment]
Totally forgot that one - the move from msg.payload to msg.payload.sunevent :) Yeah, that requires administrator changes as well.
