### ISSUE TITLE
After restoring from snapshot Node-Red fails to start

### ISSUE THREAD

**Issue by casperklein** [hassio-addons/addon-node-red#93]
# Problem/Motivation

> I have two Hassio installations. One in a VM (for staging) and one running on a RPI3. When taking a Hassio snapshot in the VM and restoring to the rpi, node-red fails to start:

`
INFO (SyncWorker_12) [hassio.docker.interface] Clean hassioaddons/node-red-aarch64 Docker application
ERROR (SyncWorker_12) [hassio.docker] Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyS1": no such file or directory")
`
## Expected behavior

> node-red should properly start after restoring

## Actual behavior

> node-red is not able to start after restoring

## Proposed changes

> To fix that, I have to reinstall the node-red addon on the pi after each restore.

**Comment by frenck** [comment]
This is an Hass.io issue, and not something the add-on can influence (it has not even started...).

Please file an issue with the Hass.io GitHub repository.
