### ISSUE TITLE
Nodes between 00:00 and 00:59 passed the time as 24:xx breaking the logic

### ISSUE THREAD

**Issue by alfonsolsl** [hassio-addons/addon-node-red#932]
# Problem/Motivation
![IMG_20210316_003543](https://user-images.githubusercontent.com/6255385/111323162-9b31fd80-8637-11eb-90ea-49cc37f6d4ce.jpg)

To be more specific this is a very simple logic, the function block only set a flow variable, doesn't do anything with the payload or date.

The timezones are the same, I do not use daylight saving time in this country. The Rpi when NR is running had the right time.

The recorder on HA saves the triggers at the correct time 00:xx

The trigger on the screen was at 00:34 but NR rendered to 24:34. The time range block failed to identify if there inside or outside the range. At 1am NR rendered 01:00 and the logic worked again.

## Expected behavior

Trigger node render the payload time at 00:xx

## Actual behavior

The trigger node and other nodes passed the time like 24:xx

## Steps to reproduce

Set a trigger node wait to midnight and trigger the block, see the payload time.

**Comment by frenck** [comment]
Hi there,

Thanks for reporting an issue, however, add-ons wrap existing applications. The error you are describing seems to originate with the Home Assistant node for Node-RED. This is not maintained or developed by the add-on itself (merely wrapped). Please file an issue upstream 👍 

Thanks!

../Frenck
