### ISSUE TITLE
Not loading properly Home assistant

### ISSUE THREAD

**Issue by treforparr** [hassio-addons/addon-node-red#936]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is an empty issue. Feel free to open a new one, that actually has content. Thanks 👍
