### ISSUE TITLE
Connection cycle

### ISSUE THREAD

**Issue by th00mas88** [hassio-addons/addon-node-red#942]
# Problem/Motivation

I had this issue about a week ago where Nodered went in to a connection cycle 
I played about , removed the nodered folder, uninstalled, rebooted, several times and then it just "clicked" in and worked. its bee fine until yesterday when the issue struck again.

## Expected behavior

Nodered to run.

## Actual behavior

nodes linked in to Homeassistant (state entitys) dont connect 

## Steps to reproduce

No idea - not been able to link why - current install is bare, nothing special 

## config 

credential_secret: althesecretwords
dark_mode: false
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: false
system_packages: []
npm_packages: []
init_commands: []

## log 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 8.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.3.4
 Home Assistant Supervisor: 2021.03.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1159 (offset 628 lines).
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 1.229s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:29:03] INFO: Starting Node-RED...
> addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
19 Mar 16:29:06 - [info] 
Welcome to Node-RED
===================
19 Mar 16:29:06 - [info] Node-RED version: v1.2.9
19 Mar 16:29:06 - [info] Node.js  version: v14.16.0
19 Mar 16:29:06 - [info] Linux 5.4.83-v8 arm64 LE
19 Mar 16:29:07 - [info] Loading palette nodes
19 Mar 16:29:12 - [info] Dashboard version 2.28.1 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
19 Mar 16:29:12 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
19 Mar 16:29:13 - [info] Settings file  : /etc/node-red/config.js
19 Mar 16:29:13 - [info] Context store  : 'default' [module=memory]
19 Mar 16:29:13 - [info] User directory : /config/node-red/
19 Mar 16:29:13 - [warn] Projects disabled : editorTheme.projects.enabled=false
19 Mar 16:29:13 - [info] Flows file     : /config/node-red/flows.json
19 Mar 16:29:13 - [info] Starting flows
19 Mar 16:29:13 - [info] Started flows
19 Mar 16:29:13 - [info] Server now running at http://127.0.0.1:46836/
[16:29:13] INFO: Starting NGinx...
19 Mar 16:29:18 - [info] [server:Home Assistant] Connecting to http://supervisor/core
19 Mar 16:29:18 - [info] [server:Home Assistant] Connected to http://supervisor/core
19 Mar 16:29:18 - [info] [server:Home Assistant] Connection closed to http://supervisor/core

---- then a persistant cycle of 

 [info] [server:Home Assistant] Connecting to http://supervisor/core
 [info] [server:Home Assistant] Connected to http://supervisor/core
 [info] [server:Home Assistant] Connection closed to http://supervisor/core

**Comment by frenck** [comment]
Nothing in this log is weird.

**Comment by th00mas88** [comment]
> Nothing in this log is weird.

Exactly. But the cycle is happening and was not happening before.

**Comment by th00mas88** [comment]
So I solved in the end with Unticking the add-on button. Getting a token and using the direct IP of homeassistant.  I have no idea what happened.or why. 

![IMG_20210322_131517.jpg](https://user-images.githubusercontent.com/67537157/111988461-cffaf480-8b10-11eb-96f3-06c93662f50b.jpg)
