### ISSUE TITLE
No configuration created for fresh install of Node-RED

### ISSUE THREAD

**Issue by polds** [hassio-addons/addon-node-red#943]
# Problem/Motivation

I have done a fresh install of Node-RED through the add-on store, however no configuration was created and there were no prompts to create any credentials.

As a result, I see `502: Bad Gateway` when attempting to access the web ui.

Where should this configuration file exist?

## Expected behavior

I think:

- Install add-on
- Receive prompt for credentials
- OR: have a configuration directory and file be written some place

## Actual behavior

- No prompt, no configuration files written
- WebUI returns a 502

I see this in the logs (crashlooping):

```
21-03-19 20:57:46 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_nodered!
21-03-19 20:57:46 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_a0d7b954_nodered application
21-03-19 20:57:46 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/amd64 with version 8.2.0
21-03-19 20:58:16 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_nodered!
```

## Steps to reproduce

Core: core-2021.3.4
Supervisor: supervisor-2021.03.6

- Install Node-RED
- Be presented with 502.

**Comment by frenck** [comment]
As per installation instruction of the add-on, check the logs...

**Comment by polds** [comment]
The logs just say:

```
21-03-19 20:57:46 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_nodered!
21-03-19 20:57:46 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_a0d7b954_nodered application
21-03-19 20:57:46 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/amd64 with version 8.2.0
21-03-19 20:58:16 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_nodered!
```

And repeat endlessly.

**Comment by frenck** [comment]
Those are not the add-on logs...

**Comment by sinclairpaul** [comment]
Click Configuration, the node-red secret and ssl options are set there

![image](https://user-images.githubusercontent.com/24625998/111855070-0eb66200-88f9-11eb-807c-cb6a16c9a788.png)

**Comment by polds** [comment]
This is what I was missing. Thank you.
