### ISSUE TITLE
Call Service Node does not accept Mustache Templates

### ISSUE THREAD

**Issue by jkyselak** [hassio-addons/addon-node-red#960]
Even though the Node Help specifies that the "Service" field in the Call Service Node does accept Mustache Templates, using them results in an "Unknown Service" message.

![image](https://user-images.githubusercontent.com/77690105/113862319-3ec58800-9776-11eb-88e3-d61280567578.png)

**Comment by sinclairpaul** [comment]
The documentation for those nodes can be found at https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/mustache-templates.html

It's preinstalled with the addon, so any issues would need to be logged at https://github.com/zachowj/node-red-contrib-home-assistant-websocket
