### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'nodered'

### ISSUE THREAD

**Issue by ve6rah** [hassio-addons/addon-node-red#961]
# Problem/Motivation

> As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'nodered'

## Expected behavior

> needs to be updated for new versions

## Actual behavior

> error message appears in logs on home assistant reboot

## Steps to reproduce

> have the node-red add-on installed and restart home assistant. review logs.

## Proposed changes

> update the manifest file.

**Comment by frenck** [comment]
This is an add-on, not an integration.

**Comment by ve6rah** [comment]
Well I opened this bug in both the integration and the add-on, both sides closed it immediately. But neither side actually fixed anything. Good thing I plan on migrating away from node red, because it's obviously going to stop working for me in 2 months either way.

**Comment by frenck** [comment]
> But neither side actually fixed anything.

Sorry to hear that, with all the goodwill in the world, I cannot fix anything on this end. As this is an add-on, not an integration. Add-ons are versioned since day 1.

**Comment by jimmyz5150** [comment]
frenck,
I have this as well... I think I get what ur saying... Is it something that will effect node red and your add-on work?... If not ignore, it will fix itself? I'm a noob level 2.5 :)

**Comment by sinclairpaul** [comment]
The issue is with the custom component not the addon, https://github.com/zachowj/hass-node-red/issues/61

Please update the custom component via HACS or manually.
