### ISSUE TITLE
Cannot install NodeRed on latest HA (using HA Blue)

### ISSUE THREAD

**Issue by popescunsergiu** [hassio-addons/addon-node-red#964]
# Problem/Motivation

> Cannot install NodeRed on latest HA

## Expected behavior

> (What you expected to happen)

## Actual behavior

> 21-04-08 17:34:40 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/node-red/aarch64 with tag 8.2.1.
21-04-08 17:35:01 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/hassio-addons/node-red/aarch64:8.2.1 -> 404 Client Error for http+docker://localhost/v1.40/images/ghcr.io/hassio-addons/node-red/aarch64:8.2.1/json: Not Found ("no such image: ghcr.io/hassio-addons/node-red/aarch64:8.2.1: No such image: ghcr.io/hassio-addons/node-red/aarch64:8.2.1").
I can Install other addons

## Steps to reproduce

> I am using a HA Blue. Enable Advanced mode and try to install NodeRed
ha supervisor repair does not work

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
It definitely exists:

<https://github.com/orgs/hassio-addons/packages/container/node-red%2Faarch64/1729826>

Docker can throw 404 when disk space is running low, make sure you have enough of those bit & bytes available.

**Comment by popescunsergiu** [comment]
This is a brand new HA Blue. I just unpacked it

**Comment by frenck** [comment]
I honestly don't know what to answer 🤷

**Comment by popescunsergiu** [comment]
Just double-checked and I cannot install any of the "Home Assistant Community Add-ons" on the latest HA. :(

**Comment by popescunsergiu** [comment]
And checking further I get the following 302 redirect: 
http://ghcr.io/hassio-addons/portainer/amd64:1.4.0
to
https://github.com/-/hassio-addons/packages/container/package/portainer%2Famd64

And on this page:
there is no: ghcr.io/hassio-addons/portainer/amd64:1.4.0
Only: ghcr.io/hassio-addons/portainer/amd64:9e0a7be

**Comment by frenck** [comment]
There is: <https://github.com/orgs/hassio-addons/packages/container/portainer%2Famd64/877871>

**Comment by popescunsergiu** [comment]
Not reproducing anymore
