### ISSUE TITLE
Configuration options cannot be saved [works again]

### ISSUE THREAD

**Issue by vicfalls** [hassio-addons/addon-node-red#971]
I'm not able to save the configuration options on my NodeRED installation. By pressing the save button it always goes back to original settings. Does anyone know why?
This is the only suspect error message I get, since I have installed NodeRED Add-on:

21-04-09 18:03:13 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62827 ssl:default [Connect call failed ('172.30.32.1', 62827)]

Thanks
Vic

**Comment by vicfalls** [comment]
Works again, I deinstalled NodeRED and rebooted the HASS and used new credential.

**Comment by sinclairpaul** [comment]
As you are working I will close.
