### ISSUE TITLE
Documentation minor update

### ISSUE THREAD

**Issue by JohnnyDN** [hassio-addons/addon-node-red#973]
Please update the doc where it is described that secrets.yaml could be used in the addon configuration as the credential_secret.

Currently the documentation says:
_Note: This option support secrets, e.g., !secret red_secret._

Please update to:
_Note: This option support secrets, e.g., '!secret red_secret'_

Because !secret is used without quotes elsewhere, this is confusing.

**Comment by sinclairpaul** [comment]
Click this:

![image](https://user-images.githubusercontent.com/24625998/114288948-d0b4e580-9a41-11eb-9fae-a9df3a8bb06c.png)

Edit the file and submit a PR 😉

**Comment by frenck** [comment]
This note should be removed. It used to be an add-on feature, however, it no longer is.

**Comment by JohnnyDN** [comment]
Hello, thanks for your reply.

Franck, I have just updated both hassio OS and core and this feature is
still working.
Is this no longer intended then?


Il giorno dom 11 apr 2021 alle ore 09:03 Franck Nijhof <
***@***.***> ha scritto:

**Comment by frenck** [comment]
Yes, the feature is working, but now part of Home Assistant itself (not an add-on feature). Secrets work in all fields nowadays.
