### ISSUE TITLE
HA restart slowed down/hampered by reconnect effort of node-red HA addon

### ISSUE THREAD

**Issue by vincentnl** [hassio-addons/addon-node-red#98]
# Problem/Motivation
Node-red addon HA quickly and repeatedly tries to reestablish connection to node-red, for each separate node, which slows down Home Assistant (HA) in startup.

## Expected behavior
HA to (re)start up quickly (5 seconds)

## Actual behavior

HA starts up slowly (2 minutes)

## Steps to reproduce
- Home assistant on a raspberry PI
- Node-red on a windows PC

1. Have multiple HA nodes trigger-state or server-events
2. Restart HA

## Proposed changes

After a failed re-establishment of connection to the Home-Assistant by the node, built in a pause of a few seconds, so HA has time to start up.

## Log of reconnect tries

25 Dec 15:50:13 - [error] [trigger-state:Daylight] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:13 - [error] [trigger-state:Daylight] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:OwnTracks home] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Vincent Home] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Guests] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Home] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Work] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Home] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Work] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:AtHome] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:InBed] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [server-events:All] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:90540130.64233] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:16ab2fc6.65339] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [server-events:All] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Frontdoor] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Alarm] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:Terrasdeur] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:16 - [error] [trigger-state:InBed] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:AtHome] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:WC on] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:Badkamer on switch] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:Stekker on] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:WC movement] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:Badkamer movement] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:AtHome] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:InBed] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:Daylight] connect ECONNREFUSED 192.168.1.100:8123
25 Dec 15:50:17 - [error] [trigger-state:Daylight] connect ECONNREFUSED 192.168.1.100:8123

**Comment by tjorim** [comment]
Hi, thanks for taking the time to report this issue.
However, this is out of scope for the add-on itself.

You should report this to the home-assistant-websocket node itself over here: https://github.com/zachowj/node-red-contrib-home-assistant-websocket

**Comment by frenck** [comment]
Closing issue.
