### ISSUE TITLE
New theme option breaks Node-RED projects

### ISSUE THREAD

**Issue by crnh** [hassio-addons/addon-node-red#992]
# Problem/Motivation

I am using the projects feature for version control in Node-RED. After updating the Node-RED add-on to version 9.0.0, my project did not load; instead, the flows in my old `flows.json` were loaded. Besides, the whole projects functionality was unavailable.

## Expected behavior

After updating, the projects feature keeps functioning and the correct flow file is loaded.

## Actual behavior

The projects feature is not enabled and instead of the project flows, the flows from `flows.json` are loaded.

## Steps to reproduce

1. Enable the projects feature in `settings.js` by setting `editorTheme.projects` to `true`:
  ```js
  module.exports = {
    ...
    editorTheme: {
      projects: {
        enabled: true
      }
    }
  }
  ```

2. Restart the add-on;
3. The projects UI is not present.

## Proposed changes

Previously, [`config.js`](https://github.com/hassio-addons/addon-node-red/blob/main/node-red/rootfs/etc/node-red/config.js) added a property to `config.editorTheme` in order to set the theme:

```js
config.editorTheme.page = {
  css: "/opt/node_modules/@node-red-contrib-themes/midnight-red/theme.css",
};
```

Currently, `config.editorTheme` is overwritten, disabling any customization using `settings.js`:

```js
config.editorTheme = {
  theme: options.theme,
};
```

If the code above is changed to only set the `theme` property of `config.editorTheme` instead of overwriting it, this issue would be solved.

**Comment by bonanitech** [comment]
Pushing a fix in a few minutes.

**Comment by mik-at** [comment]
Is there any workaround until this gets fixed?

**Comment by frenck** [comment]
There is a PR open, will be testing/reviewing that and release a patch asap @mik-at 👍 

../Frenck 🚂

**Comment by mik-at** [comment]
> There is a PR open, will be testing/reviewing that and release a patch asap @mik-at 👍 
> 
> 
> 
> ../Frenck 🚂 

Thanks a lot Frenck, you are doing a great job!

Also what I noticed but not sure yet if it is related to this issue: Custom nodes get deleted every restart and have to be reinstalled. Never happened in any update/restart prior to this version.

**Comment by frenck** [comment]
@mik-at This has always been the case, and documented as such.

**Comment by PhilippCh** [comment]
Sorry to reopen an old issue, but have you already released the patch by any chance? I can't see any updates for the node-red addon on my HA instance.

**Comment by crnh** [comment]
You can check that yourself in the [releases](https://github.com/hassio-addons/addon-node-red/releases) section of this repo. 9.0.0 is the newest, so no, the patch has not yet been released.
