### ISSUE TITLE
Documentation improvement: credentialSecret, persistant storage

### ISSUE THREAD

**Issue by hklages** [hassio-addons/addon-node-red#994]
# Problem/Motivation

Just striving to improve documentation.

### First addition related to the usage of projects

> 2. Set a credential_secret, which is used to encrypt sensitive data. This is just a "password", which you should save in a secondary location.

Add: 
If you have projects enabled then it will use the credentialSecret you have configured for the project, not the one above.

[source knolleary](https://discourse.nodered.org/t/solved-credentialsecret-flows-stopped-as-the-credentials-could-not-be-decrypted/19363/2)

### Second addition related to global variables 

Add: 

7. To make the global / flow / node variables persistent you have to add the following to settings. js
```// Configure contextStorage such as global variables
  contextStorage: {
    default: {
      module:"localfilesystem",
      config: {
      }
    }
  },
```

**Comment by frenck** [comment]
I'm not sure how that is related to this add-on. The config can be adjusted to ones likings, but I'm not going to re-create / re-write the Node-RED documentation.

**Comment by hklages** [comment]
OK understand - the second point is well documented in Node-RED. 
Regarding the first point it is more to correct a (partly) wrong statement.  The mentioned credential_secret is not at all used in project based Node-RED installations.

**Comment by hklages** [comment]
Thanks!
